module.exports = [
  { commonWord: 'mace', intruderWord: 'qen', category: 'animals', difficulty: 'easy' },
  { commonWord: 'elefant', intruderWord: 'gjirafë', category: 'animals', difficulty: 'easy' },
  { commonWord: 'pinguin', intruderWord: 'delfin', category: 'animals', difficulty: 'medium' },
  { commonWord: 'flutur', intruderWord: 'libellulë', category: 'animals', difficulty: 'medium' },
  { commonWord: 'oktapor', intruderWord: 'kalamar', category: 'animals', difficulty: 'hard' },
  { commonWord: 'pica', intruderWord: 'hamburger', category: 'food', difficulty: 'easy' },
  { commonWord: 'mollë', intruderWord: 'portokall', category: 'food', difficulty: 'easy' },
  { commonWord: 'sushi', intruderWord: 'ramen', category: 'food', difficulty: 'medium' },
  { commonWord: 'croissant', intruderWord: 'bagel', category: 'food', difficulty: 'medium' },
  { commonWord: 'trufë', intruderWord: 'kaviar', category: 'food', difficulty: 'hard' },
  { commonWord: 'blu', intruderWord: 'gjelbër', category: 'colors', difficulty: 'easy' },
  { commonWord: 'kuq', intruderWord: 'rozë', category: 'colors', difficulty: 'easy' },
  { commonWord: 'vjollcë', intruderWord: 'violet', category: 'colors', difficulty: 'medium' },
  { commonWord: 'turkuaz', intruderWord: 'blu jeshil', category: 'colors', difficulty: 'medium' },
  { commonWord: 'magenta', intruderWord: 'fuchsia', category: 'colors', difficulty: 'hard' },
  { commonWord: 'i lumtur', intruderWord: 'i trishtuar', category: 'emotions', difficulty: 'easy' },
  { commonWord: 'i zemëruar', intruderWord: 'i furishëm', category: 'emotions', difficulty: 'medium' },
  { commonWord: 'i emocionuar', intruderWord: 'i entuziastë', category: 'emotions', difficulty: 'medium' },
  { commonWord: 'i ankthuar', intruderWord: 'i shqetësuar', category: 'emotions', difficulty: 'hard' },
  { commonWord: 'ekstatik', intruderWord: 'i ngazëllyer', category: 'emotions', difficulty: 'hard' },
  { commonWord: 'karrige', intruderWord: 'tavolinë', category: 'objects', difficulty: 'easy' },
  { commonWord: 'telefon', intruderWord: 'kompjuter', category: 'objects', difficulty: 'easy' },
  { commonWord: 'llambë', intruderWord: 'qiri', category: 'objects', difficulty: 'medium' },
  { commonWord: 'pasqyrë', intruderWord: 'dritare', category: 'objects', difficulty: 'medium' },
  { commonWord: 'skulpturë', intruderWord: 'pikturë', category: 'objects', difficulty: 'hard' },
  { commonWord: 'pemë', intruderWord: 'lule', category: 'nature', difficulty: 'easy' },
  { commonWord: 'mal', intruderWord: 'kodër', category: 'nature', difficulty: 'easy' },
  { commonWord: 'oqean', intruderWord: 'liqen', category: 'nature', difficulty: 'medium' },
  { commonWord: 'pyll', intruderWord: 'xhuxh', category: 'nature', difficulty: 'medium' },
  { commonWord: 'vullkan', intruderWord: 'gayser', category: 'nature', difficulty: 'hard' },
  { commonWord: 'futboll', intruderWord: 'futboll amerikan', category: 'sports', difficulty: 'easy' },
  { commonWord: 'basketboll', intruderWord: 'volejboll', category: 'sports', difficulty: 'easy' },
  { commonWord: 'tenis', intruderWord: 'badminton', category: 'sports', difficulty: 'medium' },
  { commonWord: 'not', intruderWord: 'zhytje', category: 'sports', difficulty: 'medium' },
  { commonWord: 'curling', intruderWord: 'bob', category: 'sports', difficulty: 'hard' },
  { commonWord: 'mjek', intruderWord: 'infermier', category: 'professions', difficulty: 'easy' },
  { commonWord: 'mësues', intruderWord: 'profesor', category: 'professions', difficulty: 'medium' },
  { commonWord: 'kuzhinier', intruderWord: 'furrtar', category: 'professions', difficulty: 'medium' },
  { commonWord: 'arkitekt', intruderWord: 'inxhinier', category: 'professions', difficulty: 'hard' },
  { commonWord: 'astronaut', intruderWord: 'pilot', category: 'professions', difficulty: 'hard' },
  { commonWord: 'restorant', intruderWord: 'kafe', category: 'places', difficulty: 'easy' },
  { commonWord: 'shkollë', intruderWord: 'universitet', category: 'places', difficulty: 'medium' },
  { commonWord: 'muze', intruderWord: 'galeri', category: 'places', difficulty: 'medium' },
  { commonWord: 'bibliotekë', intruderWord: 'librari', category: 'places', difficulty: 'medium' },
  { commonWord: 'kështjellë', intruderWord: 'pallat', category: 'places', difficulty: 'hard' },
  { commonWord: 'lexim', intruderWord: 'shkrim', category: 'activities', difficulty: 'easy' },
  { commonWord: 'gatim', intruderWord: 'pjekje', category: 'activities', difficulty: 'medium' },
  { commonWord: 'vallëzim', intruderWord: 'këngë', category: 'activities', difficulty: 'medium' },
  { commonWord: 'pikturë', intruderWord: 'vizatim', category: 'activities', difficulty: 'medium' },
  { commonWord: 'meditim', intruderWord: 'joga', category: 'activities', difficulty: 'hard' },
  { commonWord: 'luani', intruderWord: 'tigri', category: 'animals', difficulty: 'easy' },
  { commonWord: 'kali', intruderWord: 'zebra', category: 'animals', difficulty: 'easy' },
  { commonWord: 'ariu', intruderWord: 'ujku', category: 'animals', difficulty: 'easy' },
  { commonWord: 'lepuri', intruderWord: 'lepur i egër', category: 'animals', difficulty: 'easy' },
  { commonWord: 'zogu', intruderWord: 'lakuriq nate', category: 'animals', difficulty: 'easy' },
  { commonWord: 'peshku', intruderWord: 'peshkaqen', category: 'animals', difficulty: 'easy' },
  { commonWord: 'gjarpri', intruderWord: 'hardhuca', category: 'animals', difficulty: 'medium' },
  { commonWord: 'breshka', intruderWord: 'breshkë toke', category: 'animals', difficulty: 'medium' },
  { commonWord: 'bufi', intruderWord: 'shqiponja', category: 'animals', difficulty: 'medium' },
  { commonWord: 'krokodili', intruderWord: 'aligator', category: 'animals', difficulty: 'medium' },
  { commonWord: 'balena', intruderWord: 'delfini', category: 'animals', difficulty: 'medium' },
  { commonWord: 'gaforre', intruderWord: 'karavidhe', category: 'animals', difficulty: 'medium' },
  { commonWord: 'bleta', intruderWord: 'grerëz', category: 'animals', difficulty: 'medium' },
  { commonWord: 'milingu', intruderWord: 'termiti', category: 'animals', difficulty: 'medium' },
  { commonWord: 'hamster', intruderWord: 'gerbil', category: 'animals', difficulty: 'hard' },
  { commonWord: 'bukë', intruderWord: 'simite', category: 'food', difficulty: 'easy' },
  { commonWord: 'qumësht', intruderWord: 'krem', category: 'food', difficulty: 'easy' },
  { commonWord: 'oriz', intruderWord: 'makarona', category: 'food', difficulty: 'easy' },
  { commonWord: 'djathë', intruderWord: 'kos', category: 'food', difficulty: 'easy' },
  { commonWord: 'pule', intruderWord: 'gjel deti', category: 'food', difficulty: 'easy' },
  { commonWord: 'karotë', intruderWord: 'pastinakë', category: 'food', difficulty: 'easy' },
  { commonWord: 'domate', intruderWord: 'specë', category: 'food', difficulty: 'easy' },
  { commonWord: 'tortë', intruderWord: 'byrek', category: 'food', difficulty: 'easy' },
  { commonWord: 'kafe', intruderWord: 'çaj', category: 'food', difficulty: 'easy' },
  { commonWord: 'supë', intruderWord: 'gjellë', category: 'food', difficulty: 'medium' },
  { commonWord: 'sallatë', intruderWord: 'sallatë lakër', category: 'food', difficulty: 'medium' },
  { commonWord: 'omëletë', intruderWord: 'frittata', category: 'food', difficulty: 'medium' },
  { commonWord: 'muffin', intruderWord: 'cupcake', category: 'food', difficulty: 'medium' },
  { commonWord: 'brokoli', intruderWord: 'lulelakër', category: 'food', difficulty: 'medium' },
  { commonWord: 'trangull', intruderWord: 'kungull', category: 'food', difficulty: 'medium' },
  { commonWord: 'arrë', intruderWord: 'pekán', category: 'food', difficulty: 'medium' },
  { commonWord: 'mjalte', intruderWord: 'sirup', category: 'food', difficulty: 'medium' },
  { commonWord: 'uthull', intruderWord: 'limon', category: 'food', difficulty: 'hard' },
  { commonWord: 'verdhë', intruderWord: 'artë', category: 'colors', difficulty: 'easy' },
  { commonWord: 'zi', intruderWord: 'gri', category: 'colors', difficulty: 'easy' },
  { commonWord: 'bardhë', intruderWord: 'krem', category: 'colors', difficulty: 'easy' },
  { commonWord: 'portokalli', intruderWord: 'qelibar', category: 'colors', difficulty: 'medium' },
  { commonWord: 'kafe e errët', intruderWord: 'bojë kafe', category: 'colors', difficulty: 'medium' },
  { commonWord: 'karmin', intruderWord: 'skuq', category: 'colors', difficulty: 'medium' },
  { commonWord: 'blu deti', intruderWord: 'indigo', category: 'colors', difficulty: 'medium' },
  { commonWord: 'bordeaux', intruderWord: 'burgundy', category: 'colors', difficulty: 'hard' },
  { commonWord: 'korale', intruderWord: 'salmón', category: 'colors', difficulty: 'hard' },
  { commonWord: 'qetë', intruderWord: 'paqësor', category: 'emotions', difficulty: 'easy' },
  { commonWord: 'i lodhur', intruderWord: 'i rraskapitur', category: 'emotions', difficulty: 'easy' },
  { commonWord: 'i frikësuar', intruderWord: 'i tmerruar', category: 'emotions', difficulty: 'easy' },
  { commonWord: 'i befasuar', intruderWord: 'i tronditur', category: 'emotions', difficulty: 'medium' },
  { commonWord: 'krenar', intruderWord: 'arrogant', category: 'emotions', difficulty: 'medium' },
  { commonWord: 'xheloz', intruderWord: 'zili', category: 'emotions', difficulty: 'medium' },
  { commonWord: 'kurioz', intruderWord: 'pyetës', category: 'emotions', difficulty: 'medium' },
  { commonWord: 'mirënjohës', intruderWord: 'falenderues', category: 'emotions', difficulty: 'medium' },
  { commonWord: 'nervoz', intruderWord: 'i shqetësuar', category: 'emotions', difficulty: 'medium' },
  { commonWord: 'i sigurt', intruderWord: 'mendjemadh', category: 'emotions', difficulty: 'hard' },
  { commonWord: 'libër', intruderWord: 'revistë', category: 'objects', difficulty: 'easy' },
  { commonWord: 'çelës', intruderWord: 'kyç', category: 'objects', difficulty: 'easy' },
  { commonWord: 'stilolaps', intruderWord: 'laps', category: 'objects', difficulty: 'easy' },
  { commonWord: 'filxhan', intruderWord: 'kupë', category: 'objects', difficulty: 'easy' },
  { commonWord: 'derë', intruderWord: 'portë', category: 'objects', difficulty: 'easy' },
  { commonWord: 'çantë', intruderWord: 'çantë shpine', category: 'objects', difficulty: 'easy' },
  { commonWord: 'orë', intruderWord: 'orë muri', category: 'objects', difficulty: 'easy' },
  { commonWord: 'syze', intruderWord: 'syze mbrojtëse', category: 'objects', difficulty: 'medium' },
  { commonWord: 'ombrellë', intruderWord: 'ombrellë dielli', category: 'objects', difficulty: 'medium' },
  { commonWord: 'jastëk', intruderWord: 'jastëk i vogël', category: 'objects', difficulty: 'medium' },
  { commonWord: 'batanije', intruderWord: 'jorgan', category: 'objects', difficulty: 'medium' },
  { commonWord: 'divan', intruderWord: 'kolltuk', category: 'objects', difficulty: 'medium' },
  { commonWord: 'dollap', intruderWord: 'gardërobë', category: 'objects', difficulty: 'medium' },
  { commonWord: 'vazo', intruderWord: 'urnë', category: 'objects', difficulty: 'hard' },
  { commonWord: 'diell', intruderWord: 'hënë', category: 'nature', difficulty: 'easy' },
  { commonWord: 'shi', intruderWord: 'borë', category: 'nature', difficulty: 'easy' },
  { commonWord: 'lumë', intruderWord: 'përrua', category: 'nature', difficulty: 'easy' },
  { commonWord: 'plazh', intruderWord: 'breg', category: 'nature', difficulty: 'easy' },
  { commonWord: 're', intruderWord: 'mjegull', category: 'nature', difficulty: 'easy' },
  { commonWord: 'bar', intruderWord: 'myshk', category: 'nature', difficulty: 'easy' },
  { commonWord: 'shkëmb', intruderWord: 'gur i madh', category: 'nature', difficulty: 'medium' },
  { commonWord: 'ishull', intruderWord: 'gadishull', category: 'nature', difficulty: 'medium' },
  { commonWord: 'ujëvarë', intruderWord: 'rrëzë', category: 'nature', difficulty: 'medium' },
  { commonWord: 'kanion', intruderWord: 'grykë', category: 'nature', difficulty: 'medium' },
  { commonWord: 'shkretëtirë', intruderWord: 'oaz', category: 'nature', difficulty: 'medium' },
  { commonWord: 'livadh', intruderWord: 'rrafshinë', category: 'nature', difficulty: 'medium' },
  { commonWord: 'shkrepinë', intruderWord: 'brinjë', category: 'nature', difficulty: 'hard' },
  { commonWord: 'golf', intruderWord: 'polo', category: 'sports', difficulty: 'easy' },
  { commonWord: 'vrapim', intruderWord: 'jogging', category: 'sports', difficulty: 'easy' },
  { commonWord: 'boks', intruderWord: 'mundje', category: 'sports', difficulty: 'easy' },
  { commonWord: 'çikliizëm', intruderWord: 'patinazh', category: 'sports', difficulty: 'easy' },
  { commonWord: 'ski', intruderWord: 'snowboard', category: 'sports', difficulty: 'medium' },
  { commonWord: 'lundrim', intruderWord: 'kajak', category: 'sports', difficulty: 'medium' },
  { commonWord: 'gjueti me hark', intruderWord: 'skërmim', category: 'sports', difficulty: 'medium' },
  { commonWord: 'gjimnastikë', intruderWord: 'akrobaci', category: 'sports', difficulty: 'medium' },
  { commonWord: 'maratonë', intruderWord: 'sprint', category: 'sports', difficulty: 'medium' },
  { commonWord: 'kriket', intruderWord: 'bejzbol', category: 'sports', difficulty: 'hard' },
  { commonWord: 'avokat', intruderWord: 'gjykatës', category: 'professions', difficulty: 'easy' },
  { commonWord: 'shofer', intruderWord: 'kalorës', category: 'professions', difficulty: 'easy' },
  { commonWord: 'shkrimtar', intruderWord: 'autor', category: 'professions', difficulty: 'easy' },
  { commonWord: 'artist', intruderWord: 'piktor', category: 'professions', difficulty: 'easy' },
  { commonWord: 'këngëtar', intruderWord: 'muzikant', category: 'professions', difficulty: 'easy' },
  { commonWord: 'aktor', intruderWord: 'aktore', category: 'professions', difficulty: 'medium' },
  { commonWord: 'gazetar', intruderWord: 'reporter', category: 'professions', difficulty: 'medium' },
  { commonWord: 'fotograf', intruderWord: 'kameraman', category: 'professions', difficulty: 'medium' },
  { commonWord: 'kontabilist', intruderWord: 'auditor', category: 'professions', difficulty: 'medium' },
  { commonWord: 'mekanik', intruderWord: 'teknik', category: 'professions', difficulty: 'medium' },
  { commonWord: 'bibliotekar', intruderWord: 'arkivitar', category: 'professions', difficulty: 'hard' },
  { commonWord: 'spital', intruderWord: 'klinikë', category: 'places', difficulty: 'easy' },
  { commonWord: 'park', intruderWord: 'kopsht', category: 'places', difficulty: 'easy' },
  { commonWord: 'dyqan', intruderWord: 'treg', category: 'places', difficulty: 'easy' },
  { commonWord: 'hotel', intruderWord: 'motel', category: 'places', difficulty: 'easy' },
  { commonWord: 'rrugë', intruderWord: 'avenue', category: 'places', difficulty: 'easy' },
  { commonWord: 'urë', intruderWord: 'tunel', category: 'places', difficulty: 'medium' },
  { commonWord: 'aeroport', intruderWord: 'stacion', category: 'places', difficulty: 'medium' },
  { commonWord: 'stadium', intruderWord: 'arena', category: 'places', difficulty: 'medium' },
  { commonWord: 'teatër', intruderWord: 'kinema', category: 'places', difficulty: 'medium' },
  { commonWord: 'furrë buke', intruderWord: 'pasticeri', category: 'places', difficulty: 'medium' },
  { commonWord: 'depo', intruderWord: 'magazinë', category: 'places', difficulty: 'hard' },
  { commonWord: 'ecje', intruderWord: 'peizazh', category: 'activities', difficulty: 'easy' },
  { commonWord: 'gjumë', intruderWord: 'dremitje', category: 'activities', difficulty: 'easy' },
  { commonWord: 'ngrenë', intruderWord: 'pirje', category: 'activities', difficulty: 'easy' },
  { commonWord: 'shikim', intruderWord: 'dëgjim', category: 'activities', difficulty: 'easy' },
  { commonWord: 'not', intruderWord: 'lundrim', category: 'activities', difficulty: 'easy' },
  { commonWord: 'blerje', intruderWord: 'shfletoj', category: 'activities', difficulty: 'medium' },
  { commonWord: 'udhëtim', intruderWord: 'endacak', category: 'activities', difficulty: 'medium' },
  { commonWord: 'mësim', intruderWord: 'përsëritje', category: 'activities', difficulty: 'medium' },
  { commonWord: 'pastrim', intruderWord: 'rregullim', category: 'activities', difficulty: 'medium' },
  { commonWord: 'ngas', intruderWord: 'hipi', category: 'activities', difficulty: 'medium' },
  { commonWord: 'kopshtari', intruderWord: 'mbjellje', category: 'activities', difficulty: 'medium' },
  { commonWord: 'thurje', intruderWord: 'qepje', category: 'activities', difficulty: 'hard' },
  { commonWord: 'dhelpër', intruderWord: 'kojotë', category: 'animals', difficulty: 'medium' },
  { commonWord: 'papagall', intruderWord: 'daullje', category: 'animals', difficulty: 'medium' },
  { commonWord: 'dre', intruderWord: 'dre i madh', category: 'animals', difficulty: 'easy' },
  { commonWord: 'bretkocë', intruderWord: 'thithëlopë', category: 'animals', difficulty: 'medium' },
  { commonWord: 'fokë', intruderWord: 'luan deti', category: 'animals', difficulty: 'hard' },
  { commonWord: 'majmun', intruderWord: 'gorilë', category: 'animals', difficulty: 'easy' },
  { commonWord: 'derr', intruderWord: 'derr i egër', category: 'animals', difficulty: 'easy' },
  { commonWord: 'rosë', intruderWord: 'patë', category: 'animals', difficulty: 'easy' },
  { commonWord: 'dele', intruderWord: 'dhi', category: 'animals', difficulty: 'easy' },
  { commonWord: 'panda', intruderWord: 'koala', category: 'animals', difficulty: 'medium' },
  { commonWord: 'rrush', intruderWord: 'boronicë', category: 'food', difficulty: 'easy' },
  { commonWord: 'luleshtrydhe', intruderWord: 'mjedër', category: 'food', difficulty: 'medium' },
  { commonWord: 'kikirk', intruderWord: 'bajame', category: 'food', difficulty: 'easy' },
  { commonWord: 'gjalp', intruderWord: 'margarinë', category: 'food', difficulty: 'medium' },
  { commonWord: 'reçel', intruderWord: 'marmelatë', category: 'food', difficulty: 'medium' },
  { commonWord: 'çokollatë', intruderWord: 'karamel', category: 'food', difficulty: 'easy' },
  { commonWord: 'vafer', intruderWord: 'petull', category: 'food', difficulty: 'easy' },
  { commonWord: 'limon', intruderWord: 'lime', category: 'food', difficulty: 'easy' },
  { commonWord: 'hudhër', intruderWord: 'qepë', category: 'food', difficulty: 'easy' },
  { commonWord: 'kanellë', intruderWord: 'arrë myshku', category: 'food', difficulty: 'hard' },
  { commonWord: 'makinë', intruderWord: 'kamion', category: 'vehicles', difficulty: 'easy' },
  { commonWord: 'biçikletë', intruderWord: 'skuter', category: 'vehicles', difficulty: 'easy' },
  { commonWord: 'tren', intruderWord: 'tramvaj', category: 'vehicles', difficulty: 'medium' },
  { commonWord: 'varkë', intruderWord: 'anije', category: 'vehicles', difficulty: 'easy' },
  { commonWord: 'avion', intruderWord: 'helikopter', category: 'vehicles', difficulty: 'easy' },
  { commonWord: 'motor', intruderWord: 'moped', category: 'vehicles', difficulty: 'medium' },
  { commonWord: 'autobus', intruderWord: 'furgon', category: 'vehicles', difficulty: 'easy' },
  { commonWord: 'nëndetëse', intruderWord: 'traget', category: 'vehicles', difficulty: 'hard' },
  { commonWord: 'raketë', intruderWord: 'satelit', category: 'vehicles', difficulty: 'hard' },
  { commonWord: 'kanoe', intruderWord: 'varkë me vela', category: 'vehicles', difficulty: 'medium' },
  { commonWord: 'këmishë', intruderWord: 'bluzë', category: 'clothing', difficulty: 'easy' },
  { commonWord: 'pantallona', intruderWord: 'pantallona të shkurtra', category: 'clothing', difficulty: 'easy' },
  { commonWord: 'kapelë', intruderWord: 'kapuç', category: 'clothing', difficulty: 'easy' },
  { commonWord: 'çizme', intruderWord: 'këpucë', category: 'clothing', difficulty: 'easy' },
  { commonWord: 'xhaketë', intruderWord: 'pallto', category: 'clothing', difficulty: 'easy' },
  { commonWord: 'shall', intruderWord: 'shami', category: 'clothing', difficulty: 'medium' },
  { commonWord: 'doreza', intruderWord: 'doreza pa gishta', category: 'clothing', difficulty: 'medium' },
  { commonWord: 'fustan', intruderWord: 'fund', category: 'clothing', difficulty: 'easy' },
  { commonWord: 'triko', intruderWord: 'hudi', category: 'clothing', difficulty: 'easy' },
  { commonWord: 'sandale', intruderWord: 'shapka plazhi', category: 'clothing', difficulty: 'medium' },
  { commonWord: 'bubullimë', intruderWord: 'vetëtimë', category: 'weather', difficulty: 'easy' },
  { commonWord: 'stuhi', intruderWord: 'uragan', category: 'weather', difficulty: 'medium' },
  { commonWord: 'fllad', intruderWord: 'erë', category: 'weather', difficulty: 'easy' },
  { commonWord: 'ngricë', intruderWord: 'akull', category: 'weather', difficulty: 'easy' },
  { commonWord: 'breshër', intruderWord: 'borë me shi', category: 'weather', difficulty: 'hard' },
  { commonWord: 'thatësirë', intruderWord: 'përmbytje', category: 'weather', difficulty: 'medium' },
  { commonWord: 'mjegull', intruderWord: 'mjergull', category: 'weather', difficulty: 'hard' },
  { commonWord: 'dorë', intruderWord: 'këmbë', category: 'body', difficulty: 'easy' },
  { commonWord: 'sy', intruderWord: 'vesh', category: 'body', difficulty: 'easy' },
  { commonWord: 'gisht', intruderWord: 'gisht i këmbës', category: 'body', difficulty: 'easy' },
  { commonWord: 'gju', intruderWord: 'bërryl', category: 'body', difficulty: 'easy' },
  { commonWord: 'sup', intruderWord: 'ijë', category: 'body', difficulty: 'medium' },
  { commonWord: 'kyç i dorës', intruderWord: 'kyç i këmbës', category: 'body', difficulty: 'medium' },
  { commonWord: 'kitarë', intruderWord: 'violinë', category: 'music', difficulty: 'easy' },
  { commonWord: 'piano', intruderWord: 'organo', category: 'music', difficulty: 'medium' },
  { commonWord: 'daulle', intruderWord: 'dajre', category: 'music', difficulty: 'easy' },
  { commonWord: 'flautë', intruderWord: 'klarinetë', category: 'music', difficulty: 'medium' },
  { commonWord: 'trombë', intruderWord: 'trombon', category: 'music', difficulty: 'hard' },
  { commonWord: 'harpë', intruderWord: 'çelo', category: 'music', difficulty: 'hard' },
  { commonWord: 'laptop', intruderWord: 'tablet', category: 'technology', difficulty: 'easy' },
  { commonWord: 'maus', intruderWord: 'tastierë', category: 'technology', difficulty: 'easy' },
  { commonWord: 'printer', intruderWord: 'skaner', category: 'technology', difficulty: 'easy' },
  { commonWord: 'kamerë', intruderWord: 'projektor', category: 'technology', difficulty: 'medium' },
  { commonWord: 'altoparlant', intruderWord: 'mikrofon', category: 'technology', difficulty: 'easy' },
  { commonWord: 'karikues', intruderWord: 'kabllo', category: 'technology', difficulty: 'medium' },
  { commonWord: 'fajkua', intruderWord: 'skifteri', category: 'animals', difficulty: 'medium' },
  { commonWord: 'pallua', intruderWord: 'flamingo', category: 'animals', difficulty: 'medium' },
  { commonWord: 'iriq', intruderWord: 'landër', category: 'animals', difficulty: 'hard' },
  { commonWord: 'deve', intruderWord: 'lamë', category: 'animals', difficulty: 'medium' },
  { commonWord: 'gepard', intruderWord: 'leopard', category: 'animals', difficulty: 'hard' },
  { commonWord: 'mjellmë', intruderWord: 'lejlek', category: 'animals', difficulty: 'medium' },
  { commonWord: 'ketër', intruderWord: 'ketër me vija', category: 'animals', difficulty: 'hard' },
  { commonWord: 'vemje', intruderWord: 'krimb', category: 'animals', difficulty: 'medium' },
  { commonWord: 'pjeshkë', intruderWord: 'kajsi', category: 'food', difficulty: 'medium' },
  { commonWord: 'pjepër', intruderWord: 'shalqi', category: 'food', difficulty: 'easy' },
  { commonWord: 'misër', intruderWord: 'grurë', category: 'food', difficulty: 'easy' },
  { commonWord: 'beikon', intruderWord: 'proshutë', category: 'food', difficulty: 'easy' },
  { commonWord: 'gjevrek', intruderWord: 'krispa', category: 'food', difficulty: 'medium' },
  { commonWord: 'ulliri', intruderWord: 'turshi', category: 'food', difficulty: 'medium' },
  { commonWord: 'xhenxhefil', intruderWord: 'shafran', category: 'food', difficulty: 'hard' },
  { commonWord: 'borzilok', intruderWord: 'rigon', category: 'food', difficulty: 'hard' },
  { commonWord: 'kumbull', intruderWord: 'qershi', category: 'food', difficulty: 'easy' },
  { commonWord: 'salmon', intruderWord: 'troftë', category: 'food', difficulty: 'medium' },
  { commonWord: 'gërshërë', intruderWord: 'thikë', category: 'objects', difficulty: 'easy' },
  { commonWord: 'furçë', intruderWord: 'krehër', category: 'objects', difficulty: 'easy' },
  { commonWord: 'shishe', intruderWord: 'kavanoz', category: 'objects', difficulty: 'easy' },
  { commonWord: 'litar', intruderWord: 'zinxhir', category: 'objects', difficulty: 'medium' },
  { commonWord: 'gjilpërë', intruderWord: 'karficë', category: 'objects', difficulty: 'medium' },
  { commonWord: 'zile', intruderWord: 'fishkëllimë', category: 'objects', difficulty: 'medium' },
  { commonWord: 'valixhe', intruderWord: 'arkë', category: 'objects', difficulty: 'medium' },
  { commonWord: 'vizore', intruderWord: 'kompas', category: 'objects', difficulty: 'medium' },
  { commonWord: 'pellg', intruderWord: 'pellg i vogël', category: 'nature', difficulty: 'easy' },
  { commonWord: 'shpellë', intruderWord: 'grotë', category: 'nature', difficulty: 'medium' },
  { commonWord: 'akullnajë', intruderWord: 'ajsberg', category: 'nature', difficulty: 'hard' },
  { commonWord: 'moçal', intruderWord: 'kënetë', category: 'nature', difficulty: 'hard' },
  { commonWord: 'luginë', intruderWord: 'humnerë', category: 'nature', difficulty: 'medium' },
  { commonWord: 'agim', intruderWord: 'perëndim', category: 'nature', difficulty: 'easy' },
  { commonWord: 'hokej', intruderWord: 'lakros', category: 'sports', difficulty: 'medium' },
  { commonWord: 'surfim', intruderWord: 'surfim me erë', category: 'sports', difficulty: 'medium' },
  { commonWord: 'xhudo', intruderWord: 'karate', category: 'sports', difficulty: 'medium' },
  { commonWord: 'ngjitje', intruderWord: 'ngjitje shkëmbinjsh', category: 'sports', difficulty: 'medium' },
  { commonWord: 'shigjetat', intruderWord: 'bilardo', category: 'sports', difficulty: 'medium' },
  { commonWord: 'skejtbord', intruderWord: 'patinazh', category: 'sports', difficulty: 'medium' },
  { commonWord: 'dentist', intruderWord: 'kirurg', category: 'professions', difficulty: 'medium' },
  { commonWord: 'fermer', intruderWord: 'blegtori', category: 'professions', difficulty: 'medium' },
  { commonWord: 'hidraulik', intruderWord: 'elektricist', category: 'professions', difficulty: 'medium' },
  { commonWord: 'zjarrfikës', intruderWord: 'paramedik', category: 'professions', difficulty: 'medium' },
  { commonWord: 'detektiv', intruderWord: 'spiun', category: 'professions', difficulty: 'hard' },
  { commonWord: 'marangoz', intruderWord: 'zdrukthar', category: 'professions', difficulty: 'hard' },
  { commonWord: 'kishë', intruderWord: 'xhami', category: 'places', difficulty: 'easy' },
  { commonWord: 'kopshti zoologjik', intruderWord: 'akuarium', category: 'places', difficulty: 'easy' },
  { commonWord: 'kullë', intruderWord: 'qiellartës', category: 'places', difficulty: 'medium' },
  { commonWord: 'port', intruderWord: 'skele', category: 'places', difficulty: 'medium' },
  { commonWord: 'fanar', intruderWord: 'kullë vrojtimi', category: 'places', difficulty: 'hard' },
  { commonWord: 'ambasadë', intruderWord: 'konsullatë', category: 'places', difficulty: 'hard' },
  { commonWord: 'peshkim', intruderWord: 'gjueti', category: 'activities', difficulty: 'easy' },
  { commonWord: 'kamping', intruderWord: 'piknik', category: 'activities', difficulty: 'medium' },
  { commonWord: 'skulpturë', intruderWord: 'gdhëndje', category: 'activities', difficulty: 'hard' },
  { commonWord: 'fotografi', intruderWord: 'filmim', category: 'activities', difficulty: 'medium' },
  { commonWord: 'ushtrim', intruderWord: 'shtendosje', category: 'activities', difficulty: 'easy' },
  { commonWord: 'vullnetarizëm', intruderWord: 'dhurim', category: 'activities', difficulty: 'medium' },
  { commonWord: 'taksi', intruderWord: 'limuzynë', category: 'vehicles', difficulty: 'medium' },
  { commonWord: 'ambulancë', intruderWord: 'zjarrfikëse', category: 'vehicles', difficulty: 'easy' },
  { commonWord: 'traktor', intruderWord: 'ekskavator', category: 'vehicles', difficulty: 'medium' },
  { commonWord: 'teleferik', intruderWord: 'gondolë', category: 'vehicles', difficulty: 'hard' },
  { commonWord: 'jaht', intruderWord: 'anije kroçiere', category: 'vehicles', difficulty: 'medium' },
  { commonWord: 'kravatë', intruderWord: 'flutur', category: 'clothing', difficulty: 'easy' },
  { commonWord: 'çorape', intruderWord: 'çorape të gjata', category: 'clothing', difficulty: 'easy' },
  { commonWord: 'pizhame', intruderWord: 'përparëse', category: 'clothing', difficulty: 'easy' },
  { commonWord: 'rrip', intruderWord: 'mbajtëse', category: 'clothing', difficulty: 'medium' },
  { commonWord: 'jelek', intruderWord: 'xhemper me kopsa', category: 'clothing', difficulty: 'medium' },
  { commonWord: 'tornado', intruderWord: 'ciklon', category: 'weather', difficulty: 'hard' },
  { commonWord: 'vesë', intruderWord: 'rrebesh', category: 'weather', difficulty: 'medium' },
  { commonWord: 'diell', intruderWord: 'hije', category: 'weather', difficulty: 'easy' },
  { commonWord: 'stuhi bore', intruderWord: 'breshëri bore', category: 'weather', difficulty: 'hard' },
  { commonWord: 'qafë', intruderWord: 'mjekër', category: 'body', difficulty: 'easy' },
  { commonWord: 'gjoks', intruderWord: 'shpinë', category: 'body', difficulty: 'easy' },
  { commonWord: 'gishti i madh', intruderWord: 'gishti i vogël', category: 'body', difficulty: 'easy' },
  { commonWord: 'ballë', intruderWord: 'tëmth', category: 'body', difficulty: 'medium' },
  { commonWord: 'pëllëmbë', intruderWord: 'thembër', category: 'body', difficulty: 'medium' },
  { commonWord: 'banxho', intruderWord: 'ukulele', category: 'music', difficulty: 'medium' },
  { commonWord: 'saksofon', intruderWord: 'oboe', category: 'music', difficulty: 'hard' },
  { commonWord: 'fizarmonikë', intruderWord: 'harmonikë', category: 'music', difficulty: 'medium' },
  { commonWord: 'cimbal', intruderWord: 'gong', category: 'music', difficulty: 'medium' },
  { commonWord: 'ksilofon', intruderWord: 'marimba', category: 'music', difficulty: 'hard' },
  { commonWord: 'ruter', intruderWord: 'modem', category: 'technology', difficulty: 'medium' },
  { commonWord: 'kufje', intruderWord: 'kufje veshi', category: 'technology', difficulty: 'easy' },
  { commonWord: 'monitor', intruderWord: 'televizor', category: 'technology', difficulty: 'easy' },
  { commonWord: 'dron', intruderWord: 'robot', category: 'technology', difficulty: 'medium' },
  { commonWord: 'bateri', intruderWord: 'gjenerator', category: 'technology', difficulty: 'medium' }
];
