module.exports = [
  { commonWord: 'kedi', intruderWord: 'köpek', category: 'animals', difficulty: 'easy' },
  { commonWord: 'fil', intruderWord: 'zürafa', category: 'animals', difficulty: 'easy' },
  { commonWord: 'penguen', intruderWord: 'yunus', category: 'animals', difficulty: 'medium' },
  { commonWord: 'kelebek', intruderWord: 'yusufçuk', category: 'animals', difficulty: 'medium' },
  { commonWord: 'ahtapot', intruderWord: 'mürekkepbalığı', category: 'animals', difficulty: 'hard' },
  { commonWord: 'pizza', intruderWord: 'burger', category: 'food', difficulty: 'easy' },
  { commonWord: 'elma', intruderWord: 'portakal', category: 'food', difficulty: 'easy' },
  { commonWord: 'suşi', intruderWord: 'ramen', category: 'food', difficulty: 'medium' },
  { commonWord: 'krokan', intruderWord: 'simit', category: 'food', difficulty: 'medium' },
  { commonWord: 'trüf', intruderWord: 'havyar', category: 'food', difficulty: 'hard' },
  { commonWord: 'mavi', intruderWord: 'yeşil', category: 'colors', difficulty: 'easy' },
  { commonWord: 'kırmızı', intruderWord: 'pembe', category: 'colors', difficulty: 'easy' },
  { commonWord: 'mor', intruderWord: 'eflatun', category: 'colors', difficulty: 'medium' },
  { commonWord: 'turkuaz', intruderWord: 'teal', category: 'colors', difficulty: 'medium' },
  { commonWord: 'macenta', intruderWord: 'fuşya', category: 'colors', difficulty: 'hard' },
  { commonWord: 'mutlu', intruderWord: 'üzgün', category: 'emotions', difficulty: 'easy' },
  { commonWord: 'kızgın', intruderWord: 'öfkeli', category: 'emotions', difficulty: 'medium' },
  { commonWord: 'heyecanlı', intruderWord: 'coşkulu', category: 'emotions', difficulty: 'medium' },
  { commonWord: 'endişeli', intruderWord: 'kaygılı', category: 'emotions', difficulty: 'hard' },
  { commonWord: 'çok mutlu', intruderWord: 'uçan', category: 'emotions', difficulty: 'hard' },
  { commonWord: 'sandalye', intruderWord: 'masa', category: 'objects', difficulty: 'easy' },
  { commonWord: 'telefon', intruderWord: 'bilgisayar', category: 'objects', difficulty: 'easy' },
  { commonWord: 'lamba', intruderWord: 'mum', category: 'objects', difficulty: 'medium' },
  { commonWord: 'ayna', intruderWord: 'pencere', category: 'objects', difficulty: 'medium' },
  { commonWord: 'heykel', intruderWord: 'tablo', category: 'objects', difficulty: 'hard' },
  { commonWord: 'ağaç', intruderWord: 'çiçek', category: 'nature', difficulty: 'easy' },
  { commonWord: 'dağ', intruderWord: 'tepe', category: 'nature', difficulty: 'easy' },
  { commonWord: 'okyanus', intruderWord: 'göl', category: 'nature', difficulty: 'medium' },
  { commonWord: 'orman', intruderWord: 'cangıl', category: 'nature', difficulty: 'medium' },
  { commonWord: 'yanardağ', intruderWord: 'gayzer', category: 'nature', difficulty: 'hard' },
  { commonWord: 'futbol', intruderWord: 'amerikan futbolu', category: 'sports', difficulty: 'easy' },
  { commonWord: 'basketbol', intruderWord: 'voleybol', category: 'sports', difficulty: 'easy' },
  { commonWord: 'tenis', intruderWord: 'badminton', category: 'sports', difficulty: 'medium' },
  { commonWord: 'yüzme', intruderWord: 'dalış', category: 'sports', difficulty: 'medium' },
  { commonWord: 'körling', intruderWord: 'kızak', category: 'sports', difficulty: 'hard' },
  { commonWord: 'doktor', intruderWord: 'hemşire', category: 'professions', difficulty: 'easy' },
  { commonWord: 'öğretmen', intruderWord: 'profesör', category: 'professions', difficulty: 'medium' },
  { commonWord: 'şef', intruderWord: 'fırıncı', category: 'professions', difficulty: 'medium' },
  { commonWord: 'mimar', intruderWord: 'mühendis', category: 'professions', difficulty: 'hard' },
  { commonWord: 'astronot', intruderWord: 'pilot', category: 'professions', difficulty: 'hard' },
  { commonWord: 'restoran', intruderWord: 'kafe', category: 'places', difficulty: 'easy' },
  { commonWord: 'okul', intruderWord: 'üniversite', category: 'places', difficulty: 'medium' },
  { commonWord: 'müze', intruderWord: 'galeri', category: 'places', difficulty: 'medium' },
  { commonWord: 'kütüphane', intruderWord: 'kitapçı', category: 'places', difficulty: 'medium' },
  { commonWord: 'kale', intruderWord: 'saray', category: 'places', difficulty: 'hard' },
  { commonWord: 'okumak', intruderWord: 'yazmak', category: 'activities', difficulty: 'easy' },
  { commonWord: 'yemek yapmak', intruderWord: 'fırında pişirmek', category: 'activities', difficulty: 'medium' },
  { commonWord: 'dans etmek', intruderWord: 'şarkı söylemek', category: 'activities', difficulty: 'medium' },
  { commonWord: 'resim yapmak', intruderWord: 'çizim yapmak', category: 'activities', difficulty: 'medium' },
  { commonWord: 'meditasyon', intruderWord: 'yoga', category: 'activities', difficulty: 'hard' },
  { commonWord: 'aslan', intruderWord: 'kaplan', category: 'animals', difficulty: 'easy' },
  { commonWord: 'at', intruderWord: 'zebra', category: 'animals', difficulty: 'easy' },
  { commonWord: 'ayı', intruderWord: 'kurt', category: 'animals', difficulty: 'easy' },
  { commonWord: 'tavşan', intruderWord: 'yaban tavşanı', category: 'animals', difficulty: 'easy' },
  { commonWord: 'kuş', intruderWord: 'yarasa', category: 'animals', difficulty: 'easy' },
  { commonWord: 'balık', intruderWord: 'köpekbalığı', category: 'animals', difficulty: 'easy' },
  { commonWord: 'yılan', intruderWord: 'kertenkele', category: 'animals', difficulty: 'medium' },
  { commonWord: 'kaplumbağa', intruderWord: 'kara kaplumbağası', category: 'animals', difficulty: 'medium' },
  { commonWord: 'baykuş', intruderWord: 'kartal', category: 'animals', difficulty: 'medium' },
  { commonWord: 'timsah', intruderWord: 'aligator', category: 'animals', difficulty: 'medium' },
  { commonWord: 'balina', intruderWord: 'yunus', category: 'animals', difficulty: 'medium' },
  { commonWord: 'yengeç', intruderWord: 'ıstakoz', category: 'animals', difficulty: 'medium' },
  { commonWord: 'arı', intruderWord: 'eşekarısı', category: 'animals', difficulty: 'medium' },
  { commonWord: 'karınca', intruderWord: 'termit', category: 'animals', difficulty: 'medium' },
  { commonWord: 'hamster', intruderWord: 'gerbil', category: 'animals', difficulty: 'hard' },
  { commonWord: 'ekmek', intruderWord: 'roka', category: 'food', difficulty: 'easy' },
  { commonWord: 'süt', intruderWord: 'krema', category: 'food', difficulty: 'easy' },
  { commonWord: 'pilav', intruderWord: 'makarna', category: 'food', difficulty: 'easy' },
  { commonWord: 'peynir', intruderWord: 'yoğurt', category: 'food', difficulty: 'easy' },
  { commonWord: 'tavuk', intruderWord: 'hindi', category: 'food', difficulty: 'easy' },
  { commonWord: 'havuç', intruderWord: 'yaban havucu', category: 'food', difficulty: 'easy' },
  { commonWord: 'domates', intruderWord: 'biber', category: 'food', difficulty: 'easy' },
  { commonWord: 'pasta', intruderWord: 'börek', category: 'food', difficulty: 'easy' },
  { commonWord: 'kahve', intruderWord: 'çay', category: 'food', difficulty: 'easy' },
  { commonWord: 'çorba', intruderWord: 'güveç', category: 'food', difficulty: 'medium' },
  { commonWord: 'salata', intruderWord: 'lahana salatası', category: 'food', difficulty: 'medium' },
  { commonWord: 'omlet', intruderWord: 'frittata', category: 'food', difficulty: 'medium' },
  { commonWord: 'muffin', intruderWord: 'cupcake', category: 'food', difficulty: 'medium' },
  { commonWord: 'brokoli', intruderWord: 'karnabahar', category: 'food', difficulty: 'medium' },
  { commonWord: 'salatalık', intruderWord: 'kabak', category: 'food', difficulty: 'medium' },
  { commonWord: 'ceviz', intruderWord: 'pekán', category: 'food', difficulty: 'medium' },
  { commonWord: 'bal', intruderWord: 'şurup', category: 'food', difficulty: 'medium' },
  { commonWord: 'sirke', intruderWord: 'limon', category: 'food', difficulty: 'hard' },
  { commonWord: 'sarı', intruderWord: 'altın', category: 'colors', difficulty: 'easy' },
  { commonWord: 'siyah', intruderWord: 'gri', category: 'colors', difficulty: 'easy' },
  { commonWord: 'beyaz', intruderWord: 'krem', category: 'colors', difficulty: 'easy' },
  { commonWord: 'turuncu', intruderWord: 'kehribar', category: 'colors', difficulty: 'medium' },
  { commonWord: 'kahverengi', intruderWord: 'ten rengi', category: 'colors', difficulty: 'medium' },
  { commonWord: 'kırmızı', intruderWord: 'al', category: 'colors', difficulty: 'medium' },
  { commonWord: 'lacivert', intruderWord: 'çivit', category: 'colors', difficulty: 'medium' },
  { commonWord: 'bordo', intruderWord: 'burgonya', category: 'colors', difficulty: 'hard' },
  { commonWord: 'mercan', intruderWord: 'somon', category: 'colors', difficulty: 'hard' },
  { commonWord: 'sakin', intruderWord: 'huzurlu', category: 'emotions', difficulty: 'easy' },
  { commonWord: 'yorgun', intruderWord: 'bitkin', category: 'emotions', difficulty: 'easy' },
  { commonWord: 'korkmuş', intruderWord: 'dehşete düşmüş', category: 'emotions', difficulty: 'easy' },
  { commonWord: 'şaşkın', intruderWord: 'şokta', category: 'emotions', difficulty: 'medium' },
  { commonWord: 'gururlu', intruderWord: 'kibirli', category: 'emotions', difficulty: 'medium' },
  { commonWord: 'kıskanç', intruderWord: 'haset', category: 'emotions', difficulty: 'medium' },
  { commonWord: 'meraklı', intruderWord: 'sorgulayıcı', category: 'emotions', difficulty: 'medium' },
  { commonWord: 'minnettar', intruderWord: 'müteşekkir', category: 'emotions', difficulty: 'medium' },
  { commonWord: 'gergin', intruderWord: 'sinirli', category: 'emotions', difficulty: 'medium' },
  { commonWord: 'kendinden emin', intruderWord: 'kendini beğenmiş', category: 'emotions', difficulty: 'hard' },
  { commonWord: 'kitap', intruderWord: 'dergi', category: 'objects', difficulty: 'easy' },
  { commonWord: 'anahtar', intruderWord: 'kilit', category: 'objects', difficulty: 'easy' },
  { commonWord: 'kalem', intruderWord: 'kurşun kalem', category: 'objects', difficulty: 'easy' },
  { commonWord: 'fincan', intruderWord: 'kupa', category: 'objects', difficulty: 'easy' },
  { commonWord: 'kapı', intruderWord: 'geçit', category: 'objects', difficulty: 'easy' },
  { commonWord: 'çanta', intruderWord: 'sırt çantası', category: 'objects', difficulty: 'easy' },
  { commonWord: 'saat', intruderWord: 'duvar saati', category: 'objects', difficulty: 'easy' },
  { commonWord: 'gözlük', intruderWord: 'koruyucu gözlük', category: 'objects', difficulty: 'medium' },
  { commonWord: 'şemsiye', intruderWord: 'güneş şemsiyesi', category: 'objects', difficulty: 'medium' },
  { commonWord: 'yastık', intruderWord: 'minder', category: 'objects', difficulty: 'medium' },
  { commonWord: 'battaniye', intruderWord: 'yorgan', category: 'objects', difficulty: 'medium' },
  { commonWord: 'kanepe', intruderWord: 'koltuk', category: 'objects', difficulty: 'medium' },
  { commonWord: 'dolap', intruderWord: 'gardırop', category: 'objects', difficulty: 'medium' },
  { commonWord: 'vazo', intruderWord: 'urn', category: 'objects', difficulty: 'hard' },
  { commonWord: 'güneş', intruderWord: 'ay', category: 'nature', difficulty: 'easy' },
  { commonWord: 'yağmur', intruderWord: 'kar', category: 'nature', difficulty: 'easy' },
  { commonWord: 'nehir', intruderWord: 'dere', category: 'nature', difficulty: 'easy' },
  { commonWord: 'plaj', intruderWord: 'kıyı', category: 'nature', difficulty: 'easy' },
  { commonWord: 'bulut', intruderWord: 'sis', category: 'nature', difficulty: 'easy' },
  { commonWord: 'çimen', intruderWord: 'yosun', category: 'nature', difficulty: 'easy' },
  { commonWord: 'kaya', intruderWord: 'kaya parçası', category: 'nature', difficulty: 'medium' },
  { commonWord: 'ada', intruderWord: 'yarımada', category: 'nature', difficulty: 'medium' },
  { commonWord: 'şelale', intruderWord: 'kaskad', category: 'nature', difficulty: 'medium' },
  { commonWord: 'kanyon', intruderWord: 'boğaz', category: 'nature', difficulty: 'medium' },
  { commonWord: 'çöl', intruderWord: 'vaha', category: 'nature', difficulty: 'medium' },
  { commonWord: 'çayır', intruderWord: 'ova', category: 'nature', difficulty: 'medium' },
  { commonWord: 'uçurum', intruderWord: 'sarp kayalık', category: 'nature', difficulty: 'hard' },
  { commonWord: 'golf', intruderWord: 'polo', category: 'sports', difficulty: 'easy' },
  { commonWord: 'koşu', intruderWord: 'jogging', category: 'sports', difficulty: 'easy' },
  { commonWord: 'boks', intruderWord: 'güreş', category: 'sports', difficulty: 'easy' },
  { commonWord: 'bisiklet', intruderWord: 'paten', category: 'sports', difficulty: 'easy' },
  { commonWord: 'kayak', intruderWord: 'snowboard', category: 'sports', difficulty: 'medium' },
  { commonWord: 'kürek', intruderWord: 'kano', category: 'sports', difficulty: 'medium' },
  { commonWord: 'okçuluk', intruderWord: 'eskrim', category: 'sports', difficulty: 'medium' },
  { commonWord: 'jimnastik', intruderWord: 'akrobasi', category: 'sports', difficulty: 'medium' },
  { commonWord: 'maraton', intruderWord: 'sprint', category: 'sports', difficulty: 'medium' },
  { commonWord: 'kriket', intruderWord: 'beyzbol', category: 'sports', difficulty: 'hard' },
  { commonWord: 'avukat', intruderWord: 'hakim', category: 'professions', difficulty: 'easy' },
  { commonWord: 'sürücü', intruderWord: 'binici', category: 'professions', difficulty: 'easy' },
  { commonWord: 'yazar', intruderWord: 'müellif', category: 'professions', difficulty: 'easy' },
  { commonWord: 'sanatçı', intruderWord: 'ressam', category: 'professions', difficulty: 'easy' },
  { commonWord: 'şarkıcı', intruderWord: 'müzisyen', category: 'professions', difficulty: 'easy' },
  { commonWord: 'aktör', intruderWord: 'aktris', category: 'professions', difficulty: 'medium' },
  { commonWord: 'gazeteci', intruderWord: 'muhabir', category: 'professions', difficulty: 'medium' },
  { commonWord: 'fotoğrafçı', intruderWord: 'kameraman', category: 'professions', difficulty: 'medium' },
  { commonWord: 'muhasebeci', intruderWord: 'denetçi', category: 'professions', difficulty: 'medium' },
  { commonWord: 'mekanik', intruderWord: 'teknisyen', category: 'professions', difficulty: 'medium' },
  { commonWord: 'kütüphaneci', intruderWord: 'arşivci', category: 'professions', difficulty: 'hard' },
  { commonWord: 'hastane', intruderWord: 'klinik', category: 'places', difficulty: 'easy' },
  { commonWord: 'park', intruderWord: 'bahçe', category: 'places', difficulty: 'easy' },
  { commonWord: 'dükkan', intruderWord: 'pazar', category: 'places', difficulty: 'easy' },
  { commonWord: 'otel', intruderWord: 'motel', category: 'places', difficulty: 'easy' },
  { commonWord: 'sokak', intruderWord: 'bulvar', category: 'places', difficulty: 'easy' },
  { commonWord: 'köprü', intruderWord: 'tünel', category: 'places', difficulty: 'medium' },
  { commonWord: 'havaalanı', intruderWord: 'istasyon', category: 'places', difficulty: 'medium' },
  { commonWord: 'stadyum', intruderWord: 'arena', category: 'places', difficulty: 'medium' },
  { commonWord: 'tiyatro', intruderWord: 'sinema', category: 'places', difficulty: 'medium' },
  { commonWord: 'fırın', intruderWord: 'pastane', category: 'places', difficulty: 'medium' },
  { commonWord: 'depo', intruderWord: 'antrepo', category: 'places', difficulty: 'hard' },
  { commonWord: 'yürüyüş', intruderWord: 'dağ yürüyüşü', category: 'activities', difficulty: 'easy' },
  { commonWord: 'uyumak', intruderWord: 'kestirmek', category: 'activities', difficulty: 'easy' },
  { commonWord: 'yemek', intruderWord: 'içmek', category: 'activities', difficulty: 'easy' },
  { commonWord: 'izlemek', intruderWord: 'dinlemek', category: 'activities', difficulty: 'easy' },
  { commonWord: 'yüzmek', intruderWord: 'suda kalmak', category: 'activities', difficulty: 'easy' },
  { commonWord: 'alışveriş', intruderWord: 'gezinmek', category: 'activities', difficulty: 'medium' },
  { commonWord: 'seyahat', intruderWord: 'dolaşmak', category: 'activities', difficulty: 'medium' },
  { commonWord: 'çalışmak', intruderWord: 'tekrarlamak', category: 'activities', difficulty: 'medium' },
  { commonWord: 'temizlik', intruderWord: 'toparlamak', category: 'activities', difficulty: 'medium' },
  { commonWord: 'araba sürmek', intruderWord: 'binmek', category: 'activities', difficulty: 'medium' },
  { commonWord: 'bahçıvanlık', intruderWord: 'dikmek', category: 'activities', difficulty: 'medium' },
  { commonWord: 'örgü', intruderWord: 'dikiş', category: 'activities', difficulty: 'hard' }
];
