module.exports = [
  { en: 'raccoon', tr: 'rakun', de: 'Waschbär', fr: 'raton laveur', es: 'mapache', it: 'procione', sq: 'rakun' },
  { en: 'pelican', tr: 'pelikan', de: 'Pelikan', fr: 'pélican', es: 'pelícano', it: 'pellicano', sq: 'pelikan' },
  { en: 'seagull', tr: 'martı', de: 'Möwe', fr: 'mouette', es: 'gaviota', it: 'gabbiano', sq: 'pulëbardha' },
  { en: 'jellyfish', tr: 'denizanası', de: 'Qualle', fr: 'méduse', es: 'medusa', it: 'medusa', sq: 'meduzë' },
  { en: 'starfish', tr: 'denizyıldızı', de: 'Seestern', fr: 'étoile de mer', es: 'estrella de mar', it: 'stella marina', sq: 'yll i detit' },
  { en: 'seahorse', tr: 'denizatı', de: 'Seepferdchen', fr: 'hippocampe', es: 'caballito de mar', it: 'cavalluccio marino', sq: 'kalë deti' },
  { en: 'scorpion', tr: 'akrep', de: 'Skorpion', fr: 'scorpion', es: 'escorpión', it: 'scorpione', sq: 'akrep' },
  { en: 'caterpillar', tr: 'tırtıl', de: 'Raupe', fr: 'chenille', es: 'oruga', it: 'bruco', sq: 'tërfili' },
  { en: 'ladybug', tr: 'uğur böceği', de: 'Marienkäfer', fr: 'coccinelle', es: 'mariquita', it: 'coccinella', sq: 'buburreci' },
  { en: 'mosquito', tr: 'sivrisinek', de: 'Mücke', fr: 'moustique', es: 'mosquito', it: 'zanzara', sq: 'mushkonjë' },
  { en: 'grasshopper', tr: 'çekirge', de: 'Heuschrecke', fr: 'sauterelle', es: 'saltamontes', it: 'cavalletta', sq: 'karkalec' },
  { en: 'bread', tr: 'ekmek', de: 'Brot', fr: 'pain', es: 'pan', it: 'pane', sq: 'bukë' },
  { en: 'milk', tr: 'süt', de: 'Milch', fr: 'lait', es: 'leche', it: 'latte', sq: 'qumësht' },
  { en: 'egg', tr: 'yumurta', de: 'Ei', fr: 'œuf', es: 'huevo', it: 'uovo', sq: 'vezë' },
  { en: 'cheese', tr: 'peynir', de: 'Käse', fr: 'fromage', es: 'queso', it: 'formaggio', sq: 'djathë' },
  { en: 'water', tr: 'su', de: 'Wasser', fr: 'eau', es: 'agua', it: 'acqua', sq: 'ujë' },
  { en: 'coffee', tr: 'kahve', de: 'Kaffee', fr: 'café', es: 'café', it: 'caffè', sq: 'kafe' },
  { en: 'tea', tr: 'çay', de: 'Tee', fr: 'thé', es: 'té', it: 'tè', sq: 'çaj' },
  { en: 'orange', tr: 'portakal', de: 'Orange', fr: 'orange', es: 'naranja', it: 'arancia', sq: 'portokall' },
  { en: 'grape', tr: 'üzüm', de: 'Traube', fr: 'raisin', es: 'uva', it: 'uva', sq: 'rrush' },
  { en: 'strawberry', tr: 'çilek', de: 'Erdbeere', fr: 'fraise', es: 'fresa', it: 'fragola', sq: 'luleshtrydhe' },
  { en: 'carrot', tr: 'havuç', de: 'Karotte', fr: 'carotte', es: 'zanahoria', it: 'carota', sq: 'karotë' },
  { en: 'tomato', tr: 'domates', de: 'Tomate', fr: 'tomate', es: 'tomate', it: 'pomodoro', sq: 'domate' },
  { en: 'potato', tr: 'patates', de: 'Kartoffel', fr: 'pomme de terre', es: 'patata', it: 'patata', sq: 'patate' },
  { en: 'burger', tr: 'burger', de: 'Burger', fr: 'burger', es: 'hamburguesa', it: 'hamburger', sq: 'burger' },
  { en: 'sandwich', tr: 'sandviç', de: 'Sandwich', fr: 'sandwich', es: 'bocadillo', it: 'panino', sq: 'sanduiç' },
  { en: 'soup', tr: 'çorba', de: 'Suppe', fr: 'soupe', es: 'sopa', it: 'zuppa', sq: 'supë' },
  { en: 'salad', tr: 'salata', de: 'Salat', fr: 'salade', es: 'ensalada', it: 'insalata', sq: 'sallatë' },
  { en: 'pasta', tr: 'makarna', de: 'Nudeln', fr: 'pâtes', es: 'pasta', it: 'pasta', sq: 'makarona' },
  { en: 'rice', tr: 'pilav', de: 'Reis', fr: 'riz', es: 'arroz', it: 'riso', sq: 'oriz' },
  { en: 'chicken', tr: 'tavuk', de: 'Hähnchen', fr: 'poulet', es: 'pollo', it: 'pollo', sq: 'pule' },
  { en: 'steak', tr: 'biftek', de: 'Steak', fr: 'steak', es: 'filete', it: 'bistecca', sq: 'biftek' },
  { en: 'sushi', tr: 'suşi', de: 'Sushi', fr: 'sushi', es: 'sushi', it: 'sushi', sq: 'sushi' },
  { en: 'pancake', tr: 'gözleme', de: 'Pfannkuchen', fr: 'crêpe', es: 'tortita', it: 'frittella', sq: 'petulla' },
  { en: 'waffle', tr: 'vafıl', de: 'Waffel', fr: 'gaufre', es: 'gofre', it: 'cialda', sq: 'vafël' },
  { en: 'donut', tr: 'donut', de: 'Donut', fr: 'donut', es: 'dona', it: 'ciambella', sq: 'donut' },
  { en: 'cookie', tr: 'kurabiye', de: 'Keks', fr: 'biscuit', es: 'galleta', it: 'biscotto', sq: 'biskotë' },
  { en: 'chocolate', tr: 'çikolata', de: 'Schokolade', fr: 'chocolat', es: 'chocolate', it: 'cioccolato', sq: 'çokollatë' },
  { en: 'watermelon', tr: 'karpuz', de: 'Wassermelone', fr: 'pastèque', es: 'sandía', it: 'anguria', sq: 'shalqi' },
  { en: 'pineapple', tr: 'ananas', de: 'Ananas', fr: 'ananas', es: 'piña', it: 'ananas', sq: 'ananas' },
  { en: 'avocado', tr: 'avokado', de: 'Avocado', fr: 'avocat', es: 'aguacate', it: 'avocado', sq: 'avokado' },
  { en: 'broccoli', tr: 'brokoli', de: 'Brokkoli', fr: 'brocoli', es: 'brócoli', it: 'broccolo', sq: 'brokoli' },
  { en: 'cucumber', tr: 'salatalık', de: 'Gurke', fr: 'concombre', es: 'pepino', it: 'cetriolo', sq: 'kastravec' },
  { en: 'pepper', tr: 'biber', de: 'Pfeffer', fr: 'poivre', es: 'pimienta', it: 'pepe', sq: 'specë' },
  { en: 'onion', tr: 'soğan', de: 'Zwiebel', fr: 'oignon', es: 'cebolla', it: 'cipolla', sq: 'qepë' },
  { en: 'garlic', tr: 'sarımsak', de: 'Knoblauch', fr: 'ail', es: 'ajo', it: 'aglio', sq: 'hudhër' },
  { en: 'honey', tr: 'bal', de: 'Honig', fr: 'miel', es: 'miel', it: 'miele', sq: 'mjaltë' },
  { en: 'jam', tr: 'reçel', de: 'Marmelade', fr: 'confiture', es: 'mermelada', it: 'marmellata', sq: 'reçel' },
  { en: 'butter', tr: 'tereyağı', de: 'Butter', fr: 'beurre', es: 'mantequilla', it: 'burro', sq: 'gjalpë' },
  { en: 'cereal', tr: 'mısır gevreği', de: 'Müsli', fr: 'céréales', es: 'cereal', it: 'cereali', sq: 'drithëra' },
  { en: 'popcorn', tr: 'patlamış mısır', de: 'Popcorn', fr: 'pop-corn', es: 'palomitas', it: 'popcorn', sq: 'kokoshka' },
  { en: 'croissant', tr: 'kruvasan', de: 'Croissant', fr: 'croissant', es: 'croissant', it: 'croissant', sq: 'kroasant' },
  { en: 'bagel', tr: 'simit', de: 'Bagel', fr: 'bagel', es: 'bagel', it: 'bagel', sq: 'bagel' },
  { en: 'hummus', tr: 'humus', de: 'Hummus', fr: 'houmous', es: 'humus', it: 'hummus', sq: 'humus' },
  { en: 'quinoa', tr: 'kinoa', de: 'Quinoa', fr: 'quinoa', es: 'quinoa', it: 'quinoa', sq: 'kuinoa' },
  { en: 'truffle', tr: 'trüf mantarı', de: 'Trüffel', fr: 'truffe', es: 'trufa', it: 'tartufo', sq: 'trufë' },
  { en: 'caviar', tr: 'havyar', de: 'Kaviar', fr: 'caviar', es: 'caviar', it: 'caviale', sq: 'kaviar' },
  { en: 'marshmallow', tr: 'lokum', de: 'Marshmallow', fr: 'guimauve', es: 'malvavisco', it: 'marshmallow', sq: 'marshmallow' },
  { en: 'cinnamon', tr: 'tarçın', de: 'Zimt', fr: 'cannelle', es: 'canela', it: 'cannella', sq: 'kanellë' },
  { en: 'vanilla', tr: 'vanilya', de: 'Vanille', fr: 'vanille', es: 'vainilla', it: 'vaniglia', sq: 'vanilje' },
  { en: 'ginger', tr: 'zencefil', de: 'Ingwer', fr: 'gingembre', es: 'jengibre', it: 'zenzero', sq: 'xhenxhefil' },
  { en: 'mint', tr: 'nane', de: 'Minze', fr: 'menthe', es: 'menta', it: 'menta', sq: 'mentë' },
  { en: 'basil', tr: 'fesleğen', de: 'Basilikum', fr: 'basilic', es: 'albahaca', it: 'basilico', sq: 'borzilok' },
  { en: 'oregano', tr: 'kekik', de: 'Oregano', fr: 'origan', es: 'orégano', it: 'origano', sq: 'rigon' },
  { en: 'parsley', tr: 'maydanoz', de: 'Petersilie', fr: 'persil', es: 'perejil', it: 'prezzemolo', sq: 'majdanoz' },
  { en: 'coconut', tr: 'hindistan cevizi', de: 'Kokosnuss', fr: 'noix de coco', es: 'coco', it: 'cocco', sq: 'kokos' },
  { en: 'almond', tr: 'badem', de: 'Mandel', fr: 'amande', es: 'almendra', it: 'mandorla', sq: 'bajame' },
  { en: 'walnut', tr: 'ceviz', de: 'Walnuss', fr: 'noix', es: 'nuez', it: 'noce', sq: 'arrë' },
  { en: 'pistachio', tr: 'antep fıstığı', de: 'Pistazie', fr: 'pistache', es: 'pistacho', it: 'pistacchio', sq: 'fistëk' },
  { en: 'raspberry', tr: 'ahududu', de: 'Himbeere', fr: 'framboise', es: 'frambuesa', it: 'lampone', sq: 'manaferrë' },
  { en: 'blackberry', tr: 'böğürtlen', de: 'Brombeere', fr: 'mûre', es: 'mora', it: 'mora', sq: 'manaferrë e zezë' },
  { en: 'blueberry', tr: 'yaban mersini', de: 'Blaubeere', fr: 'myrtille', es: 'arándano', it: 'mirtillo', sq: 'boronicë' },
  { en: 'cranberry', tr: 'kızılcık', de: 'Preiselbeere', fr: 'canneberge', es: 'arándano rojo', it: 'mirtillo rosso', sq: 'boronicë e kuqe' },
  { en: 'black', tr: 'siyah', de: 'Schwarz', fr: 'noir', es: 'negro', it: 'nero', sq: 'zi' },
  { en: 'white', tr: 'beyaz', de: 'Weiß', fr: 'blanc', es: 'blanco', it: 'bianco', sq: 'bardhë' },
  { en: 'pink', tr: 'pembe', de: 'Rosa', fr: 'rose', es: 'rosa', it: 'rosa', sq: 'rozë' },
  { en: 'purple', tr: 'mor', de: 'Lila', fr: 'violet', es: 'morado', it: 'viola', sq: 'vjollcë' },
  { en: 'orange', tr: 'portakal', de: 'Orange', fr: 'orange', es: 'naranja', it: 'arancia', sq: 'portokall' },
  { en: 'brown', tr: 'kahverengi', de: 'Braun', fr: 'marron', es: 'marrón', it: 'marrone', sq: 'kafe' },
  { en: 'gray', tr: 'gri', de: 'Grau', fr: 'gris', es: 'gris', it: 'grigio', sq: 'gri' },
  { en: 'gold', tr: 'altın', de: 'Gold', fr: 'or', es: 'dorado', it: 'oro', sq: 'artë' },
  { en: 'silver', tr: 'gümüş', de: 'Silber', fr: 'argent', es: 'plata', it: 'argento', sq: 'argjend' },
  { en: 'turquoise', tr: 'turkuaz', de: 'Türkis', fr: 'turquoise', es: 'turquesa', it: 'turchese', sq: 'turkuaz' },
  { en: 'navy', tr: 'lacivert', de: 'Marineblau', fr: 'bleu marine', es: 'azul marino', it: 'blu navy', sq: 'blu deti' },
  { en: 'maroon', tr: 'bordo', de: 'Bordeaux', fr: 'bordeaux', es: 'granate', it: 'bordeaux', sq: 'bordoxhi' },
  { en: 'beige', tr: 'bej', de: 'Beige', fr: 'beige', es: 'beige', it: 'beige', sq: 'bezh' },
  { en: 'coral', tr: 'mercan', de: 'Koralle', fr: 'corail', es: 'coral', it: 'corallo', sq: 'koral' },
  { en: 'lavender', tr: 'lavanta', de: 'Lavendel', fr: 'lavande', es: 'lavanda', it: 'lavanda', sq: 'lavandë' },
  { en: 'amber', tr: 'kehribar', de: 'Bernstein', fr: 'ambre', es: 'ámbar', it: 'ambra', sq: 'qelibar' },
  { en: 'indigo', tr: 'çivit', de: 'Indigo', fr: 'indigo', es: 'índigo', it: 'indaco', sq: 'indigo' },
  { en: 'violet', tr: 'menekşe', de: 'Violett', fr: 'violet', es: 'violeta', it: 'viola', sq: 'vjollcë' },
  { en: 'teal', tr: 'deniz mavisi', de: 'Blaugrün', fr: 'sarcelle', es: 'verde azulado', it: 'verde acqua', sq: 'blu-jeshil' },
  { en: 'olive', tr: 'zeytin', de: 'Olive', fr: 'olive', es: 'oliva', it: 'oliva', sq: 'ulli' },
  { en: 'tan', tr: 'taba', de: 'Hellbraun', fr: 'bronzé', es: 'canela', it: 'camoscio', sq: 'kafe e hapur' },
  { en: 'cream', tr: 'krem', de: 'Creme', fr: 'crème', es: 'crema', it: 'crema', sq: 'kremë' },
  { en: 'crimson', tr: 'koyu kırmızı', de: 'Karmesin', fr: 'cramoisi', es: 'carmesí', it: 'cremisi', sq: 'karmin' },
  { en: 'scarlet', tr: 'al', de: 'Scharlachrot', fr: 'écarlate', es: 'escarlata', it: 'scarlatto', sq: 'skuq' },
  { en: 'burgundy', tr: 'bordo', de: 'Burgunder', fr: 'bordeaux', es: 'burdeos', it: 'bordeaux', sq: 'bordoxhi' },
  { en: 'magenta', tr: 'macenta', de: 'Magenta', fr: 'magenta', es: 'magenta', it: 'magenta', sq: 'magenta' },
  { en: 'fuchsia', tr: 'fuşya', de: 'Fuchsia', fr: 'fuchsia', es: 'fucsia', it: 'fucsia', sq: 'fuchsia' },
  { en: 'salmon', tr: 'somon', de: 'Lachs', fr: 'saumon', es: 'salmón', it: 'salmone', sq: 'ngjyrë salmoni' },
  { en: 'peach', tr: 'şeftali', de: 'Pfirsich', fr: 'pêche', es: 'melocotón', it: 'pesca', sq: 'pjeshkë' },
  { en: 'mauve', tr: 'eflatun', de: 'Mauve', fr: 'mauve', es: 'malva', it: 'malva', sq: 'vjollcë e zbehtë' },
  { en: 'plum', tr: 'erik', de: 'Pflaume', fr: 'prune', es: 'ciruela', it: 'prugna', sq: 'kumbull' },
  { en: 'cyan', tr: 'camgöbeği', de: 'Cyan', fr: 'cyan', es: 'cian', it: 'ciano', sq: 'cyan' },
  { en: 'azure', tr: 'gök mavisi', de: 'Azurblau', fr: 'azur', es: 'azul celeste', it: 'azzurro', sq: 'kaltër' },
  { en: 'ivory', tr: 'fildişi', de: 'Elfenbein', fr: 'ivoire', es: 'marfil', it: 'avorio', sq: 'fildişi' },
  { en: 'charcoal', tr: 'kömür', de: 'Kohle', fr: 'charbon', es: 'carbón', it: 'carbone', sq: 'qymyr' },
  { en: 'mustard', tr: 'hardal', de: 'Senf', fr: 'moutarde', es: 'mostaza', it: 'senape', sq: 'mustardë' },
  { en: 'rust', tr: 'pas', de: 'Rost', fr: 'rouille', es: 'óxido', it: 'ruggine', sq: 'ndryshk' },
  { en: 'bronze', tr: 'bronz', de: 'Bronze', fr: 'bronze', es: 'bronce', it: 'bronzo', sq: 'bronz' },
  { en: 'copper', tr: 'bakır', de: 'Kupfer', fr: 'cuivre', es: 'cobre', it: 'rame', sq: 'bakër' },
  { en: 'emerald', tr: 'zümrüt', de: 'Smaragd', fr: 'émeraude', es: 'esmeralda', it: 'smeraldo', sq: 'smaragd' },
  { en: 'sapphire', tr: 'safir', de: 'Saphir', fr: 'saphir', es: 'zafiro', it: 'zaffiro', sq: 'safir' },
  { en: 'ruby', tr: 'yakut', de: 'Rubin', fr: 'rubis', es: 'rubí', it: 'rubino', sq: 'rubin' },
  { en: 'jade', tr: 'yeşim', de: 'Jade', fr: 'jade', es: 'jade', it: 'giada', sq: 'jade' },
  { en: 'coral', tr: 'mercan', de: 'Koralle', fr: 'corail', es: 'coral', it: 'corallo', sq: 'koral' },
  { en: 'lavender', tr: 'lavanta', de: 'Lavendel', fr: 'lavande', es: 'lavanda', it: 'lavanda', sq: 'lavandë' },
  { en: 'mint', tr: 'nane', de: 'Minze', fr: 'menthe', es: 'menta', it: 'menta', sq: 'mentë' },
  { en: 'lilac', tr: 'leylak', de: 'Flieder', fr: 'lilas', es: 'lila', it: 'lilla', sq: 'lila' },
  { en: 'chartreuse', tr: 'sarımsı yeşil', de: 'Chartreuse', fr: 'chartreuse', es: 'chartreuse', it: 'chartreuse', sq: 'chartreuse' },
  { en: 'vermilion', tr: 'kırmızı', de: 'Zinnober', fr: 'vermillon', es: 'bermellón', it: 'vermiglio', sq: 'vermillion' },
  { en: 'cerulean', tr: 'gök mavisi', de: 'Himmelblau', fr: 'céruléen', es: 'cerúleo', it: 'ceruleo', sq: 'kaltër' },
  { en: 'ochre', tr: 'okra', de: 'Ocker', fr: 'ocre', es: 'ocre', it: 'ocra', sq: 'oker' },
  { en: 'excited', tr: 'heyecanlı', de: 'aufgeregt', fr: 'excité', es: 'emocionado', it: 'eccitato', sq: 'i emocionuar' },
  { en: 'tired', tr: 'yorgun', de: 'müde', fr: 'fatigué', es: 'cansado', it: 'stanco', sq: 'i lodhur' },
  { en: 'nervous', tr: 'gergin', de: 'nervös', fr: 'nerveux', es: 'nervioso', it: 'nervoso', sq: 'nervoz' },
  { en: 'calm', tr: 'sakin', de: 'ruhig', fr: 'calme', es: 'tranquilo', it: 'calmo', sq: 'qetë' },
  { en: 'love', tr: 'aşk', de: 'Liebe', fr: 'amour', es: 'amor', it: 'amore', sq: 'dashuri' },
  { en: 'joy', tr: 'neşe', de: 'Freude', fr: 'joie', es: 'alegría', it: 'gioia', sq: 'gëzim' },
  { en: 'fear', tr: 'korku', de: 'Angst', fr: 'peur', es: 'miedo', it: 'paura', sq: 'frikë' },
  { en: 'anger', tr: 'öfke', de: 'Wut', fr: 'colère', es: 'ira', it: 'rabbia', sq: 'zemërim' },
  { en: 'hope', tr: 'umut', de: 'Hoffnung', fr: 'espoir', es: 'esperanza', it: 'speranza', sq: 'shpresë' },
  { en: 'pride', tr: 'gurur', de: 'Stolz', fr: 'fierté', es: 'orgullo', it: 'orgoglio', sq: 'krenari' },
  { en: 'shame', tr: 'utanç', de: 'Scham', fr: 'honte', es: 'vergüenza', it: 'vergogna', sq: 'turp' },
  { en: 'guilt', tr: 'suçluluk', de: 'Schuld', fr: 'culpabilité', es: 'culpa', it: 'colpa', sq: 'faj' },
  { en: 'jealousy', tr: 'kıskançlık', de: 'Eifersucht', fr: 'jalousie', es: 'celos', it: 'gelosia', sq: 'xhelozi' },
  { en: 'boredom', tr: 'can sıkıntısı', de: 'Langeweile', fr: 'ennui', es: 'aburrimiento', it: 'noia', sq: 'merzi' },
  { en: 'confusion', tr: 'kafa karışıklığı', de: 'Verwirrung', fr: 'confusion', es: 'confusión', it: 'confusione', sq: 'konfuzion' },
  { en: 'curiosity', tr: 'merak', de: 'Neugier', fr: 'curiosité', es: 'curiosidad', it: 'curiosità', sq: 'kuriozitet' },
  { en: 'gratitude', tr: 'minnettarlık', de: 'Dankbarkeit', fr: 'gratitude', es: 'gratitud', it: 'gratitudine', sq: 'mirënjohje' },
  { en: 'relief', tr: 'rahatlama', de: 'Erleichterung', fr: 'soulagement', es: 'alivio', it: 'sollievo', sq: 'lehtësim' },
  { en: 'disappointment', tr: 'hayal kırıklığı', de: 'Enttäuschung', fr: 'déception', es: 'decepción', it: 'delusione', sq: 'zhgënjim' },
  { en: 'embarrassment', tr: 'utangaçlık', de: 'Verlegenheit', fr: 'embarras', es: 'vergüenza', it: 'imbarazzo', sq: 'turp' },
  { en: 'frustration', tr: 'hayal kırıklığı', de: 'Frustration', fr: 'frustration', es: 'frustración', it: 'frustrazione', sq: 'frustrim' },
  { en: 'anxiety', tr: 'kaygı', de: 'Angst', fr: 'anxiété', es: 'ansiedad', it: 'ansia', sq: 'ankth' },
  { en: 'enthusiasm', tr: 'heves', de: 'Begeisterung', fr: 'enthousiasme', es: 'entusiasmo', it: 'entusiasmo', sq: 'entuziazëm' },
  { en: 'contentment', tr: 'memnuniyet', de: 'Zufriedenheit', fr: 'contentement', es: 'contento', it: 'contentezza', sq: 'kënaqësi' },
  { en: 'loneliness', tr: 'yalnızlık', de: 'Einsamkeit', fr: 'solitude', es: 'soledad', it: 'solitudine', sq: 'vetmi' },
  { en: 'nostalgia', tr: 'nostalji', de: 'Nostalgie', fr: 'nostalgie', es: 'nostalgia', it: 'nostalgia', sq: 'nostalgji' },
  { en: 'melancholy', tr: 'melankoli', de: 'Melancholie', fr: 'mélancolie', es: 'melancolía', it: 'malinconia', sq: 'melankoli' },
  { en: 'euphoria', tr: 'öfori', de: 'Euphorie', fr: 'euphorie', es: 'euforia', it: 'euforia', sq: 'eufori' },
  { en: 'serenity', tr: 'huzur', de: 'Gelassenheit', fr: 'sérénité', es: 'serenidad', it: 'serenità', sq: 'qetësi' },
  { en: 'bewilderment', tr: 'şaşkınlık', de: 'Verwirrung', fr: 'désarroi', es: 'desconcierto', it: 'sconcerto', sq: 'habitë' },
  { en: 'amusement', tr: 'eğlence', de: 'Belustigung', fr: 'amusement', es: 'diversión', it: 'divertimento', sq: 'argëtim' },
  { en: 'astonishment', tr: 'hayret', de: 'Erstaunen', fr: 'étonnement', es: 'asombro', it: 'stupore', sq: 'çuditë' },
  { en: 'determination', tr: 'kararlılık', de: 'Entschlossenheit', fr: 'détermination', es: 'determinación', it: 'determinazione', sq: 'vendosmëri' },
  { en: 'overwhelmed', tr: 'boğulmuş', de: 'überwältigt', fr: 'submergé', es: 'abrumado', it: 'sopraffatto', sq: 'i mbushur' },
  { en: 'resentment', tr: 'kızgınlık', de: 'Groll', fr: 'rancune', es: 'resentimiento', it: 'risentimento', sq: 'inatim' },
  { en: 'admiration', tr: 'hayranlık', de: 'Bewunderung', fr: 'admiration', es: 'admiración', it: 'ammirazione', sq: 'adhurim' },
  { en: 'anticipation', tr: 'beklenti', de: 'Vorfreude', fr: 'anticipation', es: 'anticipación', it: 'anticipazione', sq: 'pritje' },
  { en: 'apprehension', tr: 'endişe', de: 'Befürchtung', fr: 'appréhension', es: 'aprensión', it: 'apprensione', sq: 'ankth' },
  { en: 'contempt', tr: 'küçümseme', de: 'Verachtung', fr: 'mépris', es: 'desprecio', it: 'disprezzo', sq: 'përbuzje' },
  { en: 'devotion', tr: 'bağlılık', de: 'Hingabe', fr: 'dévouement', es: 'devoción', it: 'devozione', sq: 'devotësim' },
  { en: 'dread', tr: 'dehşet', de: 'Furcht', fr: 'terreur', es: 'pavor', it: 'terrore', sq: 'tmerr' },
  { en: 'ecstasy', tr: 'vecit', de: 'Ekstase', fr: 'extase', es: 'éxtasis', it: 'estasi', sq: 'ekstazë' },
  { en: 'envy', tr: 'kıskançlık', de: 'Neid', fr: 'envie', es: 'envidia', it: 'invidia', sq: 'zili' },
  { en: 'grief', tr: 'keder', de: 'Trauer', fr: 'chagrin', es: 'pena', it: 'dolore', sq: 'brengë' },
  { en: 'indifference', tr: 'kayıtsızlık', de: 'Gleichgültigkeit', fr: 'indifférence', es: 'indiferencia', it: 'indifferenza', sq: 'indiferencë' },
  { en: 'longing', tr: 'özlem', de: 'Sehnsucht', fr: 'nostalgie', es: 'añoranza', it: 'desiderio', sq: 'dëshirë' },
  { en: 'rage', tr: 'öfke', de: 'Wut', fr: 'rage', es: 'rabia', it: 'rabbia', sq: 'tërbohet' },
  { en: 'regret', tr: 'pişmanlık', de: 'Bedauern', fr: 'regret', es: 'arrepentimiento', it: 'rimpianto', sq: 'pendim' },
  { en: 'remorse', tr: 'vicdan azabı', de: 'Reue', fr: 'remords', es: 'remordimiento', it: 'rimorso', sq: 'pendim' },
  { en: 'satisfaction', tr: 'tatmin', de: 'Zufriedenheit', fr: 'satisfaction', es: 'satisfacción', it: 'soddisfazione', sq: 'kënaqësi' },
  { en: 'sorrow', tr: 'keder', de: 'Kummer', fr: 'chagrin', es: 'pena', it: 'dolore', sq: 'brengë' },
  { en: 'suspense', tr: 'gerilim', de: 'Spannung', fr: 'suspens', es: 'suspense', it: 'suspense', sq: 'tension' },
  { en: 'sympathy', tr: 'sempati', de: 'Sympathie', fr: 'sympathie', es: 'simpatía', it: 'simpatia', sq: 'keqardhje' },
  { en: 'terror', tr: 'terör', de: 'Schrecken', fr: 'terreur', es: 'terror', it: 'terrore', sq: 'tmerr' },
  { en: 'wonder', tr: 'hayranlık', de: 'Staunen', fr: 'émerveillement', es: 'asombro', it: 'meraviglia', sq: 'çudi' },
  { en: 'chair', tr: 'sandalye', de: 'Stuhl', fr: 'chaise', es: 'silla', it: 'sedia', sq: 'karrige' },
  { en: 'table', tr: 'masa', de: 'Tisch', fr: 'table', es: 'mesa', it: 'tavolo', sq: 'tavolinë' },
  { en: 'lamp', tr: 'lamba', de: 'Lampe', fr: 'lampe', es: 'lámpara', it: 'lampada', sq: 'llambë' },
  { en: 'door', tr: 'kapı', de: 'Tür', fr: 'porte', es: 'puerta', it: 'porta', sq: 'derë' },
  { en: 'window', tr: 'pencere', de: 'Fenster', fr: 'fenêtre', es: 'ventana', it: 'finestra', sq: 'dritare' },
  { en: 'clock', tr: 'saat', de: 'Uhr', fr: 'horloge', es: 'reloj', it: 'orologio', sq: 'orë' },
  { en: 'watch', tr: 'kol saati', de: 'Armbanduhr', fr: 'montre', es: 'reloj', it: 'orologio', sq: 'orë' },
  { en: 'bag', tr: 'çanta', de: 'Tasche', fr: 'sac', es: 'bolso', it: 'borsa', sq: 'çantë' },
  { en: 'cup', tr: 'fincan', de: 'Tasse', fr: 'tasse', es: 'taza', it: 'tazza', sq: 'filxhan' },
  { en: 'pen', tr: 'kalem', de: 'Stift', fr: 'stylo', es: 'bolígrafo', it: 'penna', sq: 'stilolaps' },
  { en: 'mirror', tr: 'ayna', de: 'Spiegel', fr: 'miroir', es: 'espejo', it: 'specchio', sq: 'pasqyrë' },
  { en: 'pillow', tr: 'yastık', de: 'Kissen', fr: 'oreiller', es: 'almohada', it: 'cuscino', sq: 'jastëk' },
  { en: 'blanket', tr: 'battaniye', de: 'Decke', fr: 'couverture', es: 'manta', it: 'coperta', sq: 'batanije' },
  { en: 'sofa', tr: 'kanepe', de: 'Sofa', fr: 'canapé', es: 'sofá', it: 'divano', sq: 'divan' },
  { en: 'glasses', tr: 'gözlük', de: 'Brille', fr: 'lunettes', es: 'gafas', it: 'occhiali', sq: 'syze' },
  { en: 'wallet', tr: 'cüzdan', de: 'Geldbörse', fr: 'portefeuille', es: 'cartera', it: 'portafoglio', sq: 'portofol' },
  { en: 'backpack', tr: 'sırt çantası', de: 'Rucksack', fr: 'sac à dos', es: 'mochila', it: 'zaino', sq: 'çantë shpine' },
  { en: 'bottle', tr: 'şişe', de: 'Flasche', fr: 'bouteille', es: 'botella', it: 'bottiglia', sq: 'shishe' },
  { en: 'scissors', tr: 'makas', de: 'Schere', fr: 'ciseaux', es: 'tijeras', it: 'forbici', sq: 'gërshërë' },
  { en: 'hammer', tr: 'çekiç', de: 'Hammer', fr: 'marteau', es: 'martillo', it: 'martello', sq: 'çekiç' },
  { en: 'brush', tr: 'fırça', de: 'Pinsel', fr: 'pinceau', es: 'cepillo', it: 'pennello', sq: 'furçë' },
  { en: 'comb', tr: 'tarak', de: 'Kamm', fr: 'peigne', es: 'peine', it: 'pettine', sq: 'krehër' },
  { en: 'toothbrush', tr: 'diş fırçası', de: 'Zahnbürste', fr: 'brosse à dents', es: 'cepillo de dientes', it: 'spazzolino', sq: 'furçë dhëmbësh' },
  { en: 'towel', tr: 'havlu', de: 'Handtuch', fr: 'serviette', es: 'toalla', it: 'asciugamano', sq: 'peshqir' },
  { en: 'newspaper', tr: 'gazete', de: 'Zeitung', fr: 'journal', es: 'periódico', it: 'giornale', sq: 'gazetë' },
  { en: 'magazine', tr: 'dergi', de: 'Zeitschrift', fr: 'magazine', es: 'revista', it: 'rivista', sq: 'revistë' },
  { en: 'remote', tr: 'kumanda', de: 'Fernbedienung', fr: 'télécommande', es: 'mando', it: 'telecomando', sq: 'telekomandë' },
  { en: 'headphones', tr: 'kulaklık', de: 'Kopfhörer', fr: 'écouteurs', es: 'auriculares', it: 'cuffie', sq: 'kufje' },
  { en: 'laptop', tr: 'dizüstü bilgisayar', de: 'Laptop', fr: 'ordinateur portable', es: 'portátil', it: 'laptop', sq: 'kompjuter portativ' },
  { en: 'keyboard', tr: 'klavye', de: 'Tastatur', fr: 'clavier', es: 'teclado', it: 'tastiera', sq: 'tastierë' },
  { en: 'mouse', tr: 'fare', de: 'Maus', fr: 'souris', es: 'ratón', it: 'mouse', sq: 'miu' },
  { en: 'speaker', tr: 'hoparlör', de: 'Lautsprecher', fr: 'enceinte', es: 'altavoz', it: 'altoparlante', sq: 'altoparlant' },
  { en: 'microphone', tr: 'mikrofon', de: 'Mikrofon', fr: 'microphone', es: 'micrófono', it: 'microfono', sq: 'mikrofon' },
  { en: 'flashlight', tr: 'el feneri', de: 'Taschenlampe', fr: 'lampe de poche', es: 'linterna', it: 'torcia', sq: 'dritë dore' },
  { en: 'battery', tr: 'pil', de: 'Batterie', fr: 'pile', es: 'batería', it: 'batteria', sq: 'bateri' },
  { en: 'charger', tr: 'şarj cihazı', de: 'Ladegerät', fr: 'chargeur', es: 'cargador', it: 'caricabatterie', sq: 'karikues' },
  { en: 'vase', tr: 'vazo', de: 'Vase', fr: 'vase', es: 'florero', it: 'vaso', sq: 'vazo' },
  { en: 'umbrella', tr: 'şemsiye', de: 'Regenschirm', fr: 'parapluie', es: 'paraguas', it: 'ombrello', sq: 'ombrellë' },
  { en: 'parasol', tr: 'güneş şemsiyesi', de: 'Sonnenschirm', fr: 'parasol', es: 'sombrilla', it: 'parasole', sq: 'ombrellë dielli' },
  { en: 'binoculars', tr: 'dürbün', de: 'Fernglas', fr: 'jumelles', es: 'prismáticos', it: 'binocolo', sq: 'dylbi' },
  { en: 'telescope', tr: 'teleskop', de: 'Teleskop', fr: 'télescope', es: 'telescopio', it: 'telescopio', sq: 'teleskop' },
  { en: 'compass', tr: 'pusula', de: 'Kompass', fr: 'boussole', es: 'brújula', it: 'bussola', sq: 'busullë' },
  { en: 'thermometer', tr: 'termometre', de: 'Thermometer', fr: 'thermomètre', es: 'termómetro', it: 'termometro', sq: 'termometër' },
  { en: 'magnifying glass', tr: 'büyüteç', de: 'Lupe', fr: 'loupe', es: 'lupa', it: 'lente d\'ingrandimento', sq: 'lupë' },
  { en: 'screwdriver', tr: 'tornavida', de: 'Schraubenzieher', fr: 'tournevis', es: 'destornillador', it: 'cacciavite', sq: 'kaçavidë' },
  { en: 'wrench', tr: 'İngiliz anahtarı', de: 'Schraubenschlüssel', fr: 'clé', es: 'llave', it: 'chiave', sq: 'çelës' },
  { en: 'pliers', tr: 'pense', de: 'Zange', fr: 'pince', es: 'alicates', it: 'pinze', sq: 'darë' },
  { en: 'needle', tr: 'iğne', de: 'Nadel', fr: 'aiguille', es: 'aguja', it: 'ago', sq: 'grep' },
  { en: 'thread', tr: 'iplik', de: 'Faden', fr: 'fil', es: 'hilo', it: 'filo', sq: 'fije' },
  { en: 'suitcase', tr: 'bavul', de: 'Koffer', fr: 'valise', es: 'maleta', it: 'valigia', sq: 'valixhe' },
  { en: 'briefcase', tr: 'evrak çantası', de: 'Aktentasche', fr: 'mallette', es: 'maletín', it: 'valigetta', sq: 'portofol' },
  { en: 'umbrella stand', tr: 'şemsiye standı', de: 'Regenschirmständer', fr: 'porte-parapluies', es: 'paragüero', it: 'portaombrelli', sq: 'mbajtës ombrellash' },
  { en: 'coat hanger', tr: 'askı', de: 'Kleiderbügel', fr: 'cintre', es: 'percha', it: 'gruccia', sq: 'varëse' },
  { en: 'doorbell', tr: 'kapı zili', de: 'Türklingel', fr: 'sonnette', es: 'timbre', it: 'campanello', sq: 'zile derë' },
  { en: 'door knocker', tr: 'kapı tokmağı', de: 'Türklopfer', fr: 'marteau de porte', es: 'aldaba', it: 'battente', sq: 'trokitës dere' },
  { en: 'curtain', tr: 'perde', de: 'Vorhang', fr: 'rideau', es: 'cortina', it: 'tenda', sq: 'perde' },
  { en: 'blinds', tr: 'jaluz', de: 'Jalousie', fr: 'stores', es: 'persianas', it: 'persiane', sq: 'xham' },
  { en: 'chandelier', tr: 'avize', de: 'Kronleuchter', fr: 'lustre', es: 'candelabro', it: 'lampadario', sq: 'lustër' },
  { en: 'candelabra', tr: 'şamdan', de: 'Kandelaber', fr: 'candélabre', es: 'candelabro', it: 'candelabro', sq: 'shandan' },
  { en: 'hourglass', tr: 'kum saati', de: 'Sanduhr', fr: 'sablier', es: 'reloj de arena', it: 'clessidra', sq: 'orë rëre' },
  { en: 'sundial', tr: 'güneş saati', de: 'Sonnenuhr', fr: 'cadran solaire', es: 'reloj de sol', it: 'meridiana', sq: 'orë dielli' },
  { en: 'globe', tr: 'küre', de: 'Globus', fr: 'globe', es: 'globo', it: 'globo', sq: 'glob' },
  { en: 'atlas', tr: 'atlas', de: 'Atlas', fr: 'atlas', es: 'atlas', it: 'atlante', sq: 'atlas' },
  { en: 'encyclopedia', tr: 'ansiklopedi', de: 'Enzyklopädie', fr: 'encyclopédie', es: 'enciclopedia', it: 'enciclopedia', sq: 'enciklopedi' },
  { en: 'scrapbook', tr: 'albüm', de: 'Sammelalbum', fr: 'album', es: 'álbum de recortes', it: 'album', sq: 'album' },
  { en: 'photo album', tr: 'fotoğraf albümü', de: 'Fotoalbum', fr: 'album photo', es: 'álbum de fotos', it: 'album fotografico', sq: 'album fotosh' },
  { en: 'jewelry box', tr: 'mücevher kutusu', de: 'Schmuckkästchen', fr: 'coffret à bijoux', es: 'joyero', it: 'portagioie', sq: 'kuti bizhuterish' },
  { en: 'piggy bank', tr: 'kumbara', de: 'Sparschwein', fr: 'tirelire', es: 'alcancía', it: 'salvadanaio', sq: 'kupa kursimi' },
  { en: 'flower', tr: 'flower', de: 'flower', fr: 'flower', es: 'flower', it: 'flower', sq: 'flower' },
  { en: 'grass', tr: 'grass', de: 'grass', fr: 'grass', es: 'grass', it: 'grass', sq: 'grass' },
  { en: 'cloud', tr: 'cloud', de: 'cloud', fr: 'cloud', es: 'cloud', it: 'cloud', sq: 'cloud' },
  { en: 'snow', tr: 'snow', de: 'snow', fr: 'snow', es: 'snow', it: 'snow', sq: 'snow' },
  { en: 'wind', tr: 'wind', de: 'wind', fr: 'wind', es: 'wind', it: 'wind', sq: 'wind' },
  { en: 'river', tr: 'river', de: 'river', fr: 'river', es: 'river', it: 'river', sq: 'river' },
  { en: 'lake', tr: 'lake', de: 'lake', fr: 'lake', es: 'lake', it: 'lake', sq: 'lake' },
  { en: 'ocean', tr: 'ocean', de: 'ocean', fr: 'ocean', es: 'ocean', it: 'ocean', sq: 'ocean' },
  { en: 'beach', tr: 'beach', de: 'beach', fr: 'beach', es: 'beach', it: 'beach', sq: 'beach' },
  { en: 'forest', tr: 'forest', de: 'forest', fr: 'forest', es: 'forest', it: 'forest', sq: 'forest' },
  { en: 'rock', tr: 'rock', de: 'rock', fr: 'rock', es: 'rock', it: 'rock', sq: 'rock' },
  { en: 'island', tr: 'island', de: 'island', fr: 'island', es: 'island', it: 'island', sq: 'island' },
  { en: 'waterfall', tr: 'waterfall', de: 'waterfall', fr: 'waterfall', es: 'waterfall', it: 'waterfall', sq: 'waterfall' },
  { en: 'volcano', tr: 'volcano', de: 'volcano', fr: 'volcano', es: 'volcano', it: 'volcano', sq: 'volcano' },
  { en: 'desert', tr: 'desert', de: 'desert', fr: 'desert', es: 'desert', it: 'desert', sq: 'desert' },
  { en: 'valley', tr: 'valley', de: 'valley', fr: 'valley', es: 'valley', it: 'valley', sq: 'valley' },
  { en: 'canyon', tr: 'canyon', de: 'canyon', fr: 'canyon', es: 'canyon', it: 'canyon', sq: 'canyon' },
  { en: 'cliff', tr: 'cliff', de: 'cliff', fr: 'cliff', es: 'cliff', it: 'cliff', sq: 'cliff' },
  { en: 'meadow', tr: 'meadow', de: 'meadow', fr: 'meadow', es: 'meadow', it: 'meadow', sq: 'meadow' },
  { en: 'stream', tr: 'stream', de: 'stream', fr: 'stream', es: 'stream', it: 'stream', sq: 'stream' },
  { en: 'pond', tr: 'pond', de: 'pond', fr: 'pond', es: 'pond', it: 'pond', sq: 'pond' },
  { en: 'wave', tr: 'wave', de: 'wave', fr: 'wave', es: 'wave', it: 'wave', sq: 'wave' },
  { en: 'storm', tr: 'storm', de: 'storm', fr: 'storm', es: 'storm', it: 'storm', sq: 'storm' },
  { en: 'thunder', tr: 'thunder', de: 'thunder', fr: 'thunder', es: 'thunder', it: 'thunder', sq: 'thunder' },
  { en: 'lightning', tr: 'lightning', de: 'lightning', fr: 'lightning', es: 'lightning', it: 'lightning', sq: 'lightning' },
  { en: 'fog', tr: 'fog', de: 'fog', fr: 'fog', es: 'fog', it: 'fog', sq: 'fog' },
  { en: 'mist', tr: 'mist', de: 'mist', fr: 'mist', es: 'mist', it: 'mist', sq: 'mist' },
  { en: 'dew', tr: 'dew', de: 'dew', fr: 'dew', es: 'dew', it: 'dew', sq: 'dew' },
  { en: 'frost', tr: 'frost', de: 'frost', fr: 'frost', es: 'frost', it: 'frost', sq: 'frost' },
  { en: 'hail', tr: 'hail', de: 'hail', fr: 'hail', es: 'hail', it: 'hail', sq: 'hail' },
  { en: 'hurricane', tr: 'hurricane', de: 'hurricane', fr: 'hurricane', es: 'hurricane', it: 'hurricane', sq: 'hurricane' },
  { en: 'tornado', tr: 'tornado', de: 'tornado', fr: 'tornado', es: 'tornado', it: 'tornado', sq: 'tornado' },
  { en: 'earthquake', tr: 'earthquake', de: 'earthquake', fr: 'earthquake', es: 'earthquake', it: 'earthquake', sq: 'earthquake' },
  { en: 'avalanche', tr: 'avalanche', de: 'avalanche', fr: 'avalanche', es: 'avalanche', it: 'avalanche', sq: 'avalanche' },
  { en: 'wildfire', tr: 'wildfire', de: 'wildfire', fr: 'wildfire', es: 'wildfire', it: 'wildfire', sq: 'wildfire' },
  { en: 'geyser', tr: 'geyser', de: 'geyser', fr: 'geyser', es: 'geyser', it: 'geyser', sq: 'geyser' },
  { en: 'glacier', tr: 'glacier', de: 'glacier', fr: 'glacier', es: 'glacier', it: 'glacier', sq: 'glacier' },
  { en: 'iceberg', tr: 'iceberg', de: 'iceberg', fr: 'iceberg', es: 'iceberg', it: 'iceberg', sq: 'iceberg' },
  { en: 'oasis', tr: 'oasis', de: 'oasis', fr: 'oasis', es: 'oasis', it: 'oasis', sq: 'oasis' },
  { en: 'peninsula', tr: 'peninsula', de: 'peninsula', fr: 'peninsula', es: 'peninsula', it: 'peninsula', sq: 'peninsula' },
  { en: 'archipelago', tr: 'archipelago', de: 'archipelago', fr: 'archipelago', es: 'archipelago', it: 'archipelago', sq: 'archipelago' },
  { en: 'estuary', tr: 'estuary', de: 'estuary', fr: 'estuary', es: 'estuary', it: 'estuary', sq: 'estuary' },
  { en: 'delta', tr: 'delta', de: 'delta', fr: 'delta', es: 'delta', it: 'delta', sq: 'delta' },
  { en: 'tributary', tr: 'tributary', de: 'tributary', fr: 'tributary', es: 'tributary', it: 'tributary', sq: 'tributary' },
  { en: 'reservoir', tr: 'reservoir', de: 'reservoir', fr: 'reservoir', es: 'reservoir', it: 'reservoir', sq: 'reservoir' },
  { en: 'wetland', tr: 'wetland', de: 'wetland', fr: 'wetland', es: 'wetland', it: 'wetland', sq: 'wetland' },
  { en: 'marsh', tr: 'marsh', de: 'marsh', fr: 'marsh', es: 'marsh', it: 'marsh', sq: 'marsh' },
  { en: 'swamp', tr: 'swamp', de: 'swamp', fr: 'swamp', es: 'swamp', it: 'swamp', sq: 'swamp' },
  { en: 'tundra', tr: 'tundra', de: 'tundra', fr: 'tundra', es: 'tundra', it: 'tundra', sq: 'tundra' },
  { en: 'savanna', tr: 'savanna', de: 'savanna', fr: 'savanna', es: 'savanna', it: 'savanna', sq: 'savanna' },
  { en: 'prairie', tr: 'prairie', de: 'prairie', fr: 'prairie', es: 'prairie', it: 'prairie', sq: 'prairie' },
  { en: 'jungle', tr: 'jungle', de: 'jungle', fr: 'jungle', es: 'jungle', it: 'jungle', sq: 'jungle' },
  { en: 'reef', tr: 'reef', de: 'reef', fr: 'reef', es: 'reef', it: 'reef', sq: 'reef' },
  { en: 'coral', tr: 'mercan', de: 'Koralle', fr: 'corail', es: 'coral', it: 'corallo', sq: 'koral' },
  { en: 'dune', tr: 'dune', de: 'dune', fr: 'dune', es: 'dune', it: 'dune', sq: 'dune' },
  { en: 'crater', tr: 'crater', de: 'crater', fr: 'crater', es: 'crater', it: 'crater', sq: 'crater' },
  { en: 'summit', tr: 'summit', de: 'summit', fr: 'summit', es: 'summit', it: 'summit', sq: 'summit' },
  { en: 'ridge', tr: 'ridge', de: 'ridge', fr: 'ridge', es: 'ridge', it: 'ridge', sq: 'ridge' },
  { en: 'plateau', tr: 'plateau', de: 'plateau', fr: 'plateau', es: 'plateau', it: 'plateau', sq: 'plateau' },
  { en: 'grove', tr: 'grove', de: 'grove', fr: 'grove', es: 'grove', it: 'grove', sq: 'grove' },
  { en: 'thicket', tr: 'thicket', de: 'thicket', fr: 'thicket', es: 'thicket', it: 'thicket', sq: 'thicket' },
  { en: 'canopy', tr: 'canopy', de: 'canopy', fr: 'canopy', es: 'canopy', it: 'canopy', sq: 'canopy' },
  { en: 'underbrush', tr: 'underbrush', de: 'underbrush', fr: 'underbrush', es: 'underbrush', it: 'underbrush', sq: 'underbrush' },
  { en: 'blossom', tr: 'blossom', de: 'blossom', fr: 'blossom', es: 'blossom', it: 'blossom', sq: 'blossom' },
  { en: 'petal', tr: 'petal', de: 'petal', fr: 'petal', es: 'petal', it: 'petal', sq: 'petal' },
  { en: 'thorn', tr: 'thorn', de: 'thorn', fr: 'thorn', es: 'thorn', it: 'thorn', sq: 'thorn' },
  { en: 'vine', tr: 'vine', de: 'vine', fr: 'vine', es: 'vine', it: 'vine', sq: 'vine' },
  { en: 'moss', tr: 'moss', de: 'moss', fr: 'moss', es: 'moss', it: 'moss', sq: 'moss' },
  { en: 'fern', tr: 'fern', de: 'fern', fr: 'fern', es: 'fern', it: 'fern', sq: 'fern' },
  { en: 'cactus', tr: 'cactus', de: 'cactus', fr: 'cactus', es: 'cactus', it: 'cactus', sq: 'cactus' },
  { en: 'soccer', tr: 'soccer', de: 'soccer', fr: 'soccer', es: 'soccer', it: 'soccer', sq: 'soccer' },
  { en: 'baseball', tr: 'baseball', de: 'baseball', fr: 'baseball', es: 'baseball', it: 'baseball', sq: 'baseball' },
  { en: 'golf', tr: 'golf', de: 'golf', fr: 'golf', es: 'golf', it: 'golf', sq: 'golf' },
  { en: 'boxing', tr: 'boxing', de: 'boxing', fr: 'boxing', es: 'boxing', it: 'boxing', sq: 'boxing' },
  { en: 'wrestling', tr: 'wrestling', de: 'wrestling', fr: 'wrestling', es: 'wrestling', it: 'wrestling', sq: 'wrestling' },
  { en: 'skiing', tr: 'skiing', de: 'skiing', fr: 'skiing', es: 'skiing', it: 'skiing', sq: 'skiing' },
  { en: 'skating', tr: 'skating', de: 'skating', fr: 'skating', es: 'skating', it: 'skating', sq: 'skating' },
  { en: 'jogging', tr: 'jogging', de: 'jogging', fr: 'jogging', es: 'jogging', it: 'jogging', sq: 'jogging' },
  { en: 'yoga', tr: 'yoga', de: 'yoga', fr: 'yoga', es: 'yoga', it: 'yoga', sq: 'yoga' },
  { en: 'diving', tr: 'diving', de: 'diving', fr: 'diving', es: 'diving', it: 'diving', sq: 'diving' },
  { en: 'volleyball', tr: 'volleyball', de: 'volleyball', fr: 'volleyball', es: 'volleyball', it: 'volleyball', sq: 'volleyball' },
  { en: 'hockey', tr: 'hockey', de: 'hockey', fr: 'hockey', es: 'hockey', it: 'hockey', sq: 'hockey' },
  { en: 'rugby', tr: 'rugby', de: 'rugby', fr: 'rugby', es: 'rugby', it: 'rugby', sq: 'rugby' },
  { en: 'badminton', tr: 'badminton', de: 'badminton', fr: 'badminton', es: 'badminton', it: 'badminton', sq: 'badminton' },
  { en: 'rowing', tr: 'rowing', de: 'rowing', fr: 'rowing', es: 'rowing', it: 'rowing', sq: 'rowing' },
  { en: 'kayaking', tr: 'kayaking', de: 'kayaking', fr: 'kayaking', es: 'kayaking', it: 'kayaking', sq: 'kayaking' },
  { en: 'snowboarding', tr: 'snowboarding', de: 'snowboarding', fr: 'snowboarding', es: 'snowboarding', it: 'snowboarding', sq: 'snowboarding' },
  { en: 'gymnastics', tr: 'gymnastics', de: 'gymnastics', fr: 'gymnastics', es: 'gymnastics', it: 'gymnastics', sq: 'gymnastics' },
  { en: 'martial arts', tr: 'martial arts', de: 'martial arts', fr: 'martial arts', es: 'martial arts', it: 'martial arts', sq: 'martial arts' },
  { en: 'weightlifting', tr: 'weightlifting', de: 'weightlifting', fr: 'weightlifting', es: 'weightlifting', it: 'weightlifting', sq: 'weightlifting' },
  { en: 'jumping', tr: 'jumping', de: 'jumping', fr: 'jumping', es: 'jumping', it: 'jumping', sq: 'jumping' },
  { en: 'climbing', tr: 'climbing', de: 'climbing', fr: 'climbing', es: 'climbing', it: 'climbing', sq: 'climbing' },
  { en: 'fencing', tr: 'fencing', de: 'fencing', fr: 'fencing', es: 'fencing', it: 'fencing', sq: 'fencing' },
  { en: 'archery', tr: 'archery', de: 'archery', fr: 'archery', es: 'archery', it: 'archery', sq: 'archery' },
  { en: 'bowling', tr: 'bowling', de: 'bowling', fr: 'bowling', es: 'bowling', it: 'bowling', sq: 'bowling' },
  { en: 'pool', tr: 'pool', de: 'pool', fr: 'pool', es: 'pool', it: 'pool', sq: 'pool' },
  { en: 'darts', tr: 'darts', de: 'darts', fr: 'darts', es: 'darts', it: 'darts', sq: 'darts' },
  { en: 'ping pong', tr: 'ping pong', de: 'ping pong', fr: 'ping pong', es: 'ping pong', it: 'ping pong', sq: 'ping pong' },
  { en: 'marathon', tr: 'marathon', de: 'marathon', fr: 'marathon', es: 'marathon', it: 'marathon', sq: 'marathon' },
  { en: 'sprint', tr: 'sprint', de: 'sprint', fr: 'sprint', es: 'sprint', it: 'sprint', sq: 'sprint' },
  { en: 'triathlon', tr: 'triathlon', de: 'triathlon', fr: 'triathlon', es: 'triathlon', it: 'triathlon', sq: 'triathlon' },
  { en: 'pentathlon', tr: 'pentathlon', de: 'pentathlon', fr: 'pentathlon', es: 'pentathlon', it: 'pentathlon', sq: 'pentathlon' },
  { en: 'decathlon', tr: 'decathlon', de: 'decathlon', fr: 'decathlon', es: 'decathlon', it: 'decathlon', sq: 'decathlon' },
  { en: 'parachuting', tr: 'parachuting', de: 'parachuting', fr: 'parachuting', es: 'parachuting', it: 'parachuting', sq: 'parachuting' },
  { en: 'hang gliding', tr: 'hang gliding', de: 'hang gliding', fr: 'hang gliding', es: 'hang gliding', it: 'hang gliding', sq: 'hang gliding' },
  { en: 'rock climbing', tr: 'rock climbing', de: 'rock climbing', fr: 'rock climbing', es: 'rock climbing', it: 'rock climbing', sq: 'rock climbing' },
  { en: 'bobsled', tr: 'bobsled', de: 'bobsled', fr: 'bobsled', es: 'bobsled', it: 'bobsled', sq: 'bobsled' },
  { en: 'curling', tr: 'curling', de: 'curling', fr: 'curling', es: 'curling', it: 'curling', sq: 'curling' },
  { en: 'polo', tr: 'polo', de: 'polo', fr: 'polo', es: 'polo', it: 'polo', sq: 'polo' },
  { en: 'lacrosse', tr: 'lacrosse', de: 'lacrosse', fr: 'lacrosse', es: 'lacrosse', it: 'lacrosse', sq: 'lacrosse' },
  { en: 'cricket', tr: 'cricket', de: 'cricket', fr: 'cricket', es: 'cricket', it: 'cricket', sq: 'cricket' },
  { en: 'squash', tr: 'squash', de: 'squash', fr: 'squash', es: 'squash', it: 'squash', sq: 'squash' },
  { en: 'racquetball', tr: 'racquetball', de: 'racquetball', fr: 'racquetball', es: 'racquetball', it: 'racquetball', sq: 'racquetball' },
  { en: 'javelin', tr: 'javelin', de: 'javelin', fr: 'javelin', es: 'javelin', it: 'javelin', sq: 'javelin' },
  { en: 'shot put', tr: 'shot put', de: 'shot put', fr: 'shot put', es: 'shot put', it: 'shot put', sq: 'shot put' },
  { en: 'discus', tr: 'discus', de: 'discus', fr: 'discus', es: 'discus', it: 'discus', sq: 'discus' },
  { en: 'hammer throw', tr: 'hammer throw', de: 'hammer throw', fr: 'hammer throw', es: 'hammer throw', it: 'hammer throw', sq: 'hammer throw' },
  { en: 'high jump', tr: 'high jump', de: 'high jump', fr: 'high jump', es: 'high jump', it: 'high jump', sq: 'high jump' },
  { en: 'long jump', tr: 'long jump', de: 'long jump', fr: 'long jump', es: 'long jump', it: 'long jump', sq: 'long jump' },
  { en: 'pole vault', tr: 'pole vault', de: 'pole vault', fr: 'pole vault', es: 'pole vault', it: 'pole vault', sq: 'pole vault' },
  { en: 'hurdles', tr: 'hurdles', de: 'hurdles', fr: 'hurdles', es: 'hurdles', it: 'hurdles', sq: 'hurdles' },
  { en: 'relay', tr: 'relay', de: 'relay', fr: 'relay', es: 'relay', it: 'relay', sq: 'relay' },
  { en: 'synchronized swimming', tr: 'synchronized swimming', de: 'synchronized swimming', fr: 'synchronized swimming', es: 'synchronized swimming', it: 'synchronized swimming', sq: 'synchronized swimming' },
  { en: 'water polo', tr: 'water polo', de: 'water polo', fr: 'water polo', es: 'water polo', it: 'water polo', sq: 'water polo' },
  { en: 'surfing', tr: 'surfing', de: 'surfing', fr: 'surfing', es: 'surfing', it: 'surfing', sq: 'surfing' },
  { en: 'windsurfing', tr: 'windsurfing', de: 'windsurfing', fr: 'windsurfing', es: 'windsurfing', it: 'windsurfing', sq: 'windsurfing' },
  { en: 'kitesurfing', tr: 'kitesurfing', de: 'kitesurfing', fr: 'kitesurfing', es: 'kitesurfing', it: 'kitesurfing', sq: 'kitesurfing' },
  { en: 'scuba diving', tr: 'scuba diving', de: 'scuba diving', fr: 'scuba diving', es: 'scuba diving', it: 'scuba diving', sq: 'scuba diving' },
  { en: 'snorkeling', tr: 'snorkeling', de: 'snorkeling', fr: 'snorkeling', es: 'snorkeling', it: 'snorkeling', sq: 'snorkeling' },
  { en: 'paragliding', tr: 'paragliding', de: 'paragliding', fr: 'paragliding', es: 'paragliding', it: 'paragliding', sq: 'paragliding' },
  { en: 'skydiving', tr: 'skydiving', de: 'skydiving', fr: 'skydiving', es: 'skydiving', it: 'skydiving', sq: 'skydiving' },
  { en: 'bungee jumping', tr: 'bungee jumping', de: 'bungee jumping', fr: 'bungee jumping', es: 'bungee jumping', it: 'bungee jumping', sq: 'bungee jumping' },
  { en: 'parkour', tr: 'parkour', de: 'parkour', fr: 'parkour', es: 'parkour', it: 'parkour', sq: 'parkour' },
  { en: 'breakdancing', tr: 'breakdancing', de: 'breakdancing', fr: 'breakdancing', es: 'breakdancing', it: 'breakdancing', sq: 'breakdancing' },
  { en: 'nurse', tr: 'nurse', de: 'nurse', fr: 'nurse', es: 'nurse', it: 'nurse', sq: 'nurse' },
  { en: 'driver', tr: 'driver', de: 'driver', fr: 'driver', es: 'driver', it: 'driver', sq: 'driver' },
  { en: 'chef', tr: 'chef', de: 'chef', fr: 'chef', es: 'chef', it: 'chef', sq: 'chef' },
  { en: 'artist', tr: 'artist', de: 'artist', fr: 'artist', es: 'artist', it: 'artist', sq: 'artist' },
  { en: 'singer', tr: 'singer', de: 'singer', fr: 'singer', es: 'singer', it: 'singer', sq: 'singer' },
  { en: 'actor', tr: 'actor', de: 'actor', fr: 'actor', es: 'actor', it: 'actor', sq: 'actor' },
  { en: 'farmer', tr: 'farmer', de: 'farmer', fr: 'farmer', es: 'farmer', it: 'farmer', sq: 'farmer' },
  { en: 'pilot', tr: 'pilot', de: 'pilot', fr: 'pilot', es: 'pilot', it: 'pilot', sq: 'pilot' },
  { en: 'soldier', tr: 'soldier', de: 'soldier', fr: 'soldier', es: 'soldier', it: 'soldier', sq: 'soldier' },
  { en: 'police', tr: 'police', de: 'police', fr: 'police', es: 'police', it: 'police', sq: 'police' },
  { en: 'lawyer', tr: 'lawyer', de: 'lawyer', fr: 'lawyer', es: 'lawyer', it: 'lawyer', sq: 'lawyer' },
  { en: 'judge', tr: 'judge', de: 'judge', fr: 'judge', es: 'judge', it: 'judge', sq: 'judge' },
  { en: 'writer', tr: 'writer', de: 'writer', fr: 'writer', es: 'writer', it: 'writer', sq: 'writer' },
  { en: 'journalist', tr: 'journalist', de: 'journalist', fr: 'journalist', es: 'journalist', it: 'journalist', sq: 'journalist' },
  { en: 'photographer', tr: 'photographer', de: 'photographer', fr: 'photographer', es: 'photographer', it: 'photographer', sq: 'photographer' },
  { en: 'architect', tr: 'architect', de: 'architect', fr: 'architect', es: 'architect', it: 'architect', sq: 'architect' },
  { en: 'engineer', tr: 'engineer', de: 'engineer', fr: 'engineer', es: 'engineer', it: 'engineer', sq: 'engineer' },
  { en: 'scientist', tr: 'scientist', de: 'scientist', fr: 'scientist', es: 'scientist', it: 'scientist', sq: 'scientist' },
  { en: 'astronaut', tr: 'astronaut', de: 'astronaut', fr: 'astronaut', es: 'astronaut', it: 'astronaut', sq: 'astronaut' },
  { en: 'firefighter', tr: 'firefighter', de: 'firefighter', fr: 'firefighter', es: 'firefighter', it: 'firefighter', sq: 'firefighter' },
  { en: 'mechanic', tr: 'mechanic', de: 'mechanic', fr: 'mechanic', es: 'mechanic', it: 'mechanic', sq: 'mechanic' },
  { en: 'electrician', tr: 'electrician', de: 'electrician', fr: 'electrician', es: 'electrician', it: 'electrician', sq: 'electrician' },
  { en: 'plumber', tr: 'plumber', de: 'plumber', fr: 'plumber', es: 'plumber', it: 'plumber', sq: 'plumber' },
  { en: 'carpenter', tr: 'carpenter', de: 'carpenter', fr: 'carpenter', es: 'carpenter', it: 'carpenter', sq: 'carpenter' },
  { en: 'painter', tr: 'painter', de: 'painter', fr: 'painter', es: 'painter', it: 'painter', sq: 'painter' },
  { en: 'tailor', tr: 'tailor', de: 'tailor', fr: 'tailor', es: 'tailor', it: 'tailor', sq: 'tailor' },
  { en: 'barber', tr: 'barber', de: 'barber', fr: 'barber', es: 'barber', it: 'barber', sq: 'barber' },
  { en: 'dentist', tr: 'dentist', de: 'dentist', fr: 'dentist', es: 'dentist', it: 'dentist', sq: 'dentist' },
  { en: 'vet', tr: 'vet', de: 'vet', fr: 'vet', es: 'vet', it: 'vet', sq: 'vet' },
  { en: 'librarian', tr: 'librarian', de: 'librarian', fr: 'librarian', es: 'librarian', it: 'librarian', sq: 'librarian' },
  { en: 'accountant', tr: 'accountant', de: 'accountant', fr: 'accountant', es: 'accountant', it: 'accountant', sq: 'accountant' },
  { en: 'banker', tr: 'banker', de: 'banker', fr: 'banker', es: 'banker', it: 'banker', sq: 'banker' },
  { en: 'realtor', tr: 'realtor', de: 'realtor', fr: 'realtor', es: 'realtor', it: 'realtor', sq: 'realtor' },
  { en: 'detective', tr: 'detective', de: 'detective', fr: 'detective', es: 'detective', it: 'detective', sq: 'detective' },
  { en: 'spy', tr: 'spy', de: 'spy', fr: 'spy', es: 'spy', it: 'spy', sq: 'spy' },
  { en: 'magician', tr: 'magician', de: 'magician', fr: 'magician', es: 'magician', it: 'magician', sq: 'magician' },
  { en: 'clown', tr: 'clown', de: 'clown', fr: 'clown', es: 'clown', it: 'clown', sq: 'clown' },
  { en: 'dancer', tr: 'dancer', de: 'dancer', fr: 'dancer', es: 'dancer', it: 'dancer', sq: 'dancer' },
  { en: 'musician', tr: 'musician', de: 'musician', fr: 'musician', es: 'musician', it: 'musician', sq: 'musician' },
  { en: 'composer', tr: 'composer', de: 'composer', fr: 'composer', es: 'composer', it: 'composer', sq: 'composer' },
  { en: 'conductor', tr: 'conductor', de: 'conductor', fr: 'conductor', es: 'conductor', it: 'conductor', sq: 'conductor' },
  { en: 'curator', tr: 'curator', de: 'curator', fr: 'curator', es: 'curator', it: 'curator', sq: 'curator' },
  { en: 'archivist', tr: 'archivist', de: 'archivist', fr: 'archivist', es: 'archivist', it: 'archivist', sq: 'archivist' },
  { en: 'anthropologist', tr: 'anthropologist', de: 'anthropologist', fr: 'anthropologist', es: 'anthropologist', it: 'anthropologist', sq: 'anthropologist' },
  { en: 'archaeologist', tr: 'archaeologist', de: 'archaeologist', fr: 'archaeologist', es: 'archaeologist', it: 'archaeologist', sq: 'archaeologist' },
  { en: 'geologist', tr: 'geologist', de: 'geologist', fr: 'geologist', es: 'geologist', it: 'geologist', sq: 'geologist' },
  { en: 'astronomer', tr: 'astronomer', de: 'astronomer', fr: 'astronomer', es: 'astronomer', it: 'astronomer', sq: 'astronomer' },
  { en: 'biologist', tr: 'biologist', de: 'biologist', fr: 'biologist', es: 'biologist', it: 'biologist', sq: 'biologist' },
  { en: 'chemist', tr: 'chemist', de: 'chemist', fr: 'chemist', es: 'chemist', it: 'chemist', sq: 'chemist' },
  { en: 'physicist', tr: 'physicist', de: 'physicist', fr: 'physicist', es: 'physicist', it: 'physicist', sq: 'physicist' },
  { en: 'psychologist', tr: 'psychologist', de: 'psychologist', fr: 'psychologist', es: 'psychologist', it: 'psychologist', sq: 'psychologist' },
  { en: 'therapist', tr: 'therapist', de: 'therapist', fr: 'therapist', es: 'therapist', it: 'therapist', sq: 'therapist' },
  { en: 'surgeon', tr: 'surgeon', de: 'surgeon', fr: 'surgeon', es: 'surgeon', it: 'surgeon', sq: 'surgeon' },
  { en: 'paramedic', tr: 'paramedic', de: 'paramedic', fr: 'paramedic', es: 'paramedic', it: 'paramedic', sq: 'paramedic' },
  { en: 'pharmacist', tr: 'pharmacist', de: 'pharmacist', fr: 'pharmacist', es: 'pharmacist', it: 'pharmacist', sq: 'pharmacist' },
  { en: 'diplomat', tr: 'diplomat', de: 'diplomat', fr: 'diplomat', es: 'diplomat', it: 'diplomat', sq: 'diplomat' },
  { en: 'ambassador', tr: 'ambassador', de: 'ambassador', fr: 'ambassador', es: 'ambassador', it: 'ambassador', sq: 'ambassador' },
  { en: 'magistrate', tr: 'magistrate', de: 'magistrate', fr: 'magistrate', es: 'magistrate', it: 'magistrate', sq: 'magistrate' },
  { en: 'notary', tr: 'notary', de: 'notary', fr: 'notary', es: 'notary', it: 'notary', sq: 'notary' },
  { en: 'auditor', tr: 'auditor', de: 'auditor', fr: 'auditor', es: 'auditor', it: 'auditor', sq: 'auditor' },
  { en: 'actuary', tr: 'actuary', de: 'actuary', fr: 'actuary', es: 'actuary', it: 'actuary', sq: 'actuary' },
  { en: 'cartographer', tr: 'cartographer', de: 'cartographer', fr: 'cartographer', es: 'cartographer', it: 'cartographer', sq: 'cartographer' },
  { en: 'translator', tr: 'translator', de: 'translator', fr: 'translator', es: 'translator', it: 'translator', sq: 'translator' },
  { en: 'interpreter', tr: 'interpreter', de: 'interpreter', fr: 'interpreter', es: 'interpreter', it: 'interpreter', sq: 'interpreter' },
  { en: 'editor', tr: 'editor', de: 'editor', fr: 'editor', es: 'editor', it: 'editor', sq: 'editor' },
  { en: 'publisher', tr: 'publisher', de: 'publisher', fr: 'publisher', es: 'publisher', it: 'publisher', sq: 'publisher' },
  { en: 'illustrator', tr: 'illustrator', de: 'illustrator', fr: 'illustrator', es: 'illustrator', it: 'illustrator', sq: 'illustrator' },
  { en: 'sculptor', tr: 'sculptor', de: 'sculptor', fr: 'sculptor', es: 'sculptor', it: 'sculptor', sq: 'sculptor' },
  { en: 'potter', tr: 'potter', de: 'potter', fr: 'potter', es: 'potter', it: 'potter', sq: 'potter' },
  { en: 'blacksmith', tr: 'blacksmith', de: 'blacksmith', fr: 'blacksmith', es: 'blacksmith', it: 'blacksmith', sq: 'blacksmith' },
  { en: 'jeweler', tr: 'jeweler', de: 'jeweler', fr: 'jeweler', es: 'jeweler', it: 'jeweler', sq: 'jeweler' },
  { en: 'watchmaker', tr: 'watchmaker', de: 'watchmaker', fr: 'watchmaker', es: 'watchmaker', it: 'watchmaker', sq: 'watchmaker' },
  { en: 'locksmith', tr: 'locksmith', de: 'locksmith', fr: 'locksmith', es: 'locksmith', it: 'locksmith', sq: 'locksmith' },
  { en: 'florist', tr: 'florist', de: 'florist', fr: 'florist', es: 'florist', it: 'florist', sq: 'florist' },
  { en: 'sommelier', tr: 'sommelier', de: 'sommelier', fr: 'sommelier', es: 'sommelier', it: 'sommelier', sq: 'sommelier' },
  { en: 'maitre d', tr: 'maitre d', de: 'Ober', fr: 'maître d\'hôtel', es: 'maître', it: 'maître', sq: 'maitre d' },
  { en: 'concierge', tr: 'concierge', de: 'concierge', fr: 'concierge', es: 'concierge', it: 'concierge', sq: 'concierge' },
  { en: 'steward', tr: 'steward', de: 'steward', fr: 'steward', es: 'steward', it: 'steward', sq: 'steward' },
  { en: 'navigator', tr: 'navigator', de: 'navigator', fr: 'navigator', es: 'navigator', it: 'navigator', sq: 'navigator' },
  { en: 'park', tr: 'park', de: 'park', fr: 'park', es: 'park', it: 'park', sq: 'park' },
  { en: 'hospital', tr: 'hospital', de: 'hospital', fr: 'hospital', es: 'hospital', it: 'hospital', sq: 'hospital' },
  { en: 'hotel', tr: 'hotel', de: 'hotel', fr: 'hotel', es: 'hotel', it: 'hotel', sq: 'hotel' },
  { en: 'shop', tr: 'shop', de: 'shop', fr: 'shop', es: 'shop', it: 'shop', sq: 'shop' },
  { en: 'street', tr: 'street', de: 'street', fr: 'street', es: 'street', it: 'street', sq: 'street' },
  { en: 'library', tr: 'library', de: 'library', fr: 'library', es: 'library', it: 'library', sq: 'library' },
  { en: 'museum', tr: 'museum', de: 'museum', fr: 'museum', es: 'museum', it: 'museum', sq: 'museum' },
  { en: 'cinema', tr: 'cinema', de: 'cinema', fr: 'cinema', es: 'cinema', it: 'cinema', sq: 'cinema' },
  { en: 'stadium', tr: 'stadium', de: 'stadium', fr: 'stadium', es: 'stadium', it: 'stadium', sq: 'stadium' },
  { en: 'airport', tr: 'airport', de: 'airport', fr: 'airport', es: 'airport', it: 'airport', sq: 'airport' },
  { en: 'station', tr: 'station', de: 'station', fr: 'station', es: 'station', it: 'station', sq: 'station' },
  { en: 'harbor', tr: 'harbor', de: 'harbor', fr: 'harbor', es: 'harbor', it: 'harbor', sq: 'harbor' },
  { en: 'market', tr: 'market', de: 'market', fr: 'market', es: 'market', it: 'market', sq: 'market' },
  { en: 'mall', tr: 'mall', de: 'mall', fr: 'mall', es: 'mall', it: 'mall', sq: 'mall' },
  { en: 'bank', tr: 'bank', de: 'bank', fr: 'bank', es: 'bank', it: 'bank', sq: 'bank' },
  { en: 'post office', tr: 'post office', de: 'post office', fr: 'post office', es: 'post office', it: 'post office', sq: 'post office' },
  { en: 'courthouse', tr: 'courthouse', de: 'courthouse', fr: 'courthouse', es: 'courthouse', it: 'courthouse', sq: 'courthouse' },
  { en: 'prison', tr: 'prison', de: 'prison', fr: 'prison', es: 'prison', it: 'prison', sq: 'prison' },
  { en: 'church', tr: 'church', de: 'church', fr: 'church', es: 'church', it: 'church', sq: 'church' },
  { en: 'temple', tr: 'temple', de: 'temple', fr: 'temple', es: 'temple', it: 'temple', sq: 'temple' },
  { en: 'mosque', tr: 'mosque', de: 'mosque', fr: 'mosque', es: 'mosque', it: 'mosque', sq: 'mosque' },
  { en: 'castle', tr: 'castle', de: 'castle', fr: 'castle', es: 'castle', it: 'castle', sq: 'castle' },
  { en: 'palace', tr: 'palace', de: 'palace', fr: 'palace', es: 'palace', it: 'palace', sq: 'palace' },
  { en: 'tower', tr: 'tower', de: 'tower', fr: 'tower', es: 'tower', it: 'tower', sq: 'tower' },
  { en: 'bridge', tr: 'bridge', de: 'bridge', fr: 'bridge', es: 'bridge', it: 'bridge', sq: 'bridge' },
  { en: 'tunnel', tr: 'tunnel', de: 'tunnel', fr: 'tunnel', es: 'tunnel', it: 'tunnel', sq: 'tunnel' },
  { en: 'highway', tr: 'highway', de: 'highway', fr: 'highway', es: 'highway', it: 'highway', sq: 'highway' },
  { en: 'boulevard', tr: 'boulevard', de: 'boulevard', fr: 'boulevard', es: 'boulevard', it: 'boulevard', sq: 'boulevard' },
  { en: 'alley', tr: 'alley', de: 'alley', fr: 'alley', es: 'alley', it: 'alley', sq: 'alley' },
  { en: 'square', tr: 'square', de: 'square', fr: 'square', es: 'square', it: 'square', sq: 'square' },
  { en: 'fountain', tr: 'fountain', de: 'fountain', fr: 'fountain', es: 'fountain', it: 'fountain', sq: 'fountain' },
  { en: 'monument', tr: 'monument', de: 'monument', fr: 'monument', es: 'monument', it: 'monument', sq: 'monument' },
  { en: 'cemetery', tr: 'cemetery', de: 'cemetery', fr: 'cemetery', es: 'cemetery', it: 'cemetery', sq: 'cemetery' },
  { en: 'zoo', tr: 'zoo', de: 'zoo', fr: 'zoo', es: 'zoo', it: 'zoo', sq: 'zoo' },
  { en: 'aquarium', tr: 'aquarium', de: 'aquarium', fr: 'aquarium', es: 'aquarium', it: 'aquarium', sq: 'aquarium' },
  { en: 'gym', tr: 'gym', de: 'gym', fr: 'gym', es: 'gym', it: 'gym', sq: 'gym' },
  { en: 'pool', tr: 'pool', de: 'pool', fr: 'pool', es: 'pool', it: 'pool', sq: 'pool' },
  { en: 'arena', tr: 'arena', de: 'arena', fr: 'arena', es: 'arena', it: 'arena', sq: 'arena' },
  { en: 'theater', tr: 'theater', de: 'theater', fr: 'theater', es: 'theater', it: 'theater', sq: 'theater' },
  { en: 'gallery', tr: 'gallery', de: 'gallery', fr: 'gallery', es: 'gallery', it: 'gallery', sq: 'gallery' },
  { en: 'bakery', tr: 'bakery', de: 'bakery', fr: 'bakery', es: 'bakery', it: 'bakery', sq: 'bakery' },
  { en: 'cafe', tr: 'cafe', de: 'cafe', fr: 'cafe', es: 'cafe', it: 'cafe', sq: 'cafe' },
  { en: 'bar', tr: 'bar', de: 'bar', fr: 'bar', es: 'bar', it: 'bar', sq: 'bar' },
  { en: 'warehouse', tr: 'warehouse', de: 'warehouse', fr: 'warehouse', es: 'warehouse', it: 'warehouse', sq: 'warehouse' },
  { en: 'factory', tr: 'factory', de: 'factory', fr: 'factory', es: 'factory', it: 'factory', sq: 'factory' },
  { en: 'laboratory', tr: 'laboratory', de: 'laboratory', fr: 'laboratory', es: 'laboratory', it: 'laboratory', sq: 'laboratory' },
  { en: 'observatory', tr: 'observatory', de: 'observatory', fr: 'observatory', es: 'observatory', it: 'observatory', sq: 'observatory' },
  { en: 'planetarium', tr: 'planetarium', de: 'planetarium', fr: 'planetarium', es: 'planetarium', it: 'planetarium', sq: 'planetarium' },
  { en: 'cathedral', tr: 'cathedral', de: 'cathedral', fr: 'cathedral', es: 'cathedral', it: 'cathedral', sq: 'cathedral' },
  { en: 'monastery', tr: 'monastery', de: 'monastery', fr: 'monastery', es: 'monastery', it: 'monastery', sq: 'monastery' },
  { en: 'convent', tr: 'convent', de: 'convent', fr: 'convent', es: 'convent', it: 'convent', sq: 'convent' },
  { en: 'mausoleum', tr: 'mausoleum', de: 'mausoleum', fr: 'mausoleum', es: 'mausoleum', it: 'mausoleum', sq: 'mausoleum' },
  { en: 'colosseum', tr: 'colosseum', de: 'colosseum', fr: 'colosseum', es: 'colosseum', it: 'colosseum', sq: 'colosseum' },
  { en: 'amphitheater', tr: 'amphitheater', de: 'amphitheater', fr: 'amphitheater', es: 'amphitheater', it: 'amphitheater', sq: 'amphitheater' },
  { en: 'pavilion', tr: 'pavilion', de: 'pavilion', fr: 'pavilion', es: 'pavilion', it: 'pavilion', sq: 'pavilion' },
  { en: 'gazebo', tr: 'gazebo', de: 'gazebo', fr: 'gazebo', es: 'gazebo', it: 'gazebo', sq: 'gazebo' },
  { en: 'lighthouse', tr: 'lighthouse', de: 'lighthouse', fr: 'lighthouse', es: 'lighthouse', it: 'lighthouse', sq: 'lighthouse' },
  { en: 'windmill', tr: 'windmill', de: 'windmill', fr: 'windmill', es: 'windmill', it: 'windmill', sq: 'windmill' },
  { en: 'watermill', tr: 'watermill', de: 'watermill', fr: 'watermill', es: 'watermill', it: 'watermill', sq: 'watermill' },
  { en: 'barn', tr: 'barn', de: 'barn', fr: 'barn', es: 'barn', it: 'barn', sq: 'barn' },
  { en: 'silo', tr: 'silo', de: 'silo', fr: 'silo', es: 'silo', it: 'silo', sq: 'silo' },
  { en: 'greenhouse', tr: 'greenhouse', de: 'greenhouse', fr: 'greenhouse', es: 'greenhouse', it: 'greenhouse', sq: 'greenhouse' },
  { en: 'conservatory', tr: 'conservatory', de: 'conservatory', fr: 'conservatory', es: 'conservatory', it: 'conservatory', sq: 'conservatory' },
  { en: 'arboretum', tr: 'arboretum', de: 'arboretum', fr: 'arboretum', es: 'arboretum', it: 'arboretum', sq: 'arboretum' },
  { en: 'botanical garden', tr: 'botanical garden', de: 'botanical garden', fr: 'botanical garden', es: 'botanical garden', it: 'botanical garden', sq: 'botanical garden' },
  { en: 'vineyard', tr: 'vineyard', de: 'vineyard', fr: 'vineyard', es: 'vineyard', it: 'vineyard', sq: 'vineyard' },
  { en: 'brewery', tr: 'brewery', de: 'brewery', fr: 'brewery', es: 'brewery', it: 'brewery', sq: 'brewery' },
  { en: 'distillery', tr: 'distillery', de: 'distillery', fr: 'distillery', es: 'distillery', it: 'distillery', sq: 'distillery' },
  { en: 'boutique', tr: 'boutique', de: 'boutique', fr: 'boutique', es: 'boutique', it: 'boutique', sq: 'boutique' },
  { en: 'emporium', tr: 'emporium', de: 'emporium', fr: 'emporium', es: 'emporium', it: 'emporium', sq: 'emporium' },
  { en: 'bazaar', tr: 'bazaar', de: 'bazaar', fr: 'bazaar', es: 'bazaar', it: 'bazaar', sq: 'bazaar' },
  { en: 'downtown', tr: 'downtown', de: 'downtown', fr: 'downtown', es: 'downtown', it: 'downtown', sq: 'downtown' },
  { en: 'suburb', tr: 'suburb', de: 'suburb', fr: 'suburb', es: 'suburb', it: 'suburb', sq: 'suburb' },
  { en: 'countryside', tr: 'countryside', de: 'countryside', fr: 'countryside', es: 'countryside', it: 'countryside', sq: 'countryside' },
  { en: 'metropolis', tr: 'metropolis', de: 'metropolis', fr: 'metropolis', es: 'metropolis', it: 'metropolis', sq: 'metropolis' },
  { en: 'capital', tr: 'capital', de: 'capital', fr: 'capital', es: 'capital', it: 'capital', sq: 'capital' },
  { en: 'border', tr: 'border', de: 'border', fr: 'border', es: 'border', it: 'border', sq: 'border' },
  { en: 'checkpoint', tr: 'checkpoint', de: 'checkpoint', fr: 'checkpoint', es: 'checkpoint', it: 'checkpoint', sq: 'checkpoint' },
  { en: 'terminal', tr: 'terminal', de: 'terminal', fr: 'terminal', es: 'terminal', it: 'terminal', sq: 'terminal' },
  { en: 'depot', tr: 'depot', de: 'depot', fr: 'depot', es: 'depot', it: 'depot', sq: 'depot' },
  { en: 'dock', tr: 'dock', de: 'dock', fr: 'dock', es: 'dock', it: 'dock', sq: 'dock' },
  { en: 'pier', tr: 'pier', de: 'pier', fr: 'pier', es: 'pier', it: 'pier', sq: 'pier' },
  { en: 'marina', tr: 'marina', de: 'marina', fr: 'marina', es: 'marina', it: 'marina', sq: 'marina' },
  { en: 'canal', tr: 'canal', de: 'canal', fr: 'canal', es: 'canal', it: 'canal', sq: 'canal' },
  { en: 'reservoir', tr: 'reservoir', de: 'reservoir', fr: 'reservoir', es: 'reservoir', it: 'reservoir', sq: 'reservoir' },
  { en: 'walking', tr: 'walking', de: 'walking', fr: 'walking', es: 'walking', it: 'walking', sq: 'walking' },
  { en: 'eating', tr: 'eating', de: 'eating', fr: 'eating', es: 'eating', it: 'eating', sq: 'eating' },
  { en: 'watching', tr: 'watching', de: 'watching', fr: 'watching', es: 'watching', it: 'watching', sq: 'watching' },
  { en: 'listening', tr: 'listening', de: 'listening', fr: 'listening', es: 'listening', it: 'listening', sq: 'listening' },
  { en: 'drawing', tr: 'drawing', de: 'drawing', fr: 'drawing', es: 'drawing', it: 'drawing', sq: 'drawing' },
  { en: 'writing', tr: 'writing', de: 'writing', fr: 'writing', es: 'writing', it: 'writing', sq: 'writing' },
  { en: 'cleaning', tr: 'cleaning', de: 'cleaning', fr: 'cleaning', es: 'cleaning', it: 'cleaning', sq: 'cleaning' },
  { en: 'shopping', tr: 'shopping', de: 'shopping', fr: 'shopping', es: 'shopping', it: 'shopping', sq: 'shopping' },
  { en: 'driving', tr: 'driving', de: 'driving', fr: 'driving', es: 'driving', it: 'driving', sq: 'driving' },
  { en: 'riding', tr: 'riding', de: 'riding', fr: 'riding', es: 'riding', it: 'riding', sq: 'riding' },
  { en: 'studying', tr: 'studying', de: 'studying', fr: 'studying', es: 'studying', it: 'studying', sq: 'studying' },
  { en: 'traveling', tr: 'traveling', de: 'traveling', fr: 'traveling', es: 'traveling', it: 'traveling', sq: 'traveling' },
  { en: 'gardening', tr: 'gardening', de: 'gardening', fr: 'gardening', es: 'gardening', it: 'gardening', sq: 'gardening' },
  { en: 'baking', tr: 'baking', de: 'baking', fr: 'baking', es: 'baking', it: 'baking', sq: 'baking' },
  { en: 'knitting', tr: 'knitting', de: 'knitting', fr: 'knitting', es: 'knitting', it: 'knitting', sq: 'knitting' },
  { en: 'sewing', tr: 'sewing', de: 'sewing', fr: 'sewing', es: 'sewing', it: 'sewing', sq: 'sewing' },
  { en: 'meditation', tr: 'meditation', de: 'meditation', fr: 'meditation', es: 'meditation', it: 'meditation', sq: 'meditation' },
  { en: 'stretching', tr: 'stretching', de: 'stretching', fr: 'stretching', es: 'stretching', it: 'stretching', sq: 'stretching' },
  { en: 'jogging', tr: 'jogging', de: 'jogging', fr: 'jogging', es: 'jogging', it: 'jogging', sq: 'jogging' },
  { en: 'hiking', tr: 'hiking', de: 'hiking', fr: 'hiking', es: 'hiking', it: 'hiking', sq: 'hiking' },
  { en: 'camping', tr: 'camping', de: 'camping', fr: 'camping', es: 'camping', it: 'camping', sq: 'camping' },
  { en: 'picnicking', tr: 'picnicking', de: 'picnicking', fr: 'picnicking', es: 'picnicking', it: 'picnicking', sq: 'picnicking' },
  { en: 'barbecuing', tr: 'barbecuing', de: 'barbecuing', fr: 'barbecuing', es: 'barbecuing', it: 'barbecuing', sq: 'barbecuing' },
  { en: 'playing', tr: 'playing', de: 'playing', fr: 'playing', es: 'playing', it: 'playing', sq: 'playing' },
  { en: 'dancing', tr: 'dancing', de: 'dancing', fr: 'dancing', es: 'dancing', it: 'dancing', sq: 'dancing' },
  { en: 'acting', tr: 'acting', de: 'acting', fr: 'acting', es: 'acting', it: 'acting', sq: 'acting' },
  { en: 'filming', tr: 'filming', de: 'filming', fr: 'filming', es: 'filming', it: 'filming', sq: 'filming' },
  { en: 'editing', tr: 'editing', de: 'editing', fr: 'editing', es: 'editing', it: 'editing', sq: 'editing' },
  { en: 'blogging', tr: 'blogging', de: 'blogging', fr: 'blogging', es: 'blogging', it: 'blogging', sq: 'blogging' },
  { en: 'streaming', tr: 'streaming', de: 'streaming', fr: 'streaming', es: 'streaming', it: 'streaming', sq: 'streaming' },
  { en: 'gaming', tr: 'gaming', de: 'gaming', fr: 'gaming', es: 'gaming', it: 'gaming', sq: 'gaming' },
  { en: 'puzzling', tr: 'puzzling', de: 'puzzling', fr: 'puzzling', es: 'puzzling', it: 'puzzling', sq: 'puzzling' },
  { en: 'scrapbooking', tr: 'scrapbooking', de: 'scrapbooking', fr: 'scrapbooking', es: 'scrapbooking', it: 'scrapbooking', sq: 'scrapbooking' },
  { en: 'collecting', tr: 'collecting', de: 'collecting', fr: 'collecting', es: 'collecting', it: 'collecting', sq: 'collecting' },
  { en: 'volunteering', tr: 'volunteering', de: 'volunteering', fr: 'volunteering', es: 'volunteering', it: 'volunteering', sq: 'volunteering' },
  { en: 'donating', tr: 'donating', de: 'donating', fr: 'donating', es: 'donating', it: 'donating', sq: 'donating' },
  { en: 'recycling', tr: 'recycling', de: 'recycling', fr: 'recycling', es: 'recycling', it: 'recycling', sq: 'recycling' },
  { en: 'composting', tr: 'composting', de: 'composting', fr: 'composting', es: 'composting', it: 'composting', sq: 'composting' },
  { en: 'birdwatching', tr: 'birdwatching', de: 'birdwatching', fr: 'birdwatching', es: 'birdwatching', it: 'birdwatching', sq: 'birdwatching' },
  { en: 'stargazing', tr: 'stargazing', de: 'stargazing', fr: 'stargazing', es: 'stargazing', it: 'stargazing', sq: 'stargazing' },
  { en: 'geocaching', tr: 'geocaching', de: 'geocaching', fr: 'geocaching', es: 'geocaching', it: 'geocaching', sq: 'geocaching' },
  { en: 'orienteering', tr: 'orienteering', de: 'orienteering', fr: 'orienteering', es: 'orienteering', it: 'orienteering', sq: 'orienteering' },
  { en: 'calligraphy', tr: 'calligraphy', de: 'calligraphy', fr: 'calligraphy', es: 'calligraphy', it: 'calligraphy', sq: 'calligraphy' },
  { en: 'origami', tr: 'origami', de: 'origami', fr: 'origami', es: 'origami', it: 'origami', sq: 'origami' },
  { en: 'pottery', tr: 'pottery', de: 'pottery', fr: 'pottery', es: 'pottery', it: 'pottery', sq: 'pottery' },
  { en: 'weaving', tr: 'weaving', de: 'weaving', fr: 'weaving', es: 'weaving', it: 'weaving', sq: 'weaving' },
  { en: 'embroidery', tr: 'embroidery', de: 'embroidery', fr: 'embroidery', es: 'embroidery', it: 'embroidery', sq: 'embroidery' },
  { en: 'quilting', tr: 'quilting', de: 'quilting', fr: 'quilting', es: 'quilting', it: 'quilting', sq: 'quilting' },
  { en: 'woodworking', tr: 'woodworking', de: 'woodworking', fr: 'woodworking', es: 'woodworking', it: 'woodworking', sq: 'woodworking' },
  { en: 'metalworking', tr: 'metalworking', de: 'metalworking', fr: 'metalworking', es: 'metalworking', it: 'metalworking', sq: 'metalworking' },
  { en: 'blacksmithing', tr: 'blacksmithing', de: 'blacksmithing', fr: 'blacksmithing', es: 'blacksmithing', it: 'blacksmithing', sq: 'blacksmithing' },
  { en: 'whittling', tr: 'whittling', de: 'whittling', fr: 'whittling', es: 'whittling', it: 'whittling', sq: 'whittling' },
  { en: 'sculpting', tr: 'sculpting', de: 'sculpting', fr: 'sculpting', es: 'sculpting', it: 'sculpting', sq: 'sculpting' },
  { en: 'sketching', tr: 'sketching', de: 'sketching', fr: 'sketching', es: 'sketching', it: 'sketching', sq: 'sketching' },
  { en: 'watercolor', tr: 'watercolor', de: 'watercolor', fr: 'watercolor', es: 'watercolor', it: 'watercolor', sq: 'watercolor' },
  { en: 'journaling', tr: 'journaling', de: 'journaling', fr: 'journaling', es: 'journaling', it: 'journaling', sq: 'journaling' },
  { en: 'storytelling', tr: 'storytelling', de: 'storytelling', fr: 'storytelling', es: 'storytelling', it: 'storytelling', sq: 'storytelling' },
  { en: 'debating', tr: 'debating', de: 'debating', fr: 'debating', es: 'debating', it: 'debating', sq: 'debating' },
  { en: 'negotiating', tr: 'negotiating', de: 'negotiating', fr: 'negotiating', es: 'negotiating', it: 'negotiating', sq: 'negotiating' },
  { en: 'mentoring', tr: 'mentoring', de: 'mentoring', fr: 'mentoring', es: 'mentoring', it: 'mentoring', sq: 'mentoring' },
  { en: 'tutoring', tr: 'tutoring', de: 'tutoring', fr: 'tutoring', es: 'tutoring', it: 'tutoring', sq: 'tutoring' },
  { en: 'researching', tr: 'researching', de: 'researching', fr: 'researching', es: 'researching', it: 'researching', sq: 'researching' },
  { en: 'experimenting', tr: 'experimenting', de: 'experimenting', fr: 'experimenting', es: 'experimenting', it: 'experimenting', sq: 'experimenting' },
  { en: 'inventing', tr: 'inventing', de: 'inventing', fr: 'inventing', es: 'inventing', it: 'inventing', sq: 'inventing' },
  { en: 'composing', tr: 'composing', de: 'composing', fr: 'composing', es: 'composing', it: 'composing', sq: 'composing' },
  { en: 'improvising', tr: 'improvising', de: 'improvising', fr: 'improvising', es: 'improvising', it: 'improvising', sq: 'improvising' },
  { en: 'conducting', tr: 'conducting', de: 'conducting', fr: 'conducting', es: 'conducting', it: 'conducting', sq: 'conducting' },
  { en: 'choreographing', tr: 'choreographing', de: 'choreographing', fr: 'choreographing', es: 'choreographing', it: 'choreographing', sq: 'choreographing' },
  { en: 'directing', tr: 'directing', de: 'directing', fr: 'directing', es: 'directing', it: 'directing', sq: 'directing' },
  { en: 'producing', tr: 'producing', de: 'producing', fr: 'producing', es: 'producing', it: 'producing', sq: 'producing' },
  { en: 'broadcasting', tr: 'broadcasting', de: 'broadcasting', fr: 'broadcasting', es: 'broadcasting', it: 'broadcasting', sq: 'broadcasting' },
  { en: 'podcasting', tr: 'podcasting', de: 'podcasting', fr: 'podcasting', es: 'podcasting', it: 'podcasting', sq: 'podcasting' },
  { en: 'vlogging', tr: 'vlogging', de: 'vlogging', fr: 'vlogging', es: 'vlogging', it: 'vlogging', sq: 'vlogging' },
  { en: 'photography', tr: 'photography', de: 'photography', fr: 'photography', es: 'photography', it: 'photography', sq: 'photography' },
  { en: 'videography', tr: 'videography', de: 'videography', fr: 'videography', es: 'videography', it: 'videography', sq: 'videography' },
  { en: 'animating', tr: 'animating', de: 'animating', fr: 'animating', es: 'animating', it: 'animating', sq: 'animating' },
  { en: 'designing', tr: 'designing', de: 'designing', fr: 'designing', es: 'designing', it: 'designing', sq: 'designing' },
  { en: 'programming', tr: 'programming', de: 'programming', fr: 'programming', es: 'programming', it: 'programming', sq: 'programming' },
  { en: 'debugging', tr: 'debugging', de: 'debugging', fr: 'debugging', es: 'debugging', it: 'debugging', sq: 'debugging' },
  { en: 'networking', tr: 'networking', de: 'networking', fr: 'networking', es: 'networking', it: 'networking', sq: 'networking' },
  { en: 'presenting', tr: 'presenting', de: 'presenting', fr: 'presenting', es: 'presenting', it: 'presenting', sq: 'presenting' },
  { en: 'public speaking', tr: 'public speaking', de: 'public speaking', fr: 'public speaking', es: 'public speaking', it: 'public speaking', sq: 'public speaking' },
  { en: 'brainstorming', tr: 'brainstorming', de: 'brainstorming', fr: 'brainstorming', es: 'brainstorming', it: 'brainstorming', sq: 'brainstorming' },
  { en: 'problem solving', tr: 'problem solving', de: 'problem solving', fr: 'problem solving', es: 'problem solving', it: 'problem solving', sq: 'problem solving' }
];
