module.exports = [
  { word: 'të kërcesh', category: 'activities', difficulty: 'easy' },
  { word: 'të notosh', category: 'activities', difficulty: 'easy' },
  { word: 'të lexosh', category: 'activities', difficulty: 'easy' },
  { word: 'të gatuash', category: 'activities', difficulty: 'easy' },
  { word: 'të këndosh', category: 'activities', difficulty: 'easy' },
  { word: 'të vraposh', category: 'sports', difficulty: 'easy' },
  { word: 'të flesh', category: 'activities', difficulty: 'easy' },
  { word: 'të peshkosh', category: 'activities', difficulty: 'easy' },
  { word: 'të pikturosh', category: 'activities', difficulty: 'medium' },
  { word: 'futboll', category: 'sports', difficulty: 'easy' },
  { word: 'basketboll', category: 'sports', difficulty: 'easy' },
  { word: 'tenis', category: 'sports', difficulty: 'easy' },
  { word: 'elefant', category: 'animals', difficulty: 'easy' },
  { word: 'flutur', category: 'animals', difficulty: 'medium' },
  { word: 'aeroplan', category: 'objects', difficulty: 'easy' },
  { word: 'ombrellë', category: 'objects', difficulty: 'easy' },
  { word: 'telefon', category: 'objects', difficulty: 'easy' },
  { word: 'pica', category: 'food', difficulty: 'easy' },
  { word: 'ditëlindje', category: 'emotions', difficulty: 'easy' },
  { word: 'krishtlindje', category: 'places', difficulty: 'easy' },
  { word: 'ylber', category: 'nature', difficulty: 'easy' },
  { word: 'njeri dëbore', category: 'nature', difficulty: 'easy' },
  { word: 'kampim', category: 'activities', difficulty: 'medium' },
  { word: 'surf', category: 'sports', difficulty: 'medium' },
  { word: 'gitarë', category: 'objects', difficulty: 'easy' },
  { word: 'piano', category: 'objects', difficulty: 'easy' },
  { word: 'kamerë', category: 'objects', difficulty: 'easy' },
  { word: 'urë', category: 'places', difficulty: 'easy' },
  { word: 'mal', category: 'nature', difficulty: 'easy' },
  { word: 'dragua', category: 'animals', difficulty: 'medium' },
  { word: 'thesar', category: 'objects', difficulty: 'medium' },
  { word: 'pirat', category: 'professions', difficulty: 'easy' },
  { word: 'mace', category: 'animals', difficulty: 'easy' },
  { word: 'qen', category: 'animals', difficulty: 'easy' },
  { word: 'kalë', category: 'animals', difficulty: 'easy' },
  { word: 'zog', category: 'animals', difficulty: 'easy' },
  { word: 'luani', category: 'animals', difficulty: 'easy' },
  { word: 'mollë', category: 'food', difficulty: 'easy' },
  { word: 'banane', category: 'food', difficulty: 'easy' },
  { word: 'tortë', category: 'food', difficulty: 'easy' },
  { word: 'akullore', category: 'food', difficulty: 'easy' },
  { word: 'i lumtur', category: 'emotions', difficulty: 'easy' },
  { word: 'i trishtuar', category: 'emotions', difficulty: 'easy' },
  { word: 'i zemëruar', category: 'emotions', difficulty: 'easy' },
  { word: 'i frikësuar', category: 'emotions', difficulty: 'easy' },
  { word: 'i befasuar', category: 'emotions', difficulty: 'medium' },
  { word: 'kuq', category: 'colors', difficulty: 'easy' },
  { word: 'blu', category: 'colors', difficulty: 'easy' },
  { word: 'gjelbër', category: 'colors', difficulty: 'easy' },
  { word: 'verdhë', category: 'colors', difficulty: 'easy' },
  { word: 'libër', category: 'objects', difficulty: 'easy' },
  { word: 'çelës', category: 'objects', difficulty: 'easy' },
  { word: 'pemë', category: 'objects', difficulty: 'easy' },
  { word: 'diell', category: 'nature', difficulty: 'easy' },
  { word: 'shi', category: 'nature', difficulty: 'easy' },
  { word: 'mjek', category: 'nature', difficulty: 'easy' },
  { word: 'mësues', category: 'professions', difficulty: 'easy' },
  { word: 'restorant', category: 'professions', difficulty: 'easy' },
  { word: 'shkollë', category: 'places', difficulty: 'easy' },
  { word: 'çiklistikë', category: 'places', difficulty: 'easy' },
  { word: 'tigër', category: 'sports', difficulty: 'easy' },
  { word: 'ariu', category: 'animals', difficulty: 'easy' },
  { word: 'lepur', category: 'animals', difficulty: 'easy' },
  { word: 'peshk', category: 'animals', difficulty: 'easy' },
  { word: 'gjarpër', category: 'animals', difficulty: 'easy' },
  { word: 'majmun', category: 'animals', difficulty: 'easy' },
  { word: 'bukë', category: 'animals', difficulty: 'easy' },
  { word: 'qumësht', category: 'animals', difficulty: 'easy' },
  { word: 'vezë', category: 'animals', difficulty: 'easy' },
  { word: 'djathë', category: 'animals', difficulty: 'easy' },
  { word: 'kafe', category: 'animals', difficulty: 'easy' },
  { word: 'çaj', category: 'animals', difficulty: 'medium' },
  { word: 'portokall', category: 'animals', difficulty: 'medium' },
  { word: 'domate', category: 'animals', difficulty: 'medium' },
  { word: 'patate', category: 'animals', difficulty: 'medium' },
  { word: 'i zi', category: 'animals', difficulty: 'medium' },
  { word: 'i bardhë', category: 'animals', difficulty: 'medium' },
  { word: 'rozë', category: 'animals', difficulty: 'medium' },
  { word: 'vjollcë', category: 'animals', difficulty: 'medium' },
  { word: 'i emocionuar', category: 'animals', difficulty: 'medium' },
  { word: 'i lodhur', category: 'animals', difficulty: 'medium' },
  { word: 'i qetë', category: 'animals', difficulty: 'medium' },
  { word: 'dashuri', category: 'animals', difficulty: 'medium' },
  { word: 'karrige', category: 'animals', difficulty: 'medium' },
  { word: 'tavolinë', category: 'animals', difficulty: 'medium' },
  { word: 'derë', category: 'animals', difficulty: 'medium' },
  { word: 'dritare', category: 'animals', difficulty: 'medium' },
  { word: 'orë', category: 'animals', difficulty: 'medium' },
  { word: 'lule', category: 'animals', difficulty: 'medium' },
  { word: 'bar', category: 'animals', difficulty: 'medium' },
  { word: 're', category: 'animals', difficulty: 'medium' },
  { word: 'borë', category: 'animals', difficulty: 'hard' },
  { word: 'lum', category: 'animals', difficulty: 'hard' },
  { word: 'liqen', category: 'animals', difficulty: 'hard' },
  { word: 'oqean', category: 'animals', difficulty: 'hard' },
  { word: 'plazh', category: 'animals', difficulty: 'hard' },
  { word: 'pyll', category: 'animals', difficulty: 'hard' },
  { word: 'park', category: 'animals', difficulty: 'hard' },
  { word: 'spital', category: 'animals', difficulty: 'hard' },
  { word: 'hotel', category: 'animals', difficulty: 'hard' },
  { word: 'rakun', category: 'animals', difficulty: 'hard' },
  { word: 'pelikan', category: 'animals', difficulty: 'hard' },
  { word: 'pulëbardha', category: 'animals', difficulty: 'hard' },
  { word: 'meduzë', category: 'animals', difficulty: 'hard' },
  { word: 'yll i detit', category: 'animals', difficulty: 'hard' },
  { word: 'kalë deti', category: 'animals', difficulty: 'hard' },
  { word: 'akrep', category: 'animals', difficulty: 'hard' },
  { word: 'tërfili', category: 'animals', difficulty: 'hard' },
  { word: 'buburreci', category: 'animals', difficulty: 'hard' },
  { word: 'mushkonjë', category: 'animals', difficulty: 'hard' },
  { word: 'karkalec', category: 'animals', difficulty: 'hard' },
  { word: 'bukë', category: 'food', difficulty: 'easy' },
  { word: 'qumësht', category: 'food', difficulty: 'easy' },
  { word: 'vezë', category: 'food', difficulty: 'easy' },
  { word: 'djathë', category: 'food', difficulty: 'easy' },
  { word: 'ujë', category: 'food', difficulty: 'easy' },
  { word: 'kafe', category: 'food', difficulty: 'easy' },
  { word: 'çaj', category: 'food', difficulty: 'easy' },
  { word: 'portokall', category: 'food', difficulty: 'easy' },
  { word: 'rrush', category: 'food', difficulty: 'easy' },
  { word: 'luleshtrydhe', category: 'food', difficulty: 'easy' },
  { word: 'karotë', category: 'food', difficulty: 'easy' },
  { word: 'domate', category: 'food', difficulty: 'easy' },
  { word: 'patate', category: 'food', difficulty: 'easy' },
  { word: 'burger', category: 'food', difficulty: 'easy' },
  { word: 'sanduiç', category: 'food', difficulty: 'easy' },
  { word: 'supë', category: 'food', difficulty: 'medium' },
  { word: 'sallatë', category: 'food', difficulty: 'medium' },
  { word: 'makarona', category: 'food', difficulty: 'medium' },
  { word: 'oriz', category: 'food', difficulty: 'medium' },
  { word: 'pule', category: 'food', difficulty: 'medium' },
  { word: 'biftek', category: 'food', difficulty: 'medium' },
  { word: 'sushi', category: 'food', difficulty: 'medium' },
  { word: 'petulla', category: 'food', difficulty: 'medium' },
  { word: 'vafël', category: 'food', difficulty: 'medium' },
  { word: 'donut', category: 'food', difficulty: 'medium' },
  { word: 'biskotë', category: 'food', difficulty: 'medium' },
  { word: 'çokollatë', category: 'food', difficulty: 'medium' },
  { word: 'shalqi', category: 'food', difficulty: 'medium' },
  { word: 'ananas', category: 'food', difficulty: 'medium' },
  { word: 'avokado', category: 'food', difficulty: 'medium' },
  { word: 'brokoli', category: 'food', difficulty: 'medium' },
  { word: 'kastravec', category: 'food', difficulty: 'medium' },
  { word: 'specë', category: 'food', difficulty: 'medium' },
  { word: 'qepë', category: 'food', difficulty: 'medium' },
  { word: 'hudhër', category: 'food', difficulty: 'medium' },
  { word: 'mjaltë', category: 'food', difficulty: 'medium' },
  { word: 'reçel', category: 'food', difficulty: 'medium' },
  { word: 'gjalpë', category: 'food', difficulty: 'medium' },
  { word: 'drithëra', category: 'food', difficulty: 'medium' },
  { word: 'kokoshka', category: 'food', difficulty: 'medium' },
  { word: 'kroasant', category: 'food', difficulty: 'hard' },
  { word: 'bagetë', category: 'food', difficulty: 'hard' },
  { word: 'humus', category: 'food', difficulty: 'hard' },
  { word: 'kuinoa', category: 'food', difficulty: 'hard' },
  { word: 'tartuf', category: 'food', difficulty: 'hard' },
  { word: 'kaviar', category: 'food', difficulty: 'hard' },
  { word: 'marshmallow', category: 'food', difficulty: 'hard' },
  { word: 'kanellë', category: 'food', difficulty: 'hard' },
  { word: 'vanilje', category: 'food', difficulty: 'hard' },
  { word: 'xhenxhefil', category: 'food', difficulty: 'hard' },
  { word: 'mente', category: 'food', difficulty: 'hard' },
  { word: 'borzilok', category: 'food', difficulty: 'hard' },
  { word: 'rigon', category: 'food', difficulty: 'hard' },
  { word: 'majdanoz', category: 'food', difficulty: 'hard' },
  { word: 'kokos', category: 'food', difficulty: 'hard' },
  { word: 'bajame', category: 'food', difficulty: 'hard' },
  { word: 'arrë', category: 'food', difficulty: 'hard' },
  { word: 'fistëk', category: 'food', difficulty: 'hard' },
  { word: 'manaferrë', category: 'food', difficulty: 'hard' },
  { word: 'manaferrë e zezë', category: 'food', difficulty: 'hard' },
  { word: 'boronicë', category: 'food', difficulty: 'hard' },
  { word: 'boronicë e kuqe', category: 'food', difficulty: 'hard' },
  { word: 'zi', category: 'colors', difficulty: 'easy' },
  { word: 'bardhë', category: 'colors', difficulty: 'easy' },
  { word: 'rozë', category: 'colors', difficulty: 'easy' },
  { word: 'vjollcë', category: 'colors', difficulty: 'easy' },
  { word: 'portokall', category: 'colors', difficulty: 'easy' },
  { word: 'kafe', category: 'colors', difficulty: 'easy' },
  { word: 'gri', category: 'colors', difficulty: 'easy' },
  { word: 'artë', category: 'colors', difficulty: 'medium' },
  { word: 'argjend', category: 'colors', difficulty: 'medium' },
  { word: 'turkuaz', category: 'colors', difficulty: 'medium' },
  { word: 'blu deti', category: 'colors', difficulty: 'medium' },
  { word: 'bezh', category: 'colors', difficulty: 'medium' },
  { word: 'koral', category: 'colors', difficulty: 'medium' },
  { word: 'lavandë', category: 'colors', difficulty: 'medium' },
  { word: 'qelibar', category: 'colors', difficulty: 'medium' },
  { word: 'indigo', category: 'colors', difficulty: 'medium' },
  { word: 'vjollcë', category: 'colors', difficulty: 'medium' },
  { word: 'blu-jeshil', category: 'colors', difficulty: 'medium' },
  { word: 'ulli', category: 'colors', difficulty: 'medium' },
  { word: 'kafe e hapur', category: 'colors', difficulty: 'medium' },
  { word: 'kremë', category: 'colors', difficulty: 'medium' },
  { word: 'karmin', category: 'colors', difficulty: 'hard' },
  { word: 'skuq', category: 'colors', difficulty: 'hard' },
  { word: 'magenta', category: 'colors', difficulty: 'hard' },
  { word: 'ngjyrë salmoni', category: 'colors', difficulty: 'hard' },
  { word: 'pjeshkë', category: 'colors', difficulty: 'hard' },
  { word: 'vjollcë e zbehtë', category: 'colors', difficulty: 'hard' },
  { word: 'kumbull', category: 'colors', difficulty: 'hard' },
  { word: 'cyan', category: 'colors', difficulty: 'hard' },
  { word: 'kaltër', category: 'colors', difficulty: 'hard' },
  { word: 'fildişi', category: 'colors', difficulty: 'hard' },
  { word: 'qymyr', category: 'colors', difficulty: 'hard' },
  { word: 'mustardë', category: 'colors', difficulty: 'hard' },
  { word: 'ndryshk', category: 'colors', difficulty: 'hard' },
  { word: 'bronz', category: 'colors', difficulty: 'hard' },
  { word: 'bakër', category: 'colors', difficulty: 'hard' },
  { word: 'safir', category: 'colors', difficulty: 'hard' },
  { word: 'rubin', category: 'colors', difficulty: 'hard' },
  { word: 'koral', category: 'colors', difficulty: 'hard' },
  { word: 'lavandër', category: 'colors', difficulty: 'hard' },
  { word: 'mentë', category: 'colors', difficulty: 'hard' },
  { word: 'kaltër', category: 'colors', difficulty: 'hard' },
  { word: 'oker', category: 'colors', difficulty: 'hard' },
  { word: 'i emocionuar', category: 'emotions', difficulty: 'easy' },
  { word: 'i lodhur', category: 'emotions', difficulty: 'easy' },
  { word: 'nervoz', category: 'emotions', difficulty: 'easy' },
  { word: 'qetë', category: 'emotions', difficulty: 'easy' },
  { word: 'dashuri', category: 'emotions', difficulty: 'easy' },
  { word: 'gëzim', category: 'emotions', difficulty: 'medium' },
  { word: 'frikë', category: 'emotions', difficulty: 'medium' },
  { word: 'zemërim', category: 'emotions', difficulty: 'medium' },
  { word: 'shpresë', category: 'emotions', difficulty: 'medium' },
  { word: 'krenari', category: 'emotions', difficulty: 'medium' },
  { word: 'turp', category: 'emotions', difficulty: 'medium' },
  { word: 'faj', category: 'emotions', difficulty: 'medium' },
  { word: 'xhelozi', category: 'emotions', difficulty: 'medium' },
  { word: 'merzi', category: 'emotions', difficulty: 'medium' },
  { word: 'konfuzion', category: 'emotions', difficulty: 'medium' },
  { word: 'kuriozitet', category: 'emotions', difficulty: 'medium' },
  { word: 'mirënjohje', category: 'emotions', difficulty: 'medium' },
  { word: 'lehtësim', category: 'emotions', difficulty: 'medium' },
  { word: 'zhgënjim', category: 'emotions', difficulty: 'medium' },
  { word: 'turp', category: 'emotions', difficulty: 'medium' },
  { word: 'frustrim', category: 'emotions', difficulty: 'medium' },
  { word: 'ankth', category: 'emotions', difficulty: 'medium' },
  { word: 'entuziazëm', category: 'emotions', difficulty: 'medium' },
  { word: 'kënaqësi', category: 'emotions', difficulty: 'medium' },
  { word: 'vetmi', category: 'emotions', difficulty: 'medium' },
  { word: 'nostalgji', category: 'emotions', difficulty: 'hard' },
  { word: 'melankoli', category: 'emotions', difficulty: 'hard' },
  { word: 'eufori', category: 'emotions', difficulty: 'hard' },
  { word: 'qetësi', category: 'emotions', difficulty: 'hard' },
  { word: 'habitë', category: 'emotions', difficulty: 'hard' },
  { word: 'argëtim', category: 'emotions', difficulty: 'hard' },
  { word: 'çuditë', category: 'emotions', difficulty: 'hard' },
  { word: 'vendosmëri', category: 'emotions', difficulty: 'hard' },
  { word: 'i mbushur', category: 'emotions', difficulty: 'hard' },
  { word: 'inatim', category: 'emotions', difficulty: 'hard' },
  { word: 'adhurim', category: 'emotions', difficulty: 'hard' },
  { word: 'pritje', category: 'emotions', difficulty: 'hard' },
  { word: 'ankth', category: 'emotions', difficulty: 'hard' },
  { word: 'përbuzje', category: 'emotions', difficulty: 'hard' },
  { word: 'devotësim', category: 'emotions', difficulty: 'hard' },
  { word: 'tmerr', category: 'emotions', difficulty: 'hard' },
  { word: 'ekstazë', category: 'emotions', difficulty: 'hard' },
  { word: 'zili', category: 'emotions', difficulty: 'hard' },
  { word: 'brengë', category: 'emotions', difficulty: 'hard' },
  { word: 'indiferencë', category: 'emotions', difficulty: 'hard' },
  { word: 'dëshirë', category: 'emotions', difficulty: 'hard' },
  { word: 'tërbohet', category: 'emotions', difficulty: 'hard' },
  { word: 'pendim', category: 'emotions', difficulty: 'hard' },
  { word: 'pendim', category: 'emotions', difficulty: 'hard' },
  { word: 'kënaqësi', category: 'emotions', difficulty: 'hard' },
  { word: 'brengë', category: 'emotions', difficulty: 'hard' },
  { word: 'tension', category: 'emotions', difficulty: 'hard' },
  { word: 'keqardhje', category: 'emotions', difficulty: 'hard' },
  { word: 'tmerr', category: 'emotions', difficulty: 'hard' },
  { word: 'çudi', category: 'emotions', difficulty: 'hard' },
  { word: 'karrige', category: 'objects', difficulty: 'easy' },
  { word: 'tavolinë', category: 'objects', difficulty: 'easy' },
  { word: 'llambë', category: 'objects', difficulty: 'easy' },
  { word: 'derë', category: 'objects', difficulty: 'easy' },
  { word: 'dritare', category: 'objects', difficulty: 'easy' },
  { word: 'orë', category: 'objects', difficulty: 'easy' },
  { word: 'orë', category: 'objects', difficulty: 'easy' },
  { word: 'çantë', category: 'objects', difficulty: 'easy' },
  { word: 'filxhan', category: 'objects', difficulty: 'easy' },
  { word: 'stilolaps', category: 'objects', difficulty: 'easy' },
  { word: 'pasqyrë', category: 'objects', difficulty: 'medium' },
  { word: 'jastëk', category: 'objects', difficulty: 'medium' },
  { word: 'batanije', category: 'objects', difficulty: 'medium' },
  { word: 'divan', category: 'objects', difficulty: 'medium' },
  { word: 'syze', category: 'objects', difficulty: 'medium' },
  { word: 'portofol', category: 'objects', difficulty: 'medium' },
  { word: 'çantë shpine', category: 'objects', difficulty: 'medium' },
  { word: 'shishe', category: 'objects', difficulty: 'medium' },
  { word: 'gërshërë', category: 'objects', difficulty: 'medium' },
  { word: 'çekiç', category: 'objects', difficulty: 'medium' },
  { word: 'furçë', category: 'objects', difficulty: 'medium' },
  { word: 'krehër', category: 'objects', difficulty: 'medium' },
  { word: 'furçë dhëmbësh', category: 'objects', difficulty: 'medium' },
  { word: 'peshqir', category: 'objects', difficulty: 'medium' },
  { word: 'gazetë', category: 'objects', difficulty: 'medium' },
  { word: 'revistë', category: 'objects', difficulty: 'medium' },
  { word: 'telekomandë', category: 'objects', difficulty: 'medium' },
  { word: 'kufje', category: 'objects', difficulty: 'medium' },
  { word: 'kompjuter portativ', category: 'objects', difficulty: 'medium' },
  { word: 'tastierë', category: 'objects', difficulty: 'medium' },
  { word: 'miu', category: 'objects', difficulty: 'medium' },
  { word: 'altoparlant', category: 'objects', difficulty: 'medium' },
  { word: 'mikrofon', category: 'objects', difficulty: 'medium' },
  { word: 'dritë dore', category: 'objects', difficulty: 'medium' },
  { word: 'bateri', category: 'objects', difficulty: 'medium' },
  { word: 'karikues', category: 'objects', difficulty: 'medium' },
  { word: 'vazo', category: 'objects', difficulty: 'hard' },
  { word: 'ombrellë', category: 'objects', difficulty: 'hard' },
  { word: 'ombrellë dielli', category: 'objects', difficulty: 'hard' },
  { word: 'dylbi', category: 'objects', difficulty: 'hard' },
  { word: 'teleskop', category: 'objects', difficulty: 'hard' },
  { word: 'busullë', category: 'objects', difficulty: 'hard' },
  { word: 'termometër', category: 'objects', difficulty: 'hard' },
  { word: 'lupë', category: 'objects', difficulty: 'hard' },
  { word: 'kaçavidë', category: 'objects', difficulty: 'hard' },
  { word: 'çelës', category: 'objects', difficulty: 'hard' },
  { word: 'darë', category: 'objects', difficulty: 'hard' },
  { word: 'grep', category: 'objects', difficulty: 'hard' },
  { word: 'fije', category: 'objects', difficulty: 'hard' },
  { word: 'valixhe', category: 'objects', difficulty: 'hard' },
  { word: 'portofol', category: 'objects', difficulty: 'hard' },
  { word: 'mbajtës ombrellash', category: 'objects', difficulty: 'hard' },
  { word: 'varëse', category: 'objects', difficulty: 'hard' },
  { word: 'zile derë', category: 'objects', difficulty: 'hard' },
  { word: 'trokitës dere', category: 'objects', difficulty: 'hard' },
  { word: 'perde', category: 'objects', difficulty: 'hard' },
  { word: 'xham', category: 'objects', difficulty: 'hard' },
  { word: 'lustër', category: 'objects', difficulty: 'hard' },
  { word: 'shandan', category: 'objects', difficulty: 'hard' },
  { word: 'orë rëre', category: 'objects', difficulty: 'hard' },
  { word: 'orë dielli', category: 'objects', difficulty: 'hard' },
  { word: 'glob', category: 'objects', difficulty: 'hard' },
  { word: 'atlas', category: 'objects', difficulty: 'hard' },
  { word: 'enciklopedi', category: 'objects', difficulty: 'hard' },
  { word: 'album', category: 'objects', difficulty: 'hard' },
  { word: 'album fotosh', category: 'objects', difficulty: 'hard' },
  { word: 'kuti bizhuterish', category: 'objects', difficulty: 'hard' },
  { word: 'kupa kursimi', category: 'objects', difficulty: 'hard' },
  { word: 'lule', category: 'nature', difficulty: 'easy' },
  { word: 'bar', category: 'nature', difficulty: 'easy' },
  { word: 're', category: 'nature', difficulty: 'easy' },
  { word: 'borë', category: 'nature', difficulty: 'easy' },
  { word: 'erë', category: 'nature', difficulty: 'easy' },
  { word: 'lumë', category: 'nature', difficulty: 'easy' },
  { word: 'liqen', category: 'nature', difficulty: 'easy' },
  { word: 'oqean', category: 'nature', difficulty: 'easy' },
  { word: 'plazh', category: 'nature', difficulty: 'easy' },
  { word: 'pyll', category: 'nature', difficulty: 'easy' },
  { word: 'shkëmb', category: 'nature', difficulty: 'medium' },
  { word: 'ishull', category: 'nature', difficulty: 'medium' },
  { word: 'ujëvarë', category: 'nature', difficulty: 'medium' },
  { word: 'vullkan', category: 'nature', difficulty: 'medium' },
  { word: 'shkretëtirë', category: 'nature', difficulty: 'medium' },
  { word: 'luginë', category: 'nature', difficulty: 'medium' },
  { word: 'grykë', category: 'nature', difficulty: 'medium' },
  { word: 'shpat shkëmbor', category: 'nature', difficulty: 'medium' },
  { word: 'livadh', category: 'nature', difficulty: 'medium' },
  { word: 'përrue', category: 'nature', difficulty: 'medium' },
  { word: 'pellg', category: 'nature', difficulty: 'medium' },
  { word: 'valë', category: 'nature', difficulty: 'medium' },
  { word: 'stuhi', category: 'nature', difficulty: 'medium' },
  { word: 'bubullimë', category: 'nature', difficulty: 'medium' },
  { word: 'vetëtimë', category: 'nature', difficulty: 'medium' },
  { word: 'mjegull', category: 'nature', difficulty: 'medium' },
  { word: 'avull', category: 'nature', difficulty: 'medium' },
  { word: 'vesë', category: 'nature', difficulty: 'medium' },
  { word: 'ngricë', category: 'nature', difficulty: 'medium' },
  { word: 'breshër', category: 'nature', difficulty: 'medium' },
  { word: 'uragan', category: 'nature', difficulty: 'medium' },
  { word: 'tornado', category: 'nature', difficulty: 'medium' },
  { word: 'tërmet', category: 'nature', difficulty: 'medium' },
  { word: 'ortek', category: 'nature', difficulty: 'medium' },
  { word: 'zjarr i egër', category: 'nature', difficulty: 'medium' },
  { word: 'gejzer', category: 'nature', difficulty: 'hard' },
  { word: 'akullnajë', category: 'nature', difficulty: 'hard' },
  { word: 'ajsberg', category: 'nature', difficulty: 'hard' },
  { word: 'oaz', category: 'nature', difficulty: 'hard' },
  { word: 'gadishull', category: 'nature', difficulty: 'hard' },
  { word: 'arkipelag', category: 'nature', difficulty: 'hard' },
  { word: 'grykëderdhje', category: 'nature', difficulty: 'hard' },
  { word: 'delta', category: 'nature', difficulty: 'hard' },
  { word: 'degë lumi', category: 'nature', difficulty: 'hard' },
  { word: 'rezervuar', category: 'nature', difficulty: 'hard' },
  { word: 'tokë e lagët', category: 'nature', difficulty: 'hard' },
  { word: 'kënetë', category: 'nature', difficulty: 'hard' },
  { word: 'moçal', category: 'nature', difficulty: 'hard' },
  { word: 'tundër', category: 'nature', difficulty: 'hard' },
  { word: 'savane', category: 'nature', difficulty: 'hard' },
  { word: 'prarí', category: 'nature', difficulty: 'hard' },
  { word: 'xhungël', category: 'nature', difficulty: 'hard' },
  { word: 'grep', category: 'nature', difficulty: 'hard' },
  { word: 'koral', category: 'nature', difficulty: 'hard' },
  { word: 'dunë', category: 'nature', difficulty: 'hard' },
  { word: 'krater', category: 'nature', difficulty: 'hard' },
  { word: 'majë', category: 'nature', difficulty: 'hard' },
  { word: 'kurriz mali', category: 'nature', difficulty: 'hard' },
  { word: 'rrafshnaltë', category: 'nature', difficulty: 'hard' },
  { word: 'kopsht pemësh', category: 'nature', difficulty: 'hard' },
  { word: 'kaçubë', category: 'nature', difficulty: 'hard' },
  { word: 'kurorë pylli', category: 'nature', difficulty: 'hard' },
  { word: 'nënpyllje', category: 'nature', difficulty: 'hard' },
  { word: 'lulëzim', category: 'nature', difficulty: 'hard' },
  { word: 'petale', category: 'nature', difficulty: 'hard' },
  { word: 'gjemb', category: 'nature', difficulty: 'hard' },
  { word: 'hardhí', category: 'nature', difficulty: 'hard' },
  { word: 'myshk', category: 'nature', difficulty: 'hard' },
  { word: 'fishtë', category: 'nature', difficulty: 'hard' },
  { word: 'kaktus', category: 'nature', difficulty: 'hard' },

  { word: 'futboll', category: 'sports', difficulty: 'easy' },
  { word: 'bejsboll', category: 'sports', difficulty: 'easy' },
  { word: 'golf', category: 'sports', difficulty: 'easy' },
  { word: 'boks', category: 'sports', difficulty: 'easy' },
  { word: 'mundje', category: 'sports', difficulty: 'easy' },
  { word: 'ski', category: 'sports', difficulty: 'easy' },
  { word: 'patinazh', category: 'sports', difficulty: 'easy' },
  { word: 'vrapim i lehtë', category: 'sports', difficulty: 'easy' },
  { word: 'jogë', category: 'sports', difficulty: 'easy' },
  { word: 'zhytje', category: 'sports', difficulty: 'easy' },
  { word: 'volejboll', category: 'sports', difficulty: 'medium' },
  { word: 'hokej', category: 'sports', difficulty: 'medium' },
  { word: 'ragbi', category: 'sports', difficulty: 'medium' },
  { word: 'badminton', category: 'sports', difficulty: 'medium' },
  { word: 'vozitje', category: 'sports', difficulty: 'medium' },
  { word: 'kajak', category: 'sports', difficulty: 'medium' },
  { word: 'dërrasë bore', category: 'sports', difficulty: 'medium' },
  { word: 'gjimnastikë', category: 'sports', difficulty: 'medium' },
  { word: 'arte luftarake', category: 'sports', difficulty: 'medium' },
  { word: 'ngritje pesash', category: 'sports', difficulty: 'medium' },
  { word: 'kërcim', category: 'sports', difficulty: 'medium' },
  { word: 'ngjitje', category: 'sports', difficulty: 'medium' },
  { word: 'eskrimë', category: 'sports', difficulty: 'medium' },
  { word: 'harkëtari', category: 'sports', difficulty: 'medium' },
  { word: 'boçe', category: 'sports', difficulty: 'medium' },
  { word: 'bilardo', category: 'sports', difficulty: 'medium' },
  { word: 'shigjeta', category: 'sports', difficulty: 'medium' },
  { word: 'ping pong', category: 'sports', difficulty: 'medium' },
  { word: 'maraton', category: 'sports', difficulty: 'medium' },
  { word: 'sprint', category: 'sports', difficulty: 'medium' },
  { word: 'triatlon', category: 'sports', difficulty: 'medium' },
  { word: 'pentatlon', category: 'sports', difficulty: 'hard' },
  { word: 'dekatlon', category: 'sports', difficulty: 'hard' },
  { word: 'parashutizëm', category: 'sports', difficulty: 'hard' },
  { word: 'deltaplan', category: 'sports', difficulty: 'hard' },
  { word: 'ngjitje shkëmbore', category: 'sports', difficulty: 'hard' },
  { word: 'bobsled', category: 'sports', difficulty: 'hard' },
  { word: 'karling', category: 'sports', difficulty: 'hard' },
  { word: 'polo', category: 'sports', difficulty: 'hard' },
  { word: 'lakros', category: 'sports', difficulty: 'hard' },
  { word: 'kriket', category: 'sports', difficulty: 'hard' },
  { word: 'skuash', category: 'sports', difficulty: 'hard' },
  { word: 'raketboll', category: 'sports', difficulty: 'hard' },
  { word: 'hedhje shtize', category: 'sports', difficulty: 'hard' },
  { word: 'hedhje guri', category: 'sports', difficulty: 'hard' },
  { word: 'hedhje disku', category: 'sports', difficulty: 'hard' },
  { word: 'hedhje çekiçi', category: 'sports', difficulty: 'hard' },
  { word: 'kërcim së larti', category: 'sports', difficulty: 'hard' },
  { word: 'kërcim së gjati', category: 'sports', difficulty: 'hard' },
  { word: 'kërcim me shtagë', category: 'sports', difficulty: 'hard' },
  { word: 'vrapim me pengesa', category: 'sports', difficulty: 'hard' },
  { word: 'stafetë', category: 'sports', difficulty: 'hard' },
  { word: 'not sinkron', category: 'sports', difficulty: 'hard' },
  { word: 'polo ujore', category: 'sports', difficulty: 'hard' },
  { word: 'surfim', category: 'sports', difficulty: 'hard' },
  { word: 'windsurf', category: 'sports', difficulty: 'hard' },
  { word: 'kitesurfing', category: 'sports', difficulty: 'hard' },
  { word: 'zhytje me oksigjën', category: 'sports', difficulty: 'hard' },
  { word: 'snorkelim', category: 'sports', difficulty: 'hard' },
  { word: 'paraglidim', category: 'sports', difficulty: 'hard' },
  { word: 'kërcim me parashutë', category: 'sports', difficulty: 'hard' },
  { word: 'kërcim bungji', category: 'sports', difficulty: 'hard' },
  { word: 'parkur', category: 'sports', difficulty: 'hard' },
  { word: 'breakdans', category: 'sports', difficulty: 'hard' },

  { word: 'infermiere', category: 'professions', difficulty: 'easy' },
  { word: 'shofer', category: 'professions', difficulty: 'easy' },
  { word: 'kuzhinier', category: 'professions', difficulty: 'easy' },
  { word: 'artist', category: 'professions', difficulty: 'easy' },
  { word: 'këngëtar', category: 'professions', difficulty: 'easy' },
  { word: 'aktor', category: 'professions', difficulty: 'easy' },
  { word: 'fermer', category: 'professions', difficulty: 'easy' },
  { word: 'pilot', category: 'professions', difficulty: 'easy' },
  { word: 'ushtar', category: 'professions', difficulty: 'easy' },
  { word: 'polici', category: 'professions', difficulty: 'easy' },
  { word: 'avokat', category: 'professions', difficulty: 'medium' },
  { word: 'gjykatës', category: 'professions', difficulty: 'medium' },
  { word: 'shkrimtar', category: 'professions', difficulty: 'medium' },
  { word: 'gazetar', category: 'professions', difficulty: 'medium' },
  { word: 'fotograf', category: 'professions', difficulty: 'medium' },
  { word: 'arkitekt', category: 'professions', difficulty: 'medium' },
  { word: 'inxhinier', category: 'professions', difficulty: 'medium' },
  { word: 'shkencëtar', category: 'professions', difficulty: 'medium' },
  { word: 'astronaut', category: 'professions', difficulty: 'medium' },
  { word: 'zjarrfikës', category: 'professions', difficulty: 'medium' },
  { word: 'mekanik', category: 'professions', difficulty: 'medium' },
  { word: 'elektricist', category: 'professions', difficulty: 'medium' },
  { word: 'hidraulik', category: 'professions', difficulty: 'medium' },
  { word: 'marangoz', category: 'professions', difficulty: 'medium' },
  { word: 'piktor', category: 'professions', difficulty: 'medium' },
  { word: 'rrobaqepës', category: 'professions', difficulty: 'medium' },
  { word: 'berber', category: 'professions', difficulty: 'medium' },
  { word: 'dentist', category: 'professions', difficulty: 'medium' },
  { word: 'veteriner', category: 'professions', difficulty: 'medium' },
  { word: 'bibliotekar', category: 'professions', difficulty: 'medium' },
  { word: 'kontabilist', category: 'professions', difficulty: 'medium' },
  { word: 'bankier', category: 'professions', difficulty: 'medium' },
  { word: 'agjent imobiliar', category: 'professions', difficulty: 'medium' },
  { word: 'detektiv', category: 'professions', difficulty: 'medium' },
  { word: 'spiun', category: 'professions', difficulty: 'medium' },
  { word: 'magjistar', category: 'professions', difficulty: 'medium' },
  { word: 'kloun', category: 'professions', difficulty: 'medium' },
  { word: 'kërcimtar', category: 'professions', difficulty: 'medium' },
  { word: 'muzikant', category: 'professions', difficulty: 'medium' },
  { word: 'kompozitor', category: 'professions', difficulty: 'hard' },
  { word: 'dirigjent', category: 'professions', difficulty: 'hard' },
  { word: 'kujdestar muze', category: 'professions', difficulty: 'hard' },
  { word: 'arkivist', category: 'professions', difficulty: 'hard' },
  { word: 'antropolog', category: 'professions', difficulty: 'hard' },
  { word: 'arkeolog', category: 'professions', difficulty: 'hard' },
  { word: 'gjeolog', category: 'professions', difficulty: 'hard' },
  { word: 'astronom', category: 'professions', difficulty: 'hard' },
  { word: 'biolog', category: 'professions', difficulty: 'hard' },
  { word: 'kimist', category: 'professions', difficulty: 'hard' },
  { word: 'fizikant', category: 'professions', difficulty: 'hard' },
  { word: 'psikolog', category: 'professions', difficulty: 'hard' },
  { word: 'terapist', category: 'professions', difficulty: 'hard' },
  { word: 'kirurg', category: 'professions', difficulty: 'hard' },
  { word: 'paramjekësor', category: 'professions', difficulty: 'hard' },
  { word: 'farmacist', category: 'professions', difficulty: 'hard' },
  { word: 'diplomat', category: 'professions', difficulty: 'hard' },
  { word: 'ambasador', category: 'professions', difficulty: 'hard' },
  { word: 'magjistrat', category: 'professions', difficulty: 'hard' },
  { word: 'noter', category: 'professions', difficulty: 'hard' },
  { word: 'auditor', category: 'professions', difficulty: 'hard' },
  { word: 'aktuar', category: 'professions', difficulty: 'hard' },
  { word: 'kartograf', category: 'professions', difficulty: 'hard' },
  { word: 'përkthyes', category: 'professions', difficulty: 'hard' },
  { word: 'interpretues', category: 'professions', difficulty: 'hard' },
  { word: 'redaktor', category: 'professions', difficulty: 'hard' },
  { word: 'botues', category: 'professions', difficulty: 'hard' },
  { word: 'ilustrues', category: 'professions', difficulty: 'hard' },
  { word: 'skulptor', category: 'professions', difficulty: 'hard' },
  { word: 'poçar', category: 'professions', difficulty: 'hard' },
  { word: 'farkëtar', category: 'professions', difficulty: 'hard' },
  { word: 'argjendtar', category: 'professions', difficulty: 'hard' },
  { word: 'orëndreqës', category: 'professions', difficulty: 'hard' },
  { word: 'çelësar', category: 'professions', difficulty: 'hard' },
  { word: 'luleshitës', category: 'professions', difficulty: 'hard' },
  { word: 'somelier', category: 'professions', difficulty: 'hard' },
  { word: 'kryekamarier', category: 'professions', difficulty: 'hard' },
  { word: 'konsiergj', category: 'professions', difficulty: 'hard' },
  { word: 'stjuard', category: 'professions', difficulty: 'hard' },
  { word: 'navigator', category: 'professions', difficulty: 'hard' },

  { word: 'park', category: 'places', difficulty: 'easy' },
  { word: 'spital', category: 'places', difficulty: 'easy' },
  { word: 'hotel', category: 'places', difficulty: 'easy' },
  { word: 'dyqan', category: 'places', difficulty: 'easy' },
  { word: 'rrugë', category: 'places', difficulty: 'easy' },
  { word: 'bibliotekë', category: 'places', difficulty: 'easy' },
  { word: 'muze', category: 'places', difficulty: 'easy' },
  { word: 'kinema', category: 'places', difficulty: 'easy' },
  { word: 'stadium', category: 'places', difficulty: 'easy' },
  { word: 'aeroport', category: 'places', difficulty: 'easy' },
  { word: 'stacion', category: 'places', difficulty: 'medium' },
  { word: 'port', category: 'places', difficulty: 'medium' },
  { word: 'treg', category: 'places', difficulty: 'medium' },
  { word: 'qendër tregtare', category: 'places', difficulty: 'medium' },
  { word: 'bankë', category: 'places', difficulty: 'medium' },
  { word: 'zyrë postare', category: 'places', difficulty: 'medium' },
  { word: 'gjykatë', category: 'places', difficulty: 'medium' },
  { word: 'burg', category: 'places', difficulty: 'medium' },
  { word: 'kishë', category: 'places', difficulty: 'medium' },
  { word: 'tempull', category: 'places', difficulty: 'medium' },
  { word: 'xhami', category: 'places', difficulty: 'medium' },
  { word: 'kështjellë', category: 'places', difficulty: 'medium' },
  { word: 'pallat', category: 'places', difficulty: 'medium' },
  { word: 'kullë', category: 'places', difficulty: 'medium' },
  { word: 'urë', category: 'places', difficulty: 'medium' },
  { word: 'tunel', category: 'places', difficulty: 'medium' },
  { word: 'autostradë', category: 'places', difficulty: 'medium' },
  { word: 'bulevard', category: 'places', difficulty: 'medium' },
  { word: 'kalë e ngushtë', category: 'places', difficulty: 'medium' },
  { word: 'shesh', category: 'places', difficulty: 'medium' },
  { word: 'shatërvan', category: 'places', difficulty: 'medium' },
  { word: 'monument', category: 'places', difficulty: 'medium' },
  { word: 'varrezë', category: 'places', difficulty: 'medium' },
  { word: 'kopsht zoologjik', category: 'places', difficulty: 'medium' },
  { word: 'akuarium', category: 'places', difficulty: 'medium' },
  { word: 'palestër', category: 'places', difficulty: 'medium' },
  { word: 'pishinë', category: 'places', difficulty: 'medium' },
  { word: 'arenë', category: 'places', difficulty: 'medium' },
  { word: 'teatër', category: 'places', difficulty: 'medium' },
  { word: 'galeri', category: 'places', difficulty: 'medium' },
  { word: 'furre buke', category: 'places', difficulty: 'medium' },
  { word: 'kafe', category: 'places', difficulty: 'medium' },
  { word: 'bar', category: 'places', difficulty: 'medium' },
  { word: 'depo', category: 'places', difficulty: 'hard' },
  { word: 'fabrikë', category: 'places', difficulty: 'hard' },
  { word: 'laborator', category: 'places', difficulty: 'hard' },
  { word: 'observator', category: 'places', difficulty: 'hard' },
  { word: 'planetarium', category: 'places', difficulty: 'hard' },
  { word: 'katedrale', category: 'places', difficulty: 'hard' },
  { word: 'manastir', category: 'places', difficulty: 'hard' },
  { word: 'kovent', category: 'places', difficulty: 'hard' },
  { word: 'mauzole', category: 'places', difficulty: 'hard' },
  { word: 'koloseun', category: 'places', difficulty: 'hard' },
  { word: 'amfiteatër', category: 'places', difficulty: 'hard' },
  { word: 'pavilion', category: 'places', difficulty: 'hard' },
  { word: 'çardak', category: 'places', difficulty: 'hard' },
  { word: 'far deti', category: 'places', difficulty: 'hard' },
  { word: 'mulli ere', category: 'places', difficulty: 'hard' },
  { word: 'mulli uji', category: 'places', difficulty: 'hard' },
  { word: 'hambar', category: 'places', difficulty: 'hard' },
  { word: 'silo', category: 'places', difficulty: 'hard' },
  { word: 'serrë', category: 'places', difficulty: 'hard' },
  { word: 'konservator', category: 'places', difficulty: 'hard' },
  { word: 'arboretum', category: 'places', difficulty: 'hard' },
  { word: 'kopsht botanik', category: 'places', difficulty: 'hard' },
  { word: 'vresht', category: 'places', difficulty: 'hard' },
  { word: 'fabrikë birre', category: 'places', difficulty: 'hard' },
  { word: 'distileri', category: 'places', difficulty: 'hard' },
  { word: 'butik', category: 'places', difficulty: 'hard' },
  { word: 'emporium', category: 'places', difficulty: 'hard' },
  { word: 'bazar', category: 'places', difficulty: 'hard' },
  { word: 'qendër e qytetit', category: 'places', difficulty: 'hard' },
  { word: 'periferi', category: 'places', difficulty: 'hard' },
  { word: 'fshat', category: 'places', difficulty: 'hard' },
  { word: 'metropol', category: 'places', difficulty: 'hard' },
  { word: 'kryeqytet', category: 'places', difficulty: 'hard' },
  { word: 'kufi', category: 'places', difficulty: 'hard' },
  { word: 'pikë kontrolli', category: 'places', difficulty: 'hard' },
  { word: 'terminal', category: 'places', difficulty: 'hard' },
  { word: 'depo', category: 'places', difficulty: 'hard' },
  { word: 'dok', category: 'places', difficulty: 'hard' },
  { word: 'molo', category: 'places', difficulty: 'hard' },
  { word: 'marinë', category: 'places', difficulty: 'hard' },
  { word: 'kanal', category: 'places', difficulty: 'hard' },
  { word: 'rezervuar', category: 'places', difficulty: 'hard' },

  { word: 'ecje', category: 'activities', difficulty: 'easy' },
  { word: 'ngrënie', category: 'activities', difficulty: 'easy' },
  { word: 'shikimi', category: 'activities', difficulty: 'easy' },
  { word: 'dëgjimi', category: 'activities', difficulty: 'easy' },
  { word: 'vizatimi', category: 'activities', difficulty: 'easy' },
  { word: 'shkrimi', category: 'activities', difficulty: 'easy' },
  { word: 'pastrimi', category: 'activities', difficulty: 'easy' },
  { word: 'blerje', category: 'activities', difficulty: 'easy' },
  { word: 'ngasje', category: 'activities', difficulty: 'easy' },
  { word: 'kalërim', category: 'activities', difficulty: 'easy' },
  { word: 'studim', category: 'activities', difficulty: 'medium' },
  { word: 'udhëtim', category: 'activities', difficulty: 'medium' },
  { word: 'kopshtari', category: 'activities', difficulty: 'medium' },
  { word: 'pjekje', category: 'activities', difficulty: 'medium' },
  { word: 'thurje', category: 'activities', difficulty: 'medium' },
  { word: 'qepje', category: 'activities', difficulty: 'medium' },
  { word: 'meditim', category: 'activities', difficulty: 'medium' },
  { word: 'shtrirje', category: 'activities', difficulty: 'medium' },
  { word: 'vrapim i lehtë', category: 'activities', difficulty: 'medium' },
  { word: 'ecje malore', category: 'activities', difficulty: 'medium' },
  { word: 'kamping', category: 'activities', difficulty: 'medium' },
  { word: 'piknik', category: 'activities', difficulty: 'medium' },
  { word: 'skarë', category: 'activities', difficulty: 'medium' },
  { word: 'lojë', category: 'activities', difficulty: 'medium' },
  { word: 'valle', category: 'activities', difficulty: 'medium' },
  { word: 'akting', category: 'activities', difficulty: 'medium' },
  { word: 'xhirim', category: 'activities', difficulty: 'medium' },
  { word: 'redaktim', category: 'activities', difficulty: 'medium' },
  { word: 'bloging', category: 'activities', difficulty: 'medium' },
  { word: 'transmetim', category: 'activities', difficulty: 'medium' },
  { word: 'lojëra kompjuterike', category: 'activities', difficulty: 'medium' },
  { word: 'enigmë', category: 'activities', difficulty: 'medium' },
  { word: 'album kujtimesh', category: 'activities', difficulty: 'medium' },
  { word: 'koleksionim', category: 'activities', difficulty: 'medium' },
  { word: 'vullnetarizëm', category: 'activities', difficulty: 'medium' },
  { word: 'dhënie dhuratash', category: 'activities', difficulty: 'medium' },
  { word: 'riciklim', category: 'activities', difficulty: 'medium' },
  { word: 'kompostim', category: 'activities', difficulty: 'medium' },
  { word: 'vëzhgim zogjsh', category: 'activities', difficulty: 'hard' },
  { word: 'vëzhgim yjetësh', category: 'activities', difficulty: 'hard' },
  { word: 'gjeokeshing', category: 'activities', difficulty: 'hard' },
  { word: 'orientim', category: 'activities', difficulty: 'hard' },
  { word: 'kaligrafi', category: 'activities', difficulty: 'hard' },
  { word: 'origami', category: 'activities', difficulty: 'hard' },
  { word: 'poçari', category: 'activities', difficulty: 'hard' },
  { word: 'endja', category: 'activities', difficulty: 'hard' },
  { word: 'qëndisje', category: 'activities', difficulty: 'hard' },
  { word: 'qepje çarçafi', category: 'activities', difficulty: 'hard' },
  { word: 'punë me dru', category: 'activities', difficulty: 'hard' },
  { word: 'punë me metal', category: 'activities', difficulty: 'hard' },
  { word: 'farkëtari', category: 'activities', difficulty: 'hard' },
  { word: 'gdhendja e drurit', category: 'activities', difficulty: 'hard' },
  { word: 'skulpturë', category: 'activities', difficulty: 'hard' },
  { word: 'skicim', category: 'activities', difficulty: 'hard' },
  { word: 'akuarel', category: 'activities', difficulty: 'hard' },
  { word: 'ditari', category: 'activities', difficulty: 'hard' },
  { word: 'tregimtari', category: 'activities', difficulty: 'hard' },
  { word: 'debatim', category: 'activities', difficulty: 'hard' },
  { word: 'negocim', category: 'activities', difficulty: 'hard' },
  { word: 'mentorim', category: 'activities', difficulty: 'hard' },
  { word: 'tutorësi', category: 'activities', difficulty: 'hard' },
  { word: 'kërkime', category: 'activities', difficulty: 'hard' },
  { word: 'eksperimentim', category: 'activities', difficulty: 'hard' },
  { word: 'shpikje', category: 'activities', difficulty: 'hard' },
  { word: 'kompozim', category: 'activities', difficulty: 'hard' },
  { word: 'improvizim', category: 'activities', difficulty: 'hard' },
  { word: 'dirigjim', category: 'activities', difficulty: 'hard' },
  { word: 'koreografi', category: 'activities', difficulty: 'hard' },
  { word: 'regji', category: 'activities', difficulty: 'hard' },
  { word: 'prodhim', category: 'activities', difficulty: 'hard' },
  { word: 'transmetim', category: 'activities', difficulty: 'hard' },
  { word: 'podcast', category: 'activities', difficulty: 'hard' },
  { word: 'vlog', category: 'activities', difficulty: 'hard' },
  { word: 'fotografi', category: 'activities', difficulty: 'hard' },
  { word: 'videografi', category: 'activities', difficulty: 'hard' },
  { word: 'animacion', category: 'activities', difficulty: 'hard' },
  { word: 'dizajn', category: 'activities', difficulty: 'hard' },
  { word: 'programim', category: 'activities', difficulty: 'hard' },
  { word: 'korrigjim gabimesh', category: 'activities', difficulty: 'hard' },
  { word: 'rrjetëzim', category: 'activities', difficulty: 'hard' },
  { word: 'prezantim', category: 'activities', difficulty: 'hard' },
  { word: 'fjalim publik', category: 'activities', difficulty: 'hard' },
  { word: 'stuhi mendimesh', category: 'activities', difficulty: 'hard' },
  { word: 'zgjidhje problemesh', category: 'activities', difficulty: 'hard' },
];
