module.exports = [
  { word: 'dans etmek', category: 'activities', difficulty: 'easy' },
  { word: 'yüzmek', category: 'activities', difficulty: 'easy' },
  { word: 'okumak', category: 'activities', difficulty: 'easy' },
  { word: 'yemek yapmak', category: 'activities', difficulty: 'easy' },
  { word: 'şarkı söylemek', category: 'activities', difficulty: 'easy' },
  { word: 'koşmak', category: 'sports', difficulty: 'easy' },
  { word: 'uyumak', category: 'activities', difficulty: 'easy' },
  { word: 'balık tutmak', category: 'activities', difficulty: 'easy' },
  { word: 'resim yapmak', category: 'activities', difficulty: 'medium' },
  { word: 'futbol', category: 'sports', difficulty: 'easy' },
  { word: 'basketbol', category: 'sports', difficulty: 'easy' },
  { word: 'tenis', category: 'sports', difficulty: 'easy' },
  { word: 'fil', category: 'animals', difficulty: 'easy' },
  { word: 'kelebek', category: 'animals', difficulty: 'medium' },
  { word: 'uçak', category: 'objects', difficulty: 'easy' },
  { word: 'şemsiye', category: 'objects', difficulty: 'easy' },
  { word: 'telefon', category: 'objects', difficulty: 'easy' },
  { word: 'pizza', category: 'food', difficulty: 'easy' },
  { word: 'doğum günü', category: 'emotions', difficulty: 'easy' },
  { word: 'noel', category: 'places', difficulty: 'easy' },
  { word: 'gökkuşağı', category: 'nature', difficulty: 'easy' },
  { word: 'kardan adam', category: 'nature', difficulty: 'easy' },
  { word: 'kamp yapmak', category: 'activities', difficulty: 'medium' },
  { word: 'sörf', category: 'sports', difficulty: 'medium' },
  { word: 'gitar', category: 'objects', difficulty: 'easy' },
  { word: 'piyano', category: 'objects', difficulty: 'easy' },
  { word: 'kamera', category: 'objects', difficulty: 'easy' },
  { word: 'köprü', category: 'places', difficulty: 'easy' },
  { word: 'dağ', category: 'nature', difficulty: 'easy' },
  { word: 'ejderha', category: 'animals', difficulty: 'medium' },
  { word: 'hazine', category: 'objects', difficulty: 'medium' },
  { word: 'korsan', category: 'professions', difficulty: 'easy' },
  { word: 'kedi', category: 'animals', difficulty: 'easy' },
  { word: 'köpek', category: 'animals', difficulty: 'easy' },
  { word: 'at', category: 'animals', difficulty: 'easy' },
  { word: 'kuş', category: 'animals', difficulty: 'easy' },
  { word: 'aslan', category: 'animals', difficulty: 'easy' },
  { word: 'elma', category: 'food', difficulty: 'easy' },
  { word: 'muz', category: 'food', difficulty: 'easy' },
  { word: 'pasta', category: 'food', difficulty: 'easy' },
  { word: 'dondurma', category: 'food', difficulty: 'easy' },
  { word: 'mutlu', category: 'emotions', difficulty: 'easy' },
  { word: 'üzgün', category: 'emotions', difficulty: 'easy' },
  { word: 'kızgın', category: 'emotions', difficulty: 'easy' },
  { word: 'korkmuş', category: 'emotions', difficulty: 'easy' },
  { word: 'şaşırmış', category: 'emotions', difficulty: 'medium' },
  { word: 'kırmızı', category: 'colors', difficulty: 'easy' },
  { word: 'mavi', category: 'colors', difficulty: 'easy' },
  { word: 'yeşil', category: 'colors', difficulty: 'easy' },
  { word: 'sarı', category: 'colors', difficulty: 'easy' },
  { word: 'kitap', category: 'objects', difficulty: 'easy' },
  { word: 'anahtar', category: 'objects', difficulty: 'easy' },
  { word: 'ağaç', category: 'objects', difficulty: 'easy' },
  { word: 'güneş', category: 'nature', difficulty: 'easy' },
  { word: 'yağmur', category: 'nature', difficulty: 'easy' },
  { word: 'doktor', category: 'nature', difficulty: 'easy' },
  { word: 'öğretmen', category: 'professions', difficulty: 'easy' },
  { word: 'restoran', category: 'professions', difficulty: 'easy' },
  { word: 'okul', category: 'places', difficulty: 'easy' },
  { word: 'bisiklet', category: 'places', difficulty: 'easy' },
  { word: 'kaplan', category: 'sports', difficulty: 'easy' },
  { word: 'ayı', category: 'animals', difficulty: 'easy' },
  { word: 'tavşan', category: 'animals', difficulty: 'easy' },
  { word: 'balık', category: 'animals', difficulty: 'easy' },
  { word: 'yılan', category: 'animals', difficulty: 'easy' },
  { word: 'maymun', category: 'animals', difficulty: 'easy' },
  { word: 'ekmek', category: 'animals', difficulty: 'easy' },
  { word: 'süt', category: 'animals', difficulty: 'easy' },
  { word: 'yumurta', category: 'animals', difficulty: 'easy' },
  { word: 'peynir', category: 'animals', difficulty: 'easy' },
  { word: 'kahve', category: 'animals', difficulty: 'easy' },
  { word: 'çay', category: 'animals', difficulty: 'medium' },
  { word: 'portakal', category: 'animals', difficulty: 'medium' },
  { word: 'domates', category: 'animals', difficulty: 'medium' },
  { word: 'patates', category: 'animals', difficulty: 'medium' },
  { word: 'siyah', category: 'animals', difficulty: 'medium' },
  { word: 'beyaz', category: 'animals', difficulty: 'medium' },
  { word: 'pembe', category: 'animals', difficulty: 'medium' },
  { word: 'mor', category: 'animals', difficulty: 'medium' },
  { word: 'heyecanlı', category: 'animals', difficulty: 'medium' },
  { word: 'yorgun', category: 'animals', difficulty: 'medium' },
  { word: 'sakin', category: 'animals', difficulty: 'medium' },
  { word: 'sevmek', category: 'animals', difficulty: 'medium' },
  { word: 'sandalye', category: 'animals', difficulty: 'medium' },
  { word: 'masa', category: 'animals', difficulty: 'medium' },
  { word: 'kapı', category: 'animals', difficulty: 'medium' },
  { word: 'pencere', category: 'animals', difficulty: 'medium' },
  { word: 'saat', category: 'animals', difficulty: 'medium' },
  { word: 'çiçek', category: 'animals', difficulty: 'medium' },
  { word: 'çimen', category: 'animals', difficulty: 'medium' },
  { word: 'bulut', category: 'animals', difficulty: 'medium' },
  { word: 'kar', category: 'animals', difficulty: 'hard' },
  { word: 'nehir', category: 'animals', difficulty: 'hard' },
  { word: 'göl', category: 'animals', difficulty: 'hard' },
  { word: 'okyanus', category: 'animals', difficulty: 'hard' },
  { word: 'plaj', category: 'animals', difficulty: 'hard' },
  { word: 'orman', category: 'animals', difficulty: 'hard' },
  { word: 'park', category: 'animals', difficulty: 'hard' },
  { word: 'hastane', category: 'animals', difficulty: 'hard' },
  { word: 'otel', category: 'animals', difficulty: 'hard' },
  { word: 'rakun', category: 'animals', difficulty: 'hard' },
  { word: 'pelikan', category: 'animals', difficulty: 'hard' },
  { word: 'martı', category: 'animals', difficulty: 'hard' },
  { word: 'denizanası', category: 'animals', difficulty: 'hard' },
  { word: 'denizyıldızı', category: 'animals', difficulty: 'hard' },
  { word: 'denizatı', category: 'animals', difficulty: 'hard' },
  { word: 'akrep', category: 'animals', difficulty: 'hard' },
  { word: 'tırtıl', category: 'animals', difficulty: 'hard' },
  { word: 'uğur böceği', category: 'animals', difficulty: 'hard' },
  { word: 'sivrisinek', category: 'animals', difficulty: 'hard' },
  { word: 'çekirge', category: 'animals', difficulty: 'hard' },
  { word: 'ekmek', category: 'food', difficulty: 'easy' },
  { word: 'süt', category: 'food', difficulty: 'easy' },
  { word: 'yumurta', category: 'food', difficulty: 'easy' },
  { word: 'peynir', category: 'food', difficulty: 'easy' },
  { word: 'su', category: 'food', difficulty: 'easy' },
  { word: 'kahve', category: 'food', difficulty: 'easy' },
  { word: 'çay', category: 'food', difficulty: 'easy' },
  { word: 'portakal', category: 'food', difficulty: 'easy' },
  { word: 'üzüm', category: 'food', difficulty: 'easy' },
  { word: 'çilek', category: 'food', difficulty: 'easy' },
  { word: 'havuç', category: 'food', difficulty: 'easy' },
  { word: 'domates', category: 'food', difficulty: 'easy' },
  { word: 'patates', category: 'food', difficulty: 'easy' },
  { word: 'burger', category: 'food', difficulty: 'easy' },
  { word: 'sandviç', category: 'food', difficulty: 'easy' },
  { word: 'çorba', category: 'food', difficulty: 'medium' },
  { word: 'salata', category: 'food', difficulty: 'medium' },
  { word: 'makarna', category: 'food', difficulty: 'medium' },
  { word: 'pilav', category: 'food', difficulty: 'medium' },
  { word: 'tavuk', category: 'food', difficulty: 'medium' },
  { word: 'biftek', category: 'food', difficulty: 'medium' },
  { word: 'suşi', category: 'food', difficulty: 'medium' },
  { word: 'gözleme', category: 'food', difficulty: 'medium' },
  { word: 'vafıl', category: 'food', difficulty: 'medium' },
  { word: 'donut', category: 'food', difficulty: 'medium' },
  { word: 'kurabiye', category: 'food', difficulty: 'medium' },
  { word: 'çikolata', category: 'food', difficulty: 'medium' },
  { word: 'karpuz', category: 'food', difficulty: 'medium' },
  { word: 'ananas', category: 'food', difficulty: 'medium' },
  { word: 'avokado', category: 'food', difficulty: 'medium' },
  { word: 'brokoli', category: 'food', difficulty: 'medium' },
  { word: 'salatalık', category: 'food', difficulty: 'medium' },
  { word: 'biber', category: 'food', difficulty: 'medium' },
  { word: 'soğan', category: 'food', difficulty: 'medium' },
  { word: 'sarımsak', category: 'food', difficulty: 'medium' },
  { word: 'bal', category: 'food', difficulty: 'medium' },
  { word: 'reçel', category: 'food', difficulty: 'medium' },
  { word: 'tereyağı', category: 'food', difficulty: 'medium' },
  { word: 'mısır gevreği', category: 'food', difficulty: 'medium' },
  { word: 'patlamış mısır', category: 'food', difficulty: 'medium' },
  { word: 'kruvasan', category: 'food', difficulty: 'hard' },
  { word: 'simit', category: 'food', difficulty: 'hard' },
  { word: 'humus', category: 'food', difficulty: 'hard' },
  { word: 'kinoa', category: 'food', difficulty: 'hard' },
  { word: 'trüf mantarı', category: 'food', difficulty: 'hard' },
  { word: 'havyar', category: 'food', difficulty: 'hard' },
  { word: 'lokum', category: 'food', difficulty: 'hard' },
  { word: 'tarçın', category: 'food', difficulty: 'hard' },
  { word: 'vanilya', category: 'food', difficulty: 'hard' },
  { word: 'zencefil', category: 'food', difficulty: 'hard' },
  { word: 'nane', category: 'food', difficulty: 'hard' },
  { word: 'fesleğen', category: 'food', difficulty: 'hard' },
  { word: 'kekik', category: 'food', difficulty: 'hard' },
  { word: 'maydanoz', category: 'food', difficulty: 'hard' },
  { word: 'hindistan cevizi', category: 'food', difficulty: 'hard' },
  { word: 'badem', category: 'food', difficulty: 'hard' },
  { word: 'ceviz', category: 'food', difficulty: 'hard' },
  { word: 'antep fıstığı', category: 'food', difficulty: 'hard' },
  { word: 'ahududu', category: 'food', difficulty: 'hard' },
  { word: 'böğürtlen', category: 'food', difficulty: 'hard' },
  { word: 'yaban mersini', category: 'food', difficulty: 'hard' },
  { word: 'kızılcık', category: 'food', difficulty: 'hard' },
  { word: 'siyah', category: 'colors', difficulty: 'easy' },
  { word: 'beyaz', category: 'colors', difficulty: 'easy' },
  { word: 'pembe', category: 'colors', difficulty: 'easy' },
  { word: 'mor', category: 'colors', difficulty: 'easy' },
  { word: 'portakal', category: 'colors', difficulty: 'easy' },
  { word: 'kahverengi', category: 'colors', difficulty: 'easy' },
  { word: 'gri', category: 'colors', difficulty: 'easy' },
  { word: 'altın', category: 'colors', difficulty: 'medium' },
  { word: 'gümüş', category: 'colors', difficulty: 'medium' },
  { word: 'turkuaz', category: 'colors', difficulty: 'medium' },
  { word: 'lacivert', category: 'colors', difficulty: 'medium' },
  { word: 'bordo', category: 'colors', difficulty: 'medium' },
  { word: 'bej', category: 'colors', difficulty: 'medium' },
  { word: 'mercan', category: 'colors', difficulty: 'medium' },
  { word: 'lavanta', category: 'colors', difficulty: 'medium' },
  { word: 'kehribar', category: 'colors', difficulty: 'medium' },
  { word: 'çivit', category: 'colors', difficulty: 'medium' },
  { word: 'menekşe', category: 'colors', difficulty: 'medium' },
  { word: 'deniz mavisi', category: 'colors', difficulty: 'medium' },
  { word: 'zeytin', category: 'colors', difficulty: 'medium' },
  { word: 'taba', category: 'colors', difficulty: 'medium' },
  { word: 'krem', category: 'colors', difficulty: 'medium' },
  { word: 'koyu kırmızı', category: 'colors', difficulty: 'hard' },
  { word: 'al', category: 'colors', difficulty: 'hard' },
  { word: 'bordo', category: 'colors', difficulty: 'hard' },
  { word: 'macenta', category: 'colors', difficulty: 'hard' },
  { word: 'fuşya', category: 'colors', difficulty: 'hard' },
  { word: 'somon', category: 'colors', difficulty: 'hard' },
  { word: 'şeftali', category: 'colors', difficulty: 'hard' },
  { word: 'eflatun', category: 'colors', difficulty: 'hard' },
  { word: 'erik', category: 'colors', difficulty: 'hard' },
  { word: 'camgöbeği', category: 'colors', difficulty: 'hard' },
  { word: 'gök mavisi', category: 'colors', difficulty: 'hard' },
  { word: 'fildişi', category: 'colors', difficulty: 'hard' },
  { word: 'kömür', category: 'colors', difficulty: 'hard' },
  { word: 'hardal', category: 'colors', difficulty: 'hard' },
  { word: 'pas', category: 'colors', difficulty: 'hard' },
  { word: 'bronz', category: 'colors', difficulty: 'hard' },
  { word: 'bakır', category: 'colors', difficulty: 'hard' },
  { word: 'zümrüt', category: 'colors', difficulty: 'hard' },
  { word: 'safir', category: 'colors', difficulty: 'hard' },
  { word: 'yakut', category: 'colors', difficulty: 'hard' },
  { word: 'yeşim', category: 'colors', difficulty: 'hard' },
  { word: 'mercan', category: 'colors', difficulty: 'hard' },
  { word: 'lavanta', category: 'colors', difficulty: 'hard' },
  { word: 'nane', category: 'colors', difficulty: 'hard' },
  { word: 'leylak', category: 'colors', difficulty: 'hard' },
  { word: 'sarımsı yeşil', category: 'colors', difficulty: 'hard' },
  { word: 'kırmızı', category: 'colors', difficulty: 'hard' },
  { word: 'gök mavisi', category: 'colors', difficulty: 'hard' },
  { word: 'okra', category: 'colors', difficulty: 'hard' },
  { word: 'heyecanlı', category: 'emotions', difficulty: 'easy' },
  { word: 'yorgun', category: 'emotions', difficulty: 'easy' },
  { word: 'gergin', category: 'emotions', difficulty: 'easy' },
  { word: 'sakin', category: 'emotions', difficulty: 'easy' },
  { word: 'aşk', category: 'emotions', difficulty: 'easy' },
  { word: 'neşe', category: 'emotions', difficulty: 'medium' },
  { word: 'korku', category: 'emotions', difficulty: 'medium' },
  { word: 'öfke', category: 'emotions', difficulty: 'medium' },
  { word: 'umut', category: 'emotions', difficulty: 'medium' },
  { word: 'gurur', category: 'emotions', difficulty: 'medium' },
  { word: 'utanç', category: 'emotions', difficulty: 'medium' },
  { word: 'suçluluk', category: 'emotions', difficulty: 'medium' },
  { word: 'kıskançlık', category: 'emotions', difficulty: 'medium' },
  { word: 'can sıkıntısı', category: 'emotions', difficulty: 'medium' },
  { word: 'kafa karışıklığı', category: 'emotions', difficulty: 'medium' },
  { word: 'merak', category: 'emotions', difficulty: 'medium' },
  { word: 'minnettarlık', category: 'emotions', difficulty: 'medium' },
  { word: 'rahatlama', category: 'emotions', difficulty: 'medium' },
  { word: 'hayal kırıklığı', category: 'emotions', difficulty: 'medium' },
  { word: 'utangaçlık', category: 'emotions', difficulty: 'medium' },
  { word: 'hayal kırıklığı', category: 'emotions', difficulty: 'medium' },
  { word: 'kaygı', category: 'emotions', difficulty: 'medium' },
  { word: 'heves', category: 'emotions', difficulty: 'medium' },
  { word: 'memnuniyet', category: 'emotions', difficulty: 'medium' },
  { word: 'yalnızlık', category: 'emotions', difficulty: 'medium' },
  { word: 'nostalji', category: 'emotions', difficulty: 'hard' },
  { word: 'melankoli', category: 'emotions', difficulty: 'hard' },
  { word: 'öfori', category: 'emotions', difficulty: 'hard' },
  { word: 'huzur', category: 'emotions', difficulty: 'hard' },
  { word: 'şaşkınlık', category: 'emotions', difficulty: 'hard' },
  { word: 'eğlence', category: 'emotions', difficulty: 'hard' },
  { word: 'hayret', category: 'emotions', difficulty: 'hard' },
  { word: 'kararlılık', category: 'emotions', difficulty: 'hard' },
  { word: 'boğulmuş', category: 'emotions', difficulty: 'hard' },
  { word: 'kızgınlık', category: 'emotions', difficulty: 'hard' },
  { word: 'hayranlık', category: 'emotions', difficulty: 'hard' },
  { word: 'beklenti', category: 'emotions', difficulty: 'hard' },
  { word: 'endişe', category: 'emotions', difficulty: 'hard' },
  { word: 'küçümseme', category: 'emotions', difficulty: 'hard' },
  { word: 'bağlılık', category: 'emotions', difficulty: 'hard' },
  { word: 'dehşet', category: 'emotions', difficulty: 'hard' },
  { word: 'vecit', category: 'emotions', difficulty: 'hard' },
  { word: 'kıskançlık', category: 'emotions', difficulty: 'hard' },
  { word: 'keder', category: 'emotions', difficulty: 'hard' },
  { word: 'kayıtsızlık', category: 'emotions', difficulty: 'hard' },
  { word: 'özlem', category: 'emotions', difficulty: 'hard' },
  { word: 'öfke', category: 'emotions', difficulty: 'hard' },
  { word: 'pişmanlık', category: 'emotions', difficulty: 'hard' },
  { word: 'vicdan azabı', category: 'emotions', difficulty: 'hard' },
  { word: 'tatmin', category: 'emotions', difficulty: 'hard' },
  { word: 'keder', category: 'emotions', difficulty: 'hard' },
  { word: 'gerilim', category: 'emotions', difficulty: 'hard' },
  { word: 'sempati', category: 'emotions', difficulty: 'hard' },
  { word: 'terör', category: 'emotions', difficulty: 'hard' },
  { word: 'hayranlık', category: 'emotions', difficulty: 'hard' },
  { word: 'sandalye', category: 'objects', difficulty: 'easy' },
  { word: 'masa', category: 'objects', difficulty: 'easy' },
  { word: 'lamba', category: 'objects', difficulty: 'easy' },
  { word: 'kapı', category: 'objects', difficulty: 'easy' },
  { word: 'pencere', category: 'objects', difficulty: 'easy' },
  { word: 'saat', category: 'objects', difficulty: 'easy' },
  { word: 'kol saati', category: 'objects', difficulty: 'easy' },
  { word: 'çanta', category: 'objects', difficulty: 'easy' },
  { word: 'fincan', category: 'objects', difficulty: 'easy' },
  { word: 'kalem', category: 'objects', difficulty: 'easy' },
  { word: 'ayna', category: 'objects', difficulty: 'medium' },
  { word: 'yastık', category: 'objects', difficulty: 'medium' },
  { word: 'battaniye', category: 'objects', difficulty: 'medium' },
  { word: 'kanepe', category: 'objects', difficulty: 'medium' },
  { word: 'gözlük', category: 'objects', difficulty: 'medium' },
  { word: 'cüzdan', category: 'objects', difficulty: 'medium' },
  { word: 'sırt çantası', category: 'objects', difficulty: 'medium' },
  { word: 'şişe', category: 'objects', difficulty: 'medium' },
  { word: 'makas', category: 'objects', difficulty: 'medium' },
  { word: 'çekiç', category: 'objects', difficulty: 'medium' },
  { word: 'fırça', category: 'objects', difficulty: 'medium' },
  { word: 'tarak', category: 'objects', difficulty: 'medium' },
  { word: 'diş fırçası', category: 'objects', difficulty: 'medium' },
  { word: 'havlu', category: 'objects', difficulty: 'medium' },
  { word: 'gazete', category: 'objects', difficulty: 'medium' },
  { word: 'dergi', category: 'objects', difficulty: 'medium' },
  { word: 'kumanda', category: 'objects', difficulty: 'medium' },
  { word: 'kulaklık', category: 'objects', difficulty: 'medium' },
  { word: 'dizüstü bilgisayar', category: 'objects', difficulty: 'medium' },
  { word: 'klavye', category: 'objects', difficulty: 'medium' },
  { word: 'fare', category: 'objects', difficulty: 'medium' },
  { word: 'hoparlör', category: 'objects', difficulty: 'medium' },
  { word: 'mikrofon', category: 'objects', difficulty: 'medium' },
  { word: 'el feneri', category: 'objects', difficulty: 'medium' },
  { word: 'pil', category: 'objects', difficulty: 'medium' },
  { word: 'şarj cihazı', category: 'objects', difficulty: 'medium' },
  { word: 'vazo', category: 'objects', difficulty: 'hard' },
  { word: 'şemsiye', category: 'objects', difficulty: 'hard' },
  { word: 'güneş şemsiyesi', category: 'objects', difficulty: 'hard' },
  { word: 'dürbün', category: 'objects', difficulty: 'hard' },
  { word: 'teleskop', category: 'objects', difficulty: 'hard' },
  { word: 'pusula', category: 'objects', difficulty: 'hard' },
  { word: 'termometre', category: 'objects', difficulty: 'hard' },
  { word: 'büyüteç', category: 'objects', difficulty: 'hard' },
  { word: 'tornavida', category: 'objects', difficulty: 'hard' },
  { word: 'İngiliz anahtarı', category: 'objects', difficulty: 'hard' },
  { word: 'pense', category: 'objects', difficulty: 'hard' },
  { word: 'iğne', category: 'objects', difficulty: 'hard' },
  { word: 'iplik', category: 'objects', difficulty: 'hard' },
  { word: 'bavul', category: 'objects', difficulty: 'hard' },
  { word: 'evrak çantası', category: 'objects', difficulty: 'hard' },
  { word: 'şemsiye standı', category: 'objects', difficulty: 'hard' },
  { word: 'askı', category: 'objects', difficulty: 'hard' },
  { word: 'kapı zili', category: 'objects', difficulty: 'hard' },
  { word: 'kapı tokmağı', category: 'objects', difficulty: 'hard' },
  { word: 'perde', category: 'objects', difficulty: 'hard' },
  { word: 'jaluz', category: 'objects', difficulty: 'hard' },
  { word: 'avize', category: 'objects', difficulty: 'hard' },
  { word: 'şamdan', category: 'objects', difficulty: 'hard' },
  { word: 'kum saati', category: 'objects', difficulty: 'hard' },
  { word: 'güneş saati', category: 'objects', difficulty: 'hard' },
  { word: 'küre', category: 'objects', difficulty: 'hard' },
  { word: 'atlas', category: 'objects', difficulty: 'hard' },
  { word: 'ansiklopedi', category: 'objects', difficulty: 'hard' },
  { word: 'albüm', category: 'objects', difficulty: 'hard' },
  { word: 'fotoğraf albümü', category: 'objects', difficulty: 'hard' },
  { word: 'mücevher kutusu', category: 'objects', difficulty: 'hard' },
  { word: 'kumbara', category: 'objects', difficulty: 'hard' },
  { word: 'çiçek', category: 'nature', difficulty: 'easy' },
  { word: 'çimen', category: 'nature', difficulty: 'easy' },
  { word: 'bulut', category: 'nature', difficulty: 'easy' },
  { word: 'kar', category: 'nature', difficulty: 'easy' },
  { word: 'rüzgar', category: 'nature', difficulty: 'easy' },
  { word: 'nehir', category: 'nature', difficulty: 'easy' },
  { word: 'göl', category: 'nature', difficulty: 'easy' },
  { word: 'okyanus', category: 'nature', difficulty: 'easy' },
  { word: 'plaj', category: 'nature', difficulty: 'easy' },
  { word: 'orman', category: 'nature', difficulty: 'easy' },
  { word: 'kaya', category: 'nature', difficulty: 'medium' },
  { word: 'ada', category: 'nature', difficulty: 'medium' },
  { word: 'şelale', category: 'nature', difficulty: 'medium' },
  { word: 'yanardağ', category: 'nature', difficulty: 'medium' },
  { word: 'çöl', category: 'nature', difficulty: 'medium' },
  { word: 'vadi', category: 'nature', difficulty: 'medium' },
  { word: 'kanyon', category: 'nature', difficulty: 'medium' },
  { word: 'uçurum', category: 'nature', difficulty: 'medium' },
  { word: 'çayır', category: 'nature', difficulty: 'medium' },
  { word: 'dere', category: 'nature', difficulty: 'medium' },
  { word: 'gölet', category: 'nature', difficulty: 'medium' },
  { word: 'dalga', category: 'nature', difficulty: 'medium' },
  { word: 'fırtına', category: 'nature', difficulty: 'medium' },
  { word: 'gök gürültüsü', category: 'nature', difficulty: 'medium' },
  { word: 'şimşek', category: 'nature', difficulty: 'medium' },
  { word: 'sis', category: 'nature', difficulty: 'medium' },
  { word: 'pus', category: 'nature', difficulty: 'medium' },
  { word: 'çiy', category: 'nature', difficulty: 'medium' },
  { word: 'kırağı', category: 'nature', difficulty: 'medium' },
  { word: 'dolu', category: 'nature', difficulty: 'medium' },
  { word: 'kasırga', category: 'nature', difficulty: 'medium' },
  { word: 'hortum', category: 'nature', difficulty: 'medium' },
  { word: 'deprem', category: 'nature', difficulty: 'medium' },
  { word: 'çığ', category: 'nature', difficulty: 'medium' },
  { word: 'orman yangını', category: 'nature', difficulty: 'medium' },
  { word: 'gayzer', category: 'nature', difficulty: 'hard' },
  { word: 'buzul', category: 'nature', difficulty: 'hard' },
  { word: 'buzdağı', category: 'nature', difficulty: 'hard' },
  { word: 'vaha', category: 'nature', difficulty: 'hard' },
  { word: 'yarımada', category: 'nature', difficulty: 'hard' },
  { word: 'takımada', category: 'nature', difficulty: 'hard' },
  { word: 'haliç', category: 'nature', difficulty: 'hard' },
  { word: 'delta', category: 'nature', difficulty: 'hard' },
  { word: 'kol', category: 'nature', difficulty: 'hard' },
  { word: 'rezervuar', category: 'nature', difficulty: 'hard' },
  { word: 'sulak alan', category: 'nature', difficulty: 'hard' },
  { word: 'bataklık', category: 'nature', difficulty: 'hard' },
  { word: 'batak', category: 'nature', difficulty: 'hard' },
  { word: 'tundra', category: 'nature', difficulty: 'hard' },
  { word: 'savan', category: 'nature', difficulty: 'hard' },
  { word: 'bozkır', category: 'nature', difficulty: 'hard' },
  { word: 'orman', category: 'nature', difficulty: 'hard' },
  { word: 'resif', category: 'nature', difficulty: 'hard' },
  { word: 'mercan', category: 'nature', difficulty: 'hard' },
  { word: 'kum tepesi', category: 'nature', difficulty: 'hard' },
  { word: 'krater', category: 'nature', difficulty: 'hard' },
  { word: 'zirve', category: 'nature', difficulty: 'hard' },
  { word: 'sırt', category: 'nature', difficulty: 'hard' },
  { word: 'yayla', category: 'nature', difficulty: 'hard' },
  { word: 'koru', category: 'nature', difficulty: 'hard' },
  { word: 'çalılık', category: 'nature', difficulty: 'hard' },
  { word: 'orman örtüsü', category: 'nature', difficulty: 'hard' },
  { word: 'alt bitki örtüsü', category: 'nature', difficulty: 'hard' },
  { word: 'çiçeklenme', category: 'nature', difficulty: 'hard' },
  { word: 'taç yaprağı', category: 'nature', difficulty: 'hard' },
  { word: 'diken', category: 'nature', difficulty: 'hard' },
  { word: 'asma', category: 'nature', difficulty: 'hard' },
  { word: 'yosun', category: 'nature', difficulty: 'hard' },
  { word: 'eğreltiotu', category: 'nature', difficulty: 'hard' },
  { word: 'kaktüs', category: 'nature', difficulty: 'hard' },

  { word: 'futbol', category: 'sports', difficulty: 'easy' },
  { word: 'beyzbol', category: 'sports', difficulty: 'easy' },
  { word: 'golf', category: 'sports', difficulty: 'easy' },
  { word: 'boks', category: 'sports', difficulty: 'easy' },
  { word: 'güreş', category: 'sports', difficulty: 'easy' },
  { word: 'kayak', category: 'sports', difficulty: 'easy' },
  { word: 'buz pateni', category: 'sports', difficulty: 'easy' },
  { word: 'koşu', category: 'sports', difficulty: 'easy' },
  { word: 'yoga', category: 'sports', difficulty: 'easy' },
  { word: 'dalış', category: 'sports', difficulty: 'easy' },
  { word: 'voleybol', category: 'sports', difficulty: 'medium' },
  { word: 'hokey', category: 'sports', difficulty: 'medium' },
  { word: 'ragbi', category: 'sports', difficulty: 'medium' },
  { word: 'badminton', category: 'sports', difficulty: 'medium' },
  { word: 'kürek', category: 'sports', difficulty: 'medium' },
  { word: 'kano', category: 'sports', difficulty: 'medium' },
  { word: 'snowboard', category: 'sports', difficulty: 'medium' },
  { word: 'jimnastik', category: 'sports', difficulty: 'medium' },
  { word: 'dövüş sanatları', category: 'sports', difficulty: 'medium' },
  { word: 'halter', category: 'sports', difficulty: 'medium' },
  { word: 'atlama', category: 'sports', difficulty: 'medium' },
  { word: 'tırmanma', category: 'sports', difficulty: 'medium' },
  { word: 'eskrim', category: 'sports', difficulty: 'medium' },
  { word: 'okçuluk', category: 'sports', difficulty: 'medium' },
  { word: 'bowling', category: 'sports', difficulty: 'medium' },
  { word: 'bilardo', category: 'sports', difficulty: 'medium' },
  { word: 'dart', category: 'sports', difficulty: 'medium' },
  { word: 'masa tenisi', category: 'sports', difficulty: 'medium' },
  { word: 'maraton', category: 'sports', difficulty: 'medium' },
  { word: 'sprint', category: 'sports', difficulty: 'medium' },
  { word: 'triatlon', category: 'sports', difficulty: 'medium' },
  { word: 'pentatlon', category: 'sports', difficulty: 'hard' },
  { word: 'dekatlon', category: 'sports', difficulty: 'hard' },
  { word: 'paraşütle atlama', category: 'sports', difficulty: 'hard' },
  { word: 'yamaç paraşütü', category: 'sports', difficulty: 'hard' },
  { word: 'kaya tırmanışı', category: 'sports', difficulty: 'hard' },
  { word: 'bobsled', category: 'sports', difficulty: 'hard' },
  { word: 'curling', category: 'sports', difficulty: 'hard' },
  { word: 'polo', category: 'sports', difficulty: 'hard' },
  { word: 'lakros', category: 'sports', difficulty: 'hard' },
  { word: 'kriket', category: 'sports', difficulty: 'hard' },
  { word: 'squash', category: 'sports', difficulty: 'hard' },
  { word: 'raketle top', category: 'sports', difficulty: 'hard' },
  { word: 'cirit atma', category: 'sports', difficulty: 'hard' },
  { word: 'gülle atma', category: 'sports', difficulty: 'hard' },
  { word: 'disk atma', category: 'sports', difficulty: 'hard' },
  { word: 'çekiç atma', category: 'sports', difficulty: 'hard' },
  { word: 'yüksek atlama', category: 'sports', difficulty: 'hard' },
  { word: 'uzun atlama', category: 'sports', difficulty: 'hard' },
  { word: 'sırıkla atlama', category: 'sports', difficulty: 'hard' },
  { word: 'engelli koşu', category: 'sports', difficulty: 'hard' },
  { word: 'bayrak yarışı', category: 'sports', difficulty: 'hard' },
  { word: 'senkronize yüzme', category: 'sports', difficulty: 'hard' },
  { word: 'su topu', category: 'sports', difficulty: 'hard' },
  { word: 'sörf', category: 'sports', difficulty: 'hard' },
  { word: 'rüzgar sörfü', category: 'sports', difficulty: 'hard' },
  { word: 'uçurtma sörfü', category: 'sports', difficulty: 'hard' },
  { word: 'tüplü dalış', category: 'sports', difficulty: 'hard' },
  { word: 'şnorkelle dalış', category: 'sports', difficulty: 'hard' },
  { word: 'yamaç paraşütü uçuşu', category: 'sports', difficulty: 'hard' },
  { word: 'serbest atlama', category: 'sports', difficulty: 'hard' },
  { word: 'bungee atlama', category: 'sports', difficulty: 'hard' },
  { word: 'parkur', category: 'sports', difficulty: 'hard' },
  { word: 'breakdans', category: 'sports', difficulty: 'hard' },

  { word: 'hemşire', category: 'professions', difficulty: 'easy' },
  { word: 'sürücü', category: 'professions', difficulty: 'easy' },
  { word: 'aşçı', category: 'professions', difficulty: 'easy' },
  { word: 'sanatçı', category: 'professions', difficulty: 'easy' },
  { word: 'şarkıcı', category: 'professions', difficulty: 'easy' },
  { word: 'aktör', category: 'professions', difficulty: 'easy' },
  { word: 'çiftçi', category: 'professions', difficulty: 'easy' },
  { word: 'pilot', category: 'professions', difficulty: 'easy' },
  { word: 'asker', category: 'professions', difficulty: 'easy' },
  { word: 'polis', category: 'professions', difficulty: 'easy' },
  { word: 'avukat', category: 'professions', difficulty: 'medium' },
  { word: 'hâkim', category: 'professions', difficulty: 'medium' },
  { word: 'yazar', category: 'professions', difficulty: 'medium' },
  { word: 'gazeteci', category: 'professions', difficulty: 'medium' },
  { word: 'fotoğrafçı', category: 'professions', difficulty: 'medium' },
  { word: 'mimar', category: 'professions', difficulty: 'medium' },
  { word: 'mühendis', category: 'professions', difficulty: 'medium' },
  { word: 'bilim insanı', category: 'professions', difficulty: 'medium' },
  { word: 'astronot', category: 'professions', difficulty: 'medium' },
  { word: 'itfaiyeci', category: 'professions', difficulty: 'medium' },
  { word: 'tamirci', category: 'professions', difficulty: 'medium' },
  { word: 'elektrikçi', category: 'professions', difficulty: 'medium' },
  { word: 'tesisatçı', category: 'professions', difficulty: 'medium' },
  { word: 'marangoz', category: 'professions', difficulty: 'medium' },
  { word: 'ressam', category: 'professions', difficulty: 'medium' },
  { word: 'terzi', category: 'professions', difficulty: 'medium' },
  { word: 'berber', category: 'professions', difficulty: 'medium' },
  { word: 'diş hekimi', category: 'professions', difficulty: 'medium' },
  { word: 'veteriner', category: 'professions', difficulty: 'medium' },
  { word: 'kütüphaneci', category: 'professions', difficulty: 'medium' },
  { word: 'muhasebeci', category: 'professions', difficulty: 'medium' },
  { word: 'bankacı', category: 'professions', difficulty: 'medium' },
  { word: 'emlakçı', category: 'professions', difficulty: 'medium' },
  { word: 'dedektif', category: 'professions', difficulty: 'medium' },
  { word: 'casus', category: 'professions', difficulty: 'medium' },
  { word: 'sihirbaz', category: 'professions', difficulty: 'medium' },
  { word: 'palyaço', category: 'professions', difficulty: 'medium' },
  { word: 'dansçı', category: 'professions', difficulty: 'medium' },
  { word: 'müzisyen', category: 'professions', difficulty: 'medium' },
  { word: 'besteci', category: 'professions', difficulty: 'hard' },
  { word: 'orkestra şefi', category: 'professions', difficulty: 'hard' },
  { word: 'küratör', category: 'professions', difficulty: 'hard' },
  { word: 'arşivci', category: 'professions', difficulty: 'hard' },
  { word: 'antropolog', category: 'professions', difficulty: 'hard' },
  { word: 'arkeolog', category: 'professions', difficulty: 'hard' },
  { word: 'jeolog', category: 'professions', difficulty: 'hard' },
  { word: 'astronom', category: 'professions', difficulty: 'hard' },
  { word: 'biyolog', category: 'professions', difficulty: 'hard' },
  { word: 'kimyager', category: 'professions', difficulty: 'hard' },
  { word: 'fizikçi', category: 'professions', difficulty: 'hard' },
  { word: 'psikolog', category: 'professions', difficulty: 'hard' },
  { word: 'terapist', category: 'professions', difficulty: 'hard' },
  { word: 'cerrah', category: 'professions', difficulty: 'hard' },
  { word: 'paramedik', category: 'professions', difficulty: 'hard' },
  { word: 'eczacı', category: 'professions', difficulty: 'hard' },
  { word: 'diplomat', category: 'professions', difficulty: 'hard' },
  { word: 'büyükelçi', category: 'professions', difficulty: 'hard' },
  { word: 'yargıç', category: 'professions', difficulty: 'hard' },
  { word: 'noter', category: 'professions', difficulty: 'hard' },
  { word: 'denetçi', category: 'professions', difficulty: 'hard' },
  { word: 'aktüer', category: 'professions', difficulty: 'hard' },
  { word: 'kartograf', category: 'professions', difficulty: 'hard' },
  { word: 'çevirmen', category: 'professions', difficulty: 'hard' },
  { word: 'tercüman', category: 'professions', difficulty: 'hard' },
  { word: 'editör', category: 'professions', difficulty: 'hard' },
  { word: 'yayıncı', category: 'professions', difficulty: 'hard' },
  { word: 'illüstratör', category: 'professions', difficulty: 'hard' },
  { word: 'heykeltıraş', category: 'professions', difficulty: 'hard' },
  { word: 'çömlekçi', category: 'professions', difficulty: 'hard' },
  { word: 'demirci', category: 'professions', difficulty: 'hard' },
  { word: 'kuyumcu', category: 'professions', difficulty: 'hard' },
  { word: 'saatçi', category: 'professions', difficulty: 'hard' },
  { word: 'çilingir', category: 'professions', difficulty: 'hard' },
  { word: 'çiçekçi', category: 'professions', difficulty: 'hard' },
  { word: 'sommelier', category: 'professions', difficulty: 'hard' },
  { word: 'başgarson', category: 'professions', difficulty: 'hard' },
  { word: 'kapıcı', category: 'professions', difficulty: 'hard' },
  { word: 'hostes', category: 'professions', difficulty: 'hard' },
  { word: 'navigator', category: 'professions', difficulty: 'hard' },

  { word: 'park', category: 'places', difficulty: 'easy' },
  { word: 'hastane', category: 'places', difficulty: 'easy' },
  { word: 'otel', category: 'places', difficulty: 'easy' },
  { word: 'dükkan', category: 'places', difficulty: 'easy' },
  { word: 'sokak', category: 'places', difficulty: 'easy' },
  { word: 'kütüphane', category: 'places', difficulty: 'easy' },
  { word: 'müze', category: 'places', difficulty: 'easy' },
  { word: 'sinema', category: 'places', difficulty: 'easy' },
  { word: 'stadyum', category: 'places', difficulty: 'easy' },
  { word: 'havalimanı', category: 'places', difficulty: 'easy' },
  { word: 'istasyon', category: 'places', difficulty: 'medium' },
  { word: 'liman', category: 'places', difficulty: 'medium' },
  { word: 'pazar', category: 'places', difficulty: 'medium' },
  { word: 'alışveriş merkezi', category: 'places', difficulty: 'medium' },
  { word: 'banka', category: 'places', difficulty: 'medium' },
  { word: 'postane', category: 'places', difficulty: 'medium' },
  { word: 'adliye', category: 'places', difficulty: 'medium' },
  { word: 'hapishane', category: 'places', difficulty: 'medium' },
  { word: 'kilise', category: 'places', difficulty: 'medium' },
  { word: 'tapınak', category: 'places', difficulty: 'medium' },
  { word: 'cami', category: 'places', difficulty: 'medium' },
  { word: 'kale', category: 'places', difficulty: 'medium' },
  { word: 'saray', category: 'places', difficulty: 'medium' },
  { word: 'kule', category: 'places', difficulty: 'medium' },
  { word: 'köprü', category: 'places', difficulty: 'medium' },
  { word: 'tünel', category: 'places', difficulty: 'medium' },
  { word: 'otoyol', category: 'places', difficulty: 'medium' },
  { word: 'bulvar', category: 'places', difficulty: 'medium' },
  { word: 'ara sokak', category: 'places', difficulty: 'medium' },
  { word: 'meydan', category: 'places', difficulty: 'medium' },
  { word: 'çeşme', category: 'places', difficulty: 'medium' },
  { word: 'anıt', category: 'places', difficulty: 'medium' },
  { word: 'mezarlık', category: 'places', difficulty: 'medium' },
  { word: 'hayvanat bahçesi', category: 'places', difficulty: 'medium' },
  { word: 'akvaryum', category: 'places', difficulty: 'medium' },
  { word: 'spor salonu', category: 'places', difficulty: 'medium' },
  { word: 'yüzme havuzu', category: 'places', difficulty: 'medium' },
  { word: 'arena', category: 'places', difficulty: 'medium' },
  { word: 'tiyatro', category: 'places', difficulty: 'medium' },
  { word: 'galeri', category: 'places', difficulty: 'medium' },
  { word: 'fırın', category: 'places', difficulty: 'medium' },
  { word: 'kafe', category: 'places', difficulty: 'medium' },
  { word: 'bar', category: 'places', difficulty: 'medium' },
  { word: 'depo', category: 'places', difficulty: 'hard' },
  { word: 'fabrika', category: 'places', difficulty: 'hard' },
  { word: 'laboratuvar', category: 'places', difficulty: 'hard' },
  { word: 'rasathane', category: 'places', difficulty: 'hard' },
  { word: 'planetaryum', category: 'places', difficulty: 'hard' },
  { word: 'katedral', category: 'places', difficulty: 'hard' },
  { word: 'manastır', category: 'places', difficulty: 'hard' },
  { word: 'konvent', category: 'places', difficulty: 'hard' },
  { word: 'mozole', category: 'places', difficulty: 'hard' },
  { word: 'kolezyum', category: 'places', difficulty: 'hard' },
  { word: 'amfitiyatro', category: 'places', difficulty: 'hard' },
  { word: 'pavyon', category: 'places', difficulty: 'hard' },
  { word: 'köşk', category: 'places', difficulty: 'hard' },
  { word: 'deniz feneri', category: 'places', difficulty: 'hard' },
  { word: 'yel değirmeni', category: 'places', difficulty: 'hard' },
  { word: 'su değirmeni', category: 'places', difficulty: 'hard' },
  { word: 'ahır', category: 'places', difficulty: 'hard' },
  { word: 'silo', category: 'places', difficulty: 'hard' },
  { word: 'sera', category: 'places', difficulty: 'hard' },
  { word: 'konservatuvar', category: 'places', difficulty: 'hard' },
  { word: 'arboretum', category: 'places', difficulty: 'hard' },
  { word: 'botanik bahçesi', category: 'places', difficulty: 'hard' },
  { word: 'bağ', category: 'places', difficulty: 'hard' },
  { word: 'bira fabrikası', category: 'places', difficulty: 'hard' },
  { word: 'damıtımevi', category: 'places', difficulty: 'hard' },
  { word: 'butik', category: 'places', difficulty: 'hard' },
  { word: 'emporium', category: 'places', difficulty: 'hard' },
  { word: 'çarşı', category: 'places', difficulty: 'hard' },
  { word: 'şehir merkezi', category: 'places', difficulty: 'hard' },
  { word: 'banliyö', category: 'places', difficulty: 'hard' },
  { word: 'kırsal', category: 'places', difficulty: 'hard' },
  { word: 'metropol', category: 'places', difficulty: 'hard' },
  { word: 'başkent', category: 'places', difficulty: 'hard' },
  { word: 'sınır', category: 'places', difficulty: 'hard' },
  { word: 'kontrol noktası', category: 'places', difficulty: 'hard' },
  { word: 'terminal', category: 'places', difficulty: 'hard' },
  { word: 'garaj', category: 'places', difficulty: 'hard' },
  { word: 'dok', category: 'places', difficulty: 'hard' },
  { word: 'iskele', category: 'places', difficulty: 'hard' },
  { word: 'marina', category: 'places', difficulty: 'hard' },
  { word: 'kanal', category: 'places', difficulty: 'hard' },
  { word: 'rezervuar', category: 'places', difficulty: 'hard' },

  { word: 'yürüyüş', category: 'activities', difficulty: 'easy' },
  { word: 'yemek yemek', category: 'activities', difficulty: 'easy' },
  { word: 'izlemek', category: 'activities', difficulty: 'easy' },
  { word: 'dinlemek', category: 'activities', difficulty: 'easy' },
  { word: 'çizim yapmak', category: 'activities', difficulty: 'easy' },
  { word: 'yazmak', category: 'activities', difficulty: 'easy' },
  { word: 'temizlik', category: 'activities', difficulty: 'easy' },
  { word: 'alışveriş', category: 'activities', difficulty: 'easy' },
  { word: 'araba kullanmak', category: 'activities', difficulty: 'easy' },
  { word: 'binicilik', category: 'activities', difficulty: 'easy' },
  { word: 'çalışmak', category: 'activities', difficulty: 'medium' },
  { word: 'seyahat etmek', category: 'activities', difficulty: 'medium' },
  { word: 'bahçecilik', category: 'activities', difficulty: 'medium' },
  { word: 'fırında pişirmek', category: 'activities', difficulty: 'medium' },
  { word: 'örgü örmek', category: 'activities', difficulty: 'medium' },
  { word: 'dikiş dikmek', category: 'activities', difficulty: 'medium' },
  { word: 'meditasyon', category: 'activities', difficulty: 'medium' },
  { word: 'esneme', category: 'activities', difficulty: 'medium' },
  { word: 'koşu', category: 'activities', difficulty: 'medium' },
  { word: 'doğa yürüyüşü', category: 'activities', difficulty: 'medium' },
  { word: 'kamp yapmak', category: 'activities', difficulty: 'medium' },
  { word: 'piknik', category: 'activities', difficulty: 'medium' },
  { word: 'barbekü', category: 'activities', difficulty: 'medium' },
  { word: 'oynamak', category: 'activities', difficulty: 'medium' },
  { word: 'dans etmek', category: 'activities', difficulty: 'medium' },
  { word: 'oyunculuk', category: 'activities', difficulty: 'medium' },
  { word: 'film çekmek', category: 'activities', difficulty: 'medium' },
  { word: 'video düzenlemek', category: 'activities', difficulty: 'medium' },
  { word: 'blog yazmak', category: 'activities', difficulty: 'medium' },
  { word: 'yayın yapmak', category: 'activities', difficulty: 'medium' },
  { word: 'oyun oynamak', category: 'activities', difficulty: 'medium' },
  { word: 'bulmaca çözmek', category: 'activities', difficulty: 'medium' },
  { word: 'scrapbooking', category: 'activities', difficulty: 'medium' },
  { word: 'koleksiyon yapmak', category: 'activities', difficulty: 'medium' },
  { word: 'gönüllülük', category: 'activities', difficulty: 'medium' },
  { word: 'bağış yapmak', category: 'activities', difficulty: 'medium' },
  { word: 'geri dönüşüm', category: 'activities', difficulty: 'medium' },
  { word: 'kompost yapmak', category: 'activities', difficulty: 'medium' },
  { word: 'kuş gözlemciliği', category: 'activities', difficulty: 'hard' },
  { word: 'yıldız gözlemciliği', category: 'activities', difficulty: 'hard' },
  { word: 'geocaching', category: 'activities', difficulty: 'hard' },
  { word: 'oryantiring', category: 'activities', difficulty: 'hard' },
  { word: 'kaligrafi', category: 'activities', difficulty: 'hard' },
  { word: 'origami', category: 'activities', difficulty: 'hard' },
  { word: 'çömlekçilik', category: 'activities', difficulty: 'hard' },
  { word: 'dokumacılık', category: 'activities', difficulty: 'hard' },
  { word: 'nakış işlemek', category: 'activities', difficulty: 'hard' },
  { word: 'yorgan yapmak', category: 'activities', difficulty: 'hard' },
  { word: 'ahşap işçiliği', category: 'activities', difficulty: 'hard' },
  { word: 'metal işçiliği', category: 'activities', difficulty: 'hard' },
  { word: 'demircilik', category: 'activities', difficulty: 'hard' },
  { word: 'tahta oymacılığı', category: 'activities', difficulty: 'hard' },
  { word: 'heykel yapmak', category: 'activities', difficulty: 'hard' },
  { word: 'eskiz yapmak', category: 'activities', difficulty: 'hard' },
  { word: 'suluboya', category: 'activities', difficulty: 'hard' },
  { word: 'günlük tutmak', category: 'activities', difficulty: 'hard' },
  { word: 'hikaye anlatmak', category: 'activities', difficulty: 'hard' },
  { word: 'tartışmak', category: 'activities', difficulty: 'hard' },
  { word: 'müzakere etmek', category: 'activities', difficulty: 'hard' },
  { word: 'mentorluk', category: 'activities', difficulty: 'hard' },
  { word: 'özel ders vermek', category: 'activities', difficulty: 'hard' },
  { word: 'araştırma yapmak', category: 'activities', difficulty: 'hard' },
  { word: 'deney yapmak', category: 'activities', difficulty: 'hard' },
  { word: 'icat etmek', category: 'activities', difficulty: 'hard' },
  { word: 'beste yapmak', category: 'activities', difficulty: 'hard' },
  { word: 'doğaçlama yapmak', category: 'activities', difficulty: 'hard' },
  { word: 'şef olmak', category: 'activities', difficulty: 'hard' },
  { word: 'koreografi yapmak', category: 'activities', difficulty: 'hard' },
  { word: 'yönetmek', category: 'activities', difficulty: 'hard' },
  { word: 'prodüksiyon yapmak', category: 'activities', difficulty: 'hard' },
  { word: 'yayıncılık', category: 'activities', difficulty: 'hard' },
  { word: 'podcast yapmak', category: 'activities', difficulty: 'hard' },
  { word: 'vlog yapmak', category: 'activities', difficulty: 'hard' },
  { word: 'fotoğrafçılık', category: 'activities', difficulty: 'hard' },
  { word: 'video çekimi', category: 'activities', difficulty: 'hard' },
  { word: 'animasyon yapmak', category: 'activities', difficulty: 'hard' },
  { word: 'tasarım yapmak', category: 'activities', difficulty: 'hard' },
  { word: 'programlama', category: 'activities', difficulty: 'hard' },
  { word: 'hata ayıklama', category: 'activities', difficulty: 'hard' },
  { word: 'ağ kurmak', category: 'activities', difficulty: 'hard' },
  { word: 'sunum yapmak', category: 'activities', difficulty: 'hard' },
  { word: 'halka açık konuşma', category: 'activities', difficulty: 'hard' },
  { word: 'beyin fırtınası', category: 'activities', difficulty: 'hard' },
  { word: 'problem çözme', category: 'activities', difficulty: 'hard' }
];
