module.exports = [
  { question: 'Never have I ever lied about my age.', category: 'general' },
  { question: 'Never have I ever pretended to be on a phone call to avoid someone.', category: 'funny' },
  { question: 'Never have I ever sung in the shower.', category: 'general' },
  { question: 'Never have I ever danced when nobody was watching.', category: 'general' },
  { question: 'Never have I ever cried during a movie.', category: 'general' },
  { question: 'Never have I ever sent a text to the wrong person.', category: 'funny' },
  { question: 'Never have I ever forgotten someone\'s name right after they introduced themselves.', category: 'funny' },
  { question: 'Never have I ever waved back at someone who wasn\'t waving at me.', category: 'funny' },
  { question: 'Never have I ever blamed the dog for something I did.', category: 'funny' },
  { question: 'Never have I ever googled my own name.', category: 'general' },
  { question: 'Never have I ever stayed up all night watching a TV series.', category: 'general' },
  { question: 'Never have I ever eaten food that fell on the floor.', category: 'food' },
  { question: 'Never have I ever tried to pass a sneeze as a cough.', category: 'funny' },
  { question: 'Never have I ever pretended to work while actually browsing the internet.', category: 'work' },
  { question: 'Never have I ever replayed a conversation in my head and cringed.', category: 'general' },
  { question: 'Never have I ever had a crush on a teacher.', category: 'childhood' },
  { question: 'Never have I ever been caught checking myself out in a mirror.', category: 'funny' },
  { question: 'Never have I ever laughed so hard I cried.', category: 'general' },
  { question: 'Never have I ever walked into a room and forgot why I went there.', category: 'funny' },
  { question: 'Never have I ever blamed technology for my own mistake.', category: 'funny' },
  { question: 'Never have I ever traveled to another country alone.', category: 'travel' },
  { question: 'Never have I ever missed a flight or train.', category: 'travel' },
  { question: 'Never have I ever gotten lost in a foreign city.', category: 'travel' },
  { question: 'Never have I ever tried a food I was scared to try.', category: 'food' },
  { question: 'Never have I ever eaten something past its expiry date.', category: 'food' },
  { question: 'Never have I ever ordered the same thing at a restaurant every time.', category: 'food' },
  { question: 'Never have I ever eaten dessert before dinner.', category: 'food' },
  { question: 'Never have I ever lied on my resume.', category: 'work' },
  { question: 'Never have I ever called in sick when I wasn\'t sick.', category: 'work' },
  { question: 'Never have I ever fallen asleep in a meeting or class.', category: 'work' },
  { question: 'Never have I ever had a work crush.', category: 'work' },
  { question: 'Never have I ever been late to an important event.', category: 'general' },
  { question: 'Never have I ever broken something at a friend\'s house and didn\'t tell them.', category: 'relationships' },
  { question: 'Never have I ever had a secret admirer.', category: 'relationships' },
  { question: 'Never have I ever been friend-zoned.', category: 'relationships' },
  { question: 'Never have I ever had a one-night stand.', category: 'risky' },
  { question: 'Never have I ever kissed a stranger.', category: 'risky' },
  { question: 'Never have I ever gotten a tattoo.', category: 'general' },
  { question: 'Never have I ever gotten a piercing somewhere other than my ears.', category: 'general' },
  { question: 'Never have I ever dyed my hair a crazy color.', category: 'general' },
  { question: 'Never have I ever been to a concert.', category: 'general' },
  { question: 'Never have I ever been to a music festival.', category: 'general' },
  { question: 'Never have I ever met a celebrity.', category: 'general' },
  { question: 'Never have I ever been on TV or in a video that went viral.', category: 'general' },
  { question: 'Never have I ever run a marathon or half-marathon.', category: 'general' },
  { question: 'Never have I ever gone skydiving or bungee jumping.', category: 'risky' },
  { question: 'Never have I ever been on a roller coaster.', category: 'general' },
  { question: 'Never have I ever swum in the ocean at night.', category: 'travel' },
  { question: 'Never have I ever camped in the wilderness.', category: 'travel' },
  { question: 'Never have I ever hitchhiked.', category: 'risky' },
  { question: 'Never have I ever slept in an airport.', category: 'travel' },
  { question: 'Never have I ever been to more than 10 countries.', category: 'travel' },
  { question: 'Never have I ever learned to speak another language fluently.', category: 'general' },
  { question: 'Never have I ever lived in another country.', category: 'travel' },
  { question: 'Never have I ever had a pen pal from another country.', category: 'childhood' },
  { question: 'Never have I ever been to a wedding.', category: 'relationships' },
  { question: 'Never have I ever been to a funeral.', category: 'general' },
  { question: 'Never have I ever been in a fight.', category: 'risky' },
  { question: 'Never have I ever been pulled over by the police.', category: 'risky' },
  { question: 'Never have I ever been to a casino.', category: 'risky' },
  { question: 'Never have I ever gambled with money I couldn\'t afford to lose.', category: 'risky' },
  { question: 'Never have I ever broken a bone.', category: 'general' },
  { question: 'Never have I ever had stitches.', category: 'general' },
  { question: 'Never have I ever fainted.', category: 'general' },
  { question: 'Never have I ever stayed in a hospital overnight.', category: 'general' },
  { question: 'Never have I ever been to the emergency room.', category: 'general' },
  { question: 'Never have I ever had a near-death experience.', category: 'risky' },
  { question: 'Never have I ever saved someone\'s life.', category: 'general' },
  { question: 'Never have I ever been in a car accident.', category: 'general' },
  { question: 'Never have I ever gotten a speeding ticket.', category: 'risky' },
  { question: 'Never have I ever ridden a motorcycle.', category: 'general' },
  { question: 'Never have I ever gone scuba diving.', category: 'travel' },
  { question: 'Never have I ever tried surfing.', category: 'general' },
  { question: 'Never have I ever gone skiing or snowboarding.', category: 'general' },
  { question: 'Never have I ever climbed a mountain.', category: 'travel' },
  { question: 'Never have I ever been on a cruise.', category: 'travel' },
  { question: 'Never have I ever been on a boat in the middle of the ocean.', category: 'travel' },
  { question: 'Never have I ever seen the northern lights.', category: 'travel' },
  { question: 'Never have I ever seen a wild animal up close.', category: 'travel' },
  { question: 'Never have I ever been bitten by an animal.', category: 'general' },
  { question: 'Never have I ever had a pet that wasn\'t a cat or dog.', category: 'general' },
  { question: 'Never have I ever stolen something.', category: 'risky' },
  { question: 'Never have I ever been arrested or detained.', category: 'risky' },
  { question: 'Never have I ever been to a strip club.', category: 'risky' },
  { question: 'Never have I ever skinny-dipped.', category: 'risky' },
  { question: 'Never have I ever been naked in public.', category: 'risky' },
  { question: 'Never have I ever had a wardrobe malfunction in public.', category: 'funny' },
  { question: 'Never have I ever walked in on someone in the bathroom.', category: 'funny' },
  { question: 'Never have I ever been walked in on in the bathroom.', category: 'funny' },
  { question: 'Never have I ever had a dream about someone in this room.', category: 'risky' },
  { question: 'Never have I ever had a crush on a friend\'s ex.', category: 'relationships' },
  { question: 'Never have I ever dated two people at once.', category: 'relationships' },
  { question: 'Never have I ever been on a blind date.', category: 'relationships' },
  { question: 'Never have I ever been catfished or fooled online.', category: 'relationships' },
  { question: 'Never have I ever slid into someone\'s DMs.', category: 'relationships' },
  { question: 'Never have I ever been in love at first sight.', category: 'relationships' },
  { question: 'Never have I ever had a long-distance relationship.', category: 'relationships' },
  { question: 'Never have I ever gotten back together with an ex.', category: 'relationships' },
  { question: 'Never have I ever been ghosted.', category: 'relationships' },
  { question: 'Never have I ever ghosted someone.', category: 'relationships' },
  { question: 'Never have I ever had a one-sided crush for more than a year.', category: 'relationships' },
  { question: 'Never have I ever written a love letter.', category: 'relationships' },
  { question: 'Never have I ever been serenaded or serenaded someone.', category: 'relationships' },
  { question: 'Never have I ever had a food fight.', category: 'childhood' },
  { question: 'Never have I ever been sent to the principal\'s office.', category: 'childhood' },
  { question: 'Never have I ever cheated on a test.', category: 'childhood' },
  { question: 'Never have I ever been suspended or expelled from school.', category: 'childhood' },
  { question: 'Never have I ever pulled an all-nighter for school.', category: 'childhood' },
  { question: 'Never have I ever had a fake ID.', category: 'risky' },
  { question: 'Never have I ever snuck out of the house as a teenager.', category: 'childhood' },
  { question: 'Never have I ever had a party when my parents were away.', category: 'childhood' },
  { question: 'Never have I ever broken a window or something valuable at home.', category: 'childhood' },
  { question: 'Never have I ever been grounded for more than a week.', category: 'childhood' },
  { question: 'Never have I ever lied to my parents about where I was.', category: 'childhood' },
  { question: 'Never have I ever had a diary or journal that someone read.', category: 'childhood' },
  { question: 'Never have I ever been in a school play or talent show.', category: 'childhood' },
  { question: 'Never have I ever been the last one picked for a team.', category: 'childhood' },
  { question: 'Never have I ever been bullied or bullied someone.', category: 'childhood' },
  { question: 'Never have I ever had a nickname I hated.', category: 'funny' },
  { question: 'Never have I ever been photobombed or photobombed someone.', category: 'funny' },
  { question: 'Never have I ever taken a selfie and deleted it immediately.', category: 'funny' },
  { question: 'Never have I ever posted something and deleted it within an hour.', category: 'funny' },
  { question: 'Never have I ever argued with a stranger on the internet.', category: 'funny' },
  { question: 'Never have I ever commented on an old post by accident.', category: 'funny' },
  { question: 'Never have I ever liked my own post or photo.', category: 'funny' },
  { question: 'Never have I ever accidentally liked someone\'s old photo.', category: 'funny' },
  { question: 'Never have I ever been blocked by someone on social media.', category: 'relationships' },
  { question: 'Never have I ever blocked someone I know in real life.', category: 'relationships' },
  { question: 'Never have I ever had more than 1000 followers on any platform.', category: 'general' },
  { question: 'Never have I ever gone viral for something embarrassing.', category: 'funny' },
  { question: 'Never have I ever tried to cook and failed badly.', category: 'food' },
  { question: 'Never have I ever set off a smoke alarm while cooking.', category: 'food' },
  { question: 'Never have I ever ordered pizza more than twice in one week.', category: 'food' },
  { question: 'Never have I ever eaten an entire pizza by myself.', category: 'food' },
  { question: 'Never have I ever eaten something raw that was supposed to be cooked.', category: 'food' },
  { question: 'Never have I ever tried a weird food combination.', category: 'food' },
  { question: 'Never have I ever been to an all-you-can-eat and made myself sick.', category: 'food' },
  { question: 'Never have I ever stolen food from a roommate or family member.', category: 'food' },
  { question: 'Never have I ever eaten breakfast for dinner.', category: 'food' },
  { question: 'Never have I ever had a caffeine addiction.', category: 'food' },
  { question: 'Never have I ever tried energy drinks to stay awake.', category: 'food' },
  { question: 'Never have I ever gone to a fast-food drive-through in pajamas.', category: 'funny' },
  { question: 'Never have I ever cried over spilt milk or dropped food.', category: 'funny' },
  { question: 'Never have I ever pretended to like a gift I received.', category: 'relationships' },
  { question: 'Never have I ever regifted something.', category: 'relationships' },
  { question: 'Never have I ever forgotten a close friend\'s or family member\'s birthday.', category: 'relationships' },
  { question: 'Never have I ever shown up to a party on the wrong day.', category: 'funny' },
  { question: 'Never have I ever been the only one who showed up in costume.', category: 'funny' },
  { question: 'Never have I ever fallen asleep at a party.', category: 'funny' },
  { question: 'Never have I ever been the designated driver and hated it.', category: 'general' },
  { question: 'Never have I ever lost my phone and panicked.', category: 'funny' },
  { question: 'Never have I ever left my phone at home and felt naked.', category: 'funny' },
  { question: 'Never have I ever had a phone fall in the toilet.', category: 'funny' },
  { question: 'Never have I ever cracked my phone screen.', category: 'general' },
  { question: 'Never have I ever used someone else\'s phone without asking.', category: 'relationships' },
  { question: 'Never have I ever looked through someone else\'s messages.', category: 'relationships' },
  { question: 'Never have I ever been caught looking at someone\'s phone.', category: 'funny' },
  { question: 'Never have I ever had a password that was "password" or "123456".', category: 'funny' },
  { question: 'Never have I ever forgotten an important password.', category: 'funny' },
  { question: 'Never have I ever replied "you too" when someone said "enjoy your movie" or similar.', category: 'funny' },
  { question: 'Never have I ever said "bye" twice in the same conversation.', category: 'funny' },
  { question: 'Never have I ever tripped in public.', category: 'funny' },
  { question: 'Never have I ever waved at a stranger thinking I knew them.', category: 'funny' },
  { question: 'Never have I ever tried to open a push door by pulling.', category: 'funny' },
  { question: 'Never have I ever walked into a glass door.', category: 'funny' },
  { question: 'Never have I ever missed a step and stumbled.', category: 'funny' },
  { question: 'Never have I ever had a zoom or video call and forgotten I was on camera.', category: 'work' },
  { question: 'Never have I ever been in a meeting and had no idea what was being discussed.', category: 'work' },
  { question: 'Never have I ever taken a nap during work hours.', category: 'work' },
  { question: 'Never have I ever had a job I hated.', category: 'work' },
  { question: 'Never have I ever quit a job without having another one lined up.', category: 'work' },
  { question: 'Never have I ever been fired from a job.', category: 'work' },
  { question: 'Never have I ever been promoted.', category: 'work' },
  { question: 'Never have I ever had a rivalry with a coworker.', category: 'work' },
  { question: 'Never have I ever dated a coworker.', category: 'work' },
  { question: 'Never have I ever had a celebrity crush.', category: 'general' },
  { question: 'Never have I ever written fan mail or DMed a celebrity.', category: 'general' },
  { question: 'Never have I ever cried over a celebrity breakup.', category: 'funny' },
  { question: 'Never have I ever been to a midnight movie premiere.', category: 'general' },
  { question: 'Never have I ever dressed up as a character for a movie release.', category: 'funny' },
  { question: 'Never have I ever rewatched the same movie more than 10 times.', category: 'general' },
  { question: 'Never have I ever fallen asleep in a movie theater.', category: 'funny' },
  { question: 'Never have I ever been to a concert and didn\'t know any songs.', category: 'funny' },
  { question: 'Never have I ever sung karaoke.', category: 'general' },
  { question: 'Never have I ever danced on a table.', category: 'risky' },
  { question: 'Never have I ever made a scene in public.', category: 'funny' },
  { question: 'Never have I ever been kicked out of a place.', category: 'risky' },
  { question: 'Never have I ever had a near-miss with the law.', category: 'risky' },
  { question: 'Never have I ever helped someone hide something from their parents.', category: 'relationships' },
  { question: 'Never have I ever kept a secret that was really hard to keep.', category: 'relationships' },
  { question: 'Never have I ever accidentally revealed a secret.', category: 'relationships' },
  { question: 'Never have I ever been betrayed by a friend.', category: 'relationships' },
  { question: 'Never have I ever betrayed a friend\'s trust.', category: 'relationships' },
  { question: 'Never have I ever had a falling out with a best friend.', category: 'relationships' },
  { question: 'Never have I ever reconnected with an old friend after years.', category: 'relationships' },
  { question: 'Never have I ever been to a high school or college reunion.', category: 'relationships' },
  { question: 'Never have I ever had a roommate I couldn\'t stand.', category: 'relationships' },
  { question: 'Never have I ever had a neighbor I couldn\'t stand.', category: 'relationships' },
  { question: 'Never have I ever complained about someone who was in the same room.', category: 'funny' },
  { question: 'Never have I ever been caught talking about someone.', category: 'funny' },
  { question: 'Never have I ever laughed at the wrong moment.', category: 'funny' },
  { question: 'Never have I ever farted in public and pretended it wasn\'t me.', category: 'funny' },
  { question: 'Never have I ever had a wardrobe malfunction.', category: 'funny' },
  { question: 'Never have I ever worn the same outfit two days in a row to work or school.', category: 'general' },
  { question: 'Never have I ever worn clothes inside out by accident.', category: 'funny' },
  { question: 'Never have I ever worn two different shoes.', category: 'funny' },
  { question: 'Never have I ever left the house without pants or with pajamas.', category: 'funny' },
  { question: 'Never have I ever had a bad haircut and cried.', category: 'funny' },
  { question: 'Never have I ever cut my own hair.', category: 'general' },
  { question: 'Never have I ever tried to give myself bangs.', category: 'funny' },
  { question: 'Never have I ever had a perm.', category: 'general' },
  { question: 'Never have I ever been sunburned so bad I couldn\'t sleep.', category: 'travel' },
  { question: 'Never have I ever gotten lost in a store as a kid.', category: 'childhood' },
  { question: 'Never have I ever been scared of the dark as an adult.', category: 'general' },
  { question: 'Never have I ever had a recurring nightmare.', category: 'general' },
  { question: 'Never have I ever slept walked or talked in my sleep.', category: 'general' },
  { question: 'Never have I ever had a dream that felt real and affected my day.', category: 'general' },
  { question: 'Never have I ever been woken up by a nightmare and called someone.', category: 'general' },
  { question: 'Never have I ever believed in ghosts or supernatural things.', category: 'general' },
  { question: 'Never have I ever thought I saw a ghost or something paranormal.', category: 'general' },
  { question: 'Never have I ever been to a haunted house or place.', category: 'general' },
  { question: 'Never have I ever been to a psychic or tarot reader.', category: 'general' },
  { question: 'Never have I ever tried to learn a magic trick.', category: 'general' },
  { question: 'Never have I ever tried to do a backflip or cartwheel and failed.', category: 'funny' },
  { question: 'Never have I ever tried to learn a TikTok or viral dance.', category: 'funny' },
  { question: 'Never have I ever posted a TikTok or Reel.', category: 'general' },
  { question: 'Never have I ever gone viral on social media.', category: 'general' },
  { question: 'Never have I ever had a photo of me go viral without my consent.', category: 'general' },
  { question: 'Never have I ever been recognized in public by a stranger.', category: 'general' },
  { question: 'Never have I ever been to a theme park alone.', category: 'travel' },
  { question: 'Never have I ever ridden the same ride 5 times in a row.', category: 'general' },
  { question: 'Never have I ever thrown up on a ride.', category: 'funny' },
  { question: 'Never have I ever been scared on a ride and had to get off.', category: 'general' },
  { question: 'Never have I ever tried an extreme sport.', category: 'risky' },
  { question: 'Never have I ever volunteered for something and regretted it.', category: 'general' },
  { question: 'Never have I ever donated blood.', category: 'general' },
  { question: 'Never have I ever fainted at the sight of blood.', category: 'general' },
  { question: 'Never have I ever had a fear of needles.', category: 'general' },
  { question: 'Never have I ever been scared of flying.', category: 'travel' },
  { question: 'Never have I ever had a panic attack.', category: 'general' },
  { question: 'Never have I ever tried meditation or yoga.', category: 'general' },
  { question: 'Never have I ever been to therapy or counseling.', category: 'general' },
  { question: 'Never have I ever given someone the silent treatment for more than a day.', category: 'relationships' },
  { question: 'Never have I ever held a grudge for years.', category: 'relationships' },
  { question: 'Never have I ever apologized when I wasn\'t wrong.', category: 'relationships' },
  { question: 'Never have I ever refused to apologize when I was wrong.', category: 'relationships' },
  { question: 'Never have I ever had a public argument with someone.', category: 'relationships' },
  { question: 'Never have I ever made up with someone after a big fight.', category: 'relationships' },
  { question: 'Never have I ever been to a wedding and didn\'t know the couple well.', category: 'relationships' },
  { question: 'Never have I ever been a bridesmaid or groomsman.', category: 'relationships' },
  { question: 'Never have I ever caught the bouquet or garter.', category: 'relationships' },
  { question: 'Never have I ever given a speech at a wedding.', category: 'relationships' },
  { question: 'Never have I ever cried at a wedding.', category: 'relationships' },
  { question: 'Never have I ever been to a baby shower.', category: 'relationships' },
  { question: 'Never have I ever held a newborn baby.', category: 'general' },
  { question: 'Never have I ever changed a diaper.', category: 'general' },
  { question: 'Never have I ever baby-sat.', category: 'general' },
  { question: 'Never have I ever wanted to have kids.', category: 'general' },
  { question: 'Never have I ever not wanted to have kids.', category: 'general' },
  { question: 'Never have I ever had a pet die and cried.', category: 'general' },
  { question: 'Never have I ever buried a pet.', category: 'general' },
  { question: 'Never have I ever gone to a funeral and laughed at the wrong time.', category: 'funny' },
  { question: 'Never have I ever spoken at a funeral.', category: 'general' },
  { question: 'Never have I ever visited a grave of someone I knew.', category: 'general' },
  { question: 'Never have I ever had a near-death experience and thought about my life.', category: 'risky' },
  { question: 'Never have I ever made a bucket list.', category: 'general' },
  { question: 'Never have I ever crossed something off my bucket list.', category: 'general' },
  { question: 'Never have I ever tried to learn a new language and gave up.', category: 'general' },
  { question: 'Never have I ever learned to play an instrument.', category: 'general' },
  { question: 'Never have I ever tried to learn an instrument and quit.', category: 'general' },
  { question: 'Never have I ever written a song or poem.', category: 'general' },
  { question: 'Never have I ever painted or drawn something I was proud of.', category: 'general' },
  { question: 'Never have I ever tried to cook a fancy meal and failed.', category: 'food' },
  { question: 'Never have I ever baked something from scratch.', category: 'food' },
  { question: 'Never have I ever burned something I was cooking.', category: 'food' },
  { question: 'Never have I ever tried a diet and quit after a week.', category: 'food' },
  { question: 'Never have I ever been vegetarian or vegan.', category: 'food' },
  { question: 'Never have I ever tried a food trend like kale or avocado toast.', category: 'food' },
  { question: 'Never have I ever eaten something I grew myself.', category: 'food' },
  { question: 'Never have I ever been to a farmers market.', category: 'food' },
  { question: 'Never have I ever been to a fancy restaurant and felt underdressed.', category: 'food' },
  { question: 'Never have I ever sent food back at a restaurant.', category: 'food' },
  { question: 'Never have I ever left without tipping.', category: 'food' },
  { question: 'Never have I ever had an argument over the bill.', category: 'relationships' },
  { question: 'Never have I ever been on a diet with a friend.', category: 'relationships' },
  { question: 'Never have I ever competed with a friend over something silly.', category: 'relationships' },
  { question: 'Never have I ever had a secret handshake with someone.', category: 'childhood' },
  { question: 'Never have I ever had an imaginary friend.', category: 'childhood' },
  { question: 'Never have I ever believed in Santa after age 10.', category: 'childhood' },
  { question: 'Never have I ever put a tooth under my pillow for the tooth fairy.', category: 'childhood' },
  { question: 'Never have I ever been scared of clowns.', category: 'general' },
  { question: 'Never have I ever been to a circus.', category: 'general' },
  { question: 'Never have I ever been to a zoo and felt bad for the animals.', category: 'general' },
  { question: 'Never have I ever ridden a horse.', category: 'general' },
  { question: 'Never have I ever been bitten by an insect and had a bad reaction.', category: 'general' },
  { question: 'Never have I ever had a fear of spiders or insects.', category: 'general' },
  { question: 'Never have I ever killed a spider for someone else.', category: 'general' },
  { question: 'Never have I ever rescued an animal.', category: 'general' },
  { question: 'Never have I ever adopted a pet from a shelter.', category: 'general' },
  { question: 'Never have I ever lost a pet.', category: 'general' },
  { question: 'Never have I ever had a pet run away.', category: 'general' },
  { question: 'Never have I ever lied about being busy to get out of plans.', category: 'general' },
  { question: 'Never have I ever pretended to like a song when someone played it.', category: 'funny' },
  { question: 'Never have I ever said "I\'m on my way" when I hadn\'t left yet.', category: 'funny' },
  { question: 'Never have I ever read someone else\'s diary or journal.', category: 'relationships' },
  { question: 'Never have I ever had a nickname I gave myself.', category: 'funny' },
  { question: 'Never have I ever been the third wheel on a date.', category: 'relationships' },
  { question: 'Never have I ever accidentally liked an ex\'s post.', category: 'funny' },
  { question: 'Never have I ever stayed in a relationship longer than I should have.', category: 'relationships' },
  { question: 'Never have I ever had a dream about someone and felt weird around them the next day.', category: 'general' },
  { question: 'Never have I ever rewatched a show more than five times.', category: 'general' },
  { question: 'Never have I ever cried at an advertisement.', category: 'funny' },
  { question: 'Never have I ever talked to myself in the mirror.', category: 'funny' },
  { question: 'Never have I ever practiced a conversation before it happened.', category: 'general' },
  { question: 'Never have I ever been scared to check my bank balance.', category: 'general' },
  { question: 'Never have I ever bought something I couldn\'t afford.', category: 'general' },
  { question: 'Never have I ever returned a gift.', category: 'relationships' },
  { question: 'Never have I ever forgotten a close friend\'s birthday.', category: 'relationships' },
  { question: 'Never have I ever shown up late to my own event.', category: 'funny' },
  { question: 'Never have I ever mixed up two people\'s names in the same sentence.', category: 'funny' },
  { question: 'Never have I ever said "see you tomorrow" to someone I knew I wouldn\'t see.', category: 'funny' },
  { question: 'Never have I ever pretended to understand a joke and laughed anyway.', category: 'funny' },
  { question: 'Never have I ever nodded along in a conversation I didn\'t follow.', category: 'funny' },
  { question: 'Never have I ever been caught singing in the car at a red light.', category: 'funny' },
  { question: 'Never have I ever had a crush on a fictional character.', category: 'general' },
  { question: 'Never have I ever written a letter I never sent.', category: 'general' },
  { question: 'Never have I ever tried to fix something and made it worse.', category: 'funny' },
  { question: 'Never have I ever blamed someone else for something I did.', category: 'relationships' },
  { question: 'Never have I ever taken credit for someone else\'s idea.', category: 'work' },
  { question: 'Never have I ever been caught in a white lie.', category: 'funny' },
  { question: 'Never have I ever exaggerated a story to make it more interesting.', category: 'general' },
  { question: 'Never have I ever been jealous of a friend\'s success.', category: 'relationships' },
  { question: 'Never have I ever compared myself to someone on social media and felt bad.', category: 'general' },
  { question: 'Never have I ever deleted a photo because of how I looked.', category: 'general' },
  { question: 'Never have I ever been nervous before a job interview.', category: 'work' },
  { question: 'Never have I ever messed up my first day at a new job.', category: 'work' },
  { question: 'Never have I ever fallen asleep during a movie at the cinema.', category: 'funny' },
  { question: 'Never have I ever gotten food poisoning from something I ate.', category: 'food' },
  { question: 'Never have I ever tried to impress someone with a skill I don\'t have.', category: 'general' },
  { question: 'Never have I ever been caught doing something embarrassing on camera.', category: 'funny' },
  { question: 'Never have I ever had a phase I\'m embarrassed about now.', category: 'general' },
  { question: 'Never have I ever worn something that was clearly too small or too big.', category: 'funny' },
  { question: 'Never have I ever had a bad reaction to a haircut and lied that I liked it.', category: 'funny' },
  { question: 'Never have I ever tried to take a good selfie for more than 10 minutes.', category: 'funny' },
  { question: 'Never have I ever been the one who ruined a group photo.', category: 'funny' },
  { question: 'Never have I ever forgotten what I was saying mid-sentence.', category: 'funny' },
  { question: 'Never have I ever called a teacher "mom" or "dad" by mistake.', category: 'childhood' },
  { question: 'Never have I ever walked in the wrong direction confidently.', category: 'funny' },
  { question: 'Never have I ever tried to open a door that said "pull" by pushing.', category: 'funny' },
  { question: 'Never have I ever said "thank you" when someone said "sorry".', category: 'funny' },
  { question: 'Never have I ever waved at a baby and then realized it was a doll.', category: 'funny' },
  { question: 'Never have I ever been scared of the dark as an adult.', category: 'general' },
  { question: 'Never have I ever slept with a stuffed animal as an adult.', category: 'general' },
  { question: 'Never have I ever had a lucky charm or superstition.', category: 'general' },
  { question: 'Never have I ever made a wish on a shooting star.', category: 'general' },
  { question: 'Never have I ever broken a mirror and worried about bad luck.', category: 'general' },
  { question: 'Never have I ever walked under a ladder.', category: 'general' },
  { question: 'Never have I ever been to a fortune teller.', category: 'general' },
  { question: 'Never have I ever tried to lucid dream.', category: 'general' },
  { question: 'Never have I ever had sleep paralysis.', category: 'general' },
  { question: 'Never have I ever woken up and not known where I was for a moment.', category: 'general' },
  { question: 'Never have I ever slept through an alarm and missed something important.', category: 'funny' },
  { question: 'Never have I ever hit snooze more than three times in a row.', category: 'funny' },
  { question: 'Never have I ever had a conversation in my sleep that someone heard.', category: 'funny' },
  { question: 'Never have I ever been woken up by my own snoring.', category: 'funny' },
  { question: 'Never have I ever fallen asleep in a library.', category: 'general' },
  { question: 'Never have I ever pulled an all-nighter for something that wasn\'t work or school.', category: 'general' },
  { question: 'Never have I ever had a nap that turned into sleeping the whole night.', category: 'funny' },
  { question: 'Never have I ever been to a karaoke bar and not sung.', category: 'general' },
  { question: 'Never have I ever sung karaoke and forgotten the words.', category: 'funny' },
  { question: 'Never have I ever been to a comedy show and been picked on by the comedian.', category: 'funny' },
  { question: 'Never have I ever been to a theme park and gotten sick on a ride.', category: 'travel' },
  { question: 'Never have I ever lost my luggage while traveling.', category: 'travel' },
  { question: 'Never have I ever had a flight delayed by more than 5 hours.', category: 'travel' },
  { question: 'Never have I ever sat next to someone annoying on a long flight.', category: 'travel' },
  { question: 'Never have I ever been to a country where I didn\'t speak the language.', category: 'travel' },
  { question: 'Never have I ever gotten a souvenir that broke before I got home.', category: 'travel' },
  { question: 'Never have I ever taken a photo with a stranger while traveling.', category: 'travel' },
  { question: 'Never have I ever gotten a tattoo I later regretted.', category: 'general' },
  { question: 'Never have I ever had a piercing that got infected.', category: 'general' },
  { question: 'Never have I ever tried to dye my hair at home and it went wrong.', category: 'funny' },
  { question: 'Never have I ever had a fashion phase I\'m glad is over.', category: 'general' },
  { question: 'Never have I ever worn something from the opposite gender\'s section.', category: 'general' },
  { question: 'Never have I ever bought the same outfit in multiple colors.', category: 'general' },
  { question: 'Never have I ever lost my keys and had to break into my own place.', category: 'funny' },
  { question: 'Never have I ever locked myself out of my house or car.', category: 'funny' },
  { question: 'Never have I ever forgotten where I parked my car.', category: 'funny' },
  { question: 'Never have I ever run out of gas on the road.', category: 'general' },
  { question: 'Never have I ever gotten a flat tire.', category: 'general' },
  { question: 'Never have I ever been in a car that broke down in the middle of nowhere.', category: 'travel' },
  { question: 'Never have I ever helped a stranger with their car.', category: 'general' },
  { question: 'Never have I ever given money to a stranger on the street.', category: 'general' },
  { question: 'Never have I ever volunteered for a cause I care about.', category: 'general' },
  { question: 'Never have I ever donated to a charity.', category: 'general' },
  { question: 'Never have I ever run a 5K or longer race.', category: 'general' },
  { question: 'Never have I ever joined a gym and stopped going after a month.', category: 'general' },
  { question: 'Never have I ever tried a sport and quit because I wasn\'t good at it.', category: 'general' },
  { question: 'Never have I ever been to a sports game live.', category: 'general' },
  { question: 'Never have I ever cried over a sports game.', category: 'general' },
  { question: 'Never have I ever painted my face for a game or event.', category: 'general' },
  { question: 'Never have I ever been to a protest or rally.', category: 'general' },
  { question: 'Never have I ever written a review online.', category: 'general' },
  { question: 'Never have I ever argued with a stranger in the comments section.', category: 'funny' },
  { question: 'Never have I ever deleted a comment I posted because of the backlash.', category: 'funny' },
  { question: 'Never have I ever been blocked by someone I know.', category: 'relationships' },
  { question: 'Never have I ever had a secret that was too big to keep.', category: 'relationships' },
  { question: 'Never have I ever told a friend\'s secret to someone else.', category: 'relationships' },
  { question: 'Never have I ever been caught in a lie by someone I cared about.', category: 'relationships' },
  { question: 'Never have I ever apologized years later for something I did.', category: 'relationships' },
  { question: 'Never have I ever reconnected with an ex just to see how they were doing.', category: 'relationships' },
  { question: 'Never have I ever had a crush on my best friend.', category: 'relationships' },
  { question: 'Never have I ever been set up on a blind date that went badly.', category: 'relationships' },
  { question: 'Never have I ever been the one to end a friendship.', category: 'relationships' },
  { question: 'Never have I ever made a friend while waiting in line.', category: 'general' },
  { question: 'Never have I ever had a neighbor I became friends with.', category: 'relationships' },
  { question: 'Never have I ever been to a reunion and regretted it.', category: 'relationships' },
  { question: 'Never have I ever forgotten a friend\'s name when introducing them.', category: 'funny' },
  { question: 'Never have I ever mixed up two friends\' names.', category: 'funny' },
  { question: 'Never have I ever had a group chat that went silent after one message.', category: 'funny' },
  { question: 'Never have I ever left a message on "read" for more than a day.', category: 'relationships' },
  { question: 'Never have I ever pretended to have a bad connection to end a call.', category: 'funny' },
  { question: 'Never have I ever said "I have to go" when I didn\'t.', category: 'funny' },
  { question: 'Never have I ever been to a party where I didn\'t know anyone.', category: 'general' },
  { question: 'Never have I ever been the last one to leave a party.', category: 'general' },
  { question: 'Never have I ever thrown a party that got out of hand.', category: 'general' },
  { question: 'Never have I ever cleaned up after someone else\'s party.', category: 'general' },
  { question: 'Never have I ever had a roommate I didn\'t get along with.', category: 'relationships' },
  { question: 'Never have I ever had a surprise party thrown for me.', category: 'general' },
  { question: 'Never have I ever ruined a surprise.', category: 'funny' },
  { question: 'Never have I ever forgotten an anniversary.', category: 'relationships' },
  { question: 'Never have I ever made a scene at a family gathering.', category: 'relationships' },
  { question: 'Never have I ever had a family member I avoid at holidays.', category: 'relationships' },
  { question: 'Never have I ever lied to my family about where I was going.', category: 'childhood' },
  { question: 'Never have I ever snuck someone into my house.', category: 'childhood' },
  { question: 'Never have I ever been caught doing something I wasn\'t supposed to.', category: 'general' },
];
