module.exports = [
  { question: 'Nunca he mentido sobre mi edad.', category: 'general' },
  { question: 'Nunca he fingido estar en una llamada para evitar a alguien.', category: 'funny' },
  { question: 'Nunca he cantado en la ducha.', category: 'general' },
  { question: 'Nunca he bailado cuando nadie me miraba.', category: 'general' },
  { question: 'Nunca he llorado durante una película.', category: 'general' },
  { question: 'Nunca he enviado un mensaje a la persona equivocada.', category: 'funny' },
  { question: 'Nunca he olvidado el nombre de alguien justo después de que se presentara.', category: 'funny' },
  { question: 'Nunca he devuelto el saludo a alguien que no me estaba saludando.', category: 'funny' },
  { question: 'Nunca he culpado al perro de algo que hice yo.', category: 'funny' },
  { question: 'Nunca he buscado mi propio nombre en Google.', category: 'general' },
  { question: 'Nunca he pasado toda la noche viendo una serie.', category: 'general' },
  { question: 'Nunca he comido comida que se cayó al suelo.', category: 'food' },
  { question: 'Nunca he intentado hacer pasar un estornudo por tos.', category: 'funny' },
  { question: 'Nunca he fingido trabajar mientras navegaba por internet.', category: 'work' },
  { question: 'Nunca he repasado una conversación mentalmente y me he avergonzado.', category: 'general' },
  { question: 'Nunca he tenido un crush por un profesor.', category: 'childhood' },
  { question: 'Nunca me han pillado mirándome en el espejo.', category: 'funny' },
  { question: 'Nunca me he reído tanto que he llorado.', category: 'general' },
  { question: 'Nunca he entrado en una habitación y olvidado para qué fui.', category: 'funny' },
  { question: 'Nunca he culpado a la tecnología de mi propio error.', category: 'funny' },
  { question: 'Nunca he viajado solo a otro país.', category: 'travel' },
  { question: 'Nunca he perdido un vuelo o un tren.', category: 'travel' },
  { question: 'Nunca me he perdido en una ciudad extranjera.', category: 'travel' },
  { question: 'Nunca he probado una comida que me daba miedo probar.', category: 'food' },
  { question: 'Nunca he comido algo pasada su fecha de caducidad.', category: 'food' },
  { question: 'Nunca he pedido lo mismo en un restaurante cada vez.', category: 'food' },
  { question: 'Nunca he comido postre antes de la cena.', category: 'food' },
  { question: 'Nunca he mentido en mi currículum.', category: 'work' },
  { question: 'Nunca he llamado enfermo cuando no lo estaba.', category: 'work' },
  { question: 'Nunca me he quedado dormido en una reunión o clase.', category: 'work' },
  { question: 'Nunca he tenido un crush en el trabajo.', category: 'work' },
  { question: 'Nunca he llegado tarde a un evento importante.', category: 'general' },
  { question: 'Nunca he roto algo en casa de un amigo y no se lo he dicho.', category: 'relationships' },
  { question: 'Nunca he tenido un admirador secreto.', category: 'relationships' },
  { question: 'Nunca he estado en la friendzone.', category: 'relationships' },
  { question: 'Nunca he tenido una noche de una sola vez.', category: 'risky' },
  { question: 'Nunca he besado a un desconocido.', category: 'risky' },
  { question: 'Nunca me he hecho un tatuaje.', category: 'general' },
  { question: 'Nunca me he hecho un piercing en otro sitio que no sean las orejas.', category: 'general' },
  { question: 'Nunca me he teñido el pelo de un color loco.', category: 'general' },
  { question: 'Nunca he ido a un concierto.', category: 'general' },
  { question: 'Nunca he ido a un festival de música.', category: 'general' },
  { question: 'Nunca he conocido a un famoso.', category: 'general' },
  { question: 'Nunca he salido en la tele o en un video viral.', category: 'general' },
  { question: 'Nunca he corrido un maratón o medio maratón.', category: 'general' },
  { question: 'Nunca he hecho paracaidismo o puenting.', category: 'risky' },
  { question: 'Nunca he montado en una montaña rusa.', category: 'general' },
  { question: 'Nunca he nadado en el mar de noche.', category: 'travel' },
  { question: 'Nunca he acampado en la naturaleza.', category: 'travel' },
  { question: 'Nunca he hecho autostop.', category: 'risky' },
  { question: 'Nunca he dormido en un aeropuerto.', category: 'travel' },
  { question: 'Nunca he estado en más de 10 países.', category: 'travel' },
  { question: 'Nunca he aprendido a hablar otro idioma con fluidez.', category: 'general' },
  { question: 'Nunca he vivido en otro país.', category: 'travel' },
  { question: 'Nunca he tenido un amigo por correspondencia de otro país.', category: 'childhood' },
  { question: 'Nunca he ido a una boda.', category: 'relationships' },
  { question: 'Nunca he ido a un funeral.', category: 'general' },
  { question: 'Nunca he estado en una pelea.', category: 'risky' },
  { question: 'Nunca me ha parado la policía.', category: 'risky' },
  { question: 'Nunca he ido a un casino.', category: 'risky' },
  { question: 'Nunca he apostado dinero que no me podía permitir perder.', category: 'risky' },
  { question: 'Nunca me he roto un hueso.', category: 'general' },
  { question: 'Nunca me han dado puntos.', category: 'general' },
  { question: 'Nunca me he desmayado.', category: 'general' },
  { question: 'Nunca he pasado una noche en el hospital.', category: 'general' },
  { question: 'Nunca he ido a urgencias.', category: 'general' },
  { question: 'Nunca he tenido una experiencia cercana a la muerte.', category: 'risky' },
  { question: 'Nunca he salvado la vida de alguien.', category: 'general' },
  { question: 'Nunca he tenido un accidente de coche.', category: 'general' },
  { question: 'Nunca me han multado por exceso de velocidad.', category: 'risky' },
  { question: 'Nunca he montado en moto.', category: 'general' },
  { question: 'Nunca he hecho buceo.', category: 'travel' },
  { question: 'Nunca he probado el surf.', category: 'general' },
  { question: 'Nunca he esquiado o hecho snowboard.', category: 'general' },
  { question: 'Nunca he escalado una montaña.', category: 'travel' },
  { question: 'Nunca he ido en crucero.', category: 'travel' },
  { question: 'Nunca he estado en un barco en medio del océano.', category: 'travel' },
  { question: 'Nunca he visto la aurora boreal.', category: 'travel' },
  { question: 'Nunca he visto un animal salvaje de cerca.', category: 'travel' },
  { question: 'Nunca me ha mordido un animal.', category: 'general' },
  { question: 'Nunca he tenido una mascota que no fuera gato o perro.', category: 'general' },
  { question: 'Nunca he robado nada.', category: 'risky' },
  { question: 'Nunca me han arrestado o detenido.', category: 'risky' },
  { question: 'Nunca he ido a un club de striptease.', category: 'risky' },
  { question: 'Nunca he nadado desnudo.', category: 'risky' },
  { question: 'Nunca he estado desnudo en público.', category: 'risky' },
  { question: 'Nunca he tenido un fallo de vestuario en público.', category: 'funny' },
  { question: 'Nunca he pillado a alguien en el baño.', category: 'funny' },
  { question: 'Nunca me han pillado a mí en el baño.', category: 'funny' },
  { question: 'Nunca he soñado con alguien de esta habitación.', category: 'risky' },
  { question: 'Nunca he tenido un crush por el ex de un amigo.', category: 'relationships' },
  { question: 'Nunca he salido con dos personas a la vez.', category: 'relationships' },
  { question: 'Nunca he tenido una cita a ciegas.', category: 'relationships' },
  { question: 'Nunca me han engañado o timado por internet.', category: 'relationships' },
  { question: 'Nunca he escrito a alguien por DM.', category: 'relationships' },
  { question: 'Nunca he tenido amor a primera vista.', category: 'relationships' },
  { question: 'Nunca he tenido una relación a distancia.', category: 'relationships' },
  { question: 'Nunca he vuelto con un ex.', category: 'relationships' },
  { question: 'Nunca me han ghosteado.', category: 'relationships' },
  { question: 'Nunca he ghosteado a alguien.', category: 'relationships' },
  { question: 'Nunca he tenido un crush no correspondido durante más de un año.', category: 'relationships' },
  { question: 'Nunca he escrito una carta de amor.', category: 'relationships' },
  { question: 'Nunca me han cantado una serenata ni he cantado una a alguien.', category: 'relationships' },
  { question: 'Nunca he tenido una guerra de comida.', category: 'childhood' },
  { question: 'Nunca me han mandado al despacho del director.', category: 'childhood' },
  { question: 'Nunca he copiado en un examen.', category: 'childhood' },
  { question: 'Nunca me han suspendido o expulsado del colegio.', category: 'childhood' },
  { question: 'Nunca he pasado la noche en vela por el colegio.', category: 'childhood' },
  { question: 'Nunca he tenido un DNI falso.', category: 'risky' },
  { question: 'Nunca me he escapado de casa siendo adolescente.', category: 'childhood' },
  { question: 'Nunca he organizado una fiesta cuando mis padres no estaban.', category: 'childhood' },
  { question: 'Nunca he roto una ventana o algo valioso en casa.', category: 'childhood' },
  { question: 'Nunca he estado castigado más de una semana.', category: 'childhood' },
  { question: 'Nunca he mentido a mis padres sobre dónde estaba.', category: 'childhood' },
  { question: 'Nunca he tenido un diario que alguien leyera.', category: 'childhood' },
  { question: 'Nunca he participado en una obra de teatro o concurso de talentos del colegio.', category: 'childhood' },
  { question: 'Nunca he sido el último elegido para un equipo.', category: 'childhood' },
  { question: 'Nunca me han acosado ni he acosado a nadie.', category: 'childhood' },
  { question: 'Nunca he tenido un apodo que odiara.', category: 'funny' },
  { question: 'Nunca me han photobombeado ni he photobombeado a nadie.', category: 'funny' },
  { question: 'Nunca he hecho un selfie y lo he borrado al instante.', category: 'funny' },
  { question: 'Nunca he subido algo y lo he borrado en menos de una hora.', category: 'funny' },
  { question: 'Nunca he discutido con un desconocido en internet.', category: 'funny' },
  { question: 'Nunca he comentado por error en una publicación antigua.', category: 'funny' },
  { question: 'Nunca he dado like a mi propia publicación o foto.', category: 'funny' },
  { question: 'Nunca he dado like por error a una foto antigua de alguien.', category: 'funny' },
  { question: 'Nunca me han bloqueado en redes sociales.', category: 'relationships' },
  { question: 'Nunca he bloqueado a alguien que conozco en la vida real.', category: 'relationships' },
  { question: 'Nunca he tenido más de 1000 seguidores en ninguna plataforma.', category: 'general' },
  { question: 'Nunca he sido viral por algo vergonzoso.', category: 'funny' },
  { question: 'Nunca he intentado cocinar y he fracasado.', category: 'food' },
  { question: 'Nunca he activado la alarma de humos cocinando.', category: 'food' },
  { question: 'Nunca he pedido pizza más de dos veces en una semana.', category: 'food' },
  { question: 'Nunca me he comido una pizza entera yo solo.', category: 'food' },
  { question: 'Nunca he comido algo crudo que debía estar cocinado.', category: 'food' },
  { question: 'Nunca he probado una combinación rara de comida.', category: 'food' },
  { question: 'Nunca he ido a un buffet y me he puesto malo.', category: 'food' },
  { question: 'Nunca he robado comida a un compañero de piso o familiar.', category: 'food' },
  { question: 'Nunca he cenado desayuno.', category: 'food' },
  { question: 'Nunca he tenido adicción a la cafeína.', category: 'food' },
  { question: 'Nunca he tomado bebidas energéticas para mantenerme despierto.', category: 'food' },
  { question: 'Nunca he ido al drive-through de comida rápida en pijama.', category: 'funny' },
  { question: 'Nunca he llorado por leche derramada o comida tirada.', category: 'funny' },
  { question: 'Nunca he fingido que me gustaba un regalo que recibí.', category: 'relationships' },
  { question: 'Nunca he reenvuelto un regalo para otra persona.', category: 'relationships' },
  { question: 'Nunca he olvidado el cumpleaños de un amigo cercano o familiar.', category: 'relationships' },
  { question: 'Nunca he llegado a una fiesta el día equivocado.', category: 'funny' },
  { question: 'Nunca he sido el único que fue disfrazado.', category: 'funny' },
  { question: 'Nunca me he quedado dormido en una fiesta.', category: 'funny' },
  { question: 'Nunca he sido el conductor designado y lo he odiado.', category: 'general' },
  { question: 'Nunca he perdido el móvil y entrado en pánico.', category: 'funny' },
  { question: 'Nunca he dejado el móvil en casa y me he sentido desnudo.', category: 'funny' },
  { question: 'Nunca se me ha caído el móvil al váter.', category: 'funny' },
  { question: 'Nunca he roto la pantalla del móvil.', category: 'general' },
  { question: 'Nunca he usado el móvil de otro sin preguntar.', category: 'relationships' },
  { question: 'Nunca he mirado los mensajes de otro.', category: 'relationships' },
  { question: 'Nunca me han pillado mirando el móvil de alguien.', category: 'funny' },
  { question: 'Nunca he tenido una contraseña que fuera "password" o "123456".', category: 'funny' },
  { question: 'Nunca he olvidado una contraseña importante.', category: 'funny' },
  { question: 'Nunca he respondido "a ti también" cuando alguien dijo "que disfrutes la película" o similar.', category: 'funny' },
  { question: 'Nunca he dicho "adiós" dos veces en la misma conversación.', category: 'funny' },
  { question: 'Nunca he tropezado en público.', category: 'funny' },
  { question: 'Nunca he saludado a un desconocido pensando que lo conocía.', category: 'funny' },
  { question: 'Nunca he intentado abrir una puerta de empujar tirando.', category: 'funny' },
  { question: 'Nunca me he dado contra una puerta de cristal.', category: 'funny' },
  { question: 'Nunca he perdido un escalón y tropezado.', category: 'funny' },
  { question: 'Nunca he tenido una videollamada y olvidado que la cámara estaba encendida.', category: 'work' },
  { question: 'Nunca he estado en una reunión sin tener ni idea de qué se hablaba.', category: 'work' },
  { question: 'Nunca he echado una siesta en horario laboral.', category: 'work' },
  { question: 'Nunca he tenido un trabajo que odiara.', category: 'work' },
  { question: 'Nunca he dejado un trabajo sin tener otro.', category: 'work' },
  { question: 'Nunca me han despedido.', category: 'work' },
  { question: 'Nunca me han ascendido.', category: 'work' },
  { question: 'Nunca he tenido rivalidad con un compañero.', category: 'work' },
  { question: 'Nunca he salido con un compañero de trabajo.', category: 'work' },
  { question: 'Nunca he tenido un crush por un famoso.', category: 'general' },
  { question: 'Nunca he escrito fan mail o mandado DM a un famoso.', category: 'general' },
  { question: 'Nunca he llorado por una ruptura de famosos.', category: 'funny' },
  { question: 'Nunca he ido a un estreno de medianoche.', category: 'general' },
  { question: 'Nunca me he disfrazado de personaje para el estreno de una película.', category: 'funny' },
  { question: 'Nunca he visto la misma película más de 10 veces.', category: 'general' },
  { question: 'Nunca me he quedado dormido en el cine.', category: 'funny' },
  { question: 'Nunca he ido a un concierto sin conocer ninguna canción.', category: 'funny' },
  { question: 'Nunca he cantado karaoke.', category: 'general' },
  { question: 'Nunca he bailado encima de una mesa.', category: 'risky' },
  { question: 'Nunca he montado un escándalo en público.', category: 'funny' },
  { question: 'Nunca me han echado de un sitio.', category: 'risky' },
  { question: 'Nunca he estado a punto de tener problemas con la ley.', category: 'risky' },
  { question: 'Nunca he ayudado a alguien a esconder algo a sus padres.', category: 'relationships' },
  { question: 'Nunca he guardado un secreto que costaba mucho guardar.', category: 'relationships' },
  { question: 'Nunca he revelado un secreto por error.', category: 'relationships' },
  { question: 'Nunca me ha traicionado un amigo.', category: 'relationships' },
  { question: 'Nunca he traicionado la confianza de un amigo.', category: 'relationships' },
  { question: 'Nunca me he peleado con mi mejor amigo.', category: 'relationships' },
  { question: 'Nunca me he reencontrado con un amigo de hace años.', category: 'relationships' },
  { question: 'Nunca he ido a una reunión de antiguos alumnos.', category: 'relationships' },
  { question: 'Nunca he tenido un compañero de piso que no aguantara.', category: 'relationships' },
  { question: 'Nunca he tenido un vecino que no aguantara.', category: 'relationships' },
  { question: 'Nunca me he quejado de alguien que estaba en la misma habitación.', category: 'funny' },
  { question: 'Nunca me han pillado hablando de alguien.', category: 'funny' },
  { question: 'Nunca me he reído en el momento equivocado.', category: 'funny' },
  { question: 'Nunca he tirado un pedo en público y fingido que no era yo.', category: 'funny' },
  { question: 'Nunca he tenido un fallo de vestuario.', category: 'funny' },
  { question: 'Nunca he llevado el mismo outfit dos días seguidos al trabajo o al colegio.', category: 'general' },
  { question: 'Nunca he llevado la ropa del revés por error.', category: 'funny' },
  { question: 'Nunca he llevado dos zapatos distintos.', category: 'funny' },
  { question: 'Nunca he salido de casa sin pantalones o en pijama.', category: 'funny' },
  { question: 'Nunca he tenido un mal corte de pelo y llorado.', category: 'funny' },
  { question: 'Nunca me he cortado el pelo yo mismo.', category: 'general' },
  { question: 'Nunca he intentado cortarme el flequillo yo mismo.', category: 'funny' },
  { question: 'Nunca me he hecho un permanente.', category: 'general' },
  { question: 'Nunca me he quemado tanto con el sol que no podía dormir.', category: 'travel' },
  { question: 'Nunca me he perdido en una tienda de pequeño.', category: 'childhood' },
  { question: 'Nunca he tenido miedo a la oscuridad de adulto.', category: 'general' },
  { question: 'Nunca he tenido una pesadilla recurrente.', category: 'general' },
  { question: 'Nunca he sonámbulo o hablado dormido.', category: 'general' },
  { question: 'Nunca he tenido un sueño que parecía real y afectó mi día.', category: 'general' },
  { question: 'Nunca me he despertado por una pesadilla y he llamado a alguien.', category: 'general' },
  { question: 'Nunca he creído en fantasmas o cosas sobrenaturales.', category: 'general' },
  { question: 'Nunca he creído ver un fantasma o algo paranormal.', category: 'general' },
  { question: 'Nunca he ido a una casa o lugar encantado.', category: 'general' },
  { question: 'Nunca he ido a un psíquico o lector de tarot.', category: 'general' },
  { question: 'Nunca he intentado aprender un truco de magia.', category: 'general' },
  { question: 'Nunca he intentado hacer un mortal o voltereta y fallar.', category: 'funny' },
  { question: 'Nunca he intentado aprender un baile de TikTok o viral.', category: 'funny' },
  { question: 'Nunca he subido un TikTok o Reel.', category: 'general' },
  { question: 'Nunca he sido viral en redes sociales.', category: 'general' },
  { question: 'Nunca ha sido viral una foto mía sin mi consentimiento.', category: 'general' },
  { question: 'Nunca me ha reconocido un desconocido en público.', category: 'general' },
  { question: 'Nunca he ido solo a un parque temático.', category: 'travel' },
  { question: 'Nunca he montado en la misma atracción 5 veces seguidas.', category: 'general' },
  { question: 'Nunca he vomitado en una atracción.', category: 'funny' },
  { question: 'Nunca he tenido miedo en una atracción y haber tenido que bajar.', category: 'general' },
  { question: 'Nunca he probado un deporte extremo.', category: 'risky' },
  { question: 'Nunca me he ofrecido voluntario para algo y me he arrepentido.', category: 'general' },
  { question: 'Nunca he donado sangre.', category: 'general' },
  { question: 'Nunca me he desmayado al ver sangre.', category: 'general' },
  { question: 'Nunca he tenido miedo a las agujas.', category: 'general' },
  { question: 'Nunca he tenido miedo a volar.', category: 'travel' },
  { question: 'Nunca he tenido un ataque de pánico.', category: 'general' },
  { question: 'Nunca he probado la meditación o el yoga.', category: 'general' },
  { question: 'Nunca he ido a terapia o counselling.', category: 'general' },
  { question: 'Nunca he hecho el vacío a alguien más de un día.', category: 'relationships' },
  { question: 'Nunca he guardado rencor durante años.', category: 'relationships' },
  { question: 'Nunca me he disculpado cuando no tenía culpa.', category: 'relationships' },
  { question: 'Nunca me he negado a disculparme cuando tenía culpa.', category: 'relationships' },
  { question: 'Nunca he tenido una discusión pública con alguien.', category: 'relationships' },
  { question: 'Nunca me he reconciliado con alguien después de una gran pelea.', category: 'relationships' },
  { question: 'Nunca he ido a una boda sin conocer bien a la pareja.', category: 'relationships' },
  { question: 'Nunca he sido padrino o madrina de boda.', category: 'relationships' },
  { question: 'Nunca he cogido el ramo o la liga.', category: 'relationships' },
  { question: 'Nunca he dado un discurso en una boda.', category: 'relationships' },
  { question: 'Nunca he llorado en una boda.', category: 'relationships' },
  { question: 'Nunca he ido a un baby shower.', category: 'relationships' },
  { question: 'Nunca he tenido en brazos a un recién nacido.', category: 'general' },
  { question: 'Nunca he cambiado un pañal.', category: 'general' },
  { question: 'Nunca he hecho de canguro.', category: 'general' },
  { question: 'Nunca he querido tener hijos.', category: 'general' },
  { question: 'Nunca he no querido tener hijos.', category: 'general' },
  { question: 'Nunca he tenido una mascota que muriera y llorado.', category: 'general' },
  { question: 'Nunca he enterrado una mascota.', category: 'general' },
  { question: 'Nunca he ido a un funeral y reído en el momento equivocado.', category: 'funny' },
  { question: 'Nunca he hablado en un funeral.', category: 'general' },
  { question: 'Nunca he visitado la tumba de alguien que conocía.', category: 'general' },
  { question: 'Nunca he tenido una experiencia cercana a la muerte y pensado en mi vida.', category: 'risky' },
  { question: 'Nunca he hecho una lista de cosas por hacer antes de morir.', category: 'general' },
  { question: 'Nunca he tachado algo de mi lista.', category: 'general' },
  { question: 'Nunca he intentado aprender un idioma y abandonado.', category: 'general' },
  { question: 'Nunca he aprendido a tocar un instrumento.', category: 'general' },
  { question: 'Nunca he intentado aprender un instrumento y dejado.', category: 'general' },
  { question: 'Nunca he escrito una canción o poema.', category: 'general' },
  { question: 'Nunca he pintado o dibujado algo de lo que me sintiera orgulloso.', category: 'general' },
  { question: 'Nunca he intentado cocinar una comida fancy y fracasado.', category: 'food' },
  { question: 'Nunca he horneado algo desde cero.', category: 'food' },
  { question: 'Nunca he quemado algo que estaba cocinando.', category: 'food' },
  { question: 'Nunca he probado una dieta y la he dejado tras una semana.', category: 'food' },
  { question: 'Nunca he sido vegetariano o vegano.', category: 'food' },
  { question: 'Nunca he probado una tendencia food como la col kale o el toast de aguacate.', category: 'food' },
  { question: 'Nunca he comido algo que cultivé yo mismo.', category: 'food' },
  { question: 'Nunca he ido a un mercado de agricultores.', category: 'food' },
  { question: 'Nunca he ido a un restaurante fancy y me he sentido mal vestido.', category: 'food' },
  { question: 'Nunca he devuelto comida en un restaurante.', category: 'food' },
  { question: 'Nunca me he ido sin dejar propina.', category: 'food' },
  { question: 'Nunca he discutido por la cuenta.', category: 'relationships' },
  { question: 'Nunca he hecho dieta con un amigo.', category: 'relationships' },
  { question: 'Nunca he competido con un amigo por algo tonto.', category: 'relationships' },
  { question: 'Nunca he tenido un apretón de manos secreto con alguien.', category: 'childhood' },
  { question: 'Nunca he tenido un amigo imaginario.', category: 'childhood' },
  { question: 'Nunca he creído en Papá Noel después de los 10 años.', category: 'childhood' },
  { question: 'Nunca he puesto un diente bajo la almohada para el Ratoncito Pérez.', category: 'childhood' },
  { question: 'Nunca he tenido miedo a los payasos.', category: 'general' },
  { question: 'Nunca he ido al circo.', category: 'general' },
  { question: 'Nunca he ido al zoo y me he sentido mal por los animales.', category: 'general' },
  { question: 'Nunca he montado a caballo.', category: 'general' },
  { question: 'Nunca me ha picado un insecto y he tenido mala reacción.', category: 'general' },
  { question: 'Nunca he tenido miedo a las arañas o insectos.', category: 'general' },
  { question: 'Nunca he matado una araña por alguien.', category: 'general' },
  { question: 'Nunca he rescatado un animal.', category: 'general' },
  { question: 'Nunca he adoptado una mascota de una protectora.', category: 'general' },
  { question: 'Nunca he perdido una mascota.', category: 'general' },
  { question: 'Nunca se me ha escapado una mascota.', category: 'general' },
  { question: 'Nunca he mentido que estaba ocupado para escaquearme de planes.', category: 'general' },
  { question: 'Nunca he fingido que me gustaba una canción cuando alguien la ponía.', category: 'funny' },
  { question: 'Nunca he dicho "ya voy" cuando aún no había salido.', category: 'funny' },
  { question: 'Nunca he leído el diario de otro.', category: 'relationships' },
  { question: 'Nunca he tenido un apodo que me puse yo mismo.', category: 'funny' },
  { question: 'Nunca he sido el tercero en una cita.', category: 'relationships' },
  { question: 'Nunca he dado like por error a una publicación de un ex.', category: 'funny' },
  { question: 'Nunca he seguido en una relación más de lo que debía.', category: 'relationships' },
  { question: 'Nunca he soñado con alguien y me he sentido raro con él al día siguiente.', category: 'general' },
  { question: 'Nunca he visto una serie más de cinco veces.', category: 'general' },
  { question: 'Nunca he llorado con un anuncio.', category: 'funny' },
  { question: 'Nunca he hablado solo frente al espejo.', category: 'funny' },
  { question: 'Nunca he ensayado una conversación antes de tenerla.', category: 'general' },
  { question: 'Nunca he tenido miedo de mirar el saldo del banco.', category: 'general' },
  { question: 'Nunca he comprado algo que no me podía permitir.', category: 'general' },
  { question: 'Nunca he devuelto un regalo.', category: 'relationships' },
  { question: 'Nunca he olvidado el cumpleaños de un amigo cercano.', category: 'relationships' },
  { question: 'Nunca he llegado tarde a mi propio evento.', category: 'funny' },
  { question: 'Nunca he mezclado dos nombres en la misma frase.', category: 'funny' },
  { question: 'Nunca he dicho "hasta mañana" a alguien que sabía que no vería.', category: 'funny' },
  { question: 'Nunca he fingido entender un chiste y reído igual.', category: 'funny' },
  { question: 'Nunca he asentido en una conversación que no seguía.', category: 'funny' },
  { question: 'Nunca me han pillado cantando en el coche en un semáforo.', category: 'funny' },
  { question: 'Nunca he tenido un crush por un personaje de ficción.', category: 'general' },
  { question: 'Nunca he escrito una carta que no envié.', category: 'general' },
  { question: 'Nunca he intentado arreglar algo y empeorarlo.', category: 'funny' },
  { question: 'Nunca he culpado a otro de algo que hice yo.', category: 'relationships' },
  { question: 'Nunca me he atribuido la idea de otro.', category: 'work' },
  { question: 'Nunca me han pillado en una mentira piadosa.', category: 'funny' },
  { question: 'Nunca he exagerado una historia para hacerla más interesante.', category: 'general' },
  { question: 'Nunca he tenido celos del éxito de un amigo.', category: 'relationships' },
  { question: 'Nunca me he comparado con alguien en redes y me he sentido mal.', category: 'general' },
  { question: 'Nunca he borrado una foto por cómo salía.', category: 'general' },
  { question: 'Nunca he estado nervioso antes de una entrevista de trabajo.', category: 'work' },
  { question: 'Nunca he metido la pata el primer día en un trabajo nuevo.', category: 'work' },
  { question: 'Nunca me he quedado dormido durante una película en el cine.', category: 'funny' },
  { question: 'Nunca he tenido una intoxicación alimentaria.', category: 'food' },
  { question: 'Nunca he intentado impresionar a alguien con una habilidad que no tengo.', category: 'general' },
  { question: 'Nunca me han pillado haciendo algo vergonzoso en cámara.', category: 'funny' },
  { question: 'Nunca he tenido una fase de la que me avergüence ahora.', category: 'general' },
  { question: 'Nunca he llevado algo que claramente era demasiado pequeño o grande.', category: 'funny' },
  { question: 'Nunca he reaccionado mal a un corte de pelo y fingido que me gustaba.', category: 'funny' },
  { question: 'Nunca he intentado hacer un buen selfie más de 10 minutos.', category: 'funny' },
  { question: 'Nunca he sido el que estropeó la foto de grupo.', category: 'funny' },
  { question: 'Nunca he olvidado lo que iba a decir a mitad de frase.', category: 'funny' },
  { question: 'Nunca he llamado "mamá" o "papá" por error a un profesor.', category: 'childhood' },
  { question: 'Nunca he andado con seguridad en la dirección equivocada.', category: 'funny' },
  { question: 'Nunca he intentado abrir una puerta que decía "tirar" empujando.', category: 'funny' },
  { question: 'Nunca he dicho "gracias" cuando alguien dijo "perdona".', category: 'funny' },
  { question: 'Nunca he saludado a un bebé y luego me he dado cuenta de que era un muñeco.', category: 'funny' },
  { question: 'Nunca he tenido miedo a la oscuridad de adulto.', category: 'general' },
  { question: 'Nunca he dormido con un peluche de adulto.', category: 'general' },
  { question: 'Nunca he tenido un amuleto o superstición.', category: 'general' },
  { question: 'Nunca he pedido un deseo con una estrella fugaz.', category: 'general' },
  { question: 'Nunca he roto un espejo y me he preocupado por la mala suerte.', category: 'general' },
  { question: 'Nunca he pasado por debajo de una escalera.', category: 'general' },
  { question: 'Nunca he ido a una vidente.', category: 'general' },
  { question: 'Nunca he intentado tener sueños lúcidos.', category: 'general' },
  { question: 'Nunca he tenido parálisis del sueño.', category: 'general' },
  { question: 'Nunca me he despertado y no he sabido dónde estaba un momento.', category: 'general' },
  { question: 'Nunca he dormido la alarma y perdido algo importante.', category: 'funny' },
  { question: 'Nunca he pulsado snooze más de tres veces seguidas.', category: 'funny' },
  { question: 'Nunca he tenido una conversación dormido que alguien oyera.', category: 'funny' },
  { question: 'Nunca me he despertado con mi propio ronquido.', category: 'funny' },
  { question: 'Nunca me he quedado dormido en una biblioteca.', category: 'general' },
  { question: 'Nunca he pasado la noche en vela por algo que no era trabajo ni colegio.', category: 'general' },
  { question: 'Nunca he echado una siesta que se convirtió en dormir toda la noche.', category: 'funny' },
  { question: 'Nunca he ido a un bar de karaoke y no cantar.', category: 'general' },
  { question: 'Nunca he cantado karaoke y olvidado la letra.', category: 'funny' },
  { question: 'Nunca he ido a un show de comedia y el cómico se ha metido conmigo.', category: 'funny' },
  { question: 'Nunca he ido a un parque temático y puesto malo en una atracción.', category: 'travel' },
  { question: 'Nunca he perdido el equipaje viajando.', category: 'travel' },
  { question: 'Nunca he tenido un vuelo retrasado más de 5 horas.', category: 'travel' },
  { question: 'Nunca he sentado al lado de alguien pesado en un vuelo largo.', category: 'travel' },
  { question: 'Nunca he ido a un país donde no hablaba el idioma.', category: 'travel' },
  { question: 'Nunca he comprado un souvenir que se rompió antes de llegar a casa.', category: 'travel' },
  { question: 'Nunca he hecho una foto con un desconocido viajando.', category: 'travel' },
  { question: 'Nunca me he hecho un tatuaje del que luego me arrepentí.', category: 'general' },
  { question: 'Nunca he tenido un piercing que se infectara.', category: 'general' },
  { question: 'Nunca he intentado teñirme el pelo en casa y haber salido mal.', category: 'funny' },
  { question: 'Nunca he tenido una fase de moda que me alegre que haya pasado.', category: 'general' },
  { question: 'Nunca he llevado algo de la sección del otro género.', category: 'general' },
  { question: 'Nunca he comprado el mismo outfit en varios colores.', category: 'general' },
  { question: 'Nunca he perdido las llaves y tenido que forzar mi propia casa.', category: 'funny' },
  { question: 'Nunca me he quedado fuera de casa o del coche.', category: 'funny' },
  { question: 'Nunca he olvidado dónde aparqué el coche.', category: 'funny' },
  { question: 'Nunca me he quedado sin gasolina en la carretera.', category: 'general' },
  { question: 'Nunca he tenido un pinchazo.', category: 'general' },
  { question: 'Nunca he estado en un coche que se averió en medio de la nada.', category: 'travel' },
  { question: 'Nunca he ayudado a un desconocido con su coche.', category: 'general' },
  { question: 'Nunca he dado dinero a un desconocido en la calle.', category: 'general' },
  { question: 'Nunca me he ofrecido voluntario por una causa que me importa.', category: 'general' },
  { question: 'Nunca he donado a una organización benéfica.', category: 'general' },
  { question: 'Nunca he corrido una carrera de 5K o más.', category: 'general' },
  { question: 'Nunca me he apuntado al gimnasio y dejado de ir tras un mes.', category: 'general' },
  { question: 'Nunca he probado un deporte y lo he dejado por no ser bueno.', category: 'general' },
  { question: 'Nunca he ido a un partido en vivo.', category: 'general' },
  { question: 'Nunca he llorado por un partido.', category: 'general' },
  { question: 'Nunca me he pintado la cara para un partido o evento.', category: 'general' },
  { question: 'Nunca he ido a una manifestación o concentración.', category: 'general' },
  { question: 'Nunca he escrito una reseña online.', category: 'general' },
  { question: 'Nunca he discutido con un desconocido en los comentarios.', category: 'funny' },
  { question: 'Nunca he borrado un comentario que subí por las críticas.', category: 'funny' },
  { question: 'Nunca me ha bloqueado alguien que conozco.', category: 'relationships' },
  { question: 'Nunca he tenido un secreto demasiado grande para guardar.', category: 'relationships' },
  { question: 'Nunca he contado el secreto de un amigo a otro.', category: 'relationships' },
  { question: 'Nunca me han pillado en una mentira alguien que me importaba.', category: 'relationships' },
  { question: 'Nunca me he disculpado años después por algo que hice.', category: 'relationships' },
  { question: 'Nunca me he reencontrado con un ex solo para ver cómo estaba.', category: 'relationships' },
  { question: 'Nunca he tenido un crush por mi mejor amigo.', category: 'relationships' },
  { question: 'Nunca he tenido una cita a ciegas que salió mal.', category: 'relationships' },
  { question: 'Nunca he sido yo quien terminó una amistad.', category: 'relationships' },
  { question: 'Nunca he hecho un amigo esperando en cola.', category: 'general' },
  { question: 'Nunca he tenido un vecino con el que me hiciera amigo.', category: 'relationships' },
  { question: 'Nunca he ido a una reunión y me he arrepentido.', category: 'relationships' },
  { question: 'Nunca he olvidado el nombre de un amigo al presentarlo.', category: 'funny' },
  { question: 'Nunca he confundido los nombres de dos amigos.', category: 'funny' },
  { question: 'Nunca he tenido un grupo de chat que se quedó en silencio tras un mensaje.', category: 'funny' },
  { question: 'Nunca he dejado un mensaje en "leído" más de un día.', category: 'relationships' },
  { question: 'Nunca he fingido mala conexión para colgar.', category: 'funny' },
  { question: 'Nunca he dicho "tengo que irme" cuando no era verdad.', category: 'funny' },
  { question: 'Nunca he ido a una fiesta donde no conocía a nadie.', category: 'general' },
  { question: 'Nunca he sido el último en irse de una fiesta.', category: 'general' },
  { question: 'Nunca he organizado una fiesta que se descontroló.', category: 'general' },
  { question: 'Nunca he limpiado después de la fiesta de otro.', category: 'general' },
  { question: 'Nunca he tenido un compañero de piso con el que no me llevara.', category: 'relationships' },
  { question: 'Nunca me han organizado una fiesta sorpresa.', category: 'general' },
  { question: 'Nunca he destrozado una sorpresa.', category: 'funny' },
  { question: 'Nunca he olvidado un aniversario.', category: 'relationships' },
  { question: 'Nunca he montado un escándalo en una reunión familiar.', category: 'relationships' },
  { question: 'Nunca he tenido un familiar al que evito en fiestas.', category: 'relationships' },
  { question: 'Nunca he mentido a mi familia sobre dónde iba.', category: 'childhood' },
  { question: 'Nunca he colado a alguien en mi casa.', category: 'childhood' },
  { question: 'Nunca me han pillado haciendo algo que no debía.', category: 'general' },
];
