module.exports = [
  { question: 'Je n\'ai jamais menti sur mon âge.', category: 'general' },
  { question: 'Je n\'ai jamais fait semblant d\'être au téléphone pour éviter quelqu\'un.', category: 'funny' },
  { question: 'Je n\'ai jamais chanté sous la douche.', category: 'general' },
  { question: 'Je n\'ai jamais dansé quand personne ne regardait.', category: 'general' },
  { question: 'Je n\'ai jamais pleuré pendant un film.', category: 'general' },
  { question: 'Je n\'ai jamais envoyé un message à la mauvaise personne.', category: 'funny' },
  { question: 'Je n\'ai jamais oublié le nom de quelqu\'un juste après qu\'il se soit présenté.', category: 'funny' },
  { question: 'Je n\'ai jamais fait signe à quelqu\'un qui ne me faisait pas signe.', category: 'funny' },
  { question: 'Je n\'ai jamais rejeté la faute sur le chien pour quelque chose que j\'ai fait.', category: 'funny' },
  { question: 'Je n\'ai jamais googlé mon propre nom.', category: 'general' },
  { question: 'Je n\'ai jamais passé toute une nuit à regarder une série.', category: 'general' },
  { question: 'Je n\'ai jamais mangé de la nourriture tombée par terre.', category: 'food' },
  { question: 'Je n\'ai jamais fait passer un éternuement pour une toux.', category: 'funny' },
  { question: 'Je n\'ai jamais fait semblant de travailler en surfant sur internet.', category: 'work' },
  { question: 'Je n\'ai jamais repassé une conversation dans ma tête en me sentant gêné.', category: 'general' },
  { question: 'Je n\'ai jamais eu le béguin pour un prof.', category: 'childhood' },
  { question: 'Je n\'ai jamais été pris en train de m\'admirer dans un miroir.', category: 'funny' },
  { question: 'Je n\'ai jamais ri si fort que j\'en ai pleuré.', category: 'general' },
  { question: 'Je n\'ai jamais entré dans une pièce en oubliant pourquoi j\'y allais.', category: 'funny' },
  { question: 'Je n\'ai jamais rejeté la faute sur la technologie pour ma propre erreur.', category: 'funny' },
  { question: 'Je n\'ai jamais voyagé seul dans un autre pays.', category: 'travel' },
  { question: 'Je n\'ai jamais raté un avion ou un train.', category: 'travel' },
  { question: 'Je n\'ai jamais été perdu dans une ville étrangère.', category: 'travel' },
  { question: 'Je n\'ai jamais goûté un plat dont j\'avais peur.', category: 'food' },
  { question: 'Je n\'ai jamais mangé quelque chose périmé.', category: 'food' },
  { question: 'Je n\'ai jamais commandé la même chose au restaurant à chaque fois.', category: 'food' },
  { question: 'Je n\'ai jamais mangé le dessert avant le dîner.', category: 'food' },
  { question: 'Je n\'ai jamais menti sur mon CV.', category: 'work' },
  { question: 'Je n\'ai jamais appelé malade quand je ne l\'étais pas.', category: 'work' },
  { question: 'Je n\'ai jamais dormi en réunion ou en cours.', category: 'work' },
  { question: 'Je n\'ai jamais eu un crush au travail.', category: 'work' },
  { question: 'Je n\'ai jamais été en retard à un événement important.', category: 'general' },
  { question: 'Je n\'ai jamais cassé quelque chose chez un ami sans lui dire.', category: 'relationships' },
  { question: 'Je n\'ai jamais eu un admirateur secret.', category: 'relationships' },
  { question: 'Je n\'ai jamais été friendzoné.', category: 'relationships' },
  { question: 'Je n\'ai jamais eu un plan d\'un soir.', category: 'risky' },
  { question: 'Je n\'ai jamais embrassé un inconnu.', category: 'risky' },
  { question: 'Je n\'ai jamais fait de tatouage.', category: 'general' },
  { question: 'Je n\'ai jamais fait de piercing ailleurs qu\'aux oreilles.', category: 'general' },
  { question: 'Je n\'ai jamais teint mes cheveux en couleur folle.', category: 'general' },
  { question: 'Je n\'ai jamais été à un concert.', category: 'general' },
  { question: 'Je n\'ai jamais été à un festival de musique.', category: 'general' },
  { question: 'Je n\'ai jamais rencontré une célébrité.', category: 'general' },
  { question: 'Je n\'ai jamais passé à la télé ou dans une vidéo virale.', category: 'general' },
  { question: 'Je n\'ai jamais couru un marathon ou semi-marathon.', category: 'general' },
  { question: 'Je n\'ai jamais fait du saut en parachute ou du saut à l\'élastique.', category: 'risky' },
  { question: 'Je n\'ai jamais fait des montagnes russes.', category: 'general' },
  { question: 'Je n\'ai jamais nagé dans l\'océan la nuit.', category: 'travel' },
  { question: 'Je n\'ai jamais campé en pleine nature.', category: 'travel' },
  { question: 'Je n\'ai jamais fait du stop.', category: 'risky' },
  { question: 'Je n\'ai jamais dormi dans un aéroport.', category: 'travel' },
  { question: 'Je n\'ai jamais été dans plus de 10 pays.', category: 'travel' },
  { question: 'Je n\'ai jamais appris à parler une autre langue couramment.', category: 'general' },
  { question: 'Je n\'ai jamais vécu dans un autre pays.', category: 'travel' },
  { question: 'Je n\'ai jamais eu un correspondant d\'un autre pays.', category: 'childhood' },
  { question: 'Je n\'ai jamais été à un mariage.', category: 'relationships' },
  { question: 'Je n\'ai jamais été à un enterrement.', category: 'general' },
  { question: 'Je n\'ai jamais été dans une bagarre.', category: 'risky' },
  { question: 'Je n\'ai jamais été arrêté par la police.', category: 'risky' },
  { question: 'Je n\'ai jamais été dans un casino.', category: 'risky' },
  { question: 'Je n\'ai jamais joué de l\'argent que je ne pouvais pas me permettre de perdre.', category: 'risky' },
  { question: 'Je n\'ai jamais eu une fracture.', category: 'general' },
  { question: 'Je n\'ai jamais eu de points de suture.', category: 'general' },
  { question: 'Je n\'ai jamais fait un malaise.', category: 'general' },
  { question: 'Je n\'ai jamais passé une nuit à l\'hôpital.', category: 'general' },
  { question: 'Je n\'ai jamais été aux urgences.', category: 'general' },
  { question: 'Je n\'ai jamais eu une expérience de mort imminente.', category: 'risky' },
  { question: 'Je n\'ai jamais sauvé la vie de quelqu\'un.', category: 'general' },
  { question: 'Je n\'ai jamais eu un accident de voiture.', category: 'general' },
  { question: 'Je n\'ai jamais eu une amende pour excès de vitesse.', category: 'risky' },
  { question: 'Je n\'ai jamais fait de moto.', category: 'general' },
  { question: 'Je n\'ai jamais fait de plongée sous-marine.', category: 'travel' },
  { question: 'Je n\'ai jamais essayé le surf.', category: 'general' },
  { question: 'Je n\'ai jamais fait de ski ou snowboard.', category: 'general' },
  { question: 'Je n\'ai jamais gravi une montagne.', category: 'travel' },
  { question: 'Je n\'ai jamais fait de croisière.', category: 'travel' },
  { question: 'Je n\'ai jamais été sur un bateau au milieu de l\'océan.', category: 'travel' },
  { question: 'Je n\'ai jamais vu les aurores boréales.', category: 'travel' },
  { question: 'Je n\'ai jamais vu un animal sauvage de près.', category: 'travel' },
  { question: 'Je n\'ai jamais été mordu par un animal.', category: 'general' },
  { question: 'Je n\'ai jamais eu un animal qui n\'était ni chat ni chien.', category: 'general' },
  { question: 'Je n\'ai jamais volé quelque chose.', category: 'risky' },
  { question: 'Je n\'ai jamais été arrêté ou détenu.', category: 'risky' },
  { question: 'Je n\'ai jamais été dans un club de strip-tease.', category: 'risky' },
  { question: 'Je n\'ai jamais nagé nu.', category: 'risky' },
  { question: 'Je n\'ai jamais été nu en public.', category: 'risky' },
  { question: 'Je n\'ai jamais eu un décolleté malencontreux en public.', category: 'funny' },
  { question: 'Je n\'ai jamais surpris quelqu\'un aux toilettes.', category: 'funny' },
  { question: 'Je n\'ai jamais été surpris aux toilettes.', category: 'funny' },
  { question: 'Je n\'ai jamais rêvé de quelqu\'un dans cette pièce.', category: 'risky' },
  { question: 'Je n\'ai jamais eu le béguin pour l\'ex d\'un ami.', category: 'relationships' },
  { question: 'Je n\'ai jamais fréquenté deux personnes en même temps.', category: 'relationships' },
  { question: 'Je n\'ai jamais été à un rencard blind.', category: 'relationships' },
  { question: 'Je n\'ai jamais été catfishé ou dupé en ligne.', category: 'relationships' },
  { question: 'Je n\'ai jamais écrit en DM à quelqu\'un.', category: 'relationships' },
  { question: 'Je n\'ai jamais eu le coup de foudre.', category: 'relationships' },
  { question: 'Je n\'ai jamais eu une relation à distance.', category: 'relationships' },
  { question: 'Je n\'ai jamais remis le couvert avec un ex.', category: 'relationships' },
  { question: 'Je n\'ai jamais été ghosté.', category: 'relationships' },
  { question: 'Je n\'ai jamais ghosté quelqu\'un.', category: 'relationships' },
  { question: 'Je n\'ai jamais eu un crush à sens unique pendant plus d\'un an.', category: 'relationships' },
  { question: 'Je n\'ai jamais écrit une lettre d\'amour.', category: 'relationships' },
  { question: 'Je n\'ai jamais reçu ni donné une sérénade.', category: 'relationships' },
  { question: 'Je n\'ai jamais fait une bataille de nourriture.', category: 'childhood' },
  { question: 'Je n\'ai jamais été envoyé chez le directeur.', category: 'childhood' },
  { question: 'Je n\'ai jamais triché à un examen.', category: 'childhood' },
  { question: 'Je n\'ai jamais été suspendu ou exclu de l\'école.', category: 'childhood' },
  { question: 'Je n\'ai jamais passé une nuit blanche pour l\'école.', category: 'childhood' },
  { question: 'Je n\'ai jamais eu une fausse carte d\'identité.', category: 'risky' },
  { question: 'Je n\'ai jamais fugué de la maison ado.', category: 'childhood' },
  { question: 'Je n\'ai jamais fait une fête quand mes parents étaient absents.', category: 'childhood' },
  { question: 'Je n\'ai jamais cassé une vitre ou un objet de valeur à la maison.', category: 'childhood' },
  { question: 'Je n\'ai jamais été puni plus d\'une semaine.', category: 'childhood' },
  { question: 'Je n\'ai jamais menti à mes parents sur où j\'étais.', category: 'childhood' },
  { question: 'Je n\'ai jamais eu un journal intime lu par quelqu\'un.', category: 'childhood' },
  { question: 'Je n\'ai jamais joué dans une pièce ou un spectacle de l\'école.', category: 'childhood' },
  { question: 'Je n\'ai jamais été le dernier choisi pour une équipe.', category: 'childhood' },
  { question: 'Je n\'ai jamais été harcelé ni harcelé quelqu\'un.', category: 'childhood' },
  { question: 'Je n\'ai jamais eu un surnom que je détestais.', category: 'funny' },
  { question: 'Je n\'ai jamais été photobombé ni photobombé quelqu\'un.', category: 'funny' },
  { question: 'Je n\'ai jamais pris un selfie et l\'avoir supprimé tout de suite.', category: 'funny' },
  { question: 'Je n\'ai jamais posté quelque chose et l\'avoir supprimé en une heure.', category: 'funny' },
  { question: 'Je n\'ai jamais disputé avec un inconnu sur internet.', category: 'funny' },
  { question: 'Je n\'ai jamais commenté par erreur un vieux post.', category: 'funny' },
  { question: 'Je n\'ai jamais liké mon propre post ou ma propre photo.', category: 'funny' },
  { question: 'Je n\'ai jamais liké par erreur une vieille photo de quelqu\'un.', category: 'funny' },
  { question: 'Je n\'ai jamais été bloqué par quelqu\'un sur les réseaux.', category: 'relationships' },
  { question: 'Je n\'ai jamais bloqué quelqu\'un que je connais en vrai.', category: 'relationships' },
  { question: 'Je n\'ai jamais eu plus de 1000 abonnés sur une plateforme.', category: 'general' },
  { question: 'Je n\'ai jamais été viral pour un truc gênant.', category: 'funny' },
  { question: 'Je n\'ai jamais essayé de cuisiner et complètement raté.', category: 'food' },
  { question: 'Je n\'ai jamais déclenché le détecteur de fumée en cuisinant.', category: 'food' },
  { question: 'Je n\'ai jamais commandé des pizzas plus de deux fois en une semaine.', category: 'food' },
  { question: 'Je n\'ai jamais mangé une pizza entière tout seul.', category: 'food' },
  { question: 'Je n\'ai jamais mangé quelque chose de cru qui devait être cuit.', category: 'food' },
  { question: 'Je n\'ai jamais essayé une combinaison alimentaire bizarre.', category: 'food' },
  { question: 'Je n\'ai jamais été au buffet à volonté et m\'être rendu malade.', category: 'food' },
  { question: 'Je n\'ai jamais volé de la nourriture à un coloc ou un proche.', category: 'food' },
  { question: 'Je n\'ai jamais mangé le petit-déjeuner au dîner.', category: 'food' },
  { question: 'Je n\'ai jamais eu une addiction à la caféine.', category: 'food' },
  { question: 'Je n\'ai jamais bu des boissons énergétiques pour rester éveillé.', category: 'food' },
  { question: 'Je n\'ai jamais été au drive en pyjama.', category: 'funny' },
  { question: 'Je n\'ai jamais pleuré pour du lait renversé ou de la nourriture tombée.', category: 'funny' },
  { question: 'Je n\'ai jamais fait semblant d\'aimer un cadeau reçu.', category: 'relationships' },
  { question: 'Je n\'ai jamais revendu un cadeau.', category: 'relationships' },
  { question: 'Je n\'ai jamais oublié l\'anniversaire d\'un ami proche ou d\'un proche.', category: 'relationships' },
  { question: 'Je n\'ai jamais débarqué à une fête le mauvais jour.', category: 'funny' },
  { question: 'Je n\'ai jamais été le seul déguisé.', category: 'funny' },
  { question: 'Je n\'ai jamais dormi à une fête.', category: 'funny' },
  { question: 'Je n\'ai jamais été le conducteur désigné et détesté ça.', category: 'general' },
  { question: 'Je n\'ai jamais perdu mon téléphone et paniqué.', category: 'funny' },
  { question: 'Je n\'ai jamais oublié mon téléphone et me suis senti nu.', category: 'funny' },
  { question: 'Je n\'ai jamais fait tomber mon téléphone dans les toilettes.', category: 'funny' },
  { question: 'Je n\'ai jamais cassé l\'écran de mon téléphone.', category: 'general' },
  { question: 'Je n\'ai jamais utilisé le téléphone de quelqu\'un sans demander.', category: 'relationships' },
  { question: 'Je n\'ai jamais regardé les messages de quelqu\'un.', category: 'relationships' },
  { question: 'Je n\'ai jamais été pris en train de regarder le téléphone de quelqu\'un.', category: 'funny' },
  { question: 'Je n\'ai jamais eu un mot de passe "password" ou "123456".', category: 'funny' },
  { question: 'Je n\'ai jamais oublié un mot de passe important.', category: 'funny' },
  { question: 'Je n\'ai jamais répondu "toi aussi" quand quelqu\'un a dit "bon film" ou similaire.', category: 'funny' },
  { question: 'Je n\'ai jamais dit "au revoir" deux fois dans la même conversation.', category: 'funny' },
  { question: 'Je n\'ai jamais trébuché en public.', category: 'funny' },
  { question: 'Je n\'ai jamais fait signe à un inconnu en croyant le connaître.', category: 'funny' },
  { question: 'Je n\'ai jamais essayé d\'ouvrir une porte à pousser en tirant.', category: 'funny' },
  { question: 'Je n\'ai jamais foncé dans une porte en verre.', category: 'funny' },
  { question: 'Je n\'ai jamais raté une marche et trébuché.', category: 'funny' },
  { question: 'Je n\'ai jamais eu une visio et oublié que la caméra était allumée.', category: 'work' },
  { question: 'Je n\'ai jamais été en réunion sans rien comprendre au sujet.', category: 'work' },
  { question: 'Je n\'ai jamais fait une sieste pendant les heures de travail.', category: 'work' },
  { question: 'Je n\'ai jamais eu un job que je détestais.', category: 'work' },
  { question: 'Je n\'ai jamais démissionné sans avoir un autre job.', category: 'work' },
  { question: 'Je n\'ai jamais été viré.', category: 'work' },
  { question: 'Je n\'ai jamais été promu.', category: 'work' },
  { question: 'Je n\'ai jamais eu une rivalité avec un collègue.', category: 'work' },
  { question: 'Je n\'ai jamais fréquenté un collègue.', category: 'work' },
  { question: 'Je n\'ai jamais eu un crush pour une célébrité.', category: 'general' },
  { question: 'Je n\'ai jamais écrit de fan mail ni envoyé de DM à une célébrité.', category: 'general' },
  { question: 'Je n\'ai jamais pleuré pour une rupture de célébrités.', category: 'funny' },
  { question: 'Je n\'ai jamais été à une avant-première minuit.', category: 'general' },
  { question: 'Je n\'ai jamais été déguisé en personnage pour une sortie de film.', category: 'funny' },
  { question: 'Je n\'ai jamais revu le même film plus de 10 fois.', category: 'general' },
  { question: 'Je n\'ai jamais dormi au cinéma.', category: 'funny' },
  { question: 'Je n\'ai jamais été à un concert sans connaître aucune chanson.', category: 'funny' },
  { question: 'Je n\'ai jamais fait du karaoké.', category: 'general' },
  { question: 'Je n\'ai jamais dansé sur une table.', category: 'risky' },
  { question: 'Je n\'ai jamais fait une scène en public.', category: 'funny' },
  { question: 'Je n\'ai jamais été viré d\'un endroit.', category: 'risky' },
  { question: 'Je n\'ai jamais frôlé des ennuis avec la loi.', category: 'risky' },
  { question: 'Je n\'ai jamais aidé quelqu\'un à cacher quelque chose à ses parents.', category: 'relationships' },
  { question: 'Je n\'ai jamais gardé un secret très difficile à garder.', category: 'relationships' },
  { question: 'Je n\'ai jamais révélé un secret par erreur.', category: 'relationships' },
  { question: 'Je n\'ai jamais été trahi par un ami.', category: 'relationships' },
  { question: 'Je n\'ai jamais trahi la confiance d\'un ami.', category: 'relationships' },
  { question: 'Je n\'ai jamais brouillé avec mon meilleur ami.', category: 'relationships' },
  { question: 'Je n\'ai jamais renoué avec un vieil ami après des années.', category: 'relationships' },
  { question: 'Je n\'ai jamais été à une réunion d\'anciens élèves.', category: 'relationships' },
  { question: 'Je n\'ai jamais eu un coloc que je ne supportais pas.', category: 'relationships' },
  { question: 'Je n\'ai jamais eu un voisin que je ne supportais pas.', category: 'relationships' },
  { question: 'Je n\'ai jamais critiqué quelqu\'un qui était dans la même pièce.', category: 'funny' },
  { question: 'Je n\'ai jamais été pris en train de parler de quelqu\'un.', category: 'funny' },
  { question: 'Je n\'ai jamais ri au mauvais moment.', category: 'funny' },
  { question: 'Je n\'ai jamais pété en public en faisant semblant que ce n\'était pas moi.', category: 'funny' },
  { question: 'Je n\'ai jamais eu un décolleté malencontreux.', category: 'funny' },
  { question: 'Je n\'ai jamais porté la même tenue deux jours de suite au travail ou à l\'école.', category: 'general' },
  { question: 'Je n\'ai jamais porté un vêtement à l\'envers par erreur.', category: 'funny' },
  { question: 'Je n\'ai jamais porté deux chaussures différentes.', category: 'funny' },
  { question: 'Je n\'ai jamais quitté la maison sans pantalon ou en pyjama.', category: 'funny' },
  { question: 'Je n\'ai jamais eu une mauvaise coupe et pleuré.', category: 'funny' },
  { question: 'Je n\'ai jamais me suis coupé les cheveux moi-même.', category: 'general' },
  { question: 'Je n\'ai jamais essayé de me couper la frange moi-même.', category: 'funny' },
  { question: 'Je n\'ai jamais fait une permanente.', category: 'general' },
  { question: 'Je n\'ai jamais eu un coup de soleil si fort que je ne pouvais pas dormir.', category: 'travel' },
  { question: 'Je n\'ai jamais été perdu dans un magasin enfant.', category: 'childhood' },
  { question: 'Je n\'ai jamais eu peur du noir adulte.', category: 'general' },
  { question: 'Je n\'ai jamais eu un cauchemar récurrent.', category: 'general' },
  { question: 'Je n\'ai jamais fait du somnambulisme ou parlé en dormant.', category: 'general' },
  { question: 'Je n\'ai jamais fait un rêve qui semblait réel et a affecté ma journée.', category: 'general' },
  { question: 'Je n\'ai jamais été réveillé par un cauchemar et appelé quelqu\'un.', category: 'general' },
  { question: 'Je n\'ai jamais cru aux fantômes ou au surnaturel.', category: 'general' },
  { question: 'Je n\'ai jamais cru voir un fantôme ou quelque chose de paranormal.', category: 'general' },
  { question: 'Je n\'ai jamais été dans une maison ou un lieu hanté.', category: 'general' },
  { question: 'Je n\'ai jamais été voir un médium ou un lecteur de tarot.', category: 'general' },
  { question: 'Je n\'ai jamais essayé d\'apprendre un tour de magie.', category: 'general' },
  { question: 'Je n\'ai jamais essayé de faire un salto ou une roue et raté.', category: 'funny' },
  { question: 'Je n\'ai jamais essayé d\'apprendre une danse TikTok ou virale.', category: 'funny' },
  { question: 'Je n\'ai jamais posté un TikTok ou Reel.', category: 'general' },
  { question: 'Je n\'ai jamais été viral sur les réseaux.', category: 'general' },
  { question: 'Je n\'ai jamais eu une photo de moi virale sans mon accord.', category: 'general' },
  { question: 'Je n\'ai jamais été reconnu en public par un inconnu.', category: 'general' },
  { question: 'Je n\'ai jamais été seul dans un parc d\'attractions.', category: 'travel' },
  { question: 'Je n\'ai jamais fait la même attraction 5 fois d\'affilée.', category: 'general' },
  { question: 'Je n\'ai jamais vomi dans une attraction.', category: 'funny' },
  { question: 'Je n\'ai jamais eu peur dans une attraction et dû descendre.', category: 'general' },
  { question: 'Je n\'ai jamais essayé un sport extrême.', category: 'risky' },
  { question: 'Je n\'ai jamais été bénévole pour quelque chose et l\'avoir regretté.', category: 'general' },
  { question: 'Je n\'ai jamais donné mon sang.', category: 'general' },
  { question: 'Je n\'ai jamais fait un malaise à la vue du sang.', category: 'general' },
  { question: 'Je n\'ai jamais eu peur des aiguilles.', category: 'general' },
  { question: 'Je n\'ai jamais eu peur de l\'avion.', category: 'travel' },
  { question: 'Je n\'ai jamais fait une crise de panique.', category: 'general' },
  { question: 'Je n\'ai jamais essayé la méditation ou le yoga.', category: 'general' },
  { question: 'Je n\'ai jamais été en thérapie ou en counselling.', category: 'general' },
  { question: 'Je n\'ai jamais fait la gueule à quelqu\'un plus d\'un jour.', category: 'relationships' },
  { question: 'Je n\'ai jamais gardé rancune pendant des années.', category: 'relationships' },
  { question: 'Je n\'ai jamais présenté des excuses quand je n\'avais pas tort.', category: 'relationships' },
  { question: 'Je n\'ai jamais refusé de m\'excuser quand j\'avais tort.', category: 'relationships' },
  { question: 'Je n\'ai jamais eu une dispute en public.', category: 'relationships' },
  { question: 'Je n\'ai jamais fait la paix après une grosse dispute.', category: 'relationships' },
  { question: 'Je n\'ai jamais été à un mariage sans bien connaître le couple.', category: 'relationships' },
  { question: 'Je n\'ai jamais été demoiselle ou garçon d\'honneur.', category: 'relationships' },
  { question: 'Je n\'ai jamais attrapé le bouquet ou la jarretière.', category: 'relationships' },
  { question: 'Je n\'ai jamais fait un discours à un mariage.', category: 'relationships' },
  { question: 'Je n\'ai jamais pleuré à un mariage.', category: 'relationships' },
  { question: 'Je n\'ai jamais été à un baby shower.', category: 'relationships' },
  { question: 'Je n\'ai jamais tenu un nouveau-né dans mes bras.', category: 'general' },
  { question: 'Je n\'ai jamais changé une couche.', category: 'general' },
  { question: 'Je n\'ai jamais fait du baby-sitting.', category: 'general' },
  { question: 'Je n\'ai jamais voulu avoir des enfants.', category: 'general' },
  { question: 'Je n\'ai jamais ne pas voulu avoir d\'enfants.', category: 'general' },
  { question: 'Je n\'ai jamais perdu un animal et pleuré.', category: 'general' },
  { question: 'Je n\'ai jamais enterré un animal.', category: 'general' },
  { question: 'Je n\'ai jamais été à un enterrement et ri au mauvais moment.', category: 'funny' },
  { question: 'Je n\'ai jamais pris la parole à un enterrement.', category: 'general' },
  { question: 'Je n\'ai jamais visité la tombe de quelqu\'un que je connaissais.', category: 'general' },
  { question: 'Je n\'ai jamais eu une expérience de mort imminente et réfléchi à ma vie.', category: 'risky' },
  { question: 'Je n\'ai jamais fait une bucket list.', category: 'general' },
  { question: 'Je n\'ai jamais coché quelque chose sur ma bucket list.', category: 'general' },
  { question: 'Je n\'ai jamais essayé d\'apprendre une langue et abandonné.', category: 'general' },
  { question: 'Je n\'ai jamais appris à jouer d\'un instrument.', category: 'general' },
  { question: 'Je n\'ai jamais essayé d\'apprendre un instrument et arrêté.', category: 'general' },
  { question: 'Je n\'ai jamais écrit une chanson ou un poème.', category: 'general' },
  { question: 'Je n\'ai jamais peint ou dessiné quelque chose dont j\'étais fier.', category: 'general' },
  { question: 'Je n\'ai jamais essayé de cuisiner un plat fancy et raté.', category: 'food' },
  { question: 'Je n\'ai jamais fait une pâtisserie from scratch.', category: 'food' },
  { question: 'Je n\'ai jamais brûlé quelque chose que je cuisinais.', category: 'food' },
  { question: 'Je n\'ai jamais essayé un régime et arrêté après une semaine.', category: 'food' },
  { question: 'Je n\'ai jamais été végétarien ou végan.', category: 'food' },
  { question: 'Je n\'ai jamais essayé une tendance food comme le kale ou le toast avocat.', category: 'food' },
  { question: 'Je n\'ai jamais mangé quelque chose que j\'ai cultivé.', category: 'food' },
  { question: 'Je n\'ai jamais été au marché des producteurs.', category: 'food' },
  { question: 'Je n\'ai jamais été dans un resto fancy et me suis senti sous-habillé.', category: 'food' },
  { question: 'Je n\'ai jamais renvoyé un plat au restaurant.', category: 'food' },
  { question: 'Je n\'ai jamais parti sans laisser de pourboire.', category: 'food' },
  { question: 'Je n\'ai jamais disputé pour l\'addition.', category: 'relationships' },
  { question: 'Je n\'ai jamais fait un régime avec un ami.', category: 'relationships' },
  { question: 'Je n\'ai jamais rivalisé avec un ami pour un truc bête.', category: 'relationships' },
  { question: 'Je n\'ai jamais eu une poignée de main secrète avec quelqu\'un.', category: 'childhood' },
  { question: 'Je n\'ai jamais eu un ami imaginaire.', category: 'childhood' },
  { question: 'Je n\'ai jamais cru au Père Noël après 10 ans.', category: 'childhood' },
  { question: 'Je n\'ai jamais mis une dent sous l\'oreiller pour la petite souris.', category: 'childhood' },
  { question: 'Je n\'ai jamais eu peur des clowns.', category: 'general' },
  { question: 'Je n\'ai jamais été au cirque.', category: 'general' },
  { question: 'Je n\'ai jamais été au zoo et eu de la peine pour les animaux.', category: 'general' },
  { question: 'Je n\'ai jamais fait du cheval.', category: 'general' },
  { question: 'Je n\'ai jamais été piqué par un insecte et eu une mauvaise réaction.', category: 'general' },
  { question: 'Je n\'ai jamais eu peur des araignées ou insectes.', category: 'general' },
  { question: 'Je n\'ai jamais tué une araignée pour quelqu\'un.', category: 'general' },
  { question: 'Je n\'ai jamais sauvé un animal.', category: 'general' },
  { question: 'Je n\'ai jamais adopté un animal en refuge.', category: 'general' },
  { question: 'Je n\'ai jamais perdu un animal.', category: 'general' },
  { question: 'Je n\'ai jamais eu un animal qui s\'est enfui.', category: 'general' },
  { question: 'Je n\'ai jamais menti être occupé pour me décommander.', category: 'general' },
  { question: 'Je n\'ai jamais fait semblant d\'aimer une chanson quand quelqu\'un la passait.', category: 'funny' },
  { question: 'Je n\'ai jamais dit "j\'arrive" quand je n\'étais pas parti.', category: 'funny' },
  { question: 'Je n\'ai jamais lu le journal intime de quelqu\'un.', category: 'relationships' },
  { question: 'Je n\'ai jamais eu un surnom que je me suis donné.', category: 'funny' },
  { question: 'Je n\'ai jamais été la cinquième roue du carrosse à un rencard.', category: 'relationships' },
  { question: 'Je n\'ai jamais liké par erreur le post d\'un ex.', category: 'funny' },
  { question: 'Je n\'ai jamais resté dans une relation plus longtemps que je n\'aurais dû.', category: 'relationships' },
  { question: 'Je n\'ai jamais rêvé de quelqu\'un et me suis senti bizarre avec lui le lendemain.', category: 'general' },
  { question: 'Je n\'ai jamais revu une série plus de cinq fois.', category: 'general' },
  { question: 'Je n\'ai jamais pleuré devant une pub.', category: 'funny' },
  { question: 'Je n\'ai jamais parlé tout seul devant le miroir.', category: 'funny' },
  { question: 'Je n\'ai jamais répété une conversation avant qu\'elle ait lieu.', category: 'general' },
  { question: 'Je n\'ai jamais eu peur de regarder mon solde bancaire.', category: 'general' },
  { question: 'Je n\'ai jamais acheté quelque chose que je ne pouvais pas me permettre.', category: 'general' },
  { question: 'Je n\'ai jamais rendu un cadeau.', category: 'relationships' },
  { question: 'Je n\'ai jamais oublié l\'anniversaire d\'un ami proche.', category: 'relationships' },
  { question: 'Je n\'ai jamais été en retard à mon propre événement.', category: 'funny' },
  { question: 'Je n\'ai jamais mélangé deux noms dans la même phrase.', category: 'funny' },
  { question: 'Je n\'ai jamais dit "à demain" à quelqu\'un que je savais ne pas revoir.', category: 'funny' },
  { question: 'Je n\'ai jamais fait semblant de comprendre une blague et ri quand même.', category: 'funny' },
  { question: 'Je n\'ai jamais acquiescé dans une conversation que je ne suivais pas.', category: 'funny' },
  { question: 'Je n\'ai jamais été pris en train de chanter en voiture à un feu rouge.', category: 'funny' },
  { question: 'Je n\'ai jamais eu un crush pour un personnage de fiction.', category: 'general' },
  { question: 'Je n\'ai jamais écrit une lettre que je n\'ai pas envoyée.', category: 'general' },
  { question: 'Je n\'ai jamais essayé de réparer quelque chose et empiré.', category: 'funny' },
  { question: 'Je n\'ai jamais rejeté la faute sur quelqu\'un d\'autre pour ce que j\'ai fait.', category: 'relationships' },
  { question: 'Je n\'ai jamais récupéré le mérite de l\'idée de quelqu\'un.', category: 'work' },
  { question: 'Je n\'ai jamais été pris dans un mensonge blanc.', category: 'funny' },
  { question: 'Je n\'ai jamais enjolivé une histoire pour la rendre plus intéressante.', category: 'general' },
  { question: 'Je n\'ai jamais été jaloux du succès d\'un ami.', category: 'relationships' },
  { question: 'Je n\'ai jamais me suis comparé à quelqu\'un sur les réseaux et me suis senti mal.', category: 'general' },
  { question: 'Je n\'ai jamais supprimé une photo à cause de mon apparence.', category: 'general' },
  { question: 'Je n\'ai jamais été stressé avant un entretien d\'embauche.', category: 'work' },
  { question: 'Je n\'ai jamais raté mon premier jour dans un nouveau job.', category: 'work' },
  { question: 'Je n\'ai jamais dormi pendant un film au cinéma.', category: 'funny' },
  { question: 'Je n\'ai jamais eu une intoxication alimentaire.', category: 'food' },
  { question: 'Je n\'ai jamais essayé d\'impressionner quelqu\'un avec un talent que je n\'ai pas.', category: 'general' },
  { question: 'Je n\'ai jamais été pris en train de faire quelque chose de gênant à la caméra.', category: 'funny' },
  { question: 'Je n\'ai jamais eu une phase dont j\'ai honte maintenant.', category: 'general' },
  { question: 'Je n\'ai jamais porté un vêtement clairement trop petit ou trop grand.', category: 'funny' },
  { question: 'Je n\'ai jamais mal réagi à une coupe et menti que ça me plaisait.', category: 'funny' },
  { question: 'Je n\'ai jamais passé plus de 10 minutes à essayer de prendre un bon selfie.', category: 'funny' },
  { question: 'Je n\'ai jamais été celui qui a ruiné la photo de groupe.', category: 'funny' },
  { question: 'Je n\'ai jamais oublié ce que je disais au milieu d\'une phrase.', category: 'funny' },
  { question: 'Je n\'ai jamais appelé un prof "maman" ou "papa" par erreur.', category: 'childhood' },
  { question: 'Je n\'ai jamais marché avec assurance dans la mauvaise direction.', category: 'funny' },
  { question: 'Je n\'ai jamais essayé d\'ouvrir une porte "tirer" en poussant.', category: 'funny' },
  { question: 'Je n\'ai jamais dit "merci" quand quelqu\'un a dit "désolé".', category: 'funny' },
  { question: 'Je n\'ai jamais fait signe à un bébé puis réalisé que c\'était une poupée.', category: 'funny' },
  { question: 'Je n\'ai jamais eu peur du noir adulte.', category: 'general' },
  { question: 'Je n\'ai jamais dormi avec une peluche adulte.', category: 'general' },
  { question: 'Je n\'ai jamais eu un porte-bonheur ou une superstition.', category: 'general' },
  { question: 'Je n\'ai jamais fait un vœu sur une étoile filante.', category: 'general' },
  { question: 'Je n\'ai jamais cassé un miroir et m\'être inquiété du mauvais sort.', category: 'general' },
  { question: 'Je n\'ai jamais passé sous une échelle.', category: 'general' },
  { question: 'Je n\'ai jamais été chez une voyante.', category: 'general' },
  { question: 'Je n\'ai jamais essayé de faire des rêves lucides.', category: 'general' },
  { question: 'Je n\'ai jamais eu une paralysie du sommeil.', category: 'general' },
  { question: 'Je n\'ai jamais me suis réveillé sans savoir où j\'étais un instant.', category: 'general' },
  { question: 'Je n\'ai jamais fait la grasse mat\' sur le réveil et raté quelque chose d\'important.', category: 'funny' },
  { question: 'Je n\'ai jamais appuyé sur snooze plus de trois fois d\'affilée.', category: 'funny' },
  { question: 'Je n\'ai jamais eu une conversation en dormant que quelqu\'un a entendue.', category: 'funny' },
  { question: 'Je n\'ai jamais été réveillé par mon propre ronflement.', category: 'funny' },
  { question: 'Je n\'ai jamais dormi dans une bibliothèque.', category: 'general' },
  { question: 'Je n\'ai jamais passé une nuit blanche pour autre chose que le travail ou l\'école.', category: 'general' },
  { question: 'Je n\'ai jamais fait une sieste qui s\'est transformée en nuit complète.', category: 'funny' },
  { question: 'Je n\'ai jamais été dans un bar karaoké sans chanter.', category: 'general' },
  { question: 'Je n\'ai jamais fait du karaoké et oublié les paroles.', category: 'funny' },
  { question: 'Je n\'ai jamais été à un spectacle d\'humour et été la cible du comique.', category: 'funny' },
  { question: 'Je n\'ai jamais été dans un parc d\'attractions et été malade dans une attraction.', category: 'travel' },
  { question: 'Je n\'ai jamais perdu mes bagages en voyage.', category: 'travel' },
  { question: 'Je n\'ai jamais eu un vol retardé de plus de 5 heures.', category: 'travel' },
  { question: 'Je n\'ai jamais été à côté de quelqu\'un de pénible en long courrier.', category: 'travel' },
  { question: 'Je n\'ai jamais été dans un pays dont je ne parlais pas la langue.', category: 'travel' },
  { question: 'Je n\'ai jamais rapporté un souvenir qui s\'est cassé avant d\'arriver.', category: 'travel' },
  { question: 'Je n\'ai jamais pris une photo avec un inconnu en voyage.', category: 'travel' },
  { question: 'Je n\'ai jamais fait un tatouage que j\'ai regretté ensuite.', category: 'general' },
  { question: 'Je n\'ai jamais eu un piercing qui s\'est infecté.', category: 'general' },
  { question: 'Je n\'ai jamais essayé de me teindre les cheveux à la maison et raté.', category: 'funny' },
  { question: 'Je n\'ai jamais eu une phase mode dont je suis content que ce soit fini.', category: 'general' },
  { question: 'Je n\'ai jamais porté un vêtement du rayon du sexe opposé.', category: 'general' },
  { question: 'Je n\'ai jamais acheté la même tenue en plusieurs couleurs.', category: 'general' },
  { question: 'Je n\'ai jamais perdu mes clés et dû m\'introduire chez moi.', category: 'funny' },
  { question: 'Je n\'ai jamais été enfermé dehors chez moi ou dans ma voiture.', category: 'funny' },
  { question: 'Je n\'ai jamais oublié où j\'avais garé ma voiture.', category: 'funny' },
  { question: 'Je n\'ai jamais été en panne d\'essence sur la route.', category: 'general' },
  { question: 'Je n\'ai jamais eu une crevaison.', category: 'general' },
  { question: 'Je n\'ai jamais été dans une voiture en panne au milieu de nulle part.', category: 'travel' },
  { question: 'Je n\'ai jamais aidé un inconnu avec sa voiture.', category: 'general' },
  { question: 'Je n\'ai jamais donné de l\'argent à un inconnu dans la rue.', category: 'general' },
  { question: 'Je n\'ai jamais été bénévole pour une cause qui me tient à cœur.', category: 'general' },
  { question: 'Je n\'ai jamais donné à une association.', category: 'general' },
  { question: 'Je n\'ai jamais couru une course de 5 km ou plus.', category: 'general' },
  { question: 'Je n\'ai jamais pris un abo salle et arrêté d\'y aller après un mois.', category: 'general' },
  { question: 'Je n\'ai jamais essayé un sport et arrêté parce que j\'étais nul.', category: 'general' },
  { question: 'Je n\'ai jamais été à un match en direct.', category: 'general' },
  { question: 'Je n\'ai jamais pleuré pour un match.', category: 'general' },
  { question: 'Je n\'ai jamais me suis peint le visage pour un match ou un événement.', category: 'general' },
  { question: 'Je n\'ai jamais été à une manifestation ou un rassemblement.', category: 'general' },
  { question: 'Je n\'ai jamais écrit un avis en ligne.', category: 'general' },
  { question: 'Je n\'ai jamais disputé avec un inconnu dans les commentaires.', category: 'funny' },
  { question: 'Je n\'ai jamais supprimé un commentaire à cause du backlash.', category: 'funny' },
  { question: 'Je n\'ai jamais été bloqué par quelqu\'un que je connais.', category: 'relationships' },
  { question: 'Je n\'ai jamais eu un secret trop gros à garder.', category: 'relationships' },
  { question: 'Je n\'ai jamais raconté le secret d\'un ami à quelqu\'un d\'autre.', category: 'relationships' },
  { question: 'Je n\'ai jamais été pris en mensonge par quelqu\'un qui comptait pour moi.', category: 'relationships' },
  { question: 'Je n\'ai jamais présenté des excuses des années après pour quelque chose que j\'ai fait.', category: 'relationships' },
  { question: 'Je n\'ai jamais renoué avec un ex juste pour prendre des nouvelles.', category: 'relationships' },
  { question: 'Je n\'ai jamais eu le béguin pour mon meilleur ami.', category: 'relationships' },
  { question: 'Je n\'ai jamais été à un rencard blind qui s\'est mal passé.', category: 'relationships' },
  { question: 'Je n\'ai jamais été celui qui a mis fin à une amitié.', category: 'relationships' },
  { question: 'Je n\'ai jamais me suis fait un ami en faisant la queue.', category: 'general' },
  { question: 'Je n\'ai jamais eu un voisin avec qui je suis devenu ami.', category: 'relationships' },
  { question: 'Je n\'ai jamais été à une réunion et l\'avoir regretté.', category: 'relationships' },
  { question: 'Je n\'ai jamais oublié le nom d\'un ami en le présentant.', category: 'funny' },
  { question: 'Je n\'ai jamais confondu les noms de deux amis.', category: 'funny' },
  { question: 'Je n\'ai jamais eu un groupe qui s\'est tu après un message.', category: 'funny' },
  { question: 'Je n\'ai jamais laissé un message "lu" plus d\'un jour.', category: 'relationships' },
  { question: 'Je n\'ai jamais fait semblant d\'avoir une mauvaise connexion pour raccrocher.', category: 'funny' },
  { question: 'Je n\'ai jamais dit "je dois y aller" quand ce n\'était pas vrai.', category: 'funny' },
  { question: 'Je n\'ai jamais été à une fête où je ne connaissais personne.', category: 'general' },
  { question: 'Je n\'ai jamais été le dernier à partir d\'une fête.', category: 'general' },
  { question: 'Je n\'ai jamais organisé une fête qui a dérapé.', category: 'general' },
  { question: 'Je n\'ai jamais nettoyé après la fête de quelqu\'un d\'autre.', category: 'general' },
  { question: 'Je n\'ai jamais eu un coloc avec qui je ne m\'entendais pas.', category: 'relationships' },
  { question: 'Je n\'ai jamais eu une fête surprise organisée pour moi.', category: 'general' },
  { question: 'Je n\'ai jamais gâché une surprise.', category: 'funny' },
  { question: 'Je n\'ai jamais oublié un anniversaire.', category: 'relationships' },
  { question: 'Je n\'ai jamais fait une scène à un repas de famille.', category: 'relationships' },
  { question: 'Je n\'ai jamais eu un membre de la famille que j\'évite les fêtes.', category: 'relationships' },
  { question: 'Je n\'ai jamais menti à ma famille sur où j\'allais.', category: 'childhood' },
  { question: 'Je n\'ai jamais fait entrer quelqu\'un en douce chez moi.', category: 'childhood' },
  { question: 'Je n\'ai jamais été pris en train de faire quelque chose que je n\'aurais pas dû.', category: 'general' },
];
