module.exports = [
  { question: 'Non ho mai mentito sulla mia età.', category: 'general' },
  { question: 'Non ho mai finto di essere al telefono per evitare qualcuno.', category: 'funny' },
  { question: 'Non ho mai cantato sotto la doccia.', category: 'general' },
  { question: 'Non ho mai ballato quando nessuno mi guardava.', category: 'general' },
  { question: 'Non ho mai pianto durante un film.', category: 'general' },
  { question: 'Non ho mai inviato un messaggio alla persona sbagliata.', category: 'funny' },
  { question: 'Non ho mai dimenticato il nome di qualcuno subito dopo che si era presentato.', category: 'funny' },
  { question: 'Non ho mai salutato con la mano qualcuno che non stava salutando me.', category: 'funny' },
  { question: 'Non ho mai dato la colpa al cane per qualcosa che ho fatto io.', category: 'funny' },
  { question: 'Non ho mai cercato il mio nome su Google.', category: 'general' },
  { question: 'Non ho mai passato tutta la notte a guardare una serie TV.', category: 'general' },
  { question: 'Non ho mai mangiato cibo caduto per terra.', category: 'food' },
  { question: 'Non ho mai fatto passare uno starnuto per un colpo di tosse.', category: 'funny' },
  { question: 'Non ho mai finto di lavorare mentre navigavo su internet.', category: 'work' },
  { question: 'Non ho mai ripensato a una conversazione nella mia testa sentendomi in imbarazzo.', category: 'general' },
  { question: 'Non ho mai avuto una cotta per un insegnante.', category: 'childhood' },
  { question: 'Non sono mai stato beccato mentre mi guardavo allo specchio.', category: 'funny' },
  { question: 'Non ho mai riso così forte da piangere.', category: 'general' },
  { question: 'Non ho mai entrato in una stanza dimenticando perché ci andavo.', category: 'funny' },
  { question: 'Non ho mai dato la colpa alla tecnologia per un mio errore.', category: 'funny' },
  { question: 'Non ho mai viaggiato da solo in un altro paese.', category: 'travel' },
  { question: 'Non ho mai perso un aereo o un treno.', category: 'travel' },
  { question: 'Non mi sono mai perso in una città straniera.', category: 'travel' },
  { question: 'Non ho mai provato un cibo che mi faceva paura provare.', category: 'food' },
  { question: 'Non ho mai mangiato qualcosa scaduta.', category: 'food' },
  { question: 'Non ho mai ordinato sempre la stessa cosa al ristorante.', category: 'food' },
  { question: 'Non ho mai mangiato il dolce prima della cena.', category: 'food' },
  { question: 'Non ho mai mentito sul mio curriculum.', category: 'work' },
  { question: 'Non ho mai chiamato malato quando non lo ero.', category: 'work' },
  { question: 'Non mi sono mai addormentato in una riunione o a lezione.', category: 'work' },
  { question: 'Non ho mai avuto una cotta per un collega.', category: 'work' },
  { question: 'Non sono mai arrivato in ritardo a un evento importante.', category: 'general' },
  { question: 'Non ho mai rotto qualcosa a casa di un amico senza dirglielo.', category: 'relationships' },
  { question: 'Non ho mai avuto un ammiratore segreto.', category: 'relationships' },
  { question: 'Non sono mai stato nella friendzone.', category: 'relationships' },
  { question: 'Non ho mai avuto un avventura di una notte.', category: 'risky' },
  { question: 'Non ho mai baciato uno sconosciuto.', category: 'risky' },
  { question: 'Non mi sono mai fatto un tatuaggio.', category: 'general' },
  { question: 'Non mi sono mai fatto un piercing da nessuna parte tranne le orecchie.', category: 'general' },
  { question: 'Non mi sono mai tinto i capelli di un colore pazzo.', category: 'general' },
  { question: 'Non sono mai stato a un concerto.', category: 'general' },
  { question: 'Non sono mai stato a un festival musicale.', category: 'general' },
  { question: 'Non ho mai incontrato una celebrità.', category: 'general' },
  { question: 'Non sono mai stato in TV o in un video virale.', category: 'general' },
  { question: 'Non ho mai corso una maratona o mezza maratona.', category: 'general' },
  { question: 'Non ho mai fatto paracadutismo o bungee jumping.', category: 'risky' },
  { question: 'Non sono mai stato sulle montagne russe.', category: 'general' },
  { question: 'Non ho mai nuotato nell\'oceano di notte.', category: 'travel' },
  { question: 'Non ho mai campeggiato nella natura.', category: 'travel' },
  { question: 'Non ho mai fatto l\'autostop.', category: 'risky' },
  { question: 'Non ho mai dormito in aeroporto.', category: 'travel' },
  { question: 'Non sono mai stato in più di 10 paesi.', category: 'travel' },
  { question: 'Non ho mai imparato a parlare fluentemente un\'altra lingua.', category: 'general' },
  { question: 'Non ho mai vissuto in un altro paese.', category: 'travel' },
  { question: 'Non ho mai avuto un amico di penna da un altro paese.', category: 'childhood' },
  { question: 'Non sono mai stato a un matrimonio.', category: 'relationships' },
  { question: 'Non sono mai stato a un funerale.', category: 'general' },
  { question: 'Non sono mai stato in una rissa.', category: 'risky' },
  { question: 'Non sono mai stato fermato dalla polizia.', category: 'risky' },
  { question: 'Non sono mai stato in un casinò.', category: 'risky' },
  { question: 'Non ho mai scommesso soldi che non potevo permettermi di perdere.', category: 'risky' },
  { question: 'Non mi sono mai rotto un osso.', category: 'general' },
  { question: 'Non ho mai avuto punti di sutura.', category: 'general' },
  { question: 'Non sono mai svenuto.', category: 'general' },
  { question: 'Non ho mai passato una notte in ospedale.', category: 'general' },
  { question: 'Non sono mai stato al pronto soccorso.', category: 'general' },
  { question: 'Non ho mai avuto un\'esperienza di pre-morte.', category: 'risky' },
  { question: 'Non ho mai salvato la vita a qualcuno.', category: 'general' },
  { question: 'Non ho mai avuto un incidente d\'auto.', category: 'general' },
  { question: 'Non ho mai preso una multa per eccesso di velocità.', category: 'risky' },
  { question: 'Non ho mai guidato la moto.', category: 'general' },
  { question: 'Non ho mai fatto immersioni subacquee.', category: 'travel' },
  { question: 'Non ho mai provato il surf.', category: 'general' },
  { question: 'Non ho mai sciato o fatto snowboard.', category: 'general' },
  { question: 'Non ho mai scalato una montagna.', category: 'travel' },
  { question: 'Non sono mai stato in crociera.', category: 'travel' },
  { question: 'Non sono mai stato su una barca in mezzo all\'oceano.', category: 'travel' },
  { question: 'Non ho mai visto l\'aurora boreale.', category: 'travel' },
  { question: 'Non ho mai visto un animale selvatico da vicino.', category: 'travel' },
  { question: 'Non sono mai stato morso da un animale.', category: 'general' },
  { question: 'Non ho mai avuto un animale che non fosse un gatto o un cane.', category: 'general' },
  { question: 'Non ho mai rubato nulla.', category: 'risky' },
  { question: 'Non sono mai stato arrestato o fermato.', category: 'risky' },
  { question: 'Non sono mai stato in un locale di strip-tease.', category: 'risky' },
  { question: 'Non ho mai fatto il bagno nudo.', category: 'risky' },
  { question: 'Non sono mai stato nudo in pubblico.', category: 'risky' },
  { question: 'Non ho mai avuto un inconveniente con i vestiti in pubblico.', category: 'funny' },
  { question: 'Non ho mai beccato qualcuno in bagno.', category: 'funny' },
  { question: 'Non sono mai stato beccato in bagno.', category: 'funny' },
  { question: 'Non ho mai sognato qualcuno in questa stanza.', category: 'risky' },
  { question: 'Non ho mai avuto una cotta per l\'ex di un amico.', category: 'relationships' },
  { question: 'Non ho mai frequentato due persone contemporaneamente.', category: 'relationships' },
  { question: 'Non sono mai stato a un appuntamento al buio.', category: 'relationships' },
  { question: 'Non sono mai stato catfisato o ingannato online.', category: 'relationships' },
  { question: 'Non ho mai scritto in DM a qualcuno.', category: 'relationships' },
  { question: 'Non ho mai avuto amore a prima vista.', category: 'relationships' },
  { question: 'Non ho mai avuto una relazione a distanza.', category: 'relationships' },
  { question: 'Non sono mai tornato insieme a un ex.', category: 'relationships' },
  { question: 'Non sono mai stato ghostato.', category: 'relationships' },
  { question: 'Non ho mai ghostato qualcuno.', category: 'relationships' },
  { question: 'Non ho mai avuto una cotta non corrisposta per più di un anno.', category: 'relationships' },
  { question: 'Non ho mai scritto una lettera d\'amore.', category: 'relationships' },
  { question: 'Non ho mai ricevuto né dato una serenata.', category: 'relationships' },
  { question: 'Non ho mai fatto una battaglia di cibo.', category: 'childhood' },
  { question: 'Non sono mai stato mandato dal preside.', category: 'childhood' },
  { question: 'Non ho mai copiato a un compito.', category: 'childhood' },
  { question: 'Non sono mai stato sospeso o espulso da scuola.', category: 'childhood' },
  { question: 'Non ho mai passato una notte in bianco per la scuola.', category: 'childhood' },
  { question: 'Non ho mai avuto un documento falso.', category: 'risky' },
  { question: 'Non sono mai uscito di nascosto di casa da adolescente.', category: 'childhood' },
  { question: 'Non ho mai fatto una festa quando i miei genitori non c\'erano.', category: 'childhood' },
  { question: 'Non ho mai rotto una finestra o qualcosa di valore a casa.', category: 'childhood' },
  { question: 'Non sono mai stato punito per più di una settimana.', category: 'childhood' },
  { question: 'Non ho mai mentito ai miei genitori su dove ero.', category: 'childhood' },
  { question: 'Non ho mai avuto un diario che qualcuno ha letto.', category: 'childhood' },
  { question: 'Non ho mai partecipato a uno spettacolo scolastico o a un talent show.', category: 'childhood' },
  { question: 'Non sono mai stato l\'ultimo scelto per una squadra.', category: 'childhood' },
  { question: 'Non sono mai stato bullizzato né ho bullizzato qualcuno.', category: 'childhood' },
  { question: 'Non ho mai avuto un soprannome che odiavo.', category: 'funny' },
  { question: 'Non sono mai stato photobombato né ho photobombato qualcuno.', category: 'funny' },
  { question: 'Non ho mai fatto un selfie e cancellato subito.', category: 'funny' },
  { question: 'Non ho mai postato qualcosa e cancellato entro un\'ora.', category: 'funny' },
  { question: 'Non ho mai litigato con uno sconosciuto su internet.', category: 'funny' },
  { question: 'Non ho mai commentato per sbaglio un vecchio post.', category: 'funny' },
  { question: 'Non ho mai messo like al mio stesso post o alla mia foto.', category: 'funny' },
  { question: 'Non ho mai messo like per sbaglio a una vecchia foto di qualcuno.', category: 'funny' },
  { question: 'Non sono mai stato bloccato da qualcuno sui social.', category: 'relationships' },
  { question: 'Non ho mai bloccato qualcuno che conosco nella vita reale.', category: 'relationships' },
  { question: 'Non ho mai avuto più di 1000 follower su nessuna piattaforma.', category: 'general' },
  { question: 'Non sono mai diventato virale per qualcosa di imbarazzante.', category: 'funny' },
  { question: 'Non ho mai provato a cucinare e fallito miseramente.', category: 'food' },
  { question: 'Non ho mai fatto scattare l\'allarme antincendio cucinando.', category: 'food' },
  { question: 'Non ho mai ordinato pizza più di due volte in una settimana.', category: 'food' },
  { question: 'Non ho mai mangiato una pizza intera da solo.', category: 'food' },
  { question: 'Non ho mai mangiato qualcosa di crudo che doveva essere cotto.', category: 'food' },
  { question: 'Non ho mai provato una combinazione di cibi strana.', category: 'food' },
  { question: 'Non sono mai stato in un all-you-can-eat e mi sono sentito male.', category: 'food' },
  { question: 'Non ho mai rubato cibo a un coinquilino o familiare.', category: 'food' },
  { question: 'Non ho mai mangiato la colazione a cena.', category: 'food' },
  { question: 'Non ho mai avuto una dipendenza dalla caffeina.', category: 'food' },
  { question: 'Non ho mai provato le bevande energetiche per restare sveglio.', category: 'food' },
  { question: 'Non sono mai andato al drive-through del fast food in pigiama.', category: 'funny' },
  { question: 'Non ho mai pianto per latte versato o cibo caduto.', category: 'funny' },
  { question: 'Non ho mai finto di gradire un regalo ricevuto.', category: 'relationships' },
  { question: 'Non ho mai rigirato un regalo.', category: 'relationships' },
  { question: 'Non ho mai dimenticato il compleanno di un amico stretto o di un familiare.', category: 'relationships' },
  { question: 'Non sono mai arrivato a una festa nel giorno sbagliato.', category: 'funny' },
  { question: 'Non sono mai stato l\'unico in costume.', category: 'funny' },
  { question: 'Non mi sono mai addormentato a una festa.', category: 'funny' },
  { question: 'Non sono mai stato il guidatore designato e l\'ho odiato.', category: 'general' },
  { question: 'Non ho mai perso il cellulare e andato in panico.', category: 'funny' },
  { question: 'Non ho mai lasciato il cellulare a casa e sentirmi nudo.', category: 'funny' },
  { question: 'Non mi è mai caduto il cellulare nel water.', category: 'funny' },
  { question: 'Non ho mai rotto lo schermo del cellulare.', category: 'general' },
  { question: 'Non ho mai usato il cellulare di qualcuno senza chiedere.', category: 'relationships' },
  { question: 'Non ho mai guardato i messaggi di qualcun altro.', category: 'relationships' },
  { question: 'Non sono mai stato beccato a guardare il cellulare di qualcuno.', category: 'funny' },
  { question: 'Non ho mai avuto una password che era "password" o "123456".', category: 'funny' },
  { question: 'Non ho mai dimenticato una password importante.', category: 'funny' },
  { question: 'Non ho mai risposto "anche a te" quando qualcuno diceva "buon film" o simile.', category: 'funny' },
  { question: 'Non ho mai detto "ciao" due volte nella stessa conversazione.', category: 'funny' },
  { question: 'Non sono mai inciampato in pubblico.', category: 'funny' },
  { question: 'Non ho mai salutato uno sconosciuto pensando di conoscerlo.', category: 'funny' },
  { question: 'Non ho mai provato ad aprire una porta a spinta tirando.', category: 'funny' },
  { question: 'Non sono mai andato contro una porta di vetro.', category: 'funny' },
  { question: 'Non ho mai perso uno scalino e inciampato.', category: 'funny' },
  { question: 'Non ho mai avuto una videochiamata e dimenticato che la telecamera era accesa.', category: 'work' },
  { question: 'Non sono mai stato in una riunione senza capire di cosa si parlava.', category: 'work' },
  { question: 'Non ho mai fatto un pisolino durante l\'orario di lavoro.', category: 'work' },
  { question: 'Non ho mai avuto un lavoro che odiavo.', category: 'work' },
  { question: 'Non ho mai lasciato un lavoro senza averne un altro.', category: 'work' },
  { question: 'Non sono mai stato licenziato.', category: 'work' },
  { question: 'Non sono mai stato promosso.', category: 'work' },
  { question: 'Non ho mai avuto una rivalità con un collega.', category: 'work' },
  { question: 'Non ho mai frequentato un collega.', category: 'work' },
  { question: 'Non ho mai avuto una cotta per una celebrità.', category: 'general' },
  { question: 'Non ho mai scritto fan mail o mandato DM a una celebrità.', category: 'general' },
  { question: 'Non ho mai pianto per una rottura tra celebrità.', category: 'funny' },
  { question: 'Non sono mai stato a una prima di mezzanotte.', category: 'general' },
  { question: 'Non mi sono mai travestito da personaggio per l\'uscita di un film.', category: 'funny' },
  { question: 'Non ho mai rivisto lo stesso film più di 10 volte.', category: 'general' },
  { question: 'Non mi sono mai addormentato al cinema.', category: 'funny' },
  { question: 'Non sono mai stato a un concerto senza conoscere nessuna canzone.', category: 'funny' },
  { question: 'Non ho mai cantato al karaoke.', category: 'general' },
  { question: 'Non ho mai ballato su un tavolo.', category: 'risky' },
  { question: 'Non ho mai fatto una scena in pubblico.', category: 'funny' },
  { question: 'Non sono mai stato cacciato da un locale.', category: 'risky' },
  { question: 'Non ho mai avuto un quasi-incidente con la legge.', category: 'risky' },
  { question: 'Non ho mai aiutato qualcuno a nascondere qualcosa ai genitori.', category: 'relationships' },
  { question: 'Non ho mai tenuto un segreto davvero difficile da tenere.', category: 'relationships' },
  { question: 'Non ho mai rivelato per sbaglio un segreto.', category: 'relationships' },
  { question: 'Non sono mai stato tradito da un amico.', category: 'relationships' },
  { question: 'Non ho mai tradito la fiducia di un amico.', category: 'relationships' },
  { question: 'Non ho mai litigato con il mio migliore amico.', category: 'relationships' },
  { question: 'Non mi sono mai rimesso in contatto con un vecchio amico dopo anni.', category: 'relationships' },
  { question: 'Non sono mai stato a una riunione di ex compagni di scuola.', category: 'relationships' },
  { question: 'Non ho mai avuto un coinquilino che non sopportavo.', category: 'relationships' },
  { question: 'Non ho mai avuto un vicino che non sopportavo.', category: 'relationships' },
  { question: 'Non ho mai criticato qualcuno che era nella stessa stanza.', category: 'funny' },
  { question: 'Non sono mai stato beccato a parlare di qualcuno.', category: 'funny' },
  { question: 'Non ho mai riso nel momento sbagliato.', category: 'funny' },
  { question: 'Non ho mai scoreggiato in pubblico fingendo che non fossi io.', category: 'funny' },
  { question: 'Non ho mai avuto un inconveniente con i vestiti.', category: 'funny' },
  { question: 'Non ho mai indossato lo stesso outfit due giorni di fila al lavoro o a scuola.', category: 'general' },
  { question: 'Non ho mai indossato i vestiti al rovescio per sbaglio.', category: 'funny' },
  { question: 'Non ho mai indossato due scarpe diverse.', category: 'funny' },
  { question: 'Non sono mai uscito di casa senza pantaloni o in pigiama.', category: 'funny' },
  { question: 'Non ho mai avuto un taglio di capelli brutto e pianto.', category: 'funny' },
  { question: 'Non mi sono mai tagliato i capelli da solo.', category: 'general' },
  { question: 'Non ho mai provato a tagliarmi la frangia da solo.', category: 'funny' },
  { question: 'Non ho mai fatto la permanente.', category: 'general' },
  { question: 'Non mi sono mai scottato così tanto al sole da non dormire.', category: 'travel' },
  { question: 'Non mi sono mai perso in un negozio da bambino.', category: 'childhood' },
  { question: 'Non ho mai avuto paura del buio da adulto.', category: 'general' },
  { question: 'Non ho mai avuto un incubo ricorrente.', category: 'general' },
  { question: 'Non ho mai fatto sonnambulismo o parlato nel sonno.', category: 'general' },
  { question: 'Non ho mai fatto un sogno che sembrava reale e ha influenzato la mia giornata.', category: 'general' },
  { question: 'Non mi sono mai svegliato da un incubo e chiamato qualcuno.', category: 'general' },
  { question: 'Non ho mai creduto nei fantasmi o nel soprannaturale.', category: 'general' },
  { question: 'Non ho mai creduto di vedere un fantasma o qualcosa di paranormale.', category: 'general' },
  { question: 'Non sono mai stato in una casa o luogo infestato.', category: 'general' },
  { question: 'Non sono mai stato da un medium o lettore di tarocchi.', category: 'general' },
  { question: 'Non ho mai provato a imparare un trucco di magia.', category: 'general' },
  { question: 'Non ho mai provato a fare un backflip o una ruota e fallito.', category: 'funny' },
  { question: 'Non ho mai provato a imparare una danza TikTok o virale.', category: 'funny' },
  { question: 'Non ho mai postato un TikTok o Reel.', category: 'general' },
  { question: 'Non sono mai diventato virale sui social.', category: 'general' },
  { question: 'Non ho mai avuto una mia foto virale senza il mio consenso.', category: 'general' },
  { question: 'Non sono mai stato riconosciuto in pubblico da uno sconosciuto.', category: 'general' },
  { question: 'Non sono mai stato da solo in un parco divertimenti.', category: 'travel' },
  { question: 'Non ho mai fatto lo stesso giro 5 volte di fila.', category: 'general' },
  { question: 'Non ho mai vomitato su un\'attrazione.', category: 'funny' },
  { question: 'Non ho mai avuto paura su un\'attrazione e dovuto scendere.', category: 'general' },
  { question: 'Non ho mai provato uno sport estremo.', category: 'risky' },
  { question: 'Non mi sono mai offerto volontario per qualcosa e me ne sono pentito.', category: 'general' },
  { question: 'Non ho mai donato il sangue.', category: 'general' },
  { question: 'Non sono mai svenuto alla vista del sangue.', category: 'general' },
  { question: 'Non ho mai avuto paura degli aghi.', category: 'general' },
  { question: 'Non ho mai avuto paura di volare.', category: 'travel' },
  { question: 'Non ho mai avuto un attacco di panico.', category: 'general' },
  { question: 'Non ho mai provato meditazione o yoga.', category: 'general' },
  { question: 'Non sono mai stato in terapia o counselling.', category: 'general' },
  { question: 'Non ho mai fatto il muso a qualcuno per più di un giorno.', category: 'relationships' },
  { question: 'Non ho mai tenuto il broncio per anni.', category: 'relationships' },
  { question: 'Non mi sono mai scusato quando non avevo torto.', category: 'relationships' },
  { question: 'Non mi sono mai rifiutato di scusarmi quando avevo torto.', category: 'relationships' },
  { question: 'Non ho mai litigato in pubblico con qualcuno.', category: 'relationships' },
  { question: 'Non mi sono mai riconciliato con qualcuno dopo una grossa litigata.', category: 'relationships' },
  { question: 'Non sono mai stato a un matrimonio senza conoscere bene la coppia.', category: 'relationships' },
  { question: 'Non sono mai stato damigella o testimone di nozze.', category: 'relationships' },
  { question: 'Non ho mai preso il bouquet o la giarrettiera.', category: 'relationships' },
  { question: 'Non ho mai fatto un discorso a un matrimonio.', category: 'relationships' },
  { question: 'Non ho mai pianto a un matrimonio.', category: 'relationships' },
  { question: 'Non sono mai stato a un baby shower.', category: 'relationships' },
  { question: 'Non ho mai tenuto in braccio un neonato.', category: 'general' },
  { question: 'Non ho mai cambiato un pannolino.', category: 'general' },
  { question: 'Non ho mai fatto da babysitter.', category: 'general' },
  { question: 'Non ho mai voluto avere figli.', category: 'general' },
  { question: 'Non ho mai non voluto avere figli.', category: 'general' },
  { question: 'Non ho mai perso un animale e pianto.', category: 'general' },
  { question: 'Non ho mai seppellito un animale.', category: 'general' },
  { question: 'Non sono mai stato a un funerale e riso nel momento sbagliato.', category: 'funny' },
  { question: 'Non ho mai parlato a un funerale.', category: 'general' },
  { question: 'Non ho mai visitato la tomba di qualcuno che conoscevo.', category: 'general' },
  { question: 'Non ho mai avuto un\'esperienza di pre-morte e pensato alla mia vita.', category: 'risky' },
  { question: 'Non ho mai fatto una bucket list.', category: 'general' },
  { question: 'Non ho mai spuntato qualcosa dalla mia bucket list.', category: 'general' },
  { question: 'Non ho mai provato a imparare una nuova lingua e rinunciato.', category: 'general' },
  { question: 'Non ho mai imparato a suonare uno strumento.', category: 'general' },
  { question: 'Non ho mai provato a imparare uno strumento e smesso.', category: 'general' },
  { question: 'Non ho mai scritto una canzone o una poesia.', category: 'general' },
  { question: 'Non ho mai dipinto o disegnato qualcosa di cui fossi orgoglioso.', category: 'general' },
  { question: 'Non ho mai provato a cucinare un pasto fancy e fallito.', category: 'food' },
  { question: 'Non ho mai cucinato qualcosa from scratch.', category: 'food' },
  { question: 'Non ho mai bruciato qualcosa che stavo cucinando.', category: 'food' },
  { question: 'Non ho mai provato una dieta e smesso dopo una settimana.', category: 'food' },
  { question: 'Non sono mai stato vegetariano o vegano.', category: 'food' },
  { question: 'Non ho mai provato una tendenza food come il kale o il toast all\'avocado.', category: 'food' },
  { question: 'Non ho mai mangiato qualcosa che ho coltivato io.', category: 'food' },
  { question: 'Non sono mai stato al mercato contadino.', category: 'food' },
  { question: 'Non sono mai stato in un ristorante fancy sentendomi sotto vestito.', category: 'food' },
  { question: 'Non ho mai rimandato indietro del cibo al ristorante.', category: 'food' },
  { question: 'Non sono mai uscito senza lasciare la mancia.', category: 'food' },
  { question: 'Non ho mai litigato per il conto.', category: 'relationships' },
  { question: 'Non ho mai fatto una dieta con un amico.', category: 'relationships' },
  { question: 'Non ho mai gareggiato con un amico per qualcosa di stupido.', category: 'relationships' },
  { question: 'Non ho mai avuto una stretta di mano segreta con qualcuno.', category: 'childhood' },
  { question: 'Non ho mai avuto un amico immaginario.', category: 'childhood' },
  { question: 'Non ho mai creduto a Babbo Natale dopo i 10 anni.', category: 'childhood' },
  { question: 'Non ho mai messo un dente sotto il cuscino per la fatina dei denti.', category: 'childhood' },
  { question: 'Non ho mai avuto paura dei pagliacci.', category: 'general' },
  { question: 'Non sono mai stato al circo.', category: 'general' },
  { question: 'Non sono mai stato allo zoo sentendomi in colpa per gli animali.', category: 'general' },
  { question: 'Non ho mai cavalcato un cavallo.', category: 'general' },
  { question: 'Non sono mai stato punto da un insetto con una brutta reazione.', category: 'general' },
  { question: 'Non ho mai avuto paura dei ragni o degli insetti.', category: 'general' },
  { question: 'Non ho mai ucciso un ragno per qualcuno.', category: 'general' },
  { question: 'Non ho mai salvato un animale.', category: 'general' },
  { question: 'Non ho mai adottato un animale da un rifugio.', category: 'general' },
  { question: 'Non ho mai perso un animale.', category: 'general' },
  { question: 'Non ho mai avuto un animale che è scappato.', category: 'general' },
  { question: 'Non ho mai mentito di essere occupato per disdire dei piani.', category: 'general' },
  { question: 'Non ho mai finto di gradire una canzone quando qualcuno la metteva.', category: 'funny' },
  { question: 'Non ho mai detto "sto arrivando" quando non ero ancora partito.', category: 'funny' },
  { question: 'Non ho mai letto il diario di qualcun altro.', category: 'relationships' },
  { question: 'Non ho mai avuto un soprannome che mi sono dato io.', category: 'funny' },
  { question: 'Non sono mai stato il terzo incomodo a un appuntamento.', category: 'relationships' },
  { question: 'Non ho mai messo like per sbaglio al post di un ex.', category: 'funny' },
  { question: 'Non sono mai restato in una relazione più del dovuto.', category: 'relationships' },
  { question: 'Non ho mai sognato qualcuno e sentirmi a disagio con lui il giorno dopo.', category: 'general' },
  { question: 'Non ho mai rivisto una serie più di cinque volte.', category: 'general' },
  { question: 'Non ho mai pianto per una pubblicità.', category: 'funny' },
  { question: 'Non ho mai parlato da solo allo specchio.', category: 'funny' },
  { question: 'Non ho mai provato una conversazione prima che avvenisse.', category: 'general' },
  { question: 'Non ho mai avuto paura di controllare il saldo del conto.', category: 'general' },
  { question: 'Non ho mai comprato qualcosa che non potevo permettermi.', category: 'general' },
  { question: 'Non ho mai restituito un regalo.', category: 'relationships' },
  { question: 'Non ho mai dimenticato il compleanno di un amico stretto.', category: 'relationships' },
  { question: 'Non sono mai arrivato in ritardo al mio stesso evento.', category: 'funny' },
  { question: 'Non ho mai confuso due nomi nella stessa frase.', category: 'funny' },
  { question: 'Non ho mai detto "ci vediamo domani" a qualcuno che sapevo non avrei rivisto.', category: 'funny' },
  { question: 'Non ho mai finto di capire una battuta e riso comunque.', category: 'funny' },
  { question: 'Non ho mai annuito in una conversazione che non seguivo.', category: 'funny' },
  { question: 'Non sono mai stato beccato a cantare in macchina al semaforo.', category: 'funny' },
  { question: 'Non ho mai avuto una cotta per un personaggio di finzione.', category: 'general' },
  { question: 'Non ho mai scritto una lettera che non ho mai inviato.', category: 'general' },
  { question: 'Non ho mai provato a riparare qualcosa e peggiorato.', category: 'funny' },
  { question: 'Non ho mai dato la colpa a qualcun altro per qualcosa che ho fatto io.', category: 'relationships' },
  { question: 'Non mi sono mai preso il merito dell\'idea di qualcun altro.', category: 'work' },
  { question: 'Non sono mai stato beccato in una bugia bianca.', category: 'funny' },
  { question: 'Non ho mai esagerato una storia per renderla più interessante.', category: 'general' },
  { question: 'Non ho mai invidiato il successo di un amico.', category: 'relationships' },
  { question: 'Non mi sono mai paragonato a qualcuno sui social sentendomi male.', category: 'general' },
  { question: 'Non ho mai cancellato una foto per come apparivo.', category: 'general' },
  { question: 'Non sono mai stato nervoso prima di un colloquio.', category: 'work' },
  { question: 'Non ho mai combinato un disastro il primo giorno in un nuovo lavoro.', category: 'work' },
  { question: 'Non mi sono mai addormentato durante un film al cinema.', category: 'funny' },
  { question: 'Non ho mai avuto un\'intossicazione alimentare.', category: 'food' },
  { question: 'Non ho mai provato a impressionare qualcuno con un\'abilità che non ho.', category: 'general' },
  { question: 'Non sono mai stato beccato a fare qualcosa di imbarazzante in video.', category: 'funny' },
  { question: 'Non ho mai avuto una fase di cui mi vergogno ora.', category: 'general' },
  { question: 'Non ho mai indossato qualcosa chiaramente troppo piccolo o troppo grande.', category: 'funny' },
  { question: 'Non ho mai reagito male a un taglio di capelli e mentito che mi piaceva.', category: 'funny' },
  { question: 'Non ho mai passato più di 10 minuti a cercare di fare un buon selfie.', category: 'funny' },
  { question: 'Non sono mai stato quello che ha rovinato la foto di gruppo.', category: 'funny' },
  { question: 'Non ho mai dimenticato cosa stavo dicendo a metà frase.', category: 'funny' },
  { question: 'Non ho mai chiamato un insegnante "mamma" o "papà" per sbaglio.', category: 'childhood' },
  { question: 'Non ho mai camminato sicuro nella direzione sbagliata.', category: 'funny' },
  { question: 'Non ho mai provato ad aprire una porta "tirare" spingendo.', category: 'funny' },
  { question: 'Non ho mai detto "grazie" quando qualcuno diceva "scusa".', category: 'funny' },
  { question: 'Non ho mai salutato un bambino e poi realizzato che era una bambola.', category: 'funny' },
  { question: 'Non ho mai avuto paura del buio da adulto.', category: 'general' },
  { question: 'Non ho mai dormito con un peluche da adulto.', category: 'general' },
  { question: 'Non ho mai avuto un portafortuna o una superstizione.', category: 'general' },
  { question: 'Non ho mai espresso un desiderio su una stella cadente.', category: 'general' },
  { question: 'Non ho mai rotto uno specchio e preoccupato della sfortuna.', category: 'general' },
  { question: 'Non ho mai passato sotto una scala.', category: 'general' },
  { question: 'Non sono mai stato da una chiromante.', category: 'general' },
  { question: 'Non ho mai provato a fare sogni lucidi.', category: 'general' },
  { question: 'Non ho mai avuto la paralisi nel sonno.', category: 'general' },
  { question: 'Non mi sono mai svegliato senza sapere dove ero per un momento.', category: 'general' },
  { question: 'Non ho mai dormito oltre la sveglia e perso qualcosa di importante.', category: 'funny' },
  { question: 'Non ho mai premuto snooze più di tre volte di fila.', category: 'funny' },
  { question: 'Non ho mai avuto una conversazione nel sonno che qualcuno ha sentito.', category: 'funny' },
  { question: 'Non mi sono mai svegliato per i miei stessi russamenti.', category: 'funny' },
  { question: 'Non mi sono mai addormentato in biblioteca.', category: 'general' },
  { question: 'Non ho mai passato una notte in bianco per qualcosa che non era lavoro o scuola.', category: 'general' },
  { question: 'Non ho mai fatto un pisolino che si è trasformato in dormire tutta la notte.', category: 'funny' },
  { question: 'Non sono mai stato in un bar karaoke senza cantare.', category: 'general' },
  { question: 'Non ho mai cantato al karaoke e dimenticato le parole.', category: 'funny' },
  { question: 'Non sono mai stato a uno spettacolo comico e preso di mira dal comico.', category: 'funny' },
  { question: 'Non sono mai stato in un parco divertimenti e sentirmi male su un\'attrazione.', category: 'travel' },
  { question: 'Non ho mai perso i bagagli in viaggio.', category: 'travel' },
  { question: 'Non ho mai avuto un volo in ritardo di più di 5 ore.', category: 'travel' },
  { question: 'Non sono mai seduto accanto a qualcuno di fastidioso su un volo lungo.', category: 'travel' },
  { question: 'Non sono mai stato in un paese di cui non parlavo la lingua.', category: 'travel' },
  { question: 'Non ho mai comprato un souvenir che si è rotto prima di arrivare a casa.', category: 'travel' },
  { question: 'Non ho mai fatto una foto con uno sconosciuto in viaggio.', category: 'travel' },
  { question: 'Non mi sono mai fatto un tatuaggio che ho poi rimpianto.', category: 'general' },
  { question: 'Non ho mai avuto un piercing che si è infettato.', category: 'general' },
  { question: 'Non ho mai provato a tingermi i capelli a casa e andato male.', category: 'funny' },
  { question: 'Non ho mai avuto una fase fashion di cui sono contento che sia finita.', category: 'general' },
  { question: 'Non ho mai indossato qualcosa dal reparto dell\'altro sesso.', category: 'general' },
  { question: 'Non ho mai comprato lo stesso outfit in più colori.', category: 'general' },
  { question: 'Non ho mai perso le chiavi e dovuto fare irruzione in casa mia.', category: 'funny' },
  { question: 'Non mi sono mai chiuso fuori di casa o dalla macchina.', category: 'funny' },
  { question: 'Non ho mai dimenticato dove avevo parcheggiato.', category: 'funny' },
  { question: 'Non mi sono mai trovato senza benzina per strada.', category: 'general' },
  { question: 'Non ho mai avuto una gomma a terra.', category: 'general' },
  { question: 'Non sono mai stato in una macchina in panne in mezzo al nulla.', category: 'travel' },
  { question: 'Non ho mai aiutato uno sconosciuto con la sua macchina.', category: 'general' },
  { question: 'Non ho mai dato soldi a uno sconosciuto per strada.', category: 'general' },
  { question: 'Non mi sono mai offerto volontario per una causa a cui tengo.', category: 'general' },
  { question: 'Non ho mai donato a un\'organizzazione di beneficenza.', category: 'general' },
  { question: 'Non ho mai corso una 5K o una gara più lunga.', category: 'general' },
  { question: 'Non mi sono mai iscritto in palestra e smesso di andarci dopo un mese.', category: 'general' },
  { question: 'Non ho mai provato uno sport e smesso perché non ero bravo.', category: 'general' },
  { question: 'Non sono mai stato a una partita dal vivo.', category: 'general' },
  { question: 'Non ho mai pianto per una partita.', category: 'general' },
  { question: 'Non mi sono mai dipinto la faccia per una partita o un evento.', category: 'general' },
  { question: 'Non sono mai stato a una manifestazione o raduno.', category: 'general' },
  { question: 'Non ho mai scritto una recensione online.', category: 'general' },
  { question: 'Non ho mai litigato con uno sconosciuto nei commenti.', category: 'funny' },
  { question: 'Non ho mai cancellato un commento che avevo postato per le reazioni.', category: 'funny' },
  { question: 'Non sono mai stato bloccato da qualcuno che conosco.', category: 'relationships' },
  { question: 'Non ho mai avuto un segreto troppo grande da tenere.', category: 'relationships' },
  { question: 'Non ho mai raccontato il segreto di un amico a qualcun altro.', category: 'relationships' },
  { question: 'Non sono mai stato beccato in una bugia da qualcuno a cui tenevo.', category: 'relationships' },
  { question: 'Non mi sono mai scusato anni dopo per qualcosa che avevo fatto.', category: 'relationships' },
  { question: 'Non mi sono mai rimesso in contatto con un ex solo per sapere come stava.', category: 'relationships' },
  { question: 'Non ho mai avuto una cotta per il mio migliore amico.', category: 'relationships' },
  { question: 'Non sono mai stato a un appuntamento al buio andato male.', category: 'relationships' },
  { question: 'Non sono mai stato io a porre fine a un\'amicizia.', category: 'relationships' },
  { question: 'Non ho mai fatto amicizia con qualcuno aspettando in coda.', category: 'general' },
  { question: 'Non ho mai avuto un vicino con cui sono diventato amico.', category: 'relationships' },
  { question: 'Non sono mai stato a una riunione e me ne sono pentito.', category: 'relationships' },
  { question: 'Non ho mai dimenticato il nome di un amico presentandolo.', category: 'funny' },
  { question: 'Non ho mai confuso i nomi di due amici.', category: 'funny' },
  { question: 'Non ho mai avuto un gruppo chat che è andato in silenzio dopo un messaggio.', category: 'funny' },
  { question: 'Non ho mai lasciato un messaggio in "letto" per più di un giorno.', category: 'relationships' },
  { question: 'Non ho mai finto di avere una cattiva connessione per finire una chiamata.', category: 'funny' },
  { question: 'Non ho mai detto "devo andare" quando non era vero.', category: 'funny' },
  { question: 'Non sono mai stato a una festa dove non conoscevo nessuno.', category: 'general' },
  { question: 'Non sono mai stato l\'ultimo ad andarsene da una festa.', category: 'general' },
  { question: 'Non ho mai organizzato una festa che è sfuggita di mano.', category: 'general' },
  { question: 'Non ho mai pulito dopo la festa di qualcun altro.', category: 'general' },
  { question: 'Non ho mai avuto un coinquilino con cui non andavo d\'accordo.', category: 'relationships' },
  { question: 'Non mi è mai stata organizzata una festa a sorpresa.', category: 'general' },
  { question: 'Non ho mai rovinato una sorpresa.', category: 'funny' },
  { question: 'Non ho mai dimenticato un anniversario.', category: 'relationships' },
  { question: 'Non ho mai fatto una scena a un raduno di famiglia.', category: 'relationships' },
  { question: 'Non ho mai avuto un familiare che evito alle feste.', category: 'relationships' },
  { question: 'Non ho mai mentito alla mia famiglia su dove stavo andando.', category: 'childhood' },
  { question: 'Non ho mai fatto entrare qualcuno di nascosto in casa mia.', category: 'childhood' },
  { question: 'Non sono mai stato beccato a fare qualcosa che non avrei dovuto.', category: 'general' },
];
