module.exports = [
  { question: 'Kurrë nuk kam genjitur për moshën time.', category: 'general' },
  { question: 'Kurrë nuk kam bërë sikur jam në telefon për të shmangur dikë.', category: 'funny' },
  { question: 'Kurrë nuk kam kënduar në dush.', category: 'general' },
  { question: 'Kurrë nuk kam kërcyer kur askush nuk po shikonte.', category: 'general' },
  { question: 'Kurrë nuk kam qarë gjatë një filmi.', category: 'general' },
  { question: 'Kurrë nuk kam dërguar një mesazh personit të gabuar.', category: 'funny' },
  { question: 'Kurrë nuk kam harruar emrin e dikujt menjëherë pasi u prezantuan.', category: 'funny' },
  { question: 'Kurrë nuk kam tundur dorën dikujt që nuk po më tundte mua.', category: 'funny' },
  { question: 'Kurrë nuk kam fajësuar qenin për diçka që bëra unë.', category: 'funny' },
  { question: 'Kurrë nuk kam kërkuar emrin tim në Google.', category: 'general' },
  { question: 'Kurrë nuk kam qëndruar gjithë natën duke parë një serial TV.', category: 'general' },
  { question: 'Kurrë nuk kam ngrënë ushqim që ra në dysheme.', category: 'food' },
  { question: 'Kurrë nuk kam provuar të përfytyroj teshtimin si kollë.', category: 'funny' },
  { question: 'Kurrë nuk kam bërë sikur punoj kur në të vërtetë po shfletoja internetin.', category: 'work' },
  { question: 'Kurrë nuk kam përsëritur një bisedë në kokën time dhe u ndjeva e turpëruar.', category: 'general' },
  { question: 'Kurrë nuk kam pasur dashuri për një mësues.', category: 'childhood' },
  { question: 'Kurrë nuk jam kapur duke u parë në pasqyrë.', category: 'funny' },
  { question: 'Kurrë nuk kam qeshur aq fort sa qava.', category: 'general' },
  { question: 'Kurrë nuk kam hyrë në një dhomë dhe harrova pse shkova atje.', category: 'funny' },
  { question: 'Kurrë nuk kam fajësuar teknologjinë për gabimin tim.', category: 'funny' },
  { question: 'Kurrë nuk kam udhëtuar vetëm në një vend tjetër.', category: 'travel' },
  { question: 'Kurrë nuk kam humbur një fluturim ose tren.', category: 'travel' },
  { question: 'Kurrë nuk jam humbur në një qytet të huaj.', category: 'travel' },
  { question: 'Kurrë nuk kam provuar një ushqim nga i cili kisha frikë.', category: 'food' },
  { question: 'Kurrë nuk kam ngrënë diçka pas datës së skadimit.', category: 'food' },
  { question: 'Kurrë nuk kam porositur të njëjtën gjë në restorant çdo herë.', category: 'food' },
  { question: 'Kurrë nuk kam ngrënë ëmbëlsirë para darkës.', category: 'food' },
  { question: 'Kurrë nuk kam genjitur në CV-në time.', category: 'work' },
  { question: 'Kurrë nuk kam thirrur të sëmurë kur nuk isha i sëmurë.', category: 'work' },
  { question: 'Kurrë nuk kam rënë në gjumë në një mbledhje ose orë mësimi.', category: 'work' },
  { question: 'Kurrë nuk kam pasur dashuri për dikë në punë.', category: 'work' },
  { question: 'Kurrë nuk kam ardhur vonë në një ngjarje të rëndësishme.', category: 'general' },
  { question: 'Kurrë nuk kam thyer diçka në shtëpinë e një miku dhe nuk i thashë.', category: 'relationships' },
  { question: 'Kurrë nuk kam pasur një adhurues sekret.', category: 'relationships' },
  { question: 'Kurrë nuk jam vendosur në zonën e miqësisë.', category: 'relationships' },
  { question: 'Kurrë nuk kam pasur një takim një natë.', category: 'risky' },
  { question: 'Kurrë nuk kam puthur një të huaj.', category: 'risky' },
  { question: 'Kurrë nuk kam bërë një tatuazh.', category: 'general' },
  { question: 'Kurrë nuk kam bërë vrimë diku tjetër përveç veshëve.', category: 'general' },
  { question: 'Kurrë nuk kam lyer flokët me një ngjyrë të çmendur.', category: 'general' },
  { question: 'Kurrë nuk kam qenë në një koncert.', category: 'general' },
  { question: 'Kurrë nuk kam qenë në një festival muzikor.', category: 'general' },
  { question: 'Kurrë nuk kam takuar një celebritet.', category: 'general' },
  { question: 'Kurrë nuk kam qenë në TV ose në një video që u bë virale.', category: 'general' },
  { question: 'Kurrë nuk kam vrapuar një maratonë ose gjysmë-maratonë.', category: 'general' },
  { question: 'Kurrë nuk kam bërë parashutizëm ose bungee jumping.', category: 'risky' },
  { question: 'Kurrë nuk kam qenë në një tren të vogël.', category: 'general' },
  { question: 'Kurrë nuk kam notuar në oqean natën.', category: 'travel' },
  { question: 'Kurrë nuk kam kampinguar në shkretëtirë.', category: 'travel' },
  { question: 'Kurrë nuk kam bërë autostop.', category: 'risky' },
  { question: 'Kurrë nuk kam fjetur në një aeroport.', category: 'travel' },
  { question: 'Kurrë nuk kam qenë në më shumë se 10 vende.', category: 'travel' },
  { question: 'Kurrë nuk kam mësuar të flas një gjuhë tjetër rrjedhshëm.', category: 'general' },
  { question: 'Kurrë nuk kam jetuar në një vend tjetër.', category: 'travel' },
  { question: 'Kurrë nuk kam pasur një mik me letra nga një vend tjetër.', category: 'childhood' },
  { question: 'Kurrë nuk kam qenë në një martesë.', category: 'relationships' },
  { question: 'Kurrë nuk kam qenë në një varrim.', category: 'general' },
  { question: 'Kurrë nuk kam qenë në një përleshje.', category: 'risky' },
  { question: 'Kurrë nuk jam ndalur nga policia.', category: 'risky' },
  { question: 'Kurrë nuk kam qenë në një kazino.', category: 'risky' },
  { question: 'Kurrë nuk kam bërë baste me para që nuk mund t\'i humbisja.', category: 'risky' },
  { question: 'Kurrë nuk kam thyer një kockë.', category: 'general' },
  { question: 'Kurrë nuk kam pasur qepje.', category: 'general' },
  { question: 'Kurrë nuk kam mërguar.', category: 'general' },
  { question: 'Kurrë nuk kam qëndruar një natë në spital.', category: 'general' },
  { question: 'Kurrë nuk kam qenë në urgjencë.', category: 'general' },
  { question: 'Kurrë nuk kam pasur një përvojë afër vdekjes.', category: 'risky' },
  { question: 'Kurrë nuk kam shpëtuar jetën e dikujt.', category: 'general' },
  { question: 'Kurrë nuk kam qenë në një aksident automobilistik.', category: 'general' },
  { question: 'Kurrë nuk kam marrë një gjobë për shpejtësi.', category: 'risky' },
  { question: 'Kurrë nuk kam hipur në moto.', category: 'general' },
  { question: 'Kurrë nuk kam bërë zhytje me cilindra.', category: 'travel' },
  { question: 'Kurrë nuk kam provuar të bëj surf.', category: 'general' },
  { question: 'Kurrë nuk kam bërë ski ose snowboard.', category: 'general' },
  { question: 'Kurrë nuk kam ngjitur një mal.', category: 'travel' },
  { question: 'Kurrë nuk kam qenë në një kruizë.', category: 'travel' },
  { question: 'Kurrë nuk kam qenë në një varkë në mes të oqeanit.', category: 'travel' },
  { question: 'Kurrë nuk kam parë dritat veriore.', category: 'travel' },
  { question: 'Kurrë nuk kam parë një kafshë të egër nga afër.', category: 'travel' },
  { question: 'Kurrë nuk jam kafshuar nga një kafshë.', category: 'general' },
  { question: 'Kurrë nuk kam pasur një kafshë shtëpiake që nuk ishte mace ose qen.', category: 'general' },
  { question: 'Kurrë nuk kam vjedhur diçka.', category: 'risky' },
  { question: 'Kurrë nuk jam arrestuar ose mbajtur.', category: 'risky' },
  { question: 'Kurrë nuk kam qenë në një strip klub.', category: 'risky' },
  { question: 'Kurrë nuk kam notuar lakuriq.', category: 'risky' },
  { question: 'Kurrë nuk kam qenë lakuriq në publik.', category: 'risky' },
  { question: 'Kurrë nuk kam pasur një problem me rrobat në publik.', category: 'funny' },
  { question: 'Kurrë nuk kam hyrë te dikush në banjë.', category: 'funny' },
  { question: 'Kurrë nuk më kanë hyrë te unë në banjë.', category: 'funny' },
  { question: 'Kurrë nuk kam parë ëndërr për dikë në këtë dhomë.', category: 'risky' },
  { question: 'Kurrë nuk kam pasur dashuri për ish-tën e një miku.', category: 'relationships' },
  { question: 'Kurrë nuk kam dalë me dy njerëz njëkohësisht.', category: 'relationships' },
  { question: 'Kurrë nuk kam qenë në një takim të verbër.', category: 'relationships' },
  { question: 'Kurrë nuk jam mashtruar ose gënjyer në internet.', category: 'relationships' },
  { question: 'Kurrë nuk kam dërguar mesazh dikujt në DMs.', category: 'relationships' },
  { question: 'Kurrë nuk kam qenë i dashuruar në shikim të parë.', category: 'relationships' },
  { question: 'Kurrë nuk kam pasur një marrëdhënie largësie.', category: 'relationships' },
  { question: 'Kurrë nuk jam kthyer së bashku me një ish.', category: 'relationships' },
  { question: 'Kurrë nuk jam lënë pa përgjigje.', category: 'relationships' },
  { question: 'Kurrë nuk kam lënë dikë pa përgjigje.', category: 'relationships' },
  { question: 'Kurrë nuk kam pasur një dashuri të palidhur për më shumë se një vit.', category: 'relationships' },
  { question: 'Kurrë nuk kam shkruar një letër dashurie.', category: 'relationships' },
  { question: 'Kurrë nuk më kanë kënduar ose kam kënduar dikujt.', category: 'relationships' },
  { question: 'Kurrë nuk kam pasur një luftë ushqimore.', category: 'childhood' },
  { question: 'Kurrë nuk jam dërguar te zyra e drejtorit.', category: 'childhood' },
  { question: 'Kurrë nuk kam kopjuar në një provim.', category: 'childhood' },
  { question: 'Kurrë nuk jam pezulluar ose përjashtuar nga shkolla.', category: 'childhood' },
  { question: 'Kurrë nuk kam qëndruar gjithë natën për shkollë.', category: 'childhood' },
  { question: 'Kurrë nuk kam pasur një ID të rreme.', category: 'risky' },
  { question: 'Kurrë nuk kam dalë fshehurazi nga shtëpia si adoleshent.', category: 'childhood' },
  { question: 'Kurrë nuk kam bërë festë kur prindërit nuk ishin.', category: 'childhood' },
  { question: 'Kurrë nuk kam thyer një dritare ose diçka me vlerë në shtëpi.', category: 'childhood' },
  { question: 'Kurrë nuk jam ndaluar për më shumë se një javë.', category: 'childhood' },
  { question: 'Kurrë nuk kam genjitur prindërit për vendin ku isha.', category: 'childhood' },
  { question: 'Kurrë nuk kam pasur një ditar që dikush e lexoi.', category: 'childhood' },
  { question: 'Kurrë nuk kam qenë në një pjesë shkolle ose shfaqje talente.', category: 'childhood' },
  { question: 'Kurrë nuk kam qenë i fundit i zgjedhur për një ekip.', category: 'childhood' },
  { question: 'Kurrë nuk jam ngacmuar ose kam ngacmuar dikë.', category: 'childhood' },
  { question: 'Kurrë nuk kam pasur një nofkë që e urreja.', category: 'funny' },
  { question: 'Kurrë nuk jam fotobombuar ose kam fotobombuar dikë.', category: 'funny' },
  { question: 'Kurrë nuk kam bërë një selfie dhe e fshiva menjëherë.', category: 'funny' },
  { question: 'Kurrë nuk kam postuar diçka dhe e fshiva brenda një ore.', category: 'funny' },
  { question: 'Kurrë nuk kam debatuar me një të huaj në internet.', category: 'funny' },
  { question: 'Kurrë nuk kam komentuar aksidentalisht në një postim të vjetër.', category: 'funny' },
  { question: 'Kurrë nuk kam pëlqyer postimin ose foton time.', category: 'funny' },
  { question: 'Kurrë nuk kam pëlqyer aksidentalisht foton e vjetër të dikujt.', category: 'funny' },
  { question: 'Kurrë nuk jam bllokuar nga dikush në rrjetet sociale.', category: 'relationships' },
  { question: 'Kurrë nuk kam bllokuar dikë që njoh në jetën reale.', category: 'relationships' },
  { question: 'Kurrë nuk kam pasur më shumë se 1000 ndjekës në asnjë platformë.', category: 'general' },
  { question: 'Kurrë nuk jam bërë viral për diçka të turpshme.', category: 'funny' },
  { question: 'Kurrë nuk kam provuar të gatuaj dhe dështuar keq.', category: 'food' },
  { question: 'Kurrë nuk kam aktivizuar alarmin e tymit duke gatuar.', category: 'food' },
  { question: 'Kurrë nuk kam porositur picë më shumë se dy herë në një javë.', category: 'food' },
  { question: 'Kurrë nuk kam ngrënë një picë të tërë vetëm.', category: 'food' },
  { question: 'Kurrë nuk kam ngrënë diçka të papërgatitur që duhej gatuar.', category: 'food' },
  { question: 'Kurrë nuk kam provuar një kombinim të çuditshëm ushqimesh.', category: 'food' },
  { question: 'Kurrë nuk kam qenë në një "sa të mundesh" dhe u sëmura.', category: 'food' },
  { question: 'Kurrë nuk kam vjedhur ushqim nga një bashkëbanor ose anëtar familje.', category: 'food' },
  { question: 'Kurrë nuk kam ngrënë mëngjes për darkë.', category: 'food' },
  { question: 'Kurrë nuk kam pasur varësi nga kafeina.', category: 'food' },
  { question: 'Kurrë nuk kam provuar pije energjie për të qëndruar zgjuar.', category: 'food' },
  { question: 'Kurrë nuk kam shkuar në drive-through të fast-food në pizhama.', category: 'funny' },
  { question: 'Kurrë nuk kam qarë për qumësht të derdhur ose ushqim të rënë.', category: 'funny' },
  { question: 'Kurrë nuk kam bërë sikur më pëlqen një dhuratë që mora.', category: 'relationships' },
  { question: 'Kurrë nuk kam ridarë diçka.', category: 'relationships' },
  { question: 'Kurrë nuk kam harruar ditëlindjen e një miku të afërt ose anëtari të familjes.', category: 'relationships' },
  { question: 'Kurrë nuk kam shfaqur në një festë në ditën e gabuar.', category: 'funny' },
  { question: 'Kurrë nuk kam qenë i vetmi që u shfaq me kostum.', category: 'funny' },
  { question: 'Kurrë nuk kam rënë në gjumë në një festë.', category: 'funny' },
  { question: 'Kurrë nuk kam qenë shoferi i caktuar dhe e urreja.', category: 'general' },
  { question: 'Kurrë nuk kam humbur celularin dhe u çudita.', category: 'funny' },
  { question: 'Kurrë nuk kam lënë celularin në shtëpi dhe u ndjeva e zhveshur.', category: 'funny' },
  { question: 'Kurrë nuk më ka rënë celulari në tualet.', category: 'funny' },
  { question: 'Kurrë nuk kam thyer ekranin e celularit.', category: 'general' },
  { question: 'Kurrë nuk kam përdorur celularin e dikujt tjetër pa pyetur.', category: 'relationships' },
  { question: 'Kurrë nuk kam parë mesazhet e dikujt tjetër.', category: 'relationships' },
  { question: 'Kurrë nuk jam kapur duke parë celularin e dikujt.', category: 'funny' },
  { question: 'Kurrë nuk kam pasur një fjalëkalim që ishte "password" ose "123456".', category: 'funny' },
  { question: 'Kurrë nuk kam harruar një fjalëkalim të rëndësishëm.', category: 'funny' },
  { question: 'Kurrë nuk kam përgjigjur "edhe ti" kur dikush tha "shijoni filmin" ose të ngjashme.', category: 'funny' },
  { question: 'Kurrë nuk kam thënë "mirupafshim" dy herë në të njëjtën bisedë.', category: 'funny' },
  { question: 'Kurrë nuk kam penguar në publik.', category: 'funny' },
  { question: 'Kurrë nuk kam tundur dorën një të huaji duke menduar se e njihja.', category: 'funny' },
  { question: 'Kurrë nuk kam provuar të hap një derë shtytjeje duke tërhequr.', category: 'funny' },
  { question: 'Kurrë nuk kam hyrë në një derë xhami.', category: 'funny' },
  { question: 'Kurrë nuk kam humbur një hap dhe u pengova.', category: 'funny' },
  { question: 'Kurrë nuk kam pasur një thirrje video dhe harrova që isha në kamerë.', category: 'work' },
  { question: 'Kurrë nuk kam qenë në një mbledhje dhe nuk kisha idenë se për çfarë po diskutohej.', category: 'work' },
  { question: 'Kurrë nuk kam bërë një dremitje gjatë orëve të punës.', category: 'work' },
  { question: 'Kurrë nuk kam pasur një punë që e urreja.', category: 'work' },
  { question: 'Kurrë nuk kam dhënë dorëheqje nga një punë pa pasur një tjetër.', category: 'work' },
  { question: 'Kurrë nuk jam pushuar nga një punë.', category: 'work' },
  { question: 'Kurrë nuk jam promovuar.', category: 'work' },
  { question: 'Kurrë nuk kam pasur rivalitet me një bashkëpunëtor.', category: 'work' },
  { question: 'Kurrë nuk kam dalë me një bashkëpunëtor.', category: 'work' },
  { question: 'Kurrë nuk kam pasur dashuri për një celebritet.', category: 'general' },
  { question: 'Kurrë nuk kam shkruar fan mail ose dërguar DM një celebriteti.', category: 'general' },
  { question: 'Kurrë nuk kam qarë për një ndarje celebritetesh.', category: 'funny' },
  { question: 'Kurrë nuk kam qenë në premiere mesnate të filmit.', category: 'general' },
  { question: 'Kurrë nuk kam veshur si personazh për lëshimin e një filmi.', category: 'funny' },
  { question: 'Kurrë nuk kam parë të njëjtin film më shumë se 10 herë.', category: 'general' },
  { question: 'Kurrë nuk kam rënë në gjumë në kinema.', category: 'funny' },
  { question: 'Kurrë nuk kam qenë në një koncert dhe nuk njihja asnjë këngë.', category: 'funny' },
  { question: 'Kurrë nuk kam kënduar karaoke.', category: 'general' },
  { question: 'Kurrë nuk kam kërcyer mbi një tavolinë.', category: 'risky' },
  { question: 'Kurrë nuk kam bërë skenë në publik.', category: 'funny' },
  { question: 'Kurrë nuk jam përjashtuar nga një vend.', category: 'risky' },
  { question: 'Kurrë nuk kam pasur një pothuajse-incident me ligjin.', category: 'risky' },
  { question: 'Kurrë nuk kam ndihmuar dikë të fshehë diçka nga prindërit e tyre.', category: 'relationships' },
  { question: 'Kurrë nuk kam mbajtur një sekret që ishte vërtetë e vështirë.', category: 'relationships' },
  { question: 'Kurrë nuk kam zbuluar aksidentalisht një sekret.', category: 'relationships' },
  { question: 'Kurrë nuk jam tradhtuar nga një mik.', category: 'relationships' },
  { question: 'Kurrë nuk kam tradhtuar besimin e një miku.', category: 'relationships' },
  { question: 'Kurrë nuk kam pasur grindje me më të mirin mik.', category: 'relationships' },
  { question: 'Kurrë nuk jam rilidhur me një mik të vjetër pas viteve.', category: 'relationships' },
  { question: 'Kurrë nuk kam qenë në takim të shkollës së mesme ose kolegjit.', category: 'relationships' },
  { question: 'Kurrë nuk kam pasur një bashkëbanor që nuk mund ta duroja.', category: 'relationships' },
  { question: 'Kurrë nuk kam pasur një fqinj që nuk mund ta duroja.', category: 'relationships' },
  { question: 'Kurrë nuk kam ankuar për dikë që ishte në të njëjtën dhomë.', category: 'funny' },
  { question: 'Kurrë nuk jam kapur duke folur për dikë.', category: 'funny' },
  { question: 'Kurrë nuk kam qeshur në momentin e gabuar.', category: 'funny' },
  { question: 'Kurrë nuk kam përdorur erë në publik dhe bëra sikur nuk isha unë.', category: 'funny' },
  { question: 'Kurrë nuk kam pasur problem me rrobat.', category: 'funny' },
  { question: 'Kurrë nuk kam veshur të njëjtin outfit dy ditë me radhë në punë ose shkollë.', category: 'general' },
  { question: 'Kurrë nuk kam veshur rroba me anën e brendshme aksidentalisht.', category: 'funny' },
  { question: 'Kurrë nuk kam veshur dy këpucë të ndryshme.', category: 'funny' },
  { question: 'Kurrë nuk kam dalë nga shtëpia pa pantallona ose me pizhama.', category: 'funny' },
  { question: 'Kurrë nuk kam pasur një prerje flokësh të keqe dhe qava.', category: 'funny' },
  { question: 'Kurrë nuk kam prerë flokët e mi vetë.', category: 'general' },
  { question: 'Kurrë nuk kam provuar t\'i bëj vetes ballë.', category: 'funny' },
  { question: 'Kurrë nuk kam pasur permanente.', category: 'general' },
  { question: 'Kurrë nuk jam djegur nga dielli aq keq sa nuk mund të flija.', category: 'travel' },
  { question: 'Kurrë nuk jam humbur në një dyqan si fëmijë.', category: 'childhood' },
  { question: 'Kurrë nuk kam pasur frikë nga errësira si i rritur.', category: 'general' },
  { question: 'Kurrë nuk kam pasur një makth të përsëritur.', category: 'general' },
  { question: 'Kurrë nuk kam ecur ose folar në gjumë.', category: 'general' },
  { question: 'Kurrë nuk kam parë një ëndërr që u ndje e vërtetë dhe preku ditën time.', category: 'general' },
  { question: 'Kurrë nuk jam zgjuar nga një makth dhe kam thirrur dikë.', category: 'general' },
  { question: 'Kurrë nuk kam besuar në fantazma ose gjëra mbinatyrore.', category: 'general' },
  { question: 'Kurrë nuk kam menduar se pashë një fantazmë ose diçka paranormale.', category: 'general' },
  { question: 'Kurrë nuk kam qenë në një shtëpi ose vend të ndrequr.', category: 'general' },
  { question: 'Kurrë nuk kam qenë te një psikik ose lexues tarot.', category: 'general' },
  { question: 'Kurrë nuk kam provuar të mësoj një truk magjie.', category: 'general' },
  { question: 'Kurrë nuk kam provuar të bëj backflip ose rrotullim dhe dështova.', category: 'funny' },
  { question: 'Kurrë nuk kam provuar të mësoj një valë TikTok ose virale.', category: 'funny' },
  { question: 'Kurrë nuk kam postuar një TikTok ose Reel.', category: 'general' },
  { question: 'Kurrë nuk jam bërë viral në rrjetet sociale.', category: 'general' },
  { question: 'Kurrë nuk kam pasur një foto të imja që u bë virale pa pëlqimin tim.', category: 'general' },
  { question: 'Kurrë nuk jam njohur në publik nga një i huaj.', category: 'general' },
  { question: 'Kurrë nuk kam qenë vetëm në një park tematik.', category: 'travel' },
  { question: 'Kurrë nuk kam hipur në të njëjtën atraksion 5 herë me radhë.', category: 'general' },
  { question: 'Kurrë nuk kam vjellë në një atraksion.', category: 'funny' },
  { question: 'Kurrë nuk kam pasur frikë në një atraksion dhe duhej të zbritja.', category: 'general' },
  { question: 'Kurrë nuk kam provuar një sport ekstrem.', category: 'risky' },
  { question: 'Kurrë nuk kam ofruar vullnetar dhe u pendova.', category: 'general' },
  { question: 'Kurrë nuk kam dhënë gjak.', category: 'general' },
  { question: 'Kurrë nuk kam mërguar në shikim të gjakut.', category: 'general' },
  { question: 'Kurrë nuk kam pasur frikë nga gjilpërat.', category: 'general' },
  { question: 'Kurrë nuk kam pasur frikë të fluturoj.', category: 'travel' },
  { question: 'Kurrë nuk kam pasur një krizë paniku.', category: 'general' },
  { question: 'Kurrë nuk kam provuar meditim ose joga.', category: 'general' },
  { question: 'Kurrë nuk kam qenë në terapi ose këshillim.', category: 'general' },
  { question: 'Kurrë nuk kam bërë trajtim të heshtur dikujt për më shumë se një ditë.', category: 'relationships' },
  { question: 'Kurrë nuk kam mbajtur grindje për vite.', category: 'relationships' },
  { question: 'Kurrë nuk kam kërkuar falje kur nuk isha gabim.', category: 'relationships' },
  { question: 'Kurrë nuk kam refuzuar të kërkoj falje kur isha gabim.', category: 'relationships' },
  { question: 'Kurrë nuk kam pasur një debat publik me dikë.', category: 'relationships' },
  { question: 'Kurrë nuk jam pajtuar me dikë pas një grindjeje të madhe.', category: 'relationships' },
  { question: 'Kurrë nuk kam qenë në një martesë dhe nuk i njihja mirë çiftin.', category: 'relationships' },
  { question: 'Kurrë nuk kam qenë vajzë nderi ose djalë nderi.', category: 'relationships' },
  { question: 'Kurrë nuk kam kapur buqetën ose lidhësen.', category: 'relationships' },
  { question: 'Kurrë nuk kam mbajtur fjalim në një martesë.', category: 'relationships' },
  { question: 'Kurrë nuk kam qarë në një martesë.', category: 'relationships' },
  { question: 'Kurrë nuk kam qenë në një baby shower.', category: 'relationships' },
  { question: 'Kurrë nuk kam mbajtur një foshnjë të sapolindur.', category: 'general' },
  { question: 'Kurrë nuk kam ndërruar pelenë.', category: 'general' },
  { question: 'Kurrë nuk kam kujdesur fëmijë.', category: 'general' },
  { question: 'Kurrë nuk kam dashur të kem fëmijë.', category: 'general' },
  { question: 'Kurrë nuk kam dashur të mos kem fëmijë.', category: 'general' },
  { question: 'Kurrë nuk kam pasur një kafshë që vdiq dhe qava.', category: 'general' },
  { question: 'Kurrë nuk kam varrosur një kafshë.', category: 'general' },
  { question: 'Kurrë nuk kam qenë në një varrim dhe qeshura në momentin e gabuar.', category: 'funny' },
  { question: 'Kurrë nuk kam folur në një varrim.', category: 'general' },
  { question: 'Kurrë nuk kam vizituar varrin e dikujt që njoha.', category: 'general' },
  { question: 'Kurrë nuk kam pasur një përvojë afër vdekjes dhe mendova për jetën time.', category: 'risky' },
  { question: 'Kurrë nuk kam bërë një listë bucket.', category: 'general' },
  { question: 'Kurrë nuk kam kryqëzuar diçka nga lista ime bucket.', category: 'general' },
  { question: 'Kurrë nuk kam provuar të mësoj një gjuhë të re dhe u dorëzova.', category: 'general' },
  { question: 'Kurrë nuk kam mësuar të luaj një instrument.', category: 'general' },
  { question: 'Kurrë nuk kam provuar të mësoj një instrument dhe e lashë.', category: 'general' },
  { question: 'Kurrë nuk kam shkruar një këngë ose poemë.', category: 'general' },
  { question: 'Kurrë nuk kam piktuar ose vizatuar diçka që isha krenar.', category: 'general' },
  { question: 'Kurrë nuk kam provuar të gatuaj një vakt të sofistikuar dhe dështova.', category: 'food' },
  { question: 'Kurrë nuk kam pjekur diçka nga e para.', category: 'food' },
  { question: 'Kurrë nuk kam djegur diçka që po gatuaja.', category: 'food' },
  { question: 'Kurrë nuk kam provuar një dietë dhe e lashë pas një jave.', category: 'food' },
  { question: 'Kurrë nuk kam qenë vegjetarian ose vegan.', category: 'food' },
  { question: 'Kurrë nuk kam provuar një trend ushqimor si jeshilja ose tosti me avokado.', category: 'food' },
  { question: 'Kurrë nuk kam ngrënë diçka që rrita vetë.', category: 'food' },
  { question: 'Kurrë nuk kam qenë në një treg fermerësh.', category: 'food' },
  { question: 'Kurrë nuk kam qenë në një restorant të sofistikuar dhe u ndjeva e pamjaftueshme.', category: 'food' },
  { question: 'Kurrë nuk kam kthyer ushqim në restorant.', category: 'food' },
  { question: 'Kurrë nuk kam larguar pa lënë bakshish.', category: 'food' },
  { question: 'Kurrë nuk kam pasur debat për faturën.', category: 'relationships' },
  { question: 'Kurrë nuk kam qenë në dietë me një mik.', category: 'relationships' },
  { question: 'Kurrë nuk kam konkurruar me një mik për diçka qesharake.', category: 'relationships' },
  { question: 'Kurrë nuk kam pasur shtrëngim sekret të dorës me dikë.', category: 'childhood' },
  { question: 'Kurrë nuk kam pasur një mik imagjinar.', category: 'childhood' },
  { question: 'Kurrë nuk kam besuar në Babagjyshin pas moshës 10 vjeçare.', category: 'childhood' },
  { question: 'Kurrë nuk kam vënë një dhëmb nën jastëk për Zanën e Dhëmbëve.', category: 'childhood' },
  { question: 'Kurrë nuk kam pasur frikë nga klounat.', category: 'general' },
  { question: 'Kurrë nuk kam qenë në një cirk.', category: 'general' },
  { question: 'Kurrë nuk kam qenë në kopshtin zoologjik dhe u ndjeva keq për kafshët.', category: 'general' },
  { question: 'Kurrë nuk kam hipur në kalë.', category: 'general' },
  { question: 'Kurrë nuk jam kafshuar nga një insekt dhe pata reaksion të keq.', category: 'general' },
  { question: 'Kurrë nuk kam pasur frikë nga merimangat ose insektet.', category: 'general' },
  { question: 'Kurrë nuk kam vrarë një merimangë për dikë tjetër.', category: 'general' },
  { question: 'Kurrë nuk kam shpëtuar një kafshë.', category: 'general' },
  { question: 'Kurrë nuk kam adoptuar një kafshë nga një strehë.', category: 'general' },
  { question: 'Kurrë nuk kam humbur një kafshë.', category: 'general' },
  { question: 'Kurrë nuk kam pasur një kafshë që iku.', category: 'general' },
  { question: 'Kurrë nuk kam genjitur se jam i zënë për të dalë nga planet.', category: 'general' },
  { question: 'Kurrë nuk kam bërë sikur më pëlqen një këngë kur dikush e luante.', category: 'funny' },
  { question: 'Kurrë nuk kam thënë "Jam në rrugë" kur ende nuk kisha nisur.', category: 'funny' },
  { question: 'Kurrë nuk kam lexuar ditarin e dikujt tjetër.', category: 'relationships' },
  { question: 'Kurrë nuk kam pasur një nofkë që i dhashë vetes.', category: 'funny' },
  { question: 'Kurrë nuk kam qenë i treti rrotë në një takim.', category: 'relationships' },
  { question: 'Kurrë nuk kam pëlqyer aksidentalisht postimin e një ish.', category: 'funny' },
  { question: 'Kurrë nuk kam qëndruar në një marrëdhënie më gjatë se duhej.', category: 'relationships' },
  { question: 'Kurrë nuk kam parë ëndërr për dikë dhe u ndjeva e çuditshme pranë tyre ditën tjetër.', category: 'general' },
  { question: 'Kurrë nuk kam parë një serial më shumë se pesë herë.', category: 'general' },
  { question: 'Kurrë nuk kam qarë për një reklamë.', category: 'funny' },
  { question: 'Kurrë nuk kam biseduar me veten në pasqyrë.', category: 'funny' },
  { question: 'Kurrë nuk kam praktikuar një bisedë para se të ndodhte.', category: 'general' },
  { question: 'Kurrë nuk kam pasur frikë të kontrolloj bilancin e bankës.', category: 'general' },
  { question: 'Kurrë nuk kam blerë diçka që nuk mund ta përballoja.', category: 'general' },
  { question: 'Kurrë nuk kam kthyer një dhuratë.', category: 'relationships' },
  { question: 'Kurrë nuk kam harruar ditëlindjen e një miku të afërt.', category: 'relationships' },
  { question: 'Kurrë nuk kam shfaqur vonë në ngjarjen time.', category: 'funny' },
  { question: 'Kurrë nuk kam ngatërruar emrat e dy njerëzve në të njëjtën fjali.', category: 'funny' },
  { question: 'Kurrë nuk kam thënë "shihemi nesër" dikujt që dinja që nuk do të shihesha.', category: 'funny' },
  { question: 'Kurrë nuk kam bërë sikur kuptoj një shaka dhe qeshura gjithsesi.', category: 'funny' },
  { question: 'Kurrë nuk kam tundur kokën në një bisedë që nuk e ndoqa.', category: 'funny' },
  { question: 'Kurrë nuk jam kapur duke kënduar në makinë në një semafor të kuq.', category: 'funny' },
  { question: 'Kurrë nuk kam pasur dashuri për një personazh fictiv.', category: 'general' },
  { question: 'Kurrë nuk kam shkruar një letër që nuk e dërgova kurrë.', category: 'general' },
  { question: 'Kurrë nuk kam provuar të rregulloj diçka dhe e bëra më keq.', category: 'funny' },
  { question: 'Kurrë nuk kam fajësuar dikë tjetër për diçka që bëra unë.', category: 'relationships' },
  { question: 'Kurrë nuk kam marrë kredit për idenë e dikujt tjetër.', category: 'work' },
  { question: 'Kurrë nuk jam kapur në një gënjeshtër të vogël.', category: 'funny' },
  { question: 'Kurrë nuk kam ekzagjeruar një histori për ta bërë më interesante.', category: 'general' },
  { question: 'Kurrë nuk kam qenë xheloz nga suksesi i një miku.', category: 'relationships' },
  { question: 'Kurrë nuk jam krahasuar me dikë në rrjetet sociale dhe u ndjeva keq.', category: 'general' },
  { question: 'Kurrë nuk kam fshirë një foto për shkak të pamjes sime.', category: 'general' },
  { question: 'Kurrë nuk kam qenë nervoz para një interviste pune.', category: 'work' },
  { question: 'Kurrë nuk kam dështuar ditën e parë në një punë të re.', category: 'work' },
  { question: 'Kurrë nuk kam rënë në gjumë gjatë një filmi në kinema.', category: 'funny' },
  { question: 'Kurrë nuk kam pasur helmim ushqimor nga diçka që hëngra.', category: 'food' },
  { question: 'Kurrë nuk kam provuar të bëj përshtypje dikujt me një aftësi që nuk e kam.', category: 'general' },
  { question: 'Kurrë nuk jam kapur duke bërë diçka të turpshme në kamerë.', category: 'funny' },
  { question: 'Kurrë nuk kam pasur një fazë që tani më turpëron.', category: 'general' },
  { question: 'Kurrë nuk kam veshur diçka që ishte qartësisht shumë e vogël ose shumë e madhe.', category: 'funny' },
  { question: 'Kurrë nuk kam pasur reaksion të keq ndaj një prerje flokësh dhe genjita se më pëlqente.', category: 'funny' },
  { question: 'Kurrë nuk kam provuar të bëj një selfie të mirë për më shumë se 10 minuta.', category: 'funny' },
  { question: 'Kurrë nuk kam qenë ai që prishi foton e grupit.', category: 'funny' },
  { question: 'Kurrë nuk kam harruar çfarë po thosha në mes të fjalisë.', category: 'funny' },
  { question: 'Kurrë nuk kam quajtur gabimisht një mësues "mama" ose "baba".', category: 'childhood' },
  { question: 'Kurrë nuk kam ecur me siguri në drejtimin e gabuar.', category: 'funny' },
  { question: 'Kurrë nuk kam provuar të hap një derë që thoshte "tërhiq" duke shtyrë.', category: 'funny' },
  { question: 'Kurrë nuk kam thënë "faleminderit" kur dikush tha "më vjen keq".', category: 'funny' },
  { question: 'Kurrë nuk kam tundur dorën një foshnje dhe pastaj kuptova që ishte kukull.', category: 'funny' },
  { question: 'Kurrë nuk kam pasur frikë nga errësira si i rritur.', category: 'general' },
  { question: 'Kurrë nuk kam fjetur me një kafshë plushi si i rritur.', category: 'general' },
  { question: 'Kurrë nuk kam pasur një maskotë ose supersticion.', category: 'general' },
  { question: 'Kurrë nuk kam bërë një dëshirë mbi një yll që bie.', category: 'general' },
  { question: 'Kurrë nuk kam thyer një pasqyrë dhe u shqetësova për fat të keq.', category: 'general' },
  { question: 'Kurrë nuk kam kaluar nën një shkallë.', category: 'general' },
  { question: 'Kurrë nuk kam qenë te një parashikues.', category: 'general' },
  { question: 'Kurrë nuk kam provuar të ëndërroj lucid.', category: 'general' },
  { question: 'Kurrë nuk kam pasur paralizë gjumi.', category: 'general' },
  { question: 'Kurrë nuk jam zgjuar dhe nuk dija ku isha për një moment.', category: 'general' },
  { question: 'Kurrë nuk kam fjetur mbi alarm dhe humba diçka të rëndësishme.', category: 'funny' },
  { question: 'Kurrë nuk kam shtypur snooze më shumë se tre herë me radhë.', category: 'funny' },
  { question: 'Kurrë nuk kam pasur një bisedë në gjumë që dikush dëgjoi.', category: 'funny' },
  { question: 'Kurrë nuk jam zgjuar nga gërhitja ime.', category: 'funny' },
  { question: 'Kurrë nuk kam rënë në gjumë në bibliotekë.', category: 'general' },
  { question: 'Kurrë nuk kam qëndruar gjithë natën për diçka që nuk ishte punë ose shkollë.', category: 'general' },
  { question: 'Kurrë nuk kam pasur një dremitje që u shndërrua në gjumë gjithë natën.', category: 'funny' },
  { question: 'Kurrë nuk kam qenë në një bar karaoke dhe nuk këndova.', category: 'general' },
  { question: 'Kurrë nuk kam kënduar karaoke dhe harrova fjalët.', category: 'funny' },
  { question: 'Kurrë nuk kam qenë në një shfaqje komedie dhe komediani më zgjodhi mua.', category: 'funny' },
  { question: 'Kurrë nuk kam qenë në një park tematik dhe u sëmura në një atraksion.', category: 'travel' },
  { question: 'Kurrë nuk kam humbur bagazhin gjatë udhëtimit.', category: 'travel' },
  { question: 'Kurrë nuk kam pasur një fluturim të vonuar më shumë se 5 orë.', category: 'travel' },
  { question: 'Kurrë nuk kam qenë ulur pranë dikujt të bezdisshëm në një fluturim të gjatë.', category: 'travel' },
  { question: 'Kurrë nuk kam qenë në një vend ku nuk flisja gjuhën.', category: 'travel' },
  { question: 'Kurrë nuk kam marrë një suvenir që u thye para se të kthehesha në shtëpi.', category: 'travel' },
  { question: 'Kurrë nuk kam bërë një foto me një të huaj gjatë udhëtimit.', category: 'travel' },
  { question: 'Kurrë nuk kam bërë një tatuazh që më vonë u pendova.', category: 'general' },
  { question: 'Kurrë nuk kam pasur një vrimë që u infektua.', category: 'general' },
  { question: 'Kurrë nuk kam provuar të lyej flokët në shtëpi dhe shkoi keq.', category: 'funny' },
  { question: 'Kurrë nuk kam pasur një fazë mode që më vjen mirë që kaloi.', category: 'general' },
  { question: 'Kurrë nuk kam veshur diçka nga seksioni i gjinisë së kundërt.', category: 'general' },
  { question: 'Kurrë nuk kam blerë të njëjtin outfit në shumë ngjyra.', category: 'general' },
  { question: 'Kurrë nuk kam humbur çelësat dhe duhej të thyja vetes.', category: 'funny' },
  { question: 'Kurrë nuk jam mbyllur jashtë shtëpisë ose makinës time.', category: 'funny' },
  { question: 'Kurrë nuk kam harruar ku e parkova makinën.', category: 'funny' },
  { question: 'Kurrë nuk më kanë mbaruar benzinat në rrugë.', category: 'general' },
  { question: 'Kurrë nuk kam pasur gomë të sheshtë.', category: 'general' },
  { question: 'Kurrë nuk kam qenë në një makinë që u prish në mes të asgjëje.', category: 'travel' },
  { question: 'Kurrë nuk kam ndihmuar një të huaj me makinën e tyre.', category: 'general' },
  { question: 'Kurrë nuk kam dhënë para një të huaji në rrugë.', category: 'general' },
  { question: 'Kurrë nuk kam ofruar vullnetar për një shkak që më intereson.', category: 'general' },
  { question: 'Kurrë nuk kam dhënë për bamirësi.', category: 'general' },
  { question: 'Kurrë nuk kam vrapuar një garë 5K ose më të gjatë.', category: 'general' },
  { question: 'Kurrë nuk kam hyrë në palestër dhe nuk shkova më pas një muaj.', category: 'general' },
  { question: 'Kurrë nuk kam provuar një sport dhe e lashë sepse nuk isha i mirë.', category: 'general' },
  { question: 'Kurrë nuk kam qenë në një ndeshje sportive drejtpërdrejt.', category: 'general' },
  { question: 'Kurrë nuk kam qarë për një ndeshje sportive.', category: 'general' },
  { question: 'Kurrë nuk kam lyer fytyrën për një ndeshje ose ngjarje.', category: 'general' },
  { question: 'Kurrë nuk kam qenë në një protestë ose mbledhje.', category: 'general' },
  { question: 'Kurrë nuk kam shkruar një recension në internet.', category: 'general' },
  { question: 'Kurrë nuk kam debatuar me një të huaj në seksionin e komenteve.', category: 'funny' },
  { question: 'Kurrë nuk kam fshirë një koment që postova për shkak të reagimit.', category: 'funny' },
  { question: 'Kurrë nuk jam bllokuar nga dikush që njoh.', category: 'relationships' },
  { question: 'Kurrë nuk kam pasur një sekret shumë të madh për ta mbajtur.', category: 'relationships' },
  { question: 'Kurrë nuk kam thënë sekretin e një miku dikujt tjetër.', category: 'relationships' },
  { question: 'Kurrë nuk jam kapur në një gënjeshtër nga dikush për të cilin kujdesesha.', category: 'relationships' },
  { question: 'Kurrë nuk kam kërkuar falje vite më vonë për diçka që bëra.', category: 'relationships' },
  { question: 'Kurrë nuk jam rilidhur me një ish vetëm për të parë si janë.', category: 'relationships' },
  { question: 'Kurrë nuk kam pasur dashuri për më të mirin tim mik.', category: 'relationships' },
  { question: 'Kurrë nuk jam vendosur në një takim të verbër që shkoi keq.', category: 'relationships' },
  { question: 'Kurrë nuk kam qenë ai që e mbylli një miqësi.', category: 'relationships' },
  { question: 'Kurrë nuk kam bërë një mik duke pritur në radhë.', category: 'general' },
  { question: 'Kurrë nuk kam pasur një fqinj me të cilin u bëra mik.', category: 'relationships' },
  { question: 'Kurrë nuk kam qenë në takim dhe u pendova.', category: 'relationships' },
  { question: 'Kurrë nuk kam harruar emrin e një miku kur po e prezantoja.', category: 'funny' },
  { question: 'Kurrë nuk kam ngatërruar emrat e dy miqve.', category: 'funny' },
  { question: 'Kurrë nuk kam pasur një bisedë grupi që u hesht pas një mesazhi.', category: 'funny' },
  { question: 'Kurrë nuk kam lënë një mesazh "të lexuar" për më shumë se një ditë.', category: 'relationships' },
  { question: 'Kurrë nuk kam bërë sikur kam lidhje të keqe për të mbyllur një thirrje.', category: 'funny' },
  { question: 'Kurrë nuk kam thënë "duhet të shkoj" kur nuk duhej.', category: 'funny' },
  { question: 'Kurrë nuk kam qenë në një festë ku nuk njihja askënd.', category: 'general' },
  { question: 'Kurrë nuk kam qenë i fundit që u largua nga një festë.', category: 'general' },
  { question: 'Kurrë nuk kam organizuar një festë që u jashtëkontrollua.', category: 'general' },
  { question: 'Kurrë nuk kam pastruar pas festës së dikujt tjetër.', category: 'general' },
  { question: 'Kurrë nuk kam pasur një bashkëbanor me të cilin nuk përputhesha.', category: 'relationships' },
  { question: 'Kurrë nuk më kanë organizuar një festë surprizë.', category: 'general' },
  { question: 'Kurrë nuk kam prishur një surprizë.', category: 'funny' },
  { question: 'Kurrë nuk kam harruar një përvjetor.', category: 'relationships' },
  { question: 'Kurrë nuk kam bërë skenë në një mbledhje familjare.', category: 'relationships' },
  { question: 'Kurrë nuk kam pasur një anëtar familje që i shmangem në festa.', category: 'relationships' },
  { question: 'Kurrë nuk kam genjitur familjen për vendin ku po shkoja.', category: 'childhood' },
  { question: 'Kurrë nuk kam futur fshehurazi dikë në shtëpinë time.', category: 'childhood' },
  { question: 'Kurrë nuk jam kapur duke bërë diçka që nuk duhej.', category: 'general' },
];
