module.exports = [
  { question: 'Hiç yaşım hakkında yalan söylemedim.', category: 'general' },
  { question: 'Hiç birinden kaçınmak için telefonla konuşuyormuş gibi yapmadım.', category: 'funny' },
  { question: 'Hiç duşta şarkı söylemedim.', category: 'general' },
  { question: 'Hiç kimse izlemezken dans etmedim.', category: 'general' },
  { question: 'Hiç film izlerken ağlamadım.', category: 'general' },
  { question: 'Hiç yanlış kişiye mesaj atmadım.', category: 'funny' },
  { question: 'Hiç birinin kendini tanıttıktan hemen sonra adını unutmadım.', category: 'funny' },
  { question: 'Hiç bana el sallamayan birine el sallayarak karşılık vermedim.', category: 'funny' },
  { question: 'Hiç yaptığım bir şey için köpeği suçlamadım.', category: 'funny' },
  { question: 'Hiç kendi adımı Google\'da aramadım.', category: 'general' },
  { question: 'Hiç bütün gece bir TV dizisi izleyerek uyumadım.', category: 'general' },
  { question: 'Hiç yere düşen yemeği yemedim.', category: 'food' },
  { question: 'Hiç hapşırığı öksürük diye yutturmaya çalışmadım.', category: 'funny' },
  { question: 'Hiç aslında internette gezinirken çalışıyormuş gibi yapmadım.', category: 'work' },
  { question: 'Hiç kafamda bir konuşmayı tekrarlayıp utandığımı hissetmedim.', category: 'general' },
  { question: 'Hiç bir öğretmene aşık olmadım.', category: 'childhood' },
  { question: 'Hiç aynada kendime bakarken yakalanmadım.', category: 'funny' },
  { question: 'Hiç o kadar çok gülüp ağlamadım.', category: 'general' },
  { question: 'Hiç bir odaya girip neden gittiğimi unutmadım.', category: 'funny' },
  { question: 'Hiç kendi hatam için teknolojiyi suçlamadım.', category: 'funny' },
  { question: 'Hiç tek başıma başka bir ülkeye seyahat etmedim.', category: 'travel' },
  { question: 'Hiç uçak ya da tren kaçırmadım.', category: 'travel' },
  { question: 'Hiç yabancı bir şehirde kaybolmadım.', category: 'travel' },
  { question: 'Hiç denemekten korktuğum bir yemeği denemedim.', category: 'food' },
  { question: 'Hiç son kullanma tarihi geçmiş bir şey yemedim.', category: 'food' },
  { question: 'Hiç restoranda her seferinde aynı şeyi sipariş etmedim.', category: 'food' },
  { question: 'Hiç yemekten önce tatlı yemedim.', category: 'food' },
  { question: 'Hiç özgeçmişimde yalan söylemedim.', category: 'work' },
  { question: 'Hiç hasta olmadığım halde hasta diye işe gelmedim.', category: 'work' },
  { question: 'Hiç toplantıda ya da derste uyuyakalmadım.', category: 'work' },
  { question: 'Hiç iş yerinde birine aşık olmadım.', category: 'work' },
  { question: 'Hiç önemli bir etkinliğe geç kalmadım.', category: 'general' },
  { question: 'Hiç bir arkadaşımın evinde bir şey kırıp söylemedim.', category: 'relationships' },
  { question: 'Hiç gizli bir hayranım olmadı.', category: 'relationships' },
  { question: 'Hiç arkadaş bölgesine düşmedim.', category: 'relationships' },
  { question: 'Hiç bir gecelik ilişkim olmadı.', category: 'risky' },
  { question: 'Hiç bir yabancıyı öpmedim.', category: 'risky' },
  { question: 'Hiç dövme yaptırmadım.', category: 'general' },
  { question: 'Hiç kulak memesi dışında bir yere piercing yaptırmadım.', category: 'general' },
  { question: 'Hiç saçımı çılgın bir renge boyatmadım.', category: 'general' },
  { question: 'Hiç konsere gitmedim.', category: 'general' },
  { question: 'Hiç müzik festivaline gitmedim.', category: 'general' },
  { question: 'Hiç bir ünlüyle tanışmadım.', category: 'general' },
  { question: 'Hiç TV\'de ya da viral bir videoda yer almadım.', category: 'general' },
  { question: 'Hiç maraton ya da yarı maraton koşmadım.', category: 'general' },
  { question: 'Hiç paraşüt ya da bungee jumping yapmadım.', category: 'risky' },
  { question: 'Hiç hız trenine binmedim.', category: 'general' },
  { question: 'Hiç gece okyanusta yüzmedim.', category: 'travel' },
  { question: 'Hiç doğada kamp yapmadım.', category: 'travel' },
  { question: 'Hiç otostop yapmadım.', category: 'risky' },
  { question: 'Hiç havalimanında uyumadım.', category: 'travel' },
  { question: 'Hiç 10\'dan fazla ülkeye gitmedim.', category: 'travel' },
  { question: 'Hiç başka bir dili akıcı konuşmayı öğrenmedim.', category: 'general' },
  { question: 'Hiç başka bir ülkede yaşamadım.', category: 'travel' },
  { question: 'Hiç başka ülkeden mektup arkadaşım olmadı.', category: 'childhood' },
  { question: 'Hiç düğüne gitmedim.', category: 'relationships' },
  { question: 'Hiç cenazeye gitmedim.', category: 'general' },
  { question: 'Hiç kavga etmedim.', category: 'risky' },
  { question: 'Hiç polis tarafından durdurulmadım.', category: 'risky' },
  { question: 'Hiç kumarhaneye gitmedim.', category: 'risky' },
  { question: 'Hiç kaybetmeyi göze alamayacağım parayla kumar oynamadım.', category: 'risky' },
  { question: 'Hiç kemiğim kırılmadı.', category: 'general' },
  { question: 'Hiç dikiş atmadım.', category: 'general' },
  { question: 'Hiç bayılmadım.', category: 'general' },
  { question: 'Hiç hastanede bir gece kalmadım.', category: 'general' },
  { question: 'Hiç acile gitmedim.', category: 'general' },
  { question: 'Hiç ölüme yakın bir deneyim yaşamadım.', category: 'risky' },
  { question: 'Hiç birinin hayatını kurtarmadım.', category: 'general' },
  { question: 'Hiç trafik kazası geçirmedim.', category: 'general' },
  { question: 'Hiç hız cezası almadım.', category: 'risky' },
  { question: 'Hiç motosiklet sürmedim.', category: 'general' },
  { question: 'Hiç tüplü dalış yapmadım.', category: 'travel' },
  { question: 'Hiç sörf denemedim.', category: 'general' },
  { question: 'Hiç kayak ya da snowboard yapmadım.', category: 'general' },
  { question: 'Hiç dağa tırmanmadım.', category: 'travel' },
  { question: 'Hiç gemi turuna çıkmadım.', category: 'travel' },
  { question: 'Hiç okyanusun ortasında bir teknede olmadım.', category: 'travel' },
  { question: 'Hiç kuzey ışıklarını görmedim.', category: 'travel' },
  { question: 'Hiç vahşi bir hayvanı yakından görmedim.', category: 'travel' },
  { question: 'Hiç bir hayvan tarafından ısırılmadım.', category: 'general' },
  { question: 'Hiç kedi veya köpek olmayan bir evcil hayvanım olmadı.', category: 'general' },
  { question: 'Hiç bir şey çalmadım.', category: 'risky' },
  { question: 'Hiç tutuklanmadım ya da gözaltına alınmadım.', category: 'risky' },
  { question: 'Hiç striptiz kulübüne gitmedim.', category: 'risky' },
  { question: 'Hiç çıplak yüzmedim.', category: 'risky' },
  { question: 'Hiç toplum içinde çıplak olmadım.', category: 'risky' },
  { question: 'Hiç toplum içinde giyim hatası yaşamadım.', category: 'funny' },
  { question: 'Hiç banyoda birine yakalanmadım.', category: 'funny' },
  { question: 'Hiç banyodayken biri beni görmedi.', category: 'funny' },
  { question: 'Hiç bu odadaki biri hakkında rüya görmedim.', category: 'risky' },
  { question: 'Hiç bir arkadaşımın eski sevgilisine aşık olmadım.', category: 'relationships' },
  { question: 'Hiç aynı anda iki kişiyle çıkmadım.', category: 'relationships' },
  { question: 'Hiç kör randevuya çıkmadım.', category: 'relationships' },
  { question: 'Hiç internetten catfish\'e düşmedim ya da kandırılmadım.', category: 'relationships' },
  { question: 'Hiç birine DM\'den yazmadım.', category: 'relationships' },
  { question: 'Hiç ilk görüşte aşık olmadım.', category: 'relationships' },
  { question: 'Hiç uzaktan ilişkim olmadı.', category: 'relationships' },
  { question: 'Hiç bir eskiyle tekrar bir araya gelmedim.', category: 'relationships' },
  { question: 'Hiç ghost\'lanmadım.', category: 'relationships' },
  { question: 'Hiç birini ghost\'lamadım.', category: 'relationships' },
  { question: 'Hiç bir yıldan fazla karşılıksız aşk yaşamadım.', category: 'relationships' },
  { question: 'Hiç aşk mektubu yazmadım.', category: 'relationships' },
  { question: 'Hiç bana serenat yapılmadı ya da ben birine yapmadım.', category: 'relationships' },
  { question: 'Hiç yemek savaşı yapmadım.', category: 'childhood' },
  { question: 'Hiç müdür odasına gönderilmedim.', category: 'childhood' },
  { question: 'Hiç sınavda kopya çekmedim.', category: 'childhood' },
  { question: 'Hiç okuldan uzaklaştırılmadım ya da atılmadım.', category: 'childhood' },
  { question: 'Hiç okul için bütün gece uyumadım.', category: 'childhood' },
  { question: 'Hiç sahte kimlik kullanmadım.', category: 'risky' },
  { question: 'Hiç ergenken evden gizlice kaçmadım.', category: 'childhood' },
  { question: 'Hiç ailem yokken evde parti vermedim.', category: 'childhood' },
  { question: 'Hiç evde cam ya da değerli bir şey kırmadım.', category: 'childhood' },
  { question: 'Hiç bir haftadan fazla cezalandırılmadım.', category: 'childhood' },
  { question: 'Hiç aileme nerede olduğum konusunda yalan söylemedim.', category: 'childhood' },
  { question: 'Hiç birinin okuduğu bir günlüğüm olmadı.', category: 'childhood' },
  { question: 'Hiç okul oyununda ya da yetenek şovunda yer almadım.', category: 'childhood' },
  { question: 'Hiç takıma seçilen son kişi olmadım.', category: 'childhood' },
  { question: 'Hiç zorbalığa uğramadım ya da zorbalık yapmadım.', category: 'childhood' },
  { question: 'Hiç nefret ettiğim bir lakabım olmadı.', category: 'funny' },
  { question: 'Hiç photobomb\'a uğramadım ya da birini photobomb\'lamadım.', category: 'funny' },
  { question: 'Hiç selfie çekip hemen silmedim.', category: 'funny' },
  { question: 'Hiç bir şey paylaşım yapıp bir saat içinde silmedim.', category: 'funny' },
  { question: 'Hiç internetten bir yabancıyla tartışmadım.', category: 'funny' },
  { question: 'Hiç yanlışlıkla eski bir paylaşıma yorum yapmadım.', category: 'funny' },
  { question: 'Hiç kendi paylaşımıma ya da fotoğrafıma beğeni atmadım.', category: 'funny' },
  { question: 'Hiç yanlışlıkla birinin eski fotoğrafını beğenmedim.', category: 'funny' },
  { question: 'Hiç sosyal medyada biri tarafından engellenmedim.', category: 'relationships' },
  { question: 'Hiç gerçek hayatta tanıdığım birini engellemedim.', category: 'relationships' },
  { question: 'Hiç hiçbir platformda 1000\'den fazla takipçim olmadı.', category: 'general' },
  { question: 'Hiç utandırıcı bir şey yüzünden viral olmadım.', category: 'funny' },
  { question: 'Hiç yemek yapmayı deneyip berbat bir şekilde başarısız olmadım.', category: 'food' },
  { question: 'Hiç yemek yaparken duman alarmını tetiklemedim.', category: 'food' },
  { question: 'Hiç bir haftada ikiden fazla pizza siparişi vermedim.', category: 'food' },
  { question: 'Hiç tek başıma bütün bir pizza yemedim.', category: 'food' },
  { question: 'Hiç pişirilmesi gereken çiğ bir şey yemedim.', category: 'food' },
  { question: 'Hiç tuhaf bir yemek kombinasyonu denemedim.', category: 'food' },
  { question: 'Hiç açık büfeye gidip kendimi hasta etmedim.', category: 'food' },
  { question: 'Hiç ev arkadaşımdan ya da aile üyemden yemek çalmadım.', category: 'food' },
  { question: 'Hiç akşam yemeği yerine kahvaltı yemedim.', category: 'food' },
  { question: 'Hiç kafein bağımlılığım olmadı.', category: 'food' },
  { question: 'Hiç uyanık kalmak için enerji içeceği içmedim.', category: 'food' },
  { question: 'Hiç pijamayla drive-through\'da fast food\'a gitmedim.', category: 'funny' },
  { question: 'Hiç dökülen süt ya da düşen yemek yüzünden ağlamadım.', category: 'funny' },
  { question: 'Hiç aldığım bir hediyeyi beğeniyormuş gibi yapmadım.', category: 'relationships' },
  { question: 'Hiç bir hediyeyi başkasına hediye etmedim.', category: 'relationships' },
  { question: 'Hiç yakın bir arkadaşımın ya da aile üyemin doğum gününü unutmadım.', category: 'relationships' },
  { question: 'Hiç yanlış günde bir partiye gitmedim.', category: 'funny' },
  { question: 'Hiç kostümle giden tek kişi olmadım.', category: 'funny' },
  { question: 'Hiç partide uyuyakalmadım.', category: 'funny' },
  { question: 'Hiç designated driver oldum ve nefret ettim.', category: 'general' },
  { question: 'Hiç telefonumu kaybedip paniğe kapılmadım.', category: 'funny' },
  { question: 'Hiç telefonumu evde unutup çıplak gibi hissetmedim.', category: 'funny' },
  { question: 'Hiç telefonum tuvalete düşmedi.', category: 'funny' },
  { question: 'Hiç telefon ekranımı kırmadım.', category: 'general' },
  { question: 'Hiç sormadan birinin telefonunu kullanmadım.', category: 'relationships' },
  { question: 'Hiç birinin mesajlarına bakmadım.', category: 'relationships' },
  { question: 'Hiç birinin telefonuna bakarken yakalanmadım.', category: 'funny' },
  { question: 'Hiç "password" ya da "123456" şifrem olmadı.', category: 'funny' },
  { question: 'Hiç önemli bir şifreyi unutmadım.', category: 'funny' },
  { question: 'Hiç biri "iyi seyirler" dediğinde "sana da" diye cevap vermedim.', category: 'funny' },
  { question: 'Hiç aynı sohbette iki kez "hoşça kal" demedim.', category: 'funny' },
  { question: 'Hiç toplum içinde tökezlemedim.', category: 'funny' },
  { question: 'Hiç tanıdığımı sanıp bir yabancıya el sallamadım.', category: 'funny' },
  { question: 'Hiç itme kapısını çekerek açmaya çalışmadım.', category: 'funny' },
  { question: 'Hiç cam bir kapıya çarpmadım.', category: 'funny' },
  { question: 'Hiç basamak kaçırıp tökezlemedim.', category: 'funny' },
  { question: 'Hiç video görüşmede kamerada olduğumu unutmadım.', category: 'work' },
  { question: 'Hiç toplantıda ne konuşulduğuna dair hiç fikrim olmadı.', category: 'work' },
  { question: 'Hiç mesai saatlerinde şekerleme yapmadım.', category: 'work' },
  { question: 'Hiç nefret ettiğim bir işim olmadı.', category: 'work' },
  { question: 'Hiç başka iş sıralamadan işten ayrılmadım.', category: 'work' },
  { question: 'Hiç işten kovulmadım.', category: 'work' },
  { question: 'Hiç terfi almadım.', category: 'work' },
  { question: 'Hiç bir iş arkadaşımla rekabet etmedim.', category: 'work' },
  { question: 'Hiç bir iş arkadaşımla çıkmadım.', category: 'work' },
  { question: 'Hiç bir ünlüye aşık olmadım.', category: 'general' },
  { question: 'Hiç hayran mektubu yazmadım ya da ünlüye DM atmadım.', category: 'general' },
  { question: 'Hiç ünlü ayrılığı yüzünden ağlamadım.', category: 'funny' },
  { question: 'Hiç gece yarısı film galasına gitmedim.', category: 'general' },
  { question: 'Hiç film çıkışı için bir karaktere bürünmedim.', category: 'funny' },
  { question: 'Hiç aynı filmi 10\'dan fazla izlemedim.', category: 'general' },
  { question: 'Hiç sinemada uyuyakalmadım.', category: 'funny' },
  { question: 'Hiç hiçbir şarkı bilmeden konsere gitmedim.', category: 'funny' },
  { question: 'Hiç karaoke söylemedim.', category: 'general' },
  { question: 'Hiç masanın üstünde dans etmedim.', category: 'risky' },
  { question: 'Hiç toplum içinde sahne yapmadım.', category: 'funny' },
  { question: 'Hiç bir yerden kovulmadım.', category: 'risky' },
  { question: 'Hiç kanunla burun buruna gelmedim.', category: 'risky' },
  { question: 'Hiç birine ailesinden bir şey saklamasında yardım etmedim.', category: 'relationships' },
  { question: 'Hiç tutması çok zor bir sır saklamadım.', category: 'relationships' },
  { question: 'Hiç yanlışlıkla bir sır açığa vurmadım.', category: 'relationships' },
  { question: 'Hiç bir arkadaşım tarafından ihanete uğramadım.', category: 'relationships' },
  { question: 'Hiç bir arkadaşımın güvenini ihanet etmedim.', category: 'relationships' },
  { question: 'Hiç en iyi arkadaşımla kavga edip ayrılmadım.', category: 'relationships' },
  { question: 'Hiç yıllar sonra eski bir arkadaşla tekrar buluşmadım.', category: 'relationships' },
  { question: 'Hiç lise ya da üniversite buluşmasına gitmedim.', category: 'relationships' },
  { question: 'Hiç katlanamadığım bir ev arkadaşım olmadı.', category: 'relationships' },
  { question: 'Hiç katlanamadığım bir komşum olmadı.', category: 'relationships' },
  { question: 'Hiç aynı odadaki biri hakkında şikayet etmedim.', category: 'funny' },
  { question: 'Hiç biri hakkında konuşurken yakalanmadım.', category: 'funny' },
  { question: 'Hiç yanlış anda gülmedim.', category: 'funny' },
  { question: 'Hiç toplum içinde osurup ben değilmişim gibi yapmadım.', category: 'funny' },
  { question: 'Hiç giyim hatası yaşamadım.', category: 'funny' },
  { question: 'Hiç işte ya da okulda iki gün üst üste aynı kıyafeti giymedim.', category: 'general' },
  { question: 'Hiç yanlışlıkla kıyafetleri ters giymedim.', category: 'funny' },
  { question: 'Hiç iki farklı ayakkabı giymedim.', category: 'funny' },
  { question: 'Hiç pantolonsuz ya da pijamayla evden çıkmadım.', category: 'funny' },
  { question: 'Hiç berbat saç kesimi olup ağlamadım.', category: 'funny' },
  { question: 'Hiç kendi saçımı kendim kesmedim.', category: 'general' },
  { question: 'Hiç kendime kakül kesmeyi denemedim.', category: 'funny' },
  { question: 'Hiç permanente yaptırmadım.', category: 'general' },
  { question: 'Hiç o kadar güneş yanığı oldum ki uyuyamadım.', category: 'travel' },
  { question: 'Hiç çocukken mağazada kaybolmadım.', category: 'childhood' },
  { question: 'Hiç yetişkinken karanlıktan korkmadım.', category: 'general' },
  { question: 'Hiç tekrarlayan kabus görmedim.', category: 'general' },
  { question: 'Hiç uyurgezerlik yapmadım ya da uykuda konuşmadım.', category: 'general' },
  { question: 'Hiç gerçek gibi gelen ve günümü etkileyen bir rüya görmedim.', category: 'general' },
  { question: 'Hiç kabustan uyanıp birini aramadım.', category: 'general' },
  { question: 'Hiç hayaletlere ya da doğaüstü şeylere inanmadım.', category: 'general' },
  { question: 'Hiç hayalet ya da paranormal bir şey gördüğümü düşünmedim.', category: 'general' },
  { question: 'Hiç perili bir eve ya da yere gitmedim.', category: 'general' },
  { question: 'Hiç medyuma ya da tarot falcısına gitmedim.', category: 'general' },
  { question: 'Hiç sihir numarası öğrenmeyi denemedim.', category: 'general' },
  { question: 'Hiç backflip ya da amut deneyip başarısız olmadım.', category: 'funny' },
  { question: 'Hiç TikTok ya da viral dans öğrenmeyi denemedim.', category: 'funny' },
  { question: 'Hiç TikTok ya da Reel paylaşmadım.', category: 'general' },
  { question: 'Hiç sosyal medyada viral olmadım.', category: 'general' },
  { question: 'Hiç iznim olmadan fotoğrafım viral olmadı.', category: 'general' },
  { question: 'Hiç toplum içinde bir yabancı tarafından tanınmadım.', category: 'general' },
  { question: 'Hiç tek başıma tema parkına gitmedim.', category: 'travel' },
  { question: 'Hiç aynı oyuncuğa 5 kez üst üste binmedim.', category: 'general' },
  { question: 'Hiç bir oyuncakta kusmadım.', category: 'funny' },
  { question: 'Hiç bir oyuncakta korkup inmek zorunda kalmadım.', category: 'general' },
  { question: 'Hiç ekstrem spor denemedim.', category: 'risky' },
  { question: 'Hiç gönüllü olup pişman olmadım.', category: 'general' },
  { question: 'Hiç kan bağışı yapmadım.', category: 'general' },
  { question: 'Hiç kan görünce bayılmadım.', category: 'general' },
  { question: 'Hiç iğne korkum olmadı.', category: 'general' },
  { question: 'Hiç uçak korkum olmadı.', category: 'travel' },
  { question: 'Hiç panik atak geçirmedim.', category: 'general' },
  { question: 'Hiç meditasyon ya da yoga denemedim.', category: 'general' },
  { question: 'Hiç terapi ya da danışmanlığa gitmedim.', category: 'general' },
  { question: 'Hiç bir günden fazla birine küsmem.', category: 'relationships' },
  { question: 'Hiç yıllarca kin tutmadım.', category: 'relationships' },
  { question: 'Hiç haksızken özür dilemedim.', category: 'relationships' },
  { question: 'Hiç haklıyken özür dilemeyi reddetmedim.', category: 'relationships' },
  { question: 'Hiç toplum içinde biriyle tartışmadım.', category: 'relationships' },
  { question: 'Hiç büyük kavga sonrası biriyle barışmadım.', category: 'relationships' },
  { question: 'Hiç çifti iyi tanımadan düğüne gitmedim.', category: 'relationships' },
  { question: 'Hiç nedime ya da sağdıç olmadım.', category: 'relationships' },
  { question: 'Hiç buket ya da jartiyer yakalamadım.', category: 'relationships' },
  { question: 'Hiç düğünde konuşma yapmadım.', category: 'relationships' },
  { question: 'Hiç düğünde ağlamadım.', category: 'relationships' },
  { question: 'Hiç bebek shower\'ına gitmedim.', category: 'relationships' },
  { question: 'Hiç yeni doğmuş bir bebeği kucağımda tutmadım.', category: 'general' },
  { question: 'Hiç bez değiştirmedim.', category: 'general' },
  { question: 'Hiç bebek bakıcılığı yapmadım.', category: 'general' },
  { question: 'Hiç çocuk sahibi olmak istemedim.', category: 'general' },
  { question: 'Hiç çocuk sahibi olmamak istemedim.', category: 'general' },
  { question: 'Hiç evcil hayvanım ölüp ağlamadım.', category: 'general' },
  { question: 'Hiç bir evcil hayvanı gömmem.', category: 'general' },
  { question: 'Hiç cenazede yanlış anda gülmedim.', category: 'funny' },
  { question: 'Hiç cenazede konuşma yapmadım.', category: 'general' },
  { question: 'Hiç tanıdığım birinin mezarını ziyaret etmedim.', category: 'general' },
  { question: 'Hiç ölüme yakın deneyim yaşayıp hayatımı düşünmedim.', category: 'risky' },
  { question: 'Hiç bucket list yapmadım.', category: 'general' },
  { question: 'Hiç bucket list\'imden bir şeyi tamamlamadım.', category: 'general' },
  { question: 'Hiç yeni dil öğrenmeyi deneyip vazgeçmedim.', category: 'general' },
  { question: 'Hiç enstrüman çalmayı öğrenmedim.', category: 'general' },
  { question: 'Hiç enstrüman öğrenmeyi deneyip bırakmadım.', category: 'general' },
  { question: 'Hiç şarkı ya da şiir yazmadım.', category: 'general' },
  { question: 'Hiç gurur duyduğum bir şey çizmedim ya da boyamadım.', category: 'general' },
  { question: 'Hiç süslü yemek yapmayı deneyip başarısız olmadım.', category: 'food' },
  { question: 'Hiç sıfırdan bir şey pişirmedim.', category: 'food' },
  { question: 'Hiç pişirdiğim bir şeyi yakmadım.', category: 'food' },
  { question: 'Hiç diyet deneyip bir hafta sonra bırakmadım.', category: 'food' },
  { question: 'Hiç vejetaryen ya da vegan olmadım.', category: 'food' },
  { question: 'Hiç kale ya da avokado tostu gibi yemek trendi denemedim.', category: 'food' },
  { question: 'Hiç kendi yetiştirdiğim bir şeyi yemedim.', category: 'food' },
  { question: 'Hiç çiftçi pazarına gitmedim.', category: 'food' },
  { question: 'Hiç şık restorana gidip underdressed hissetmedim.', category: 'food' },
  { question: 'Hiç restoranda yemeği geri göndermedim.', category: 'food' },
  { question: 'Hiç bahşiş bırakmadan ayrılmadım.', category: 'food' },
  { question: 'Hiç hesap konusunda tartışmadım.', category: 'relationships' },
  { question: 'Hiç bir arkadaşımla diyet yapmadım.', category: 'relationships' },
  { question: 'Hiç bir arkadaşımla saçma bir şey için yarışmadım.', category: 'relationships' },
  { question: 'Hiç biriyle gizli el sıkışma yapmadım.', category: 'childhood' },
  { question: 'Hiç hayali arkadaşım olmadı.', category: 'childhood' },
  { question: 'Hiç 10 yaşından sonra Noel Baba\'ya inanmadım.', category: 'childhood' },
  { question: 'Hiç diş perisi için yastığın altına diş koymadım.', category: 'childhood' },
  { question: 'Hiç palyaçolardan korkmadım.', category: 'general' },
  { question: 'Hiç sirke gitmedim.', category: 'general' },
  { question: 'Hiç hayvanat bahçesine gidip hayvanlar için üzülmedim.', category: 'general' },
  { question: 'Hiç ata binmedim.', category: 'general' },
  { question: 'Hiç böcek tarafından ısırılıp kötü reaksiyon geçirmedim.', category: 'general' },
  { question: 'Hiç örümcek ya da böcek korkum olmadı.', category: 'general' },
  { question: 'Hiç birinin için örümcek öldürmedim.', category: 'general' },
  { question: 'Hiç bir hayvan kurtarmadım.', category: 'general' },
  { question: 'Hiç barınaktan evcil hayvan sahiplenmedim.', category: 'general' },
  { question: 'Hiç evcil hayvan kaybetmedim.', category: 'general' },
  { question: 'Hiç evcil hayvanım kaçmadı.', category: 'general' },
  { question: 'Hiç planlardan sıyrılmak için meşgulüm diye yalan söylemedim.', category: 'general' },
  { question: 'Hiç biri çalarken şarkıyı beğeniyormuş gibi yapmadım.', category: 'funny' },
  { question: 'Hiç henüz çıkmamışken "yoldayım" demedim.', category: 'funny' },
  { question: 'Hiç birinin günlüğünü okumadım.', category: 'relationships' },
  { question: 'Hiç kendime verdiğim bir lakabım olmadı.', category: 'funny' },
  { question: 'Hiç randevuda üçüncü tekerlek olmadım.', category: 'relationships' },
  { question: 'Hiç yanlışlıkla bir eskinin paylaşımını beğenmedim.', category: 'funny' },
  { question: 'Hiç olması gerekenden uzun süre bir ilişkide kalmadım.', category: 'relationships' },
  { question: 'Hiç biri hakkında rüya görüp ertesi gün yanında garip hissetmedim.', category: 'general' },
  { question: 'Hiç bir diziyi beşten fazla izlemedim.', category: 'general' },
  { question: 'Hiç reklam izlerken ağlamadım.', category: 'funny' },
  { question: 'Hiç aynada kendimle konuşmadım.', category: 'funny' },
  { question: 'Hiç bir konuşmayı olmadan önce prova etmedim.', category: 'general' },
  { question: 'Hiç banka bakiyeme bakmaktan korkmadım.', category: 'general' },
  { question: 'Hiç karşılayamayacağım bir şey almadım.', category: 'general' },
  { question: 'Hiç hediye iade etmedim.', category: 'relationships' },
  { question: 'Hiç yakın bir arkadaşımın doğum gününü unutmadım.', category: 'relationships' },
  { question: 'Hiç kendi etkinliğime geç kalmadım.', category: 'funny' },
  { question: 'Hiç aynı cümlede iki kişinin adını karıştırmadım.', category: 'funny' },
  { question: 'Hiç görmeyeceğimi bildiğim birine "yarın görüşürüz" demedim.', category: 'funny' },
  { question: 'Hiç şakayı anlamıyormuş gibi yapıp yine de gülmedim.', category: 'funny' },
  { question: 'Hiç takip etmediğim bir sohbette kafa sallamadım.', category: 'funny' },
  { question: 'Hiç kırmızı ışıkta arabada şarkı söylerken yakalanmadım.', category: 'funny' },
  { question: 'Hiç kurgu bir karaktere aşık olmadım.', category: 'general' },
  { question: 'Hiç göndermediğim bir mektup yazmadım.', category: 'general' },
  { question: 'Hiç bir şeyi tamir etmeye çalışıp daha da kötüleştirmedim.', category: 'funny' },
  { question: 'Hiç yaptığım bir şey için başkasını suçlamadım.', category: 'relationships' },
  { question: 'Hiç birinin fikrini kendime mal etmedim.', category: 'work' },
  { question: 'Hiç beyaz yalanda yakalanmadım.', category: 'funny' },
  { question: 'Hiç bir hikayeyi daha ilginç yapmak için abartmadım.', category: 'general' },
  { question: 'Hiç bir arkadaşımın başarısına haset etmedim.', category: 'relationships' },
  { question: 'Hiç sosyal medyada kendimi birine kıyaslayıp kötü hissetmedim.', category: 'general' },
  { question: 'Hiç görünüşüm yüzünden fotoğraf silmedim.', category: 'general' },
  { question: 'Hiç iş görüşmesinden önce gergin olmadım.', category: 'work' },
  { question: 'Hiç yeni işte ilk günümü berbat etmedim.', category: 'work' },
  { question: 'Hiç sinemada film izlerken uyuyakalmadım.', category: 'funny' },
  { question: 'Hiç yediğim bir şeyden gıda zehirlenmesi geçirmedim.', category: 'food' },
  { question: 'Hiç sahip olmadığım bir yetenekle birini etkilemeye çalışmadım.', category: 'general' },
  { question: 'Hiç kamerada utandırıcı bir şey yaparken yakalanmadım.', category: 'funny' },
  { question: 'Hiç şimdi utandığım bir dönemim olmadı.', category: 'general' },
  { question: 'Hiç açıkça çok küçük ya da büyük bir şey giymedim.', category: 'funny' },
  { question: 'Hiç saç kesimine kötü tepki verip beğendiğimi söylemedim.', category: 'funny' },
  { question: 'Hiç 10 dakikadan fazla iyi selfie çekmeye çalışmadım.', category: 'funny' },
  { question: 'Hiç grup fotoğrafını berbat eden ben olmadım.', category: 'funny' },
  { question: 'Hiç cümlenin ortasında ne söylediğimi unutmadım.', category: 'funny' },
  { question: 'Hiç yanlışlıkla bir öğretmene "anne" ya da "baba" demedim.', category: 'childhood' },
  { question: 'Hiç kendinden emin yanlış yönde yürümedim.', category: 'funny' },
  { question: 'Hiç "çek" yazan kapıyı iterek açmaya çalışmadım.', category: 'funny' },
  { question: 'Hiç biri "özür dilerim" dediğinde "teşekkürler" demedim.', category: 'funny' },
  { question: 'Hiç bebeğe el sallayıp sonra bebeğin oyuncak olduğunu anlamadım.', category: 'funny' },
  { question: 'Hiç yetişkinken karanlıktan korkmadım.', category: 'general' },
  { question: 'Hiç yetişkinken peluş hayvanla uyumadım.', category: 'general' },
  { question: 'Hiç uğur getiren ya da batıl inancım olmadı.', category: 'general' },
  { question: 'Hiç kayan yıldızda dilek tutmadım.', category: 'general' },
  { question: 'Hiç ayna kırıp uğursuzluktan endişelenmedim.', category: 'general' },
  { question: 'Hiç merdiven altından geçmedim.', category: 'general' },
  { question: 'Hiç falcıya gitmedim.', category: 'general' },
  { question: 'Hiç bilinçli rüya görmeyi denemedim.', category: 'general' },
  { question: 'Hiç uyku felci yaşamadım.', category: 'general' },
  { question: 'Hiç uyanıp bir an nerede olduğumu bilmedim.', category: 'general' },
  { question: 'Hiç alarmı kaçırıp önemli bir şeyi kaçırmadım.', category: 'funny' },
  { question: 'Hiç ardışık üçten fazla erteleye basmadım.', category: 'funny' },
  { question: 'Hiç uykuda birinin duyduğu bir konuşma yapmadım.', category: 'funny' },
  { question: 'Hiç kendi horlamamla uyanmadım.', category: 'funny' },
  { question: 'Hiç kütüphanede uyuyakalmadım.', category: 'general' },
  { question: 'Hiç iş ya da okul dışında bir şey için bütün gece uyumadım.', category: 'general' },
  { question: 'Hiç şekerleme yapıp bütün gece uyumadım.', category: 'funny' },
  { question: 'Hiç karaoke barına gidip şarkı söylemeden dönmedim.', category: 'general' },
  { question: 'Hiç karaoke söyleyip sözleri unutmadım.', category: 'funny' },
  { question: 'Hiç komedi şovuna gidip komedyen tarafından hedef alınmadım.', category: 'funny' },
  { question: 'Hiç tema parkına gidip bir oyuncakta hasta olmadım.', category: 'travel' },
  { question: 'Hiç seyahatte bagajımı kaybetmedim.', category: 'travel' },
  { question: 'Hiç 5 saatten fazla gecikmiş uçuşum olmadı.', category: 'travel' },
  { question: 'Hiç uzun uçuşta sinir bozucu birinin yanında oturmadım.', category: 'travel' },
  { question: 'Hiç dilini bilmediğim bir ülkeye gitmedim.', category: 'travel' },
  { question: 'Hiç eve gelmeden kırılan bir hediyelik eşya almadım.', category: 'travel' },
  { question: 'Hiç seyahatte bir yabancıyla fotoğraf çektirmedim.', category: 'travel' },
  { question: 'Hiç sonradan pişman olduğum dövme yaptırmadım.', category: 'general' },
  { question: 'Hiç iltihap kapan piercing\'im olmadı.', category: 'general' },
  { question: 'Hiç evde saç boyamayı deneyip berbat etmedim.', category: 'funny' },
  { question: 'Hiç bitmesine sevindiğim bir moda dönemim olmadı.', category: 'general' },
  { question: 'Hiç karşı cinsin reyonundan bir şey giymedim.', category: 'general' },
  { question: 'Hiç aynı kıyafeti birden fazla renkte almadım.', category: 'general' },
  { question: 'Hiç anahtarlarımı kaybedip kendi evime zorla girmek zorunda kalmadım.', category: 'funny' },
  { question: 'Hiç kendimi evden ya da arabadan kilitlemedim.', category: 'funny' },
  { question: 'Hiç arabamı nereye park ettiğimi unutmadım.', category: 'funny' },
  { question: 'Hiç yolda benzim bitmedi.', category: 'general' },
  { question: 'Hiç lastiğim patlamadı.', category: 'general' },
  { question: 'Hiç ortada kalan bir arabada olmadım.', category: 'travel' },
  { question: 'Hiç bir yabancıya arabası için yardım etmedim.', category: 'general' },
  { question: 'Hiç sokakta bir yabancıya para vermedim.', category: 'general' },
  { question: 'Hiç önemsediğim bir davaya gönüllü olmadım.', category: 'general' },
  { question: 'Hiç hayır kurumuna bağış yapmadım.', category: 'general' },
  { question: 'Hiç 5K ya da daha uzun yarış koşmadım.', category: 'general' },
  { question: 'Hiç spor salonuna yazılıp bir ay sonra bırakmadım.', category: 'general' },
  { question: 'Hiç spor deneyip iyi olmadığım için bırakmadım.', category: 'general' },
  { question: 'Hiç canlı maça gitmedim.', category: 'general' },
  { question: 'Hiç maç yüzünden ağlamadım.', category: 'general' },
  { question: 'Hiç maç ya da etkinlik için yüzümü boyamadım.', category: 'general' },
  { question: 'Hiç protesto ya da mitinge gitmedim.', category: 'general' },
  { question: 'Hiç online yorum yazmadım.', category: 'general' },
  { question: 'Hiç yorumlarda bir yabancıyla tartışmadım.', category: 'funny' },
  { question: 'Hiç tepki yüzünden attığım yorumu silmedim.', category: 'funny' },
  { question: 'Hiç tanıdığım biri tarafından engellenmedim.', category: 'relationships' },
  { question: 'Hiç tutamayacağım kadar büyük sırrım olmadı.', category: 'relationships' },
  { question: 'Hiç bir arkadaşımın sırrını başkasına anlatmadım.', category: 'relationships' },
  { question: 'Hiç önemsediğim biri tarafından yalanda yakalanmadım.', category: 'relationships' },
  { question: 'Hiç yıllar sonra yaptığım bir şey için özür dilemedim.', category: 'relationships' },
  { question: 'Hiç nasıl olduklarını görmek için bir eskiyle tekrar buluşmadım.', category: 'relationships' },
  { question: 'Hiç en iyi arkadaşıma aşık olmadım.', category: 'relationships' },
  { question: 'Hiç berbat giden kör randevuya çıkmadım.', category: 'relationships' },
  { question: 'Hiç arkadaşlığı bitiren ben olmadım.', category: 'relationships' },
  { question: 'Hiç sırada beklerken arkadaş edinmedim.', category: 'general' },
  { question: 'Hiç arkadaş olduğum bir komşum olmadı.', category: 'relationships' },
  { question: 'Hiç buluşmaya gidip pişman olmadım.', category: 'relationships' },
  { question: 'Hiç bir arkadaşı tanıtırken adını unutmadım.', category: 'funny' },
  { question: 'Hiç iki arkadaşın adını karıştırmadım.', category: 'funny' },
  { question: 'Hiç bir mesajdan sonra sessiz kalan grup sohbetim olmadı.', category: 'funny' },
  { question: 'Hiç bir mesajı bir günden fazla "okundu" bırakmadım.', category: 'relationships' },
  { question: 'Hiç görüşmeyi bitirmek için kötü bağlantı numarası yapmadım.', category: 'funny' },
  { question: 'Hiç gitmem gerekmezken "gitmem lazım" demedim.', category: 'funny' },
  { question: 'Hiç kimseyi tanımadığım bir partiye gitmedim.', category: 'general' },
  { question: 'Hiç partiden ayrılan son kişi olmadım.', category: 'general' },
  { question: 'Hiç kontrolden çıkan parti vermedim.', category: 'general' },
  { question: 'Hiç başkasının partisinden sonra temizlik yapmadım.', category: 'general' },
  { question: 'Hiç anlaşamadığım ev arkadaşım olmadı.', category: 'relationships' },
  { question: 'Hiç bana sürpriz parti düzenlenmedi.', category: 'general' },
  { question: 'Hiç sürprizi berbat etmedim.', category: 'funny' },
  { question: 'Hiç yıldönümü unutmadım.', category: 'relationships' },
  { question: 'Hiç aile toplantısında sahne yapmadım.', category: 'relationships' },
  { question: 'Hiç bayramlarda kaçındığım bir aile üyem olmadı.', category: 'relationships' },
  { question: 'Hiç aileme nereye gideceğim konusunda yalan söylemedim.', category: 'childhood' },
  { question: 'Hiç birini evime gizlice sokmadım.', category: 'childhood' },
  { question: 'Hiç yapmamam gereken bir şey yaparken yakalanmadım.', category: 'general' },
];
