const truths = [
  { text: 'What is your biggest fear?', category: 'general' },
  { text: 'What is the most embarrassing thing that happened to you?', category: 'funny' },
  { text: 'Have you ever lied to get out of plans?', category: 'general' },
  { text: 'What is your guilty pleasure?', category: 'general' },
  { text: 'Who was your first crush?', category: 'friendship' },
  { text: 'What is the worst thing you have said about a friend?', category: 'risky' },
  { text: 'Have you ever cheated on a test?', category: 'general' },
  { text: 'What is your biggest regret?', category: 'general' },
  { text: 'Have you ever had a crush on a friend\'s partner?', category: 'risky' },
  { text: 'What is the silliest thing you believe in?', category: 'funny' },
  { text: 'What is your most irrational fear?', category: 'general' },
  { text: 'Have you ever pretended to like a gift?', category: 'funny' },
  { text: 'What is the meanest thing you have done?', category: 'risky' },
  { text: 'Who do you have a secret crush on right now?', category: 'risky' },
  { text: 'What is something you have never told anyone?', category: 'risky' },
  { text: 'Have you ever broken someone\'s heart?', category: 'friendship' },
  { text: 'What is your most embarrassing habit?', category: 'funny' },
  { text: 'Have you ever spread a rumor?', category: 'risky' },
  { text: 'What is the worst date you have ever been on?', category: 'general' },
  { text: 'Have you ever been in love?', category: 'friendship' },
  { text: 'What is your biggest insecurity?', category: 'general' },
  { text: 'Have you ever stolen something?', category: 'risky' },
  { text: 'What is the most childish thing you still do?', category: 'funny' },
  { text: 'Have you ever lied to your parents?', category: 'general' },
  { text: 'What is your secret talent?', category: 'general' },
  { text: 'Have you ever had a near-death experience?', category: 'general' },
  { text: 'What is the worst thing you have done while drunk?', category: 'risky' },
  { text: 'Have you ever been rejected?', category: 'friendship' },
  { text: 'What is your biggest pet peeve?', category: 'general' },
  { text: 'Have you ever been caught in a lie?', category: 'funny' },
  { text: 'What would you do if you had one day left to live?', category: 'challenge' },
  { text: 'What is the most trouble you have been in?', category: 'risky' },
  { text: 'Have you ever had a one-night stand?', category: 'risky' },
  { text: 'What is your most controversial opinion?', category: 'challenge' },
  { text: 'Have you ever betrayed a friend?', category: 'risky' },
  { text: 'What is your biggest secret?', category: 'risky' },
  { text: 'Have you ever been in a physical fight?', category: 'risky' },
  { text: 'What is the worst job you have ever had?', category: 'general' },
  { text: 'Have you ever been arrested or detained?', category: 'risky' },
  { text: 'What is something you would never do again?', category: 'general' },
  { text: 'What is the most embarrassing song on your playlist?', category: 'funny' },
  { text: 'Have you ever had a crush on a teacher or boss?', category: 'risky' },
  { text: 'What is the worst lie you have ever told?', category: 'risky' },
  { text: 'Have you ever been caught doing something you shouldn\'t?', category: 'general' },
  { text: 'What is your most embarrassing childhood memory?', category: 'funny' },
  { text: 'Have you ever ghosted someone?', category: 'friendship' },
  { text: 'What is the strangest dream you have ever had?', category: 'general' },
  { text: 'Have you ever had a secret you couldn\'t keep?', category: 'risky' },
  { text: 'What is the most reckless thing you have done?', category: 'risky' },
  { text: 'Have you ever had a crush on a friend\'s sibling?', category: 'friendship' },
  { text: 'What is something you are proud of but never share?', category: 'general' },
  { text: 'Have you ever pretended to be sick to skip something?', category: 'funny' },
  { text: 'What is your biggest turn-off in a person?', category: 'general' },
  { text: 'Have you ever been stood up on a date?', category: 'friendship' },
  { text: 'What is the most money you have ever spent on something silly?', category: 'general' },
  { text: 'Have you ever had a near-miss with the law?', category: 'risky' },
  { text: 'What is the worst gift you have ever received?', category: 'funny' },
  { text: 'Have you ever been in love with two people at once?', category: 'risky' },
  { text: 'What is your most controversial food opinion?', category: 'challenge' },
  { text: 'Have you ever lied on your resume?', category: 'risky' },
  { text: 'What is the most childish thing you still enjoy?', category: 'funny' },
  { text: 'Have you ever had a friendship end badly?', category: 'friendship' },
  { text: 'What is something you would do if nobody would judge you?', category: 'challenge' },
  { text: 'Have you ever been caught checking someone out?', category: 'funny' },
  { text: 'What is your biggest irrational pet peeve?', category: 'general' },
  { text: 'Have you ever had a one-sided friendship?', category: 'friendship' },
  { text: 'What is the worst thing you have said behind someone\'s back?', category: 'risky' },
  { text: 'Have you ever faked being busy to avoid someone?', category: 'funny' },
  { text: 'What is your guilty pleasure TV show or movie?', category: 'general' },
  { text: 'Have you ever had a crush on someone in this room?', category: 'risky' },
  { text: 'What is the most embarrassing thing your parents have done?', category: 'funny' },
  { text: 'Have you ever been caught in an awkward situation?', category: 'funny' },
  { text: 'What is something you regret saying?', category: 'general' },
  { text: 'Have you ever had a secret admirer?', category: 'friendship' },
  { text: 'What is the worst habit you have?', category: 'general' },
  { text: 'Have you ever been the "other person" in a situation?', category: 'risky' },
  { text: 'What is the most embarrassing thing in your search history?', category: 'funny' },
  { text: 'Have you ever pretended to know someone you didn\'t?', category: 'funny' },
  { text: 'What is your biggest fear about the future?', category: 'general' },
  { text: 'Have you ever had a crush on a celebrity that you are embarrassed about?', category: 'funny' },
  { text: 'What is the most selfish thing you have done?', category: 'risky' },
  { text: 'Have you ever been caught lying to your partner?', category: 'risky' },
  { text: 'What is the weirdest thing you find attractive?', category: 'challenge' },
  { text: 'Have you ever had a dream about someone in this room?', category: 'risky' },
  { text: 'What is the worst rumor you have heard about yourself?', category: 'general' },
  { text: 'Have you ever stayed in a relationship you knew was wrong?', category: 'friendship' },
  { text: 'What is the most embarrassing thing you have done to impress someone?', category: 'funny' },
  { text: 'Have you ever been caught talking to yourself?', category: 'funny' },
  { text: 'What is your biggest insecurity about your appearance?', category: 'general' },
  { text: 'Have you ever had a secret that could ruin a friendship?', category: 'risky' },
  { text: 'What is the most childish argument you have had?', category: 'funny' },
  { text: 'Have you ever been jealous of a friend\'s success?', category: 'friendship' },
  { text: 'What is the worst advice you have ever given?', category: 'general' },
  { text: 'Have you ever had a crush on someone much older or younger?', category: 'risky' },
  { text: 'What is the most embarrassing thing you have done at work or school?', category: 'funny' },
  { text: 'What is the last thing you searched for online?', category: 'general' },
  { text: 'Have you ever had a fake ID?', category: 'risky' },
  { text: 'What is your go-to karaoke song?', category: 'funny' },
  { text: 'Have you ever been caught picking your nose?', category: 'funny' },
  { text: 'What is the weirdest food combination you enjoy?', category: 'general' },
  { text: 'Have you ever cried at a movie?', category: 'friendship' },
  { text: 'What is your most used excuse for being late?', category: 'general' },
  { text: 'Have you ever had a wardrobe malfunction in public?', category: 'funny' },
  { text: 'What is the last thing you bought that you regret?', category: 'general' },
  { text: 'Have you ever had a crush on a cartoon character?', category: 'funny' },
  { text: 'What is your biggest fear about relationships?', category: 'general' },
  { text: 'Have you ever snooped through someone else\'s phone?', category: 'risky' },
  { text: 'What is the most embarrassing thing in your room?', category: 'funny' },
  { text: 'Have you ever pretended to read a book you never finished?', category: 'funny' },
  { text: 'What is your secret hobby?', category: 'general' },
  { text: 'Have you ever been caught singing in the shower?', category: 'funny' },
  { text: 'What is the worst haircut you have ever had?', category: 'funny' },
  { text: 'Have you ever had a crush on a coworker?', category: 'risky' },
  { text: 'What is something you are weirdly good at?', category: 'general' },
  { text: 'Have you ever blamed a sibling for something you did?', category: 'friendship' },
  { text: 'What is your most embarrassing moment from childhood?', category: 'funny' },
  { text: 'Have you ever sent a text to the wrong person?', category: 'risky' },
  { text: 'What is the strangest compliment you have received?', category: 'general' },
  { text: 'Have you ever had a dream that felt too real?', category: 'general' },
  { text: 'What is your guilty pleasure snack?', category: 'general' },
  { text: 'Have you ever been caught in a white lie?', category: 'funny' },
  { text: 'What is the worst fashion phase you went through?', category: 'funny' },
  { text: 'Have you ever had a near-miss while driving?', category: 'risky' },
  { text: 'What is something you would never admit in person?', category: 'challenge' },
  { text: 'Have you ever had a crush on a friend\'s ex?', category: 'risky' },
  { text: 'What is your most embarrassing autocorrect fail?', category: 'funny' },
  { text: 'Have you ever pretended to be on a call to avoid someone?', category: 'funny' },
  { text: 'What is the worst present you have ever given?', category: 'general' },
  { text: 'Have you ever been caught doing something embarrassing?', category: 'funny' },
  { text: 'What is your biggest fear about getting older?', category: 'general' },
  { text: 'Have you ever had a secret handshake with someone?', category: 'friendship' },
  { text: 'What is the most childish thing you still find funny?', category: 'funny' },
  { text: 'Have you ever lied about your age?', category: 'risky' },
  { text: 'What is the worst advice you have ever followed?', category: 'general' },
  { text: 'Have you ever had a crush on someone you just met?', category: 'friendship' },
  { text: 'What is your most embarrassing moment from a party?', category: 'funny' },
  { text: 'Have you ever been caught talking in your sleep?', category: 'funny' },
  { text: 'What is the weirdest thing you have ever eaten?', category: 'general' },
  { text: 'Have you ever had a friendship that started with a lie?', category: 'risky' },
  { text: 'What is your biggest fear about being judged?', category: 'general' },
  { text: 'Have you ever pretended to like a song to fit in?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have said out loud?', category: 'funny' },
  { text: 'Have you ever had a secret code with a friend?', category: 'friendship' },
  { text: 'What is the worst date idea you have ever had?', category: 'general' },
  { text: 'Have you ever been caught dancing when you thought no one was watching?', category: 'funny' },
  { text: 'What is the last app you downloaded?', category: 'general' },
  { text: 'Have you ever had a nickname you hated?', category: 'funny' },
  { text: 'What is your biggest pet peeve in a roommate?', category: 'general' },
  { text: 'Have you ever pretended to be sick to get attention?', category: 'funny' },
  { text: 'What is the most reckless purchase you have made?', category: 'general' },
  { text: 'Have you ever had a crush on a stranger you saw once?', category: 'friendship' },
  { text: 'What is the worst joke you have ever told?', category: 'funny' },
  { text: 'Have you ever been caught looking at yourself in a mirror?', category: 'funny' },
  { text: 'What is your secret comfort food?', category: 'general' },
  { text: 'Have you ever lied about your height or weight?', category: 'risky' },
  { text: 'What is the most embarrassing thing your sibling has done?', category: 'funny' },
  { text: 'Have you ever had a dream about someone you dislike?', category: 'general' },
  { text: 'What is the worst habit you picked up from someone?', category: 'general' },
  { text: 'Have you ever been caught taking a selfie?', category: 'funny' },
  { text: 'What is your biggest fear about failure?', category: 'general' },
  { text: 'Have you ever had a secret you told one person but not others?', category: 'risky' },
  { text: 'What is the most embarrassing thing you have done for likes?', category: 'funny' },
  { text: 'Have you ever pretended to understand a joke you did not get?', category: 'funny' },
  { text: 'What is the worst rumor you have ever spread?', category: 'risky' },
  { text: 'Have you ever had a crush on a character in a book or show?', category: 'funny' },
  { text: 'What is your most embarrassing moment from gym class?', category: 'funny' },
  { text: 'Have you ever been caught talking to your pet like a person?', category: 'funny' },
  { text: 'What is the strangest thing you have ever believed as a kid?', category: 'funny' },
  { text: 'Have you ever had a friendship end over a misunderstanding?', category: 'friendship' },
  { text: 'What is your biggest fear about being alone?', category: 'general' },
  { text: 'Have you ever pretended to be busy when you were not?', category: 'funny' },
  { text: 'What is the most embarrassing thing in your browser history?', category: 'risky' },
  { text: 'Have you ever been caught singing in the car?', category: 'funny' },
  { text: 'What is the worst pickup line you have used or heard?', category: 'funny' },
  { text: 'Have you ever had a secret that you eventually told?', category: 'risky' },
  { text: 'What is your most irrational pet peeve?', category: 'general' },
  { text: 'Have you ever pretended to work when you were slacking?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done to get attention?', category: 'funny' },
  { text: 'Have you ever been jealous of a friend\'s relationship?', category: 'friendship' },
  { text: 'What is the worst fashion choice you have ever made?', category: 'funny' },
  { text: 'Have you ever had a crush on someone who did not like you back?', category: 'friendship' },
  { text: 'What is your biggest fear about commitment?', category: 'general' },
  { text: 'Have you ever been caught daydreaming in class or work?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have posted online?', category: 'funny' },
  { text: 'Have you ever lied about where you were?', category: 'risky' },
  { text: 'What is the weirdest dream you have had about someone here?', category: 'challenge' },
  { text: 'Have you ever had a secret admirer you never told anyone about?', category: 'friendship' },
  { text: 'What is your most embarrassing moment from a family gathering?', category: 'funny' },
  { text: 'Have you ever been caught making a funny face in a photo?', category: 'funny' },
  { text: 'What is the worst thing you have done when you were angry?', category: 'risky' },
  { text: 'Have you ever had a crush on a friend\'s crush?', category: 'risky' },
  { text: 'What is your biggest fear about being vulnerable?', category: 'general' },
  { text: 'Have you ever pretended to like a food you hate?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done on a date?', category: 'funny' },
  { text: 'Have you ever been caught laughing at your own joke?', category: 'funny' },
  { text: 'What is the worst lie you have told to avoid plans?', category: 'general' },
  { text: 'Have you ever had a friendship that you regret ending?', category: 'friendship' },
  { text: 'What is your most embarrassing moment from a vacation?', category: 'funny' },
  { text: 'Have you ever been caught talking to yourself in public?', category: 'funny' },
  { text: 'What is the strangest thing you collect or used to collect?', category: 'general' },
  { text: 'Have you ever had a crush on someone in a position of power?', category: 'risky' },
  { text: 'What is your biggest fear about rejection?', category: 'general' },
  { text: 'Have you ever pretended to have seen a movie you have not?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a wedding?', category: 'funny' },
  { text: 'Have you ever been caught doing something you said you would never do?', category: 'funny' },
  { text: 'What is the worst excuse you have ever used?', category: 'general' },
  { text: 'Have you ever had a secret that could change a relationship?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a job interview?', category: 'funny' },
  { text: 'Have you ever been jealous of a sibling?', category: 'friendship' },
  { text: 'What is the weirdest thing you have done when no one was watching?', category: 'challenge' },
  { text: 'Have you ever had a crush on someone who was wrong for you?', category: 'friendship' },
  { text: 'What is your biggest fear about success?', category: 'general' },
  { text: 'Have you ever pretended to be asleep to avoid someone?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a restaurant?', category: 'funny' },
  { text: 'Have you ever been caught watching something embarrassing?', category: 'funny' },
  { text: 'What is the worst decision you have made on a whim?', category: 'general' },
  { text: 'Have you ever had a secret that you are still keeping?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a first date?', category: 'funny' },
  { text: 'Have you ever been the last to know something about a friend?', category: 'friendship' },
  { text: 'What is the strangest habit you have?', category: 'general' },
  { text: 'Have you ever had a crush on someone you should not have?', category: 'risky' },
  { text: 'What is your biggest fear about change?', category: 'general' },
  { text: 'Have you ever pretended to be confident when you were not?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a sleepover?', category: 'funny' },
  { text: 'Have you ever been caught in an embarrassing photo?', category: 'funny' },
  { text: 'What is the worst thing you have said in the heat of the moment?', category: 'risky' },
  { text: 'Have you ever had a friendship that felt one-sided?', category: 'friendship' },
  { text: 'What is your most embarrassing moment from a concert?', category: 'funny' },
  { text: 'Have you ever been caught singing in public?', category: 'funny' },
  { text: 'What is the weirdest thing you find comforting?', category: 'general' },
  { text: 'Have you ever had a crush on someone you met online?', category: 'risky' },
  { text: 'What is your biggest fear about the unknown?', category: 'general' },
  { text: 'Have you ever pretended to be interested in a topic you hate?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a reunion?', category: 'funny' },
  { text: 'Have you ever been caught doing something childish?', category: 'funny' },
  { text: 'What is the worst thing you have done to impress someone?', category: 'risky' },
  { text: 'Have you ever had a secret that you wish you could tell?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a holiday?', category: 'funny' },
  { text: 'Have you ever been the one who caused a friendship to end?', category: 'friendship' },
  { text: 'What is the strangest fear you had as a child?', category: 'funny' },
  { text: 'Have you ever had a crush on someone you never told?', category: 'friendship' },
  { text: 'What is your biggest fear about trust?', category: 'general' },
  { text: 'Have you ever pretended to be happy when you were not?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a funeral?', category: 'funny' },
  { text: 'Have you ever been caught in a lie by a friend?', category: 'risky' },
  { text: 'What is the worst thing you have done when you were bored?', category: 'general' },
  { text: 'Have you ever had a secret that made you feel guilty?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a birthday party?', category: 'funny' },
  { text: 'Have you ever been the third wheel?', category: 'friendship' },
  { text: 'What is the weirdest thing you have ever said to someone?', category: 'general' },
  { text: 'Have you ever had a crush on someone who was taken?', category: 'risky' },
  { text: 'What is your biggest fear about love?', category: 'general' },
  { text: 'Have you ever pretended to be someone you are not online?', category: 'risky' },
  { text: 'What is the most embarrassing thing you have done at a meeting?', category: 'funny' },
  { text: 'Have you ever been caught doing something you are ashamed of?', category: 'risky' },
  { text: 'What is the worst thing you have done when you were drunk?', category: 'risky' },
  { text: 'Have you ever had a friendship that you miss?', category: 'friendship' },
  { text: 'What is your most embarrassing moment from a sports event?', category: 'funny' },
  { text: 'Have you ever been caught in an awkward silence?', category: 'funny' },
  { text: 'What is the strangest thing you have ever wanted?', category: 'general' },
  { text: 'Have you ever had a crush on someone you work with?', category: 'risky' },
  { text: 'What is your biggest fear about being misunderstood?', category: 'general' },
  { text: 'Have you ever pretended to forget something on purpose?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a wedding?', category: 'funny' },
  { text: 'Have you ever been the one who had to end a friendship?', category: 'friendship' },
  { text: 'What is the worst thing you have done for money?', category: 'risky' },
  { text: 'Have you ever had a secret that you are afraid to tell?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a presentation?', category: 'funny' },
  { text: 'Have you ever been caught in a compromising position?', category: 'risky' },
  { text: 'What is the weirdest thing you have ever done for fun?', category: 'general' },
  { text: 'Have you ever had a crush on someone you barely know?', category: 'friendship' },
  { text: 'What is your biggest fear about disappointing others?', category: 'general' },
  { text: 'Have you ever pretended to be sick to skip work or school?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a party?', category: 'funny' },
  { text: 'Have you ever been the one who was ghosted?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were jealous?', category: 'risky' },
  { text: 'Have you ever had a secret that could hurt someone?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a photoshoot?', category: 'funny' },
  { text: 'Have you ever been caught in a silly argument?', category: 'funny' },
  { text: 'What is the strangest thing you have ever tried?', category: 'general' },
  { text: 'Have you ever had a crush on someone you see every day?', category: 'friendship' },
  { text: 'What is your biggest fear about being left out?', category: 'general' },
  { text: 'Have you ever pretended to be tired to leave early?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a bar?', category: 'funny' },
  { text: 'Have you ever been the one who spread a rumor?', category: 'risky' },
  { text: 'What is the worst thing you have done when you were stressed?', category: 'general' },
  { text: 'Have you ever had a secret that you shared with the wrong person?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a trip?', category: 'funny' },
  { text: 'Have you ever been caught in a moment of weakness?', category: 'general' },
  { text: 'What is the weirdest thing you have ever believed?', category: 'general' },
  { text: 'Have you ever had a crush on someone who ghosted you?', category: 'friendship' },
  { text: 'What is your biggest fear about being replaced?', category: 'general' },
  { text: 'Have you ever pretended to be fine when you were hurt?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a club?', category: 'funny' },
  { text: 'Have you ever been the one who was betrayed?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were scared?', category: 'general' },
  { text: 'Have you ever had a secret that you regret telling?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a class?', category: 'funny' },
  { text: 'Have you ever been caught in a funny situation?', category: 'funny' },
  { text: 'What is the strangest thing you have ever said to a stranger?', category: 'general' },
  { text: 'Have you ever had a crush on someone you cannot have?', category: 'friendship' },
  { text: 'What is your biggest fear about being forgotten?', category: 'general' },
  { text: 'Have you ever pretended to agree when you did not?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a concert?', category: 'funny' },
  { text: 'Have you ever been the one who had to apologize?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were tired?', category: 'general' },
  { text: 'Have you ever had a secret that you are proud of?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a dinner?', category: 'funny' },
  { text: 'Have you ever been caught in a lie by family?', category: 'risky' },
  { text: 'What is the weirdest thing you have ever done alone?', category: 'general' },
  { text: 'Have you ever had a crush on someone from your past?', category: 'friendship' },
  { text: 'What is your biggest fear about being judged by family?', category: 'general' },
  { text: 'Have you ever pretended to be cool when you were nervous?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a cafe?', category: 'funny' },
  { text: 'Have you ever been the one who was rejected?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were sad?', category: 'general' },
  { text: 'Have you ever had a secret that you wrote down somewhere?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a flight?', category: 'funny' },
  { text: 'Have you ever been caught in a weird habit?', category: 'funny' },
  { text: 'What is the strangest thing you have ever done with friends?', category: 'general' },
  { text: 'Have you ever had a crush on someone you fought with?', category: 'friendship' },
  { text: 'What is your biggest fear about being vulnerable with friends?', category: 'general' },
  { text: 'Have you ever pretended to be brave when you were scared?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a mall?', category: 'funny' },
  { text: 'Have you ever been the one who had to forgive?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were happy?', category: 'general' },
  { text: 'Have you ever had a secret that you almost told?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a hike?', category: 'funny' },
  { text: 'Have you ever been caught in a moment of honesty?', category: 'general' },
  { text: 'What is the weirdest thing you have ever done at night?', category: 'general' },
  { text: 'Have you ever had a crush on someone you admire?', category: 'friendship' },
  { text: 'What is your biggest fear about being too much?', category: 'general' },
  { text: 'Have you ever pretended to be chill when you were freaking out?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a pool?', category: 'funny' },
  { text: 'Have you ever been the one who had to say sorry first?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were angry at someone?', category: 'risky' },
  { text: 'Have you ever had a secret that you keep from your family?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a beach trip?', category: 'funny' },
  { text: 'Have you ever been caught in a silly moment?', category: 'funny' },
  { text: 'What is the strangest thing you have ever done in the morning?', category: 'general' },
  { text: 'Have you ever had a crush on someone who made you nervous?', category: 'friendship' },
  { text: 'What is your biggest fear about not being enough?', category: 'general' },
  { text: 'Have you ever pretended to know something you did not?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a gym?', category: 'funny' },
  { text: 'Have you ever been the one who had to let go?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were embarrassed?', category: 'general' },
  { text: 'Have you ever had a secret that you tell only one person?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a road trip?', category: 'funny' },
  { text: 'Have you ever been caught in a lazy moment?', category: 'funny' },
  { text: 'What is the weirdest thing you have ever done to relax?', category: 'general' },
  { text: 'Have you ever had a crush on someone who made you smile?', category: 'friendship' },
  { text: 'What is your biggest fear about being too little?', category: 'general' },
  { text: 'Have you ever pretended to be surprised when you were not?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a park?', category: 'funny' },
  { text: 'Have you ever been the one who had to move on?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were confused?', category: 'general' },
  { text: 'Have you ever had a secret that you are scared to share?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a camping trip?', category: 'funny' },
  { text: 'Have you ever been caught in a weird moment?', category: 'funny' },
  { text: 'What is the strangest thing you have ever done to cheer up?', category: 'general' },
  { text: 'Have you ever had a crush on someone who made you laugh?', category: 'friendship' },
  { text: 'What is your biggest fear about being boring?', category: 'general' },
  { text: 'Have you ever pretended to be busy to avoid a conversation?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a museum?', category: 'funny' },
  { text: 'Have you ever been the one who had to say goodbye?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were impatient?', category: 'general' },
  { text: 'Have you ever had a secret that you wrote in a diary?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a boat trip?', category: 'funny' },
  { text: 'Have you ever been caught in a happy moment?', category: 'funny' },
  { text: 'What is the weirdest thing you have ever done to procrastinate?', category: 'general' },
  { text: 'Have you ever had a crush on someone who was kind to you?', category: 'friendship' },
  { text: 'What is your biggest fear about being annoying?', category: 'general' },
  { text: 'Have you ever pretended to be listening when you were not?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a zoo?', category: 'funny' },
  { text: 'Have you ever been the one who had to start over?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were jealous of a friend?', category: 'risky' },
  { text: 'Have you ever had a secret that you typed but never sent?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a festival?', category: 'funny' },
  { text: 'Have you ever been caught in a sad moment?', category: 'general' },
  { text: 'What is the strangest thing you have ever done to impress?', category: 'general' },
  { text: 'Have you ever had a crush on someone who was funny?', category: 'friendship' },
  { text: 'What is your biggest fear about being too quiet?', category: 'general' },
  { text: 'Have you ever pretended to be asleep to listen to a conversation?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a theater?', category: 'funny' },
  { text: 'Have you ever been the one who had to make amends?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were in a bad mood?', category: 'general' },
  { text: 'Have you ever had a secret that you whispered to someone?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a picnic?', category: 'funny' },
  { text: 'Have you ever been caught in a romantic moment?', category: 'funny' },
  { text: 'What is the weirdest thing you have ever done to avoid work?', category: 'general' },
  { text: 'Have you ever had a crush on someone who was smart?', category: 'friendship' },
  { text: 'What is your biggest fear about being too loud?', category: 'general' },
  { text: 'Have you ever pretended to be sick to get out of a date?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a library?', category: 'funny' },
  { text: 'Have you ever been the one who had to admit the truth?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were jealous of a sibling?', category: 'risky' },
  { text: 'Have you ever had a secret that you are glad you kept?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a barbecue?', category: 'funny' },
  { text: 'Have you ever been caught in a nervous moment?', category: 'funny' },
  { text: 'What is the strangest thing you have ever done to fit in?', category: 'general' },
  { text: 'Have you ever had a crush on someone who was creative?', category: 'friendship' },
  { text: 'What is your biggest fear about being too serious?', category: 'general' },
  { text: 'Have you ever pretended to be awake when you were half asleep?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a bowling alley?', category: 'funny' },
  { text: 'Have you ever been the one who had to take the blame?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were jealous of a coworker?', category: 'risky' },
  { text: 'Have you ever had a secret that you are afraid might get out?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a karaoke night?', category: 'funny' },
  { text: 'Have you ever been caught in an excited moment?', category: 'funny' },
  { text: 'What is the weirdest thing you have ever done to celebrate?', category: 'general' },
  { text: 'Have you ever had a crush on someone who was talented?', category: 'friendship' },
  { text: 'What is your biggest fear about being too silly?', category: 'general' },
  { text: 'Have you ever pretended to be offended when you were not?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a bowling alley?', category: 'funny' },
  { text: 'Have you ever been the one who had to stand up for someone?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were jealous of an ex?', category: 'risky' },
  { text: 'Have you ever had a secret that you think about often?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a game night?', category: 'funny' },
  { text: 'Have you ever been caught in a thoughtful moment?', category: 'general' },
  { text: 'What is the strangest thing you have ever done to surprise someone?', category: 'general' },
  { text: 'Have you ever had a crush on someone who was mysterious?', category: 'friendship' },
  { text: 'What is your biggest fear about being too honest?', category: 'general' },
  { text: 'Have you ever pretended to be angry when you were not?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a casino?', category: 'funny' },
  { text: 'Have you ever been the one who had to keep a secret for someone?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were jealous of a stranger?', category: 'risky' },
  { text: 'Have you ever had a secret that you want to tell but cannot?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a dinner party?', category: 'funny' },
  { text: 'Have you ever been caught in a nostalgic moment?', category: 'general' },
  { text: 'What is the weirdest thing you have ever done to help someone?', category: 'general' },
  { text: 'Have you ever had a crush on someone who was adventurous?', category: 'friendship' },
  { text: 'What is your biggest fear about being too dependent?', category: 'general' },
  { text: 'Have you ever pretended to be sad when you were not?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a wedding reception?', category: 'funny' },
  { text: 'Have you ever been the one who had to break bad news?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were jealous of a celebrity?', category: 'funny' },
  { text: 'Have you ever had a secret that you shared too soon?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a baby shower?', category: 'funny' },
  { text: 'Have you ever been caught in a hopeful moment?', category: 'general' },
  { text: 'What is the strangest thing you have ever done to get revenge?', category: 'risky' },
  { text: 'Have you ever had a crush on someone who was calm?', category: 'friendship' },
  { text: 'What is your biggest fear about being too independent?', category: 'general' },
  { text: 'Have you ever pretended to be excited when you were not?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a baby shower?', category: 'funny' },
  { text: 'Have you ever been the one who had to comfort someone?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were jealous of a neighbor?', category: 'risky' },
  { text: 'Have you ever had a secret that you regret not telling?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a graduation?', category: 'funny' },
  { text: 'Have you ever been caught in a peaceful moment?', category: 'general' },
  { text: 'What is the weirdest thing you have ever done to get attention?', category: 'general' },
  { text: 'Have you ever had a crush on someone who was passionate?', category: 'friendship' },
  { text: 'What is your biggest fear about being too emotional?', category: 'general' },
  { text: 'Have you ever pretended to be jealous when you were not?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a graduation party?', category: 'funny' },
  { text: 'Have you ever been the one who had to give advice?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were jealous of a relative?', category: 'risky' },
  { text: 'Have you ever had a secret that you told in a dream?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a house party?', category: 'funny' },
  { text: 'Have you ever been caught in a silly argument with yourself?', category: 'funny' },
  { text: 'What is the strangest thing you have ever done to win a bet?', category: 'challenge' },
  { text: 'Have you ever had a crush on someone who was shy?', category: 'friendship' },
  { text: 'What is your biggest fear about being too logical?', category: 'general' },
  { text: 'Have you ever pretended to be calm when you were panicking?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a housewarming?', category: 'funny' },
  { text: 'Have you ever been the one who had to mediate a fight?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were jealous of a classmate?', category: 'risky' },
  { text: 'Have you ever had a secret that you wrote in a letter but never sent?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a reunion?', category: 'funny' },
  { text: 'Have you ever been caught in a moment of courage?', category: 'general' },
  { text: 'What is the weirdest thing you have ever done to make someone laugh?', category: 'general' },
  { text: 'Have you ever had a crush on someone who was outgoing?', category: 'friendship' },
  { text: 'What is your biggest fear about being too sensitive?', category: 'general' },
  { text: 'Have you ever pretended to be indifferent when you cared?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a retirement party?', category: 'funny' },
  { text: 'Have you ever been the one who had to choose sides?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were jealous of a teammate?', category: 'risky' },
  { text: 'Have you ever had a secret that you hinted at but never said?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a holiday party?', category: 'funny' },
  { text: 'Have you ever been caught in a moment of kindness?', category: 'general' },
  { text: 'What is the strangest thing you have ever done to get over someone?', category: 'general' },
  { text: 'Have you ever had a crush on someone who was stubborn?', category: 'friendship' },
  { text: 'What is your biggest fear about being too forgiving?', category: 'general' },
  { text: 'Have you ever pretended to be hurt when you were not?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a office party?', category: 'funny' },
  { text: 'Have you ever been the one who had to tell a white lie?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were jealous of a roommate?', category: 'risky' },
  { text: 'Have you ever had a secret that you are planning to tell someday?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a birthday dinner?', category: 'funny' },
  { text: 'Have you ever been caught in a moment of weakness and then strength?', category: 'general' },
  { text: 'What is the weirdest thing you have ever done to remember someone?', category: 'general' },
  { text: 'Have you ever had a crush on someone who was different from you?', category: 'friendship' },
  { text: 'What is your biggest fear about being too trusting?', category: 'general' },
  { text: 'Have you ever pretended to be patient when you were not?', category: 'funny' },
  { text: 'What is the most embarrassing thing you have done at a networking event?', category: 'funny' },
  { text: 'Have you ever been the one who had to keep the peace?', category: 'friendship' },
  { text: 'What is the worst thing you have done when you were jealous of a best friend?', category: 'risky' },
  { text: 'Have you ever had a secret that you are waiting for the right time to tell?', category: 'risky' },
  { text: 'What is your most embarrassing moment from a blind date?', category: 'funny' },
  { text: 'Have you ever been caught in a moment of clarity?', category: 'general' },
  { text: 'What is the strangest thing you have ever done to honor someone?', category: 'general' },
];

const dares = [
  { text: 'Do your best impression of someone in the room.', category: 'funny' },
  { text: 'Sing the chorus of your favorite song out loud.', category: 'funny' },
  { text: 'Dance for 30 seconds with no music.', category: 'challenge' },
  { text: 'Speak in an accent for the next 3 rounds.', category: 'funny' },
  { text: 'Let someone else post a story on your social media.', category: 'risky' },
  { text: 'Call a contact and sing them happy birthday.', category: 'challenge' },
  { text: 'Do 10 push-ups or squats.', category: 'challenge' },
  { text: 'Eat a spoonful of a condiment chosen by the group.', category: 'challenge' },
  { text: 'Let the group go through your photo gallery for 1 minute.', category: 'risky' },
  { text: 'Say something nice about each person in the room.', category: 'friendship' },
  { text: 'Do a handstand or headstand for 10 seconds.', category: 'challenge' },
  { text: 'Speak only in questions for the next 2 rounds.', category: 'funny' },
  { text: 'Let someone draw on your face with a pen.', category: 'funny' },
  { text: 'Exchange one item of clothing with the person to your left.', category: 'challenge' },
  { text: 'Do your best animal impression and keep it for 1 minute.', category: 'funny' },
  { text: 'Send a voice message to your crush or ex (group chooses the text).', category: 'risky' },
  { text: 'Balance a book on your head for 2 minutes.', category: 'challenge' },
  { text: 'Let the group give you a new hairstyle.', category: 'funny' },
  { text: 'Do a dramatic reading of the last text you sent.', category: 'funny' },
  { text: 'Hold a plank for 1 minute.', category: 'challenge' },
  { text: 'Speak in rhyme for the next 2 rounds.', category: 'funny' },
  { text: 'Let someone tickle you for 30 seconds without laughing.', category: 'challenge' },
  { text: 'Do a fashion show wearing clothes backwards.', category: 'funny' },
  { text: 'Call a family member and tell them you love them.', category: 'friendship' },
  { text: 'Eat something without using your hands.', category: 'challenge' },
  { text: 'Let the group choose an emoji; react that way for 2 rounds.', category: 'funny' },
  { text: 'Do your best celebrity impression.', category: 'funny' },
  { text: 'Say the alphabet backwards in under 30 seconds.', category: 'challenge' },
  { text: 'Let someone else control your phone for the next 5 minutes.', category: 'risky' },
  { text: 'Do a TikTok or viral dance in front of everyone.', category: 'funny' },
  { text: 'Speak in a baby voice for the next 3 rounds.', category: 'funny' },
  { text: 'Give a 1-minute motivational speech to the group.', category: 'challenge' },
  { text: 'Let the group pick your profile picture for 24 hours.', category: 'risky' },
  { text: 'Do 20 jumping jacks.', category: 'challenge' },
  { text: 'Text the last person you talked to and say "I miss you".', category: 'risky' },
  { text: 'Act like a chicken until your next turn.', category: 'funny' },
  { text: 'Let someone feed you a bite of food while blindfolded.', category: 'challenge' },
  { text: 'Read the last 3 texts you received out loud.', category: 'risky' },
  { text: 'Do an impression of the person to your right.', category: 'funny' },
  { text: 'Let the group choose a song; you have to sing the first verse.', category: 'challenge' },
  { text: 'Do 15 squats while making eye contact with everyone.', category: 'challenge' },
  { text: 'Let someone style your hair however they want for the rest of the game.', category: 'funny' },
  { text: 'Speak in a pirate voice for the next 3 rounds.', category: 'funny' },
  { text: 'Do your best impression of a celebrity and let the group guess.', category: 'funny' },
  { text: 'Let the person to your right go through your camera roll for 30 seconds.', category: 'risky' },
  { text: 'Send a flirty text to the last person in your contacts (group writes it).', category: 'risky' },
  { text: 'Do a runway walk and pose at the end.', category: 'funny' },
  { text: 'Eat a bite of food with your eyes closed while someone feeds you.', category: 'challenge' },
  { text: 'Let the group give you a new nickname for the rest of the night.', category: 'funny' },
  { text: 'Do 10 burpees.', category: 'challenge' },
  { text: 'Read your last search out loud.', category: 'risky' },
  { text: 'Act like a dog for 1 minute.', category: 'funny' },
  { text: 'Let someone put ice down your back.', category: 'challenge' },
  { text: 'Do a dramatic monologue as if you are in a soap opera.', category: 'funny' },
  { text: 'Speak in a British (or other) accent until your next turn.', category: 'funny' },
  { text: 'Let the group choose an outfit from your closet; you wear it for 10 minutes.', category: 'challenge' },
  { text: 'Do a handstand against the wall for 15 seconds.', category: 'challenge' },
  { text: 'Call a friend and say "I have something important to tell you" then hang up.', category: 'risky' },
  { text: 'Let someone draw a mustache on your face with a pen.', category: 'funny' },
  { text: 'Do your best impression of the person on your left.', category: 'funny' },
  { text: 'Eat a spoonful of hot sauce or lemon.', category: 'challenge' },
  { text: 'Let the group read your last 5 texts (you can hide names).', category: 'risky' },
  { text: 'Do a cartwheel or attempt one.', category: 'challenge' },
  { text: 'Sing "Happy Birthday" to yourself in a dramatic way.', category: 'funny' },
  { text: 'Let someone tickle you for 20 seconds without moving.', category: 'challenge' },
  { text: 'Do a commercial for an imaginary product.', category: 'funny' },
  { text: 'Speak only in song lyrics for the next 2 rounds.', category: 'funny' },
  { text: 'Let the group pick what you post on your story next.', category: 'risky' },
  { text: 'Do 20 sit-ups.', category: 'challenge' },
  { text: 'Act like a cat for 1 minute (meow, lick "paws", etc.).', category: 'funny' },
  { text: 'Let someone else write a text and you send it to the person they choose.', category: 'risky' },
  { text: 'Do a slow-motion replay of yourself "scoring a goal" or "winning a race".', category: 'funny' },
  { text: 'Eat a piece of bread without using your hands.', category: 'challenge' },
  { text: 'Let the group look at your most used emojis and guess who you text most.', category: 'risky' },
  { text: 'Do your best opera singing for 30 seconds.', category: 'funny' },
  { text: 'Speak in a robot voice for the next 2 rounds.', category: 'funny' },
  { text: 'Let someone put a blindfold on you and spin you 5 times; then try to walk in a straight line.', category: 'challenge' },
  { text: 'Do a TikTok trend (current or old) in front of everyone.', category: 'funny' },
  { text: 'Call a pizza place and ask for a "surprise pizza" (don\'t actually order).', category: 'funny' },
  { text: 'Let the person on your left choose your next 3 social media posts.', category: 'risky' },
  { text: 'Do a trust fall into the arms of the group.', category: 'challenge' },
  { text: 'Act like you are in a silent movie for 1 minute.', category: 'funny' },
  { text: 'Let someone feed you 3 different foods while blindfolded; guess what they are.', category: 'challenge' },
  { text: 'Do your best impression of a teacher or boss.', category: 'funny' },
  { text: 'Speak in rhyme for the next 3 rounds.', category: 'funny' },
  { text: 'Let the group choose a song; dance to it for 1 minute.', category: 'challenge' },
  { text: 'Do 30 seconds of stand-up comedy about yourself.', category: 'funny' },
  { text: 'Call a family member and say you love them in the most dramatic way possible.', category: 'friendship' },
  { text: 'Let someone go through your notes app for 30 seconds.', category: 'risky' },
  { text: 'Do a dramatic reading of a random Wikipedia article.', category: 'funny' },
  { text: 'Act like a news anchor reporting on the current game.', category: 'funny' },
  { text: 'Let the group give you a new profile picture for 24 hours.', category: 'risky' },
  { text: 'Do your best impression of a sports commentator.', category: 'funny' },
  { text: 'Speak like a Shakespeare character for the next 2 rounds.', category: 'funny' },
  { text: 'Let someone choose what you eat for your next meal.', category: 'challenge' },
  { text: 'Do a "get ready with me" style commentary while fixing your hair.', category: 'funny' },
  { text: 'Call a random contact and say "I just wanted to hear your voice" then hang up.', category: 'risky' },
  { text: 'Let the group look at one of your playlists and roast it.', category: 'funny' },
  { text: 'Do a magic trick (real or fake) for the group.', category: 'funny' },
  { text: 'Act like you are a fitness instructor and lead a 1-minute "workout".', category: 'funny' },
  { text: 'Let someone write a caption for your next post.', category: 'risky' },
  { text: 'Do your best impression of a politician giving a speech.', category: 'funny' },
  { text: 'Speak only in questions for the next 3 rounds.', category: 'funny' },
  { text: 'Let the person to your right choose your ringtone for a week.', category: 'challenge' },
  { text: 'Do a dramatic reenactment of the last time you stubbed your toe.', category: 'funny' },
  { text: 'Give everyone in the room a compliment in a poetic way.', category: 'friendship' },
  { text: 'Let the group pick an old photo of you; you have to post it as your story.', category: 'risky' },
  { text: 'Do your best impression of a weather forecaster.', category: 'funny' },
  { text: 'Act like you are in a commercial for the room you are in.', category: 'funny' },
  { text: 'Let someone read your last DM conversation (with names hidden if needed).', category: 'risky' },
  { text: 'Do 10 lunges while saying something nice about each person.', category: 'challenge' },
  { text: 'Speak in a whisper for the next 2 rounds.', category: 'funny' },
  { text: 'Let the group choose what you drink next.', category: 'challenge' },
  { text: 'Do a dramatic interpretation of "I have to go to the bathroom".', category: 'funny' },
  { text: 'Call a friend and sing the first 30 seconds of a song they choose.', category: 'challenge' },
  { text: 'Let someone draw on your arm with a pen (washable).', category: 'funny' },
  { text: 'Do your best impression of a game show host.', category: 'funny' },
  { text: 'Act like a tour guide showing everyone around the room.', category: 'funny' },
  { text: 'Let the group decide one thing you have to do tomorrow.', category: 'challenge' },
  { text: 'Do a "day in my life" voiceover for the last hour.', category: 'funny' },
  { text: 'Give a 30-second pep talk to the person on your left.', category: 'friendship' },
  { text: 'Let someone pick an outfit from your closet; you wear it for the next hour.', category: 'challenge' },
  { text: 'Do your best impression of a chef presenting a dish.', category: 'funny' },
  { text: 'Speak like you are in a horror movie for the next 2 rounds.', category: 'funny' },
  { text: 'Let the group choose a filter; you take a selfie and post it.', category: 'risky' },
  { text: 'Do a dramatic reading of a text you received today.', category: 'funny' },
  { text: 'Act like a commentator for the next round of the game.', category: 'funny' },
  { text: 'Do 25 jumping jacks while singing a nursery rhyme.', category: 'challenge' },
  { text: 'Let the group pick a word; use it in every sentence for 3 rounds.', category: 'funny' },
  { text: 'Send a voice note to a contact saying you are thinking of them.', category: 'risky' },
  { text: 'Do your best impression of a villain from a movie.', category: 'funny' },
  { text: 'Give the person on your left a 30-second shoulder massage.', category: 'friendship' },
  { text: 'Eat a cracker and try to whistle immediately after.', category: 'challenge' },
  { text: 'Let someone post a status on your behalf (they choose the text).', category: 'risky' },
  { text: 'Speak like a poet for the next 2 rounds.', category: 'funny' },
  { text: 'Do 15 mountain climbers.', category: 'challenge' },
  { text: 'Text your mom or dad "I love you" with a heart emoji.', category: 'friendship' },
  { text: 'Act like a detective and "investigate" the room for 1 minute.', category: 'funny' },
  { text: 'Let the group see your last 10 photos (no skipping).', category: 'risky' },
  { text: 'Do a dramatic reading of a takeout menu.', category: 'funny' },
  { text: 'Hold your breath for 30 seconds, then say a tongue twister.', category: 'challenge' },
  { text: 'Compliment the person on your right in a creative way.', category: 'friendship' },
  { text: 'Speak in a Southern accent for the next 3 rounds.', category: 'funny' },
  { text: 'Do 20 high knees in place.', category: 'challenge' },
  { text: 'Call a friend and say "Guess what?" then say "Chicken butt."', category: 'funny' },
  { text: 'Let someone scroll through your Instagram following for 30 seconds.', category: 'risky' },
  { text: 'Do your best impression of a superhero.', category: 'funny' },
  { text: 'Say three things you admire about each person in the room.', category: 'friendship' },
  { text: 'Eat a lemon wedge without making a face.', category: 'challenge' },
  { text: 'Read your last sent email subject line out loud.', category: 'risky' },
  { text: 'Act like a flight attendant and give safety instructions for the room.', category: 'funny' },
  { text: 'Do 10 tricep dips using a chair or couch.', category: 'challenge' },
  { text: 'Text a friend a random compliment.', category: 'friendship' },
  { text: 'Speak in a French accent for the next 2 rounds.', category: 'funny' },
  { text: 'Let the group choose what you snack on next.', category: 'challenge' },
  { text: 'Do a dramatic reenactment of tripping over something.', category: 'funny' },
  { text: 'Send a meme to the last person you texted (group picks the meme).', category: 'risky' },
  { text: 'Do your best impression of a motivational speaker.', category: 'funny' },
  { text: 'Hug everyone in the room and say one nice thing to each.', category: 'friendship' },
  { text: 'Balance on one leg for 1 minute while telling a story.', category: 'challenge' },
  { text: 'Read the first text in your inbox out loud (group decides if you send a reply).', category: 'risky' },
  { text: 'Act like a game show contestant for the next round.', category: 'funny' },
  { text: 'Do 15 butt kicks.', category: 'challenge' },
  { text: 'Call a family member and tell them a joke.', category: 'friendship' },
  { text: 'Speak only in movie quotes for the next 2 rounds.', category: 'funny' },
  { text: 'Let someone pick an embarrassing song; you listen to 30 seconds with no reaction.', category: 'challenge' },
  { text: 'Do a commercial for the worst product you can think of.', category: 'funny' },
  { text: 'Post a story with a caption the group writes.', category: 'risky' },
  { text: 'Do your best impression of a chef on a cooking show.', category: 'funny' },
  { text: 'Tell the person on your left why you are glad they are your friend.', category: 'friendship' },
  { text: 'Do 20 seconds of wall sit.', category: 'challenge' },
  { text: 'Let the group see your screen time for today.', category: 'risky' },
  { text: 'Act like you are presenting an award to someone in the room.', category: 'funny' },
  { text: 'Eat a spoonful of peanut butter and try to say "toy boat" 5 times fast.', category: 'challenge' },
  { text: 'Text someone "We need to talk" then immediately send "about pizza."', category: 'funny' },
  { text: 'Do your best impression of a news reporter breaking bad news.', category: 'funny' },
  { text: 'Say something you have never said aloud about the person to your right.', category: 'friendship' },
  { text: 'Do 10 squat jumps.', category: 'challenge' },
  { text: 'Let the group look at your recent searches (one person only).', category: 'risky' },
  { text: 'Speak in an Italian accent for the next 2 rounds.', category: 'funny' },
  { text: 'Do a dramatic interpretation of receiving bad news.', category: 'funny' },
  { text: 'Send a voice message to a friend saying you appreciate them.', category: 'friendship' },
  { text: 'Hold a yoga pose for 45 seconds.', category: 'challenge' },
  { text: 'Read your last Instagram caption out loud.', category: 'risky' },
  { text: 'Act like a tour guide in a museum describing the room.', category: 'funny' },
  { text: 'Do 15 jumping jacks backwards.', category: 'challenge' },
  { text: 'Let the group pick a filter; take a selfie and set it as your wallpaper for 1 hour.', category: 'risky' },
  { text: 'Do your best impression of a disappointed parent.', category: 'funny' },
  { text: 'Tell everyone one thing you learned from the person on your left.', category: 'friendship' },
  { text: 'Eat a piece of candy and describe the flavor in extreme detail.', category: 'funny' },
  { text: 'Do 20 second plank.', category: 'challenge' },
  { text: 'Text a contact "You are awesome" with no context.', category: 'friendship' },
  { text: 'Speak like a robot for the next 3 rounds.', category: 'funny' },
  { text: 'Let someone choose your next Instagram story.', category: 'risky' },
  { text: 'Do a dramatic reading of a text you received this week.', category: 'funny' },
  { text: 'Do 10 lunges on each leg.', category: 'challenge' },
  { text: 'Call a friend and sing one line of a song they choose.', category: 'challenge' },
  { text: 'Act like a sports commentator for someone walking across the room.', category: 'funny' },
  { text: 'Let the group pick an old status; you post it again.', category: 'risky' },
  { text: 'Do your best impression of someone famous (group guesses).', category: 'funny' },
  { text: 'Say one thing you would do for each person if they needed help.', category: 'friendship' },
  { text: 'Do 15 burpees (modified is fine).', category: 'challenge' },
  { text: 'Read the last thing you copied to your clipboard out loud.', category: 'risky' },
  { text: 'Speak in a German accent for the next 2 rounds.', category: 'funny' },
  { text: 'Do a 30-second dance to a song the group chooses.', category: 'challenge' },
  { text: 'Text your best friend a inside joke only you two get.', category: 'friendship' },
  { text: 'Act like a librarian and shush everyone for 30 seconds.', category: 'funny' },
  { text: 'Let the group see your top 5 most used apps.', category: 'risky' },
  { text: 'Do your best impression of a scared person in a horror movie.', category: 'funny' },
  { text: 'Give a toast to the group as if at a wedding.', category: 'friendship' },
  { text: 'Do 20 crunches.', category: 'challenge' },
  { text: 'Send a text to someone saying "Remember that thing?" (do not explain).', category: 'funny' },
  { text: 'Speak only in emoji descriptions for the next round.', category: 'funny' },
  { text: 'Let someone pick your next WhatsApp or Messenger status.', category: 'risky' },
  { text: 'Do a dramatic reenactment of winning the lottery.', category: 'funny' },
  { text: 'Do 30 seconds of running in place with high knees.', category: 'challenge' },
  { text: 'Tell the person on your right a memory you have with them.', category: 'friendship' },
  { text: 'Act like a referee and "call a foul" on someone in the room.', category: 'funny' },
  { text: 'Read your last Google search out loud.', category: 'risky' },
  { text: 'Do your best impression of a conspiracy theorist.', category: 'funny' },
  { text: 'Say "I appreciate you" to each person in the room with eye contact.', category: 'friendship' },
  { text: 'Eat a bite of something sour and keep a straight face for 10 seconds.', category: 'challenge' },
  { text: 'Let the group write a tweet for you; you post it.', category: 'risky' },
  { text: 'Speak in a Spanish accent for the next 2 rounds.', category: 'funny' },
  { text: 'Do 15 push-ups (knee push-ups count).', category: 'challenge' },
  { text: 'Call a friend and say "I was just thinking about you" then chat for 1 min.', category: 'friendship' },
  { text: 'Do a dramatic reading of a notification you got today.', category: 'funny' },
  { text: 'Let someone go through your Spotify or Apple Music recently played.', category: 'risky' },
  { text: 'Act like a therapist and give the group a "session" for 1 minute.', category: 'funny' },
  { text: 'Do 20 toe touches.', category: 'challenge' },
  { text: 'Text a family member a random fact you learned today.', category: 'friendship' },
  { text: 'Do your best impression of a reality TV star.', category: 'funny' },
  { text: 'Let the group pick a photo from your camera roll to post as your story.', category: 'risky' },
  { text: 'Speak in a Scottish accent for the next 2 rounds.', category: 'funny' },
  { text: 'Do 10 sumo squats.', category: 'challenge' },
  { text: 'Give everyone a nickname based on their personality and use it for 2 rounds.', category: 'funny' },
  { text: 'Read the last thing you liked or reacted to on social media out loud.', category: 'risky' },
  { text: 'Do a dramatic interpretation of finding out you have a secret admirer.', category: 'funny' },
  { text: 'Tell the group one way each person has helped you.', category: 'friendship' },
  { text: 'Do 30 seconds of dancing like nobody is watching.', category: 'challenge' },
  { text: 'Send a voice message to a friend with a bad joke.', category: 'funny' },
  { text: 'Let the group choose your next profile picture for 48 hours.', category: 'risky' },
  { text: 'Act like a judge and give "sentences" to everyone for silly crimes.', category: 'funny' },
  { text: 'Do 15 leg raises.', category: 'challenge' },
  { text: 'Say one thing you are grateful for about each person.', category: 'friendship' },
  { text: 'Do your best impression of a YouTuber doing an intro.', category: 'funny' },
  { text: 'Let someone send a text from your phone to a contact they pick (you approve text).', category: 'risky' },
  { text: 'Speak in an Australian accent for the next 2 rounds.', category: 'funny' },
  { text: 'Do 20 arm circles in each direction.', category: 'challenge' },
  { text: 'Call a friend and do your best impression of them (they have to guess).', category: 'funny' },
  { text: 'Read your last sent message to your best friend out loud.', category: 'risky' },
  { text: 'Do a dramatic reenactment of your morning routine in 30 seconds.', category: 'funny' },
  { text: 'Give the person on your left a genuine compliment they have never heard.', category: 'friendship' },
  { text: 'Do 10 inchworms.', category: 'challenge' },
  { text: 'Let the group pick a song; you lip-sync to the first 30 seconds.', category: 'funny' },
  { text: 'Act like a host of a dating show and introduce everyone as contestants.', category: 'funny' },
  { text: 'Post a story with a poll; the group chooses the question and options.', category: 'risky' },
  { text: 'Do your best impression of a teacher giving a lecture.', category: 'funny' },
  { text: 'Say "You matter to me" to each person in the room.', category: 'friendship' },
  { text: 'Do 15 skater jumps.', category: 'challenge' },
  { text: 'Text someone "I need your opinion on something" then send a silly question.', category: 'funny' },
  { text: 'Let someone look at your recent calls list.', category: 'risky' },
  { text: 'Speak in a New York accent for the next 2 rounds.', category: 'funny' },
  { text: 'Do a 1-minute "Ted Talk" on a topic the group chooses.', category: 'challenge' },
  { text: 'Tell everyone one thing you admire about the person on your right.', category: 'friendship' },
  { text: 'Do your best impression of a infomercial host.', category: 'funny' },
  { text: 'Let the group pick a caption for your next post.', category: 'risky' },
  { text: 'Do 20 heel taps.', category: 'challenge' },
  { text: 'Call a friend and tell them one thing you love about them.', category: 'friendship' },
  { text: 'Act like a auctioneer and "sell" an item in the room.', category: 'funny' },
  { text: 'Read the last meme you sent out loud.', category: 'risky' },
  { text: 'Do a dramatic reading of a ad you saw today.', category: 'funny' },
  { text: 'Do 10 tuck jumps (or high jumps if easier).', category: 'challenge' },
  { text: 'Let the group choose a word; you cannot say it for the next 3 rounds.', category: 'challenge' },
  { text: 'Say one way each person has made you smile.', category: 'friendship' },
  { text: 'Do your best impression of a podcast host.', category: 'funny' },
  { text: 'Send a text to a contact saying "We should hang out soon" (group picks who).', category: 'risky' },
  { text: 'Speak in a Russian accent for the next 2 rounds.', category: 'funny' },
  { text: 'Do 15 side lunges on each side.', category: 'challenge' },
  { text: 'Give a "graduation speech" for the group in 30 seconds.', category: 'funny' },
  { text: 'Let someone scroll through your TikTok or Reels likes for 20 seconds.', category: 'risky' },
  { text: 'Act like a waiter and take everyone\'s "order" for an imaginary menu.', category: 'funny' },
  { text: 'Do 20 shoulder taps in plank position.', category: 'challenge' },
  { text: 'Text a friend "You are one of my favorite people" with no context.', category: 'friendship' },
  { text: 'Do your best impression of a villain giving a monologue.', category: 'funny' },
  { text: 'Read your last tweet or post out loud.', category: 'risky' },
  { text: 'Do a dramatic interpretation of getting good news.', category: 'funny' },
  { text: 'Tell the person on your left one thing you have always wanted to tell them.', category: 'friendship' },
  { text: 'Do 30 seconds of jumping rope (imaginary rope is fine).', category: 'challenge' },
  { text: 'Let the group pick an embarrassing song; you sing the chorus.', category: 'funny' },
  { text: 'Act like a scientist and "explain" the game to the group.', category: 'funny' },
  { text: 'Post a story asking a question the group writes.', category: 'risky' },
  { text: 'Do your best impression of a superhero landing.', category: 'funny' },
  { text: 'Say "Thank you for being here" to each person.', category: 'friendship' },
  { text: 'Do 10 reverse lunges on each leg.', category: 'challenge' },
  { text: 'Call someone and say "I am playing a game and you are part of it" then explain.', category: 'funny' },
  { text: 'Let the group see your battery and storage stats.', category: 'risky' },
  { text: 'Speak in a Jamaican accent for the next 2 rounds.', category: 'funny' },
  { text: 'Do 15 superman holds (lying on stomach, arms and legs lifted).', category: 'challenge' },
  { text: 'Give everyone a "award" and present it dramatically.', category: 'friendship' },
  { text: 'Do a dramatic reading of the weather forecast for the room.', category: 'funny' },
  { text: 'Let someone pick what you change your status to.', category: 'risky' },
  { text: 'Do your best impression of a person who just woke up.', category: 'funny' },
  { text: 'Tell the group one thing you would never change about each person.', category: 'friendship' },
  { text: 'Do 20 flutter kicks.', category: 'challenge' },
  { text: 'Text a contact "Thinking of you" with a random emoji.', category: 'friendship' },
  { text: 'Act like a coach giving a halftime speech to the group.', category: 'funny' },
  { text: 'Read the last thing you saved or bookmarked out loud.', category: 'risky' },
  { text: 'Do a 45-second dramatic monologue about a sandwich.', category: 'funny' },
  { text: 'Do 10 burpees with a clap at the top.', category: 'challenge' },
  { text: 'Let the group choose a phrase; you say it in 5 different accents.', category: 'funny' },
  { text: 'Say one thing you are proud of about each person.', category: 'friendship' },
  { text: 'Do your best impression of a person who just got bad news.', category: 'funny' },
  { text: 'Send a voice note to a friend with a terrible impression of them.', category: 'funny' },
  { text: 'Let the group look at your calendar for this week.', category: 'risky' },
  { text: 'Speak in an Indian accent for the next 2 rounds.', category: 'funny' },
  { text: 'Do 15 glute bridges.', category: 'challenge' },
  { text: 'Call a friend and say "You are the best" then hang up or keep talking.', category: 'friendship' },
  { text: 'Act like a DJ and "drop the beat" for the room.', category: 'funny' },
  { text: 'Read your last reminder or alarm label out loud.', category: 'risky' },
  { text: 'Do a dramatic reenactment of dropping your phone.', category: 'funny' },
  { text: 'Do 20 bicycle crunches.', category: 'challenge' },
  { text: 'Tell everyone one way the person on your right has influenced you.', category: 'friendship' },
  { text: 'Do your best impression of a person on a roller coaster.', category: 'funny' },
  { text: 'Let the group pick a contact; you send them a message the group writes.', category: 'risky' },
  { text: 'Speak in a Boston accent for the next 2 rounds.', category: 'funny' },
  { text: 'Do 30 seconds of shadow boxing.', category: 'challenge' },
  { text: 'Give a "State of the Union" style speech about the game.', category: 'funny' },
  { text: 'Post a photo the group selects from your gallery (no faces if needed).', category: 'risky' },
  { text: 'Do your best impression of a person who just got great news.', category: 'funny' },
  { text: 'Say "I am glad you are in my life" to each person.', category: 'friendship' },
  { text: 'Do 10 sprawls.', category: 'challenge' },
  { text: 'Text someone "Quick question" then send something random.', category: 'funny' },
  { text: 'Let someone read your last note or reminder.', category: 'risky' },
  { text: 'Act like a host of a talent show and introduce the next player.', category: 'funny' },
  { text: 'Do 15 leg lifts (lying down).', category: 'challenge' },
  { text: 'Tell the person on your left what you would do if they needed you at 3am.', category: 'friendship' },
  { text: 'Do a dramatic reading of a recipe.', category: 'funny' },
  { text: 'Let the group choose your next Instagram caption.', category: 'risky' },
  { text: 'Do your best impression of a person who just saw a ghost.', category: 'funny' },
  { text: 'Say one thing you would do to make each person\'s day better.', category: 'friendship' },
  { text: 'Do 20 squat holds.', category: 'challenge' },
  { text: 'Call a friend and do a 30-second impression of a celebrity.', category: 'funny' },
  { text: 'Read your last YouTube or video search out loud.', category: 'risky' },
  { text: 'Speak in a Southern drawl for the next 2 rounds.', category: 'funny' },
  { text: 'Do 10 box jumps (on the floor or low surface).', category: 'challenge' },
  { text: 'Give everyone a "superpower" based on their personality.', category: 'friendship' },
  { text: 'Do a dramatic interpretation of opening a gift you love.', category: 'funny' },
  { text: 'Let the group pick a song; you hum it and they guess.', category: 'funny' },
  { text: 'Act like a host of a talk show and "interview" the person on your right.', category: 'funny' },
  { text: 'Send a text to a contact with a compliment (group approves).', category: 'risky' },
  { text: 'Do your best impression of a person who just finished a marathon.', category: 'funny' },
  { text: 'Say one thing you have in common with each person.', category: 'friendship' },
  { text: 'Do 15 calf raises.', category: 'challenge' },
  { text: 'Let someone see your last 3 downloaded files.', category: 'risky' },
  { text: 'Do a 1-minute "documentary" voiceover about the room.', category: 'funny' },
  { text: 'Do 20 jumping jacks while saying the alphabet.', category: 'challenge' },
  { text: 'Tell the group one memory you have with each person.', category: 'friendship' },
  { text: 'Do your best impression of a person who just lost their keys.', category: 'funny' },
  { text: 'Post a story with a question; the group writes the question.', category: 'risky' },
  { text: 'Speak in a Canadian accent for the next 2 rounds.', category: 'funny' },
  { text: 'Do 10 v-ups or sit-ups.', category: 'challenge' },
  { text: 'Text a family member "I love you" with a specific reason.', category: 'friendship' },
  { text: 'Act like a host of a reality show and narrate the next round.', category: 'funny' },
  { text: 'Read the last thing you shared on social media out loud.', category: 'risky' },
  { text: 'Do a dramatic reenactment of stubbing your toe.', category: 'funny' },
  { text: 'Do 15 wall push-ups.', category: 'challenge' },
  { text: 'Let the group give you a "mission" to complete before the game ends.', category: 'challenge' },
  { text: 'Say "You make a difference" to each person.', category: 'friendship' },
  { text: 'Do your best impression of a person who just got a promotion.', category: 'funny' },
  { text: 'Send a voice message to a friend with a random fact.', category: 'funny' },
  { text: 'Let someone pick your next status update.', category: 'risky' },
  { text: 'Speak in a British royal accent for the next 2 rounds.', category: 'funny' },
  { text: 'Do 20 arm raises (front and side).', category: 'challenge' },
  { text: 'Give a "eulogy" for an object in the room (funny).', category: 'funny' },
  { text: 'Tell the person on your right one thing you have always wanted to do with them.', category: 'friendship' },
  { text: 'Do a dramatic reading of a product description.', category: 'funny' },
  { text: 'Let the group see your most recent screenshot.', category: 'risky' },
  { text: 'Do your best impression of a person who just got a parking ticket.', category: 'funny' },
  { text: 'Say one thing you respect about each person.', category: 'friendship' },
  { text: 'Do 10 knee push-ups.', category: 'challenge' },
  { text: 'Call a friend and say "You are amazing" then explain why (30 sec).', category: 'friendship' },
  { text: 'Act like a host of a cooking show with an imaginary dish.', category: 'funny' },
  { text: 'Read your last sent email (subject only) out loud.', category: 'risky' },
  { text: 'Do a 30-second dramatic monologue about socks.', category: 'funny' },
  { text: 'Do 15 standing oblique twists.', category: 'challenge' },
  { text: 'Let the group pick a dare for you to do in the next 24 hours.', category: 'challenge' },
  { text: 'Tell everyone one way each person has made you laugh.', category: 'friendship' },
  { text: 'Do your best impression of a person who just saw their crush.', category: 'funny' },
  { text: 'Text a contact a dad joke (group can provide one).', category: 'funny' },
  { text: 'Let someone look at your recent apps.', category: 'risky' },
  { text: 'Speak in a pirate accent for the next 3 rounds.', category: 'funny' },
  { text: 'Do 20 step-ups (on a step or low surface).', category: 'challenge' },
  { text: 'Give a "Oscar speech" thanking everyone in the room.', category: 'friendship' },
  { text: 'Do a dramatic interpretation of finding a spider.', category: 'funny' },
  { text: 'Post a story with a song the group chooses.', category: 'risky' },
  { text: 'Act like a host of a podcast and interview the person on your left.', category: 'funny' },
  { text: 'Do 10 reverse crunches.', category: 'challenge' },
  { text: 'Say "I am lucky to know you" to each person.', category: 'friendship' },
  { text: 'Do your best impression of a person who just got a gift.', category: 'funny' },
  { text: 'Read your last note to self out loud.', category: 'risky' },
  { text: 'Do a dramatic reading of a street sign or label in the room.', category: 'funny' },
  { text: 'Do 15 hip raises.', category: 'challenge' },
  { text: 'Tell the person on your left one thing you will never forget about them.', category: 'friendship' },
  { text: 'Let the group pick a phrase; you say it like a movie trailer.', category: 'funny' },
  { text: 'Send a text to someone saying "You made my day" (when they did not).', category: 'funny' },
  { text: 'Let someone choose what you post next (photo or text).', category: 'risky' },
  { text: 'Do your best impression of a person who just woke up from a nap.', category: 'funny' },
  { text: 'Say one thing you would thank each person for.', category: 'friendship' },
  { text: 'Do 20 leg circles (lying down).', category: 'challenge' },
  { text: 'Call a friend and do a 20-second impression of a teacher.', category: 'funny' },
  { text: 'Read the last thing you googled out loud.', category: 'risky' },
  { text: 'Speak in a villain accent for the next 2 rounds.', category: 'funny' },
  { text: 'Do 10 bird dogs (opposite arm and leg).', category: 'challenge' },
  { text: 'Give everyone a "title" (e.g. "Chief of Fun") and use it for 2 rounds.', category: 'friendship' },
  { text: 'Do a dramatic reenactment of slipping on ice.', category: 'funny' },
  { text: 'Let the group pick a question; you post it as your status.', category: 'risky' },
  { text: 'Act like a host of a game show and explain the next round.', category: 'funny' },
  { text: 'Do 15 dead bugs.', category: 'challenge' },
  { text: 'Text a friend "I am grateful for you" with a short reason.', category: 'friendship' },
  { text: 'Do your best impression of a person who just got a text from their crush.', category: 'funny' },
  { text: 'Let someone see your last 5 emoji uses.', category: 'risky' },
  { text: 'Do a 45-second dramatic monologue about the weather.', category: 'funny' },
  { text: 'Do 20 marching in place with high knees.', category: 'challenge' },
  { text: 'Tell the group one thing you would do to cheer up each person.', category: 'friendship' },
  { text: 'Do your best impression of a person who just won a game.', category: 'funny' },
  { text: 'Post a story with a photo the group selects.', category: 'risky' },
  { text: 'Speak in a sleepy voice for the next 2 rounds.', category: 'funny' },
  { text: 'Do 10 cat-cow stretches (yoga).', category: 'challenge' },
  { text: 'Say "You are important to me" to each person.', category: 'friendship' },
  { text: 'Act like a host of a awards show and give an award to the room.', category: 'funny' },
  { text: 'Read your last playlist or album you played out loud.', category: 'risky' },
  { text: 'Do a dramatic interpretation of getting a surprise party.', category: 'funny' },
  { text: 'Do 15 standing leg curls (kickbacks).', category: 'challenge' },
  { text: 'Let the group pick a word; you cannot say "yes" or "no" for 2 rounds.', category: 'challenge' },
  { text: 'Tell the person on your right one thing you admire about their personality.', category: 'friendship' },
  { text: 'Do your best impression of a person who just ate something spicy.', category: 'funny' },
  { text: 'Send a voice note to a contact with a joke (group approves).', category: 'risky' },
  { text: 'Speak in a whisper for the next 3 rounds.', category: 'funny' },
  { text: 'Do 20 ankle circles each direction.', category: 'challenge' },
  { text: 'Give a "press conference" as if you just won something big.', category: 'funny' },
  { text: 'Let someone pick your next Instagram story type (poll, question, etc.).', category: 'risky' },
  { text: 'Do your best impression of a person who just got caught in a lie.', category: 'funny' },
  { text: 'Say one thing you would do to support each person.', category: 'friendship' },
  { text: 'Do 10 windmills (toe touches).', category: 'challenge' },
  { text: 'Call a friend and say "I need to tell you something" then say "You are great."', category: 'funny' },
  { text: 'Read your last alarm name out loud.', category: 'risky' },
  { text: 'Do a dramatic reading of a nutrition label.', category: 'funny' },
  { text: 'Do 15 neck rolls (gentle).', category: 'challenge' },
  { text: 'Tell everyone one way each person has helped you grow.', category: 'friendship' },
  { text: 'Do your best impression of a person who just got a promotion.', category: 'funny' },
  { text: 'Let the group write a short message; you send it to someone they pick.', category: 'risky' },
  { text: 'Act like a host of a documentary and narrate the room for 1 minute.', category: 'funny' },
  { text: 'Do 20 wrist circles.', category: 'challenge' },
  { text: 'Text someone "You are one of the good ones" with no context.', category: 'friendship' },
  { text: 'Do a dramatic reenactment of your reaction to a jump scare.', category: 'funny' },
  { text: 'Let someone see your last 3 photos (you can blur if needed).', category: 'risky' },
  { text: 'Speak in a excited child voice for the next 2 rounds.', category: 'funny' },
  { text: 'Do 10 shoulder rolls.', category: 'challenge' },
  { text: 'Say "I value you" to each person.', category: 'friendship' },
  { text: 'Do your best impression of a person who just got a compliment.', category: 'funny' },
  { text: 'Post a story with a "this or that" the group creates.', category: 'risky' },
  { text: 'Do a 30-second dramatic monologue about a pen.', category: 'funny' },
  { text: 'Do 15 torso twists.', category: 'challenge' },
  { text: 'Tell the person on your left one thing you love about your friendship.', category: 'friendship' },
  { text: 'Act like a host of a morning show and do the "weather" for the room.', category: 'funny' },
  { text: 'Read your last reminder out loud.', category: 'risky' },
  { text: 'Do your best impression of a person who just got bad service.', category: 'funny' },
  { text: 'Say one thing you would do to celebrate each person.', category: 'friendship' },
  { text: 'Do 20 arm stretches.', category: 'challenge' },
  { text: 'Let the group pick a song; you sing one line in a funny voice.', category: 'funny' },
  { text: 'Send a text to a friend with a positive quote.', category: 'friendship' },
  { text: 'Let someone choose your next WhatsApp status.', category: 'risky' },
  { text: 'Do a dramatic interpretation of finding money on the ground.', category: 'funny' },
  { text: 'Do 10 quad stretches (each leg).', category: 'challenge' },
  { text: 'Tell the group one thing you have learned from each person.', category: 'friendship' },
  { text: 'Do your best impression of a person who just got a wrong order.', category: 'funny' },
  { text: 'Read your last calendar event title out loud.', category: 'risky' },
  { text: 'Speak in a dramatic movie trailer voice for the next round.', category: 'funny' },
  { text: 'Do 15 hamstring stretches.', category: 'challenge' },
  { text: 'Give a "State of the Room" address as if you are a leader.', category: 'funny' },
  { text: 'Let the group pick a question; you answer it on your story.', category: 'risky' },
  { text: 'Do your best impression of a person who just got good news.', category: 'funny' },
  { text: 'Say "You belong here" to each person.', category: 'friendship' },
  { text: 'Do 20 hip circles.', category: 'challenge' },
  { text: 'Call a friend and say "I just wanted to say hi" and chat for 1 minute.', category: 'friendship' },
  { text: 'Act like a host of a travel show and "tour" the room.', category: 'funny' },
  { text: 'Read your last typed note out loud.', category: 'risky' },
  { text: 'Do a dramatic reenactment of forgetting someone\'s name.', category: 'funny' },
  { text: 'Do 10 figure-four stretches (each side).', category: 'challenge' },
  { text: 'Tell the person on your right one thing you will always remember.', category: 'friendship' },
  { text: 'Do your best impression of a person who just got a like.', category: 'funny' },
  { text: 'Let the group choose a phrase; you say it in a dramatic way.', category: 'funny' },
  { text: 'Post a story with a countdown or timer the group sets.', category: 'risky' },
  { text: 'Do 15 spinal twists (seated).', category: 'challenge' },
  { text: 'Say one thing you would do to make each person feel special.', category: 'friendship' },
  { text: 'Do your best impression of a person who just got a follow request.', category: 'funny' },
  { text: 'Send a voice message to a friend saying you miss them.', category: 'friendship' },
  { text: 'Let someone see your last 5 searches.', category: 'risky' },
  { text: 'Speak in a monotone voice for the next 2 rounds.', category: 'funny' },
];

module.exports = { truths, dares };
