const truths = [
  { text: '¿Cuál es tu mayor miedo?', category: 'general' },
  { text: '¿Qué es lo más vergonzoso que te ha pasado?', category: 'funny' },
  { text: '¿Alguna vez has mentido para escaquearte de planes?', category: 'general' },
  { text: '¿Cuál es tu placer culpable?', category: 'general' },
  { text: '¿Quién fue tu primer flechazo?', category: 'friendship' },
  { text: '¿Qué es lo peor que has dicho de un amigo?', category: 'risky' },
  { text: '¿Alguna vez has copiado en un examen?', category: 'general' },
  { text: '¿Cuál es tu mayor arrepentimiento?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de la pareja de un amigo?', category: 'risky' },
  { text: '¿En qué es lo más tonto que crees?', category: 'funny' },
  { text: '¿Cuál es tu miedo más irracional?', category: 'general' },
  { text: '¿Alguna vez has fingido que te gustaba un regalo?', category: 'funny' },
  { text: '¿Qué es lo más mezquino que has hecho?', category: 'risky' },
  { text: '¿De quién tienes un crush secreto ahora mismo?', category: 'risky' },
  { text: '¿Qué es algo que nunca le has contado a nadie?', category: 'risky' },
  { text: '¿Alguna vez le has roto el corazón a alguien?', category: 'friendship' },
  { text: '¿Cuál es tu hábito más vergonzoso?', category: 'funny' },
  { text: '¿Alguna vez has difundido un rumor?', category: 'risky' },
  { text: '¿Cuál ha sido tu peor cita?', category: 'general' },
  { text: '¿Alguna vez has estado enamorado?', category: 'friendship' },
  { text: '¿Cuál es tu mayor inseguridad?', category: 'general' },
  { text: '¿Alguna vez has robado algo?', category: 'risky' },
  { text: '¿Qué es lo más infantil que sigues haciendo?', category: 'funny' },
  { text: '¿Alguna vez has mentido a tus padres?', category: 'general' },
  { text: '¿Cuál es tu talento secreto?', category: 'general' },
  { text: '¿Alguna vez has tenido una experiencia cercana a la muerte?', category: 'general' },
  { text: '¿Qué es lo peor que has hecho borracho?', category: 'risky' },
  { text: '¿Alguna vez te han rechazado?', category: 'friendship' },
  { text: '¿Qué es lo que más te molesta?', category: 'general' },
  { text: '¿Alguna vez te han pillado en una mentira?', category: 'funny' },
  { text: '¿Qué harías si te quedara un día de vida?', category: 'challenge' },
  { text: '¿En qué lío más gordo te has metido?', category: 'risky' },
  { text: '¿Alguna vez has tenido una noche de una sola vez?', category: 'risky' },
  { text: '¿Cuál es tu opinión más polémica?', category: 'challenge' },
  { text: '¿Alguna vez has traicionado a un amigo?', category: 'risky' },
  { text: '¿Cuál es tu mayor secreto?', category: 'risky' },
  { text: '¿Alguna vez te has peleado a puñetazos?', category: 'risky' },
  { text: '¿Cuál ha sido tu peor trabajo?', category: 'general' },
  { text: '¿Alguna vez te han arrestado o detenido?', category: 'risky' },
  { text: '¿Qué es algo que nunca volverías a hacer?', category: 'general' },
  { text: '¿Cuál es la canción más vergonzosa de tu playlist?', category: 'funny' },
  { text: '¿Alguna vez te has enamorado de un profesor o jefe?', category: 'risky' },
  { text: '¿Cuál es la peor mentira que has dicho?', category: 'risky' },
  { text: '¿Alguna vez te han pillado haciendo algo que no debías?', category: 'general' },
  { text: '¿Cuál es tu recuerdo de infancia más vergonzoso?', category: 'funny' },
  { text: '¿Alguna vez has ghosteado a alguien?', category: 'friendship' },
  { text: '¿Cuál es el sueño más raro que has tenido?', category: 'general' },
  { text: '¿Alguna vez has tenido un secreto que no pudiste guardar?', category: 'risky' },
  { text: '¿Qué es lo más temerario que has hecho?', category: 'risky' },
  { text: '¿Alguna vez te has enamorado del hermano de un amigo?', category: 'friendship' },
  { text: '¿De qué estás orgulloso pero nunca compartes?', category: 'general' },
  { text: '¿Alguna vez has fingido estar enfermo para escaquearte?', category: 'funny' },
  { text: '¿Qué es lo que más te repele de una persona?', category: 'general' },
  { text: '¿Alguna vez te han dejado plantado en una cita?', category: 'friendship' },
  { text: '¿En qué tontería has gastado más dinero?', category: 'general' },
  { text: '¿Alguna vez has estado a punto de tener problemas con la ley?', category: 'risky' },
  { text: '¿Cuál es el peor regalo que has recibido?', category: 'funny' },
  { text: '¿Alguna vez has estado enamorado de dos personas a la vez?', category: 'risky' },
  { text: '¿Cuál es tu opinión más polémica sobre la comida?', category: 'challenge' },
  { text: '¿Alguna vez has mentido en tu currículum?', category: 'risky' },
  { text: '¿Qué es lo más infantil que aún disfrutas?', category: 'funny' },
  { text: '¿Alguna vez una amistad ha terminado mal?', category: 'friendship' },
  { text: '¿Qué harías si nadie te juzgara?', category: 'challenge' },
  { text: '¿Alguna vez te han pillado mirando a alguien?', category: 'funny' },
  { text: '¿Cuál es tu manía más irracional?', category: 'general' },
  { text: '¿Alguna vez has tenido una amistad unilateral?', category: 'friendship' },
  { text: '¿Qué es lo peor que has dicho a espaldas de alguien?', category: 'risky' },
  { text: '¿Alguna vez has fingido estar ocupado para evitar a alguien?', category: 'funny' },
  { text: '¿Cuál es tu serie o película de guilty pleasure?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien de esta habitación?', category: 'risky' },
  { text: '¿Qué es lo más vergonzoso que han hecho tus padres?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en una situación incómoda?', category: 'funny' },
  { text: '¿Qué es algo que te arrepientes de haber dicho?', category: 'general' },
  { text: '¿Alguna vez has tenido un admirador secreto?', category: 'friendship' },
  { text: '¿Cuál es tu peor hábito?', category: 'general' },
  { text: '¿Alguna vez has sido "la otra persona" en una situación?', category: 'risky' },
  { text: '¿Qué es lo más vergonzoso de tu historial de búsqueda?', category: 'funny' },
  { text: '¿Alguna vez has fingido conocer a alguien que no conocías?', category: 'funny' },
  { text: '¿Cuál es tu mayor miedo sobre el futuro?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de un famoso y te da vergüenza?', category: 'funny' },
  { text: '¿Qué es lo más egoísta que has hecho?', category: 'risky' },
  { text: '¿Alguna vez te han pillado mintiendo a tu pareja?', category: 'risky' },
  { text: '¿Qué es lo más raro que te atrae de alguien?', category: 'challenge' },
  { text: '¿Alguna vez has soñado con alguien de esta habitación?', category: 'risky' },
  { text: '¿Cuál es el peor rumor que has oído sobre ti?', category: 'general' },
  { text: '¿Alguna vez te quedaste en una relación que sabías que estaba mal?', category: 'friendship' },
  { text: '¿Qué es lo más vergonzoso que has hecho para impresionar a alguien?', category: 'funny' },
  { text: '¿Alguna vez te han pillado hablando solo?', category: 'funny' },
  { text: '¿Cuál es tu mayor inseguridad sobre tu aspecto?', category: 'general' },
  { text: '¿Alguna vez has tenido un secreto que podría arruinar una amistad?', category: 'risky' },
  { text: '¿Cuál ha sido la discusión más infantil que has tenido?', category: 'funny' },
  { text: '¿Alguna vez has tenido celos del éxito de un amigo?', category: 'friendship' },
  { text: '¿Cuál es el peor consejo que has dado?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien mucho mayor o menor?', category: 'risky' },
  { text: '¿Qué es lo más vergonzoso que has hecho en el trabajo o en clase?', category: 'funny' },
  { text: '¿Qué fue lo último que buscaste en internet?', category: 'general' },
  { text: '¿Alguna vez has tenido un carné falso?', category: 'risky' },
  { text: '¿Cuál es tu canción de karaoke favorita?', category: 'funny' },
  { text: '¿Alguna vez te han pillado hurgándote la nariz?', category: 'funny' },
  { text: '¿Qué combinación de comida más rara te gusta?', category: 'general' },
  { text: '¿Alguna vez has llorado con una película?', category: 'friendship' },
  { text: '¿Cuál es tu excusa más usada para llegar tarde?', category: 'general' },
  { text: '¿Alguna vez has tenido un fallo de vestuario en público?', category: 'funny' },
  { text: '¿Qué fue lo último que compraste y te arrepientes?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de un personaje de dibujos?', category: 'funny' },
  { text: '¿Cuál es tu mayor miedo sobre las relaciones?', category: 'general' },
  { text: '¿Alguna vez has cotilleado el móvil de alguien?', category: 'risky' },
  { text: '¿Qué es lo más vergonzoso de tu habitación?', category: 'funny' },
  { text: '¿Alguna vez has fingido haber leído un libro que no terminaste?', category: 'funny' },
  { text: '¿Cuál es tu hobby secreto?', category: 'general' },
  { text: '¿Alguna vez te han pillado cantando en la ducha?', category: 'funny' },
  { text: '¿Cuál ha sido tu peor corte de pelo?', category: 'funny' },
  { text: '¿Alguna vez te has enamorado de un compañero de trabajo?', category: 'risky' },
  { text: '¿En qué eres raramente bueno?', category: 'general' },
  { text: '¿Alguna vez has culpado a un hermano de algo que hiciste tú?', category: 'friendship' },
  { text: '¿Cuál es tu momento más vergonzoso de la infancia?', category: 'funny' },
  { text: '¿Alguna vez has enviado un mensaje a la persona equivocada?', category: 'risky' },
  { text: '¿Cuál es el cumplido más raro que has recibido?', category: 'general' },
  { text: '¿Alguna vez has tenido un sueño que parecía muy real?', category: 'general' },
  { text: '¿Cuál es tu snack de guilty pleasure?', category: 'general' },
  { text: '¿Alguna vez te han pillado en una mentira piadosa?', category: 'funny' },
  { text: '¿Cuál fue tu peor fase de moda?', category: 'funny' },
  { text: '¿Alguna vez has estado a punto de tener un accidente conduciendo?', category: 'risky' },
  { text: '¿Qué es algo que nunca admitirías en persona?', category: 'challenge' },
  { text: '¿Alguna vez te has enamorado del ex de un amigo?', category: 'risky' },
  { text: '¿Cuál ha sido tu peor fail del autocorrector?', category: 'funny' },
  { text: '¿Alguna vez has fingido estar en una llamada para evitar a alguien?', category: 'funny' },
  { text: '¿Cuál es el peor regalo que has dado?', category: 'general' },
  { text: '¿Alguna vez te han pillado haciendo algo vergonzoso?', category: 'funny' },
  { text: '¿Cuál es tu mayor miedo sobre envejecer?', category: 'general' },
  { text: '¿Alguna vez has tenido un apretón de manos secreto con alguien?', category: 'friendship' },
  { text: '¿Qué es lo más infantil que aún te hace gracia?', category: 'funny' },
  { text: '¿Alguna vez has mentido sobre tu edad?', category: 'risky' },
  { text: '¿Cuál es el peor consejo que has seguido?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que acababas de conocer?', category: 'friendship' },
  { text: '¿Cuál es tu momento más vergonzoso en una fiesta?', category: 'funny' },
  { text: '¿Alguna vez te han pillado hablando dormido?', category: 'funny' },
  { text: '¿Qué es lo más raro que has comido?', category: 'general' },
  { text: '¿Alguna vez has tenido una amistad que empezó con una mentira?', category: 'risky' },
  { text: '¿Cuál es tu mayor miedo a ser juzgado?', category: 'general' },
  { text: '¿Alguna vez has fingido que te gustaba una canción para encajar?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has dicho en voz alta?', category: 'funny' },
  { text: '¿Alguna vez has tenido un código secreto con un amigo?', category: 'friendship' },
  { text: '¿Cuál ha sido tu peor idea de cita?', category: 'general' },
  { text: '¿Alguna vez te han pillado bailando cuando creías que nadie miraba?', category: 'funny' },
  { text: '¿Cuál fue la última app que descargaste?', category: 'general' },
  { text: '¿Alguna vez has tenido un apodo que odiabas?', category: 'funny' },
  { text: '¿Qué es lo que más te molesta de un compañero de piso?', category: 'general' },
  { text: '¿Alguna vez has fingido estar enfermo para llamar la atención?', category: 'funny' },
  { text: '¿Cuál ha sido tu compra más impulsiva?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de un desconocido que viste una vez?', category: 'friendship' },
  { text: '¿Cuál es el peor chiste que has contado?', category: 'funny' },
  { text: '¿Alguna vez te han pillado mirándote en el espejo?', category: 'funny' },
  { text: '¿Cuál es tu comida de consuelo secreta?', category: 'general' },
  { text: '¿Alguna vez has mentido sobre tu altura o peso?', category: 'risky' },
  { text: '¿Qué es lo más vergonzoso que ha hecho tu hermano?', category: 'funny' },
  { text: '¿Alguna vez has soñado con alguien que no te cae bien?', category: 'general' },
  { text: '¿Cuál es el peor hábito que has copiado de alguien?', category: 'general' },
  { text: '¿Alguna vez te han pillado haciéndote un selfie?', category: 'funny' },
  { text: '¿Cuál es tu mayor miedo al fracaso?', category: 'general' },
  { text: '¿Alguna vez has tenido un secreto que le contaste a uno pero no a otros?', category: 'risky' },
  { text: '¿Qué es lo más vergonzoso que has hecho por likes?', category: 'funny' },
  { text: '¿Alguna vez has fingido entender un chiste que no pillaste?', category: 'funny' },
  { text: '¿Cuál es el peor rumor que has difundido?', category: 'risky' },
  { text: '¿Alguna vez te has enamorado de un personaje de un libro o serie?', category: 'funny' },
  { text: '¿Cuál es tu momento más vergonzoso en clase de gimnasia?', category: 'funny' },
  { text: '¿Alguna vez te han pillado hablando con tu mascota como si fuera una persona?', category: 'funny' },
  { text: '¿Qué es lo más raro que creías de pequeño?', category: 'funny' },
  { text: '¿Alguna vez una amistad ha terminado por un malentendido?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a estar solo?', category: 'general' },
  { text: '¿Alguna vez has fingido estar ocupado cuando no lo estabas?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso de tu historial del navegador?', category: 'risky' },
  { text: '¿Alguna vez te han pillado cantando en el coche?', category: 'funny' },
  { text: '¿Cuál es el peor piropo que has usado u oído?', category: 'funny' },
  { text: '¿Alguna vez has tenido un secreto que al final contaste?', category: 'risky' },
  { text: '¿Cuál es tu manía más irracional?', category: 'general' },
  { text: '¿Alguna vez has fingido trabajar cuando estabas vagueando?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho para llamar la atención?', category: 'funny' },
  { text: '¿Alguna vez has tenido celos de la relación de un amigo?', category: 'friendship' },
  { text: '¿Cuál ha sido tu peor decisión de moda?', category: 'funny' },
  { text: '¿Alguna vez te has enamorado de alguien que no te correspondía?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo al compromiso?', category: 'general' },
  { text: '¿Alguna vez te han pillado soñando despierto en clase o trabajo?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has subido a internet?', category: 'funny' },
  { text: '¿Alguna vez has mentido sobre dónde estabas?', category: 'risky' },
  { text: '¿Cuál es el sueño más raro que has tenido sobre alguien de aquí?', category: 'challenge' },
  { text: '¿Alguna vez has tenido un admirador secreto del que no le contaste a nadie?', category: 'friendship' },
  { text: '¿Cuál es tu momento más vergonzoso en una reunión familiar?', category: 'funny' },
  { text: '¿Alguna vez te han pillado haciendo una mueca en una foto?', category: 'funny' },
  { text: '¿Qué es lo peor que has hecho cuando estabas enfadado?', category: 'risky' },
  { text: '¿Alguna vez te has enamorado del crush de un amigo?', category: 'risky' },
  { text: '¿Cuál es tu mayor miedo a ser vulnerable?', category: 'general' },
  { text: '¿Alguna vez has fingido que te gustaba una comida que odias?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en una cita?', category: 'funny' },
  { text: '¿Alguna vez te han pillado riéndote de tu propio chiste?', category: 'funny' },
  { text: '¿Cuál es la peor mentira que has dicho para escaquearte de planes?', category: 'general' },
  { text: '¿Alguna vez has tenido una amistad que lamentas haber terminado?', category: 'friendship' },
  { text: '¿Cuál es tu momento más vergonzoso en unas vacaciones?', category: 'funny' },
  { text: '¿Alguna vez te han pillado hablando solo en público?', category: 'funny' },
  { text: '¿Qué es lo más raro que coleccionas o coleccionabas?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien con poder?', category: 'risky' },
  { text: '¿Cuál es tu mayor miedo al rechazo?', category: 'general' },
  { text: '¿Alguna vez has fingido haber visto una película que no viste?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en una boda?', category: 'funny' },
  { text: '¿Alguna vez te han pillado haciendo algo que dijiste que nunca harías?', category: 'funny' },
  { text: '¿Cuál es la peor excusa que has usado?', category: 'general' },
  { text: '¿Alguna vez has tenido un secreto que podría cambiar una relación?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en una entrevista de trabajo?', category: 'funny' },
  { text: '¿Alguna vez has tenido celos de un hermano?', category: 'friendship' },
  { text: '¿Qué es lo más raro que has hecho cuando nadie miraba?', category: 'challenge' },
  { text: '¿Alguna vez te has enamorado de alguien que no era para ti?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo al éxito?', category: 'general' },
  { text: '¿Alguna vez has fingido estar dormido para evitar a alguien?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en un restaurante?', category: 'funny' },
  { text: '¿Alguna vez te han pillado viendo algo vergonzoso?', category: 'funny' },
  { text: '¿Cuál ha sido la peor decisión que has tomado al vuelo?', category: 'general' },
  { text: '¿Alguna vez has tenido un secreto que sigues guardando?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en una primera cita?', category: 'funny' },
  { text: '¿Alguna vez has sido el último en enterarte de algo de un amigo?', category: 'friendship' },
  { text: '¿Cuál es tu hábito más raro?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien de quien no debías?', category: 'risky' },
  { text: '¿Cuál es tu mayor miedo al cambio?', category: 'general' },
  { text: '¿Alguna vez has fingido estar seguro cuando no lo estabas?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en un pijamada?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en una foto vergonzosa?', category: 'funny' },
  { text: '¿Qué es lo peor que has dicho en un momento de calor?', category: 'risky' },
  { text: '¿Alguna vez has tenido una amistad que sentías unilateral?', category: 'friendship' },
  { text: '¿Cuál es tu momento más vergonzoso en un concierto?', category: 'funny' },
  { text: '¿Alguna vez te han pillado cantando en público?', category: 'funny' },
  { text: '¿Qué es lo más raro que te reconforta?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que conociste por internet?', category: 'risky' },
  { text: '¿Cuál es tu mayor miedo a lo desconocido?', category: 'general' },
  { text: '¿Alguna vez has fingido interesarte por un tema que odias?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en una reunión?', category: 'funny' },
  { text: '¿Alguna vez te han pillado haciendo algo infantil?', category: 'funny' },
  { text: '¿Qué es lo peor que has hecho para impresionar a alguien?', category: 'risky' },
  { text: '¿Alguna vez has tenido un secreto que te gustaría poder contar?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en unas vacaciones?', category: 'funny' },
  { text: '¿Alguna vez has sido tú quien hizo que una amistad terminara?', category: 'friendship' },
  { text: '¿Cuál era el miedo más raro que tenías de niño?', category: 'funny' },
  { text: '¿Alguna vez te has enamorado de alguien a quien nunca se lo dijiste?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo sobre la confianza?', category: 'general' },
  { text: '¿Alguna vez has fingido estar feliz cuando no lo estabas?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en un funeral?', category: 'funny' },
  { text: '¿Alguna vez un amigo te ha pillado en una mentira?', category: 'risky' },
  { text: '¿Qué es lo peor que has hecho cuando estabas aburrido?', category: 'general' },
  { text: '¿Alguna vez has tenido un secreto que te hacía sentir culpable?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en una fiesta de cumpleaños?', category: 'funny' },
  { text: '¿Alguna vez has sido el tercero en discordia?', category: 'friendship' },
  { text: '¿Qué es lo más raro que le has dicho a alguien?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que tenía pareja?', category: 'risky' },
  { text: '¿Cuál es tu mayor miedo al amor?', category: 'general' },
  { text: '¿Alguna vez has fingido ser alguien que no eres en internet?', category: 'risky' },
  { text: '¿Qué es lo más vergonzoso que has hecho en una reunión?', category: 'funny' },
  { text: '¿Alguna vez te han pillado haciendo algo de lo que te avergüenzas?', category: 'risky' },
  { text: '¿Qué es lo peor que has hecho borracho?', category: 'risky' },
  { text: '¿Alguna vez has tenido una amistad que echas de menos?', category: 'friendship' },
  { text: '¿Cuál es tu momento más vergonzoso en un evento deportivo?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un silencio incómodo?', category: 'funny' },
  { text: '¿Qué es lo más raro que has deseado?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien con quien trabajas?', category: 'risky' },
  { text: '¿Cuál es tu mayor temor a ser malinterpretado?', category: 'general' },
  { text: '¿Alguna vez has fingido olvidar algo a propósito?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en una boda?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que poner fin a una amistad?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho por dinero?', category: 'risky' },
  { text: '¿Alguna vez has tenido un secreto que tengas miedo de contar?', category: 'risky' },
  { text: '¿Cuál es el momento más embarazoso de una presentación?', category: 'funny' },
  { text: '¿Alguna vez te has visto atrapado en una posición comprometedora?', category: 'risky' },
  { text: '¿Qué es lo más raro que has hecho por diversión?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que apenas conoces?', category: 'friendship' },
  { text: '¿Cuál es tu mayor temor a decepcionar a los demás?', category: 'general' },
  { text: '¿Alguna vez has fingido estar enfermo para faltar al trabajo o a la escuela?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en una fiesta?', category: 'funny' },
  { text: '¿Alguna vez has sido el fantasma?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho cuando estabas celoso?', category: 'risky' },
  { text: '¿Alguna vez has tenido un secreto que pudiera lastimar a alguien?', category: 'risky' },
  { text: '¿Cuál es el momento más embarazoso de una sesión de fotos?', category: 'funny' },
  { text: '¿Alguna vez te has visto atrapado en una discusión tonta?', category: 'funny' },
  { text: '¿Qué es lo más extraño que has probado?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que ves todos los días?', category: 'friendship' },
  { text: '¿Cuál es tu mayor temor a quedarte fuera?', category: 'general' },
  { text: '¿Alguna vez has fingido estar cansado para salir temprano?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en un bar?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que ha difundido un rumor?', category: 'risky' },
  { text: '¿Qué es lo peor que has hecho cuando estabas estresado?', category: 'general' },
  { text: '¿Alguna vez has tenido un secreto que compartiste con la persona equivocada?', category: 'risky' },
  { text: '¿Cuál es el momento más embarazoso de un viaje?', category: 'funny' },
  { text: '¿Alguna vez te has visto atrapado en un momento de debilidad?', category: 'general' },
  { text: '¿Qué es lo más extraño que has creído?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que te hizo fantasma?', category: 'friendship' },
  { text: '¿Cuál es tu mayor temor a ser reemplazado?', category: 'general' },
  { text: '¿Alguna vez has fingido estar bien cuando te lastimaste?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en un club?', category: 'funny' },
  { text: '¿Alguna vez has sido traicionado?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho cuando estabas asustado?', category: 'general' },
  { text: '¿Alguna vez has tenido un secreto que te arrepientes de haber contado?', category: 'risky' },
  { text: '¿Cuál es el momento más embarazoso de una clase?', category: 'funny' },
  { text: '¿Alguna vez te has visto atrapado en una situación divertida?', category: 'funny' },
  { text: '¿Qué es lo más raro que le has dicho a un desconocido?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que no puedes tener?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a ser olvidado?', category: 'general' },
  { text: '¿Alguna vez has fingido estar de acuerdo cuando no lo estabas?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en un concierto?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que disculparse?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho cuando estabas cansado?', category: 'general' },
  { text: '¿Alguna vez has tenido un secreto del que estás orgulloso?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en una cena?', category: 'funny' },
  { text: '¿Alguna vez tu familia te ha pillado en una mentira?', category: 'risky' },
  { text: '¿Qué es lo más raro que has hecho solo?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien de tu pasado?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a ser juzgado por la familia?', category: 'general' },
  { text: '¿Alguna vez has fingido estar tranquilo cuando estabas nervioso?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en una cafetería?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el rechazado?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho cuando estabas triste?', category: 'general' },
  { text: '¿Alguna vez has tenido un secreto que escribiste en algún sitio?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en un vuelo?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un hábito raro?', category: 'funny' },
  { text: '¿Qué es lo más raro que has hecho con amigos?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien con quien te peleaste?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a ser vulnerable con los amigos?', category: 'general' },
  { text: '¿Alguna vez has fingido ser valiente cuando tenías miedo?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en un centro comercial?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que perdonar?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho cuando estabas feliz?', category: 'general' },
  { text: '¿Alguna vez has tenido un secreto que casi cuentas?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en una excursión?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un momento de honestidad?', category: 'general' },
  { text: '¿Qué es lo más raro que has hecho por la noche?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien a quien admiras?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a ser demasiado?', category: 'general' },
  { text: '¿Alguna vez has fingido estar tranquilo cuando estabas en pánico?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en una piscina?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que pedir perdón primero?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho cuando estabas enfadado con alguien?', category: 'risky' },
  { text: '¿Alguna vez has tenido un secreto que ocultas a tu familia?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en un viaje a la playa?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un momento tonto?', category: 'funny' },
  { text: '¿Qué es lo más raro que has hecho por la mañana?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que te ponía nervioso?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a no ser suficiente?', category: 'general' },
  { text: '¿Alguna vez has fingido saber algo que no sabías?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en un gimnasio?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que soltar?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho cuando estabas avergonzado?', category: 'general' },
  { text: '¿Alguna vez has tenido un secreto que solo le cuentas a una persona?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en un road trip?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un momento de pereza?', category: 'funny' },
  { text: '¿Qué es lo más raro que has hecho para relajarte?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que te hacía sonreír?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a ser demasiado poco?', category: 'general' },
  { text: '¿Alguna vez has fingido estar sorprendido cuando no lo estabas?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en un parque?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que seguir adelante?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho cuando estabas confundido?', category: 'general' },
  { text: '¿Alguna vez has tenido un secreto que te da miedo compartir?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en una acampada?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un momento raro?', category: 'funny' },
  { text: '¿Qué es lo más raro que has hecho para animarte?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que te hacía reír?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a ser aburrido?', category: 'general' },
  { text: '¿Alguna vez has fingido estar ocupado para evitar una conversación?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en un museo?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que despedirse?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho cuando estabas impaciente?', category: 'general' },
  { text: '¿Alguna vez has tenido un secreto que escribiste en un diario?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en un viaje en barco?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un momento feliz?', category: 'funny' },
  { text: '¿Qué es lo más raro que has hecho para procrastinar?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que fue amable contigo?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a ser pesado?', category: 'general' },
  { text: '¿Alguna vez has fingido estar escuchando cuando no lo hacías?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en un zoológico?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que empezar de cero?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho por celos de un amigo?', category: 'risky' },
  { text: '¿Alguna vez has tenido un secreto que escribiste pero nunca enviaste?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en un festival?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un momento triste?', category: 'general' },
  { text: '¿Qué es lo más raro que has hecho para impresionar?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que era gracioso?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a ser demasiado callado?', category: 'general' },
  { text: '¿Alguna vez has fingido estar dormido para escuchar una conversación?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en un teatro?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que hacer las paces?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho cuando estabas de mal humor?', category: 'general' },
  { text: '¿Alguna vez has tenido un secreto que le susurraste a alguien?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en un picnic?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un momento romántico?', category: 'funny' },
  { text: '¿Qué es lo más raro que has hecho para evitar trabajar?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que era inteligente?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a ser demasiado ruidoso?', category: 'general' },
  { text: '¿Alguna vez has fingido estar enfermo para cancelar una cita?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en una biblioteca?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que admitir la verdad?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho por celos de un hermano?', category: 'risky' },
  { text: '¿Alguna vez has tenido un secreto que te alegra haber guardado?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en una barbacoa?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un momento nervioso?', category: 'funny' },
  { text: '¿Qué es lo más raro que has hecho para encajar?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que era creativo?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a ser demasiado serio?', category: 'general' },
  { text: '¿Alguna vez has fingido estar despierto cuando estabas medio dormido?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en una bolera?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que cargar con la culpa?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho por celos de un compañero de trabajo?', category: 'risky' },
  { text: '¿Alguna vez has tenido un secreto que temes que salga?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en una noche de karaoke?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un momento de emoción?', category: 'funny' },
  { text: '¿Qué es lo más raro que has hecho para celebrar?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que era talentoso?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a ser demasiado tonto?', category: 'general' },
  { text: '¿Alguna vez has fingido estar ofendido cuando no lo estabas?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en una bolera?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que defender a alguien?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho por celos de un ex?', category: 'risky' },
  { text: '¿Alguna vez has tenido un secreto en el que piensas a menudo?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en una noche de juegos?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un momento reflexivo?', category: 'general' },
  { text: '¿Qué es lo más raro que has hecho para sorprender a alguien?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que era misterioso?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a ser demasiado honesto?', category: 'general' },
  { text: '¿Alguna vez has fingido estar enfadado cuando no lo estabas?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en un casino?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que guardar un secreto por alguien?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho por celos de un desconocido?', category: 'risky' },
  { text: '¿Alguna vez has tenido un secreto que quieres contar pero no puedes?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en una cena?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un momento nostálgico?', category: 'general' },
  { text: '¿Qué es lo más raro que has hecho para ayudar a alguien?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que era aventurero?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a ser demasiado dependiente?', category: 'general' },
  { text: '¿Alguna vez has fingido estar triste cuando no lo estabas?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en un banquete de boda?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que dar malas noticias?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho por celos de un famoso?', category: 'funny' },
  { text: '¿Alguna vez has tenido un secreto que contaste demasiado pronto?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en un baby shower?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un momento de esperanza?', category: 'general' },
  { text: '¿Qué es lo más raro que has hecho para vengarte?', category: 'risky' },
  { text: '¿Alguna vez te has enamorado de alguien que era tranquilo?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a ser demasiado independiente?', category: 'general' },
  { text: '¿Alguna vez has fingido estar emocionado cuando no lo estabas?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en un baby shower?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que consolar a alguien?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho por celos de un vecino?', category: 'risky' },
  { text: '¿Alguna vez has tenido un secreto del que te arrepientes de no haber contado?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en una graduación?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un momento de paz?', category: 'general' },
  { text: '¿Qué es lo más raro que has hecho para llamar la atención?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que era apasionado?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a ser demasiado emocional?', category: 'general' },
  { text: '¿Alguna vez has fingido estar celoso cuando no lo estabas?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en una fiesta de graduación?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que dar consejos?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho por celos de un familiar?', category: 'risky' },
  { text: '¿Alguna vez has tenido un secreto que contaste en un sueño?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en una fiesta en casa?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en una discusión tonta contigo mismo?', category: 'funny' },
  { text: '¿Qué es lo más raro que has hecho para ganar una apuesta?', category: 'challenge' },
  { text: '¿Alguna vez te has enamorado de alguien que era tímido?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a ser demasiado lógico?', category: 'general' },
  { text: '¿Alguna vez has fingido estar tranquilo cuando estabas en pánico?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en una fiesta de inauguración?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que mediar en una pelea?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho por celos de un compañero de clase?', category: 'risky' },
  { text: '¿Alguna vez has tenido un secreto que escribiste en una carta pero nunca enviaste?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en una reunión?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un momento de valentía?', category: 'general' },
  { text: '¿Qué es lo más raro que has hecho para hacer reír a alguien?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que era extrovertido?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a ser demasiado sensible?', category: 'general' },
  { text: '¿Alguna vez has fingido ser indiferente cuando te importaba?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en una fiesta de jubilación?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que elegir bando?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho por celos de un compañero de equipo?', category: 'risky' },
  { text: '¿Alguna vez has tenido un secreto que insinuaste pero nunca dijiste?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en una fiesta navideña?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un momento de bondad?', category: 'general' },
  { text: '¿Qué es lo más raro que has hecho para superar a alguien?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que era testarudo?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a ser demasiado perdonador?', category: 'general' },
  { text: '¿Alguna vez has fingido estar herido cuando no lo estabas?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en una fiesta de oficina?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que decir una mentira piadosa?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho por celos de un compañero de piso?', category: 'risky' },
  { text: '¿Alguna vez has tenido un secreto que planeas contar algún día?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en una cena de cumpleaños?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un momento de debilidad y luego de fortaleza?', category: 'general' },
  { text: '¿Qué es lo más raro que has hecho para recordar a alguien?', category: 'general' },
  { text: '¿Alguna vez te has enamorado de alguien que era diferente a ti?', category: 'friendship' },
  { text: '¿Cuál es tu mayor miedo a confiar demasiado?', category: 'general' },
  { text: '¿Alguna vez has fingido ser paciente cuando no lo eras?', category: 'funny' },
  { text: '¿Qué es lo más vergonzoso que has hecho en un evento de networking?', category: 'funny' },
  { text: '¿Alguna vez has sido tú el que tuvo que mantener la paz?', category: 'friendship' },
  { text: '¿Qué es lo peor que has hecho por celos de un mejor amigo?', category: 'risky' },
  { text: '¿Alguna vez has tenido un secreto que esperas el momento adecuado para contar?', category: 'risky' },
  { text: '¿Cuál es tu momento más vergonzoso en una cita a ciegas?', category: 'funny' },
  { text: '¿Alguna vez te han pillado en un momento de claridad?', category: 'general' },
  { text: '¿Qué es lo más raro que has hecho para honrar a alguien?', category: 'general' },
];

const dares = [
  { text: 'Haz tu mejor imitación de alguien de la habitación.', category: 'funny' },
  { text: 'Canta el estribillo de tu canción favorita en voz alta.', category: 'funny' },
  { text: 'Baila 30 segundos sin música.', category: 'challenge' },
  { text: 'Habla con acento las próximas 3 rondas.', category: 'funny' },
  { text: 'Deja que alguien publique una historia en tus redes sociales.', category: 'risky' },
  { text: 'Llama a un contacto y cántale cumpleaños feliz.', category: 'challenge' },
  { text: 'Haz 10 flexiones o sentadillas.', category: 'challenge' },
  { text: 'Come una cucharada de un condimento que elija el grupo.', category: 'challenge' },
  { text: 'Deja que el grupo revise tu galería de fotos 1 minuto.', category: 'risky' },
  { text: 'Di algo bonito de cada persona de la habitación.', category: 'friendship' },
  { text: 'Haz el pino o la vertical 10 segundos.', category: 'challenge' },
  { text: 'Habla solo en preguntas las próximas 2 rondas.', category: 'funny' },
  { text: 'Deja que alguien te dibuje en la cara con un boli.', category: 'funny' },
  { text: 'Intercambia una prenda con la persona de tu izquierda.', category: 'challenge' },
  { text: 'Haz tu mejor imitación de un animal y manténla 1 minuto.', category: 'funny' },
  { text: 'Envía un mensaje de voz a tu crush o ex (el grupo elige el texto).', category: 'risky' },
  { text: 'Equilibra un libro en la cabeza 2 minutos.', category: 'challenge' },
  { text: 'Deja que el grupo te haga un nuevo peinado.', category: 'funny' },
  { text: 'Haz una lectura dramática del último mensaje que enviaste.', category: 'funny' },
  { text: 'Mantén la plancha 1 minuto.', category: 'challenge' },
  { text: 'Habla en rima las próximas 2 rondas.', category: 'funny' },
  { text: 'Deja que alguien te haga cosquillas 30 segundos sin reírte.', category: 'challenge' },
  { text: 'Haz un desfile de moda con la ropa al revés.', category: 'funny' },
  { text: 'Llama a un familiar y dile que le quieres.', category: 'friendship' },
  { text: 'Come algo sin usar las manos.', category: 'challenge' },
  { text: 'Deja que el grupo elija un emoji; reacciona así 2 rondas.', category: 'funny' },
  { text: 'Haz tu mejor imitación de un famoso.', category: 'funny' },
  { text: 'Di el abecedario al revés en menos de 30 segundos.', category: 'challenge' },
  { text: 'Deja que alguien controle tu móvil los próximos 5 minutos.', category: 'risky' },
  { text: 'Haz un baile de TikTok o viral delante de todos.', category: 'funny' },
  { text: 'Habla con voz de bebé las próximas 3 rondas.', category: 'funny' },
  { text: 'Da un discurso motivacional de 1 minuto al grupo.', category: 'challenge' },
  { text: 'Deja que el grupo elija tu foto de perfil 24 horas.', category: 'risky' },
  { text: 'Haz 20 jumping jacks.', category: 'challenge' },
  { text: 'Escribe al último con quien hablaste y dile "te echo de menos".', category: 'risky' },
  { text: 'Actúa como un pollo hasta tu próximo turno.', category: 'funny' },
  { text: 'Deja que alguien te dé un bocado con los ojos vendados.', category: 'challenge' },
  { text: 'Lee en voz alta los últimos 3 mensajes que recibiste.', category: 'risky' },
  { text: 'Imita a la persona de tu derecha.', category: 'funny' },
  { text: 'El grupo elige una canción; tienes que cantar la primera estrofa.', category: 'challenge' },
  { text: 'Haz 15 sentadillas mirando a los ojos a todos.', category: 'challenge' },
  { text: 'Deja que alguien te peine como quiera el resto del juego.', category: 'funny' },
  { text: 'Habla con voz de pirata las próximas 3 rondas.', category: 'funny' },
  { text: 'Imita a un famoso y que el grupo adivine.', category: 'funny' },
  { text: 'Deja que la persona de tu derecha revise tu galería 30 segundos.', category: 'risky' },
  { text: 'Envía un mensaje coqueto al último de tus contactos (lo escribe el grupo).', category: 'risky' },
  { text: 'Haz un paseo de pasarela y posa al final.', category: 'funny' },
  { text: 'Come un bocado con los ojos cerrados mientras alguien te da de comer.', category: 'challenge' },
  { text: 'Deja que el grupo te ponga un apodo para el resto de la noche.', category: 'funny' },
  { text: 'Haz 10 burpees.', category: 'challenge' },
  { text: 'Lee en voz alta tu última búsqueda.', category: 'risky' },
  { text: 'Actúa como un perro 1 minuto.', category: 'funny' },
  { text: 'Deja que alguien te eche hielo por la espalda.', category: 'challenge' },
  { text: 'Haz un monólogo dramático como en una telenovela.', category: 'funny' },
  { text: 'Habla con acento británico (u otro) hasta tu próximo turno.', category: 'funny' },
  { text: 'El grupo elige un outfit de tu armario; lo llevas 10 minutos.', category: 'challenge' },
  { text: 'Haz el pino contra la pared 15 segundos.', category: 'challenge' },
  { text: 'Llama a un amigo y di "tengo algo importante que decirte" y cuelga.', category: 'risky' },
  { text: 'Deja que alguien te dibuje un bigote con boli.', category: 'funny' },
  { text: 'Imita a la persona de tu izquierda.', category: 'funny' },
  { text: 'Come una cucharada de salsa picante o limón.', category: 'challenge' },
  { text: 'Deja que el grupo lea tus últimos 5 mensajes (puedes ocultar nombres).', category: 'risky' },
  { text: 'Haz una voltereta lateral o inténtalo.', category: 'challenge' },
  { text: 'Cántate "Cumpleaños feliz" de forma dramática.', category: 'funny' },
  { text: 'Deja que alguien te haga cosquillas 20 segundos sin moverte.', category: 'challenge' },
  { text: 'Haz un anuncio de un producto imaginario.', category: 'funny' },
  { text: 'Habla solo con letras de canciones las próximas 2 rondas.', category: 'funny' },
  { text: 'Deja que el grupo elija qué subes a tu historia.', category: 'risky' },
  { text: 'Haz 20 abdominales.', category: 'challenge' },
  { text: 'Actúa como un gato 1 minuto (maullar, lamer "patas", etc.).', category: 'funny' },
  { text: 'Deja que alguien escriba un mensaje y lo envíes a quien elija.', category: 'risky' },
  { text: 'Haz una repetición a cámara lenta de "marcar un gol" o "ganar una carrera".', category: 'funny' },
  { text: 'Come un trozo de pan sin usar las manos.', category: 'challenge' },
  { text: 'Deja que el grupo vea tus emojis más usados y adivine a quién escribes más.', category: 'risky' },
  { text: 'Canta ópera lo mejor que puedas 30 segundos.', category: 'funny' },
  { text: 'Habla con voz de robot las próximas 2 rondas.', category: 'funny' },
  { text: 'Deja que te venden los ojos, te den 5 vueltas e intenta caminar en línea recta.', category: 'challenge' },
  { text: 'Haz un trend de TikTok (actual o antiguo) delante de todos.', category: 'funny' },
  { text: 'Llama a una pizzería y pide una "pizza sorpresa" (no pidas de verdad).', category: 'funny' },
  { text: 'La persona de tu izquierda elige tus próximas 3 publicaciones.', category: 'risky' },
  { text: 'Haz una caída de confianza en brazos del grupo.', category: 'challenge' },
  { text: 'Actúa como en una película muda 1 minuto.', category: 'funny' },
  { text: 'Deja que te den 3 alimentos distintos con los ojos vendados; adivina cuáles son.', category: 'challenge' },
  { text: 'Imita a un profesor o jefe.', category: 'funny' },
  { text: 'Habla en rima las próximas 3 rondas.', category: 'funny' },
  { text: 'El grupo elige una canción; baila 1 minuto.', category: 'challenge' },
  { text: 'Haz 30 segundos de monólogo sobre ti mismo.', category: 'funny' },
  { text: 'Llama a un familiar y dile que le quieres de la forma más dramática posible.', category: 'friendship' },
  { text: 'Deja que alguien revise tu app de notas 30 segundos.', category: 'risky' },
  { text: 'Lee dramáticamente un artículo aleatorio de Wikipedia.', category: 'funny' },
  { text: 'Actúa como un presentador de noticias del juego actual.', category: 'funny' },
  { text: 'Deja que el grupo elija tu foto de perfil 24 horas.', category: 'risky' },
  { text: 'Imita a un comentarista deportivo.', category: 'funny' },
  { text: 'Habla como un personaje de Shakespeare las próximas 2 rondas.', category: 'funny' },
  { text: 'Alguien elige qué comes en tu próxima comida.', category: 'challenge' },
  { text: 'Haz un comentario estilo "get ready with me" mientras te arreglas el pelo.', category: 'funny' },
  { text: 'Llama a un contacto al azar y di "solo quería oír tu voz" y cuelga.', category: 'risky' },
  { text: 'Deja que el grupo vea una de tus playlists y la critique.', category: 'funny' },
  { text: 'Haz un truco de magia (real o falso) para el grupo.', category: 'funny' },
  { text: 'Actúa como monitor de fitness y dirige 1 minuto de "entrenamiento".', category: 'funny' },
  { text: 'Alguien escribe la leyenda de tu próxima publicación.', category: 'risky' },
  { text: 'Imita a un político dando un discurso.', category: 'funny' },
  { text: 'Habla solo en preguntas las próximas 3 rondas.', category: 'funny' },
  { text: 'La persona de tu derecha elige tu tono de llamada una semana.', category: 'challenge' },
  { text: 'Recrea dramáticamente la última vez que te diste un golpe en el dedo.', category: 'funny' },
  { text: 'Dale un cumplido poético a cada uno de la habitación.', category: 'friendship' },
  { text: 'El grupo elige una foto antigua tuya; la subes a tu historia.', category: 'risky' },
  { text: 'Imita a un presentador del tiempo.', category: 'funny' },
  { text: 'Actúa como en un anuncio de la habitación en la que estás.', category: 'funny' },
  { text: 'Deja que alguien lea tu última conversación por DM (nombres ocultos si hace falta).', category: 'risky' },
  { text: 'Haz 10 zancadas diciendo algo bonito de cada uno.', category: 'challenge' },
  { text: 'Habla en susurro las próximas 2 rondas.', category: 'funny' },
  { text: 'El grupo elige qué bebes a continuación.', category: 'challenge' },
  { text: 'Interpreta dramáticamente "tengo que ir al baño".', category: 'funny' },
  { text: 'Llama a un amigo y canta los primeros 30 segundos de una canción que elija.', category: 'challenge' },
  { text: 'Deja que alguien te dibuje en el brazo con boli (lavable).', category: 'funny' },
  { text: 'Imita a un presentador de concurso.', category: 'funny' },
  { text: 'Actúa como guía mostrando la habitación a todos.', category: 'funny' },
  { text: 'El grupo decide una cosa que tienes que hacer mañana.', category: 'challenge' },
  { text: 'Haz un voiceover "un día en mi vida" de la última hora.', category: 'funny' },
  { text: 'Dale un discurso de ánimo de 30 segundos a la persona de tu izquierda.', category: 'friendship' },
  { text: 'Alguien elige un outfit de tu armario; lo llevas la próxima hora.', category: 'challenge' },
  { text: 'Imita a un chef presentando un plato.', category: 'funny' },
  { text: 'Habla como en una película de terror las próximas 2 rondas.', category: 'funny' },
  { text: 'El grupo elige un filtro; te haces un selfie y lo subes.', category: 'risky' },
  { text: 'Lee dramáticamente un mensaje que recibiste hoy.', category: 'funny' },
  { text: 'Actúa como comentarista de la próxima ronda del juego.', category: 'funny' },
  { text: 'Haz 25 jumping jacks cantando una canción infantil.', category: 'challenge' },
  { text: 'El grupo elige una palabra; úsala en cada frase 3 rondas.', category: 'funny' },
  { text: 'Envía un mensaje de voz a un contacto diciendo que piensas en él/ella.', category: 'risky' },
  { text: 'Imita a un villano de una película.', category: 'funny' },
  { text: 'Dale un masaje de hombros de 30 segundos a la persona de tu izquierda.', category: 'friendship' },
  { text: 'Come una galleta e intenta silbar justo después.', category: 'challenge' },
  { text: 'Alguien publica un estado por ti (ellos eligen el texto).', category: 'risky' },
  { text: 'Habla como un poeta las próximas 2 rondas.', category: 'funny' },
  { text: 'Haz 15 mountain climbers.', category: 'challenge' },
  { text: 'Escribe a tu madre o padre "te quiero" con un emoji de corazón.', category: 'friendship' },
  { text: 'Actúa como detective e "investiga" la habitación 1 minuto.', category: 'funny' },
  { text: 'Deja que el grupo vea tus últimas 10 fotos (sin saltar).', category: 'risky' },
  { text: 'Lee dramáticamente una carta de un restaurante.', category: 'funny' },
  { text: 'Aguanta la respiración 30 segundos y luego di un trabalenguas.', category: 'challenge' },
  { text: 'Dale un cumplido creativo a la persona de tu derecha.', category: 'friendship' },
  { text: 'Habla con acento sureño las próximas 3 rondas.', category: 'funny' },
  { text: 'Haz 20 rodillas altas en el sitio.', category: 'challenge' },
  { text: 'Llama a un amigo y di "¿adivina qué?" y luego "culo de pollo".', category: 'funny' },
  { text: 'Deja que alguien revise a quien sigues en Instagram 30 segundos.', category: 'risky' },
  { text: 'Imita a un superhéroe.', category: 'funny' },
  { text: 'Di tres cosas que admiras de cada persona de la habitación.', category: 'friendship' },
  { text: 'Come un gajo de limón sin poner cara.', category: 'challenge' },
  { text: 'Lee en voz alta el asunto del último email que enviaste.', category: 'risky' },
  { text: 'Actúa como azafata y da instrucciones de seguridad de la habitación.', category: 'funny' },
  { text: 'Haz 10 fondos de tríceps con una silla o sofá.', category: 'challenge' },
  { text: 'Envía un cumplido al azar a un amigo.', category: 'friendship' },
  { text: 'Habla con acento francés las próximas 2 rondas.', category: 'funny' },
  { text: 'El grupo elige con qué picoteas a continuación.', category: 'challenge' },
  { text: 'Recrea dramáticamente tropezar con algo.', category: 'funny' },
  { text: 'Envía un meme a la última persona a la que escribiste (el grupo elige el meme).', category: 'risky' },
  { text: 'Imita a un orador motivacional.', category: 'funny' },
  { text: 'Abraza a todos y di algo bonito a cada uno.', category: 'friendship' },
  { text: 'Equilibra sobre una pierna 1 minuto contando una historia.', category: 'challenge' },
  { text: 'Lee en voz alta el primer mensaje de tu bandeja (el grupo decide si respondes).', category: 'risky' },
  { text: 'Actúa como concursante de concurso la próxima ronda.', category: 'funny' },
  { text: 'Haz 15 patadas al culo.', category: 'challenge' },
  { text: 'Llama a un familiar y cuéntale un chiste.', category: 'friendship' },
  { text: 'Habla solo con frases de películas las próximas 2 rondas.', category: 'funny' },
  { text: 'Alguien elige una canción vergonzosa; la escuchas 30 segundos sin reaccionar.', category: 'challenge' },
  { text: 'Haz un anuncio del peor producto que se te ocurra.', category: 'funny' },
  { text: 'Sube una historia con la leyenda que escriba el grupo.', category: 'risky' },
  { text: 'Imita a un chef de programa de cocina.', category: 'funny' },
  { text: 'Dile a la persona de tu izquierda por qué te alegra que sea tu amigo.', category: 'friendship' },
  { text: 'Haz 20 segundos de sentadilla contra la pared.', category: 'challenge' },
  { text: 'Deja que el grupo vea tu tiempo de pantalla de hoy.', category: 'risky' },
  { text: 'Actúa como si le entregaras un premio a alguien de la habitación.', category: 'funny' },
  { text: 'Come una cucharada de mantequilla de cacahuete e intenta decir "barco de juguete" 5 veces rápido.', category: 'challenge' },
  { text: 'Escribe a alguien "tenemos que hablar" y luego envía "de pizza".', category: 'funny' },
  { text: 'Imita a un periodista dando malas noticias.', category: 'funny' },
  { text: 'Di algo que nunca has dicho en voz alta de la persona de tu derecha.', category: 'friendship' },
  { text: 'Haz 10 saltos de sentadilla.', category: 'challenge' },
  { text: 'Deja que el grupo vea tus búsquedas recientes (solo una persona).', category: 'risky' },
  { text: 'Habla con acento italiano las próximas 2 rondas.', category: 'funny' },
  { text: 'Interpreta dramáticamente recibir malas noticias.', category: 'funny' },
  { text: 'Envía un mensaje de voz a un amigo diciendo que le aprecias.', category: 'friendship' },
  { text: 'Mantén una postura de yoga 45 segundos.', category: 'challenge' },
  { text: 'Lee en voz alta tu última leyenda de Instagram.', category: 'risky' },
  { text: 'Actúa como guía de museo describiendo la habitación.', category: 'funny' },
  { text: 'Haz 15 jumping jacks hacia atrás.', category: 'challenge' },
  { text: 'El grupo elige un filtro; hazte un selfie y ponlo de fondo 1 hora.', category: 'risky' },
  { text: 'Imita a un padre decepcionado.', category: 'funny' },
  { text: 'Dile a todos una cosa que aprendiste de la persona de tu izquierda.', category: 'friendship' },
  { text: 'Come un caramelo y describe el sabor con todo detalle.', category: 'funny' },
  { text: 'Haz plancha 20 segundos.', category: 'challenge' },
  { text: 'Escribe a un contacto "Eres increíble" sin contexto.', category: 'friendship' },
  { text: 'Habla como un robot las próximas 3 rondas.', category: 'funny' },
  { text: 'Alguien elige tu próxima historia de Instagram.', category: 'risky' },
  { text: 'Lee dramáticamente un mensaje que recibiste esta semana.', category: 'funny' },
  { text: 'Haz 10 zancadas con cada pierna.', category: 'challenge' },
  { text: 'Llama a un amigo y canta una línea de una canción que elija.', category: 'challenge' },
  { text: 'Actúa como comentarista deportivo de alguien cruzando la habitación.', category: 'funny' },
  { text: 'El grupo elige un estado antiguo; lo vuelves a publicar.', category: 'risky' },
  { text: 'Imita a alguien famoso (el grupo adivina).', category: 'funny' },
  { text: 'Di una cosa que harías por cada uno si necesitaran ayuda.', category: 'friendship' },
  { text: 'Haz 15 burpees (modificado vale).', category: 'challenge' },
  { text: 'Lee en voz alta lo último que copiaste al portapapeles.', category: 'risky' },
  { text: 'Habla con acento alemán las próximas 2 rondas.', category: 'funny' },
  { text: 'Baila 30 segundos una canción que elija el grupo.', category: 'challenge' },
  { text: 'Envía a tu mejor amigo un chiste interno que solo vosotros entendáis.', category: 'friendship' },
  { text: 'Actúa como bibliotecario y pide silencio a todos 30 segundos.', category: 'funny' },
  { text: 'Deja que el grupo vea tus 5 apps más usadas.', category: 'risky' },
  { text: 'Imita a una persona asustada en una película de terror.', category: 'funny' },
  { text: 'Brinda por el grupo como en una boda.', category: 'friendship' },
  { text: 'Haz 20 abdominales.', category: 'challenge' },
  { text: 'Envía un mensaje a alguien diciendo "¿Recuerdas aquello?" (no expliques).', category: 'funny' },
  { text: 'Habla solo describiendo emojis la próxima ronda.', category: 'funny' },
  { text: 'Alguien elige tu próximo estado de WhatsApp o Messenger.', category: 'risky' },
  { text: 'Recrea dramáticamente ganar la lotería.', category: 'funny' },
  { text: 'Corre en el sitio con rodillas altas 30 segundos.', category: 'challenge' },
  { text: 'Cuéntale a la persona de tu derecha un recuerdo que tienes con ella.', category: 'friendship' },
  { text: 'Actúa como árbitro y "pita falta" a alguien de la habitación.', category: 'funny' },
  { text: 'Lee en voz alta tu última búsqueda en Google.', category: 'risky' },
  { text: 'Imita a un teórico de la conspiración.', category: 'funny' },
  { text: 'Di "te aprecio" a cada uno mirando a los ojos.', category: 'friendship' },
  { text: 'Come algo ácido y mantén la cara seria 10 segundos.', category: 'challenge' },
  { text: 'El grupo escribe un tweet; tú lo publicas.', category: 'risky' },
  { text: 'Habla con acento español las próximas 2 rondas.', category: 'funny' },
  { text: 'Haz 15 flexiones (las de rodillas cuentan).', category: 'challenge' },
  { text: 'Llama a un amigo y di "estaba pensando en ti" y charla 1 minuto.', category: 'friendship' },
  { text: 'Lee dramáticamente una notificación que te llegó hoy.', category: 'funny' },
  { text: 'Deja que alguien revise lo que has escuchado en Spotify o Apple Music.', category: 'risky' },
  { text: 'Actúa como terapeuta y dale al grupo una "sesión" 1 minuto.', category: 'funny' },
  { text: 'Haz 20 toques de dedos a los pies.', category: 'challenge' },
  { text: 'Envía a un familiar un dato aleatorio que aprendiste hoy.', category: 'friendship' },
  { text: 'Imita a una estrella de telerrealidad.', category: 'funny' },
  { text: 'El grupo elige una foto de tu galería para subir a tu historia.', category: 'risky' },
  { text: 'Habla con acento escocés las próximas 2 rondas.', category: 'funny' },
  { text: 'Haz 10 sentadillas sumo.', category: 'challenge' },
  { text: 'Ponle a cada uno un apodo según su personalidad y úsalo 2 rondas.', category: 'funny' },
  { text: 'Lee en voz alta lo último que diste like o con lo que reaccionaste en redes.', category: 'risky' },
  { text: 'Interpreta dramáticamente descubrir que tienes un admirador secreto.', category: 'funny' },
  { text: 'Dile al grupo una forma en que cada uno te ha ayudado.', category: 'friendship' },
  { text: 'Baila 30 segundos como si nadie te viera.', category: 'challenge' },
  { text: 'Envía un mensaje de voz a un amigo con un mal chiste.', category: 'funny' },
  { text: 'Deja que el grupo elija tu foto de perfil 48 horas.', category: 'risky' },
  { text: 'Actúa como juez y "sentencia" a cada uno por delitos tontos.', category: 'funny' },
  { text: 'Haz 15 elevaciones de piernas.', category: 'challenge' },
  { text: 'Di una cosa por la que estás agradecido de cada uno.', category: 'friendship' },
  { text: 'Imita a un YouTuber haciendo una intro.', category: 'funny' },
  { text: 'Alguien envía un mensaje desde tu móvil a un contacto que elija (tú apruebas el texto).', category: 'risky' },
  { text: 'Habla con acento australiano las próximas 2 rondas.', category: 'funny' },
  { text: 'Haz 20 círculos con los brazos en cada dirección.', category: 'challenge' },
  { text: 'Llama a un amigo e imítalo (tiene que adivinar).', category: 'funny' },
  { text: 'Lee en voz alta el último mensaje que enviaste a tu mejor amigo.', category: 'risky' },
  { text: 'Recrea dramáticamente tu rutina matutina en 30 segundos.', category: 'funny' },
  { text: 'Dale a la persona de tu izquierda un cumplido genuino que nunca haya oído.', category: 'friendship' },
  { text: 'Haz 10 inchworms.', category: 'challenge' },
  { text: 'El grupo elige una canción; haz playback los primeros 30 segundos.', category: 'funny' },
  { text: 'Actúa como presentador de dating y presenta a todos como concursantes.', category: 'funny' },
  { text: 'Sube una historia con una encuesta; el grupo elige pregunta y opciones.', category: 'risky' },
  { text: 'Imita a un profesor dando una clase.', category: 'funny' },
  { text: 'Di "importas para mí" a cada uno de la habitación.', category: 'friendship' },
  { text: 'Haz 15 saltos de patinador.', category: 'challenge' },
  { text: 'Escribe a alguien "necesito tu opinión sobre algo" y envía una pregunta tonta.', category: 'funny' },
  { text: 'Deja que alguien vea tu lista de llamadas recientes.', category: 'risky' },
  { text: 'Habla con acento neoyorquino las próximas 2 rondas.', category: 'funny' },
  { text: 'Da una "Ted Talk" de 1 minuto sobre un tema que elija el grupo.', category: 'challenge' },
  { text: 'Dile a todos una cosa que admiras de la persona de tu derecha.', category: 'friendship' },
  { text: 'Imita a un presentador de televentas.', category: 'funny' },
  { text: 'El grupo elige la leyenda de tu próxima publicación.', category: 'risky' },
  { text: 'Haz 20 toques de talón.', category: 'challenge' },
  { text: 'Llama a un amigo y dile una cosa que te encanta de él.', category: 'friendship' },
  { text: 'Actúa como subastador y "vende" un objeto de la habitación.', category: 'funny' },
  { text: 'Lee en voz alta el último meme que enviaste.', category: 'risky' },
  { text: 'Lee dramáticamente un anuncio que viste hoy.', category: 'funny' },
  { text: 'Haz 10 saltos con rodillas al pecho (o saltos altos).', category: 'challenge' },
  { text: 'El grupo elige una palabra; no puedes decirla las próximas 3 rondas.', category: 'challenge' },
  { text: 'Di una forma en que cada uno te ha hecho sonreír.', category: 'friendship' },
  { text: 'Imita a un presentador de podcast.', category: 'funny' },
  { text: 'Escribe a un contacto "deberíamos quedar pronto" (el grupo elige a quién).', category: 'risky' },
  { text: 'Habla con acento ruso las próximas 2 rondas.', category: 'funny' },
  { text: 'Haz 15 zancadas laterales a cada lado.', category: 'challenge' },
  { text: 'Da un "discurso de graduación" al grupo en 30 segundos.', category: 'funny' },
  { text: 'Deja que alguien revise tus likes de TikTok o Reels 20 segundos.', category: 'risky' },
  { text: 'Actúa como camarero y toma el "pedido" de todos con un menú imaginario.', category: 'funny' },
  { text: 'Haz 20 toques de hombro en posición de plancha.', category: 'challenge' },
  { text: 'Escribe a un amigo "eres una de mis personas favoritas" sin contexto.', category: 'friendship' },
  { text: 'Imita a un villano dando un monólogo.', category: 'funny' },
  { text: 'Lee en voz alta tu último tweet o publicación.', category: 'risky' },
  { text: 'Interpreta dramáticamente recibir buenas noticias.', category: 'funny' },
  { text: 'Dile a la persona de tu izquierda algo que siempre has querido decirle.', category: 'friendship' },
  { text: 'Salta a la comba 30 segundos (cuerda imaginaria vale).', category: 'challenge' },
  { text: 'El grupo elige una canción vergonzosa; cantas el estribillo.', category: 'funny' },
  { text: 'Actúa como científico y "explica" el juego al grupo.', category: 'funny' },
  { text: 'Sube una historia con una pregunta que escribe el grupo.', category: 'risky' },
  { text: 'Imita el aterrizaje de un superhéroe.', category: 'funny' },
  { text: 'Di "gracias por estar aquí" a cada uno.', category: 'friendship' },
  { text: 'Haz 10 zancadas inversas con cada pierna.', category: 'challenge' },
  { text: 'Llama a alguien y di "estoy jugando y formas parte del juego" y explica.', category: 'funny' },
  { text: 'Deja que el grupo vea la batería y el almacenamiento de tu móvil.', category: 'risky' },
  { text: 'Habla con acento jamaicano las próximas 2 rondas.', category: 'funny' },
  { text: 'Haz 15 superman (tumbado boca abajo, brazos y piernas levantados).', category: 'challenge' },
  { text: 'Dale a cada uno un "premio" y preséntalo dramáticamente.', category: 'friendship' },
  { text: 'Lee dramáticamente la previsión del tiempo de la habitación.', category: 'funny' },
  { text: 'Alguien elige a qué cambias tu estado.', category: 'risky' },
  { text: 'Imita a una persona que acaba de despertarse.', category: 'funny' },
  { text: 'Dile al grupo una cosa que nunca cambiarías de cada uno.', category: 'friendship' },
  { text: 'Haz 20 patadas de mariposa.', category: 'challenge' },
  { text: 'Escribe a un contacto "estoy pensando en ti" con un emoji al azar.', category: 'friendship' },
  { text: 'Actúa como entrenador dando un discurso al grupo.', category: 'funny' },
  { text: 'Lee en voz alta lo último que guardaste o marcaste.', category: 'risky' },
  { text: 'Haz un monólogo dramático de 45 segundos sobre un bocadillo.', category: 'funny' },
  { text: 'Haz 10 burpees con palmada arriba.', category: 'challenge' },
  { text: 'El grupo elige una frase; dila con 5 acentos distintos.', category: 'funny' },
  { text: 'Di una cosa de la que estás orgulloso de cada uno.', category: 'friendship' },
  { text: 'Imita a una persona que acaba de recibir malas noticias.', category: 'funny' },
  { text: 'Envía un mensaje de voz a un amigo con una imitación horrible de él.', category: 'funny' },
  { text: 'Deja que el grupo vea tu calendario de esta semana.', category: 'risky' },
  { text: 'Habla con acento indio las próximas 2 rondas.', category: 'funny' },
  { text: 'Haz 15 puentes de glúteos.', category: 'challenge' },
  { text: 'Llama a un amigo y di "eres el mejor" y cuelga o sigue hablando.', category: 'friendship' },
  { text: 'Actúa como DJ y "pincha" para la habitación.', category: 'funny' },
  { text: 'Lee en voz alta tu última alarma o recordatorio.', category: 'risky' },
  { text: 'Recrea dramáticamente que se te cae el móvil.', category: 'funny' },
  { text: 'Haz 20 abdominales bicicleta.', category: 'challenge' },
  { text: 'Dile a todos una forma en que la persona de tu derecha te ha influido.', category: 'friendship' },
  { text: 'Imita a una persona en una montaña rusa.', category: 'funny' },
  { text: 'El grupo elige un contacto; le envías un mensaje que escribe el grupo.', category: 'risky' },
  { text: 'Habla con acento de Boston las próximas 2 rondas.', category: 'funny' },
  { text: 'Haz 30 segundos de sombra boxeo.', category: 'challenge' },
  { text: 'Da un discurso estilo "Estado de la Unión" sobre el juego.', category: 'funny' },
  { text: 'Sube una foto que elija el grupo de tu galería (sin caras si hace falta).', category: 'risky' },
  { text: 'Imita a una persona que acaba de recibir grandes noticias.', category: 'funny' },
  { text: 'Di "me alegra que estés en mi vida" a cada uno.', category: 'friendship' },
  { text: 'Haz 10 sprawls.', category: 'challenge' },
  { text: 'Escribe a alguien "pregunta rápida" y envía algo al azar.', category: 'funny' },
  { text: 'Deja que alguien lea tu última nota o recordatorio.', category: 'risky' },
  { text: 'Actúa como presentador de talentos e presenta al siguiente jugador.', category: 'funny' },
  { text: 'Haz 15 elevaciones de piernas tumbado.', category: 'challenge' },
  { text: 'Dile a la persona de tu izquierda qué harías si te necesitara a las 3am.', category: 'friendship' },
  { text: 'Lee dramáticamente una receta.', category: 'funny' },
  { text: 'El grupo elige la leyenda de tu próxima publicación en Instagram.', category: 'risky' },
  { text: 'Imita a una persona que acaba de ver un fantasma.', category: 'funny' },
  { text: 'Di una cosa que harías para mejorar el día de cada uno.', category: 'friendship' },
  { text: 'Haz 20 sentadillas estáticas.', category: 'challenge' },
  { text: 'Llama a un amigo e imita a un famoso 30 segundos.', category: 'funny' },
  { text: 'Lee en voz alta tu última búsqueda de YouTube o vídeo.', category: 'risky' },
  { text: 'Habla con acento sureño las próximas 2 rondas.', category: 'funny' },
  { text: 'Haz 10 saltos a caja (suelo o superficie baja).', category: 'challenge' },
  { text: 'Dale a cada uno un "superpoder" según su personalidad.', category: 'friendship' },
  { text: 'Interpreta dramáticamente abrir un regalo que te encanta.', category: 'funny' },
  { text: 'El grupo elige una canción; la tarareas y adivinan.', category: 'funny' },
  { text: 'Actúa como presentador de talk show e "entrevista" a la persona de tu derecha.', category: 'funny' },
  { text: 'Envía un mensaje a un contacto con un cumplido (el grupo aprueba).', category: 'risky' },
  { text: 'Imita a una persona que acaba de terminar un maratón.', category: 'funny' },
  { text: 'Di una cosa que tienes en común con cada uno.', category: 'friendship' },
  { text: 'Haz 15 elevaciones de gemelos.', category: 'challenge' },
  { text: 'Deja que alguien vea tus últimos 3 archivos descargados.', category: 'risky' },
  { text: 'Haz un voiceover "documental" de 1 minuto sobre la habitación.', category: 'funny' },
  { text: 'Haz 20 jumping jacks diciendo el abecedario.', category: 'challenge' },
  { text: 'Cuéntale al grupo un recuerdo que tienes con cada uno.', category: 'friendship' },
  { text: 'Imita a una persona que acaba de perder las llaves.', category: 'funny' },
  { text: 'Sube una historia con una pregunta; la escribe el grupo.', category: 'risky' },
  { text: 'Habla con acento canadiense las próximas 2 rondas.', category: 'funny' },
  { text: 'Haz 10 v-ups o abdominales.', category: 'challenge' },
  { text: 'Escribe a un familiar "te quiero" con una razón concreta.', category: 'friendship' },
  { text: 'Actúa como presentador de telerrealidad y narra la próxima ronda.', category: 'funny' },
  { text: 'Lee en voz alta lo último que compartiste en redes.', category: 'risky' },
  { text: 'Recrea dramáticamente darte un golpe en el dedo.', category: 'funny' },
  { text: 'Haz 15 flexiones contra la pared.', category: 'challenge' },
  { text: 'El grupo te da una "misión" que completar antes de que acabe el juego.', category: 'challenge' },
  { text: 'Di "marcas la diferencia" a cada uno.', category: 'friendship' },
  { text: 'Imita a una persona que acaba de recibir un ascenso.', category: 'funny' },
  { text: 'Envía un mensaje de voz a un amigo con un dato al azar.', category: 'funny' },
  { text: 'Alguien elige tu próxima actualización de estado.', category: 'risky' },
  { text: 'Habla con acento real británico las próximas 2 rondas.', category: 'funny' },
  { text: 'Haz 20 elevaciones de brazos (frontal y lateral).', category: 'challenge' },
  { text: 'Da un "elogio fúnebre" de un objeto de la habitación (en plan gracioso).', category: 'funny' },
  { text: 'Dile a la persona de tu derecha algo que siempre has querido hacer con ella.', category: 'friendship' },
  { text: 'Lee dramáticamente la descripción de un producto.', category: 'funny' },
  { text: 'Deja que el grupo vea tu captura de pantalla más reciente.', category: 'risky' },
  { text: 'Imita a una persona que acaba de recibir una multa.', category: 'funny' },
  { text: 'Di una cosa que respetas de cada uno.', category: 'friendship' },
  { text: 'Haz 10 flexiones de rodillas.', category: 'challenge' },
  { text: 'Llama a un amigo y di "eres increíble" y explica por qué (30 seg).', category: 'friendship' },
  { text: 'Actúa como presentador de programa de cocina con un plato imaginario.', category: 'funny' },
  { text: 'Lee en voz alta el asunto de tu último email enviado.', category: 'risky' },
  { text: 'Haz un monólogo dramático de 30 segundos sobre calcetines.', category: 'funny' },
  { text: 'Haz 15 giros oblicuos de pie.', category: 'challenge' },
  { text: 'El grupo elige un reto que tienes que hacer en las próximas 24 horas.', category: 'challenge' },
  { text: 'Dile a todos una forma en que cada uno te ha hecho reír.', category: 'friendship' },
  { text: 'Imita a una persona que acaba de ver a su crush.', category: 'funny' },
  { text: 'Envía un chiste de padre a un contacto (el grupo puede dar uno).', category: 'funny' },
  { text: 'Deja que alguien vea tus apps recientes.', category: 'risky' },
  { text: 'Habla con acento pirata las próximas 3 rondas.', category: 'funny' },
  { text: 'Haz 20 subidas a step (o superficie baja).', category: 'challenge' },
  { text: 'Da un "discurso de Oscar" agradeciendo a todos en la habitación.', category: 'friendship' },
  { text: 'Interpreta dramáticamente encontrar una araña.', category: 'funny' },
  { text: 'Sube una historia con una canción que elija el grupo.', category: 'risky' },
  { text: 'Actúa como presentador de podcast e entrevista a la persona de tu izquierda.', category: 'funny' },
  { text: 'Haz 10 abdominales inversos.', category: 'challenge' },
  { text: 'Di "tengo suerte de conocerte" a cada uno.', category: 'friendship' },
  { text: 'Imita a una persona que acaba de recibir un regalo.', category: 'funny' },
  { text: 'Lee en voz alta tu última nota para ti mismo.', category: 'risky' },
  { text: 'Lee dramáticamente una señal o etiqueta de la habitación.', category: 'funny' },
  { text: 'Haz 15 elevaciones de cadera.', category: 'challenge' },
  { text: 'Dile a la persona de tu izquierda algo que nunca olvidarás de ella.', category: 'friendship' },
  { text: 'El grupo elige una frase; dila como un tráiler de película.', category: 'funny' },
  { text: 'Envía un mensaje a alguien diciendo "me alegraste el día" (cuando no fue así).', category: 'funny' },
  { text: 'Alguien elige qué publicas después (foto o texto).', category: 'risky' },
  { text: 'Imita a una persona que acaba de despertar de una siesta.', category: 'funny' },
  { text: 'Di una cosa por la que agradecerías a cada uno.', category: 'friendship' },
  { text: 'Haz 20 círculos con las piernas tumbado.', category: 'challenge' },
  { text: 'Llama a un amigo e imita a un profesor 20 segundos.', category: 'funny' },
  { text: 'Lee en voz alta lo último que buscaste en Google.', category: 'risky' },
  { text: 'Habla con acento de villano las próximas 2 rondas.', category: 'funny' },
  { text: 'Haz 10 bird dogs (brazo y pierna opuestos).', category: 'challenge' },
  { text: 'Dale a cada uno un "título" (ej. "Jefe de la Diversión") y úsalo 2 rondas.', category: 'friendship' },
  { text: 'Recrea dramáticamente resbalar en el hielo.', category: 'funny' },
  { text: 'El grupo elige una pregunta; la publicas como tu estado.', category: 'risky' },
  { text: 'Actúa como presentador de concurso y explica la próxima ronda.', category: 'funny' },
  { text: 'Haz 15 dead bugs.', category: 'challenge' },
  { text: 'Escribe a un amigo "te estoy agradecido" con una razón breve.', category: 'friendship' },
  { text: 'Imita a una persona que acaba de recibir un mensaje de su crush.', category: 'funny' },
  { text: 'Deja que alguien vea tus últimos 5 usos de emojis.', category: 'risky' },
  { text: 'Haz un monólogo dramático de 45 segundos sobre el tiempo.', category: 'funny' },
  { text: 'Marcha en el sitio con rodillas altas 20 veces.', category: 'challenge' },
  { text: 'Dile al grupo una cosa que harías para animar a cada uno.', category: 'friendship' },
  { text: 'Imita a una persona que acaba de ganar un juego.', category: 'funny' },
  { text: 'Sube una historia con una foto que elija el grupo.', category: 'risky' },
  { text: 'Habla con voz soñolienta las próximas 2 rondas.', category: 'funny' },
  { text: 'Haz 10 estiramientos gato-vaca (yoga).', category: 'challenge' },
  { text: 'Di "eres importante para mí" a cada uno.', category: 'friendship' },
  { text: 'Actúa como presentador de premios y entrega un premio a la habitación.', category: 'funny' },
  { text: 'Lee en voz alta tu última playlist o álbum que escuchaste.', category: 'risky' },
  { text: 'Interpreta dramáticamente que te dan una fiesta sorpresa.', category: 'funny' },
  { text: 'Haz 15 curl de pierna de pie.', category: 'challenge' },
  { text: 'El grupo elige una palabra; no puedes decir "sí" ni "no" 2 rondas.', category: 'challenge' },
  { text: 'Dile a la persona de tu derecha algo que admiras de su personalidad.', category: 'friendship' },
  { text: 'Imita a una persona que acaba de comer algo picante.', category: 'funny' },
  { text: 'Envía un mensaje de voz a un contacto con un chiste (el grupo aprueba).', category: 'risky' },
  { text: 'Habla en susurro las próximas 3 rondas.', category: 'funny' },
  { text: 'Haz 20 círculos de tobillo en cada dirección.', category: 'challenge' },
  { text: 'Da una "rueda de prensa" como si acabaras de ganar algo grande.', category: 'funny' },
  { text: 'Alguien elige el tipo de tu próxima historia de Instagram (encuesta, pregunta, etc.).', category: 'risky' },
  { text: 'Imita a una persona a la que acaban de pillar en una mentira.', category: 'funny' },
  { text: 'Di una cosa que harías para apoyar a cada uno.', category: 'friendship' },
  { text: 'Haz 10 molinos (toques a los pies).', category: 'challenge' },
  { text: 'Llama a un amigo y di "tengo que decirte algo" y luego "eres genial".', category: 'funny' },
  { text: 'Lee en voz alta el nombre de tu última alarma.', category: 'risky' },
  { text: 'Lee dramáticamente una etiqueta nutricional.', category: 'funny' },
  { text: 'Haz 15 giros de cuello (suaves).', category: 'challenge' },
  { text: 'Dile a todos una forma en que cada uno te ha ayudado a crecer.', category: 'friendship' },
  { text: 'Imita a una persona que acaba de recibir un ascenso.', category: 'funny' },
  { text: 'El grupo escribe un mensaje corto; lo envías a quien elijan.', category: 'risky' },
  { text: 'Actúa como presentador de documental y narra la habitación 1 minuto.', category: 'funny' },
  { text: 'Haz 20 círculos de muñeca.', category: 'challenge' },
  { text: 'Escribe a alguien "eres de los buenos" sin contexto.', category: 'friendship' },
  { text: 'Recrea dramáticamente tu reacción a un susto.', category: 'funny' },
  { text: 'Deja que alguien vea tus últimas 3 fotos (puedes difuminar si hace falta).', category: 'risky' },
  { text: 'Habla con voz de niño emocionado las próximas 2 rondas.', category: 'funny' },
  { text: 'Haz 10 giros de hombros.', category: 'challenge' },
  { text: 'Di "te valoro" a cada uno.', category: 'friendship' },
  { text: 'Imita a una persona que acaba de recibir un cumplido.', category: 'funny' },
  { text: 'Sube una historia con un "esto o aquello" que cree el grupo.', category: 'risky' },
  { text: 'Haz un monólogo dramático de 30 segundos sobre un boli.', category: 'funny' },
  { text: 'Haz 15 giros de torso.', category: 'challenge' },
  { text: 'Dile a la persona de tu izquierda algo que te encanta de vuestra amistad.', category: 'friendship' },
  { text: 'Actúa como presentador de programa matinal y haz el "tiempo" de la habitación.', category: 'funny' },
  { text: 'Lee en voz alta tu último recordatorio.', category: 'risky' },
  { text: 'Imita a una persona que acaba de recibir mal servicio.', category: 'funny' },
  { text: 'Di una cosa que harías para celebrar a cada uno.', category: 'friendship' },
  { text: 'Haz 20 estiramientos de brazos.', category: 'challenge' },
  { text: 'El grupo elige una canción; cantas una línea con voz graciosa.', category: 'funny' },
  { text: 'Envía un mensaje a un amigo con una cita positiva.', category: 'friendship' },
  { text: 'Alguien elige tu próximo estado de WhatsApp.', category: 'risky' },
  { text: 'Interpreta dramáticamente encontrar dinero en el suelo.', category: 'funny' },
  { text: 'Haz 10 estiramientos de cuádriceps (cada pierna).', category: 'challenge' },
  { text: 'Dile al grupo una cosa que has aprendido de cada uno.', category: 'friendship' },
  { text: 'Imita a una persona que acaba de recibir un pedido equivocado.', category: 'funny' },
  { text: 'Lee en voz alta el título de tu último evento del calendario.', category: 'risky' },
  { text: 'Habla con voz de tráiler de película dramática la próxima ronda.', category: 'funny' },
  { text: 'Haz 15 estiramientos de isquiotibiales.', category: 'challenge' },
  { text: 'Da un "discurso del estado de la habitación" como si fueras un líder.', category: 'funny' },
  { text: 'El grupo elige una pregunta; la respondes en tu historia.', category: 'risky' },
  { text: 'Imita a una persona que acaba de recibir buenas noticias.', category: 'funny' },
  { text: 'Di "perteneces aquí" a cada uno.', category: 'friendship' },
  { text: 'Haz 20 círculos de cadera.', category: 'challenge' },
  { text: 'Llama a un amigo y di "solo quería saludar" y charla 1 minuto.', category: 'friendship' },
  { text: 'Actúa como presentador de programa de viajes y "visita" la habitación.', category: 'funny' },
  { text: 'Lee en voz alta tu última nota escrita.', category: 'risky' },
  { text: 'Recrea dramáticamente olvidar el nombre de alguien.', category: 'funny' },
  { text: 'Haz 10 estiramientos figura cuatro (cada lado).', category: 'challenge' },
  { text: 'Dile a la persona de tu derecha algo que siempre recordarás.', category: 'friendship' },
  { text: 'Imita a una persona que acaba de recibir un like.', category: 'funny' },
  { text: 'El grupo elige una frase; dila de forma dramática.', category: 'funny' },
  { text: 'Sube una historia con cuenta atrás o temporizador que ponga el grupo.', category: 'risky' },
  { text: 'Haz 15 giros spinales (sentado).', category: 'challenge' },
  { text: 'Di una cosa que harías para que cada uno se sienta especial.', category: 'friendship' },
  { text: 'Imita a una persona que acaba de recibir una solicitud de seguimiento.', category: 'funny' },
  { text: 'Envía un mensaje de voz a un amigo diciendo que le echas de menos.', category: 'friendship' },
  { text: 'Deja que alguien vea tus últimas 5 búsquedas.', category: 'risky' },
  { text: 'Habla con voz monótona las próximas 2 rondas.', category: 'funny' },
];

module.exports = { truths, dares };
