const truths = [
    { text: 'Qual è la tua paura più grande?', category: 'general' },
    { text: 'Qual è la cosa più imbarazzante che ti sia mai capitata?', category: 'funny' },
    { text: 'Hai mai mentito per evitare dei piani?', category: 'general' },
    { text: 'Qual è il tuo piacere colpevole?', category: 'general' },
    { text: 'Chi era il tuo primo amore?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai detto su un amico?', category: 'risky' },
    { text: 'Hai mai copiato a un esame?', category: 'general' },
    { text: 'Qual è il tuo più grande rimpianto?', category: 'general' },
    { text: 'Hai mai avuto una cotta per il/la partner di un amico?', category: 'risky' },
    { text: 'Qual è la cosa più sciocca in cui credi?', category: 'funny' },
    { text: 'Qual è la tua paura più irrazionale?', category: 'general' },
    { text: 'Hai mai finto di apprezzare un regalo?', category: 'funny' },
    { text: 'Qual è la cosa più cattiva che hai fatto?', category: 'risky' },
    { text: 'Su chi hai una cotta segreta adesso?', category: 'risky' },
    { text: 'C\'è qualcosa che non hai mai detto a nessuno?', category: 'risky' },
    { text: 'Hai mai spezzato il cuore a qualcuno?', category: 'friendship' },
    { text: 'Qual è la tua abitudine più imbarazzante?', category: 'funny' },
    { text: 'Hai mai diffuso una voce?', category: 'risky' },
    { text: 'Qual è il peggiore appuntamento che hai mai avuto?', category: 'general' },
    { text: 'Sei mai stato innamorato?', category: 'friendship' },
    { text: 'Qual è la tua più grande insicurezza?', category: 'general' },
    { text: 'Hai mai rubato qualcosa?', category: 'risky' },
    { text: 'Qual è la cosa più infantile che fai ancora?', category: 'funny' },
    { text: 'Hai mai mentito ai tuoi genitori?', category: 'general' },
    { text: 'Qual è il tuo talento segreto?', category: 'general' },
    { text: 'Hai mai rischiato la vita?', category: 'general' },
    { text: 'Qual è la cosa peggiore che hai fatto da ubriaco?', category: 'risky' },
    { text: 'Sei mai stato rifiutato?', category: 'friendship' },
    { text: 'Qual è la cosa che ti dà più fastidio?', category: 'general' },
    { text: 'Sei mai stato scoperto in una bugia?', category: 'funny' },
    { text: 'Cosa faresti se ti rimanesse un solo giorno da vivere?', category: 'challenge' },
    { text: 'Qual è il guaio più grande in cui ti sei mai cacciato?', category: 'risky' },
    { text: 'Hai mai avuto un\'avventura di una notte?', category: 'risky' },
    { text: 'Qual è la tua opinione più controversa?', category: 'challenge' },
    { text: 'Hai mai tradito un amico?', category: 'risky' },
    { text: 'Qual è il tuo segreto più grande?', category: 'risky' },
    { text: 'Hai mai avuto uno scontro fisico?', category: 'risky' },
    { text: 'Qual è il lavoro peggiore che tu abbia mai avuto?', category: 'general' },
    { text: 'Sei mai stato arrestato o fermato dalla polizia?', category: 'risky' },
    { text: 'C\'è qualcosa che non rifaresti mai?', category: 'general' },
    { text: 'Qual è la canzone più imbarazzante nella tua playlist?', category: 'funny' },
    { text: 'Hai mai avuto una cotta per un insegnante o un capo?', category: 'risky' },
    { text: 'Qual è la bugia peggiore che tu abbia mai detto?', category: 'risky' },
    { text: 'Sei mai stato sorpreso a fare qualcosa di proibito?', category: 'general' },
    { text: 'Qual è il tuo ricordo d\'infanzia più imbarazzante?', category: 'funny' },
    { text: 'Hai mai ghostato qualcuno?', category: 'friendship' },
    { text: 'Qual è il sogno più strano che tu abbia mai fatto?', category: 'general' },
    { text: 'Hai mai avuto un segreto che non riuscivi a tenere?', category: 'risky' },
    { text: 'Qual è la cosa più sconsiderata che hai fatto?', category: 'risky' },
    { text: 'Hai mai avuto una cotta per il fratello o la sorella di un amico?', category: 'friendship' },
    { text: 'C\'è qualcosa di cui sei orgoglioso ma che non condividi mai?', category: 'general' },
    { text: 'Hai mai finto di essere malato per evitare qualcosa?', category: 'funny' },
    { text: 'Qual è la cosa che ti allontana di più da una persona?', category: 'general' },
    { text: 'Sei mai stato piantato in asso a un appuntamento?', category: 'friendship' },
    { text: 'Qual è la somma più grande che hai mai speso per qualcosa di stupido?', category: 'general' },
    { text: 'Hai mai rischiato di avere guai con la legge?', category: 'risky' },
    { text: 'Qual è il regalo peggiore che hai mai ricevuto?', category: 'funny' },
    { text: 'Sei mai stato innamorato di due persone allo stesso tempo?', category: 'risky' },
    { text: 'Qual è la tua opinione culinaria più controversa?', category: 'challenge' },
    { text: 'Hai mai mentito nel tuo curriculum?', category: 'risky' },
    { text: 'Qual è la cosa più infantile che ancora ti piace?', category: 'funny' },
    { text: 'Hai mai avuto un\'amicizia che è finita male?', category: 'friendship' },
    { text: 'C\'è qualcosa che faresti se nessuno ti giudicasse?', category: 'challenge' },
    { text: 'Sei mai stato sorpreso a controllare qualcuno?', category: 'funny' },
    { text: 'Qual è la tua più grande fissazione irrazionale?', category: 'general' },
    { text: 'Hai mai avuto un\'amicizia a senso unico?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai detto alle spalle di qualcuno?', category: 'risky' },
    { text: 'Hai mai finto di essere occupato per evitare qualcuno?', category: 'funny' },
    { text: 'Qual è la tua serie o film colpevole?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno in questa stanza?', category: 'risky' },
    { text: 'Qual è la cosa più imbarazzante che abbiano fatto i tuoi genitori?', category: 'funny' },
    { text: 'Sei mai finito in una situazione davvero imbarazzante?', category: 'funny' },
    { text: 'C\'è qualcosa che ti penti di aver detto?', category: 'general' },
    { text: 'Hai mai avuto un ammiratore segreto?', category: 'friendship' },
    { text: 'Qual è la tua abitudine peggiore?', category: 'general' },
    { text: 'Sei mai stato "l\'altra persona" in una situazione?', category: 'risky' },
    { text: 'Qual è la cosa più imbarazzante nella tua cronologia di ricerca?', category: 'funny' },
    { text: 'Hai mai finto di conoscere qualcuno che non conoscevi?', category: 'funny' },
    { text: 'Qual è la tua più grande paura per il futuro?', category: 'general' },
    { text: 'Hai mai avuto una cotta per una celebrità di cui ti vergogni?', category: 'funny' },
    { text: 'Qual è la cosa più egoista che hai fatto?', category: 'risky' },
    { text: 'Sei mai stato sorpreso a mentire al tuo partner?', category: 'risky' },
    { text: 'Qual è la cosa più strana che trovi attraente?', category: 'challenge' },
    { text: 'Hai mai sognato qualcuno presente in questa stanza?', category: 'risky' },
    { text: 'Qual è la peggiore voce che hai sentito su di te?', category: 'general' },
    { text: 'Sei mai rimasto in una relazione sapendo che era sbagliata?', category: 'friendship' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto per impressionare qualcuno?', category: 'funny' },
    { text: 'Sei mai stato sorpreso a parlare da solo?', category: 'funny' },
    { text: 'Qual è la tua più grande insicurezza sul tuo aspetto?', category: 'general' },
    { text: 'Hai mai avuto un segreto che avrebbe potuto rovinare un\'amicizia?', category: 'risky' },
    { text: 'Qual è la lite più infantile che hai avuto?', category: 'funny' },
    { text: 'Hai mai invidiato il successo di un amico?', category: 'friendship' },
    { text: 'Qual è il peggior consiglio che tu abbia mai dato?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno molto più grande o più giovane di te?', category: 'risky' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto al lavoro o a scuola?', category: 'funny' },
    { text: 'Qual è l\'ultima cosa che hai cercato online?', category: 'general' },
    { text: 'Hai mai avuto un documento falso?', category: 'risky' },
    { text: 'Qual è la tua canzone karaoke preferita?', category: 'funny' },
    { text: 'Sei mai stato sorpreso a metterti le dita nel naso?', category: 'funny' },
    { text: 'Qual è la combinazione di cibi più bizzarra che ti piace?', category: 'general' },
    { text: 'Hai mai pianto guardando un film?', category: 'friendship' },
    { text: 'Qual è la tua scusa preferita per essere in ritardo?', category: 'general' },
    { text: 'Hai mai avuto un incidente di abbigliamento in pubblico?', category: 'funny' },
    { text: 'Qual è l\'ultimo acquisto che rimpianti?', category: 'general' },
    { text: 'Hai mai avuto una cotta per un personaggio dei cartoni animati?', category: 'funny' },
    { text: 'Qual è la tua più grande paura nelle relazioni sentimentali?', category: 'general' },
    { text: 'Hai mai spiato il telefono di qualcun altro?', category: 'risky' },
    { text: 'Qual è la cosa più imbarazzante nella tua stanza?', category: 'funny' },
    { text: 'Hai mai finto di aver letto un libro che non hai mai finito?', category: 'funny' },
    { text: 'Qual è il tuo hobby segreto?', category: 'general' },
    { text: 'Sei mai stato sorpreso a cantare sotto la doccia?', category: 'funny' },
    { text: 'Qual è il taglio di capelli peggiore che hai mai avuto?', category: 'funny' },
    { text: 'Hai mai avuto una cotta per un collega?', category: 'risky' },
    { text: 'In cosa sei stranamente bravo?', category: 'general' },
    { text: 'Hai mai dato la colpa a un fratello o una sorella per qualcosa che avevi fatto tu?', category: 'friendship' },
    { text: 'Qual è il tuo momento più imbarazzante dell\'infanzia?', category: 'funny' },
    { text: 'Hai mai inviato un messaggio alla persona sbagliata?', category: 'risky' },
    { text: 'Qual è il complimento più strano che hai ricevuto?', category: 'general' },
    { text: 'Hai mai fatto un sogno che sembrava troppo reale?', category: 'general' },
    { text: 'Qual è il tuo snack colpevole?', category: 'general' },
    { text: 'Sei mai stato colto in una bugia bianca?', category: 'funny' },
    { text: 'Qual è la fase di moda peggiore che hai attraversato?', category: 'funny' },
    { text: 'Hai mai rischiato un incidente mentre guidavi?', category: 'risky' },
    { text: 'C\'è qualcosa che non ammetteresti mai di persona?', category: 'challenge' },
    { text: 'Hai mai avuto una cotta per l\'ex di un amico?', category: 'risky' },
    { text: 'Qual è il tuo errore di autocorrettore più imbarazzante?', category: 'funny' },
    { text: 'Hai mai finto di essere al telefono per evitare qualcuno?', category: 'funny' },
    { text: 'Qual è il peggiore regalo che tu abbia mai fatto?', category: 'general' },
    { text: 'Sei mai stato sorpreso a fare qualcosa di imbarazzante?', category: 'funny' },
    { text: 'Qual è la tua più grande paura nell\'invecchiare?', category: 'general' },
    { text: 'Hai mai avuto una stretta di mano segreta con qualcuno?', category: 'friendship' },
    { text: 'Qual è la cosa più infantile che trovi ancora divertente?', category: 'funny' },
    { text: 'Hai mai mentito sulla tua età?', category: 'risky' },
    { text: 'Qual è il peggior consiglio che tu abbia mai seguito?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno che hai appena incontrato?', category: 'friendship' },
    { text: 'Qual è il tuo momento più imbarazzante a una festa?', category: 'funny' },
    { text: 'Sei mai stato sorpreso a parlare nel sonno?', category: 'funny' },
    { text: 'Qual è la cosa più strana che tu abbia mai mangiato?', category: 'general' },
    { text: 'Hai mai avuto un\'amicizia che è iniziata con una bugia?', category: 'risky' },
    { text: 'Qual è la tua più grande paura di essere giudicato?', category: 'general' },
    { text: 'Hai mai finto di apprezzare una canzone per integrarti?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai detto ad alta voce?', category: 'funny' },
    { text: 'Hai mai avuto un codice segreto con un amico?', category: 'friendship' },
    { text: 'Qual è la peggiore idea di appuntamento che tu abbia mai avuto?', category: 'general' },
    { text: 'Sei mai stato sorpreso a ballare pensando che nessuno ti guardasse?', category: 'funny' },
    { text: 'Qual è l\'ultima app che hai scaricato?', category: 'general' },
    { text: 'Hai mai avuto un soprannome che odiavi?', category: 'funny' },
    { text: 'Qual è la cosa che ti dà più fastidio in un coinquilino?', category: 'general' },
    { text: 'Hai mai finto di essere malato per attirare attenzione?', category: 'funny' },
    { text: 'Qual è l\'acquisto più impulsivo che hai fatto?', category: 'general' },
    { text: 'Hai mai avuto una cotta per uno sconosciuto visto una sola volta?', category: 'friendship' },
    { text: 'Qual è la barzelletta peggiore che tu abbia mai raccontato?', category: 'funny' },
    { text: 'Sei mai stato sorpreso a guardarti allo specchio?', category: 'funny' },
    { text: 'Qual è il tuo cibo confortante segreto?', category: 'general' },
    { text: 'Hai mai mentito sulla tua altezza o il tuo peso?', category: 'risky' },
    { text: 'Qual è la cosa più imbarazzante che abbia fatto tuo fratello o tua sorella?', category: 'funny' },
    { text: 'Hai mai sognato qualcuno che non ti piace?', category: 'general' },
    { text: 'Qual è la peggiore abitudine che hai preso da qualcuno?', category: 'general' },
    { text: 'Sei mai stato sorpreso a fare un selfie?', category: 'funny' },
    { text: 'Qual è la tua più grande paura del fallimento?', category: 'general' },
    { text: 'Hai mai avuto un segreto che hai detto solo a una persona?', category: 'risky' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto per i like?', category: 'funny' },
    { text: 'Hai mai finto di capire una barzelletta che non avevi capito?', category: 'funny' },
    { text: 'Qual è la voce peggiore che tu abbia mai diffuso?', category: 'risky' },
    { text: 'Hai mai avuto una cotta per un personaggio di un libro o di una serie?', category: 'funny' },
    { text: 'Qual è il tuo momento più imbarazzante in educazione fisica?', category: 'funny' },
    { text: 'Sei mai stato sorpreso a parlare con il tuo animale come se fosse una persona?', category: 'funny' },
    { text: 'Qual è la cosa più strana in cui credevi da bambino?', category: 'funny' },
    { text: 'Hai mai avuto un\'amicizia finita per un malinteso?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di essere solo?', category: 'general' },
    { text: 'Hai mai finto di essere occupato quando non lo eri?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante nella tua cronologia di navigazione?', category: 'risky' },
    { text: 'Sei mai stato sorpreso a cantare in macchina?', category: 'funny' },
    { text: 'Qual è la peggior frase di rimorchio che hai usato o sentito?', category: 'funny' },
    { text: 'Hai mai avuto un segreto che alla fine hai rivelato?', category: 'risky' },
    { text: 'Qual è la tua più irrazionale fissazione?', category: 'general' },
    { text: 'Hai mai finto di lavorare quando stavi perdendo tempo?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto per attirare attenzione?', category: 'funny' },
    { text: 'Hai mai invidiato la relazione di un amico?', category: 'friendship' },
    { text: 'Qual è la scelta di moda peggiore che tu abbia mai fatto?', category: 'funny' },
    { text: 'Hai mai avuto una cotta per qualcuno che non ti ricambiava?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura dell\'impegno?', category: 'general' },
    { text: 'Sei mai stato sorpreso a sognare a occhi aperti in classe o al lavoro?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai pubblicato online?', category: 'funny' },
    { text: 'Hai mai mentito su dove eri?', category: 'risky' },
    { text: 'Qual è il sogno più strano che hai fatto su qualcuno qui presente?', category: 'challenge' },
    { text: 'Hai mai avuto un ammiratore segreto senza dirlo a nessuno?', category: 'friendship' },
    { text: 'Qual è il tuo momento più imbarazzante a una riunione di famiglia?', category: 'funny' },
    { text: 'Sei mai stato fotografato con una smorfia imbarazzante?', category: 'funny' },
    { text: 'Qual è la cosa peggiore che hai fatto sotto l\'effetto della rabbia?', category: 'risky' },
    { text: 'Hai mai avuto una cotta per la cotta di un amico?', category: 'risky' },
    { text: 'Qual è la tua più grande paura di essere vulnerabile?', category: 'general' },
    { text: 'Hai mai finto di apprezzare un cibo che odi?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto a un appuntamento?', category: 'funny' },
    { text: 'Sei mai stato sorpreso a ridere della tua stessa barzelletta?', category: 'funny' },
    { text: 'Qual è la bugia peggiore che hai detto per evitare dei piani?', category: 'general' },
    { text: 'Hai mai avuto un\'amicizia che ti penti di aver terminato?', category: 'friendship' },
    { text: 'Qual è il tuo momento più imbarazzante durante una vacanza?', category: 'funny' },
    { text: 'Sei mai stato sorpreso a parlare da solo in pubblico?', category: 'funny' },
    { text: 'Qual è la cosa più strana che collezzioni o che collezionavi?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno in una posizione di potere?', category: 'risky' },
    { text: 'Qual è la tua più grande paura del rifiuto?', category: 'general' },
    { text: 'Hai mai finto di aver visto un film che non hai mai visto?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto a un matrimonio?', category: 'funny' },
    { text: 'Sei mai stato sorpreso a fare qualcosa che avevi detto di non fare mai?', category: 'funny' },
    { text: 'Qual è la peggior scusa che tu abbia mai usato?', category: 'general' },
    { text: 'Hai mai avuto un segreto che avrebbe potuto cambiare una relazione?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante a un colloquio di lavoro?', category: 'funny' },
    { text: 'Hai mai invidiato un fratello o una sorella?', category: 'friendship' },
    { text: 'Qual è la cosa più strana che hai fatto quando nessuno guardava?', category: 'challenge' },
    { text: 'Hai mai avuto una cotta per qualcuno che non faceva per te?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura del successo?', category: 'general' },
    { text: 'Hai mai finto di dormire per evitare qualcuno?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto in un ristorante?', category: 'funny' },
    { text: 'Sei mai stato sorpreso a guardare qualcosa di imbarazzante?', category: 'funny' },
    { text: 'Qual è la peggior decisione che hai preso d\'impulso?', category: 'general' },
    { text: 'Hai mai avuto un segreto che stai ancora tenendo?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante a un primo appuntamento?', category: 'funny' },
    { text: 'Sei mai stato l\'ultimo a sapere qualcosa su un amico?', category: 'friendship' },
    { text: 'Qual è la tua abitudine più strana?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno che non avresti dovuto?', category: 'risky' },
    { text: 'Qual è la tua più grande paura del cambiamento?', category: 'general' },
    { text: 'Hai mai finto di essere sicuro di te quando non lo eri?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto a un pigiama party?', category: 'funny' },
    { text: 'Sei mai stato in una foto imbarazzante?', category: 'funny' },
    { text: 'Qual è la cosa peggiore che hai detto nel momento del calore?', category: 'risky' },
    { text: 'Hai mai avuto un\'amicizia a senso unico?', category: 'friendship' },
    { text: 'Qual è il tuo momento più imbarazzante a un concerto?', category: 'funny' },
    { text: 'Sei mai stato sorpreso a cantare in pubblico?', category: 'funny' },
    { text: 'Qual è la cosa più strana che trovi confortante?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno che hai conosciuto online?', category: 'risky' },
    { text: 'Qual è la tua più grande paura dell\'ignoto?', category: 'general' },
    { text: 'Hai mai finto di essere interessato a un argomento che odi?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto a una rimpatriata?', category: 'funny' },
    { text: 'Sei mai stato sorpreso a fare qualcosa di infantile?', category: 'funny' },
    { text: 'Qual è la cosa peggiore che hai fatto per impressionare qualcuno?', category: 'risky' },
    { text: 'Hai mai avuto un segreto che vorresti poter dire?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante durante una vacanza?', category: 'funny' },
    { text: 'Sei mai stato quello che ha messo fine a un\'amicizia?', category: 'friendship' },
    { text: 'Qual era la paura più strana che avevi da bambino?', category: 'funny' },
    { text: 'Hai mai avuto una cotta per qualcuno senza dirtelo mai?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di fidarsi?', category: 'general' },
    { text: 'Hai mai finto di essere felice quando non lo eri?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto a un funerale?', category: 'funny' },
    { text: 'Sei mai stato scoperto in una bugia da un amico?', category: 'risky' },
    { text: 'Qual è la cosa peggiore che hai fatto quando ti annoiavi?', category: 'general' },
    { text: 'Hai mai avuto un segreto che ti faceva sentire in colpa?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante a una festa di compleanno?', category: 'funny' },
    { text: 'Sei mai stato il terzo incomodo?', category: 'friendship' },
    { text: 'Qual è la cosa più strana che tu abbia mai detto a qualcuno?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno che non puoi avere?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di essere dimenticato?', category: 'general' },
    { text: 'Hai mai finto di essere d\'accordo quando non lo eri?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto a un concerto?', category: 'funny' },
    { text: 'Sei mai stato quello che ha dovuto scusarsi?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri stanco?', category: 'general' },
    { text: 'Hai mai avuto un segreto di cui sei orgoglioso?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante a una cena?', category: 'funny' },
    { text: 'Sei mai stato scoperto in una bugia dalla tua famiglia?', category: 'risky' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto da solo?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno del tuo passato?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di essere giudicato dalla famiglia?', category: 'general' },
    { text: 'Hai mai finto di essere cool quando eri nervoso?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto in un bar?', category: 'funny' },
    { text: 'Sei mai stato quello che è stato rifiutato?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri triste?', category: 'general' },
    { text: 'Hai mai avuto un segreto che hai scritto da qualche parte?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante su un aereo?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in una strana abitudine?', category: 'funny' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto con degli amici?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno con cui litigavi?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di essere vulnerabile con gli amici?', category: 'general' },
    { text: 'Hai mai finto di essere coraggioso quando avevi paura?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto in un centro commerciale?', category: 'funny' },
    { text: 'Sei mai stato quello che ha dovuto perdonare?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri felice?', category: 'general' },
    { text: 'Hai mai avuto un segreto che hai quasi detto?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante durante un\'escursione?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in un momento di onestà?', category: 'general' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto di notte?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno che ammiri?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di fare troppo?', category: 'general' },
    { text: 'Hai mai finto di essere rilassato quando stavi andando nel panico?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto in piscina?', category: 'funny' },
    { text: 'Sei mai stato quello che ha dovuto scusarsi per primo?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri arrabbiato con qualcuno?', category: 'risky' },
    { text: 'Hai mai avuto un segreto che nascondi alla tua famiglia?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante in un viaggio al mare?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in un momento divertente?', category: 'funny' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto la mattina?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno che ti metteva in imbarazzo?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di non essere abbastanza?', category: 'general' },
    { text: 'Hai mai finto di sapere qualcosa che non sapevi?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto in palestra?', category: 'funny' },
    { text: 'Sei mai stato quello che ha dovuto lasciar andare?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri in imbarazzo?', category: 'general' },
    { text: 'Hai mai avuto un segreto che dici solo a una persona?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante in un road trip?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in un momento di pigrizia?', category: 'funny' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto per rilassarti?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno che ti faceva sorridere?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di fare troppo poco?', category: 'general' },
    { text: 'Hai mai finto di essere sorpreso quando non lo eri?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto in un parco?', category: 'funny' },
    { text: 'Sei mai stato quello che ha dovuto andare avanti?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri confuso?', category: 'general' },
    { text: 'Hai mai avuto un segreto di cui hai paura di parlare?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante in campeggio?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in un momento strano?', category: 'funny' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto per tirarti su di morale?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno che ti faceva ridere?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di essere noioso?', category: 'general' },
    { text: 'Hai mai finto di essere occupato per evitare una conversazione?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto in un museo?', category: 'funny' },
    { text: 'Sei mai stato quello che ha dovuto dire addio?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri impaziente?', category: 'general' },
    { text: 'Hai mai avuto un segreto che hai scritto in un diario?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante su una barca?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in un momento di felicità?', category: 'funny' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto per procrastinare?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno che era gentile con te?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di essere fastidioso?', category: 'general' },
    { text: 'Hai mai finto di ascoltare quando non lo facevi?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto allo zoo?', category: 'funny' },
    { text: 'Sei mai stato quello che ha dovuto ricominciare da capo?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri geloso di un amico?', category: 'risky' },
    { text: 'Hai mai avuto un segreto che hai digitato ma mai inviato?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante a un festival?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in un momento di tristezza?', category: 'general' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto per impressionare qualcuno?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno di divertente?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di essere troppo silenzioso?', category: 'general' },
    { text: 'Hai mai finto di dormire per origliare una conversazione?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto a teatro?', category: 'funny' },
    { text: 'Sei mai stato quello che ha dovuto fare ammenda?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri di cattivo umore?', category: 'general' },
    { text: 'Hai mai avuto un segreto che hai sussurrato a qualcuno?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante a un picnic?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in un momento romantico?', category: 'funny' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto per evitare il lavoro?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno di intelligente?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di essere troppo rumoroso?', category: 'general' },
    { text: 'Hai mai finto di essere malato per evitare un appuntamento?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto in biblioteca?', category: 'funny' },
    { text: 'Sei mai stato quello che ha dovuto dire la verità?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri geloso di un fratello?', category: 'risky' },
    { text: 'Hai mai avuto un segreto di cui sei contento di aver tenuto?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante a un barbecue?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in un momento di nervosismo?', category: 'funny' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto per integrarti?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno di creativo?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di essere troppo serio?', category: 'general' },
    { text: 'Hai mai finto di essere sveglio quando eri mezzo addormentato?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto in una sala da bowling?', category: 'funny' },
    { text: 'Sei mai stato quello che ha dovuto assumersi la responsabilità?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri geloso di un collega?', category: 'risky' },
    { text: 'Hai mai avuto un segreto di cui temi che possa venire fuori?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante durante una serata karaoke?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in un momento di entusiasmo?', category: 'funny' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto per festeggiare?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno di talentuoso?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di essere troppo sciocco?', category: 'general' },
    { text: 'Hai mai finto di essere offeso quando non lo eri?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto in una sala da bowling?', category: 'funny' },
    { text: 'Sei mai stato quello che ha difeso qualcuno?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri geloso di un ex?', category: 'risky' },
    { text: 'Hai mai avuto un segreto a cui pensi spesso?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante durante una serata giochi?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in un momento di riflessione?', category: 'general' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto per sorprendere qualcuno?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno di misterioso?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di essere troppo onesto?', category: 'general' },
    { text: 'Hai mai finto di essere arrabbiato quando non lo eri?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto in un casinò?', category: 'funny' },
    { text: 'Sei mai stato quello che ha dovuto tenere un segreto per qualcuno?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri geloso di uno sconosciuto?', category: 'risky' },
    { text: 'Hai mai avuto un segreto che vuoi dire ma non puoi?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante a una cena tra amici?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in un momento di nostalgia?', category: 'general' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto per aiutare qualcuno?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno di avventuroso?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di essere troppo dipendente?', category: 'general' },
    { text: 'Hai mai finto di essere triste quando non lo eri?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto al ricevimento di un matrimonio?', category: 'funny' },
    { text: 'Sei mai stato quello che ha dovuto dare una brutta notizia?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri geloso di una celebrità?', category: 'funny' },
    { text: 'Hai mai avuto un segreto che hai condiviso troppo presto?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante a un baby shower?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in un momento di speranza?', category: 'general' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto per vendicarti?', category: 'risky' },
    { text: 'Hai mai avuto una cotta per qualcuno di calmo?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di essere troppo indipendente?', category: 'general' },
    { text: 'Hai mai finto di essere entusiasta quando non lo eri?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto a un baby shower?', category: 'funny' },
    { text: 'Sei mai stato quello che ha dovuto confortare qualcuno?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri geloso di un vicino?', category: 'risky' },
    { text: 'Hai mai avuto un segreto che ti penti di non aver detto?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante a una cerimonia di laurea?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in un momento di pace?', category: 'general' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto per attirare attenzione?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno di appassionato?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di essere troppo emotivo?', category: 'general' },
    { text: 'Hai mai finto di essere geloso quando non lo eri?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto a una festa di laurea?', category: 'funny' },
    { text: 'Sei mai stato quello che ha dovuto dare consigli?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri geloso di un parente?', category: 'risky' },
    { text: 'Hai mai avuto un segreto che hai detto in un sogno?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante a una festa in casa?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in una litigata ridicola con te stesso?', category: 'funny' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto per vincere una scommessa?', category: 'challenge' },
    { text: 'Hai mai avuto una cotta per qualcuno di timido?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di essere troppo logico?', category: 'general' },
    { text: 'Hai mai finto di essere calmo quando stavi andando nel panico?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto a un inaugurazione di casa?', category: 'funny' },
    { text: 'Sei mai stato quello che ha dovuto fare da mediatore in una lite?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri geloso di un compagno di classe?', category: 'risky' },
    { text: 'Hai mai avuto un segreto che hai scritto in una lettera mai spedita?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante a una rimpatriata?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in un momento di coraggio?', category: 'general' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto per far ridere qualcuno?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno di estroverso?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di essere troppo sensibile?', category: 'general' },
    { text: 'Hai mai finto di essere indifferente quando ti importava?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto a una festa di pensionamento?', category: 'funny' },
    { text: 'Sei mai stato quello che ha dovuto scegliere da che parte stare?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri geloso di un compagno di squadra?', category: 'risky' },
    { text: 'Hai mai avuto un segreto che hai solo accennato senza mai dirlo?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante a una festa di fine anno?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in un momento di gentilezza?', category: 'general' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto per riprenderti da qualcuno?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno di testardo?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di essere troppo indulgente?', category: 'general' },
    { text: 'Hai mai finto di essere ferito quando non lo eri?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto a una festa in ufficio?', category: 'funny' },
    { text: 'Sei mai stato quello che ha dovuto dire una bugia pietosa?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri geloso di un coinquilino?', category: 'risky' },
    { text: 'Hai mai avuto un segreto che hai intenzione di dire un giorno?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante a una cena di compleanno?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in un momento di debolezza e poi di forza?', category: 'general' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto per ricordare qualcuno?', category: 'general' },
    { text: 'Hai mai avuto una cotta per qualcuno di diverso da te?', category: 'friendship' },
    { text: 'Qual è la tua più grande paura di fidarsi troppo?', category: 'general' },
    { text: 'Hai mai finto di essere paziente quando non lo eri?', category: 'funny' },
    { text: 'Qual è la cosa più imbarazzante che hai fatto a un evento di networking?', category: 'funny' },
    { text: 'Sei mai stato quello che ha dovuto mantenere la pace?', category: 'friendship' },
    { text: 'Qual è la cosa peggiore che hai fatto quando eri geloso del tuo migliore amico?', category: 'risky' },
    { text: 'Hai mai avuto un segreto per il quale stai aspettando il momento giusto?', category: 'risky' },
    { text: 'Qual è il tuo momento più imbarazzante a un appuntamento al buio?', category: 'funny' },
    { text: 'Sei mai stato sorpreso in un momento di chiarezza?', category: 'general' },
    { text: 'Qual è la cosa più strana che tu abbia mai fatto per onorare qualcuno?', category: 'general' },
  ];
  
  const dares = [
    { text: 'Fai la tua migliore imitazione di qualcuno nella stanza.', category: 'funny' },
    { text: 'Canta il ritornello della tua canzone preferita ad alta voce.', category: 'funny' },
    { text: 'Balla per 30 secondi senza musica.', category: 'challenge' },
    { text: 'Parla con un accento per i prossimi 3 turni.', category: 'funny' },
    { text: 'Lascia che qualcun altro pubblichi una storia sui tuoi social media.', category: 'risky' },
    { text: 'Chiama un contatto e cantagli tanti auguri.', category: 'challenge' },
    { text: 'Fai 10 flessioni o squat.', category: 'challenge' },
    { text: 'Mangia un cucchiaio di un condimento scelto dal gruppo.', category: 'challenge' },
    { text: 'Lascia che il gruppo sfoglia la tua galleria foto per 1 minuto.', category: 'risky' },
    { text: 'Di\' qualcosa di carino a ogni persona nella stanza.', category: 'friendship' },
    { text: 'Fai una verticale o stai in equilibrio sulla testa per 10 secondi.', category: 'challenge' },
    { text: 'Parla solo con domande per i prossimi 2 turni.', category: 'funny' },
    { text: 'Lascia che qualcuno ti disegni sulla faccia con una penna.', category: 'funny' },
    { text: 'Scambia un capo di abbigliamento con la persona alla tua sinistra.', category: 'challenge' },
    { text: 'Fai la tua migliore imitazione di un animale e mantienila per 1 minuto.', category: 'funny' },
    { text: 'Manda un messaggio vocale al tuo crush o al tuo ex (il gruppo sceglie il testo).', category: 'risky' },
    { text: 'Tieni un libro in equilibrio sulla testa per 2 minuti.', category: 'challenge' },
    { text: 'Lascia che il gruppo ti acconci i capelli come vuole.', category: 'funny' },
    { text: 'Leggi in modo drammatico l\'ultimo messaggio che hai inviato.', category: 'funny' },
    { text: 'Tieni il plank per 1 minuto.', category: 'challenge' },
    { text: 'Parla in rima per i prossimi 2 turni.', category: 'funny' },
    { text: 'Lascia che qualcuno ti faccia il solletico per 30 secondi senza ridere.', category: 'challenge' },
    { text: 'Fai una sfilata con i vestiti al contrario.', category: 'funny' },
    { text: 'Chiama un familiare e digli che gli vuoi bene.', category: 'friendship' },
    { text: 'Mangia qualcosa senza usare le mani.', category: 'challenge' },
    { text: 'Lascia che il gruppo scelga un\'emoji; reagisci così per 2 turni.', category: 'funny' },
    { text: 'Fai la tua migliore imitazione di una celebrità.', category: 'funny' },
    { text: 'Recita l\'alfabeto al contrario in meno di 30 secondi.', category: 'challenge' },
    { text: 'Lascia che qualcun altro controlli il tuo telefono per i prossimi 5 minuti.', category: 'risky' },
    { text: 'Fai una danza TikTok o virale davanti a tutti.', category: 'funny' },
    { text: 'Parla con la voce di un bambino per i prossimi 3 turni.', category: 'funny' },
    { text: 'Fai un discorso motivazionale di 1 minuto per il gruppo.', category: 'challenge' },
    { text: 'Lascia che il gruppo scelga la tua foto profilo per 24 ore.', category: 'risky' },
    { text: 'Fai 20 jumping jack.', category: 'challenge' },
    { text: 'Manda un messaggio all\'ultima persona con cui hai parlato dicendo "Mi manchi".', category: 'risky' },
    { text: 'Imita una gallina fino al tuo prossimo turno.', category: 'funny' },
    { text: 'Lascia che qualcuno ti imbocchi bendato.', category: 'challenge' },
    { text: 'Leggi ad alta voce gli ultimi 3 messaggi che hai ricevuto.', category: 'risky' },
    { text: 'Fai l\'imitazione della persona alla tua destra.', category: 'funny' },
    { text: 'Lascia che il gruppo scelga una canzone; devi cantare il primo verso.', category: 'challenge' },
    { text: 'Fai 15 squat mantenendo il contatto visivo con tutti.', category: 'challenge' },
    { text: 'Lascia che qualcuno ti pettini come vuole per il resto del gioco.', category: 'funny' },
    { text: 'Parla con un accento da pirata per i prossimi 3 turni.', category: 'funny' },
    { text: 'Fai la tua migliore imitazione di una celebrità e lascia indovinare al gruppo.', category: 'funny' },
    { text: 'Lascia che la persona alla tua destra sfoglia la tua galleria per 30 secondi.', category: 'risky' },
    { text: 'Manda un messaggio flirty all\'ultima persona nei tuoi contatti (il gruppo lo scrive).', category: 'risky' },
    { text: 'Fai una sfilata su una passerella immaginaria con posa finale.', category: 'funny' },
    { text: 'Mangia qualcosa con gli occhi chiusi mentre qualcuno te lo porge.', category: 'challenge' },
    { text: 'Lascia che il gruppo ti dia un nuovo soprannome per il resto della serata.', category: 'funny' },
    { text: 'Fai 10 burpee.', category: 'challenge' },
    { text: 'Leggi ad alta voce la tua ultima ricerca.', category: 'risky' },
    { text: 'Imita un cane per 1 minuto.', category: 'funny' },
    { text: 'Lascia che qualcuno ti metta del ghiaccio sulla schiena.', category: 'challenge' },
    { text: 'Fai un monologo drammatico come se fossi in una telenovela.', category: 'funny' },
    { text: 'Parla con un accento inglese (o altro) fino al tuo prossimo turno.', category: 'funny' },
    { text: 'Lascia che il gruppo scelga un outfit dal tuo armadio; lo indossi per 10 minuti.', category: 'challenge' },
    { text: 'Fai la verticale contro il muro per 15 secondi.', category: 'challenge' },
    { text: 'Chiama un amico e di\' "Ho qualcosa di importante da dirti" poi riattacca.', category: 'risky' },
    { text: 'Lascia che qualcuno ti disegni i baffi sulla faccia con una penna.', category: 'funny' },
    { text: 'Fai l\'imitazione della persona alla tua sinistra.', category: 'funny' },
    { text: 'Mangia un cucchiaio di salsa piccante o un limone.', category: 'challenge' },
    { text: 'Lascia che il gruppo legga i tuoi ultimi 5 messaggi (puoi nascondere i nomi).', category: 'risky' },
    { text: 'Fai la ruota o almeno provaci.', category: 'challenge' },
    { text: 'Canta "Tanti Auguri" a te stesso in modo drammatico.', category: 'funny' },
    { text: 'Lascia che qualcuno ti faccia il solletico per 20 secondi senza muoverti.', category: 'challenge' },
    { text: 'Fai uno spot pubblicitario per un prodotto immaginario.', category: 'funny' },
    { text: 'Parla solo con testi di canzoni per i prossimi 2 turni.', category: 'funny' },
    { text: 'Lascia che il gruppo scelga cosa pubblichi nella tua storia.', category: 'risky' },
    { text: 'Fai 20 addominali.', category: 'challenge' },
    { text: 'Imita un gatto per 1 minuto (miagola, leccati le zampe, ecc.).', category: 'funny' },
    { text: 'Lascia che qualcun altro scriva un messaggio e tu lo invii alla persona che sceglie.', category: 'risky' },
    { text: 'Fai una riproduzione al rallentatore di te stesso che segna un gol.', category: 'funny' },
    { text: 'Mangia un pezzo di pane senza usare le mani.', category: 'challenge' },
    { text: 'Lascia che il gruppo guardi le tue emoji più usate e indovini a chi scrivi di più.', category: 'risky' },
    { text: 'Fai la tua migliore esibizione operistica per 30 secondi.', category: 'funny' },
    { text: 'Parla con una voce da robot per i prossimi 2 turni.', category: 'funny' },
    { text: 'Lascia che qualcuno ti bendi e ti faccia girare 5 volte; poi prova a camminare in linea retta.', category: 'challenge' },
    { text: 'Esegui un trend TikTok (recente o vecchio) davanti a tutti.', category: 'funny' },
    { text: 'Chiama una pizzeria e chiedi una "pizza sorpresa" (senza ordinare davvero).', category: 'funny' },
    { text: 'Lascia che la persona alla tua sinistra scelga i tuoi prossimi 3 post sui social.', category: 'risky' },
    { text: 'Fai un gioco di fiducia cadendo tra le braccia del gruppo.', category: 'challenge' },
    { text: 'Imita qualcuno in un film muto per 1 minuto.', category: 'funny' },
    { text: 'Lascia che qualcuno ti dia da mangiare 3 cibi diversi bendato; indovina cosa sono.', category: 'challenge' },
    { text: 'Fai la tua migliore imitazione di un professore o di un capo.', category: 'funny' },
    { text: 'Parla in rima per i prossimi 3 turni.', category: 'funny' },
    { text: 'Lascia che il gruppo scelga una canzone; balla per 1 minuto.', category: 'challenge' },
    { text: 'Fai 30 secondi di stand-up comedy su te stesso.', category: 'funny' },
    { text: 'Chiama un familiare e digli che gli vuoi bene nel modo più drammatico possibile.', category: 'friendship' },
    { text: 'Lascia che qualcuno sfoglia la tua app note per 30 secondi.', category: 'risky' },
    { text: 'Fai una lettura drammatica di un articolo casuale di Wikipedia.', category: 'funny' },
    { text: 'Imita un anchorman che riporta notizie sul gioco in corso.', category: 'funny' },
    { text: 'Lascia che il gruppo ti scelga una nuova foto profilo per 24 ore.', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di un commentatore sportivo.', category: 'funny' },
    { text: 'Parla come un personaggio di Shakespeare per i prossimi 2 turni.', category: 'funny' },
    { text: 'Lascia che qualcuno scelga cosa mangi al tuo prossimo pasto.', category: 'challenge' },
    { text: 'Fai un commento in stile "get ready with me" mentre ti aggiusti i capelli.', category: 'funny' },
    { text: 'Chiama un contatto a caso e di\' "Volevo solo sentire la tua voce" poi riattacca.', category: 'risky' },
    { text: 'Lascia che il gruppo guardi una tua playlist e la critichi.', category: 'funny' },
    { text: 'Fai un trucco di magia (vero o falso) per il gruppo.', category: 'funny' },
    { text: 'Imita un istruttore di fitness e guida un "allenamento" di 1 minuto.', category: 'funny' },
    { text: 'Lascia che qualcuno scriva una didascalia per il tuo prossimo post.', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di un politico che fa un discorso.', category: 'funny' },
    { text: 'Parla solo con domande per i prossimi 3 turni.', category: 'funny' },
    { text: 'Lascia che la persona alla tua destra scelga la tua suoneria per una settimana.', category: 'challenge' },
    { text: 'Fai una rievocazione drammatica dell\'ultima volta che ti sei fatto male a un dito del piede.', category: 'funny' },
    { text: 'Fai un complimento poetico a ogni persona nella stanza.', category: 'friendship' },
    { text: 'Lascia che il gruppo scelga una vecchia foto di te; devi pubblicarla come storia.', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di un presentatore meteorologico.', category: 'funny' },
    { text: 'Imita uno spot pubblicitario per la stanza in cui ti trovi.', category: 'funny' },
    { text: 'Lascia che qualcuno legga la tua ultima conversazione in DM (con nomi nascosti se necessario).', category: 'risky' },
    { text: 'Fai 10 affondi dicendo qualcosa di gentile a ogni persona.', category: 'challenge' },
    { text: 'Parla sottovoce per i prossimi 2 turni.', category: 'funny' },
    { text: 'Lascia che il gruppo scelga cosa bevi dopo.', category: 'challenge' },
    { text: 'Fai un\'interpretazione drammatica di "Devo andare in bagno".', category: 'funny' },
    { text: 'Chiama un amico e canta i primi 30 secondi di una canzone che sceglie lui.', category: 'challenge' },
    { text: 'Lascia che qualcuno ti disegni sul braccio con una penna (lavabile).', category: 'funny' },
    { text: 'Fai la tua migliore imitazione di un conduttore di giochi televisivi.', category: 'funny' },
    { text: 'Imita una guida turistica che fa visitare la stanza a tutti.', category: 'funny' },
    { text: 'Lascia che il gruppo decida una cosa che devi fare domani.', category: 'challenge' },
    { text: 'Fai un commento vocale "giornata tipo" sull\'ultima ora.', category: 'funny' },
    { text: 'Fai un discorso incoraggiante di 30 secondi alla persona alla tua sinistra.', category: 'friendship' },
    { text: 'Lascia che qualcuno scelga un outfit dal tuo armadio; lo indossi per la prossima ora.', category: 'challenge' },
    { text: 'Fai la tua migliore imitazione di uno chef che presenta un piatto.', category: 'funny' },
    { text: 'Parla come se fossi in un film horror per i prossimi 2 turni.', category: 'funny' },
    { text: 'Lascia che il gruppo scelga un filtro; fai un selfie e pubblicalo.', category: 'risky' },
    { text: 'Fai una lettura drammatica di un messaggio che hai ricevuto oggi.', category: 'funny' },
    { text: 'Imita un commentatore per il prossimo turno del gioco.', category: 'funny' },
    { text: 'Fai 25 jumping jack cantando una filastrocca.', category: 'challenge' },
    { text: 'Lascia che il gruppo scelga una parola; usala in ogni frase per 3 turni.', category: 'funny' },
    { text: 'Manda un messaggio vocale a un contatto dicendogli che stai pensando a lui.', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di un cattivo di un film.', category: 'funny' },
    { text: 'Dai un massaggio alle spalle di 30 secondi alla persona alla tua sinistra.', category: 'friendship' },
    { text: 'Mangia un cracker e prova subito dopo a fischiare.', category: 'challenge' },
    { text: 'Lascia che qualcuno pubblichi uno stato al posto tuo (sceglie il testo).', category: 'risky' },
    { text: 'Parla come un poeta per i prossimi 2 turni.', category: 'funny' },
    { text: 'Fai 15 mountain climber.', category: 'challenge' },
    { text: 'Manda un messaggio a tua mamma o papà con "Ti voglio bene" e un cuore.', category: 'friendship' },
    { text: 'Imita un detective e "investiga" nella stanza per 1 minuto.', category: 'funny' },
    { text: 'Lascia che il gruppo veda le tue ultime 10 foto (senza saltare).', category: 'risky' },
    { text: 'Fai una lettura drammatica di un menù di consegna.', category: 'funny' },
    { text: 'Trattieni il respiro per 30 secondi poi di\' uno scioglilingua.', category: 'challenge' },
    { text: 'Fai un complimento originale alla persona alla tua destra.', category: 'friendship' },
    { text: 'Parla con un accento del Sud Italia per i prossimi 3 turni.', category: 'funny' },
    { text: 'Fai 20 ginocchia alte sul posto.', category: 'challenge' },
    { text: 'Chiama un amico e di\' "Indovina un po\'?" poi di\' qualcosa di stupido.', category: 'funny' },
    { text: 'Lascia che qualcuno scorra i tuoi seguiti su Instagram per 30 secondi.', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di un supereroe.', category: 'funny' },
    { text: 'Di\' tre cose che ammiri di ogni persona nella stanza.', category: 'friendship' },
    { text: 'Mangia uno spicchio di limone senza fare smorfie.', category: 'challenge' },
    { text: 'Leggi ad alta voce l\'oggetto dell\'ultima email inviata.', category: 'risky' },
    { text: 'Imita un assistente di volo e dai le istruzioni di sicurezza per la stanza.', category: 'funny' },
    { text: 'Fai 10 dip alle parallele usando una sedia o il divano.', category: 'challenge' },
    { text: 'Manda un messaggio di complimento a un amico.', category: 'friendship' },
    { text: 'Parla con un accento francese esagerato per i prossimi 2 turni.', category: 'funny' },
    { text: 'Lascia che il gruppo scelga il tuo prossimo spuntino.', category: 'challenge' },
    { text: 'Fai una rievocazione drammatica di te stesso che inciampa.', category: 'funny' },
    { text: 'Manda un meme all\'ultima persona a cui hai scritto (il gruppo sceglie il meme).', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di un oratore motivazionale.', category: 'funny' },
    { text: 'Abbraccia tutti nella stanza dicendo una cosa gentile a ciascuno.', category: 'friendship' },
    { text: 'Tieniti in equilibrio su una gamba per 1 minuto mentre racconti una storia.', category: 'challenge' },
    { text: 'Leggi ad alta voce il primo messaggio nella tua casella di posta (il gruppo decide se rispondere).', category: 'risky' },
    { text: 'Imita un concorrente di un gioco televisivo per il prossimo turno.', category: 'funny' },
    { text: 'Fai 15 calci indietro.', category: 'challenge' },
    { text: 'Chiama un familiare e raccontagli una barzelletta.', category: 'friendship' },
    { text: 'Parla solo con citazioni di film per i prossimi 2 turni.', category: 'funny' },
    { text: 'Lascia che qualcuno scelga una canzone imbarazzante; la ascolti per 30 secondi senza reagire.', category: 'challenge' },
    { text: 'Fai una pubblicità per il prodotto peggiore che riesci a immaginare.', category: 'funny' },
    { text: 'Pubblica una storia con una didascalia scritta dal gruppo.', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di un cuoco in un programma di cucina.', category: 'funny' },
    { text: 'Di\' alla persona alla tua sinistra perché sei contento che sia tuo amico.', category: 'friendship' },
    { text: 'Fai 20 secondi di sedia contro il muro.', category: 'challenge' },
    { text: 'Lascia che il gruppo veda il tempo di utilizzo del tuo schermo di oggi.', category: 'risky' },
    { text: 'Imita qualcuno che consegna un premio a una persona nella stanza.', category: 'funny' },
    { text: 'Mangia un cucchiaio di burro di arachidi e prova a dire un scioglilingua 5 volte.', category: 'challenge' },
    { text: 'Manda un messaggio a qualcuno con "Dobbiamo parlare" e poi subito "Di pizza."', category: 'funny' },
    { text: 'Fai la tua migliore imitazione di un giornalista che dà una brutta notizia.', category: 'funny' },
    { text: 'Di\' qualcosa che non hai mai detto ad alta voce alla persona alla tua destra.', category: 'friendship' },
    { text: 'Fai 10 squat jump.', category: 'challenge' },
    { text: 'Lascia che il gruppo veda le tue ricerche recenti (solo una persona).', category: 'risky' },
    { text: 'Parla con un accento italiano esagerato per i prossimi 2 turni.', category: 'funny' },
    { text: 'Fai un\'interpretazione drammatica di ricevere una brutta notizia.', category: 'funny' },
    { text: 'Manda un messaggio vocale a un amico dicendogli che lo apprezzi.', category: 'friendship' },
    { text: 'Tieni una posa yoga per 45 secondi.', category: 'challenge' },
    { text: 'Leggi ad alta voce la tua ultima didascalia Instagram.', category: 'risky' },
    { text: 'Imita una guida museale che descrive la stanza.', category: 'funny' },
    { text: 'Fai 15 jumping jack al contrario.', category: 'challenge' },
    { text: 'Lascia che il gruppo scelga un filtro; fai un selfie e mettilo come sfondo per 1 ora.', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di un genitore deluso.', category: 'funny' },
    { text: 'Di\' a tutti una cosa che hai imparato dalla persona alla tua sinistra.', category: 'friendship' },
    { text: 'Mangia una caramella e descrivi il sapore in estremo dettaglio.', category: 'funny' },
    { text: 'Fai 20 secondi di plank.', category: 'challenge' },
    { text: 'Manda un messaggio a un contatto con "Sei fantastico/a" senza contesto.', category: 'friendship' },
    { text: 'Parla come un robot per i prossimi 3 turni.', category: 'funny' },
    { text: 'Lascia che qualcuno scelga la tua prossima storia Instagram.', category: 'risky' },
    { text: 'Fai una lettura drammatica di un messaggio ricevuto questa settimana.', category: 'funny' },
    { text: 'Fai 10 affondi su ogni gamba.', category: 'challenge' },
    { text: 'Chiama un amico e canta un verso di una canzone che sceglie lui.', category: 'challenge' },
    { text: 'Imita un commentatore sportivo per qualcuno che attraversa la stanza.', category: 'funny' },
    { text: 'Lascia che il gruppo scelga un vecchio stato; lo pubblichi di nuovo.', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di una persona famosa (il gruppo indovina).', category: 'funny' },
    { text: 'Di\' una cosa che faresti per ogni persona se avesse bisogno di aiuto.', category: 'friendship' },
    { text: 'Fai 15 burpee (la versione modificata va bene).', category: 'challenge' },
    { text: 'Leggi ad alta voce l\'ultimo elemento che hai copiato negli appunti.', category: 'risky' },
    { text: 'Parla con un accento tedesco per i prossimi 2 turni.', category: 'funny' },
    { text: 'Fai una danza di 30 secondi su una canzone scelta dal gruppo.', category: 'challenge' },
    { text: 'Manda al tuo migliore amico una barzelletta interna che solo voi capite.', category: 'friendship' },
    { text: 'Imita un bibliotecario e fa\' "shh" a tutti per 30 secondi.', category: 'funny' },
    { text: 'Lascia che il gruppo veda le tue 5 app più usate.', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di qualcuno che ha appena avuto uno spavento in un film horror.', category: 'funny' },
    { text: 'Fai un brindisi al gruppo come a un matrimonio.', category: 'friendship' },
    { text: 'Fai 20 crunch.', category: 'challenge' },
    { text: 'Manda un messaggio a qualcuno con "Ti ricordi di quella cosa?" (senza spiegare).', category: 'funny' },
    { text: 'Parla solo con descrizioni di emoji per il prossimo turno.', category: 'funny' },
    { text: 'Lascia che qualcuno scelga il tuo prossimo stato su WhatsApp o Messenger.', category: 'risky' },
    { text: 'Fai una rievocazione drammatica di vincere alla lotteria.', category: 'funny' },
    { text: 'Fai 30 secondi di corsa sul posto con le ginocchia alte.', category: 'challenge' },
    { text: 'Di\' alla persona alla tua destra un ricordo che hai con lei.', category: 'friendship' },
    { text: 'Imita un arbitro e "fischiad un fallo" a qualcuno nella stanza.', category: 'funny' },
    { text: 'Leggi ad alta voce la tua ultima ricerca su Google.', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di un complottista.', category: 'funny' },
    { text: 'Di\' "Ti apprezzo" a ogni persona nella stanza guardandola negli occhi.', category: 'friendship' },
    { text: 'Mangia qualcosa di acido e mantieni un\'espressione neutra per 10 secondi.', category: 'challenge' },
    { text: 'Lascia che il gruppo scriva un tweet per te; lo pubblichi.', category: 'risky' },
    { text: 'Parla con un accento spagnolo per i prossimi 2 turni.', category: 'funny' },
    { text: 'Fai 15 flessioni (quelle sulle ginocchia contano).', category: 'challenge' },
    { text: 'Chiama un amico e di\' "Stavo pensando a te" poi chatta per 1 minuto.', category: 'friendship' },
    { text: 'Fai una lettura drammatica di una notifica ricevuta oggi.', category: 'funny' },
    { text: 'Lascia che qualcuno sfoglia i tuoi ascolti recenti su Spotify o Apple Music.', category: 'risky' },
    { text: 'Imita un terapeuta e offri una "seduta" al gruppo per 1 minuto.', category: 'funny' },
    { text: 'Fai 20 sollevamenti di gambe.', category: 'challenge' },
    { text: 'Manda un fatto che hai imparato oggi a un familiare.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di una star di reality show.', category: 'funny' },
    { text: 'Lascia che il gruppo scelga una foto dalla tua galleria da pubblicare come storia.', category: 'risky' },
    { text: 'Parla con un accento scozzese per i prossimi 2 turni.', category: 'funny' },
    { text: 'Fai 10 squat sumo.', category: 'challenge' },
    { text: 'Da\' a tutti un soprannome basato sulla loro personalità e usalo per 2 turni.', category: 'funny' },
    { text: 'Leggi ad alta voce l\'ultima cosa che hai messo "mi piace" sui social.', category: 'risky' },
    { text: 'Fai un\'interpretazione drammatica di scoprire di avere un ammiratore segreto.', category: 'funny' },
    { text: 'Di\' al gruppo in che modo ogni persona ti ha aiutato.', category: 'friendship' },
    { text: 'Fai 30 secondi di ballo come se nessuno guardasse.', category: 'challenge' },
    { text: 'Manda un messaggio vocale a un amico con una barzelletta pessima.', category: 'funny' },
    { text: 'Lascia che il gruppo scelga la tua prossima foto profilo per 48 ore.', category: 'risky' },
    { text: 'Imita un giudice e assegna "pene" per crimini ridicoli a tutti.', category: 'funny' },
    { text: 'Fai 15 sollevamenti di gambe.', category: 'challenge' },
    { text: 'Di\' una cosa per cui sei grato per ogni persona.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di uno YouTuber che fa l\'intro.', category: 'funny' },
    { text: 'Lascia che qualcuno invii un messaggio dal tuo telefono a un contatto che sceglie (tu approvi il testo).', category: 'risky' },
    { text: 'Parla con un accento australiano per i prossimi 2 turni.', category: 'funny' },
    { text: 'Fai 20 cerchi con le braccia in ogni direzione.', category: 'challenge' },
    { text: 'Chiama un amico e fai la tua migliore imitazione di lui (deve indovinare).', category: 'funny' },
    { text: 'Leggi ad alta voce l\'ultimo messaggio inviato al tuo migliore amico.', category: 'risky' },
    { text: 'Fai una rievocazione drammatica della tua routine mattutina in 30 secondi.', category: 'funny' },
    { text: 'Fai un complimento genuino alla persona alla tua sinistra che non ha mai sentito.', category: 'friendship' },
    { text: 'Fai 10 inchworm.', category: 'challenge' },
    { text: 'Lascia che il gruppo scelga una canzone; fai il playback dei primi 30 secondi.', category: 'funny' },
    { text: 'Imita un conduttore di un programma di dating e presenta tutti come concorrenti.', category: 'funny' },
    { text: 'Pubblica una storia con un sondaggio; il gruppo sceglie la domanda e le opzioni.', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di un insegnante che fa lezione.', category: 'funny' },
    { text: 'Di\' "Sei importante per me" a ogni persona nella stanza.', category: 'friendship' },
    { text: 'Fai 15 salti laterali.', category: 'challenge' },
    { text: 'Manda a qualcuno "Ho bisogno del tuo parere su una cosa" poi manda una domanda stupida.', category: 'funny' },
    { text: 'Lascia che qualcuno guardi la tua lista di chiamate recenti.', category: 'risky' },
    { text: 'Parla con un accento newyorkese per i prossimi 2 turni.', category: 'funny' },
    { text: 'Fai un "Ted Talk" di 1 minuto su un argomento scelto dal gruppo.', category: 'challenge' },
    { text: 'Di\' a tutti una cosa che ammiri della persona alla tua destra.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di un conduttore di televendita.', category: 'funny' },
    { text: 'Lascia che il gruppo scelga una didascalia per il tuo prossimo post.', category: 'risky' },
    { text: 'Fai 20 heel tap.', category: 'challenge' },
    { text: 'Chiama un amico e digli una cosa che ami di lui.', category: 'friendship' },
    { text: 'Imita un banditore d\'aste e "vendi" un oggetto nella stanza.', category: 'funny' },
    { text: 'Leggi ad alta voce l\'ultimo meme che hai inviato.', category: 'risky' },
    { text: 'Fai una lettura drammatica di una pubblicità vista oggi.', category: 'funny' },
    { text: 'Fai 10 salti in alto.', category: 'challenge' },
    { text: 'Lascia che il gruppo scelga una parola; non puoi dirla per i prossimi 3 turni.', category: 'challenge' },
    { text: 'Di\' un modo in cui ogni persona ti ha fatto sorridere.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di un conduttore di podcast.', category: 'funny' },
    { text: 'Manda un messaggio a un contatto con "Dovremmo vederci presto" (il gruppo sceglie chi).', category: 'risky' },
    { text: 'Parla con un accento russo per i prossimi 2 turni.', category: 'funny' },
    { text: 'Fai 15 affondi laterali per lato.', category: 'challenge' },
    { text: 'Fai un "discorso di laurea" per il gruppo in 30 secondi.', category: 'funny' },
    { text: 'Lascia che qualcuno scorra i tuoi like su TikTok o Reels per 20 secondi.', category: 'risky' },
    { text: 'Imita un cameriere e prendi l\'ordine di tutti su un menu immaginario.', category: 'funny' },
    { text: 'Fai 20 tocchi di spalle in posizione di plank.', category: 'challenge' },
    { text: 'Manda un messaggio a un amico "Sei una delle mie persone preferite" senza contesto.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di un cattivo che fa un monologo.', category: 'funny' },
    { text: 'Leggi ad alta voce il tuo ultimo tweet o post.', category: 'risky' },
    { text: 'Fai un\'interpretazione drammatica di ricevere una buona notizia.', category: 'funny' },
    { text: 'Di\' alla persona alla tua sinistra una cosa che hai sempre voluto dirle.', category: 'friendship' },
    { text: 'Fai 30 secondi di salto con la corda (immaginaria va bene).', category: 'challenge' },
    { text: 'Lascia che il gruppo scelga una canzone imbarazzante; ne canti il ritornello.', category: 'funny' },
    { text: 'Imita uno scienziato e "spiega" il gioco al gruppo.', category: 'funny' },
    { text: 'Pubblica una storia con una domanda scritta dal gruppo.', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di un atterraggio da supereroe.', category: 'funny' },
    { text: 'Di\' "Grazie per essere qui" a ogni persona.', category: 'friendship' },
    { text: 'Fai 10 affondi inversi su ogni gamba.', category: 'challenge' },
    { text: 'Chiama qualcuno e di\' "Sto giocando a un gioco e fai parte di esso" poi spiega.', category: 'funny' },
    { text: 'Lascia che il gruppo veda le statistiche di batteria e spazio di archiviazione.', category: 'risky' },
    { text: 'Parla con un accento giamaicano per i prossimi 2 turni.', category: 'funny' },
    { text: 'Fai 15 posizioni Superman (sdraiato sulla pancia, braccia e gambe sollevate).', category: 'challenge' },
    { text: 'Da\' a tutti un "premio" e presentalo in modo drammatico.', category: 'friendship' },
    { text: 'Fai una lettura drammatica delle previsioni del tempo per la stanza.', category: 'funny' },
    { text: 'Lascia che qualcuno scelga cosa cambi come stato.', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di una persona appena svegliata.', category: 'funny' },
    { text: 'Di\' al gruppo una cosa che non cambieresti mai di ogni persona.', category: 'friendship' },
    { text: 'Fai 20 flutter kick.', category: 'challenge' },
    { text: 'Manda un messaggio a un contatto "Sto pensando a te" con una emoji casuale.', category: 'friendship' },
    { text: 'Imita un allenatore che fa un discorso a metà partita al gruppo.', category: 'funny' },
    { text: 'Leggi ad alta voce l\'ultima cosa che hai salvato o aggiunto ai preferiti.', category: 'risky' },
    { text: 'Fai un monologo drammatico di 45 secondi su un panino.', category: 'funny' },
    { text: 'Fai 10 burpee con un applauso in cima.', category: 'challenge' },
    { text: 'Lascia che il gruppo scelga una frase; la dici con 5 accenti diversi.', category: 'funny' },
    { text: 'Di\' una cosa di cui sei orgoglioso per ogni persona.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena ricevuto una brutta notizia.', category: 'funny' },
    { text: 'Manda un messaggio vocale a un amico con una pessima imitazione di lui.', category: 'funny' },
    { text: 'Lascia che il gruppo veda il tuo calendario di questa settimana.', category: 'risky' },
    { text: 'Parla con un accento indiano per i prossimi 2 turni.', category: 'funny' },
    { text: 'Fai 15 ponti glutei.', category: 'challenge' },
    { text: 'Chiama un amico e di\' "Sei il/la migliore" poi continua o riattacca.', category: 'friendship' },
    { text: 'Imita un DJ e "metti il basso" per la stanza.', category: 'funny' },
    { text: 'Leggi ad alta voce il tuo ultimo promemoria o sveglia.', category: 'risky' },
    { text: 'Fai una rievocazione drammatica di far cadere il telefono.', category: 'funny' },
    { text: 'Fai 20 crunch bicicletta.', category: 'challenge' },
    { text: 'Di\' a tutti in che modo la persona alla tua destra ti ha influenzato.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di una persona sulle montagne russe.', category: 'funny' },
    { text: 'Lascia che il gruppo scelga un contatto; gli mandi un messaggio scritto dal gruppo.', category: 'risky' },
    { text: 'Parla con un accento bostoniano per i prossimi 2 turni.', category: 'funny' },
    { text: 'Fai 30 secondi di boxe con l\'ombra.', category: 'challenge' },
    { text: 'Fai un discorso in stile "Stato dell\'Unione" sul gioco.', category: 'funny' },
    { text: 'Pubblica una foto selezionata dal gruppo dalla tua galleria (senza volti se necessario).', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena ricevuto un\'ottima notizia.', category: 'funny' },
    { text: 'Di\' "Sono contento che tu sia nella mia vita" a ogni persona.', category: 'friendship' },
    { text: 'Fai 10 sprawl.', category: 'challenge' },
    { text: 'Manda un messaggio a qualcuno con "Domanda veloce" poi manda qualcosa di casuale.', category: 'funny' },
    { text: 'Lascia che qualcuno legga il tuo ultimo promemoria.', category: 'risky' },
    { text: 'Imita un conduttore di giochi televisivi e presenta il prossimo giocatore.', category: 'funny' },
    { text: 'Fai 15 sollevamenti di gambe (sdraiato).', category: 'challenge' },
    { text: 'Di\' alla persona alla tua sinistra cosa faresti se ti chiamasse alle 3 di notte.', category: 'friendship' },
    { text: 'Fai una lettura drammatica di una ricetta.', category: 'funny' },
    { text: 'Lascia che il gruppo scelga la tua prossima didascalia Instagram.', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena visto un fantasma.', category: 'funny' },
    { text: 'Di\' una cosa che faresti per migliorare la giornata di ogni persona.', category: 'friendship' },
    { text: 'Fai 20 squat tenuti.', category: 'challenge' },
    { text: 'Chiama un amico e fai un\'imitazione di una celebrità per 30 secondi.', category: 'funny' },
    { text: 'Leggi ad alta voce la tua ultima ricerca su YouTube o video.', category: 'risky' },
    { text: 'Parla con un accento del profondo Sud per i prossimi 2 turni.', category: 'funny' },
    { text: 'Fai 10 salti in scatola (sul pavimento o su una superficie bassa).', category: 'challenge' },
    { text: 'Da\' a ognuno un "superpotere" basato sulla sua personalità.', category: 'friendship' },
    { text: 'Fai un\'interpretazione drammatica di aprire un regalo che ami.', category: 'funny' },
    { text: 'Lascia che il gruppo scelga una canzone; la canticchi e loro indovinano.', category: 'funny' },
    { text: 'Imita un conduttore di talk show e "intervista" la persona alla tua destra.', category: 'funny' },
    { text: 'Manda un messaggio a un contatto con un complimento (il gruppo approva).', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena finito una maratona.', category: 'funny' },
    { text: 'Di\' una cosa che hai in comune con ogni persona.', category: 'friendship' },
    { text: 'Fai 15 sollevamenti di polpacci.', category: 'challenge' },
    { text: 'Lascia che qualcuno veda i tuoi ultimi 3 file scaricati.', category: 'risky' },
    { text: 'Fai un commento in stile "documentario" di 1 minuto sulla stanza.', category: 'funny' },
    { text: 'Fai 20 jumping jack mentre reciti l\'alfabeto.', category: 'challenge' },
    { text: 'Di\' al gruppo un ricordo che hai con ogni persona.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena perso le chiavi.', category: 'funny' },
    { text: 'Pubblica una storia con una domanda; il gruppo scrive la domanda.', category: 'risky' },
    { text: 'Parla con un accento canadese per i prossimi 2 turni.', category: 'funny' },
    { text: 'Fai 10 v-up o addominali.', category: 'challenge' },
    { text: 'Manda un messaggio a un familiare "Ti voglio bene" con un motivo specifico.', category: 'friendship' },
    { text: 'Imita un conduttore di reality show e narra il prossimo turno.', category: 'funny' },
    { text: 'Leggi ad alta voce l\'ultima cosa che hai condiviso sui social.', category: 'risky' },
    { text: 'Fai una rievocazione drammatica di colpirti l\'alluce.', category: 'funny' },
    { text: 'Fai 15 flessioni contro il muro.', category: 'challenge' },
    { text: 'Lascia che il gruppo ti assegni una "missione" da completare prima della fine del gioco.', category: 'challenge' },
    { text: 'Di\' "Fai la differenza" a ogni persona.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena ricevuto una promozione.', category: 'funny' },
    { text: 'Manda un messaggio vocale a un amico con un fatto casuale.', category: 'funny' },
    { text: 'Lascia che qualcuno scelga il tuo prossimo stato.', category: 'risky' },
    { text: 'Parla con un accento aristocratico inglese per i prossimi 2 turni.', category: 'funny' },
    { text: 'Fai 20 sollevamenti di braccia (davanti e di lato).', category: 'challenge' },
    { text: 'Fai un "elogio funebre" per un oggetto nella stanza (versione divertente).', category: 'funny' },
    { text: 'Di\' alla persona alla tua destra una cosa che hai sempre voluto fare con lei.', category: 'friendship' },
    { text: 'Fai una lettura drammatica della descrizione di un prodotto.', category: 'funny' },
    { text: 'Lascia che il gruppo veda il tuo ultimo screenshot.', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena preso una multa.', category: 'funny' },
    { text: 'Di\' una cosa che rispetti di ogni persona.', category: 'friendship' },
    { text: 'Fai 10 flessioni sulle ginocchia.', category: 'challenge' },
    { text: 'Chiama un amico e di\' "Sei incredibile" poi spiega perché (30 sec).', category: 'friendship' },
    { text: 'Imita uno chef in un programma di cucina con un piatto immaginario.', category: 'funny' },
    { text: 'Leggi ad alta voce (solo l\'oggetto) l\'ultima email che hai inviato.', category: 'risky' },
    { text: 'Fai un monologo drammatico di 30 secondi sui calzini.', category: 'funny' },
    { text: 'Fai 15 torsioni oblique in piedi.', category: 'challenge' },
    { text: 'Lascia che il gruppo ti scelga una sfida da completare nelle prossime 24 ore.', category: 'challenge' },
    { text: 'Di\' a tutti in che modo ogni persona ti ha fatto ridere.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena visto il suo crush.', category: 'funny' },
    { text: 'Manda una barzelletta stupida a un contatto (il gruppo può suggerirne una).', category: 'funny' },
    { text: 'Lascia che qualcuno guardi le tue app recenti.', category: 'risky' },
    { text: 'Parla con un accento da pirata per i prossimi 3 turni.', category: 'funny' },
    { text: 'Fai 20 step up (su un gradino o una superficie bassa).', category: 'challenge' },
    { text: 'Fai un "discorso agli Oscar" ringraziando tutti nella stanza.', category: 'friendship' },
    { text: 'Fai un\'interpretazione drammatica di trovare un ragno.', category: 'funny' },
    { text: 'Pubblica una storia con una canzone scelta dal gruppo.', category: 'risky' },
    { text: 'Imita un conduttore di podcast e intervista la persona alla tua sinistra.', category: 'funny' },
    { text: 'Fai 10 crunch inversi.', category: 'challenge' },
    { text: 'Di\' "Sono fortunato di conoscerti" a ogni persona.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena ricevuto un regalo.', category: 'funny' },
    { text: 'Leggi ad alta voce la tua ultima nota personale.', category: 'risky' },
    { text: 'Fai una lettura drammatica di un cartello o etichetta nella stanza.', category: 'funny' },
    { text: 'Fai 15 sollevamenti di fianchi.', category: 'challenge' },
    { text: 'Di\' alla persona alla tua sinistra una cosa che non dimenticherai mai di lei.', category: 'friendship' },
    { text: 'Lascia che il gruppo scelga una frase; la dici come in un trailer di un film.', category: 'funny' },
    { text: 'Manda un messaggio a qualcuno con "Hai illuminato la mia giornata" (anche se non è vero).', category: 'funny' },
    { text: 'Lascia che qualcuno scelga cosa pubblichi dopo (foto o testo).', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di una persona che si è appena svegliata da un pisolino.', category: 'funny' },
    { text: 'Di\' una cosa per cui ringrazieresti ogni persona.', category: 'friendship' },
    { text: 'Fai 20 cerchi di gambe (sdraiato).', category: 'challenge' },
    { text: 'Chiama un amico e fai un\'imitazione di un professore per 20 secondi.', category: 'funny' },
    { text: 'Leggi ad alta voce la tua ultima ricerca su Google.', category: 'risky' },
    { text: 'Parla con la voce di un cattivo per i prossimi 2 turni.', category: 'funny' },
    { text: 'Fai 10 bird dog (braccio e gamba opposti).', category: 'challenge' },
    { text: 'Da\' a tutti un "titolo" (es. "Ministro del divertimento") e usalo per 2 turni.', category: 'friendship' },
    { text: 'Fai una rievocazione drammatica di scivolare sul ghiaccio.', category: 'funny' },
    { text: 'Lascia che il gruppo scelga una domanda; la pubblichi come stato.', category: 'risky' },
    { text: 'Imita un conduttore di giochi televisivi e spiega il prossimo turno.', category: 'funny' },
    { text: 'Fai 15 dead bug.', category: 'challenge' },
    { text: 'Manda un messaggio a un amico "Ti sono grato/a" con un breve motivo.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena ricevuto un messaggio dal suo crush.', category: 'funny' },
    { text: 'Lascia che qualcuno veda le tue ultime 5 emoji usate.', category: 'risky' },
    { text: 'Fai un monologo drammatico di 45 secondi sul tempo atmosferico.', category: 'funny' },
    { text: 'Fai 20 ginocchia alte marciando sul posto.', category: 'challenge' },
    { text: 'Di\' al gruppo una cosa che faresti per tirare su il morale di ogni persona.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena vinto una partita.', category: 'funny' },
    { text: 'Pubblica una storia con una foto selezionata dal gruppo.', category: 'risky' },
    { text: 'Parla con una voce assonnata per i prossimi 2 turni.', category: 'funny' },
    { text: 'Fai 10 stiramenti gatto-mucca (yoga).', category: 'challenge' },
    { text: 'Di\' "Sei importante per me" a ogni persona.', category: 'friendship' },
    { text: 'Imita un conduttore di una cerimonia di premiazione e assegna un premio alla stanza.', category: 'funny' },
    { text: 'Leggi ad alta voce la tua ultima playlist o album ascoltato.', category: 'risky' },
    { text: 'Fai un\'interpretazione drammatica di una festa a sorpresa.', category: 'funny' },
    { text: 'Fai 15 estensioni di gambe in piedi (calci indietro).', category: 'challenge' },
    { text: 'Lascia che il gruppo scelga una parola; non puoi dire "sì" o "no" per 2 turni.', category: 'challenge' },
    { text: 'Di\' alla persona alla tua destra una cosa che ammiri della sua personalità.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena mangiato qualcosa di piccante.', category: 'funny' },
    { text: 'Manda un messaggio vocale a un contatto con una barzelletta (il gruppo approva).', category: 'risky' },
    { text: 'Parla sottovoce per i prossimi 3 turni.', category: 'funny' },
    { text: 'Fai 20 cerchi di caviglie in ogni direzione.', category: 'challenge' },
    { text: 'Fai una "conferenza stampa" come se avessi appena vinto qualcosa di grande.', category: 'funny' },
    { text: 'Lascia che qualcuno scelga il tuo prossimo tipo di storia Instagram (sondaggio, domanda, ecc.).', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di una persona appena beccata in una bugia.', category: 'funny' },
    { text: 'Di\' una cosa che faresti per supportare ogni persona.', category: 'friendship' },
    { text: 'Fai 10 mulini a vento (tocca le punte dei piedi).', category: 'challenge' },
    { text: 'Chiama un amico e di\' "Devo dirti una cosa" poi di\' "Sei fantastico/a."', category: 'funny' },
    { text: 'Leggi ad alta voce il nome della tua ultima sveglia.', category: 'risky' },
    { text: 'Fai una lettura drammatica di un\'etichetta nutrizionale.', category: 'funny' },
    { text: 'Fai 15 rotazioni del collo (delicate).', category: 'challenge' },
    { text: 'Di\' al gruppo in che modo ogni persona ti ha aiutato a crescere.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena ricevuto una promozione.', category: 'funny' },
    { text: 'Lascia che il gruppo scriva un breve messaggio; lo invii a qualcuno che sceglie.', category: 'risky' },
    { text: 'Imita un conduttore di documentario e narra la stanza per 1 minuto.', category: 'funny' },
    { text: 'Fai 20 cerchi di polsi.', category: 'challenge' },
    { text: 'Manda un messaggio a qualcuno "Sei una delle buone persone" senza contesto.', category: 'friendship' },
    { text: 'Fai una rievocazione drammatica della tua reazione a uno spavento improvviso.', category: 'funny' },
    { text: 'Lascia che qualcuno veda le tue ultime 3 foto (puoi sfocare se necessario).', category: 'risky' },
    { text: 'Parla con una voce da bambino entusiasta per i prossimi 2 turni.', category: 'funny' },
    { text: 'Fai 10 rotazioni delle spalle.', category: 'challenge' },
    { text: 'Di\' "Ti apprezzo" a ogni persona.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena ricevuto un complimento.', category: 'funny' },
    { text: 'Pubblica una storia con un "questo o quello" creato dal gruppo.', category: 'risky' },
    { text: 'Fai un monologo drammatico di 30 secondi su una penna.', category: 'funny' },
    { text: 'Fai 15 torsioni del tronco.', category: 'challenge' },
    { text: 'Di\' alla persona alla tua sinistra una cosa che ami della vostra amicizia.', category: 'friendship' },
    { text: 'Imita un conduttore di programma mattutino e presenta il "meteo" della stanza.', category: 'funny' },
    { text: 'Leggi ad alta voce il tuo ultimo promemoria.', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena ricevuto un pessimo servizio.', category: 'funny' },
    { text: 'Di\' una cosa che faresti per celebrare ogni persona.', category: 'friendship' },
    { text: 'Fai 20 stiramenti delle braccia.', category: 'challenge' },
    { text: 'Lascia che il gruppo scelga una canzone; ne canti un verso con una voce buffa.', category: 'funny' },
    { text: 'Manda a un amico un messaggio con una citazione positiva.', category: 'friendship' },
    { text: 'Lascia che qualcuno scelga il tuo prossimo stato WhatsApp.', category: 'risky' },
    { text: 'Fai un\'interpretazione drammatica di trovare dei soldi per terra.', category: 'funny' },
    { text: 'Fai 10 stiramenti dei quadricipiti (ogni gamba).', category: 'challenge' },
    { text: 'Di\' al gruppo una cosa che hai imparato da ogni persona.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena ricevuto l\'ordine sbagliato.', category: 'funny' },
    { text: 'Leggi ad alta voce il tuo ultimo evento nel calendario.', category: 'risky' },
    { text: 'Parla con una voce drammatica da trailer di film per il prossimo turno.', category: 'funny' },
    { text: 'Fai 15 stiramenti degli ischio-crurali.', category: 'challenge' },
    { text: 'Fai un discorso sullo "Stato della Stanza" come se fossi un leader.', category: 'funny' },
    { text: 'Lascia che il gruppo scelga una domanda; rispondi nella tua storia.', category: 'risky' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena appreso una buona notizia.', category: 'funny' },
    { text: 'Di\' "Hai il tuo posto qui" a ogni persona.', category: 'friendship' },
    { text: 'Fai 20 cerchi di fianchi.', category: 'challenge' },
    { text: 'Chiama un amico e di\' "Volevo solo salutarti" e chatta per 1 minuto.', category: 'friendship' },
    { text: 'Imita un conduttore di programma di viaggio e "visita" la stanza.', category: 'funny' },
    { text: 'Leggi ad alta voce la tua ultima nota digitata.', category: 'risky' },
    { text: 'Fai una rievocazione drammatica di dimenticare il nome di qualcuno.', category: 'funny' },
    { text: 'Fai 10 stiramenti a quattro (ogni lato).', category: 'challenge' },
    { text: 'Di\' alla persona alla tua destra una cosa che ricorderai sempre di lei.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena ricevuto un like.', category: 'funny' },
    { text: 'Lascia che il gruppo scelga una frase; la dici in modo drammatico.', category: 'funny' },
    { text: 'Pubblica una storia con un conto alla rovescia o un timer impostato dal gruppo.', category: 'risky' },
    { text: 'Fai 15 torsioni spinali (seduto).', category: 'challenge' },
    { text: 'Di\' una cosa che faresti per far sentire speciale ogni persona.', category: 'friendship' },
    { text: 'Fai la tua migliore imitazione di una persona che ha appena ricevuto una richiesta di seguire.', category: 'funny' },
    { text: 'Manda un messaggio vocale a un amico dicendogli che ti manca.', category: 'friendship' },
    { text: 'Lascia che qualcuno veda le tue ultime 5 ricerche.', category: 'risky' },
    { text: 'Parla con una voce monotona per i prossimi 2 turni.', category: 'funny' },
  ];
  
  module.exports = { truths, dares };