const truths = [
    { text: 'Cili është frika jote më e madhe?', category: 'general' },
    { text: 'Cila është gjëja më e turpshme që të ka ndodhur?', category: 'funny' },
    { text: 'Ke gënjyer ndonjëherë për të anuluar planet?', category: 'general' },
    { text: 'Cili është kënaqësia jote e fshehur?', category: 'general' },
    { text: 'Kush ishte dashuría jote e parë?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke thënë për një mik?', category: 'risky' },
    { text: 'Ke kopjuar ndonjëherë në një test?', category: 'general' },
    { text: 'Cili është pendimi yt më i madh?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për partnerin/en e një miku?', category: 'risky' },
    { text: 'Cila është gjëja më e çuditshme që beson?', category: 'funny' },
    { text: 'Cila është frika jote më irracionale?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se të pëlqen një dhuratë?', category: 'funny' },
    { text: 'Cila është gjëja më e keqe që ke bërë?', category: 'risky' },
    { text: 'Kë ke shtypje sekrete tani?', category: 'risky' },
    { text: 'Çfarë është diçka që nuk i ke treguar askujt?', category: 'risky' },
    { text: 'Ke thyer ndonjëherë zemrën e dikujt?', category: 'friendship' },
    { text: 'Cili është zakoni yt më i turpshëm?', category: 'funny' },
    { text: 'Ke përhapur ndonjëherë një thashetheme?', category: 'risky' },
    { text: 'Cila është takimi më i keq që ke pasur?', category: 'general' },
    { text: 'Ke qenë ndonjëherë i/e dashuruar?', category: 'friendship' },
    { text: 'Cila është pasiguria jote më e madhe?', category: 'general' },
    { text: 'Ke vjedhur ndonjëherë diçka?', category: 'risky' },
    { text: 'Cila është gjëja më fëminore që bën ende?', category: 'funny' },
    { text: 'Ke gënjyer ndonjëherë prindërit e tu?', category: 'general' },
    { text: 'Cili është talenti yt sekret?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një përvojë afër vdekjes?', category: 'general' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe i/e dehur?', category: 'risky' },
    { text: 'Ke qenë ndonjëherë i/e refuzuar?', category: 'friendship' },
    { text: 'Cila është gjëja që të bën nervoz/e më shumë?', category: 'general' },
    { text: 'Je kapur ndonjëherë duke gënjyer?', category: 'funny' },
    { text: 'Çfarë do të bëje nëse do të kishe një ditë të fundit për të jetuar?', category: 'challenge' },
    { text: 'Cili është telashi më i madh në të cilin ke qenë?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë një aventurë për një natë?', category: 'risky' },
    { text: 'Cili është mendimi yt më kontravers?', category: 'challenge' },
    { text: 'Ke tradhtuar ndonjëherë një mik?', category: 'risky' },
    { text: 'Cili është sekreti yt më i madh?', category: 'risky' },
    { text: 'Ke qenë ndonjëherë në një luftë fizike?', category: 'risky' },
    { text: 'Cila është puna më e keqe që ke pasur?', category: 'general' },
    { text: 'Ke qenë ndonjëherë i/e arrestuar ose i/e ndaluar?', category: 'risky' },
    { text: 'Çfarë është diçka që nuk do ta bëje kurrë përsëri?', category: 'general' },
    { text: 'Cila është kënga më e turpshme në listën tënde?', category: 'funny' },
    { text: 'Ke pasur ndonjëherë ndjenja për një mësues ose shef?', category: 'risky' },
    { text: 'Cila është gënjeshtra më e keqe që ke treguar?', category: 'risky' },
    { text: 'Je kapur ndonjëherë duke bërë diçka që nuk duhej?', category: 'general' },
    { text: 'Cili është kujtimi yt më i turpshëm nga fëmijëria?', category: 'funny' },
    { text: 'Ke braktisur ndonjëherë dikë pa shpjegim?', category: 'friendship' },
    { text: 'Cila është ëndërra më e çuditshme që ke pasur?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një sekret që nuk mund ta mbaje?', category: 'risky' },
    { text: 'Cila është gjëja më e pamatur që ke bërë?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë ndjenja për vëllain/motrën e një miku?', category: 'friendship' },
    { text: 'Çfarë je krenar/e por nuk e ndan kurrë?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e sëmurë për të shmangur diçka?', category: 'funny' },
    { text: 'Cila është gjëja që të largon më shumë tek një person?', category: 'general' },
    { text: 'Ke qenë ndonjëherë i/e lënë në pritje në një takim?', category: 'friendship' },
    { text: 'Cila është shuma më e madhe e parave që ke shpenzuar për diçka pa kuptim?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një konflikt të afërt me ligjin?', category: 'risky' },
    { text: 'Cila është dhurata më e keqe që ke marrë ndonjëherë?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë i/e dashuruar me dy persona njëherësh?', category: 'risky' },
    { text: 'Cili është mendimi yt më kontravers për ushqimin?', category: 'challenge' },
    { text: 'Ke gënjyer ndonjëherë në CV-në tënde?', category: 'risky' },
    { text: 'Cila është gjëja më fëminore që ende gëzohesh?', category: 'funny' },
    { text: 'Ke pasur ndonjëherë një miqësi që përfundoi keq?', category: 'friendship' },
    { text: 'Çfarë do të bëje nëse askush nuk do të të gjykonte?', category: 'challenge' },
    { text: 'Je kapur ndonjëherë duke vëzhguar dikë?', category: 'funny' },
    { text: 'Cila është gjëja irracionale që të bën nervoz/e më shumë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një miqësi njëanëshe?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke thënë pas shpine të dikujt?', category: 'risky' },
    { text: 'Ke pretenduar ndonjëherë se je i/e zënë për të shmangur dikë?', category: 'funny' },
    { text: 'Cila është shfaqja ose filmi yt i fshehur i preferuar?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë në këtë dhomë?', category: 'risky' },
    { text: 'Cila është gjëja më e turpshme që kanë bërë prindërit e tu?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një situatë të sikletshme?', category: 'funny' },
    { text: 'Çfarë është diçka që pendohesh që ke thënë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një adhurues/e sekret?', category: 'friendship' },
    { text: 'Cili është zakoni yt më i keq?', category: 'general' },
    { text: 'Ke qenë ndonjëherë "personi tjetër" në një situatë?', category: 'risky' },
    { text: 'Cila është gjëja më e turpshme në historikun tënd të kërkimeve?', category: 'funny' },
    { text: 'Ke pretenduar ndonjëherë se njeh dikë që nuk e njihje?', category: 'funny' },
    { text: 'Cila është frika jote më e madhe për të ardhmen?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për një të famshëm që të vjen turp?', category: 'funny' },
    { text: 'Cila është gjëja më egoiste që ke bërë?', category: 'risky' },
    { text: 'Je kapur ndonjëherë duke gënjyer partnerin/en tënd?', category: 'risky' },
    { text: 'Cila është gjëja më e çuditshme që të tërheq?', category: 'challenge' },
    { text: 'Ke pasur ndonjëherë një ëndërr për dikë në këtë dhomë?', category: 'risky' },
    { text: 'Cila është thashethemja më e keqe që ke dëgjuar për veten?', category: 'general' },
    { text: 'Ke qëndruar ndonjëherë në një marrëdhënie që dije se ishte gabim?', category: 'friendship' },
    { text: 'Cila është gjëja më e turpshme që ke bërë për të mbresëlënë dikë?', category: 'funny' },
    { text: 'Je kapur ndonjëherë duke folur me veten?', category: 'funny' },
    { text: 'Cila është pasiguria jote më e madhe për pamjen tënde?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një sekret që mund të prishë një miqësi?', category: 'risky' },
    { text: 'Cila është grindje më fëminore që ke pasur?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë xheloz/e për suksesin e një miku?', category: 'friendship' },
    { text: 'Cili është këshilla më e keqe që ke dhënë ndonjëherë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë shumë më të vjetër ose më të ri?', category: 'risky' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në punë ose shkollë?', category: 'funny' },
    { text: 'Cila është gjëja e fundit që ke kërkuar online?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një ID të rreme?', category: 'risky' },
    { text: 'Cila është kënga jote e preferuar për karaoke?', category: 'funny' },
    { text: 'Je kapur ndonjëherë duke gërvishtë hundën?', category: 'funny' },
    { text: 'Cila është kombinimi më i çuditshëm i ushqimeve që të pëlqen?', category: 'general' },
    { text: 'Ke qajtur ndonjëherë duke parë një film?', category: 'friendship' },
    { text: 'Cila është justifikimi yt më i përdorur për të ardhur vonë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një incident me rrobat në publik?', category: 'funny' },
    { text: 'Cila është gjëja e fundit që ke blerë dhe pendohesh?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për një personazh të vizatimeve?', category: 'funny' },
    { text: 'Cila është frika jote më e madhe për marrëdhëniet?', category: 'general' },
    { text: 'Ke spiunuar ndonjëherë telefonin e dikujt tjetër?', category: 'risky' },
    { text: 'Cila është gjëja më e turpshme në dhomën tënde?', category: 'funny' },
    { text: 'Ke pretenduar ndonjëherë se ke lexuar një libër që nuk e ke mbaruar?', category: 'funny' },
    { text: 'Cili është hobi yt sekret?', category: 'general' },
    { text: 'Je kapur ndonjëherë duke kënduar në dush?', category: 'funny' },
    { text: 'Cila është korrja më e keqe që ke pasur ndonjëherë?', category: 'funny' },
    { text: 'Ke pasur ndonjëherë ndjenja për një koleg pune?', category: 'risky' },
    { text: 'Çfarë je çuditërisht i/e mirë?', category: 'general' },
    { text: 'Ke fajësuar ndonjëherë vëllain/motrën tënde për diçka që ke bërë ti?', category: 'friendship' },
    { text: 'Cili është momenti yt më i turpshëm nga fëmijëria?', category: 'funny' },
    { text: 'Ke dërguar ndonjëherë një mesazh personit të gabuar?', category: 'risky' },
    { text: 'Cili është komplimenti më i çuditshëm që ke marrë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një ëndërr që ndihej tepër reale?', category: 'general' },
    { text: 'Cili është ushqimi yt i fshehur i preferuar?', category: 'general' },
    { text: 'Je kapur ndonjëherë në një gënjeshtër të bardhë?', category: 'funny' },
    { text: 'Cila është faza e modës më e keqe që ke kaluar?', category: 'funny' },
    { text: 'Ke pasur ndonjëherë një aksident të afërt gjatë ngasjes?', category: 'risky' },
    { text: 'Çfarë është diçka që nuk do ta pranoje kurrë personalisht?', category: 'challenge' },
    { text: 'Ke pasur ndonjëherë ndjenja për ish-partnerin/en e një miku?', category: 'risky' },
    { text: 'Cili është dështimi yt më i turpshëm i korrigjimit automatik?', category: 'funny' },
    { text: 'Ke pretenduar ndonjëherë se ishe në telefon për të shmangur dikë?', category: 'funny' },
    { text: 'Cila është dhurata më e keqe që ke dhënë ndonjëherë?', category: 'general' },
    { text: 'Je kapur ndonjëherë duke bërë diçka të turpshme?', category: 'funny' },
    { text: 'Cila është frika jote më e madhe për të plakur?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një shtrëngim sekret duarsh me dikë?', category: 'friendship' },
    { text: 'Cila është gjëja më fëminore që ende të duket qesharake?', category: 'funny' },
    { text: 'Ke gënjyer ndonjëherë për moshën tënde?', category: 'risky' },
    { text: 'Cili është këshilla më e keqe që ke ndjekur ndonjëherë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që sapo ke takuar?', category: 'friendship' },
    { text: 'Cili është momenti yt më i turpshëm në një festë?', category: 'funny' },
    { text: 'Je kapur ndonjëherë duke folur në gjumë?', category: 'funny' },
    { text: 'Cila është gjëja më e çuditshme që ke ngrënë ndonjëherë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një miqësi që filloi me një gënjeshtër?', category: 'risky' },
    { text: 'Cila është frika jote më e madhe për t\'u gjykuar?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se të pëlqen një këngë për t\'u integruar?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke thënë me zë të lartë?', category: 'funny' },
    { text: 'Ke pasur ndonjëherë një kod sekret me një mik?', category: 'friendship' },
    { text: 'Cila është ideja më e keqe për takim që ke pasur?', category: 'general' },
    { text: 'Je kapur ndonjëherë duke kërcyer kur mendoje se askush nuk të shikonte?', category: 'funny' },
    { text: 'Cila është aplikacioni i fundit që ke shkarkuar?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një nofkë që e urreje?', category: 'funny' },
    { text: 'Cila është gjëja që të bën nervoz/e më shumë tek një shok dhome?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e sëmurë për të tërhequr vëmendjen?', category: 'funny' },
    { text: 'Cila është blerja më e pamatur që ke bërë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për një të huaj që ke parë vetëm një herë?', category: 'friendship' },
    { text: 'Cila është banomi më e keqe që ke treguar ndonjëherë?', category: 'funny' },
    { text: 'Je kapur ndonjëherë duke vështruar veten në pasqyrë?', category: 'funny' },
    { text: 'Cili është ushqimi yt sekret për ngushëllim?', category: 'general' },
    { text: 'Ke gënjyer ndonjëherë për gjatësinë ose peshën tënde?', category: 'risky' },
    { text: 'Cila është gjëja më e turpshme që ka bërë vëllai/motra jote?', category: 'funny' },
    { text: 'Ke pasur ndonjëherë një ëndërr për dikë që nuk e do?', category: 'general' },
    { text: 'Cili është zakoni më i keq që ke marrë nga dikush?', category: 'general' },
    { text: 'Je kapur ndonjëherë duke bërë një selfie?', category: 'funny' },
    { text: 'Cila është frika jote më e madhe për dështimin?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një sekret që ia ke treguar vetëm një personi?', category: 'risky' },
    { text: 'Cila është gjëja më e turpshme që ke bërë për të marrë "like"?', category: 'funny' },
    { text: 'Ke pretenduar ndonjëherë se ke kuptuar një shaka që nuk e ke kuptuar?', category: 'funny' },
    { text: 'Cila është thashethemja më e keqe që ke përhapur ndonjëherë?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë ndjenja për një personazh në libër ose shfaqje?', category: 'funny' },
    { text: 'Cili është momenti yt më i turpshëm nga ora e gjimnastikës?', category: 'funny' },
    { text: 'Je kapur ndonjëherë duke folur me kafshën tënde si person?', category: 'funny' },
    { text: 'Cila është gjëja më e çuditshme që ke besuar si fëmijë?', category: 'funny' },
    { text: 'Ke pasur ndonjëherë një miqësi që përfundoi nga një keqkuptim?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të qenë vetëm?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e zënë kur nuk ishe?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme në historikun tënd të shfletuesit?', category: 'risky' },
    { text: 'Je kapur ndonjëherë duke kënduar në makinë?', category: 'funny' },
    { text: 'Cila është rreshti më i keq i flirtimit që ke përdorur ose dëgjuar?', category: 'funny' },
    { text: 'Ke pasur ndonjëherë një sekret që e ke treguar më në fund?', category: 'risky' },
    { text: 'Cila është gjëja irracionale që të bën nervoz/e?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se punoje kur po bezdiseshe?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë për të tërhequr vëmendjen?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë xheloz/e për marrëdhënien e një miku?', category: 'friendship' },
    { text: 'Cila është zgjedhja e modës më e keqe që ke bërë ndonjëherë?', category: 'funny' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që nuk të ka dashur?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për angazhimin?', category: 'general' },
    { text: 'Je kapur ndonjëherë duke ëndërruar me sy hapur në klasë ose punë?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke postuar online?', category: 'funny' },
    { text: 'Ke gënjyer ndonjëherë për vendndodhjen tënde?', category: 'risky' },
    { text: 'Cila është ëndërra më e çuditshme që ke pasur për dikë këtu?', category: 'challenge' },
    { text: 'Ke pasur ndonjëherë një adhurues/e sekret për të cilin nuk i ke treguar askujt?', category: 'friendship' },
    { text: 'Cili është momenti yt më i turpshëm nga një mbledhje familjare?', category: 'funny' },
    { text: 'Je kapur ndonjëherë duke bërë një grimacë qesharake në foto?', category: 'funny' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe i/e zemëruar?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë ndjenja për shtypjen e një miku?', category: 'risky' },
    { text: 'Cila është frika jote më e madhe për të qenë i/e cenueshëm?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se të pëlqen një ushqim që e urren?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një takim?', category: 'funny' },
    { text: 'Je kapur ndonjëherë duke qeshur me shakanë tënde?', category: 'funny' },
    { text: 'Cila është gënjeshtra më e keqe që ke treguar për të anuluar planet?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një miqësi që pendohesh që e ke mbaruar?', category: 'friendship' },
    { text: 'Cili është momenti yt më i turpshëm nga një pushim?', category: 'funny' },
    { text: 'Je kapur ndonjëherë duke folur me veten në publik?', category: 'funny' },
    { text: 'Cila është gjëja më e çuditshme që koleksionon ose koleksionoje?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë në një pozitë pushteti?', category: 'risky' },
    { text: 'Cila është frika jote më e madhe për refuzimin?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se ke parë një film që nuk e ke?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një dasmë?', category: 'funny' },
    { text: 'Je kapur ndonjëherë duke bërë diçka që ke thënë se nuk do ta bëje kurrë?', category: 'funny' },
    { text: 'Cila është justifikimi më i keq që ke përdorur ndonjëherë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një sekret që mund të ndryshojë një marrëdhënie?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një intervistë pune?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë xheloz/e për vëllain/motrën tënde?', category: 'friendship' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë kur askush nuk të shikonte?', category: 'challenge' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që ishte i gabuar për ty?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për suksesin?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se flije për të shmangur dikë?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një restorant?', category: 'funny' },
    { text: 'Je kapur ndonjëherë duke parë diçka të turpshme?', category: 'funny' },
    { text: 'Cila është vendimi më i keq që ke marrë me nxitim?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një sekret që ende e mban?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga takimi i parë?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë i/e fundit që mëson diçka për një mik?', category: 'friendship' },
    { text: 'Cili është zakoni yt më i çuditshëm?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që nuk duhej?', category: 'risky' },
    { text: 'Cila është frika jote më e madhe për ndryshimin?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e sigurt kur nuk ishe?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një pyjamë-parti?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një foto të turpshme?', category: 'funny' },
    { text: 'Cila është gjëja më e keqe që ke thënë në nxehtësinë e momentit?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë një miqësi që ndihej njëanëshe?', category: 'friendship' },
    { text: 'Cili është momenti yt më i turpshëm nga një koncert?', category: 'funny' },
    { text: 'Je kapur ndonjëherë duke kënduar në publik?', category: 'funny' },
    { text: 'Cila është gjëja më e çuditshme që të qetëson?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që ke takuar online?', category: 'risky' },
    { text: 'Cila është frika jote më e madhe për të panjohurën?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se të intereson një temë që e urren?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një bashkim?', category: 'funny' },
    { text: 'Je kapur ndonjëherë duke bërë diçka fëminore?', category: 'funny' },
    { text: 'Cila është gjëja më e keqe që ke bërë për të mbresëlënë dikë?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë një sekret që do doje ta mund të tregoje?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një festë?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që shkaktoi mbarimin e një miqësie?', category: 'friendship' },
    { text: 'Cila është frika më e çuditshme që ke pasur si fëmijë?', category: 'funny' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që nuk ia ke treguar kurrë?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për besimin?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e lumtur kur nuk ishe?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një funeral?', category: 'funny' },
    { text: 'Je kapur ndonjëherë duke gënjyer nga një mik?', category: 'risky' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe i/e mërzitur?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një sekret që të ka bërë të ndihesh fajtor?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një festë ditëlindjeje?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë i/e tepërt (tria)?', category: 'friendship' },
    { text: 'Cila është gjëja më e çuditshme që ke thënë ndonjëherë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që ishte i/e lidhur?', category: 'risky' },
    { text: 'Cila është frika jote më e madhe për dashurinë?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë të jesh dikush tjetër online?', category: 'risky' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një mbledhje?', category: 'funny' },
    { text: 'Je kapur ndonjëherë duke bërë diçka për të cilën të vjen turp?', category: 'risky' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe i/e dehur?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë një miqësi për të cilën ke mall?', category: 'friendship' },
    { text: 'Cili është momenti yt më i turpshëm nga një ngjarje sportive?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në heshtje të sikletshme?', category: 'funny' },
    { text: 'Cila është gjëja më e çuditshme që ke dëshiruar ndonjëherë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë me të cilin punon?', category: 'risky' },
    { text: 'Cila është frika jote më e madhe për t\'u keqkuptuar?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se ke harruar diçka me qëllim?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një dasmë?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej ta mbaronte një miqësi?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë për para?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë një sekret nga i cili ke frikë?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një prezantim?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një pozitë komprometuese?', category: 'risky' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë për argëtim?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që mezi e njeh?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të zhgënjyer të tjerët?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e sëmurë për të shmangur punën ose shkollën?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një festë?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që u braktis?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe xheloz/e?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë një sekret që mund të dëmtojë dikë?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një seancë fotografie?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një grindje të kotë?', category: 'funny' },
    { text: 'Cila është gjëja më e çuditshme që ke provuar ndonjëherë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që e sheh çdo ditë?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për t\'u përjashtuar?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e lodhur për të larguar herët?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një bar?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që përhapi thashethemet?', category: 'risky' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe i/e stresuar?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një sekret që ia ke treguar personit të gabuar?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një udhëtim?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një moment dobësie?', category: 'general' },
    { text: 'Cila është gjëja më e çuditshme që ke besuar ndonjëherë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që të ka braktisur?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për t\'u zëvendësuar?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je mirë kur ishe i/e lënduar?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një klub?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që u tradhëtua?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe i/e frikësuar?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një sekret që pendohesh që e ke treguar?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një klasë?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një situatë qesharake?', category: 'funny' },
    { text: 'Cila është gjëja më e çuditshme që ke thënë ndonjëherë për një të huaj?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që nuk mund ta kesh?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për t\'u harruar?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se pajtohesh kur nuk pajtoheshe?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një koncert?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej të kërkonte falje?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe i/e lodhur?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një sekret për të cilin je krenar/e?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një darkë?', category: 'funny' },
    { text: 'Je kapur ndonjëherë duke gënjyer nga familja?', category: 'risky' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë vetëm?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë nga e kaluara jote?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për t\'u gjykuar nga familja?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e ftohtë kur ishe nervoz/e?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një kafene?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që u refuzua?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe i/e trishtuar?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një sekret që e ke shkruar diku?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një fluturim?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një zakon të çuditshëm?', category: 'funny' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë me miqtë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë me të cilin ke gërryer?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të qenë i/e cenueshëm me miqtë?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e guximshëm kur ishe i/e frikësuar?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një qendër tregtare?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej të falte?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe i/e lumtur?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një sekret që gati e ke treguar?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një shëtitje malore?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një moment ndershmërie?', category: 'general' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë natën?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që e admiron?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të qenë tepër shumë?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e qetë kur ishe i/e trazuar?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë pranë pishinës?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej të kërkonte falje i/e pari?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe i/e zemëruar me dikë?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë një sekret që e mban nga familja jote?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një udhëtim në plazh?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një moment të kotë?', category: 'funny' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë në mëngjes?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që të bënte nervoz?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të mos qenë i/e mjaftueshëm?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se di diçka që nuk e dije?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në palestër?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej të linte gjërat?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe i/e turpëruar?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një sekret që ia tregon vetëm një personi?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një udhëtim me makinë?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një moment dembel?', category: 'funny' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë për t\'u çlodhur?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që të bënte të buzëqeshje?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të qenë shumë pak?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e befasuar kur nuk ishe?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një park?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej të vazhdonte?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe i/e hutuar?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një sekret nga i cili ke frikë se mund të dalë?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një udhëtim kampingu?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një moment të çuditshëm?', category: 'funny' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë për t\'u çlodhur?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që të bënte të qeshje?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të qenë i/e mërzitshëm?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e zënë për të shmangur një bisedë?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një muze?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej të thoshte lamtumirë?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe i/e padurueshëm?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një sekret që e ke shkruar në ditar?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një udhëtim me barkë?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një moment të lumtur?', category: 'funny' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë për të procrastinuar?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që ishte i/e sjellshëm me ty?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të qenë i/e bezdisshëm?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se dëgjoje kur nuk dëgjoje?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në kopshtin zoologjik?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej të fillonte nga e para?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe xheloz/e ndaj një miku?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë një sekret që e ke shtypur por nuk e ke dërguar?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një festival?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një moment të trishtuar?', category: 'general' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë për të mbresëlënë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që ishte qesharak?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të qenë tepër i/e heshtur?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se flije për të dëgjuar një bisedë?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një teatër?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej të bënte pajtimin?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe në humor të keq?', category: 'general' },
    { text: 'Ke pasur ndonjëherë një sekret që ia ke pëshpëritur dikujt?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një piknik?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një moment romantik?', category: 'funny' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë për të shmangur punën?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që ishte i/e zgjuar?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të qenë tepër i/e lartë zëri?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e sëmurë për të shmangur një takim?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një bibliotekë?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej të pranonte të vërtetën?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe xheloz/e ndaj vëllait/motrës?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë një sekret për të cilin je gëzuar që e ke mbajtur?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një skarë?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një moment nervoz?', category: 'funny' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë për t\'u integruar?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që ishte krijues?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të qenë tepër serioz?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je zgjuar kur ishe gjysmë i/e fjetur?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një pistë bowlingu?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej të merrte fajin?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe xheloz/e ndaj një kolegu?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë një sekret nga i cili ke frikë se mund të zbulohet?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një natë karaoke?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një moment të entuziazmuar?', category: 'funny' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë për të festuar?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që ishte i talentuar?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të qenë tepër budallë?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e ofenduar kur nuk ishe?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një pistë bowlingu?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej të mbronte dikë?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe xheloz/e ndaj ish-partnerit?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë një sekret për të cilin mendoni shpesh?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një mbrëmje lojërash?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një moment mendimtar?', category: 'general' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë për të befasuar dikë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që ishte misterioz?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të qenë tepër i/e ndershëm?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e zemëruar kur nuk ishe?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një kazino?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej të mbante një sekret për dikë?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe xheloz/e ndaj një të huaji?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë një sekret që dëshiron ta tregosh por nuk mund?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një darkë mes miqsh?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një moment nostalgji?', category: 'general' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë për të ndihmuar dikë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që ishte aventurier?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të qenë tepër i/e varur?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e trishtuar kur nuk ishe?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një pritje pas dasmës?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej të jepte lajme të këqija?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe xheloz/e ndaj një të famshmi?', category: 'funny' },
    { text: 'Ke pasur ndonjëherë një sekret që e ke treguar shumë shpejt?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një festë e lindjes së fëmijës?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një moment shprese?', category: 'general' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë për hakmarrje?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që ishte i/e qetë?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të qenë tepër i/e pavarur?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e entuziazmuar kur nuk ishe?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një festë lindjes së fëmijës?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej të ngushëllonte dikë?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe xheloz/e ndaj një fqinji?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë një sekret që pendohesh që nuk e ke treguar?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një diplomim?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një moment paqeje?', category: 'general' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë për të tërhequr vëmendjen?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që ishte i/e pasionuar?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të qenë tepër emocional?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je xheloz/e kur nuk ishe?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një festë diplomimi?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej të jepte këshilla?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe xheloz/e ndaj një të afërmi?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë një sekret që e ke treguar në ëndërr?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një festë private?', category: 'funny' },
    { text: 'Je kapur ndonjëherë duke gërryer me veten?', category: 'funny' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë për të fituar një bast?', category: 'challenge' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që ishte i/e turpshëm?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të qenë tepër logjik?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e qetë kur po panikoseshe?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një festë rinovimi shtëpie?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që ndërmjetësoi një sherr?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe xheloz/e ndaj një shoku klase?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë një sekret që e ke shkruar në një letër por nuk e ke dërguar?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një bashkim?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një moment guximi?', category: 'general' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë për të bërë dikë të qeshë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që ishte i/e hapur?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të qenë tepër i/e ndjeshëm?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je indiferent kur të interesonte?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një festë dalje në pension?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej të zgjidhte anën?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe xheloz/e ndaj një anëtari ekipit?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë një sekret që e ke sugjeruar por kurrë nuk e ke thënë?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një festë e fundvitit?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një moment mirësie?', category: 'general' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë për të kaluar mbi dikë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që ishte kokëfortë?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të qenë tepër falës?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e lënduar kur nuk ishe?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një festë zyre?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej të tregonte një gënjeshtër të bardhë?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe xheloz/e ndaj shokut të dhomës?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë një sekret që planifikon ta tregosh ndonjë ditë?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një darkë ditëlindjeje?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një moment dobësie dhe pastaj force?', category: 'general' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë për të mbajtur mend dikë?', category: 'general' },
    { text: 'Ke pasur ndonjëherë ndjenja për dikë që ishte ndryshe nga ti?', category: 'friendship' },
    { text: 'Cila është frika jote më e madhe për të qenë tepër besues?', category: 'general' },
    { text: 'Ke pretenduar ndonjëherë se je i/e durueshëm kur nuk ishe?', category: 'funny' },
    { text: 'Cila është gjëja më e turpshme që ke bërë në një ngjarje networkingu?', category: 'funny' },
    { text: 'Ke qenë ndonjëherë ai/ajo që duhej të mbante paqen?', category: 'friendship' },
    { text: 'Cila është gjëja më e keqe që ke bërë kur ishe xheloz/e ndaj mikut tënd më të mirë?', category: 'risky' },
    { text: 'Ke pasur ndonjëherë një sekret që po pret momentin e duhur për ta treguar?', category: 'risky' },
    { text: 'Cili është momenti yt më i turpshëm nga një takim i verbër?', category: 'funny' },
    { text: 'Je kapur ndonjëherë në një moment qartësie?', category: 'general' },
    { text: 'Cila është gjëja më e çuditshme që ke bërë ndonjëherë për të nderuar dikë?', category: 'general' },
  ];
  
  const dares = [
    { text: 'Bëj imitimin tënd më të mirë të dikujt në dhomë.', category: 'funny' },
    { text: 'Këndo refrenet e këngës sate të preferuar me zë të lartë.', category: 'funny' },
    { text: 'Kërcej për 30 sekonda pa muzikë.', category: 'challenge' },
    { text: 'Fol me theks për 3 raunde të ardhshme.', category: 'funny' },
    { text: 'Lëre dikë tjetër të postojë një histori në rrjetet e tua sociale.', category: 'risky' },
    { text: 'Telefono një kontakt dhe i këndoi ditëlindjen e lumtur.', category: 'challenge' },
    { text: 'Bëj 10 shtytje ose squats.', category: 'challenge' },
    { text: 'Haj një lugë çaji nga një salcë e zgjedhur nga grupi.', category: 'challenge' },
    { text: 'Lëre grupin të shfletojë galerinë e fotove për 1 minutë.', category: 'risky' },
    { text: 'Thuaj diçka të mirë për secilën person në dhomë.', category: 'friendship' },
    { text: 'Bëj handstand ose headstand për 10 sekonda.', category: 'challenge' },
    { text: 'Fol vetëm me pyetje për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Lëre dikë të vizatojë në fytyrën tënde me stilolaps.', category: 'funny' },
    { text: 'Shkëmbe një copë rrobash me personin në të majtën tënde.', category: 'challenge' },
    { text: 'Bëj imitimin tënd më të mirë të kafshëve dhe mbaje për 1 minutë.', category: 'funny' },
    { text: 'Dërgo një mesazh zanor tek shtypja jote ose ish (grupi zgjedh tekstin).', category: 'risky' },
    { text: 'Balansoje një libër mbi kokën tënde për 2 minuta.', category: 'challenge' },
    { text: 'Lëre grupin të të bëjë një model të ri flokësh.', category: 'funny' },
    { text: 'Bëj një lexim dramatik të mesazhit të fundit që ke dërguar.', category: 'funny' },
    { text: 'Mbaj plankun për 1 minutë.', category: 'challenge' },
    { text: 'Fol me rimë për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Lëre dikë të të gërshërojë për 30 sekonda pa qeshur.', category: 'challenge' },
    { text: 'Bëj një shfaqje mode duke veshur rrobat prapa.', category: 'funny' },
    { text: 'Telefono një anëtar familje dhe i trego se e do.', category: 'friendship' },
    { text: 'Haj diçka pa përdorur duart.', category: 'challenge' },
    { text: 'Lëre grupin të zgjedhë një emoji; reago kështu për 2 raunde.', category: 'funny' },
    { text: 'Bëj imitimin tënd më të mirë të një të famshmi.', category: 'funny' },
    { text: 'Thuaj alfabetin prapa në më pak se 30 sekonda.', category: 'challenge' },
    { text: 'Lëre dikë tjetër të kontrollojë telefonin tënd për 5 minutat e ardhshme.', category: 'risky' },
    { text: 'Bëj një kërcim TikTok ose viral para të gjithëve.', category: 'funny' },
    { text: 'Fol me zë fëmije për 3 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj një fjalim motivues 1-minutësh për grupin.', category: 'challenge' },
    { text: 'Lëre grupin të zgjedhë foton tënde të profilit për 24 orë.', category: 'risky' },
    { text: 'Bëj 20 jumping jacks.', category: 'challenge' },
    { text: 'Dërgoi personit të fundit me të cilin ke folur mesazhin "Më mungon".', category: 'risky' },
    { text: 'Sillhu si pulë deri në raundin tënd të ardhshëm.', category: 'funny' },
    { text: 'Lëre dikë të të ushqejë me sy mbyllur.', category: 'challenge' },
    { text: 'Lexo 3 mesazhet e fundit që ke marrë me zë të lartë.', category: 'risky' },
    { text: 'Bëj imitimin e personit në të djathtën tënde.', category: 'funny' },
    { text: 'Lëre grupin të zgjedhë një këngë; duhet të këndosh strofën e parë.', category: 'challenge' },
    { text: 'Bëj 15 squats duke bërë kontakt vizual me të gjithë.', category: 'challenge' },
    { text: 'Lëre dikë të të rregullojë flokët si të dojë për pjesën tjetër të lojës.', category: 'funny' },
    { text: 'Fol me theks pirate për 3 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj imitimin tënd më të mirë të një të famshmi dhe lëre grupin të marrë me mend.', category: 'funny' },
    { text: 'Lëre personin në të djathtën tënde të shfletojë rulon e kamerës për 30 sekonda.', category: 'risky' },
    { text: 'Dërgoi personit të fundit në kontaktet e tua një mesazh flirtues (grupi e shkruan).', category: 'risky' },
    { text: 'Bëj një shëtitje si model dhe pozo në fund.', category: 'funny' },
    { text: 'Haj një kafshatë ushqimi me sy mbyllur ndërsa dikush të ushqen.', category: 'challenge' },
    { text: 'Lëre grupin të të japë një nofkë të re për pjesën tjetër të natës.', category: 'funny' },
    { text: 'Bëj 10 burpees.', category: 'challenge' },
    { text: 'Lexo kërkimin tënd të fundit me zë të lartë.', category: 'risky' },
    { text: 'Sillhu si qen për 1 minutë.', category: 'funny' },
    { text: 'Lëre dikë të të fusë akull pas shpine.', category: 'challenge' },
    { text: 'Bëj një monolog dramatik sikur je në një telenovelë.', category: 'funny' },
    { text: 'Fol me theks britanik (ose tjetër) deri në raundin tënd të ardhshëm.', category: 'funny' },
    { text: 'Lëre grupin të zgjedhë një veshje nga dollapi yt; e vesh për 10 minuta.', category: 'challenge' },
    { text: 'Bëj handstand afër murit për 15 sekonda.', category: 'challenge' },
    { text: 'Telefono një mik dhe thuaj "Kam diçka të rëndësishme për të të treguar" pastaj mbyll.', category: 'risky' },
    { text: 'Lëre dikë të të vizatojë mustaqe me stilolaps.', category: 'funny' },
    { text: 'Bëj imitimin tënd më të mirë të personit në të majtën tënde.', category: 'funny' },
    { text: 'Haj një lugë çaji me salcë të nxehtë ose limon.', category: 'challenge' },
    { text: 'Lëre grupin të lexojë 5 mesazhet e fundit (mund të fshehësh emrat).', category: 'risky' },
    { text: 'Bëj një cartwheel ose provojë.', category: 'challenge' },
    { text: 'Këndo "Happy Birthday" për veten tënde në mënyrë dramatike.', category: 'funny' },
    { text: 'Lëre dikë të të gërshërojë për 20 sekonda pa lëvizur.', category: 'challenge' },
    { text: 'Bëj një reklamë për një produkt imagjinar.', category: 'funny' },
    { text: 'Fol vetëm me tekste këngësh për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Lëre grupin të zgjedhë çfarë postoni tjetër në historinë tënde.', category: 'risky' },
    { text: 'Bëj 20 sit-ups.', category: 'challenge' },
    { text: 'Sillhu si mace për 1 minutë (miau, lëp "putrat", etj.).', category: 'funny' },
    { text: 'Lëre dikë tjetër të shkruajë një mesazh dhe ti dërgoje personit që zgjedhin.', category: 'risky' },
    { text: 'Bëj një riprodhim në xhiro të ngadaltë duke "shënuar një gol" ose "fituar një garë".', category: 'funny' },
    { text: 'Haj një copë bukë pa përdorur duart.', category: 'challenge' },
    { text: 'Lëre grupin të shohë emojitë e tua më të përdorura dhe të marrë me mend kë mesazhoni më shumë.', category: 'risky' },
    { text: 'Bëj këndimin tënd më të mirë të operës për 30 sekonda.', category: 'funny' },
    { text: 'Fol me zë roboti për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Lëre dikë të të vendosë një shall dhe të të rrotullojë 5 herë; pastaj provo të ecësh drejt.', category: 'challenge' },
    { text: 'Bëj një trend TikTok (aktual ose të vjetër) para të gjithëve.', category: 'funny' },
    { text: 'Telefono një piceri dhe kërko një "picë surprizë" (mos porosit vërtet).', category: 'funny' },
    { text: 'Lëre personin në të majtën tënde të zgjedhë 3 postimet e ardhshme në rrjete sociale.', category: 'risky' },
    { text: 'Bëj një rënie besimi në krahët e grupit.', category: 'challenge' },
    { text: 'Sillhu sikur je në një film të heshtur për 1 minutë.', category: 'funny' },
    { text: 'Lëre dikë të të ushqejë me 3 ushqime të ndryshme me sy mbyllur; merr me mend cilat janë.', category: 'challenge' },
    { text: 'Bëj imitimin tënd më të mirë të një mësuesi ose shefi.', category: 'funny' },
    { text: 'Fol me rimë për 3 raunde të ardhshme.', category: 'funny' },
    { text: 'Lëre grupin të zgjedhë një këngë; kërceje për 1 minutë.', category: 'challenge' },
    { text: 'Bëj 30 sekonda stand-up komedi për veten tënde.', category: 'funny' },
    { text: 'Telefono një anëtar familje dhe i thuaj se e do në mënyrën më dramatike të mundshme.', category: 'friendship' },
    { text: 'Lëre dikë të shfletojë aplikacionin e shënimeve për 30 sekonda.', category: 'risky' },
    { text: 'Bëj një lexim dramatik të një artikulli të rastit nga Wikipedia.', category: 'funny' },
    { text: 'Sillhu si prezantues lajmesh duke raportuar mbi lojën aktuale.', category: 'funny' },
    { text: 'Lëre grupin të të japë një foto të re të profilit për 24 orë.', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një komentatori sportiv.', category: 'funny' },
    { text: 'Fol si një personazh i Shekspirit për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Lëre dikë të zgjedhë çfarë do të hash për vaktin tënd të ardhshëm.', category: 'challenge' },
    { text: 'Bëj një komentim "get ready with me" duke rregulluar flokët.', category: 'funny' },
    { text: 'Telefono një kontakt rastësor dhe thuaj "Doja vetëm ta dëgjoja zërin tënd" pastaj mbyll.', category: 'risky' },
    { text: 'Lëre grupin të shohë njërën nga listat e tua muzikore dhe ta kritikojë.', category: 'funny' },
    { text: 'Bëj një trikë magjike (reale ose false) për grupin.', category: 'funny' },
    { text: 'Sillhu si instruktor fitness dhe udhëheq një "stërvitje" 1-minutëshe.', category: 'funny' },
    { text: 'Lëre dikë të shkruajë një subtitle për postin tënd të ardhshëm.', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një politikani që mban fjalim.', category: 'funny' },
    { text: 'Fol vetëm me pyetje për 3 raunde të ardhshme.', category: 'funny' },
    { text: 'Lëre personin në të djathtën tënde të zgjedhë tonin tënd të telefonit për një javë.', category: 'challenge' },
    { text: 'Bëj një rikrijim dramatik të herës së fundit që gosite gishtin e këmbës.', category: 'funny' },
    { text: 'Jepi çdokujt në dhomë një kompliment në mënyrë poetike.', category: 'friendship' },
    { text: 'Lëre grupin të zgjedhë një foto të vjetër tënden; duhet ta postosh si histori.', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një parashikuesi moti.', category: 'funny' },
    { text: 'Sillhu sikur je në një reklamë për dhomën ku ndodheni.', category: 'funny' },
    { text: 'Lëre dikë të lexojë bisedën tënde të fundit private (me emra të fshehur nëse nevojitet).', category: 'risky' },
    { text: 'Bëj 10 lunges duke thënë diçka të mirë për secilën person.', category: 'challenge' },
    { text: 'Fol me zë të ulët për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Lëre grupin të zgjedhë çfarë do të pish tjetër.', category: 'challenge' },
    { text: 'Bëj një interpretim dramatik të "Duhet të shkoj në banjë".', category: 'funny' },
    { text: 'Telefono një mik dhe këndo 30 sekondat e para të një kënge që zgjedhin ata.', category: 'challenge' },
    { text: 'Lëre dikë të vizatojë në krahun tënd me stilolaps (të larshëm).', category: 'funny' },
    { text: 'Bëj imitimin tënd më të mirë të një prezantuesi të lojës.', category: 'funny' },
    { text: 'Sillhu si udhërrëfyes duke treguar të gjithëve dhomën.', category: 'funny' },
    { text: 'Lëre grupin të vendosë një gjë që duhet ta bësh nesër.', category: 'challenge' },
    { text: 'Bëj një komentim "dita ime" për orën e fundit.', category: 'funny' },
    { text: 'Jepi personit në të majtën tënde një fjalim inkurajues 30-sekondshe.', category: 'friendship' },
    { text: 'Lëre dikë të zgjedhë një veshje nga dollapi yt; e vesh për orën e ardhshme.', category: 'challenge' },
    { text: 'Bëj imitimin tënd më të mirë të një kuzhinieri që prezanton një pjatë.', category: 'funny' },
    { text: 'Fol sikur je në një film horror për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Lëre grupin të zgjedhë një filter; bëj selfie dhe posto.', category: 'risky' },
    { text: 'Bëj një lexim dramatik të një mesazhi që ke marrë sot.', category: 'funny' },
    { text: 'Sillhu si komentator për raundin e ardhshëm të lojës.', category: 'funny' },
    { text: 'Bëj 25 jumping jacks duke kënduar një këngë fëmijërie.', category: 'challenge' },
    { text: 'Lëre grupin të zgjedhë një fjalë; e përdor në çdo fjali për 3 raunde.', category: 'funny' },
    { text: 'Dërgoi një kontakti një mesazh zanor duke thënë se po mendon për të.', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një antago nga film.', category: 'funny' },
    { text: 'Jepi personit në të majtën tënde një masazh shpine 30-sekondshe.', category: 'friendship' },
    { text: 'Haj një krisëse dhe provoje të fishkëllesh menjëherë pas.', category: 'challenge' },
    { text: 'Lëre dikë të postojë një status në emrin tënd (ata zgjedhin tekstin).', category: 'risky' },
    { text: 'Fol si poet për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj 15 mountain climbers.', category: 'challenge' },
    { text: 'Dërgoji nënës ose babait "Të dua" me emoji zemre.', category: 'friendship' },
    { text: 'Sillhu si detektiv dhe "heto" dhomën për 1 minutë.', category: 'funny' },
    { text: 'Lëre grupin të shohë 10 fotot e tua të fundit (pa kapërcyer).', category: 'risky' },
    { text: 'Bëj një lexim dramatik të menysë së ushqimit për porosi.', category: 'funny' },
    { text: 'Mbaj frymën për 30 sekonda, pastaj thuaj një gjuhëthelëse.', category: 'challenge' },
    { text: 'Komplimentoje personin në të djathtën tënde në mënyrë krijuese.', category: 'friendship' },
    { text: 'Fol me theks jugor për 3 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj 20 high knees në vend.', category: 'challenge' },
    { text: 'Telefono një mik dhe thuaj "Merr me mend?" pastaj thuaj "Kic de picë."', category: 'funny' },
    { text: 'Lëre dikë të shfletojë listën "duke ndjekur" në Instagram tënd për 30 sekonda.', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një superhero.', category: 'funny' },
    { text: 'Thuaj tre gjëra që admiron tek secili person në dhomë.', category: 'friendship' },
    { text: 'Haj një feta limoni pa bërë fytyrë.', category: 'challenge' },
    { text: 'Lexo temën e emailit të fundit të dërguar me zë të lartë.', category: 'risky' },
    { text: 'Sillhu si stjuardesë dhe jep udhëzime sigurie për dhomën.', category: 'funny' },
    { text: 'Bëj 10 tricep dips duke përdorur një karrige ose divan.', category: 'challenge' },
    { text: 'Dërgoi një miku një kompliment rastësor.', category: 'friendship' },
    { text: 'Fol me theks francez për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Lëre grupin të zgjedhë çfarë do të kafshësh tjetër.', category: 'challenge' },
    { text: 'Bëj një rikrijim dramatik të rastit të rënies.', category: 'funny' },
    { text: 'Dërgoi personit të fundit që i ke shkruar një meme (grupi zgjedh memën).', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një folësi motivues.', category: 'funny' },
    { text: 'Përqafo të gjithë në dhomë dhe thuaj diçka të mirë për secilin.', category: 'friendship' },
    { text: 'Qëndro në një këmbë për 1 minutë duke treguar një histori.', category: 'challenge' },
    { text: 'Lexo mesazhin e parë në kutinë hyrëse me zë të lartë (grupi vendos nëse dërgon përgjigje).', category: 'risky' },
    { text: 'Sillhu si konkurrent loje për raundin e ardhshëm.', category: 'funny' },
    { text: 'Bëj 15 butt kicks.', category: 'challenge' },
    { text: 'Telefono një anëtar familje dhe tregoi një shaka.', category: 'friendship' },
    { text: 'Fol vetëm me citate filmash për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Lëre dikë të zgjedhë një këngë të turpshme; dëgjoje 30 sekonda pa reagim.', category: 'challenge' },
    { text: 'Bëj një reklamë për produktin më të keq që mund të mendosh.', category: 'funny' },
    { text: 'Posto një histori me një subtitle që shkruan grupi.', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një kuzhinieri në emision gatimi.', category: 'funny' },
    { text: 'Jepi personit në të majtën tënde arsyen pse je i/e gëzuar që janë miku yt.', category: 'friendship' },
    { text: 'Bëj 20 sekonda wall sit.', category: 'challenge' },
    { text: 'Lëre grupin të shohë kohën e ekranit për sot.', category: 'risky' },
    { text: 'Sillhu sikur po i jep çmim dikujt në dhomë.', category: 'funny' },
    { text: 'Haj një lugë gjalp kikiriku dhe provo të thuash "toy boat" 5 herë shpejt.', category: 'challenge' },
    { text: 'Dërgoji dikujt "Duhet të flasim" pastaj menjëherë "për picën."', category: 'funny' },
    { text: 'Bëj imitimin tënd më të mirë të një reporteri lajmesh duke dhënë lajme të këqija.', category: 'funny' },
    { text: 'Thuaj diçka që nuk e ke thënë kurrë me zë të lartë për personin në të djathtën tënde.', category: 'friendship' },
    { text: 'Bëj 10 squat jumps.', category: 'challenge' },
    { text: 'Lëre grupin të shohë kërkimet e tua të fundit (vetëm një person).', category: 'risky' },
    { text: 'Fol me theks italian për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj një interpretim dramatik të marrjes së lajmeve të këqija.', category: 'funny' },
    { text: 'Dërgoi një miku një mesazh zanor duke thënë se e vlerëson.', category: 'friendship' },
    { text: 'Mbaj një pozë yoga për 45 sekonda.', category: 'challenge' },
    { text: 'Lexo subtitlin e fundit të Instagram me zë të lartë.', category: 'risky' },
    { text: 'Sillhu si udhërrëfyes muzeu duke përshkruar dhomën.', category: 'funny' },
    { text: 'Bëj 15 jumping jacks prapa.', category: 'challenge' },
    { text: 'Lëre grupin të zgjedhë një filter; bëj selfie dhe vendose si sfond për 1 orë.', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një prindi të zhgënjyer.', category: 'funny' },
    { text: 'Jepi të gjithëve një gjë që ke mësuar nga personi në të majtën tënde.', category: 'friendship' },
    { text: 'Haj një ëmbëlsirë dhe përshkruaj shijen me detaje të mëdha.', category: 'funny' },
    { text: 'Mbaj plankun 20 sekonda.', category: 'challenge' },
    { text: 'Dërgoji një kontakti "Je i/e mrekullueshëm/e" pa kontekst.', category: 'friendship' },
    { text: 'Fol si robot për 3 raunde të ardhshme.', category: 'funny' },
    { text: 'Lëre dikë të zgjedhë historinë tënde të ardhshme në Instagram.', category: 'risky' },
    { text: 'Bëj një lexim dramatik të një mesazhi që ke marrë këtë javë.', category: 'funny' },
    { text: 'Bëj 10 lunges në çdo këmbë.', category: 'challenge' },
    { text: 'Telefono një mik dhe këndo një rresht të një kënge që zgjedhin ata.', category: 'challenge' },
    { text: 'Sillhu si komentator sportiv për dikë që ecën nëpër dhomë.', category: 'funny' },
    { text: 'Lëre grupin të zgjedhë një status të vjetër; e posto sërish.', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të dikujt të famshëm (grupi merr me mend).', category: 'funny' },
    { text: 'Thuaj një gjë që do të bëje për secilin person nëse nevojitet ndihmë.', category: 'friendship' },
    { text: 'Bëj 15 burpees (versioni i modifikuar është i lejuar).', category: 'challenge' },
    { text: 'Lexo gjënë e fundit që ke kopjuar në clipboard me zë të lartë.', category: 'risky' },
    { text: 'Fol me theks gjerman për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj një kërcim 30-sekondshe për një këngë që zgjedh grupi.', category: 'challenge' },
    { text: 'Dërgoji mikut tënd më të mirë një shaka të brendshme vetëm për ju të dy.', category: 'friendship' },
    { text: 'Sillhu si bibliotekar dhe shhh-o të gjithë për 30 sekonda.', category: 'funny' },
    { text: 'Lëre grupin të shohë 5 aplikacionet e tua më të përdorura.', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një personi të frikësuar në një film horror.', category: 'funny' },
    { text: 'Bëj një tost për grupin sikur je në një dasmë.', category: 'friendship' },
    { text: 'Bëj 20 crunches.', category: 'challenge' },
    { text: 'Dërgoji dikujt "Kujto atë gjë?" (mos shpjego).', category: 'funny' },
    { text: 'Fol vetëm me përshkrime emoji për raundin e ardhshëm.', category: 'funny' },
    { text: 'Lëre dikë të zgjedhë statusin tënd të ardhshëm në WhatsApp ose Messenger.', category: 'risky' },
    { text: 'Bëj një rikrijim dramatik të fitimit të lotarisë.', category: 'funny' },
    { text: 'Bëj 30 sekonda vrapim në vend me gjunjë lart.', category: 'challenge' },
    { text: 'Jepi personit në të djathtën tënde një kujtim që ke me të.', category: 'friendship' },
    { text: 'Sillhu si gjyqtar dhe "jep verdikt" ndaj dikujt në dhomë.', category: 'funny' },
    { text: 'Lexo kërkimin tënd të fundit në Google me zë të lartë.', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një teoricieni të konspiracionit.', category: 'funny' },
    { text: 'Thuaj "Të vlerësoj" për secilin person në dhomë me kontakt vizual.', category: 'friendship' },
    { text: 'Haj diçka të thartë dhe mbaj fytyrën e drejtë për 10 sekonda.', category: 'challenge' },
    { text: 'Lëre grupin të shkruajë një tweet për ty; e posto.', category: 'risky' },
    { text: 'Fol me theks spanjoll për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj 15 shtytje (shtytjet e gjurit numërohen).', category: 'challenge' },
    { text: 'Telefono një mik dhe thuaj "Sapo po mendoja për ty" pastaj flisni 1 min.', category: 'friendship' },
    { text: 'Bëj një lexim dramatik të një njoftimi që ke marrë sot.', category: 'funny' },
    { text: 'Lëre dikë të shfletojë listën e dëgjuar rishtas në Spotify ose Apple Music.', category: 'risky' },
    { text: 'Sillhu si terapist dhe jepju grupit një "seancë" për 1 minutë.', category: 'funny' },
    { text: 'Bëj 20 toe touches.', category: 'challenge' },
    { text: 'Dërgoji një anëtari familje një fakt rastësor që ke mësuar sot.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një ylli të reality show.', category: 'funny' },
    { text: 'Lëre grupin të zgjedhë një foto nga ruli i kamerës për ta postuar si histori.', category: 'risky' },
    { text: 'Fol me theks skocez për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj 10 sumo squats.', category: 'challenge' },
    { text: 'Jepu të gjithëve një nofkë bazuar në personalitetin e tyre dhe përdore për 2 raunde.', category: 'funny' },
    { text: 'Lexo gjënë e fundit që ke pëlqyer ose reaguar ndaj saj në rrjete sociale me zë të lartë.', category: 'risky' },
    { text: 'Bëj një interpretim dramatik të zbulimit që ke një adhurues/e sekret.', category: 'funny' },
    { text: 'Jepi grupit një mënyrë me të cilën secili të ka ndihmuar.', category: 'friendship' },
    { text: 'Bëj 30 sekonda kërcimi sikur askush nuk të shikon.', category: 'challenge' },
    { text: 'Dërgoji një miku një mesazh zanor me një shaka të keqe.', category: 'funny' },
    { text: 'Lëre grupin të zgjedhë foton tënde të profilit për 48 orë.', category: 'risky' },
    { text: 'Sillhu si gjyqtar dhe jep "dënime" për krime të pafajshme.', category: 'funny' },
    { text: 'Bëj 15 leg raises.', category: 'challenge' },
    { text: 'Thuaj një gjë për të cilën je mirënjohës/e për secilin person.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një YouTuberi duke bërë intro.', category: 'funny' },
    { text: 'Lëre dikë të dërgojë një mesazh nga telefoni yt tek kontakti që zgjedhin (ti aprovoë tekstin).', category: 'risky' },
    { text: 'Fol me theks australian për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj 20 rrethe krahësh në çdo drejtim.', category: 'challenge' },
    { text: 'Telefono një mik dhe bëj imitimin tënd të tij/saj (ai/ajo duhet ta marrë me mend).', category: 'funny' },
    { text: 'Lexo mesazhin e fundit të dërguar mikut tënd më të mirë me zë të lartë.', category: 'risky' },
    { text: 'Bëj një rikrijim dramatik të rutinës sate të mëngjesit në 30 sekonda.', category: 'funny' },
    { text: 'Jepi personit në të majtën tënde një kompliment autentik që nuk e ka dëgjuar kurrë.', category: 'friendship' },
    { text: 'Bëj 10 inchworms.', category: 'challenge' },
    { text: 'Lëre grupin të zgjedhë një këngë; ti lip-syncon 30 sekondat e para.', category: 'funny' },
    { text: 'Sillhu si prezantues i emisionit të takimeve dhe prezanto të gjithë si konkurrentë.', category: 'funny' },
    { text: 'Posto një histori me sondazh; grupi zgjedh pyetjen dhe opsionet.', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një mësuesi duke dhënë leksion.', category: 'funny' },
    { text: 'Thuaj "Ti ke rëndësi për mua" për secilin person në dhomë.', category: 'friendship' },
    { text: 'Bëj 15 skater jumps.', category: 'challenge' },
    { text: 'Dërgoji dikujt "Kam nevojë për mendimin tënd" pastaj dërgoji një pyetje budallaqe.', category: 'funny' },
    { text: 'Lëre dikë të shohë listën e thirrjeve të fundit.', category: 'risky' },
    { text: 'Fol me theks nga Nju Jorku për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj një "Ted Talk" 1-minutësh mbi një temë që zgjedh grupi.', category: 'challenge' },
    { text: 'Jepi të gjithëve një gjë që admiron tek personi në të djathtën e tyre.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një prezantuesi infomercial.', category: 'funny' },
    { text: 'Lëre grupin të zgjedhë një subtitle për postin tënd të ardhshëm.', category: 'risky' },
    { text: 'Bëj 20 heel taps.', category: 'challenge' },
    { text: 'Telefono një mik dhe i trego një gjë që do tek ai/ajo.', category: 'friendship' },
    { text: 'Sillhu si ankandar dhe "shit" një objekt në dhomë.', category: 'funny' },
    { text: 'Lexo memën e fundit që ke dërguar me zë të lartë.', category: 'risky' },
    { text: 'Bëj një lexim dramatik të një reklame që ke parë sot.', category: 'funny' },
    { text: 'Bëj 10 tuck jumps (ose high jumps nëse është më e lehtë).', category: 'challenge' },
    { text: 'Lëre grupin të zgjedhë një fjalë; nuk mund ta thuash për 3 raunde.', category: 'challenge' },
    { text: 'Thuaj një mënyrë me të cilën secili të ka bërë të buzëqeshësh.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një prezantuesi podkasti.', category: 'funny' },
    { text: 'Dërgoji një kontakti "Duhet të takohemi së shpejti" (grupi zgjedh kë).', category: 'risky' },
    { text: 'Fol me theks rus për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj 15 lunges anash në çdo anë.', category: 'challenge' },
    { text: 'Bëj një "fjalim diplomimi" për grupin në 30 sekonda.', category: 'funny' },
    { text: 'Lëre dikë të shfletojë "likes" në TikTok ose Reels për 20 sekonda.', category: 'risky' },
    { text: 'Sillhu si kamarier dhe merr "porosinë" e të gjithëve për një menu imagjinare.', category: 'funny' },
    { text: 'Bëj 20 shoulder taps në pozicion planku.', category: 'challenge' },
    { text: 'Dërgoji një miku "Ti je njëri/a nga njerëzit e mi të preferuar" pa kontekst.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një antagonisti duke bërë monolog.', category: 'funny' },
    { text: 'Lexo postin ose tweetin tënd të fundit me zë të lartë.', category: 'risky' },
    { text: 'Bëj një interpretim dramatik të marrjes së lajmeve të mira.', category: 'funny' },
    { text: 'Jepi personit në të majtën tënde një gjë që ke dashur gjithmonë t\'ia tregosh.', category: 'friendship' },
    { text: 'Bëj 30 sekonda kërcim litari (litari imagjinar është i lejuar).', category: 'challenge' },
    { text: 'Lëre grupin të zgjedhë një këngë të turpshme; ti këndon refrenet.', category: 'funny' },
    { text: 'Sillhu si shkencëtar dhe "shpjego" lojën për grupin.', category: 'funny' },
    { text: 'Posto një histori duke kërkuar një pyetje që shkruan grupi.', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të uljes së superheroit.', category: 'funny' },
    { text: 'Thuaj "Faleminderit që je këtu" për secilin person.', category: 'friendship' },
    { text: 'Bëj 10 lunges prapa në çdo këmbë.', category: 'challenge' },
    { text: 'Telefono dikë dhe thuaj "Po luaj një lojë dhe ti je pjesë e saj" pastaj shpjego.', category: 'funny' },
    { text: 'Lëre grupin të shohë statistikat e baterisë dhe hapësirës.', category: 'risky' },
    { text: 'Fol me theks jamaikan për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj 15 mbajtje supermani (shtrirë barkut, krahë dhe këmbë ngritur).', category: 'challenge' },
    { text: 'Jepi të gjithëve një "çmim" dhe prezantoje dramatikisht.', category: 'friendship' },
    { text: 'Bëj një lexim dramatik të parashikimit të motit për dhomën.', category: 'funny' },
    { text: 'Lëre dikë të zgjedhë çfarë ndryshon statusin tënd.', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo u zgjua.', category: 'funny' },
    { text: 'Jepi grupit një gjë që nuk do ta ndryshonje kurrë tek secili person.', category: 'friendship' },
    { text: 'Bëj 20 flutter kicks.', category: 'challenge' },
    { text: 'Dërgoji një kontakti "Po mendoj për ty" me një emoji rastësor.', category: 'friendship' },
    { text: 'Sillhu si trajner duke bërë një fjalim në gjysmë ndeshje.', category: 'funny' },
    { text: 'Lexo gjënë e fundit që ke ruajtur ose shënuar me zë të lartë.', category: 'risky' },
    { text: 'Bëj një monolog dramatik 45-sekondshe për një sanduiç.', category: 'funny' },
    { text: 'Bëj 10 burpees me duartrokitje në krye.', category: 'challenge' },
    { text: 'Lëre grupin të zgjedhë një frazë; e thua me 5 thekse të ndryshme.', category: 'funny' },
    { text: 'Thuaj një gjë për të cilën je krenar/e tek secili person.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo mori lajme të këqija.', category: 'funny' },
    { text: 'Dërgoji një miku një mesazh zanor me një imitim të tmerrshëm të tij/saj.', category: 'funny' },
    { text: 'Lëre grupin të shohë kalendarin tënd për këtë javë.', category: 'risky' },
    { text: 'Fol me theks indian për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj 15 glute bridges.', category: 'challenge' },
    { text: 'Telefono një mik dhe thuaj "Je i/e mrekullueshëm/e" pastaj mbyll ose vazhdo.', category: 'friendship' },
    { text: 'Sillhu si DJ dhe "hedh ritmin" për dhomën.', category: 'funny' },
    { text: 'Lexo kujtuesin ose etiketën e fundit të alarmit me zë të lartë.', category: 'risky' },
    { text: 'Bëj një rikrijim dramatik të rënies së telefonit.', category: 'funny' },
    { text: 'Bëj 20 bicycle crunches.', category: 'challenge' },
    { text: 'Jepi të gjithëve një mënyrë me të cilën personi në të djathtën e tyre ka ndikuar mbi ty.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një personi në tren lëvizës.', category: 'funny' },
    { text: 'Lëre grupin të zgjedhë një kontakt; u dërgon një mesazh që shkruan grupi.', category: 'risky' },
    { text: 'Fol me theks nga Bostoni për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj 30 sekonda shadow boxing.', category: 'challenge' },
    { text: 'Bëj një fjalim "Gjendja e Bashkimit" për lojën.', category: 'funny' },
    { text: 'Posto një foto që zgjedh grupi nga galeria (pa fytyra nëse nevojitet).', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo mori lajme të shkëlqyera.', category: 'funny' },
    { text: 'Thuaj "Jam i/e lumtur që je në jetën time" për secilin person.', category: 'friendship' },
    { text: 'Bëj 10 sprawls.', category: 'challenge' },
    { text: 'Dërgoji dikujt "Pyetje e shpejtë" pastaj dërgoji diçka rastësor.', category: 'funny' },
    { text: 'Lëre dikë të lexojë shënimin ose kujtuesin tënd të fundit.', category: 'risky' },
    { text: 'Sillhu si prezantues i emisionit talente dhe prezanto lojtarin e ardhshëm.', category: 'funny' },
    { text: 'Bëj 15 ngritje këmbësh (shtrirë).', category: 'challenge' },
    { text: 'Jepi personit në të majtën tënde çfarë do të bëje nëse të nevojiteshe në orën 3 të mëngjesit.', category: 'friendship' },
    { text: 'Bëj një lexim dramatik të një recete.', category: 'funny' },
    { text: 'Lëre grupin të zgjedhë subtitlin tënd të ardhshëm në Instagram.', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo pa një fantazmë.', category: 'funny' },
    { text: 'Thuaj një gjë që do të bëje për të bërë ditën e secilit person më të mirë.', category: 'friendship' },
    { text: 'Bëj 20 squat holds.', category: 'challenge' },
    { text: 'Telefono një mik dhe bëj një imitim 30-sekondshe të një të famshmi.', category: 'funny' },
    { text: 'Lexo kërkimin tënd të fundit në YouTube ose video me zë të lartë.', category: 'risky' },
    { text: 'Fol me theks jugor të ngadalë për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj 10 box jumps (në dysheme ose sipërfaqe të ulët).', category: 'challenge' },
    { text: 'Jepi të gjithëve një "superfuqi" bazuar në personalitetin e tyre.', category: 'friendship' },
    { text: 'Bëj një interpretim dramatik të hapjes së një dhurate që do.', category: 'funny' },
    { text: 'Lëre grupin të zgjedhë një këngë; ti e gumëzhis dhe ata marrin me mend.', category: 'funny' },
    { text: 'Sillhu si prezantues talk show dhe "intervistoë" personin në të djathtën tënde.', category: 'funny' },
    { text: 'Dërgoji një kontakti një mesazh me kompliment (grupi aprovoë).', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo mbaroi një maraton.', category: 'funny' },
    { text: 'Thuaj një gjë që ke të përbashkët me secilin person.', category: 'friendship' },
    { text: 'Bëj 15 calf raises.', category: 'challenge' },
    { text: 'Lëre dikë të shohë 3 skedarët e fundit të shkarkuar.', category: 'risky' },
    { text: 'Bëj një komentim "dokumentar" 1-minutësh për dhomën.', category: 'funny' },
    { text: 'Bëj 20 jumping jacks duke thënë alfabetin.', category: 'challenge' },
    { text: 'Jepi grupit një kujtim që ke me secilin person.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo humbi çelësat.', category: 'funny' },
    { text: 'Posto një histori me pyetje; grupi shkruan pyetjen.', category: 'risky' },
    { text: 'Fol me theks kanadez për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj 10 v-ups ose sit-ups.', category: 'challenge' },
    { text: 'Dërgoji një anëtari familje "Të dua" me një arsye specifike.', category: 'friendship' },
    { text: 'Sillhu si prezantues i reality show dhe komentoë raundin e ardhshëm.', category: 'funny' },
    { text: 'Lexo gjënë e fundit që ke ndarë në rrjete sociale me zë të lartë.', category: 'risky' },
    { text: 'Bëj një rikrijim dramatik të goditjes së gishtit të këmbës.', category: 'funny' },
    { text: 'Bëj 15 wall push-ups.', category: 'challenge' },
    { text: 'Lëre grupin të të japë një "mision" për ta kryer para se të mbarojë loja.', category: 'challenge' },
    { text: 'Thuaj "Ti bën ndryshim" për secilin person.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo mori një promovim.', category: 'funny' },
    { text: 'Dërgoji një miku një mesazh zanor me një fakt rastësor.', category: 'funny' },
    { text: 'Lëre dikë të zgjedhë përditësimin tënd të ardhshëm të statusit.', category: 'risky' },
    { text: 'Fol me theks mbretëror britanik për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj 20 ngritje krahësh (përpara dhe anash).', category: 'challenge' },
    { text: 'Bëj një "eulogji" për një objekt në dhomë (qesharak).', category: 'funny' },
    { text: 'Jepi personit në të djathtën tënde një gjë që ke dashur gjithmonë ta bësh me të.', category: 'friendship' },
    { text: 'Bëj një lexim dramatik të një përshkrimi produkti.', category: 'funny' },
    { text: 'Lëre grupin të shohë pamjen e ekranit tënd të fundit.', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo mori një gjobë parkimi.', category: 'funny' },
    { text: 'Thuaj një gjë që respekton tek secili person.', category: 'friendship' },
    { text: 'Bëj 10 knee push-ups.', category: 'challenge' },
    { text: 'Telefono një mik dhe thuaj "Je i/e mrekullueshëm/e" pastaj shpjego pse (30 sek).', category: 'friendship' },
    { text: 'Sillhu si prezantues i emisionit të gatimit me një pjatë imagjinare.', category: 'funny' },
    { text: 'Lexo temën e emailit të fundit të dërguar (vetëm temën) me zë të lartë.', category: 'risky' },
    { text: 'Bëj një monolog dramatik 30-sekondshe për çorapet.', category: 'funny' },
    { text: 'Bëj 15 twisted anash duke qëndruar.', category: 'challenge' },
    { text: 'Lëre grupin të zgjedhë një sfidë për ty që ta bësh brenda 24 orëve.', category: 'challenge' },
    { text: 'Jepi të gjithëve një mënyrë me të cilën secili të ka bërë të qeshësh.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo pa shtypjen e tij/saj.', category: 'funny' },
    { text: 'Dërgoji një kontakti një shaka babi (grupi mund ta sugjerojë).', category: 'funny' },
    { text: 'Lëre dikë të shohë aplikacionet e fundit.', category: 'risky' },
    { text: 'Fol me theks pirate për 3 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj 20 step-ups (në një shkallë ose sipërfaqe të ulët).', category: 'challenge' },
    { text: 'Bëj një "fjalim Oscar" duke falënderuar të gjithë në dhomë.', category: 'friendship' },
    { text: 'Bëj një interpretim dramatik të gjetjes së një merimange.', category: 'funny' },
    { text: 'Posto një histori me një këngë që zgjedh grupi.', category: 'risky' },
    { text: 'Sillhu si prezantues podkasti dhe intervistoë personin në të majtën tënde.', category: 'funny' },
    { text: 'Bëj 10 reverse crunches.', category: 'challenge' },
    { text: 'Thuaj "Jam me fat që të njoh" për secilin person.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo mori një dhuratë.', category: 'funny' },
    { text: 'Lexo shënimin tënd të fundit me zë të lartë.', category: 'risky' },
    { text: 'Bëj një lexim dramatik të një tabelë rruge ose etikete në dhomë.', category: 'funny' },
    { text: 'Bëj 15 hip raises.', category: 'challenge' },
    { text: 'Jepi personit në të majtën tënde një gjë që nuk do ta harrosh kurrë për të.', category: 'friendship' },
    { text: 'Lëre grupin të zgjedhë një frazë; e thua si trailer filmi.', category: 'funny' },
    { text: 'Dërgoji dikujt "Ti me bëre ditën" (kur nuk ta ka bërë).', category: 'funny' },
    { text: 'Lëre dikë të zgjedhë çfarë postoni tjetër (foto ose tekst).', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo u zgjua nga gjumi i mesditës.', category: 'funny' },
    { text: 'Thuaj një gjë për të cilën do ta falënderoje secilin person.', category: 'friendship' },
    { text: 'Bëj 20 rrethe me këmbë (shtrirë).', category: 'challenge' },
    { text: 'Telefono një mik dhe bëj një imitim 20-sekondshe të një mësuesi.', category: 'funny' },
    { text: 'Lexo gjënë e fundit që ke googluar me zë të lartë.', category: 'risky' },
    { text: 'Fol me theks antagonisti për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj 10 bird dogs (krah dhe këmbë të kundërt).', category: 'challenge' },
    { text: 'Jepu të gjithëve një "titull" (p.sh. "Kryetari i Argëtimit") dhe përdore për 2 raunde.', category: 'friendship' },
    { text: 'Bëj një rikrijim dramatik të rrëshqitjes mbi akull.', category: 'funny' },
    { text: 'Lëre grupin të zgjedhë një pyetje; e posto si status.', category: 'risky' },
    { text: 'Sillhu si prezantues i lojës dhe shpjego raundin e ardhshëm.', category: 'funny' },
    { text: 'Bëj 15 dead bugs.', category: 'challenge' },
    { text: 'Dërgoji një miku "Jam mirënjohës/e për ty" me një arsye të shkurtër.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo mori një mesazh nga shtypja e tij/saj.', category: 'funny' },
    { text: 'Lëre dikë të shohë 5 emojitë e fundit që ke përdorur.', category: 'risky' },
    { text: 'Bëj një monolog dramatik 45-sekondshe për motin.', category: 'funny' },
    { text: 'Bëj 20 marshim në vend me gjunjë lart.', category: 'challenge' },
    { text: 'Jepi grupit një gjë që do të bëje për të ngushëlluar secilin person.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo fitoi një lojë.', category: 'funny' },
    { text: 'Posto një histori me një foto që zgjedh grupi.', category: 'risky' },
    { text: 'Fol me zë gjumi për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj 10 shtrirje cat-cow (yoga).', category: 'challenge' },
    { text: 'Thuaj "Ti ke rëndësi për mua" për secilin person.', category: 'friendship' },
    { text: 'Sillhu si prezantues i emisionit çmimesh dhe jep një çmim dhomës.', category: 'funny' },
    { text: 'Lexo listën e fundit muzikore ose albumin e luajtur me zë të lartë.', category: 'risky' },
    { text: 'Bëj një interpretim dramatik të marrjes së një surprize feste.', category: 'funny' },
    { text: 'Bëj 15 standing leg curls (kickbacks).', category: 'challenge' },
    { text: 'Lëre grupin të zgjedhë një fjalë; nuk mund të thuash "po" ose "jo" për 2 raunde.', category: 'challenge' },
    { text: 'Jepi personit në të djathtën tënde një gjë që admironë tek personaliteti i tij/saj.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo hëngri diçka pikante.', category: 'funny' },
    { text: 'Dërgoji një kontakti një mesazh zanor me një shaka (grupi aprovoë).', category: 'risky' },
    { text: 'Fol me zë të ulët për 3 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj 20 rrethe kyçesh në çdo drejtim.', category: 'challenge' },
    { text: 'Bëj një "konferencë shtypi" sikur sapo ke fituar diçka të madhe.', category: 'funny' },
    { text: 'Lëre dikë të zgjedhë llojin e historisë tënde të ardhshme në Instagram (sondazh, pyetje, etj.).', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo u kap duke gënjyer.', category: 'funny' },
    { text: 'Thuaj një gjë që do të bëje për të mbështetur secilin person.', category: 'friendship' },
    { text: 'Bëj 10 windmills (goditje gishti të këmbës).', category: 'challenge' },
    { text: 'Telefono një mik dhe thuaj "Duhet të të tregoj diçka" pastaj thuaj "Je i/e shkëlqyeshëm/e."', category: 'funny' },
    { text: 'Lexo emrin e fundit të alarmit me zë të lartë.', category: 'risky' },
    { text: 'Bëj një lexim dramatik të një etikete ushqimore.', category: 'funny' },
    { text: 'Bëj 15 rrotatime qafe (të buta).', category: 'challenge' },
    { text: 'Jepi të gjithëve një mënyrë me të cilën secili të ka ndihmuar të rritesh.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo mori një promovim.', category: 'funny' },
    { text: 'Lëre grupin të shkruajë një mesazh të shkurtër; e dërgon te dikush që zgjedhin.', category: 'risky' },
    { text: 'Sillhu si prezantues dokumentari dhe komentoë dhomën për 1 minutë.', category: 'funny' },
    { text: 'Bëj 20 rrethe kyçesh.', category: 'challenge' },
    { text: 'Dërgoji dikujt "Ti je njëri/a nga të mirët" pa kontekst.', category: 'friendship' },
    { text: 'Bëj një rikrijim dramatik të reagimit tënd ndaj një frikësimi.', category: 'funny' },
    { text: 'Lëre dikë të shohë 3 fotot e tua të fundit (mund t\'i turbullosh nëse nevojitet).', category: 'risky' },
    { text: 'Fol me zë fëmije të entuziazmuar për 2 raunde të ardhshme.', category: 'funny' },
    { text: 'Bëj 10 rrotatime shpatullash.', category: 'challenge' },
    { text: 'Thuaj "Të vlerësoj" për secilin person.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo mori një kompliment.', category: 'funny' },
    { text: 'Posto një histori me një "kjo apo ajo" që krijon grupi.', category: 'risky' },
    { text: 'Bëj një monolog dramatik 30-sekondshe për një stilolaps.', category: 'funny' },
    { text: 'Bëj 15 rrotullime trupi.', category: 'challenge' },
    { text: 'Jepi personit në të majtën tënde një gjë që do tek miqësia juaj.', category: 'friendship' },
    { text: 'Sillhu si prezantues i emisionit të mëngjesit dhe bëj "motin" për dhomën.', category: 'funny' },
    { text: 'Lexo kujtuesin tënd të fundit me zë të lartë.', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo mori shërbim të keq.', category: 'funny' },
    { text: 'Thuaj një gjë që do të bëje për të festuar secilin person.', category: 'friendship' },
    { text: 'Bëj 20 shtrirje krahësh.', category: 'challenge' },
    { text: 'Lëre grupin të zgjedhë një këngë; këndo një rresht me zë qesharak.', category: 'funny' },
    { text: 'Dërgoji një miku një mesazh me një citat pozitiv.', category: 'friendship' },
    { text: 'Lëre dikë të zgjedhë statusin tënd të ardhshëm në WhatsApp.', category: 'risky' },
    { text: 'Bëj një interpretim dramatik të gjetjes së parave në tokë.', category: 'funny' },
    { text: 'Bëj 10 shtrirje kuadricepsit (çdo këmbë).', category: 'challenge' },
    { text: 'Jepi grupit një gjë që ke mësuar nga secili person.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo mori porosi të gabuar.', category: 'funny' },
    { text: 'Lexo titullin e ngjarjes së fundit në kalendarit me zë të lartë.', category: 'risky' },
    { text: 'Fol me zë si trailer filmi dramatik për raundin e ardhshëm.', category: 'funny' },
    { text: 'Bëj 15 shtrirje hamstringësh.', category: 'challenge' },
    { text: 'Bëj një adresim "Gjendja e Dhomës" sikur je një udhëheqës.', category: 'funny' },
    { text: 'Lëre grupin të zgjedhë një pyetje; i përgjigjeshe në historinë tënde.', category: 'risky' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo mori lajme të mira.', category: 'funny' },
    { text: 'Thuaj "Ti i përket këtu" për secilin person.', category: 'friendship' },
    { text: 'Bëj 20 rrethe ijesh.', category: 'challenge' },
    { text: 'Telefono një mik dhe thuaj "Doja vetëm të të thoja përshëndetje" dhe bisedoni 1 minutë.', category: 'friendship' },
    { text: 'Sillhu si prezantues i emisionit udhëtimeve dhe "bëj turin" e dhomës.', category: 'funny' },
    { text: 'Lexo shënimin tënd të fundit të shtypur me zë të lartë.', category: 'risky' },
    { text: 'Bëj një rikrijim dramatik të harresës së emrit të dikujt.', category: 'funny' },
    { text: 'Bëj 10 shtrirje figure-four (çdo anë).', category: 'challenge' },
    { text: 'Jepi personit në të djathtën tënde një gjë që do ta mbash gjithmonë mend.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo mori një "like".', category: 'funny' },
    { text: 'Lëre grupin të zgjedhë një frazë; e thua në mënyrë dramatike.', category: 'funny' },
    { text: 'Posto një histori me një numërim mbrapsht ose timer që vendos grupi.', category: 'risky' },
    { text: 'Bëj 15 rrotullime kurrizore (ulur).', category: 'challenge' },
    { text: 'Thuaj një gjë që do të bëje për të bërë secilin person të ndihet special.', category: 'friendship' },
    { text: 'Bëj imitimin tënd më të mirë të një personi që sapo mori një kërkesë ndjekjeje.', category: 'funny' },
    { text: 'Dërgoji një miku një mesazh zanor duke thënë se i mungon.', category: 'friendship' },
    { text: 'Lëre dikë të shohë 5 kërkimet e tua të fundit.', category: 'risky' },
    { text: 'Fol me zë monoton për 2 raunde të ardhshme.', category: 'funny' },
  ];
  
  module.exports = { truths, dares };