const truths = [
    { text: 'En büyük korkunuz nedir?', category: 'general' },
    { text: 'Başınıza gelen en utanç verici şey nedir?', category: 'funny' },
    { text: 'Planlardan kaçmak için hiç yalan söylediniz mi?', category: 'general' },
    { text: 'Gizli zevkiniz nedir?', category: 'general' },
    { text: 'İlk aşkınız kimdi?', category: 'friendship' },
    { text: 'Bir arkadaşınız hakkında söylediğiniz en kötü şey neydi?', category: 'risky' },
    { text: 'Hiç sınavda kopya çektiniz mi?', category: 'general' },
    { text: 'En büyük pişmanlığınız nedir?', category: 'general' },
    { text: 'Hiç bir arkadaşınızın partnerine ilgi duydunuz mu?', category: 'risky' },
    { text: 'İnandığınız en saçma şey nedir?', category: 'funny' },
    { text: 'En mantıksız korkunuz nedir?', category: 'general' },
    { text: 'Hiç bir hediyeyi beğenmiş gibi davrandınız mı?', category: 'funny' },
    { text: 'Yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Şu an gizlice kimi beğeniyorsunuz?', category: 'risky' },
    { text: 'Kimseye söylemediğiniz bir şey var mı?', category: 'risky' },
    { text: 'Hiç birinin kalbini kırdınız mı?', category: 'friendship' },
    { text: 'En utanç verici alışkanlığınız nedir?', category: 'funny' },
    { text: 'Hiç dedikodu yaydınız mı?', category: 'risky' },
    { text: 'Katıldığınız en kötü randevu neydi?', category: 'general' },
    { text: 'Hiç aşık oldunuz mu?', category: 'friendship' },
    { text: 'En büyük güvensizliğiniz nedir?', category: 'general' },
    { text: 'Hiç bir şey çaldınız mı?', category: 'risky' },
    { text: 'Hâlâ yaptığınız en çocukça şey nedir?', category: 'funny' },
    { text: 'Hiç ebeveynlerinize yalan söylediniz mi?', category: 'general' },
    { text: 'Gizli yetenekleriniz nedir?', category: 'general' },
    { text: 'Hiç ölüme yakın bir deneyim yaşadınız mı?', category: 'general' },
    { text: 'Sarhoşken yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Hiç reddedildiniz mi?', category: 'friendship' },
    { text: 'Sizi en çok rahatsız eden şey nedir?', category: 'general' },
    { text: 'Hiç yalan söylerken yakalandınız mı?', category: 'funny' },
    { text: 'Yaşayacak bir gününüz kalsaydı ne yapardınız?', category: 'challenge' },
    { text: 'Başınızın en çok belaya girdiği an neydi?', category: 'risky' },
    { text: 'Hiç tek gecelik ilişki yaşadınız mı?', category: 'risky' },
    { text: 'En tartışmalı görüşünüz nedir?', category: 'challenge' },
    { text: 'Hiç bir arkadaşınıza ihanet ettiniz mi?', category: 'risky' },
    { text: 'En büyük sırrınız nedir?', category: 'risky' },
    { text: 'Hiç fiziksel bir kavgaya karıştınız mı?', category: 'risky' },
    { text: 'Şimdiye kadar yaptığınız en kötü iş neydi?', category: 'general' },
    { text: 'Hiç gözaltına alındınız mı?', category: 'risky' },
    { text: 'Bir daha asla yapmayacağınız bir şey var mı?', category: 'general' },
    { text: 'Çalma listenizdeki en utanç verici şarkı hangisi?', category: 'funny' },
    { text: 'Hiç bir öğretmeninize veya amiriinize ilgi duydunuz mu?', category: 'risky' },
    { text: 'Şimdiye kadar söylediğiniz en kötü yalan nedir?', category: 'risky' },
    { text: 'Hiç yapmamanız gereken bir şey yaparken yakalandınız mı?', category: 'general' },
    { text: 'En utanç verici çocukluk anınız nedir?', category: 'funny' },
    { text: 'Hiç birini hayatınızdan çıkardınız mı?', category: 'friendship' },
    { text: 'Şimdiye kadar gördüğünüz en tuhaf rüya neydi?', category: 'general' },
    { text: 'Hiç saklayamadığınız bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Şimdiye kadar yaptığınız en pervasız şey nedir?', category: 'risky' },
    { text: 'Hiç bir arkadaşınızın kardeşine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Gurur duyduğunuz ama hiç paylaşmadığınız bir şey var mı?', category: 'general' },
    { text: 'Bir şeyden kaçınmak için hiç hasta numarası yaptınız mı?', category: 'funny' },
    { text: 'Bir insanda en çok neyi itici bulursunuz?', category: 'general' },
    { text: 'Hiç randevuda terk edildiniz mi?', category: 'friendship' },
    { text: 'Saçma bir şeye harcadığınız en yüksek para miktarı nedir?', category: 'general' },
    { text: 'Hiç kanunla başınız belaya girdi mi?', category: 'risky' },
    { text: 'Aldığınız en kötü hediye nedir?', category: 'funny' },
    { text: 'Hiç aynı anda iki kişiye aşık oldunuz mu?', category: 'risky' },
    { text: 'Yiyecekler hakkındaki en tartışmalı görüşünüz nedir?', category: 'challenge' },
    { text: 'Hiç özgeçmişinizde yalan söylediniz mi?', category: 'risky' },
    { text: 'Hâlâ zevk aldığınız en çocukça şey nedir?', category: 'funny' },
    { text: 'Hiç kötü biten bir arkadaşlığınız oldu mu?', category: 'friendship' },
    { text: 'Kimse sizi yargılamasa ne yapardınız?', category: 'challenge' },
    { text: 'Hiç birine bakıp bakarken yakalandınız mı?', category: 'funny' },
    { text: 'En mantıksız sizi rahatsız eden şey nedir?', category: 'general' },
    { text: 'Hiç tek taraflı bir arkadaşlığınız oldu mu?', category: 'friendship' },
    { text: 'Birinin arkasından söylediğiniz en kötü şey nedir?', category: 'risky' },
    { text: 'Birinden kaçınmak için hiç meşgul numarası yaptınız mı?', category: 'funny' },
    { text: 'Gizli zevkiniz olan dizi veya film nedir?', category: 'general' },
    { text: 'Bu odadaki birine hiç ilgi duydunuz mu?', category: 'risky' },
    { text: 'Ebeveynlerinizin yaptığı en utanç verici şey nedir?', category: 'funny' },
    { text: 'Hiç garip bir durumda yakalandınız mı?', category: 'funny' },
    { text: 'Söylediğinize pişman olduğunuz bir şey var mı?', category: 'general' },
    { text: 'Hiç gizli bir hayranınız oldu mu?', category: 'friendship' },
    { text: 'En kötü alışkanlığınız nedir?', category: 'general' },
    { text: 'Hiç bir ilişkide "diğer kişi" oldunuz mu?', category: 'risky' },
    { text: 'Arama geçmişinizdeki en utanç verici şey nedir?', category: 'funny' },
    { text: 'Hiç tanımadığınız birini tanıyormuş gibi davrandınız mı?', category: 'funny' },
    { text: 'Gelecekle ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Utanç duyduğunuz bir ünlüye hiç ilgi duydunuz mu?', category: 'funny' },
    { text: 'Şimdiye kadar yaptığınız en bencil şey nedir?', category: 'risky' },
    { text: 'Hiç partnerinize yalan söylerken yakalandınız mı?', category: 'risky' },
    { text: 'Çekici bulduğunuz en tuhaf şey nedir?', category: 'challenge' },
    { text: 'Hiç bu odadaki biri hakkında rüya gördünüz mü?', category: 'risky' },
    { text: 'Kendinizle ilgili duyduğunuz en kötü dedikodu nedir?', category: 'general' },
    { text: 'Hiç yanlış olduğunu bildiğiniz bir ilişkide kaldınız mı?', category: 'friendship' },
    { text: 'Birini etkilemek için yaptığınız en utanç verici şey nedir?', category: 'funny' },
    { text: 'Hiç kendi kendinize konuşurken yakalandınız mı?', category: 'funny' },
    { text: 'Görünüşünüzle ilgili en büyük güvensizliğiniz nedir?', category: 'general' },
    { text: 'Hiç bir arkadaşlığı mahvedebilecek bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Şimdiye kadar yaptığınız en çocukça tartışma neydi?', category: 'funny' },
    { text: 'Hiç bir arkadaşınızın başarısına imrendiniz mi?', category: 'friendship' },
    { text: 'Şimdiye kadar verdiğiniz en kötü tavsiye nedir?', category: 'general' },
    { text: 'Hiç çok daha yaşlı ya da genç birine ilgi duydunuz mu?', category: 'risky' },
    { text: 'İşte veya okulda yaşadığınız en utanç verici an nedir?', category: 'funny' },
    { text: 'Çevrimiçi olarak aradığınız son şey neydi?', category: 'general' },
    { text: 'Hiç sahte kimlik kullandınız mı?', category: 'risky' },
    { text: 'Karaoke şarkınız nedir?', category: 'funny' },
    { text: 'Hiç burnunuzu karıştırırken yakalandınız mı?', category: 'funny' },
    { text: 'Sevdiğiniz en tuhaf yiyecek kombinasyonu nedir?', category: 'general' },
    { text: 'Hiç film izlerken ağladınız mı?', category: 'friendship' },
    { text: 'Geç kalmak için en çok kullandığınız bahane nedir?', category: 'general' },
    { text: 'Hiç toplum içinde kıyafet kazası yaşadınız mı?', category: 'funny' },
    { text: 'Satın alıp pişman olduğunuz son şey nedir?', category: 'general' },
    { text: 'Hiç çizgi film karakterine ilgi duydunuz mu?', category: 'funny' },
    { text: 'İlişkiler konusundaki en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç başkasının telefonunu karıştırdınız mı?', category: 'risky' },
    { text: 'Odanızdaki en utanç verici şey nedir?', category: 'funny' },
    { text: 'Hiç bitirmediğiniz bir kitabı okumuş gibi davrandınız mı?', category: 'funny' },
    { text: 'Gizli hobiniz nedir?', category: 'general' },
    { text: 'Hiç duşta şarkı söylerken yakalandınız mı?', category: 'funny' },
    { text: 'Şimdiye kadar yaptığınız en kötü saç kesimi neydi?', category: 'funny' },
    { text: 'Hiç bir iş arkadaşınıza ilgi duydunuz mu?', category: 'risky' },
    { text: 'Tuhaf biçimde iyi olduğunuz bir şey nedir?', category: 'general' },
    { text: 'Hiç yaptığınız bir şeyi kardeşinize yıktınız mı?', category: 'friendship' },
    { text: 'Çocukluğunuzdan en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç yanlış kişiye mesaj gönderdiniz mi?', category: 'risky' },
    { text: 'Aldığınız en tuhaf iltifat nedir?', category: 'general' },
    { text: 'Hiç gerçek gibi hissettiren bir rüya gördünüz mü?', category: 'general' },
    { text: 'Gizli atıştırmalığınız nedir?', category: 'general' },
    { text: 'Hiç masum bir yalanda yakalandınız mı?', category: 'funny' },
    { text: 'Geçirdiğiniz en kötü moda dönemi neydi?', category: 'funny' },
    { text: 'Hiç araç kullanırken kaza-ramak kaldı yaşadınız mı?', category: 'risky' },
    { text: 'Yüz yüze asla itiraf etmeyeceğiniz bir şey var mı?', category: 'challenge' },
    { text: 'Hiç bir arkadaşınızın eski sevgilisine ilgi duydunuz mu?', category: 'risky' },
    { text: 'En utanç verici otomatik düzeltme hatanız nedir?', category: 'funny' },
    { text: 'Birinden kaçınmak için hiç telefonda konuşuyormuş gibi davrandınız mı?', category: 'funny' },
    { text: 'Şimdiye kadar verdiğiniz en kötü hediye nedir?', category: 'general' },
    { text: 'Hiç utanç verici bir şey yaparken yakalandınız mı?', category: 'funny' },
    { text: 'Yaşlanmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç biriyle gizli el sıkışmanız oldu mu?', category: 'friendship' },
    { text: 'Hâlâ komik bulduğunuz en çocukça şey nedir?', category: 'funny' },
    { text: 'Hiç yaşınız hakkında yalan söylediniz mi?', category: 'risky' },
    { text: 'Şimdiye kadar uyduğunuz en kötü tavsiye nedir?', category: 'general' },
    { text: 'Hiç yeni tanıştığınız birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Bir partide yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç uyurken konuşurken yakalandınız mı?', category: 'funny' },
    { text: 'Şimdiye kadar yediğiniz en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç bir yalanla başlayan arkadaşlığınız oldu mu?', category: 'risky' },
    { text: 'Yargılanmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç uymak için sevmediğiniz bir şarkıyı seviyormuş gibi davrandınız mı?', category: 'funny' },
    { text: 'Yüksek sesle söylediğiniz en utanç verici şey nedir?', category: 'funny' },
    { text: 'Hiç bir arkadaşınızla gizli bir kodunuz oldu mu?', category: 'friendship' },
    { text: 'Aklınıza gelen en kötü buluşma fikri nedir?', category: 'general' },
    { text: 'Hiç kimse bakmıyor sanırken dans ederken yakalandınız mı?', category: 'funny' },
    { text: 'İndirdiğiniz son uygulama nedir?', category: 'general' },
    { text: 'Hiç nefret ettiğiniz bir lakabınız oldu mu?', category: 'funny' },
    { text: 'Bir ev arkadaşında sizi en çok rahatsız eden şey nedir?', category: 'general' },
    { text: 'Dikkat çekmek için hiç hasta numarası yaptınız mı?', category: 'funny' },
    { text: 'Şimdiye kadar yaptığınız en pervasız alışveriş nedir?', category: 'general' },
    { text: 'Hiç yalnızca bir kez gördüğünüz bir yabancıya ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Şimdiye kadar anlattığınız en kötü fıkra nedir?', category: 'funny' },
    { text: 'Hiç aynaya bakarken yakalandınız mı?', category: 'funny' },
    { text: 'Gizli teselli yiyeceğiniz nedir?', category: 'general' },
    { text: 'Hiç boyunuz veya kilonuz hakkında yalan söylediniz mi?', category: 'risky' },
    { text: 'Kardeşinizin yaptığı en utanç verici şey nedir?', category: 'funny' },
    { text: 'Hiç sevmediğiniz biri hakkında rüya gördünüz mü?', category: 'general' },
    { text: 'Birinden aldığınız en kötü alışkanlık nedir?', category: 'general' },
    { text: 'Hiç selfie çekerken yakalandınız mı?', category: 'funny' },
    { text: 'Başarısızlıkla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç yalnızca bir kişiye söylediğiniz bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Beğeni almak için yaptığınız en utanç verici şey nedir?', category: 'funny' },
    { text: 'Hiç anlamadığınız bir şakaya güler misiniz gibi davrandınız mı?', category: 'funny' },
    { text: 'Şimdiye kadar yaydığınız en kötü dedikodu nedir?', category: 'risky' },
    { text: 'Hiç bir kitap veya dizideki karaktere ilgi duydunuz mu?', category: 'funny' },
    { text: 'Beden eğitimi dersinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç evcil hayvanınızla insan gibi konuşurken yakalandınız mı?', category: 'funny' },
    { text: 'Çocukken inandığınız en tuhaf şey nedir?', category: 'funny' },
    { text: 'Hiç bir yanlış anlaşılma yüzünden biten arkadaşlığınız oldu mu?', category: 'friendship' },
    { text: 'Yalnız olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç meşgul değilken meşgulmuş gibi davrandınız mı?', category: 'funny' },
    { text: 'Tarayıcı geçmişinizdeki en utanç verici şey nedir?', category: 'risky' },
    { text: 'Hiç arabada şarkı söylerken yakalandınız mı?', category: 'funny' },
    { text: 'Kullandığınız veya duyduğunuz en kötü flört cümlesi nedir?', category: 'funny' },
    { text: 'Hiç sonunda anlattığınız bir sırrınız oldu mu?', category: 'risky' },
    { text: 'En mantıksız sizi rahatsız eden alışkanlık nedir?', category: 'general' },
    { text: 'Hiç aylak aylak gezerken çalışıyor numarası yaptınız mı?', category: 'funny' },
    { text: 'Dikkat çekmek için yaptığınız en utanç verici şey nedir?', category: 'funny' },
    { text: 'Hiç bir arkadaşınızın ilişkisine imrendiniz mi?', category: 'friendship' },
    { text: 'Şimdiye kadar yaptığınız en kötü moda seçimi nedir?', category: 'funny' },
    { text: 'Hiç sizi sevmeyen birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Bağlılıkla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç derste veya işte hayal kurarken yakalandınız mı?', category: 'funny' },
    { text: 'Çevrimiçi paylaştığınız en utanç verici şey nedir?', category: 'funny' },
    { text: 'Hiç nerede olduğunuz hakkında yalan söylediniz mi?', category: 'risky' },
    { text: 'Buradaki biri hakkında gördüğünüz en tuhaf rüya nedir?', category: 'challenge' },
    { text: 'Hiç kimseye söylemediğiniz gizli bir hayranınız oldu mu?', category: 'friendship' },
    { text: 'Bir aile toplantısında yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç bir fotoğrafta komik yüz yaparken yakalandınız mı?', category: 'funny' },
    { text: 'Öfkeliyken yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Hiç bir arkadaşınızın beğendiği birine ilgi duydunuz mu?', category: 'risky' },
    { text: 'Savunmasız olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç nefret ettiğiniz bir yemeği severmiş gibi davrandınız mı?', category: 'funny' },
    { text: 'Bir randevuda yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç kendi şakanıza gülerken yakalandınız mı?', category: 'funny' },
    { text: 'Planlardan kaçmak için söylediğiniz en kötü yalan nedir?', category: 'general' },
    { text: 'Hiç bitirdiğinize pişman olduğunuz bir arkadaşlığınız oldu mu?', category: 'friendship' },
    { text: 'Bir tatilde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç herkese açık bir yerde kendi kendinize konuşurken yakalandınız mı?', category: 'funny' },
    { text: 'Koleksiyonladığınız veya ettiğiniz en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç güç sahibi birine ilgi duydunuz mu?', category: 'risky' },
    { text: 'Reddedilmekle ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç izlemediğiniz bir filmi izlemiş gibi davrandınız mı?', category: 'funny' },
    { text: 'Bir düğünde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç asla yapmayacağım dediğiniz bir şeyi yaparken yakalandınız mı?', category: 'funny' },
    { text: 'Şimdiye kadar kullandığınız en kötü bahane nedir?', category: 'general' },
    { text: 'Hiç bir ilişkiyi değiştirebilecek bir sırrınız oldu mu?', category: 'risky' },
    { text: 'İş görüşmesinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç kardeşinize imrendiniz mi?', category: 'friendship' },
    { text: 'Kimse bakmıyorken yaptığınız en tuhaf şey nedir?', category: 'challenge' },
    { text: 'Hiç size uymayan birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Başarıyla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç birinden kaçmak için uyuyor numarası yaptınız mı?', category: 'funny' },
    { text: 'Bir restoranda yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç utanç verici bir şey izlerken yakalandınız mı?', category: 'funny' },
    { text: 'Dürtüyle aldığınız en kötü karar nedir?', category: 'general' },
    { text: 'Hâlâ sakladığınız bir sırrınız var mı?', category: 'risky' },
    { text: 'İlk randevunuzda yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç bir arkadaşınız hakkında bir şeyi en son öğrenen siz oldunuz mu?', category: 'friendship' },
    { text: 'En tuhaf alışkanlığınız nedir?', category: 'general' },
    { text: 'Hiç olmaması gereken birine ilgi duydunuz mu?', category: 'risky' },
    { text: 'Değişimle ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç güvensizken güvenli görünmeye çalıştınız mı?', category: 'funny' },
    { text: 'Bir pijama partisinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç utanç verici bir fotoğrafta yakalandınız mı?', category: 'funny' },
    { text: 'Öfkenin verdiği anda söylediğiniz en kötü şey nedir?', category: 'risky' },
    { text: 'Hiç tek taraflı hissettiren bir arkadaşlığınız oldu mu?', category: 'friendship' },
    { text: 'Bir konserde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç herkese açık bir yerde şarkı söylerken yakalandınız mı?', category: 'funny' },
    { text: 'Sizi rahatlatан en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç çevrimiçi tanıştığınız birine ilgi duydunuz mu?', category: 'risky' },
    { text: 'Bilinmeyenle ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç nefret ettiğiniz bir konuyla ilgileniyormuş gibi davrandınız mı?', category: 'funny' },
    { text: 'Bir buluşmada yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç çocukça bir şey yaparken yakalandınız mı?', category: 'funny' },
    { text: 'Birini etkilemek için yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Hiç anlatmak istediğiniz ama anlatamadığınız bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir tatilde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç bir arkadaşlığı bitiren taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Çocukken sahip olduğunuz en tuhaf korku nedir?', category: 'funny' },
    { text: 'Hiç hislerinizi söylemediğiniz birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Güvenle ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç mutsuzken mutluymuş gibi davrandınız mı?', category: 'funny' },
    { text: 'Bir cenazede yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç bir arkadaşınız tarafından yalan söylerken yakalandınız mı?', category: 'risky' },
    { text: 'Sıkılırken yaptığınız en kötü şey nedir?', category: 'general' },
    { text: 'Hiç suçluluk hissettiren bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir doğum günü partisinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç üçüncü tekер oldunuz mu?', category: 'friendship' },
    { text: 'Birine söylediğiniz en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç bağlı birine ilgi duydunuz mu?', category: 'risky' },
    { text: 'Aşkla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç çevrimiçi olarak başka biri gibi davrandınız mı?', category: 'risky' },
    { text: 'Bir toplantıda yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç utandığınız bir şey yaparken yakalandınız mı?', category: 'risky' },
    { text: 'Sarhoşken yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Hiç özlediğiniz bir arkadaşlığınız oldu mu?', category: 'friendship' },
    { text: 'Bir spor etkinliğinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç garip bir sessizliğe düştünüz mü?', category: 'funny' },
    { text: 'Şimdiye kadar istediğiniz en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç birlikte çalıştığınız birine ilgi duydunuz mu?', category: 'risky' },
    { text: 'Yanlış anlaşılmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç bir şeyi kasıtlı olarak unuttunuz mu?', category: 'funny' },
    { text: 'Bir düğünde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç bir arkadaşlığı bitirmek zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Para için yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Hiç anlatmaktan korktuğunuz bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir sunumda yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç ele geçirici bir durumda yakalandınız mı?', category: 'risky' },
    { text: 'Eğlenmek için yaptığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç neredeyse hiç tanımadığınız birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Başkalarını hayal kırıklığına uğratmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'İşten veya okuldan kaçmak için hasta numarası yaptınız mı?', category: 'funny' },
    { text: 'Bir partide yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç hayalet olduğunuz kişi siz oldunuz mu?', category: 'friendship' },
    { text: 'Kıskanç olduğunuzda yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Hiç birini incitebilecek bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir fotoğraf çekiminde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç saçma bir tartışmada yakalandınız mı?', category: 'funny' },
    { text: 'Şimdiye kadar denediğiniz en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç her gün gördüğünüz birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Dışlanmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Erken ayrılmak için hiç yorgun numarası yaptınız mı?', category: 'funny' },
    { text: 'Bir barda yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç dedikodu yayanın kendiniz olduğu oldu mu?', category: 'risky' },
    { text: 'Stresken yaptığınız en kötü şey nedir?', category: 'general' },
    { text: 'Hiç sırrınızı yanlış kişiye söylediniz mi?', category: 'risky' },
    { text: 'Bir seyahatte yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç zayıf bir anınızda yakalandınız mı?', category: 'general' },
    { text: 'Şimdiye kadar inandığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç sizi hayalet eden birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Yerini başkasının almasıyla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç incinmişken iyi görünmeye çalıştınız mı?', category: 'funny' },
    { text: 'Bir kulüpte yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç ihanete uğrayan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Korktuğunuzda yaptığınız en kötü şey nedir?', category: 'general' },
    { text: 'Hiç anlatmaktan pişman olduğunuz bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir derste yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç komik bir durumda yakalandınız mı?', category: 'funny' },
    { text: 'Bir yabancıya söylediğiniz en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç sahip olamayacağınız birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Unutulmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç katılmadığınızda katılıyor gibi davrandınız mı?', category: 'funny' },
    { text: 'Bir konserde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç özür dilemek zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Yorgunken yaptığınız en kötü şey nedir?', category: 'general' },
    { text: 'Gurur duyduğunuz bir sırrınız var mı?', category: 'risky' },
    { text: 'Bir yemekte yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç aileniz tarafından yalan söylerken yakalandınız mı?', category: 'risky' },
    { text: 'Yalnızken yaptığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç geçmişinizden birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Aileniz tarafından yargılanmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç gergin olduğunuzda sakin görünmeye çalıştınız mı?', category: 'funny' },
    { text: 'Bir kafede yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç reddedilen taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Üzgünken yaptığınız en kötü şey nedir?', category: 'general' },
    { text: 'Hiç bir yere yazdığınız bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir uçuşta yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç tuhaf bir alışkanlıkla yakalandınız mı?', category: 'funny' },
    { text: 'Arkadaşlarınızla yaptığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç tartıştığınız birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Arkadaşlarınıza karşı savunmasız olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç korkmuşken cesur görünmeye çalıştınız mı?', category: 'funny' },
    { text: 'Bir alışveriş merkezinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç affetmek zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Mutluyken yaptığınız en kötü şey nedir?', category: 'general' },
    { text: 'Hiç neredeyse anlattığınız bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir yürüyüşte yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç dürüst bir anınızda yakalandınız mı?', category: 'general' },
    { text: 'Geceleri yaptığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç hayran olduğunuz birine ilgi duydunuz mu?', category: 'friendship' },
    { text: '"Çok fazla" olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç paniklerken sakin görünmeye çalıştınız mı?', category: 'funny' },
    { text: 'Havuz başında yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç ilk özür dileyen taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Birine kızdığınızda yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Ailenizden sakladığınız bir sırrınız var mı?', category: 'risky' },
    { text: 'Bir plaj gezisinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç saçma bir anda yakalandınız mı?', category: 'funny' },
    { text: 'Sabahları yaptığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç sizi gergin hissettiren birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Yeterli olmamakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç bilmediğiniz bir şeyi biliyormuş gibi davrandınız mı?', category: 'funny' },
    { text: 'Spor salonunda yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç bırakmak zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Utandığınızda yaptığınız en kötü şey nedir?', category: 'general' },
    { text: 'Hiç yalnızca bir kişiye anlattığınız bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir yol gezisinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç tembel bir anınızda yakalandınız mı?', category: 'funny' },
    { text: 'Rahatlamak için yaptığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç sizi güldüren birine ilgi duydunuz mu?', category: 'friendship' },
    { text: '"Çok az" olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç sürpriz yapmıyorken yapmış gibi davrandınız mı?', category: 'funny' },
    { text: 'Bir parkta yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç devam etmek zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Kafanız karıştığında yaptığınız en kötü şey nedir?', category: 'general' },
    { text: 'Hiç anlatmaktan korktuğunuz bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir kamp gezisinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç tuhaf bir anda yakalandınız mı?', category: 'funny' },
    { text: 'Neşelenmek için yaptığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç sizi güldüren birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Sıkıcı olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç konuşmaktan kaçınmak için meşgulmüş gibi davrandınız mı?', category: 'funny' },
    { text: 'Bir müzede yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç veda etmek zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Sabırsızlandığınızda yaptığınız en kötü şey nedir?', category: 'general' },
    { text: 'Hiç günlüğünüze yazdığınız bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir tekne gezisinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç mutlu bir anda yakalandınız mı?', category: 'funny' },
    { text: 'Ertelemek için yaptığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç size nazik davranan birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Can sıkıcı olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç dinlemiyorken dinliyormuş gibi davrandınız mı?', category: 'funny' },
    { text: 'Hayvanat bahçesinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç baştan başlamak zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Bir arkadaşınıza kıskandığınızda yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Hiç yazıp göndermediğiniz bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir festivalde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç üzgün bir anda yakalandınız mı?', category: 'general' },
    { text: 'Etkilemek için yaptığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç komik olan birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Çok sessiz olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç bir konuşmayı dinlemek için uyuyor numarası yaptınız mı?', category: 'funny' },
    { text: 'Bir tiyatroda yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç barışmak zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Kötü ruh halindeyken yaptığınız en kötü şey nedir?', category: 'general' },
    { text: 'Hiç birine fısıldadığınız bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir piknikte yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç romantik bir anda yakalandınız mı?', category: 'funny' },
    { text: 'İşten kaçınmak için yaptığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç zeki olan birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Çok yüksek sesli olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Bir randevudan kaçmak için hasta numarası yaptınız mı?', category: 'funny' },
    { text: 'Bir kütüphanede yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç gerçeği kabul etmek zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Kardeşinize kıskandığınızda yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Hiç tutmanıza sevinen bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir mangalda yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç sinirli bir anda yakalandınız mı?', category: 'funny' },
    { text: 'Uyum sağlamak için yaptığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç yaratıcı olan birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Çok ciddi olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç yarı uykudayken uyanıkmış gibi davrandınız mı?', category: 'funny' },
    { text: 'Bir bowling salonunda yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç suçu üstlenmek zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Bir iş arkadaşınıza kıskandığınızda yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Hiç ortaya çıkmasından korktuğunuz bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir karaoke gecesinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç heyecanlı bir anda yakalandınız mı?', category: 'funny' },
    { text: 'Kutlamak için yaptığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç yetenekli olan birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Çok saçma olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç offend olmamışken offend olmuş gibi davrandınız mı?', category: 'funny' },
    { text: 'Bir bowling salonunda yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç birileri için ayağa kalkmak zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Eski partnerinize kıskandığınızda yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Hiç sık sık düşündüğünüz bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir oyun gecesinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç düşünceli bir anda yakalandınız mı?', category: 'general' },
    { text: 'Birini şaşırtmak için yaptığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç gizemli olan birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Çok dürüst olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç kızgın değilken kızgınmış gibi davrandınız mı?', category: 'funny' },
    { text: 'Bir kumarhanede yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç birileri için sır saklamak zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Bir yabancıya kıskandığınızda yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Hiç anlatmak isteyip anlatamadığınız bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir akşam yemeği partisinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç nostaljik bir anda yakalandınız mı?', category: 'general' },
    { text: 'Birine yardım etmek için yaptığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç maceraperest olan birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Çok bağımlı olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç üzgün değilken üzgünmüş gibi davrandınız mı?', category: 'funny' },
    { text: 'Bir düğün resepsiyonunda yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç kötü haber vermek zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Bir ünlüye kıskandığınızda yaptığınız en kötü şey nedir?', category: 'funny' },
    { text: 'Hiç çok erken anlattığınız bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir bebek partisinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç umutlu bir anda yakalandınız mı?', category: 'general' },
    { text: 'Öç almak için yaptığınız en tuhaf şey nedir?', category: 'risky' },
    { text: 'Hiç sakin olan birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Çok bağımsız olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç heyecanlı değilken heyecanlıymış gibi davrandınız mı?', category: 'funny' },
    { text: 'Bir bebek partisinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç birini teselli etmek zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Komşunuza kıskandığınızda yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Hiç anlamamaktan pişman olduğunuz bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir mezuniyette yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç huzurlu bir anda yakalandınız mı?', category: 'general' },
    { text: 'Dikkat çekmek için yaptığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç tutkulu olan birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Çok duygusal olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç kıskanç değilken kıskanıyormuş gibi davrandınız mı?', category: 'funny' },
    { text: 'Bir mezuniyet partisinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç tavsiye vermek zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Bir akrabanıza kıskandığınızda yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Hiç rüyada anlattığınız bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir ev partisinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç kendinizle saçma bir tartışmada yakalandınız mı?', category: 'funny' },
    { text: 'Bir bahsi kazanmak için yaptığınız en tuhaf şey nedir?', category: 'challenge' },
    { text: 'Hiç çekingen olan birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Çok mantıklı olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç paniklerken sakin görünmeye çalıştınız mı?', category: 'funny' },
    { text: 'Bir eve taşınma partisinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç bir kavgaya arabuluculuk etmek zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Sınıf arkadaşınıza kıskandığınızda yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Hiç yazıp göndermediğiniz bir mektuptaki sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir buluşmada yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç cesur bir anda yakalandınız mı?', category: 'general' },
    { text: 'Birini güldürmek için yaptığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç dışa dönük olan birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Çok hassas olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç umursamaz görünmeye çalıştınız mı?', category: 'funny' },
    { text: 'Bir emeklilik partisinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç taraf seçmek zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Takım arkadaşınıza kıskandığınızda yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Hiç ima ettiğiniz ama hiç söylemediğiniz bir sırrınız oldu mu?', category: 'risky' },
    { text: 'Bir yılbaşı partisinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç nazik bir anda yakalandınız mı?', category: 'general' },
    { text: 'Birinin üstesinden gelmek için yaptığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç inatçı olan birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Çok affedici olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç incitmemişken incitilmiş gibi davrandınız mı?', category: 'funny' },
    { text: 'Bir ofis partisinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç masum bir yalan söylemek zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'Ev arkadaşınıza kıskandığınızda yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Hiç bir gün anlatmayı planladığınız bir sırrınız var mı?', category: 'risky' },
    { text: 'Bir doğum günü yemeğinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç zayıf ama sonra güçlü bir anda yakalandınız mı?', category: 'general' },
    { text: 'Birini hatırlamak için yaptığınız en tuhaf şey nedir?', category: 'general' },
    { text: 'Hiç sizden farklı olan birine ilgi duydunuz mu?', category: 'friendship' },
    { text: 'Çok güvenen biri olmakla ilgili en büyük korkunuz nedir?', category: 'general' },
    { text: 'Hiç sabırsızken sabırlıymış gibi davrandınız mı?', category: 'funny' },
    { text: 'Bir networking etkinliğinde yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç barışı korumak zorunda kalan taraf siz oldunuz mu?', category: 'friendship' },
    { text: 'En iyi arkadaşınıza kıskandığınızda yaptığınız en kötü şey nedir?', category: 'risky' },
    { text: 'Hiç doğru zamanı beklediğiniz bir sırrınız var mı?', category: 'risky' },
    { text: 'Bir körü körüne buluşmada yaşadığınız en utanç verici anınız nedir?', category: 'funny' },
    { text: 'Hiç berrak bir anda yakalandınız mı?', category: 'general' },
    { text: 'Birini onurlandırmak için yaptığınız en tuhaf şey nedir?', category: 'general' },
  ];
  
  const dares = [
    { text: 'Odadaki birisinin taklitini yapın.', category: 'funny' },
    { text: 'En sevdiğiniz şarkının nakaratını yüksek sesle söyleyin.', category: 'funny' },
    { text: 'Müziksiz 30 saniye dans edin.', category: 'challenge' },
    { text: 'Sonraki 3 tur boyunca aksanlı konuşun.', category: 'funny' },
    { text: 'Başka birinin sosyal medyanızda hikaye paylaşmasına izin verin.', category: 'risky' },
    { text: 'Bir kişiyi arayın ve ona doğum günü şarkısı söyleyin.', category: 'challenge' },
    { text: '10 şınav veya squat yapın.', category: 'challenge' },
    { text: 'Grup tarafından seçilen bir sosun bir kaşığını yiyin.', category: 'challenge' },
    { text: 'Grubun 1 dakika boyunca fotoğraf galerinize bakmasına izin verin.', category: 'risky' },
    { text: 'Odadaki her kişi hakkında güzel bir şey söyleyin.', category: 'friendship' },
    { text: '10 saniye boyunca amuda kalkın.', category: 'challenge' },
    { text: 'Sonraki 2 tur boyunca yalnızca sorularla konuşun.', category: 'funny' },
    { text: 'Birinin yüzünüze kalemle çizmesine izin verin.', category: 'funny' },
    { text: 'Solunuzdaki kişiyle bir kıyafet parçanızı değiştirin.', category: 'challenge' },
    { text: 'En iyi hayvan taklitinizi yapın ve 1 dakika boyunca devam edin.', category: 'funny' },
    { text: 'Sevgilinize veya eski sevgilinize sesli mesaj gönderin (grup metni seçer).', category: 'risky' },
    { text: '2 dakika boyunca başınızda kitap dengeleyin.', category: 'challenge' },
    { text: 'Grubun saçınızı yeniden düzenlemesine izin verin.', category: 'funny' },
    { text: 'Gönderdiğiniz son mesajı dramatik bir şekilde okuyun.', category: 'funny' },
    { text: '1 dakika boyunca plank tutun.', category: 'challenge' },
    { text: 'Sonraki 2 tur boyunca kafiyeli konuşun.', category: 'funny' },
    { text: 'Birinin sizi 30 saniye gıdıklamasına gülmeden izin verin.', category: 'challenge' },
    { text: 'Kıyafetlerinizi ters giyerek bir defile yapın.', category: 'funny' },
    { text: 'Bir aile üyenizi arayın ve ona sevdiğinizi söyleyin.', category: 'friendship' },
    { text: 'Elinizi kullanmadan bir şey yiyin.', category: 'challenge' },
    { text: 'Grubun bir emoji seçmesine izin verin; 2 tur boyunca o şekilde tepki verin.', category: 'funny' },
    { text: 'En iyi ünlü taklitinizi yapın.', category: 'funny' },
    { text: 'Alfabeyi 30 saniyede tersine söyleyin.', category: 'challenge' },
    { text: 'Birinin telefonunuzu 5 dakika boyunca kontrol etmesine izin verin.', category: 'risky' },
    { text: 'Herkesın önünde bir TikTok veya viral dans yapın.', category: 'funny' },
    { text: 'Sonraki 3 tur boyunca bebek sesiyle konuşun.', category: 'funny' },
    { text: 'Gruba 1 dakikalık motivasyonel konuşma yapın.', category: 'challenge' },
    { text: 'Grubun 24 saat boyunca profil fotoğrafınızı seçmesine izin verin.', category: 'risky' },
    { text: '20 jumping jack yapın.', category: 'challenge' },
    { text: 'En son konuştuğunuz kişiye "Seni özledim" mesajı gönderin.', category: 'risky' },
    { text: 'Sıranıza gelene kadar tavuk gibi davranın.', category: 'funny' },
    { text: 'Birinin sizi gözleriniz kapalıyken beslemesine izin verin.', category: 'challenge' },
    { text: 'Aldığınız son 3 mesajı yüksek sesle okuyun.', category: 'risky' },
    { text: 'Sağınızdaki kişinin taklitini yapın.', category: 'funny' },
    { text: 'Grubun bir şarkı seçmesine izin verin; ilk kıtayı söylemeniz gerekiyor.', category: 'challenge' },
    { text: 'Herkesle göz teması kurarak 15 squat yapın.', category: 'challenge' },
    { text: 'Birinin oyunun geri kalanı için saçınızı istediği gibi yapmasına izin verin.', category: 'funny' },
    { text: 'Sonraki 3 tur boyunca korsan sesiyle konuşun.', category: 'funny' },
    { text: 'En iyi ünlü taklitinizi yapın ve grubun tahmin etmesine izin verin.', category: 'funny' },
    { text: 'Sağınızdaki kişinin 30 saniye boyunca kamera rulonuza bakmasına izin verin.', category: 'risky' },
    { text: 'Kişi rehberinizdeki son kişiye flörtçe bir mesaj gönderin (grup yazar).', category: 'risky' },
    { text: 'Bir pist yürüyüşü yapın ve sonunda poz verin.', category: 'funny' },
    { text: 'Gözleriniz kapalıyken biri sizi beslerken bir ısırık yiyin.', category: 'challenge' },
    { text: 'Grubun gecenin geri kalanı için size yeni bir takma ad vermesine izin verin.', category: 'funny' },
    { text: '10 burpee yapın.', category: 'challenge' },
    { text: 'Son aramanızı yüksek sesle okuyun.', category: 'risky' },
    { text: '1 dakika boyunca köpek gibi davranın.', category: 'funny' },
    { text: 'Birinin sırtınıza buz koymasına izin verin.', category: 'challenge' },
    { text: 'Bir telenovelada gibi dramatik bir monolog yapın.', category: 'funny' },
    { text: 'Sıranıza gelene kadar İngiliz (veya başka bir) aksanla konuşun.', category: 'funny' },
    { text: 'Grubun dolabınızdan bir kıyafet seçmesine izin verin; 10 dakika boyunca giyin.', category: 'challenge' },
    { text: '15 saniye boyunca duvara karşı amuda kalkın.', category: 'challenge' },
    { text: 'Bir arkadaşınızı arayın ve "Sana söylemem gereken önemli bir şey var" deyin, sonra kapatın.', category: 'risky' },
    { text: 'Birinin yüzünüze kalemle bıyık çizmesine izin verin.', category: 'funny' },
    { text: 'Solunuzdaki kişinin taklitini yapın.', category: 'funny' },
    { text: 'Bir kaşık acı sos veya limon yiyin.', category: 'challenge' },
    { text: 'Grubun son 5 mesajınızı okumasına izin verin (isterseniz isimleri gizleyebilirsiniz).', category: 'risky' },
    { text: 'Takla atın ya da deneyin.', category: 'challenge' },
    { text: '"Happy Birthday" şarkısını kendinize dramatik bir şekilde söyleyin.', category: 'funny' },
    { text: 'Birinin sizi 20 saniye kıpırdamadan gıdıklamasına izin verin.', category: 'challenge' },
    { text: 'Hayali bir ürün için reklam yapın.', category: 'funny' },
    { text: 'Sonraki 2 tur boyunca yalnızca şarkı sözleriyle konuşun.', category: 'funny' },
    { text: 'Grubun hikayenizde bir sonraki paylaşacağınızı seçmesine izin verin.', category: 'risky' },
    { text: '20 mekik yapın.', category: 'challenge' },
    { text: '1 dakika boyunca kedi gibi davranın (miyavlayın, pençenizi yalayın vb.).', category: 'funny' },
    { text: 'Birinin mesaj yazmasına ve sizin seçtikleri kişiye göndermenize izin verin.', category: 'risky' },
    { text: '"Gol atıyor" veya "yarışı kazanıyor" sahnesinin ağır çekim tekrarını yapın.', category: 'funny' },
    { text: 'Elinizi kullanmadan bir parça ekmek yiyin.', category: 'challenge' },
    { text: 'Grubun en çok kullandığınız emojilere bakarak en çok kiminle mesajlaştığınızı tahmin etmesine izin verin.', category: 'risky' },
    { text: '30 saniye boyunca en iyi opera şarkınızı söyleyin.', category: 'funny' },
    { text: 'Sonraki 2 tur boyunca robot sesiyle konuşun.', category: 'funny' },
    { text: 'Birinin gözlerinizi bağlayıp sizi 5 kez döndürmesine izin verin; sonra düz bir çizgide yürümeye çalışın.', category: 'challenge' },
    { text: 'Herkesın önünde bir TikTok trendi (yeni veya eski) yapın.', category: 'funny' },
    { text: 'Bir pizzacıyı arayın ve "sürpriz pizza" isteyin (gerçekten sipariş vermeyin).', category: 'funny' },
    { text: 'Solunuzdaki kişinin sonraki 3 sosyal medya paylaşımınızı seçmesine izin verin.', category: 'risky' },
    { text: 'Grubun kollarına düşün (güven egzersizi).', category: 'challenge' },
    { text: '1 dakika boyunca sessiz filmde gibi davranın.', category: 'funny' },
    { text: 'Birinin sizi gözleriniz kapalıyken 3 farklı yiyecekle beslemesine izin verin; ne olduklarını tahmin edin.', category: 'challenge' },
    { text: 'Bir öğretmen veya amirin taklitini yapın.', category: 'funny' },
    { text: 'Sonraki 3 tur boyunca kafiyeli konuşun.', category: 'funny' },
    { text: 'Grubun bir şarkı seçmesine izin verin; 1 dakika boyunca dans edin.', category: 'challenge' },
    { text: 'Kendiniz hakkında 30 saniyelik stand-up yapın.', category: 'funny' },
    { text: 'Bir aile üyenizi arayın ve ona en dramatik şekilde sevdiğinizi söyleyin.', category: 'friendship' },
    { text: 'Birinin 30 saniye boyunca notlar uygulamanıza bakmasına izin verin.', category: 'risky' },
    { text: 'Rastgele bir Wikipedia makalesini dramatik bir şekilde okuyun.', category: 'funny' },
    { text: 'Mevcut oyunu haberleştiren bir haber sunucusu gibi davranın.', category: 'funny' },
    { text: 'Grubun 24 saat boyunca size yeni bir profil fotoğrafı vermesine izin verin.', category: 'risky' },
    { text: 'En iyi spor yorumcusu taklitinizi yapın.', category: 'funny' },
    { text: 'Sonraki 2 tur boyunca Shakespeare karakteri gibi konuşun.', category: 'funny' },
    { text: 'Birinin bir sonraki öğününüzde ne yiyeceğinizi seçmesine izin verin.', category: 'challenge' },
    { text: 'Saçınızı düzeltirrken "get ready with me" tarzı yorum yapın.', category: 'funny' },
    { text: 'Rastgele bir kişiyi arayın ve "Sesinizi duymak istedim" deyin, sonra kapatın.', category: 'risky' },
    { text: 'Grubun çalma listelerinizden birine bakmasına ve eleştirmesine izin verin.', category: 'funny' },
    { text: 'Grup için bir sihir numarası yapın (gerçek veya sahte).', category: 'funny' },
    { text: 'Bir fitness eğitmeni gibi davranın ve 1 dakikalık "antrenman" yönetin.', category: 'funny' },
    { text: 'Birinin bir sonraki paylaşımınız için başlık yazmasına izin verin.', category: 'risky' },
    { text: 'En iyi politikacı konuşması taklitinizi yapın.', category: 'funny' },
    { text: 'Sonraki 3 tur boyunca yalnızca sorularla konuşun.', category: 'funny' },
    { text: 'Sağınızdaki kişinin bir haftalığına zil sesinizi seçmesine izin verin.', category: 'challenge' },
    { text: 'Parmağınızı çarptığınız son anın dramatik canlandırmasını yapın.', category: 'funny' },
    { text: 'Odadaki herkese şiirsel bir şekilde iltifat edin.', category: 'friendship' },
    { text: 'Grubun eski bir fotoğrafınızı seçmesine izin verin; bunu hikayeniz olarak paylaşın.', category: 'risky' },
    { text: 'En iyi hava durumu sunucusu taklitinizi yapın.', category: 'funny' },
    { text: 'İçinde bulunduğunuz oda için bir reklam gibi davranın.', category: 'funny' },
    { text: 'Birinin son DM konuşmanızı okumasına izin verin (gerekirse isimler gizlenebilir).', category: 'risky' },
    { text: 'Her kişi için güzel bir şey söylerken 10 akciğer hareketi yapın.', category: 'challenge' },
    { text: 'Sonraki 2 tur boyunca fısıltıyla konuşun.', category: 'funny' },
    { text: 'Grubun bir sonraki içeceğinizi seçmesine izin verin.', category: 'challenge' },
    { text: '"Tuvalete gitmem gerekiyor" sahnesinin dramatik yorumunu yapın.', category: 'funny' },
    { text: 'Bir arkadaşınızı arayın ve seçtikleri şarkının ilk 30 saniyesini söyleyin.', category: 'challenge' },
    { text: 'Birinin kolunuza kalemle çizmesine izin verin (silinebilir).', category: 'funny' },
    { text: 'En iyi oyun sunucusu taklitinizi yapın.', category: 'funny' },
    { text: 'Herkesi odada gezdiren bir tur rehberi gibi davranın.', category: 'funny' },
    { text: 'Grubun yarın yapmanız gereken bir şeye karar vermesine izin verin.', category: 'challenge' },
    { text: 'Son saat için "günlük rutinimde" tarzı sesli yorum yapın.', category: 'funny' },
    { text: 'Solunuzdaki kişiye 30 saniyelik moral konuşması yapın.', category: 'friendship' },
    { text: 'Birinin dolabınızdan bir kıyafet seçmesine izin verin; 1 saat boyunca giyin.', category: 'challenge' },
    { text: 'Bir pişirme programındaki şef gibi bir yemeği sunan taklitini yapın.', category: 'funny' },
    { text: 'Sonraki 2 tur boyunca korku filmi gibi konuşun.', category: 'funny' },
    { text: 'Grubun bir filtre seçmesine izin verin; selfie çekin ve paylaşın.', category: 'risky' },
    { text: 'Bugün aldığınız bir mesajın dramatik okumasını yapın.', category: 'funny' },
    { text: 'Oyunun bir sonraki turu için yorumcu gibi davranın.', category: 'funny' },
    { text: 'Bir tekerleme söylerken 25 jumping jack yapın.', category: 'challenge' },
    { text: 'Grubun bir kelime seçmesine izin verin; 3 tur boyunca her cümlede kullanın.', category: 'funny' },
    { text: 'Bir kişiye onları düşündüğünüzü söyleyen sesli mesaj gönderin.', category: 'risky' },
    { text: 'En iyi film kötü adamı taklitinizi yapın.', category: 'funny' },
    { text: 'Solunuzdaki kişiye 30 saniyelik omuz masajı yapın.', category: 'friendship' },
    { text: 'Bir kraker yiyin ve hemen ardından ıslık çalmayı deneyin.', category: 'challenge' },
    { text: 'Birinin adınıza bir durum paylaşmasına izin verin (metni kendileri seçer).', category: 'risky' },
    { text: 'Sonraki 2 tur boyunca şair gibi konuşun.', category: 'funny' },
    { text: '15 dağ tırmanıcısı yapın.', category: 'challenge' },
    { text: 'Annenize veya babanıza kalp emojili "Seni seviyorum" mesajı gönderin.', category: 'friendship' },
    { text: 'Dedektif gibi davranın ve 1 dakika boyunca odayı "soruşturun".', category: 'funny' },
    { text: 'Grubun son 10 fotoğrafınıza bakmasına izin verin (atlamak yok).', category: 'risky' },
    { text: 'Bir paket yiyeceğin menüsünü dramatik biçimde okuyun.', category: 'funny' },
    { text: '30 saniye nefinizi tutun, ardından bir tekerleme söyleyin.', category: 'challenge' },
    { text: 'Sağınızdaki kişiyi yaratıcı bir şekilde iltifat edin.', category: 'friendship' },
    { text: 'Sonraki 3 tur boyunca güney aksanıyla konuşun.', category: 'funny' },
    { text: 'Yerinde 20 yüksek diz çekin.', category: 'challenge' },
    { text: 'Bir arkadaşınızı arayın ve "Tahmin et ne?" deyin, ardından "Tavuk kıç."  deyin.', category: 'funny' },
    { text: 'Birinin Instagram takip listenize 30 saniye bakmasına izin verin.', category: 'risky' },
    { text: 'En iyi süper kahraman taklitinizi yapın.', category: 'funny' },
    { text: 'Odadaki her kişide takdir ettiğiniz üç şeyi söyleyin.', category: 'friendship' },
    { text: 'Yüz kırıştırmadan bir limon dilimine ısırın.', category: 'challenge' },
    { text: 'Gönderdiğiniz son e-postanın konu satırını yüksek sesle okuyun.', category: 'risky' },
    { text: 'Kabin görevlisi gibi davranın ve oda için güvenlik talimatlarını verin.', category: 'funny' },
    { text: 'Bir sandalye veya kanepede 10 triceps dip yapın.', category: 'challenge' },
    { text: 'Bir arkadaşınıza rastgele bir iltifat mesajı gönderin.', category: 'friendship' },
    { text: 'Sonraki 2 tur boyunca Fransız aksanıyla konuşun.', category: 'funny' },
    { text: 'Grubun bir sonraki atıştırmalığınızı seçmesine izin verin.', category: 'challenge' },
    { text: 'Bir şeye takılıp düşmenin dramatik canlandırmasını yapın.', category: 'funny' },
    { text: 'En son mesaj gönderdiğiniz kişiye grup seçimli bir meme gönderin.', category: 'risky' },
    { text: 'En iyi motivasyonel konuşmacı taklitinizi yapın.', category: 'funny' },
    { text: 'Odadaki herkesi kucaklayın ve her birine güzel bir şey söyleyin.', category: 'friendship' },
    { text: 'Bir hikaye anlatırken 1 dakika boyunca tek ayak üzerinde durun.', category: 'challenge' },
    { text: 'Gelen kutunuzdaki ilk mesajı yüksek sesle okuyun (grup cevap gönderip göndermeyeceğinize karar verir).', category: 'risky' },
    { text: 'Bir sonraki tur için yarışmacı gibi davranın.', category: 'funny' },
    { text: '15 kalça çekme yapın.', category: 'challenge' },
    { text: 'Bir aile üyenizi arayın ve onlara bir fıkra anlatın.', category: 'friendship' },
    { text: 'Sonraki 2 tur boyunca yalnızca film alıntılarıyla konuşun.', category: 'funny' },
    { text: 'Birinin utanç verici bir şarkı seçmesine izin verin; tepkisiz 30 saniye dinleyin.', category: 'challenge' },
    { text: 'Düşünebileceğiniz en kötü ürün için reklam yapın.', category: 'funny' },
    { text: 'Grubun yazdığı bir başlıkla hikaye paylaşın.', category: 'risky' },
    { text: 'En iyi pişirme programı şefi taklitinizi yapın.', category: 'funny' },
    { text: 'Solunuzdaki kişiye onunla arkadaş olmaktan neden memnun olduğunuzu söyleyin.', category: 'friendship' },
    { text: '20 saniye duvar oturuşu yapın.', category: 'challenge' },
    { text: 'Grubun bugünkü ekran sürenize bakmasına izin verin.', category: 'risky' },
    { text: 'Odadaki birine ödül takdim ediyormuş gibi davranın.', category: 'funny' },
    { text: 'Bir kaşık fıstık ezmesi yiyin ve "toy boat"ı 5 kez hızlıca söylemeye çalışın.', category: 'challenge' },
    { text: 'Birine "Konuşmamız lazım" mesajı gönderin, hemen ardından "pizza hakkında" ekleyin.', category: 'funny' },
    { text: 'En iyi kötü haber veren haber muhabiri taklitinizi yapın.', category: 'funny' },
    { text: 'Sağınızdaki kişi hakkında hiç yüksek sesle söylemediğiniz bir şey söyleyin.', category: 'friendship' },
    { text: '10 squat zıplaması yapın.', category: 'challenge' },
    { text: 'Grubun son aramalarınıza bakmasına izin verin (yalnızca bir kişi).', category: 'risky' },
    { text: 'Sonraki 2 tur boyunca İtalyan aksanıyla konuşun.', category: 'funny' },
    { text: 'Kötü haber almanın dramatik yorumunu yapın.', category: 'funny' },
    { text: 'Bir arkadaşınıza onu takdir ettiğinizi söyleyen sesli mesaj gönderin.', category: 'friendship' },
    { text: '45 saniye boyunca bir yoga pozu tutun.', category: 'challenge' },
    { text: 'Son Instagram başlığınızı yüksek sesle okuyun.', category: 'risky' },
    { text: 'Bir müze rehberi gibi davranın ve odayı tanıtın.', category: 'funny' },
    { text: '15 jumping jack yapın (ters yönde).', category: 'challenge' },
    { text: 'Grubun bir filtre seçmesine izin verin; selfie çekin ve 1 saat duvar kağıdı yapın.', category: 'risky' },
    { text: 'En iyi hayal kırıklığına uğramış ebeveyn taklitinizi yapın.', category: 'funny' },
    { text: 'Herkese solunuzdaki kişiden öğrendiğiniz bir şeyi söyleyin.', category: 'friendship' },
    { text: 'Bir şekere ısırın ve lezzeti aşırı ayrıntıyla tarif edin.', category: 'funny' },
    { text: '20 saniye plank tutun.', category: 'challenge' },
    { text: 'Bir kişiye "Muazzamsın" mesajı gönderin, bağlam yok.', category: 'friendship' },
    { text: 'Sonraki 3 tur boyunca robot gibi konuşun.', category: 'funny' },
    { text: 'Birinin bir sonraki Instagram hikayenizi seçmesine izin verin.', category: 'risky' },
    { text: 'Bu hafta aldığınız bir mesajın dramatik okumasını yapın.', category: 'funny' },
    { text: 'Her bacakta 10 akciğer hareketi yapın.', category: 'challenge' },
    { text: 'Bir arkadaşınızı arayın ve seçtikleri şarkının bir satırını söyleyin.', category: 'challenge' },
    { text: 'Odada yürüyen biri için spor yorumcusu gibi davranın.', category: 'funny' },
    { text: 'Grubun eski bir durumunuzu seçmesine izin verin; tekrar paylaşın.', category: 'risky' },
    { text: 'Ünlü birisinin taklitini yapın (grup tahmin eder).', category: 'funny' },
    { text: 'Her kişiye ihtiyacı olsaydı ne yapacağınızı söyleyin.', category: 'friendship' },
    { text: '15 burpee yapın (değiştirilmiş versiyon kabul edilir).', category: 'challenge' },
    { text: 'Panoya kopyaladığınız son şeyi yüksek sesle okuyun.', category: 'risky' },
    { text: 'Sonraki 2 tur boyunca Alman aksanıyla konuşun.', category: 'funny' },
    { text: 'Grup seçimi bir şarkıya 30 saniyelik dans yapın.', category: 'challenge' },
    { text: 'En iyi arkadaşınıza yalnızca ikinizin anlayacağı bir iç şaka gönderin.', category: 'friendship' },
    { text: 'Kütüphaneci gibi davranın ve 30 saniye boyunca herkesi susturun.', category: 'funny' },
    { text: 'Grubun en çok kullandığınız 5 uygulamaya bakmasına izin verin.', category: 'risky' },
    { text: 'En iyi korku filmi korkmuş kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Grup için düğündeymiş gibi bir kadeh kaldırın.', category: 'friendship' },
    { text: '20 mekik yapın.', category: 'challenge' },
    { text: 'Birine "O şeyi hatırlıyor musun?" mesajı gönderin (açıklamayın).', category: 'funny' },
    { text: 'Sonraki tur için yalnızca emoji açıklamalarıyla konuşun.', category: 'funny' },
    { text: 'Birinin bir sonraki WhatsApp veya Messenger durumunuzu seçmesine izin verin.', category: 'risky' },
    { text: 'Piyango kazanmanın dramatik canlandırmasını yapın.', category: 'funny' },
    { text: '30 saniye boyunca yüksek diz çekerek yerinde koşun.', category: 'challenge' },
    { text: 'Sağınızdaki kişiyle birlikte yaşadığınız bir anıyı paylaşın.', category: 'friendship' },
    { text: 'Hakem gibi davranın ve odadaki birine "faul" yapın.', category: 'funny' },
    { text: 'Son Google aramanızı yüksek sesle okuyun.', category: 'risky' },
    { text: 'En iyi komplo teorisyeni taklitinizi yapın.', category: 'funny' },
    { text: 'Odadaki her kişiye göz teması kurarak "Sizi takdir ediyorum" deyin.', category: 'friendship' },
    { text: 'Ekşi bir şeye ısırın ve 10 saniye düz yüzlü kalın.', category: 'challenge' },
    { text: 'Grubun sizin için bir tweet yazmasına izin verin; paylaşın.', category: 'risky' },
    { text: 'Sonraki 2 tur boyunca İspanyol aksanıyla konuşun.', category: 'funny' },
    { text: '15 şınav yapın (diz şınavı kabul edilir).', category: 'challenge' },
    { text: 'Bir arkadaşınızı arayın ve "Seni düşünüyordum" deyin, ardından 1 dk sohbet edin.', category: 'friendship' },
    { text: 'Bugün aldığınız bir bildirimin dramatik okumasını yapın.', category: 'funny' },
    { text: 'Birinin Spotify veya Apple Music son dinlenenlere bakmasına izin verin.', category: 'risky' },
    { text: 'Terapist gibi davranın ve gruba 1 dakikalık "seans" yapın.', category: 'funny' },
    { text: '20 ayak parmağı dokunuşu yapın.', category: 'challenge' },
    { text: 'Bir aile üyesine bugün öğrendiğiniz rastgele bir bilgi gönderin.', category: 'friendship' },
    { text: 'En iyi reality TV yıldızı taklitinizi yapın.', category: 'funny' },
    { text: 'Grubun kamera rulonuzdan hikaye olarak paylaşılacak bir fotoğraf seçmesine izin verin.', category: 'risky' },
    { text: 'Sonraki 2 tur boyunca İskoç aksanıyla konuşun.', category: 'funny' },
    { text: '10 sumo squat yapın.', category: 'challenge' },
    { text: 'Herkese kişiliğine göre bir takma ad verin ve 2 tur boyunca kullanın.', category: 'funny' },
    { text: 'Sosyal medyada beğendiğiniz veya tepki verdiğiniz son şeyi yüksek sesle okuyun.', category: 'risky' },
    { text: 'Gizli bir hayranınız olduğunu öğrenmenin dramatik yorumunu yapın.', category: 'funny' },
    { text: 'Gruba her kişinin size yardım ettiği bir yol söyleyin.', category: 'friendship' },
    { text: '30 saniye boyunca kimse bakmıyor gibi dans edin.', category: 'challenge' },
    { text: 'Bir arkadaşınıza kötü bir fıkra içeren sesli mesaj gönderin.', category: 'funny' },
    { text: 'Grubun 48 saat boyunca profil fotoğrafınızı seçmesine izin verin.', category: 'risky' },
    { text: 'Yargıç gibi davranın ve saçma suçlar için herkese "ceza" verin.', category: 'funny' },
    { text: '15 bacak kaldırma yapın.', category: 'challenge' },
    { text: 'Her kişi için minnettar olduğunuz bir şeyi söyleyin.', category: 'friendship' },
    { text: 'En iyi YouTuber intro taklitinizi yapın.', category: 'funny' },
    { text: 'Birinin telefonunuzdan seçtikleri birine onaylayacağınız bir mesaj göndermesine izin verin.', category: 'risky' },
    { text: 'Sonraki 2 tur boyunca Avustralya aksanıyla konuşun.', category: 'funny' },
    { text: 'Her yönde 20 kol dairesi yapın.', category: 'challenge' },
    { text: 'Bir arkadaşınızı arayın ve en iyi onun taklitini yapın (tahmin etmeleri lazım).', category: 'funny' },
    { text: 'En iyi arkadaşınıza gönderdiğiniz son mesajı yüksek sesle okuyun.', category: 'risky' },
    { text: 'Sabah rutininizin 30 saniyelik dramatik canlandırmasını yapın.', category: 'funny' },
    { text: 'Solunuzdaki kişiye daha önce hiç duymadığı gerçek bir iltifat yapın.', category: 'friendship' },
    { text: '10 tırtıl hareketi yapın.', category: 'challenge' },
    { text: 'Grubun bir şarkı seçmesine izin verin; ilk 30 saniyeyi dudak senkronizasyonu yapın.', category: 'funny' },
    { text: 'Bir flört programı sunucusu gibi davranın ve herkesi yarışmacı olarak tanıtın.', category: 'funny' },
    { text: 'Grubun soruyu ve seçenekleri yazdığı bir anket içeren hikaye paylaşın.', category: 'risky' },
    { text: 'En iyi ders veren öğretmen taklitinizi yapın.', category: 'funny' },
    { text: 'Odadaki her kişiye "Benim için önemlisin" deyin.', category: 'friendship' },
    { text: '15 kayakçı zıplaması yapın.', category: 'challenge' },
    { text: 'Birine "Bir konuda görüşüne ihtiyacım var" mesajı gönderin, ardından saçma bir soru gönderin.', category: 'funny' },
    { text: 'Birinin son arayanlar listesine bakmasına izin verin.', category: 'risky' },
    { text: 'Sonraki 2 tur boyunca New York aksanıyla konuşun.', category: 'funny' },
    { text: 'Grup seçimi bir konuda 1 dakikalık "Ted Talk" yapın.', category: 'challenge' },
    { text: 'Sağınızdaki kişide takdir ettiğiniz bir şeyi herkese söyleyin.', category: 'friendship' },
    { text: 'En iyi infomercial sunucusu taklitinizi yapın.', category: 'funny' },
    { text: 'Grubun bir sonraki paylaşımınız için başlık seçmesine izin verin.', category: 'risky' },
    { text: '20 topuk vurma yapın.', category: 'challenge' },
    { text: 'Bir arkadaşınızı arayın ve onu sevdiğiniz bir şeyi söyleyin.', category: 'friendship' },
    { text: 'Müzayedeci gibi davranın ve odadaki bir şeyi "satışa çıkarın".', category: 'funny' },
    { text: 'Gönderdiğiniz son memi yüksek sesle okuyun.', category: 'risky' },
    { text: 'Bugün gördüğünüz bir reklamın dramatik okumasını yapın.', category: 'funny' },
    { text: '10 tuck zıplaması yapın (daha kolaysa yüksek zıplama).', category: 'challenge' },
    { text: 'Grubun bir kelime seçmesine izin verin; 3 tur boyunca onu söyleyemezsiniz.', category: 'challenge' },
    { text: 'Her kişinin sizi güldürdüğü bir yolu söyleyin.', category: 'friendship' },
    { text: 'En iyi podcast sunucusu taklitinizi yapın.', category: 'funny' },
    { text: 'Grup seçimi birine "Yakında buluşmalıyız" mesajı gönderin.', category: 'risky' },
    { text: 'Sonraki 2 tur boyunca Rusça aksanıyla konuşun.', category: 'funny' },
    { text: 'Her tarafta 15 yan akciğer hareketi yapın.', category: 'challenge' },
    { text: 'Grup için 30 saniyelik "mezuniyet konuşması" yapın.', category: 'funny' },
    { text: 'Birinin TikTok veya Reels beğenilerinize 20 saniye bakmasına izin verin.', category: 'risky' },
    { text: 'Garson gibi davranın ve herkesten hayali bir menü için sipariş alın.', category: 'funny' },
    { text: 'Plank pozisyonunda 20 omuz vuruşu yapın.', category: 'challenge' },
    { text: 'Bir arkadaşınıza "En sevdiğim insanlardan birisin" mesajı gönderin, bağlam yok.', category: 'friendship' },
    { text: 'En iyi monolog veren kötü adam taklitinizi yapın.', category: 'funny' },
    { text: 'Son tweetinizi veya paylaşımınızı yüksek sesle okuyun.', category: 'risky' },
    { text: 'İyi haber almanın dramatik yorumunu yapın.', category: 'funny' },
    { text: 'Solunuzdaki kişiye her zaman anlatmak istediğiniz bir şeyi söyleyin.', category: 'friendship' },
    { text: '30 saniye boyunca atlama ipi atlayın (hayali ip tamam).', category: 'challenge' },
    { text: 'Grubun utanç verici bir şarkı seçmesine izin verin; nakaratı söyleyin.', category: 'funny' },
    { text: 'Bilim insanı gibi davranın ve gruba oyunu "açıklayın".', category: 'funny' },
    { text: 'Grubun yazdığı bir soruyla hikaye paylaşın.', category: 'risky' },
    { text: 'En iyi süper kahraman inişi taklitinizi yapın.', category: 'funny' },
    { text: 'Her kişiye "Burada olduğun için teşekkürler" deyin.', category: 'friendship' },
    { text: 'Her bacakta 10 geri akciğer hareketi yapın.', category: 'challenge' },
    { text: 'Birini arayın ve "Bir oyun oynuyorum ve sen de içindesin" deyin, ardından açıklayın.', category: 'funny' },
    { text: 'Grubun pil ve depolama istatistiklerinize bakmasına izin verin.', category: 'risky' },
    { text: 'Sonraki 2 tur boyunca Jamaika aksanıyla konuşun.', category: 'funny' },
    { text: '15 superman tutuşu yapın (yüzüstü yatarak kollar ve bacaklar kaldırılmış).', category: 'challenge' },
    { text: 'Herkese bir "ödül" verin ve dramatik biçimde sunun.', category: 'friendship' },
    { text: 'Oda için hava durumu tahmini yapıyor gibi dramatik okuma yapın.', category: 'funny' },
    { text: 'Birinin durumunuzu değiştirmesine izin verin.', category: 'risky' },
    { text: 'En iyi yeni uyanmış kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Gruba her kişi hakkında asla değiştirmeyeceğiniz bir şeyi söyleyin.', category: 'friendship' },
    { text: '20 flutter kick yapın.', category: 'challenge' },
    { text: 'Bir kişiye rastgele bir emoji ile "Seni düşünüyorum" mesajı gönderin.', category: 'friendship' },
    { text: 'Koç gibi davranın ve gruba devre arası konuşması yapın.', category: 'funny' },
    { text: 'Kaydettiğiniz veya işaretlediğiniz son şeyi yüksek sesle okuyun.', category: 'risky' },
    { text: 'Bir sandviç hakkında 45 saniyelik dramatik monolog yapın.', category: 'funny' },
    { text: 'Tepede alkış tutarak 10 burpee yapın.', category: 'challenge' },
    { text: 'Grubun bir cümle seçmesine izin verin; 5 farklı aksanla söyleyin.', category: 'funny' },
    { text: 'Her kişi hakkında gurur duyduğunuz bir şeyi söyleyin.', category: 'friendship' },
    { text: 'En iyi kötü haber almış kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Bir arkadaşınıza onun berbat bir taklitini içeren sesli mesaj gönderin.', category: 'funny' },
    { text: 'Grubun bu haftaki takviminize bakmasına izin verin.', category: 'risky' },
    { text: 'Sonraki 2 tur boyunca Hint aksanıyla konuşun.', category: 'funny' },
    { text: '15 glute köprüsü yapın.', category: 'challenge' },
    { text: 'Bir arkadaşınızı arayın ve "En iyisin" deyin, ardından kapatın veya konuşmaya devam edin.', category: 'friendship' },
    { text: 'DJ gibi davranın ve oda için "ritmi bırakın".', category: 'funny' },
    { text: 'Son hatırlatıcı veya alarm etiketinizi yüksek sesle okuyun.', category: 'risky' },
    { text: 'Telefonunuzu düşürmenin dramatik canlandırmasını yapın.', category: 'funny' },
    { text: '20 bisiklet mekiği yapın.', category: 'challenge' },
    { text: 'Herkese sağınızdaki kişinin sizi nasıl etkilediğini söyleyin.', category: 'friendship' },
    { text: 'En iyi lunapark treni taklitinizi yapın.', category: 'funny' },
    { text: 'Grubun seçtiği birine grubun yazdığı mesajı göndermenize izin verin.', category: 'risky' },
    { text: 'Sonraki 2 tur boyunca Boston aksanıyla konuşun.', category: 'funny' },
    { text: '30 saniye gölge boks yapın.', category: 'challenge' },
    { text: 'Oyun hakkında "Birliğin Durumu" tarzında konuşma yapın.', category: 'funny' },
    { text: 'Grubun galerinizden seçtiği fotoğrafı paylaşın (gerekirse yüz yok).', category: 'risky' },
    { text: 'En iyi harika haber almış kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Her kişiye "Hayatımda olduğuna sevindim" deyin.', category: 'friendship' },
    { text: '10 sprawl yapın.', category: 'challenge' },
    { text: 'Birine "Hızlı soru" mesajı gönderin, ardından rastgele bir şey gönderin.', category: 'funny' },
    { text: 'Birinin son not veya hatırlatıcınızı okumasına izin verin.', category: 'risky' },
    { text: 'Bir yetenek yarışması sunucusu gibi davranın ve bir sonraki oyuncuyu tanıtın.', category: 'funny' },
    { text: '15 bacak kaldırma yapın (yatarak).', category: 'challenge' },
    { text: 'Solunuzdaki kişiye sabah 3\'te ihtiyacı olsaydı ne yapardınızı söyleyin.', category: 'friendship' },
    { text: 'Bir tarifi dramatik biçimde okuyun.', category: 'funny' },
    { text: 'Grubun bir sonraki Instagram başlığınızı seçmesine izin verin.', category: 'risky' },
    { text: 'En iyi bir hayalet görmüş kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Her kişinin gününü nasıl daha iyi hale getireceğinizi söyleyin.', category: 'friendship' },
    { text: '20 squat tutma yapın.', category: 'challenge' },
    { text: 'Bir arkadaşınızı arayın ve 30 saniyelik ünlü taklidi yapın.', category: 'funny' },
    { text: 'Son YouTube veya video aramanızı yüksek sesle okuyun.', category: 'risky' },
    { text: 'Sonraki 2 tur boyunca yavaş güney aksanıyla konuşun.', category: 'funny' },
    { text: '10 kutu zıplaması yapın (yerde veya alçak yüzeyde).', category: 'challenge' },
    { text: 'Herkese kişiliğine göre bir "süper güç" verin.', category: 'friendship' },
    { text: 'Sevdiğiniz bir hediyeyi açmanın dramatik yorumunu yapın.', category: 'funny' },
    { text: 'Grubun bir şarkı seçmesine izin verin; gumuldayın ve tahmin etsinler.', category: 'funny' },
    { text: 'Bir talk show sunucusu gibi davranın ve sağınızdaki kişiyi "röportaj yapın".', category: 'funny' },
    { text: 'Bir kişiye grup onaylı bir iltifat mesajı gönderin.', category: 'risky' },
    { text: 'En iyi maraton bitiren kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Her kişiyle ortak bir şeyi söyleyin.', category: 'friendship' },
    { text: '15 baldır kaldırma yapın.', category: 'challenge' },
    { text: 'Birinin indirdiğiniz son 3 dosyaya bakmasına izin verin.', category: 'risky' },
    { text: 'Oda hakkında 1 dakikalık "belgesel" anlatımı yapın.', category: 'funny' },
    { text: 'Alfabeyi söylerken 20 jumping jack yapın.', category: 'challenge' },
    { text: 'Gruba her kişiyle birlikte yaşadığınız bir anıyı söyleyin.', category: 'friendship' },
    { text: 'En iyi anahtarını kaybetmiş kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Grubun yazdığı bir soruyla hikaye paylaşın.', category: 'risky' },
    { text: 'Sonraki 2 tur boyunca Kanada aksanıyla konuşun.', category: 'funny' },
    { text: '10 V-up veya mekik yapın.', category: 'challenge' },
    { text: 'Bir aile üyesine "Seni seviyorum" mesajı gönderin, özel bir sebep belirtin.', category: 'friendship' },
    { text: 'Bir reality show sunucusu gibi davranın ve bir sonraki turu anlatın.', category: 'funny' },
    { text: 'Sosyal medyada paylaştığınız son şeyi yüksek sesle okuyun.', category: 'risky' },
    { text: 'Parmağınızı çarptığınızın dramatik canlandırmasını yapın.', category: 'funny' },
    { text: '15 duvar şınavı yapın.', category: 'challenge' },
    { text: 'Grubun oyun bitmeden tamamlamanız için size bir "görev" vermesine izin verin.', category: 'challenge' },
    { text: 'Her kişiye "Sen fark yaratıyorsun" deyin.', category: 'friendship' },
    { text: 'En iyi terfi almış kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Bir arkadaşınıza rastgele bir bilgi içeren sesli mesaj gönderin.', category: 'funny' },
    { text: 'Birinin bir sonraki durum güncellemeni seçmesine izin verin.', category: 'risky' },
    { text: 'Sonraki 2 tur boyunca kraliyet İngiliz aksanıyla konuşun.', category: 'funny' },
    { text: '20 kol kaldırma yapın (öne ve yana).', category: 'challenge' },
    { text: 'Odadaki bir nesne için komik bir "cenaze söylevi" yapın.', category: 'funny' },
    { text: 'Sağınızdaki kişiye her zaman onunla yapmak istediğiniz bir şeyi söyleyin.', category: 'friendship' },
    { text: 'Bir ürün açıklamasının dramatik okumasını yapın.', category: 'funny' },
    { text: 'Grubun en son ekran görüntünüze bakmasına izin verin.', category: 'risky' },
    { text: 'En iyi park cezası almış kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Her kişide saygı duyduğunuz bir şeyi söyleyin.', category: 'friendship' },
    { text: '10 diz şınavı yapın.', category: 'challenge' },
    { text: 'Bir arkadaşınızı arayın ve "Muhteşemsin" deyin, ardından nedenini açıklayın (30 sn).', category: 'friendship' },
    { text: 'Hayali bir yemekle pişirme programı sunucusu gibi davranın.', category: 'funny' },
    { text: 'Gönderdiğiniz son e-postanın yalnızca konu satırını yüksek sesle okuyun.', category: 'risky' },
    { text: 'Çoraplar hakkında 30 saniyelik dramatik monolog yapın.', category: 'funny' },
    { text: '15 yan karın çalışması yapın.', category: 'challenge' },
    { text: 'Grubun önümüzdeki 24 saat içinde yapmanız için bir cesaret görevi seçmesine izin verin.', category: 'challenge' },
    { text: 'Herkese her kişinin sizi güldürdüğü bir yolu söyleyin.', category: 'friendship' },
    { text: 'En iyi sevgilisini gören kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Bir kişiye baba fıkrası gönderin (grup önerebilir).', category: 'funny' },
    { text: 'Birinin son uygulamalarınıza bakmasına izin verin.', category: 'risky' },
    { text: 'Sonraki 3 tur boyunca korsan aksanıyla konuşun.', category: 'funny' },
    { text: '20 step-up yapın (bir basamak veya alçak yüzeyde).', category: 'challenge' },
    { text: 'Odadaki herkese teşekkür ederek "Oscar konuşması" yapın.', category: 'friendship' },
    { text: 'Bir örümcek bulmanuın dramatik yorumunu yapın.', category: 'funny' },
    { text: 'Grup seçimi bir şarkıyla hikaye paylaşın.', category: 'risky' },
    { text: 'Podcast sunucusu gibi davranın ve solunuzdaki kişiyi röportaj yapın.', category: 'funny' },
    { text: '10 ters mekik yapın.', category: 'challenge' },
    { text: 'Her kişiye "Seni tanıdığıma şanslıyım" deyin.', category: 'friendship' },
    { text: 'En iyi hediye almış kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Son kendi kendine yazdığınız notu yüksek sesle okuyun.', category: 'risky' },
    { text: 'Odadaki bir tabelanın veya etiketin dramatik okumasını yapın.', category: 'funny' },
    { text: '15 kalça kaldırma yapın.', category: 'challenge' },
    { text: 'Solunuzdaki kişiye onunla ilgili asla unutmayacağınız bir şeyi söyleyin.', category: 'friendship' },
    { text: 'Grubun bir cümle seçmesine izin verin; film fragmanı gibi söyleyin.', category: 'funny' },
    { text: 'Birine "Günümü güzelleştirdin" mesajı gönderin (böyle bir şey yapmadıklarında).', category: 'funny' },
    { text: 'Birinin bir sonraki paylaşacağınızı seçmesine izin verin (fotoğraf veya metin).', category: 'risky' },
    { text: 'En iyi şekerlemeden uyanmış kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Her kişiye ne için teşekkür edeceğinizi söyleyin.', category: 'friendship' },
    { text: '20 bacak dairesi yapın (yatarken).', category: 'challenge' },
    { text: 'Bir arkadaşınızı arayın ve 20 saniyelik öğretmen taklidi yapın.', category: 'funny' },
    { text: 'Googlelediğiniz son şeyi yüksek sesle okuyun.', category: 'risky' },
    { text: 'Sonraki 2 tur boyunca kötü adam aksanıyla konuşun.', category: 'funny' },
    { text: '10 kuş köpeği (karşı kol ve bacak) yapın.', category: 'challenge' },
    { text: 'Herkese bir "unvan" verin (ör. "Eğlence Şefi") ve 2 tur boyunca kullanın.', category: 'friendship' },
    { text: 'Buzda kayarken düşmenin dramatik canlandırmasını yapın.', category: 'funny' },
    { text: 'Grubun bir soru seçmesine izin verin; durum olarak paylaşın.', category: 'risky' },
    { text: 'Bir oyun sunucusu gibi davranın ve bir sonraki turu açıklayın.', category: 'funny' },
    { text: '15 ölü böcek yapın.', category: 'challenge' },
    { text: 'Bir arkadaşınıza "Sana minnettarım" mesajı gönderin, kısa bir sebep belirtin.', category: 'friendship' },
    { text: 'En iyi sevgilisinden mesaj almış kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Birinin son 5 emoji kullanımınıza bakmasına izin verin.', category: 'risky' },
    { text: 'Hava durumu hakkında 45 saniyelik dramatik monolog yapın.', category: 'funny' },
    { text: '20 yüksek diz çekerek yerinde yürüyüş yapın.', category: 'challenge' },
    { text: 'Gruba her kişiyi neşelendirmek için ne yapacağınızı söyleyin.', category: 'friendship' },
    { text: 'En iyi bir oyun kazanmış kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Grubun seçtiği bir fotoğrafla hikaye paylaşın.', category: 'risky' },
    { text: 'Sonraki 2 tur boyunca uykulu sesle konuşun.', category: 'funny' },
    { text: '10 kedi-inek germe yapın (yoga).', category: 'challenge' },
    { text: 'Her kişiye "Benim için önemlisin" deyin.', category: 'friendship' },
    { text: 'Bir ödül töreni sunucusu gibi davranın ve odaya ödül verin.', category: 'funny' },
    { text: 'Son çaldığınız çalma listesini veya albümü yüksek sesle okuyun.', category: 'risky' },
    { text: 'Sürpriz partiye çıkmanın dramatik yorumunu yapın.', category: 'funny' },
    { text: '15 ayakta bacak kıvırma yapın.', category: 'challenge' },
    { text: 'Grubun bir kelime seçmesine izin verin; 2 tur boyunca "evet" veya "hayır" diyemezsiniz.', category: 'challenge' },
    { text: 'Sağınızdaki kişinin kişiliğinde takdir ettiğiniz bir şeyi söyleyin.', category: 'friendship' },
    { text: 'En iyi acı bir şey yemiş kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Grup onaylı bir fıkra içeren sesli mesaj gönderin.', category: 'risky' },
    { text: 'Sonraki 3 tur boyunca fısıltıyla konuşun.', category: 'funny' },
    { text: 'Her yönde 20 ayak bileği dairesi yapın.', category: 'challenge' },
    { text: 'Büyük bir şey kazanmışsınız gibi "basın toplantısı" yapın.', category: 'funny' },
    { text: 'Birinin bir sonraki Instagram hikaye türünüzü seçmesine izin verin (anket, soru vb.).', category: 'risky' },
    { text: 'En iyi yalan söylerken yakalanmış kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Her kişiyi nasıl destekleyeceğinizi söyleyin.', category: 'friendship' },
    { text: '10 değirmen hareketi (ayak parmağı dokunuşu) yapın.', category: 'challenge' },
    { text: 'Bir arkadaşınızı arayın ve "Sana bir şey söylemem lazım" deyin, ardından "Harikasın" deyin.', category: 'funny' },
    { text: 'Son alarm adınızı yüksek sesle okuyun.', category: 'risky' },
    { text: 'Bir besin etiketi dramatik biçimde okuyun.', category: 'funny' },
    { text: '15 boyun dönüşü yapın (nazikçe).', category: 'challenge' },
    { text: 'Herkese her kişinin sizi büyütmeye nasıl yardımcı olduğunu söyleyin.', category: 'friendship' },
    { text: 'En iyi terfi almış kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Grubun kısa bir mesaj yazmasına ve seçtikleri birine göndermenize izin verin.', category: 'risky' },
    { text: 'Belgesel sunucusu gibi davranın ve 1 dakika boyunca odayı anlatın.', category: 'funny' },
    { text: '20 bilek dairesi yapın.', category: 'challenge' },
    { text: 'Birine "İyilerin arasındasın" mesajı gönderin, bağlam yok.', category: 'friendship' },
    { text: 'Bir korku sahnesiyle karşılaştığınızda verdiğiniz tepkinin dramatik canlandırmasını yapın.', category: 'funny' },
    { text: 'Birinin son 3 fotoğrafınıza bakmasına izin verin (gerekirse bulanıklaştırabilirsiniz).', category: 'risky' },
    { text: 'Sonraki 2 tur boyunca heyecanlı çocuk sesiyle konuşun.', category: 'funny' },
    { text: '10 omuz dönüşü yapın.', category: 'challenge' },
    { text: 'Her kişiye "Sizi değerli buluyorum" deyin.', category: 'friendship' },
    { text: 'En iyi iltifat almış kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Grubun oluşturduğu "bunu mu yoksa bunu mu" içerikli hikaye paylaşın.', category: 'risky' },
    { text: 'Bir kalem hakkında 30 saniyelik dramatik monolog yapın.', category: 'funny' },
    { text: '15 gövde dönüşü yapın.', category: 'challenge' },
    { text: 'Solunuzdaki kişiye arkadaşlığınız hakkında sevdiğiniz bir şeyi söyleyin.', category: 'friendship' },
    { text: 'Sabah programı sunucusu gibi davranın ve oda için "hava durumu" yapın.', category: 'funny' },
    { text: 'Son hatırlatıcınızı yüksek sesle okuyun.', category: 'risky' },
    { text: 'En iyi kötü servis almış kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Her kişiyi nasıl kutlayacağınızı söyleyin.', category: 'friendship' },
    { text: '20 kol germe yapın.', category: 'challenge' },
    { text: 'Grubun bir şarkı seçmesine izin verin; komik bir sesle bir satırını söyleyin.', category: 'funny' },
    { text: 'Bir arkadaşınıza olumlu bir alıntı mesajı gönderin.', category: 'friendship' },
    { text: 'Birinin WhatsApp durumunuzu seçmesine izin verin.', category: 'risky' },
    { text: 'Yerde para bulmanın dramatik yorumunu yapın.', category: 'funny' },
    { text: 'Her bacakta 10 quadriceps germe yapın.', category: 'challenge' },
    { text: 'Gruba her kişiden öğrendiğiniz bir şeyi söyleyin.', category: 'friendship' },
    { text: 'En iyi yanlış sipariş almış kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Son takvim etkinliği başlığınızı yüksek sesle okuyun.', category: 'risky' },
    { text: 'Bir sonraki tur için dramatik film fragmanı sesiyle konuşun.', category: 'funny' },
    { text: '15 hamstring germe yapın.', category: 'challenge' },
    { text: 'Lider gibi "Odanın Durumu" konuşması yapın.', category: 'funny' },
    { text: 'Grubun bir soru seçmesine izin verin; hikayenizde cevaplayın.', category: 'risky' },
    { text: 'En iyi iyi haber almış kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Her kişiye "Sen buraya aitsin" deyin.', category: 'friendship' },
    { text: '20 kalça dairesi yapın.', category: 'challenge' },
    { text: 'Bir arkadaşınızı arayın ve "Sadece merhaba demek istedim" deyin, 1 dk sohbet edin.', category: 'friendship' },
    { text: 'Bir seyahat programı sunucusu gibi davranın ve odayı "gezdirin".', category: 'funny' },
    { text: 'Yazdığınız son notu yüksek sesle okuyun.', category: 'risky' },
    { text: 'Birinin adını unutmanın dramatik canlandırmasını yapın.', category: 'funny' },
    { text: 'Her tarafta 10 figure-four germe yapın.', category: 'challenge' },
    { text: 'Sağınızdaki kişiye her zaman hatırlayacağınız bir şeyi söyleyin.', category: 'friendship' },
    { text: 'En iyi beğeni almış kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Grubun bir cümle seçmesine izin verin; dramatik bir şekilde söyleyin.', category: 'funny' },
    { text: 'Grubun belirlediği geri sayım veya zamanlayıcıyla hikaye paylaşın.', category: 'risky' },
    { text: '15 oturarak omurga dönüşü yapın.', category: 'challenge' },
    { text: 'Her kişiyi nasıl özel hissettireceğinizi söyleyin.', category: 'friendship' },
    { text: 'En iyi takip isteği almış kişi taklitinizi yapın.', category: 'funny' },
    { text: 'Bir arkadaşınıza onu özlediğinizi söyleyen sesli mesaj gönderin.', category: 'friendship' },
    { text: 'Birinin son 5 aramanıza bakmasına izin verin.', category: 'risky' },
    { text: 'Sonraki 2 tur boyunca monoton sesle konuşun.', category: 'funny' },
  ];
  
  module.exports = { truths, dares };