module.exports = [
  { question: 'What color is the sky?', category: 'general', difficulty: 'easy' },
  { question: 'How many legs does a dog have?', category: 'general', difficulty: 'easy' },
  { question: 'What is 2 + 2?', category: 'general', difficulty: 'easy' },
  { question: 'What is the capital of France?', category: 'general', difficulty: 'easy' },
  { question: 'What animal says "moo"?', category: 'general', difficulty: 'easy' },
  { question: 'How many days are in a week?', category: 'general', difficulty: 'easy' },
  { question: 'What shape is a ball?', category: 'general', difficulty: 'easy' },
  { question: 'What do you use to write on paper?', category: 'general', difficulty: 'easy' },
  { question: 'What is the opposite of hot?', category: 'general', difficulty: 'easy' },
  { question: 'How many fingers do you have on one hand?', category: 'general', difficulty: 'easy' },
  { question: 'What planet do we live on?', category: 'general', difficulty: 'easy' },
  { question: 'What color is grass?', category: 'general', difficulty: 'easy' },
  { question: 'What is the largest ocean?', category: 'general', difficulty: 'medium' },
  { question: 'How many continents are there?', category: 'general', difficulty: 'easy' },
  { question: 'What language do people speak in Spain?', category: 'general', difficulty: 'easy' },
  { question: 'What season comes after summer?', category: 'general', difficulty: 'easy' },
  { question: 'How many hours are in a day?', category: 'general', difficulty: 'easy' },
  { question: 'What is the tallest animal?', category: 'general', difficulty: 'easy' },
  { question: 'What do bees make?', category: 'general', difficulty: 'easy' },
  { question: 'What is 10 minus 3?', category: 'general', difficulty: 'easy' },
  { question: 'What is the opposite of up?', category: 'general', difficulty: 'easy' },
  { question: 'How many wheels does a car have?', category: 'general', difficulty: 'easy' },
  { question: 'What do you call a baby cat?', category: 'general', difficulty: 'easy' },
  { question: 'What fruit is yellow and curved?', category: 'general', difficulty: 'easy' },
  { question: 'What do you wear on your feet?', category: 'general', difficulty: 'easy' },
  { question: 'What is the funniest thing you have ever seen?', category: 'funny', difficulty: 'medium' },
  { question: 'What would be the worst name for a pet?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the silliest superpower you can think of?', category: 'funny', difficulty: 'easy' },
  { question: 'If you could only eat one food forever, what would it be?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst advice you could give someone?', category: 'funny', difficulty: 'medium' },
  { question: 'What would you name your boat?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst gift you could receive?', category: 'funny', difficulty: 'easy' },
  { question: 'What animal would be the worst to be reincarnated as?', category: 'funny', difficulty: 'medium' },
  { question: 'What is the most boring thing you can imagine?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a terrible name for a restaurant?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst superpower?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst vegetable?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a bad name for a band?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst thing to forget on a trip?', category: 'funny', difficulty: 'easy' },
  { question: 'Would you rather have hands for feet or feet for hands?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather always be 10 minutes late or 20 minutes early?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather have no phone or no TV?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather eat only sweet or only salty food?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather live in the past or the future?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather be able to fly or be invisible?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather have summer or winter all year?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather have a cat or a dog?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather never use social media or never watch movies?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather speak all languages or talk to animals?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather have unlimited pizza or unlimited sushi?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather be able to teleport or time travel?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather lose your voice or your hearing?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather have a tiny elephant or a giant hamster?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'What day is it today?', category: 'random', difficulty: 'easy' },
  { question: 'What month is it?', category: 'random', difficulty: 'easy' },
  { question: 'What is the first letter of the alphabet?', category: 'random', difficulty: 'easy' },
  { question: 'How many sides does a triangle have?', category: 'random', difficulty: 'easy' },
  { question: 'What is the opposite of day?', category: 'random', difficulty: 'easy' },
  { question: 'What do you call a baby dog?', category: 'random', difficulty: 'easy' },
  { question: 'What is the fastest land animal?', category: 'random', difficulty: 'medium' },
  { question: 'How many legs does a spider have?', category: 'random', difficulty: 'easy' },
  { question: 'What is the smallest continent?', category: 'random', difficulty: 'medium' },
  { question: 'What is 100 divided by 10?', category: 'random', difficulty: 'easy' },
  { question: 'How many months are in a year?', category: 'random', difficulty: 'easy' },
  { question: 'What is 5 times 5?', category: 'random', difficulty: 'easy' },
  { question: 'How many colors are in a rainbow?', category: 'random', difficulty: 'easy' },
  { question: 'What is the largest planet in our solar system?', category: 'science', difficulty: 'easy' },
  { question: 'How many bones are in the adult human body?', category: 'science', difficulty: 'medium' },
  { question: 'What is the chemical symbol for water?', category: 'science', difficulty: 'easy' },
  { question: 'What force keeps us on the ground?', category: 'science', difficulty: 'easy' },
  { question: 'What gas do plants absorb from the air?', category: 'science', difficulty: 'easy' },
  { question: 'How many teeth does an adult usually have?', category: 'science', difficulty: 'medium' },
  { question: 'What is the boiling point of water in Celsius?', category: 'science', difficulty: 'easy' },
  { question: 'What planet is known as the Red Planet?', category: 'science', difficulty: 'easy' },
  { question: 'What is the speed of light?', category: 'science', difficulty: 'hard' },
  { question: 'How many hearts does an octopus have?', category: 'science', difficulty: 'medium' },
  { question: 'What is the capital of Japan?', category: 'geography', difficulty: 'easy' },
  { question: 'Which is the longest river in the world?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the largest country by area?', category: 'geography', difficulty: 'easy' },
  { question: 'In which continent is Egypt?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Australia?', category: 'geography', difficulty: 'easy' },
  { question: 'Which ocean is the coldest?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the smallest country in the world?', category: 'geography', difficulty: 'medium' },
  { question: 'Which country has the most people?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Brazil?', category: 'geography', difficulty: 'easy' },
  { question: 'In which country is the Eiffel Tower?', category: 'geography', difficulty: 'easy' },
  { question: 'What fruit do raisins come from?', category: 'food', difficulty: 'easy' },
  { question: 'What color is a carrot?', category: 'food', difficulty: 'easy' },
  { question: 'What do you get when you freeze water?', category: 'food', difficulty: 'easy' },
  { question: 'What is the main ingredient in bread?', category: 'food', difficulty: 'easy' },
  { question: 'What country did pizza originate from?', category: 'food', difficulty: 'easy' },
  { question: 'What color is a banana when it is ripe?', category: 'food', difficulty: 'easy' },
  { question: 'What vegetable is used to make pickles?', category: 'food', difficulty: 'easy' },
  { question: 'What is honey made by?', category: 'food', difficulty: 'easy' },
  { question: 'What type of food is sushi?', category: 'food', difficulty: 'easy' },
  { question: 'What fruit is red and has seeds on the outside?', category: 'food', difficulty: 'easy' },
  { question: 'How many players are on a soccer team?', category: 'sports', difficulty: 'easy' },
  { question: 'What color is the middle ring in the Olympic flag?', category: 'sports', difficulty: 'medium' },
  { question: 'In which sport do you score a touchdown?', category: 'sports', difficulty: 'easy' },
  { question: 'How many Grand Slam tournaments are there in tennis?', category: 'sports', difficulty: 'medium' },
  { question: 'What shape is a basketball?', category: 'sports', difficulty: 'easy' },
  { question: 'In which sport do you use a puck?', category: 'sports', difficulty: 'easy' },
  { question: 'How many laps is the Indy 500?', category: 'sports', difficulty: 'medium' },
  { question: 'What country invented the sport of golf?', category: 'sports', difficulty: 'medium' },
  { question: 'How many players are on a basketball team?', category: 'sports', difficulty: 'easy' },
  { question: 'What sport is played at Wimbledon?', category: 'sports', difficulty: 'easy' },
  { question: 'How many strings does a standard guitar have?', category: 'music', difficulty: 'easy' },
  { question: 'What instrument has black and white keys?', category: 'music', difficulty: 'easy' },
  { question: 'How many beats are in a waltz?', category: 'music', difficulty: 'medium' },
  { question: 'What is the largest instrument in an orchestra?', category: 'music', difficulty: 'easy' },
  { question: 'What band sang "Yellow Submarine"?', category: 'music', difficulty: 'easy' },
  { question: 'How many notes are in an octave?', category: 'music', difficulty: 'medium' },
  { question: 'What instrument does a drummer play?', category: 'music', difficulty: 'easy' },
  { question: 'In which country did opera originate?', category: 'music', difficulty: 'medium' },
  { question: 'What is the highest singing voice?', category: 'music', difficulty: 'easy' },
  { question: 'How many strings does a violin have?', category: 'music', difficulty: 'easy' },
  { question: 'In which movie does a lion become king?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the wizard in The Wizard of Oz?', category: 'movies', difficulty: 'easy' },
  { question: 'Which studio made Frozen?', category: 'movies', difficulty: 'easy' },
  { question: 'What animal is Remy in Ratatouille?', category: 'movies', difficulty: 'easy' },
  { question: 'In which movie does a boy find a genie in a lamp?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the fish in Finding Nemo?', category: 'movies', difficulty: 'easy' },
  { question: 'Which movie has a character named Simba?', category: 'movies', difficulty: 'easy' },
  { question: 'What color is Cinderella\'s dress?', category: 'movies', difficulty: 'easy' },
  { question: 'In which movie do toys come to life?', category: 'movies', difficulty: 'easy' },
  { question: 'What kind of animal is Dumbo?', category: 'movies', difficulty: 'easy' },
  { question: 'What is 3 times 4?', category: 'general', difficulty: 'easy' },
  { question: 'How many eyes does a person have?', category: 'general', difficulty: 'easy' },
  { question: 'What is the sun?', category: 'general', difficulty: 'easy' },
  { question: 'What do birds use to fly?', category: 'general', difficulty: 'easy' },
  { question: 'What is snow made of?', category: 'general', difficulty: 'easy' },
  { question: 'How many minutes are in an hour?', category: 'general', difficulty: 'easy' },
  { question: 'What is the opposite of big?', category: 'general', difficulty: 'easy' },
  { question: 'What do you use to see?', category: 'general', difficulty: 'easy' },
  { question: 'What animal has a long trunk?', category: 'general', difficulty: 'easy' },
  { question: 'What color is the sun?', category: 'general', difficulty: 'easy' },
  { question: 'How many sides does a square have?', category: 'general', difficulty: 'easy' },
  { question: 'What do fish breathe?', category: 'general', difficulty: 'easy' },
  { question: 'What falls from the sky when it rains?', category: 'general', difficulty: 'easy' },
  { question: 'What is 15 plus 15?', category: 'general', difficulty: 'easy' },
  { question: 'What do you call a baby sheep?', category: 'general', difficulty: 'easy' },
  { question: 'How many legs does a chair have?', category: 'general', difficulty: 'easy' },
  { question: 'What is the opposite of fast?', category: 'general', difficulty: 'easy' },
  { question: 'What do you read in a book?', category: 'general', difficulty: 'easy' },
  { question: 'What season has the most snow?', category: 'general', difficulty: 'easy' },
  { question: 'What would be the worst job title?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the most useless invention?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a bad name for a soap?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst flavor of ice cream?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a terrible password?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the silliest way to travel?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst thing to be allergic to?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the most embarrassing thing to forget?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a bad name for a hospital?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst superpower to have at a party?', category: 'funny', difficulty: 'easy' },
  { question: 'Would you rather have no taste or no smell?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather fight one horse-sized duck or 100 duck-sized horses?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather have a rewind or pause button for life?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather always sing or always whisper?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather have no eyebrows or no eyelashes?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather be famous or rich?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather have a tail or horns?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather live without music or without movies?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather have a personal chef or a personal pilot?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather know when you die or how you die?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'What is 7 times 8?', category: 'random', difficulty: 'medium' },
  { question: 'How many zeros are in one thousand?', category: 'random', difficulty: 'easy' },
  { question: 'What is the last letter of the alphabet?', category: 'random', difficulty: 'easy' },
  { question: 'How many sides does a hexagon have?', category: 'random', difficulty: 'easy' },
  { question: 'What is 50 percent of 100?', category: 'random', difficulty: 'easy' },
  { question: 'How many seconds are in a minute?', category: 'random', difficulty: 'easy' },
  { question: 'What is the freezing point of water in Celsius?', category: 'random', difficulty: 'easy' },
  { question: 'How many stripes are on the US flag?', category: 'random', difficulty: 'medium' },
  { question: 'What is 12 times 12?', category: 'random', difficulty: 'medium' },
  { question: 'How many legs does a beetle have?', category: 'random', difficulty: 'easy' },
  { question: 'What is the chemical symbol for gold?', category: 'science', difficulty: 'easy' },
  { question: 'How many planets are in our solar system?', category: 'science', difficulty: 'easy' },
  { question: 'What organ pumps blood?', category: 'science', difficulty: 'easy' },
  { question: 'What is H2O?', category: 'science', difficulty: 'easy' },
  { question: 'What gas do humans breathe out?', category: 'science', difficulty: 'easy' },
  { question: 'How many wings does a butterfly have?', category: 'science', difficulty: 'easy' },
  { question: 'What is the closest star to Earth?', category: 'science', difficulty: 'easy' },
  { question: 'What is the hardest natural substance?', category: 'science', difficulty: 'medium' },
  { question: 'How many chromosomes do humans have?', category: 'science', difficulty: 'hard' },
  { question: 'What planet is closest to the sun?', category: 'science', difficulty: 'easy' },
  { question: 'What is the capital of Germany?', category: 'geography', difficulty: 'easy' },
  { question: 'Which country has the Pyramids?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Italy?', category: 'geography', difficulty: 'easy' },
  { question: 'Which ocean is between America and Europe?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Canada?', category: 'geography', difficulty: 'easy' },
  { question: 'Which country is the Leaning Tower of Pisa in?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the longest mountain range?', category: 'geography', difficulty: 'medium' },
  { question: 'Which country has the Great Wall?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Mexico?', category: 'geography', difficulty: 'easy' },
  { question: 'In which country is the Statue of Liberty?', category: 'geography', difficulty: 'easy' },
  { question: 'What vegetable is used to make french fries?', category: 'food', difficulty: 'easy' },
  { question: 'What color is an apple?', category: 'food', difficulty: 'easy' },
  { question: 'What do you put in a toaster?', category: 'food', difficulty: 'easy' },
  { question: 'What is the main ingredient in hummus?', category: 'food', difficulty: 'easy' },
  { question: 'What fruit is green on the outside and red inside?', category: 'food', difficulty: 'easy' },
  { question: 'What do you add to tea to make it sweet?', category: 'food', difficulty: 'easy' },
  { question: 'What is ketchup made from?', category: 'food', difficulty: 'easy' },
  { question: 'What color is milk?', category: 'food', difficulty: 'easy' },
  { question: 'What grain is used to make rice?', category: 'food', difficulty: 'easy' },
  { question: 'What is the main ingredient in guacamole?', category: 'food', difficulty: 'easy' },
  { question: 'How many points is a touchdown worth?', category: 'sports', difficulty: 'easy' },
  { question: 'In which sport do you hit a shuttlecock?', category: 'sports', difficulty: 'easy' },
  { question: 'How many players are on a baseball team?', category: 'sports', difficulty: 'medium' },
  { question: 'What color jersey does the leader of the Tour de France wear?', category: 'sports', difficulty: 'medium' },
  { question: 'In which sport do you bowl?', category: 'sports', difficulty: 'easy' },
  { question: 'How many Grand Slam titles did Serena Williams win?', category: 'sports', difficulty: 'hard' },
  { question: 'What shape is a football?', category: 'sports', difficulty: 'easy' },
  { question: 'In which country did marathon running start?', category: 'sports', difficulty: 'medium' },
  { question: 'How many rings are on the Olympic flag?', category: 'sports', difficulty: 'easy' },
  { question: 'What sport uses a net and a ball?', category: 'sports', difficulty: 'easy' },
  { question: 'How many keys does a standard piano have?', category: 'music', difficulty: 'medium' },
  { question: 'What instrument did Elvis play?', category: 'music', difficulty: 'easy' },
  { question: 'How many strings does a ukulele have?', category: 'music', difficulty: 'easy' },
  { question: 'What is the lowest singing voice?', category: 'music', difficulty: 'easy' },
  { question: 'In which city is the Opera House famous?', category: 'music', difficulty: 'medium' },
  { question: 'What band had "Bohemian Rhapsody"?', category: 'music', difficulty: 'easy' },
  { question: 'How many members are in a quartet?', category: 'music', difficulty: 'easy' },
  { question: 'What instrument has a slide?', category: 'music', difficulty: 'easy' },
  { question: 'What genre is Beethoven?', category: 'music', difficulty: 'easy' },
  { question: 'How many albums did the Beatles release?', category: 'music', difficulty: 'hard' },
  { question: 'In which film does a boy go to wizard school?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the shark in Jaws?', category: 'movies', difficulty: 'easy' },
  { question: 'Which film has "I will find you"?', category: 'movies', difficulty: 'medium' },
  { question: 'What animal is Donkey in Shrek?', category: 'movies', difficulty: 'easy' },
  { question: 'In which film does a robot say "I will be back"?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the dragon in How to Train Your Dragon?', category: 'movies', difficulty: 'easy' },
  { question: 'Which studio made Toy Story?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the lion in The Lion King?', category: 'movies', difficulty: 'easy' },
  { question: 'In which film does a girl have long magical hair?', category: 'movies', difficulty: 'easy' },
  { question: 'What vehicle does Doc use in Back to the Future?', category: 'movies', difficulty: 'easy' },
  { question: 'What is 20 plus 30?', category: 'general', difficulty: 'easy' },
  { question: 'How many noses does a person have?', category: 'general', difficulty: 'easy' },
  { question: 'What do you hear with?', category: 'general', difficulty: 'easy' },
  { question: 'What is the opposite of wet?', category: 'general', difficulty: 'easy' },
  { question: 'How many corners does a rectangle have?', category: 'general', difficulty: 'easy' },
  { question: 'What do cows give us?', category: 'general', difficulty: 'easy' },
  { question: 'What do you use to smell?', category: 'general', difficulty: 'easy' },
  { question: 'What season do leaves fall?', category: 'general', difficulty: 'easy' },
  { question: 'How many legs does a table usually have?', category: 'general', difficulty: 'easy' },
  { question: 'What is 9 minus 4?', category: 'general', difficulty: 'easy' },
  { question: 'What do chickens lay?', category: 'general', difficulty: 'easy' },
  { question: 'What is the opposite of light?', category: 'general', difficulty: 'easy' },
  { question: 'How many wings does a bird have?', category: 'general', difficulty: 'easy' },
  { question: 'What do you use to brush your teeth?', category: 'general', difficulty: 'easy' },
  { question: 'What would be the worst thing to say at a wedding?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst thing to drop in public?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a terrible name for a dentist?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the silliest thing to collect?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst superpower at a job interview?', category: 'funny', difficulty: 'easy' },
  { question: 'Would you rather have sticky fingers forever or sweaty feet forever?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather have a clock that goes backward or one that is always wrong?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather only be able to whisper or only be able to shout?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather have no hair or hair everywhere?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Would you rather be able to talk to plants or to insects?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'What is 6 times 7?', category: 'random', difficulty: 'medium' },
  { question: 'How many days are in February in a leap year?', category: 'random', difficulty: 'easy' },
  { question: 'What number comes after 99?', category: 'random', difficulty: 'easy' },
  { question: 'How many legs does a crab have?', category: 'random', difficulty: 'easy' },
  { question: 'What is 25 percent of 200?', category: 'random', difficulty: 'medium' },
  { question: 'What is the chemical symbol for iron?', category: 'science', difficulty: 'medium' },
  { question: 'How many lungs do humans have?', category: 'science', difficulty: 'easy' },
  { question: 'What is the largest organ of the human body?', category: 'science', difficulty: 'medium' },
  { question: 'What planet has rings?', category: 'science', difficulty: 'easy' },
  { question: 'What do caterpillars turn into?', category: 'science', difficulty: 'easy' },
  { question: 'What is the capital of England?', category: 'geography', difficulty: 'easy' },
  { question: 'Which sea is the Dead Sea?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the capital of India?', category: 'geography', difficulty: 'easy' },
  { question: 'Which continent has the most countries?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the capital of South Korea?', category: 'geography', difficulty: 'easy' },
  { question: 'What nut is used to make peanut butter?', category: 'food', difficulty: 'easy' },
  { question: 'What fruit do you get from an orange tree?', category: 'food', difficulty: 'easy' },
  { question: 'What is the main ingredient in butter?', category: 'food', difficulty: 'easy' },
  { question: 'What vegetable is purple and round?', category: 'food', difficulty: 'easy' },
  { question: 'What do you call the meal you eat in the middle of the day?', category: 'food', difficulty: 'easy' },
  { question: 'How many players are on a volleyball team?', category: 'sports', difficulty: 'easy' },
  { question: 'What color is the ball in tennis?', category: 'sports', difficulty: 'easy' },
  { question: 'In which sport do you ride a horse?', category: 'sports', difficulty: 'easy' },
  { question: 'How many holes are on a golf course?', category: 'sports', difficulty: 'medium' },
  { question: 'What sport is played in the Super Bowl?', category: 'sports', difficulty: 'easy' },
  { question: 'What instrument is often played in jazz?', category: 'music', difficulty: 'easy' },
  { question: 'How many strings does a bass guitar have?', category: 'music', difficulty: 'easy' },
  { question: 'What is a group of four singers called?', category: 'music', difficulty: 'medium' },
  { question: 'What band sang "Stairway to Heaven"?', category: 'music', difficulty: 'easy' },
  { question: 'What note comes after G in the scale?', category: 'music', difficulty: 'medium' },
  { question: 'In which film does a boy discover he is a wizard?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the princess in Frozen?', category: 'movies', difficulty: 'easy' },
  { question: 'Which film has a character named Dory?', category: 'movies', difficulty: 'easy' },
  { question: 'In which film do cars come to life?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the snowman in Frozen?', category: 'movies', difficulty: 'easy' },
];
