module.exports = [
  { question: 'What color is the sky?', category: 'general', difficulty: 'easy' },
  { question: 'How many legs does a dog have?', category: 'general', difficulty: 'easy' },
  { question: 'What is 2 + 2?', category: 'general', difficulty: 'easy' },
  { question: 'What is the capital of France?', category: 'general', difficulty: 'easy' },
  { question: 'What animal says "moo"?', category: 'general', difficulty: 'easy' },
  { question: 'How many days are in a week?', category: 'general', difficulty: 'easy' },
  { question: 'What shape is a ball?', category: 'general', difficulty: 'easy' },
  { question: 'What do you use to write on paper?', category: 'general', difficulty: 'easy' },
  { question: 'What is the opposite of hot?', category: 'general', difficulty: 'easy' },
  { question: 'How many fingers do you have on one hand?', category: 'general', difficulty: 'easy' },
  { question: 'What planet do we live on?', category: 'general', difficulty: 'easy' },
  { question: 'What color is grass?', category: 'general', difficulty: 'easy' },
  { question: 'What is the largest ocean?', category: 'general', difficulty: 'medium' },
  { question: 'How many continents are there?', category: 'general', difficulty: 'easy' },
  { question: 'What language do people speak in Spain?', category: 'general', difficulty: 'easy' },
  { question: 'What season comes after summer?', category: 'general', difficulty: 'easy' },
  { question: 'How many hours are in a day?', category: 'general', difficulty: 'easy' },
  { question: 'What is the tallest animal?', category: 'general', difficulty: 'easy' },
  { question: 'What do bees make?', category: 'general', difficulty: 'easy' },
  { question: 'What is 10 minus 3?', category: 'general', difficulty: 'easy' },
  { question: 'What is the opposite of up?', category: 'general', difficulty: 'easy' },
  { question: 'How many wheels does a car have?', category: 'general', difficulty: 'easy' },
  { question: 'What do you call a baby cat?', category: 'general', difficulty: 'easy' },
  { question: 'What fruit is yellow and curved?', category: 'general', difficulty: 'easy' },
  { question: 'What do you wear on your feet?', category: 'general', difficulty: 'easy' },
  { question: 'What is the funniest thing you have ever seen?', category: 'funny', difficulty: 'medium' },
  { question: 'What would be the worst name for a pet?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the silliest superpower you can think of?', category: 'funny', difficulty: 'easy' },
  { question: 'If you could only eat one food forever, what would it be?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst advice you could give someone?', category: 'funny', difficulty: 'medium' },
  { question: 'What would you name your boat?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst gift you could receive?', category: 'funny', difficulty: 'easy' },
  { question: 'What animal would be the worst to be reincarnated as?', category: 'funny', difficulty: 'medium' },
  { question: 'What is the most boring thing you can imagine?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a terrible name for a restaurant?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst superpower?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst vegetable?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a bad name for a band?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst thing to forget on a trip?', category: 'funny', difficulty: 'easy' },
  { question: 'Would you rather have hands for feet or feet for hands?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather always be 10 minutes late or 20 minutes early?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather have no phone or no TV?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather eat only sweet or only salty food?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather live in the past or the future?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather be able to fly or be invisible?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather have summer or winter all year?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather have a cat or a dog?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather never use social media or never watch movies?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather speak all languages or talk to animals?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather have unlimited pizza or unlimited sushi?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather be able to teleport or time travel?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather lose your voice or your hearing?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather have a tiny elephant or a giant hamster?', category: 'general', difficulty: 'easy' },
  { question: 'What day is it today?', category: 'random', difficulty: 'easy' },
  { question: 'What month is it?', category: 'random', difficulty: 'easy' },
  { question: 'What is the first letter of the alphabet?', category: 'random', difficulty: 'easy' },
  { question: 'How many sides does a triangle have?', category: 'random', difficulty: 'easy' },
  { question: 'What is the opposite of day?', category: 'random', difficulty: 'easy' },
  { question: 'What do you call a baby dog?', category: 'random', difficulty: 'easy' },
  { question: 'What is the fastest land animal?', category: 'random', difficulty: 'medium' },
  { question: 'How many legs does a spider have?', category: 'random', difficulty: 'easy' },
  { question: 'What is the smallest continent?', category: 'random', difficulty: 'medium' },
  { question: 'What is 100 divided by 10?', category: 'random', difficulty: 'easy' },
  { question: 'How many months are in a year?', category: 'random', difficulty: 'easy' },
  { question: 'What is 5 times 5?', category: 'random', difficulty: 'easy' },
  { question: 'How many colors are in a rainbow?', category: 'random', difficulty: 'easy' },
  { question: 'What is the largest planet in our solar system?', category: 'science', difficulty: 'easy' },
  { question: 'How many bones are in the adult human body?', category: 'science', difficulty: 'medium' },
  { question: 'What is the chemical symbol for water?', category: 'science', difficulty: 'easy' },
  { question: 'What force keeps us on the ground?', category: 'science', difficulty: 'easy' },
  { question: 'What gas do plants absorb from the air?', category: 'science', difficulty: 'easy' },
  { question: 'How many teeth does an adult usually have?', category: 'science', difficulty: 'medium' },
  { question: 'What is the boiling point of water in Celsius?', category: 'science', difficulty: 'easy' },
  { question: 'What planet is known as the Red Planet?', category: 'science', difficulty: 'easy' },
  { question: 'What is the speed of light?', category: 'science', difficulty: 'hard' },
  { question: 'How many hearts does an octopus have?', category: 'science', difficulty: 'medium' },
  { question: 'What is the capital of Japan?', category: 'geography', difficulty: 'easy' },
  { question: 'Which is the longest river in the world?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the largest country by area?', category: 'geography', difficulty: 'easy' },
  { question: 'In which continent is Egypt?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Australia?', category: 'geography', difficulty: 'easy' },
  { question: 'Which ocean is the coldest?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the smallest country in the world?', category: 'geography', difficulty: 'medium' },
  { question: 'Which country has the most people?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Brazil?', category: 'geography', difficulty: 'easy' },
  { question: 'In which country is the Eiffel Tower?', category: 'geography', difficulty: 'easy' },
  { question: 'What fruit do raisins come from?', category: 'food', difficulty: 'easy' },
  { question: 'What color is a carrot?', category: 'food', difficulty: 'easy' },
  { question: 'What do you get when you freeze water?', category: 'food', difficulty: 'easy' },
  { question: 'What is the main ingredient in bread?', category: 'food', difficulty: 'easy' },
  { question: 'What country did pizza originate from?', category: 'food', difficulty: 'easy' },
  { question: 'What color is a banana when it is ripe?', category: 'food', difficulty: 'easy' },
  { question: 'What vegetable is used to make pickles?', category: 'food', difficulty: 'easy' },
  { question: 'What is honey made by?', category: 'food', difficulty: 'easy' },
  { question: 'What type of food is sushi?', category: 'food', difficulty: 'easy' },
  { question: 'What fruit is red and has seeds on the outside?', category: 'food', difficulty: 'easy' },
  { question: 'How many players are on a soccer team?', category: 'sports', difficulty: 'easy' },
  { question: 'What color is the middle ring in the Olympic flag?', category: 'sports', difficulty: 'medium' },
  { question: 'In which sport do you score a touchdown?', category: 'sports', difficulty: 'easy' },
  { question: 'How many Grand Slam tournaments are there in tennis?', category: 'sports', difficulty: 'medium' },
  { question: 'What shape is a basketball?', category: 'sports', difficulty: 'easy' },
  { question: 'In which sport do you use a puck?', category: 'sports', difficulty: 'easy' },
  { question: 'How many laps is the Indy 500?', category: 'sports', difficulty: 'medium' },
  { question: 'What country invented the sport of golf?', category: 'sports', difficulty: 'medium' },
  { question: 'How many players are on a basketball team?', category: 'sports', difficulty: 'easy' },
  { question: 'What sport is played at Wimbledon?', category: 'sports', difficulty: 'easy' },
  { question: 'How many strings does a standard guitar have?', category: 'music', difficulty: 'easy' },
  { question: 'What instrument has black and white keys?', category: 'music', difficulty: 'easy' },
  { question: 'How many beats are in a waltz?', category: 'music', difficulty: 'medium' },
  { question: 'What is the largest instrument in an orchestra?', category: 'music', difficulty: 'easy' },
  { question: 'What band sang "Yellow Submarine"?', category: 'music', difficulty: 'easy' },
  { question: 'How many notes are in an octave?', category: 'music', difficulty: 'medium' },
  { question: 'What instrument does a drummer play?', category: 'music', difficulty: 'easy' },
  { question: 'In which country did opera originate?', category: 'music', difficulty: 'medium' },
  { question: 'What is the highest singing voice?', category: 'music', difficulty: 'easy' },
  { question: 'How many strings does a violin have?', category: 'music', difficulty: 'easy' },
  { question: 'In which movie does a lion become king?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the wizard in The Wizard of Oz?', category: 'movies', difficulty: 'easy' },
  { question: 'Which studio made Frozen?', category: 'movies', difficulty: 'easy' },
  { question: 'What animal is Remy in Ratatouille?', category: 'movies', difficulty: 'easy' },
  { question: 'In which movie does a boy find a genie in a lamp?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the fish in Finding Nemo?', category: 'movies', difficulty: 'easy' },
  { question: 'Which movie has a character named Simba?', category: 'movies', difficulty: 'easy' },
  { question: 'What color is Cinderella\'s dress?', category: 'movies', difficulty: 'easy' },
  { question: 'In which movie do toys come to life?', category: 'movies', difficulty: 'easy' },
  { question: 'What kind of animal is Dumbo?', category: 'movies', difficulty: 'easy' },
  { question: 'What is 3 times 4?', category: 'general', difficulty: 'easy' },
  { question: 'How many eyes does a person have?', category: 'general', difficulty: 'easy' },
  { question: 'What is the sun?', category: 'general', difficulty: 'easy' },
  { question: 'What do birds use to fly?', category: 'general', difficulty: 'easy' },
  { question: 'What is snow made of?', category: 'general', difficulty: 'easy' },
  { question: 'How many minutes are in an hour?', category: 'general', difficulty: 'easy' },
  { question: 'What is the opposite of big?', category: 'general', difficulty: 'easy' },
  { question: 'What do you use to see?', category: 'general', difficulty: 'easy' },
  { question: 'What animal has a long trunk?', category: 'general', difficulty: 'easy' },
  { question: 'What color is the sun?', category: 'general', difficulty: 'easy' },
  { question: 'How many sides does a square have?', category: 'general', difficulty: 'easy' },
  { question: 'What do fish breathe?', category: 'general', difficulty: 'easy' },
  { question: 'What falls from the sky when it rains?', category: 'general', difficulty: 'easy' },
  { question: 'What is 15 plus 15?', category: 'general', difficulty: 'easy' },
  { question: 'What do you call a baby sheep?', category: 'general', difficulty: 'easy' },
  { question: 'How many legs does a chair have?', category: 'general', difficulty: 'easy' },
  { question: 'What is the opposite of fast?', category: 'general', difficulty: 'easy' },
  { question: 'What do you read in a book?', category: 'general', difficulty: 'easy' },
  { question: 'What season has the most snow?', category: 'general', difficulty: 'easy' },
  { question: 'What would be the worst job title?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the most useless invention?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a bad name for a soap?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst flavor of ice cream?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a terrible password?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the silliest way to travel?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst thing to be allergic to?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the most embarrassing thing to forget?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a bad name for a hospital?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst superpower to have at a party?', category: 'funny', difficulty: 'easy' },
  { question: 'Would you rather have no taste or no smell?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather fight one horse-sized duck or 100 duck-sized horses?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather have a rewind or pause button for life?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather always sing or always whisper?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather have no eyebrows or no eyelashes?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather be famous or rich?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather have a tail or horns?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather live without music or without movies?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather have a personal chef or a personal pilot?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather know when you die or how you die?', category: 'general', difficulty: 'easy' },
  { question: 'What is 7 times 8?', category: 'random', difficulty: 'medium' },
  { question: 'How many zeros are in one thousand?', category: 'random', difficulty: 'easy' },
  { question: 'What is the last letter of the alphabet?', category: 'random', difficulty: 'easy' },
  { question: 'How many sides does a hexagon have?', category: 'random', difficulty: 'easy' },
  { question: 'What is 50 percent of 100?', category: 'random', difficulty: 'easy' },
  { question: 'How many seconds are in a minute?', category: 'random', difficulty: 'easy' },
  { question: 'What is the freezing point of water in Celsius?', category: 'random', difficulty: 'easy' },
  { question: 'How many stripes are on the US flag?', category: 'random', difficulty: 'medium' },
  { question: 'What is 12 times 12?', category: 'random', difficulty: 'medium' },
  { question: 'How many legs does a beetle have?', category: 'random', difficulty: 'easy' },
  { question: 'What is the chemical symbol for gold?', category: 'science', difficulty: 'easy' },
  { question: 'How many planets are in our solar system?', category: 'science', difficulty: 'easy' },
  { question: 'What organ pumps blood?', category: 'science', difficulty: 'easy' },
  { question: 'What is H2O?', category: 'science', difficulty: 'easy' },
  { question: 'What gas do humans breathe out?', category: 'science', difficulty: 'easy' },
  { question: 'How many wings does a butterfly have?', category: 'science', difficulty: 'easy' },
  { question: 'What is the closest star to Earth?', category: 'science', difficulty: 'easy' },
  { question: 'What is the hardest natural substance?', category: 'science', difficulty: 'medium' },
  { question: 'How many chromosomes do humans have?', category: 'science', difficulty: 'hard' },
  { question: 'What planet is closest to the sun?', category: 'science', difficulty: 'easy' },
  { question: 'What is the capital of Germany?', category: 'geography', difficulty: 'easy' },
  { question: 'Which country has the Pyramids?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Italy?', category: 'geography', difficulty: 'easy' },
  { question: 'Which ocean is between America and Europe?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Canada?', category: 'geography', difficulty: 'easy' },
  { question: 'Which country is the Leaning Tower of Pisa in?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the longest mountain range?', category: 'geography', difficulty: 'medium' },
  { question: 'Which country has the Great Wall?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Mexico?', category: 'geography', difficulty: 'easy' },
  { question: 'In which country is the Statue of Liberty?', category: 'geography', difficulty: 'easy' },
  { question: 'What vegetable is used to make french fries?', category: 'food', difficulty: 'easy' },
  { question: 'What color is an apple?', category: 'food', difficulty: 'easy' },
  { question: 'What do you put in a toaster?', category: 'food', difficulty: 'easy' },
  { question: 'What is the main ingredient in hummus?', category: 'food', difficulty: 'easy' },
  { question: 'What fruit is green on the outside and red inside?', category: 'food', difficulty: 'easy' },
  { question: 'What do you add to tea to make it sweet?', category: 'food', difficulty: 'easy' },
  { question: 'What is ketchup made from?', category: 'food', difficulty: 'easy' },
  { question: 'What color is milk?', category: 'food', difficulty: 'easy' },
  { question: 'What grain is used to make rice?', category: 'food', difficulty: 'easy' },
  { question: 'What is the main ingredient in guacamole?', category: 'food', difficulty: 'easy' },
  { question: 'How many points is a touchdown worth?', category: 'sports', difficulty: 'easy' },
  { question: 'In which sport do you hit a shuttlecock?', category: 'sports', difficulty: 'easy' },
  { question: 'How many players are on a baseball team?', category: 'sports', difficulty: 'medium' },
  { question: 'What color jersey does the leader of the Tour de France wear?', category: 'sports', difficulty: 'medium' },
  { question: 'In which sport do you bowl?', category: 'sports', difficulty: 'easy' },
  { question: 'How many Grand Slam titles did Serena Williams win?', category: 'sports', difficulty: 'hard' },
  { question: 'What shape is a football?', category: 'sports', difficulty: 'easy' },
  { question: 'In which country did marathon running start?', category: 'sports', difficulty: 'medium' },
  { question: 'How many rings are on the Olympic flag?', category: 'sports', difficulty: 'easy' },
  { question: 'What sport uses a net and a ball?', category: 'sports', difficulty: 'easy' },
  { question: 'How many keys does a standard piano have?', category: 'music', difficulty: 'medium' },
  { question: 'What instrument did Elvis play?', category: 'music', difficulty: 'easy' },
  { question: 'How many strings does a ukulele have?', category: 'music', difficulty: 'easy' },
  { question: 'What is the lowest singing voice?', category: 'music', difficulty: 'easy' },
  { question: 'In which city is the Opera House famous?', category: 'music', difficulty: 'medium' },
  { question: 'What band had "Bohemian Rhapsody"?', category: 'music', difficulty: 'easy' },
  { question: 'How many members are in a quartet?', category: 'music', difficulty: 'easy' },
  { question: 'What instrument has a slide?', category: 'music', difficulty: 'easy' },
  { question: 'What genre is Beethoven?', category: 'music', difficulty: 'easy' },
  { question: 'How many albums did the Beatles release?', category: 'music', difficulty: 'hard' },
  { question: 'In which film does a boy go to wizard school?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the shark in Jaws?', category: 'movies', difficulty: 'easy' },
  { question: 'Which film has "I will find you"?', category: 'movies', difficulty: 'medium' },
  { question: 'What animal is Donkey in Shrek?', category: 'movies', difficulty: 'easy' },
  { question: 'In which film does a robot say "I will be back"?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the dragon in How to Train Your Dragon?', category: 'movies', difficulty: 'easy' },
  { question: 'Which studio made Toy Story?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the lion in The Lion King?', category: 'movies', difficulty: 'easy' },
  { question: 'In which film does a girl have long magical hair?', category: 'movies', difficulty: 'easy' },
  { question: 'What vehicle does Doc use in Back to the Future?', category: 'movies', difficulty: 'easy' },
  { question: 'What is 20 plus 30?', category: 'general', difficulty: 'easy' },
  { question: 'How many noses does a person have?', category: 'general', difficulty: 'easy' },
  { question: 'What do you hear with?', category: 'general', difficulty: 'easy' },
  { question: 'What is the opposite of wet?', category: 'general', difficulty: 'easy' },
  { question: 'How many corners does a rectangle have?', category: 'general', difficulty: 'easy' },
  { question: 'What do cows give us?', category: 'general', difficulty: 'easy' },
  { question: 'What do you use to smell?', category: 'general', difficulty: 'easy' },
  { question: 'What season do leaves fall?', category: 'general', difficulty: 'easy' },
  { question: 'How many legs does a table usually have?', category: 'general', difficulty: 'easy' },
  { question: 'What is 9 minus 4?', category: 'general', difficulty: 'easy' },
  { question: 'What do chickens lay?', category: 'general', difficulty: 'easy' },
  { question: 'What is the opposite of light?', category: 'general', difficulty: 'easy' },
  { question: 'How many wings does a bird have?', category: 'general', difficulty: 'easy' },
  { question: 'What do you use to brush your teeth?', category: 'general', difficulty: 'easy' },
  { question: 'What would be the worst thing to say at a wedding?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst thing to drop in public?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a terrible name for a dentist?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the silliest thing to collect?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst superpower at a job interview?', category: 'funny', difficulty: 'easy' },
  { question: 'Would you rather have sticky fingers forever or sweaty feet forever?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather have a clock that goes backward or one that is always wrong?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather only be able to whisper or only be able to shout?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather have no hair or hair everywhere?', category: 'general', difficulty: 'easy' },
  { question: 'Would you rather be able to talk to plants or to insects?', category: 'general', difficulty: 'easy' },
  { question: 'What is 6 times 7?', category: 'random', difficulty: 'medium' },
  { question: 'How many days are in February in a leap year?', category: 'random', difficulty: 'easy' },
  { question: 'What number comes after 99?', category: 'random', difficulty: 'easy' },
  { question: 'How many legs does a crab have?', category: 'random', difficulty: 'easy' },
  { question: 'What is 25 percent of 200?', category: 'random', difficulty: 'medium' },
  { question: 'What is the chemical symbol for iron?', category: 'science', difficulty: 'medium' },
  { question: 'How many lungs do humans have?', category: 'science', difficulty: 'easy' },
  { question: 'What is the largest organ of the human body?', category: 'science', difficulty: 'medium' },
  { question: 'What planet has rings?', category: 'science', difficulty: 'easy' },
  { question: 'What do caterpillars turn into?', category: 'science', difficulty: 'easy' },
  { question: 'What is the capital of England?', category: 'geography', difficulty: 'easy' },
  { question: 'Which sea is the Dead Sea?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the capital of India?', category: 'geography', difficulty: 'easy' },
  { question: 'Which continent has the most countries?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the capital of South Korea?', category: 'geography', difficulty: 'easy' },
  { question: 'What nut is used to make peanut butter?', category: 'food', difficulty: 'easy' },
  { question: 'What fruit do you get from an orange tree?', category: 'food', difficulty: 'easy' },
  { question: 'What is the main ingredient in butter?', category: 'food', difficulty: 'easy' },
  { question: 'What vegetable is purple and round?', category: 'food', difficulty: 'easy' },
  { question: 'What do you call the meal you eat in the middle of the day?', category: 'food', difficulty: 'easy' },
  { question: 'How many players are on a volleyball team?', category: 'sports', difficulty: 'easy' },
  { question: 'What color is the ball in tennis?', category: 'sports', difficulty: 'easy' },
  { question: 'In which sport do you ride a horse?', category: 'sports', difficulty: 'easy' },
  { question: 'How many holes are on a golf course?', category: 'sports', difficulty: 'medium' },
  { question: 'What sport is played in the Super Bowl?', category: 'sports', difficulty: 'easy' },
  { question: 'What instrument is often played in jazz?', category: 'music', difficulty: 'easy' },
  { question: 'How many strings does a bass guitar have?', category: 'music', difficulty: 'easy' },
  { question: 'What is a group of four singers called?', category: 'music', difficulty: 'medium' },
  { question: 'What band sang "Stairway to Heaven"?', category: 'music', difficulty: 'easy' },
  { question: 'What note comes after G in the scale?', category: 'music', difficulty: 'medium' },
  { question: 'In which film does a boy discover he is a wizard?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the princess in Frozen?', category: 'movies', difficulty: 'easy' },
  { question: 'Which film has a character named Dory?', category: 'movies', difficulty: 'easy' },
  { question: 'In which film do cars come to life?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the snowman in Frozen?', category: 'movies', difficulty: 'easy' },
  { question: 'In which year did World War II end?', category: 'history', difficulty: 'easy' },
  { question: 'Who was the first person to walk on the moon?', category: 'history', difficulty: 'easy' },
  { question: 'Which empire built the Colosseum?', category: 'history', difficulty: 'easy' },
  { question: 'In which country did the Renaissance begin?', category: 'history', difficulty: 'medium' },
  { question: 'Who wrote the Declaration of Independence?', category: 'history', difficulty: 'easy' },
  { question: 'Which ancient wonder was in Egypt?', category: 'history', difficulty: 'easy' },
  { question: 'When did the Berlin Wall fall?', category: 'history', difficulty: 'medium' },
  { question: 'Who invented the light bulb?', category: 'history', difficulty: 'easy' },
  { question: 'Which civilization built Machu Picchu?', category: 'history', difficulty: 'medium' },
  { question: 'In which century did World War I start?', category: 'history', difficulty: 'medium' },
  { question: 'Who was the first president of the United States?', category: 'history', difficulty: 'easy' },
  { question: 'Which country gave the Statue of Liberty to the USA?', category: 'history', difficulty: 'easy' },
  { question: 'Who painted the Mona Lisa?', category: 'history', difficulty: 'easy' },
  { question: 'When did humans first land on the moon?', category: 'history', difficulty: 'easy' },
  { question: 'Which empire had the Great Wall built?', category: 'history', difficulty: 'easy' },
  { question: 'Who discovered America in 1492?', category: 'history', difficulty: 'easy' },
  { question: 'What does CPU stand for?', category: 'technology', difficulty: 'easy' },
  { question: 'Who founded Facebook?', category: 'technology', difficulty: 'easy' },
  { question: 'What year was the first iPhone released?', category: 'technology', difficulty: 'medium' },
  { question: 'What does WiFi stand for?', category: 'technology', difficulty: 'medium' },
  { question: 'Which company makes the PlayStation?', category: 'technology', difficulty: 'easy' },
  { question: 'What does USB stand for?', category: 'technology', difficulty: 'medium' },
  { question: 'Who created Microsoft?', category: 'technology', difficulty: 'easy' },
  { question: 'What is the name of Google\'s assistant?', category: 'technology', difficulty: 'easy' },
  { question: 'How many bits are in a byte?', category: 'technology', difficulty: 'medium' },
  { question: 'What does HTML stand for?', category: 'technology', difficulty: 'easy' },
  { question: 'Which company created the Android operating system?', category: 'technology', difficulty: 'easy' },
  { question: 'What does GPS stand for?', category: 'technology', difficulty: 'easy' },
  { question: 'What is the name of Amazon\'s voice assistant?', category: 'technology', difficulty: 'easy' },
  { question: 'In what year was YouTube founded?', category: 'technology', difficulty: 'medium' },
  { question: 'What does RAM stand for?', category: 'technology', difficulty: 'medium' },
  { question: 'Which animal is the fastest on land?', category: 'nature', difficulty: 'easy' },
  { question: 'What is the largest mammal on Earth?', category: 'nature', difficulty: 'easy' },
  { question: 'How many legs does an insect have?', category: 'nature', difficulty: 'easy' },
  { question: 'What is the only mammal that can fly?', category: 'nature', difficulty: 'easy' },
  { question: 'Which planet is known as the Red Planet?', category: 'nature', difficulty: 'easy' },
  { question: 'What is the largest type of bear?', category: 'nature', difficulty: 'easy' },
  { question: 'How many stomachs does a cow have?', category: 'nature', difficulty: 'medium' },
  { question: 'What is the tallest tree species?', category: 'nature', difficulty: 'medium' },
  { question: 'Which bird cannot fly?', category: 'nature', difficulty: 'easy' },
  { question: 'What is the smallest bird in the world?', category: 'nature', difficulty: 'medium' },
  { question: 'How many arms does an octopus have?', category: 'nature', difficulty: 'easy' },
  { question: 'What is the largest ocean animal?', category: 'nature', difficulty: 'easy' },
  { question: 'Which animal sleeps the most?', category: 'nature', difficulty: 'medium' },
  { question: 'What is the only continent without reptiles?', category: 'nature', difficulty: 'hard' },
  { question: 'How many bones are in a giraffe\'s neck?', category: 'nature', difficulty: 'medium' },
  { question: 'What is the capital of France?', category: 'travel', difficulty: 'easy' },
  { question: 'Which country has the most islands?', category: 'travel', difficulty: 'medium' },
  { question: 'What is the longest river in Europe?', category: 'travel', difficulty: 'medium' },
  { question: 'In which city is the Acropolis?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of Thailand?', category: 'travel', difficulty: 'easy' },
  { question: 'Which country is the Taj Mahal in?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the smallest country in the world?', category: 'travel', difficulty: 'easy' },
  { question: 'In which city would you find the Empire State Building?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of Egypt?', category: 'travel', difficulty: 'easy' },
  { question: 'Which continent is the Sahara Desert in?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of Argentina?', category: 'travel', difficulty: 'easy' },
  { question: 'In which country is the Great Barrier Reef?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of South Africa?', category: 'travel', difficulty: 'easy' },
  { question: 'Which European city is split by the Bosphorus?', category: 'travel', difficulty: 'medium' },
  { question: 'What is the highest capital city in the world?', category: 'travel', difficulty: 'hard' },
  { question: 'What is your favorite holiday destination?', category: 'general', difficulty: 'easy' },
  { question: 'What is the best advice you have ever received?', category: 'general', difficulty: 'easy' },
  { question: 'What would you do if you had a free day?', category: 'general', difficulty: 'easy' },
  { question: 'What skill would you like to learn?', category: 'general', difficulty: 'easy' },
  { question: 'What is your favorite way to relax?', category: 'general', difficulty: 'easy' },
  { question: 'What is the strangest dream you have had?', category: 'funny', difficulty: 'medium' },
  { question: 'What would be the worst song to play at a funeral?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the most embarrassing thing in your room?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a terrible name for a pet rock?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst pickup line you have heard?', category: 'funny', difficulty: 'easy' },
  { question: 'How many sides does a stop sign have?', category: 'random', difficulty: 'easy' },
  { question: 'What is 11 times 11?', category: 'random', difficulty: 'medium' },
  { question: 'How many faces does a cube have?', category: 'random', difficulty: 'easy' },
  { question: 'What is the only even prime number?', category: 'random', difficulty: 'medium' },
  { question: 'How many bones are in the human hand?', category: 'science', difficulty: 'medium' },
  { question: 'What is the chemical symbol for sodium?', category: 'science', difficulty: 'easy' },
  { question: 'What planet is farthest from the sun?', category: 'science', difficulty: 'easy' },
  { question: 'What is the smallest bone in the human body?', category: 'science', difficulty: 'hard' },
  { question: 'What gas do we breathe in the most?', category: 'science', difficulty: 'easy' },
  { question: 'What is the capital of Spain?', category: 'geography', difficulty: 'easy' },
  { question: 'Which country has the most volcanoes?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the capital of Russia?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the main ingredient in chocolate?', category: 'food', difficulty: 'easy' },
  { question: 'What fruit is used to make wine?', category: 'food', difficulty: 'easy' },
  { question: 'What is the most consumed meat in the world?', category: 'food', difficulty: 'medium' },
  { question: 'How many players are on a cricket team?', category: 'sports', difficulty: 'medium' },
  { question: 'In which sport do you score a home run?', category: 'sports', difficulty: 'easy' },
  { question: 'What instrument has 88 keys?', category: 'music', difficulty: 'easy' },
  { question: 'Who sang "Thriller"?', category: 'music', difficulty: 'easy' },
  { question: 'In which film does a teenager get bitten by a spider?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the wizard school in Harry Potter?', category: 'movies', difficulty: 'easy' },
  { question: 'What is your favorite memory from childhood?', category: 'general', difficulty: 'easy' },
  { question: 'If you could have dinner with anyone, who would it be?', category: 'general', difficulty: 'easy' },
  { question: 'What is the best book you have ever read?', category: 'general', difficulty: 'easy' },
  { question: 'What would you do if you won the lottery?', category: 'general', difficulty: 'easy' },
  { question: 'What is your favorite season and why?', category: 'general', difficulty: 'easy' },
  { question: 'What hobby would you like to try?', category: 'general', difficulty: 'easy' },
  { question: 'What is the most beautiful place you have been?', category: 'general', difficulty: 'easy' },
  { question: 'What superpower would you choose?', category: 'general', difficulty: 'easy' },
  { question: 'What is your go-to karaoke song?', category: 'general', difficulty: 'easy' },
  { question: 'What is the worst haircut you have had?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst thing to say on a first date?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the funniest autocorrect fail you have seen?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a terrible name for a perfume?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the most ridiculous fashion trend?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst animal to be reincarnated as?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the silliest thing you have ever bought?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a bad name for a gym?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst combination of foods?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst job for a vampire?', category: 'funny', difficulty: 'easy' },
  { question: 'How many degrees are in a right angle?', category: 'random', difficulty: 'easy' },
  { question: 'What is 9 times 9?', category: 'random', difficulty: 'easy' },
  { question: 'How many sides does a pentagon have?', category: 'random', difficulty: 'easy' },
  { question: 'What is the square root of 64?', category: 'random', difficulty: 'easy' },
  { question: 'How many days are in a leap year?', category: 'random', difficulty: 'easy' },
  { question: 'What is 15 percent of 100?', category: 'random', difficulty: 'easy' },
  { question: 'How many continents start with the letter A?', category: 'random', difficulty: 'medium' },
  { question: 'What is the only number that is the same in English and French?', category: 'random', difficulty: 'hard' },
  { question: 'How many keys are on a standard computer keyboard?', category: 'random', difficulty: 'medium' },
  { question: 'What is the largest prime number under 20?', category: 'random', difficulty: 'medium' },
  { question: 'What is the powerhouse of the cell?', category: 'science', difficulty: 'easy' },
  { question: 'How many bones are in the human spine?', category: 'science', difficulty: 'medium' },
  { question: 'What is the chemical symbol for carbon?', category: 'science', difficulty: 'easy' },
  { question: 'What planet is known for its rings?', category: 'science', difficulty: 'easy' },
  { question: 'How many teeth do adults typically have?', category: 'science', difficulty: 'easy' },
  { question: 'What is the smallest planet in our solar system?', category: 'science', difficulty: 'easy' },
  { question: 'What gas makes up most of the atmosphere?', category: 'science', difficulty: 'easy' },
  { question: 'How many chambers does the human heart have?', category: 'science', difficulty: 'easy' },
  { question: 'What is the speed of sound?', category: 'science', difficulty: 'hard' },
  { question: 'What is the chemical symbol for oxygen?', category: 'science', difficulty: 'easy' },
  { question: 'What is the capital of Greece?', category: 'geography', difficulty: 'easy' },
  { question: 'Which country is home to the kangaroo?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Turkey?', category: 'geography', difficulty: 'easy' },
  { question: 'Which river flows through Paris?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Poland?', category: 'geography', difficulty: 'easy' },
  { question: 'Which country has the most population in Africa?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the capital of Sweden?', category: 'geography', difficulty: 'easy' },
  { question: 'Which sea is the saltiest?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the capital of the Netherlands?', category: 'geography', difficulty: 'easy' },
  { question: 'Which mountain is the tallest in the world?', category: 'geography', difficulty: 'easy' },
  { question: 'What vegetable is known as the king of vegetables?', category: 'food', difficulty: 'medium' },
  { question: 'What is the main ingredient in tzatziki?', category: 'food', difficulty: 'easy' },
  { question: 'What nut is in pesto?', category: 'food', difficulty: 'easy' },
  { question: 'What fruit is known as the king of fruits?', category: 'food', difficulty: 'medium' },
  { question: 'What is the primary ingredient in falafel?', category: 'food', difficulty: 'easy' },
  { question: 'What type of cheese is used in Greek salad?', category: 'food', difficulty: 'easy' },
  { question: 'What grain is used to make beer?', category: 'food', difficulty: 'easy' },
  { question: 'What is the main ingredient in guacamole?', category: 'food', difficulty: 'easy' },
  { question: 'What fruit is dried to make prunes?', category: 'food', difficulty: 'easy' },
  { question: 'What is the most expensive spice in the world?', category: 'food', difficulty: 'medium' },
  { question: 'How many players are on a rugby team?', category: 'sports', difficulty: 'medium' },
  { question: 'In which sport do you use a racket and shuttlecock?', category: 'sports', difficulty: 'easy' },
  { question: 'What color is the ball in pool?', category: 'sports', difficulty: 'easy' },
  { question: 'How many Grand Slam tournaments does tennis have per year?', category: 'sports', difficulty: 'easy' },
  { question: 'In which country did basketball originate?', category: 'sports', difficulty: 'easy' },
  { question: 'What is the national sport of Canada?', category: 'sports', difficulty: 'medium' },
  { question: 'How many minutes are in a soccer half?', category: 'sports', difficulty: 'easy' },
  { question: 'In which sport do you score a try?', category: 'sports', difficulty: 'medium' },
  { question: 'What is the diameter of a basketball hoop?', category: 'sports', difficulty: 'hard' },
  { question: 'Which country has won the most World Cups?', category: 'sports', difficulty: 'easy' },
  { question: 'What instrument has 88 keys?', category: 'music', difficulty: 'easy' },
  { question: 'Who is known as the King of Pop?', category: 'music', difficulty: 'easy' },
  { question: 'How many strings does a harp have?', category: 'music', difficulty: 'hard' },
  { question: 'What is the most played song at weddings?', category: 'music', difficulty: 'medium' },
  { question: 'In which city did jazz originate?', category: 'music', difficulty: 'medium' },
  { question: 'What band sang "Sweet Child O\' Mine"?', category: 'music', difficulty: 'easy' },
  { question: 'How many members are in a trio?', category: 'music', difficulty: 'easy' },
  { question: 'What is the highest male singing voice?', category: 'music', difficulty: 'easy' },
  { question: 'Who wrote the Ninth Symphony?', category: 'music', difficulty: 'easy' },
  { question: 'What instrument is known as the king of instruments?', category: 'music', difficulty: 'medium' },
  { question: 'In which film does a boy ride a dragon?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the dragon in Game of Thrones?', category: 'movies', difficulty: 'medium' },
  { question: 'Which film features a talking raccoon?', category: 'movies', difficulty: 'easy' },
  { question: 'In which film does a robot become human?', category: 'movies', difficulty: 'medium' },
  { question: 'What is the name of the ship in Titanic?', category: 'movies', difficulty: 'easy' },
  { question: 'Which studio made Shrek?', category: 'movies', difficulty: 'easy' },
  { question: 'In which film does a clown fish search for his son?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the dinosaur in Jurassic Park?', category: 'movies', difficulty: 'easy' },
  { question: 'Which film has "May the Force be with you"?', category: 'movies', difficulty: 'easy' },
  { question: 'In which year did the Titanic sink?', category: 'movies', difficulty: 'medium' },
  { question: 'Who was the first woman to win a Nobel Prize?', category: 'history', difficulty: 'medium' },
  { question: 'In which year did the French Revolution begin?', category: 'history', difficulty: 'medium' },
  { question: 'Who built the first printing press?', category: 'history', difficulty: 'medium' },
  { question: 'Which empire was ruled by Genghis Khan?', category: 'history', difficulty: 'easy' },
  { question: 'When did the Roman Empire fall?', category: 'history', difficulty: 'hard' },
  { question: 'Who was the British prime minister during World War II?', category: 'history', difficulty: 'easy' },
  { question: 'Which country invented paper?', category: 'history', difficulty: 'medium' },
  { question: 'Who wrote the Odyssey?', category: 'history', difficulty: 'easy' },
  { question: 'In which year did man first fly in an airplane?', category: 'history', difficulty: 'medium' },
  { question: 'Who discovered penicillin?', category: 'history', difficulty: 'medium' },
  { question: 'What does AI stand for?', category: 'technology', difficulty: 'easy' },
  { question: 'Who founded Tesla?', category: 'technology', difficulty: 'easy' },
  { question: 'What year was the first computer virus created?', category: 'technology', difficulty: 'hard' },
  { question: 'What does VPN stand for?', category: 'technology', difficulty: 'medium' },
  { question: 'Which company makes the Switch?', category: 'technology', difficulty: 'easy' },
  { question: 'What does SSD stand for?', category: 'technology', difficulty: 'medium' },
  { question: 'Who created Linux?', category: 'technology', difficulty: 'hard' },
  { question: 'What is the name of Apple\'s voice assistant?', category: 'technology', difficulty: 'easy' },
  { question: 'In what year was the first email sent?', category: 'technology', difficulty: 'hard' },
  { question: 'What does HTTP stand for?', category: 'technology', difficulty: 'medium' },
  { question: 'Which animal can live the longest?', category: 'nature', difficulty: 'medium' },
  { question: 'What is the only mammal that lays eggs?', category: 'nature', difficulty: 'easy' },
  { question: 'How many eyes does a bee have?', category: 'nature', difficulty: 'medium' },
  { question: 'What is the fastest bird?', category: 'nature', difficulty: 'medium' },
  { question: 'Which animal has the longest migration?', category: 'nature', difficulty: 'hard' },
  { question: 'What is the largest land animal?', category: 'nature', difficulty: 'easy' },
  { question: 'How many stomachs does a goat have?', category: 'nature', difficulty: 'medium' },
  { question: 'What is the only bird that can fly backward?', category: 'nature', difficulty: 'medium' },
  { question: 'Which insect is the strongest relative to its size?', category: 'nature', difficulty: 'hard' },
  { question: 'What is the loudest animal on Earth?', category: 'nature', difficulty: 'hard' },
  { question: 'What is the capital of Portugal?', category: 'travel', difficulty: 'easy' },
  { question: 'Which country has the most UNESCO World Heritage sites?', category: 'travel', difficulty: 'hard' },
  { question: 'What is the capital of Norway?', category: 'travel', difficulty: 'easy' },
  { question: 'In which city is the Parthenon?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of Switzerland?', category: 'travel', difficulty: 'easy' },
  { question: 'Which country is the Great Wall in?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of Ireland?', category: 'travel', difficulty: 'easy' },
  { question: 'In which city would you find Big Ben?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of Austria?', category: 'travel', difficulty: 'easy' },
  { question: 'Which country has the most lakes?', category: 'travel', difficulty: 'hard' },
];
