module.exports = [
  { question: '¿De qué color es el cielo?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántas patas tiene un perro?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuánto es 2 + 2?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es la capital de Francia?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué animal hace "mu"?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántos días tiene una semana?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué forma tiene una pelota?', category: 'general', difficulty: 'easy' },
  { question: '¿Con qué se escribe en papel?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es lo contrario de caliente?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántos dedos tienes en una mano?', category: 'general', difficulty: 'easy' },
  { question: '¿En qué planeta vivimos?', category: 'general', difficulty: 'easy' },
  { question: '¿De qué color es la hierba?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es el océano más grande?', category: 'general', difficulty: 'medium' },
  { question: '¿Cuántos continentes hay?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué idioma se habla en España?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué estación viene después del verano?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántas horas tiene un día?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es el animal más alto?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué hacen las abejas?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuánto es 10 menos 3?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es lo contrario de arriba?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántas ruedas tiene un coche?', category: 'general', difficulty: 'easy' },
  { question: '¿Cómo se llama un gato bebé?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué fruta es amarilla y curvada?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué llevas en los pies?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué es lo más gracioso que has visto nunca?', category: 'funny', difficulty: 'medium' },
  { question: '¿Cuál sería el peor nombre para una mascota?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál es el superpoder más tonto que se te ocurre?', category: 'funny', difficulty: 'easy' },
  { question: 'Si solo pudieras comer una cosa para siempre, ¿cuál sería?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería el peor consejo que podrías dar a alguien?', category: 'funny', difficulty: 'medium' },
  { question: '¿Cómo llamarías a tu barco?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería el peor regalo que podrías recibir?', category: 'funny', difficulty: 'easy' },
  { question: '¿Como qué animal sería lo peor reencarnarse?', category: 'funny', difficulty: 'medium' },
  { question: '¿Qué es lo más aburrido que te imaginas?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería un nombre horrible para un restaurante?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería el peor superpoder?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál es la peor verdura?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería un mal nombre para un grupo musical?', category: 'funny', difficulty: 'easy' },
  { question: '¿Qué es lo peor que se puede olvidar en un viaje?', category: 'funny', difficulty: 'easy' },
  { question: '¿Preferirías tener manos por pies o pies por manos?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías llegar siempre 10 minutos tarde o 20 minutos pronto?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías no tener móvil o no tener tele?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías comer solo dulce o solo salado?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías vivir en el pasado o en el futuro?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías poder volar o ser invisible?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías verano o invierno todo el año?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías tener un gato o un perro?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías no usar redes sociales o no ver películas nunca?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías hablar todos los idiomas o hablar con los animales?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías pizza ilimitada o sushi ilimitado?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías poder teletransportarte o viajar en el tiempo?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías perder la voz o el oído?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías tener un elefante diminuto o un hámster gigante?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Qué día es hoy?', category: 'random', difficulty: 'easy' },
  { question: '¿En qué mes estamos?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuál es la primera letra del abecedario?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuántos lados tiene un triángulo?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuál es lo contrario de día?', category: 'random', difficulty: 'easy' },
  { question: '¿Cómo se llama un perro bebé?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuál es el animal terrestre más rápido?', category: 'random', difficulty: 'medium' },
  { question: '¿Cuántas patas tiene una araña?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuál es el continente más pequeño?', category: 'random', difficulty: 'medium' },
  { question: '¿Cuánto es 100 dividido entre 10?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuántos meses tiene un año?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuánto es 5 por 5?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuántos colores tiene un arcoíris?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuál es el planeta más grande de nuestro sistema solar?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuántos huesos tiene un adulto humano?', category: 'science', difficulty: 'medium' },
  { question: '¿Cuál es el símbolo químico del agua?', category: 'science', difficulty: 'easy' },
  { question: '¿Qué fuerza nos mantiene en el suelo?', category: 'science', difficulty: 'easy' },
  { question: '¿Qué gas absorben las plantas del aire?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuántos dientes tiene normalmente un adulto?', category: 'science', difficulty: 'medium' },
  { question: '¿A cuántos grados Celsius hierve el agua?', category: 'science', difficulty: 'easy' },
  { question: '¿Qué planeta se conoce como el Planeta Rojo?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuál es la velocidad de la luz?', category: 'science', difficulty: 'hard' },
  { question: '¿Cuántos corazones tiene un pulpo?', category: 'science', difficulty: 'medium' },
  { question: '¿Cuál es la capital de Japón?', category: 'geography', difficulty: 'easy' },
  { question: '¿Cuál es el río más largo del mundo?', category: 'geography', difficulty: 'medium' },
  { question: '¿Cuál es el país más grande por superficie?', category: 'geography', difficulty: 'easy' },
  { question: '¿En qué continente está Egipto?', category: 'geography', difficulty: 'easy' },
  { question: '¿Cuál es la capital de Australia?', category: 'geography', difficulty: 'easy' },
  { question: '¿Qué océano es el más frío?', category: 'geography', difficulty: 'medium' },
  { question: '¿Cuál es el país más pequeño del mundo?', category: 'geography', difficulty: 'medium' },
  { question: '¿Qué país tiene más habitantes?', category: 'geography', difficulty: 'easy' },
  { question: '¿Cuál es la capital de Brasil?', category: 'geography', difficulty: 'easy' },
  { question: '¿En qué país está la Torre Eiffel?', category: 'geography', difficulty: 'easy' },
  { question: '¿De qué fruta salen las pasas?', category: 'food', difficulty: 'easy' },
  { question: '¿De qué color es una zanahoria?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué se obtiene al congelar agua?', category: 'food', difficulty: 'easy' },
  { question: '¿Cuál es el ingrediente principal del pan?', category: 'food', difficulty: 'easy' },
  { question: '¿De qué país es originaria la pizza?', category: 'food', difficulty: 'easy' },
  { question: '¿De qué color es un plátano cuando está maduro?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué verdura se usa para hacer encurtidos?', category: 'food', difficulty: 'easy' },
  { question: '¿Quién hace la miel?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué tipo de comida es el sushi?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué fruta es roja y tiene semillas por fuera?', category: 'food', difficulty: 'easy' },
  { question: '¿Cuántos jugadores hay en un equipo de fútbol?', category: 'sports', difficulty: 'easy' },
  { question: '¿De qué color es el anillo del medio en la bandera olímpica?', category: 'sports', difficulty: 'medium' },
  { question: '¿En qué deporte se marca un touchdown?', category: 'sports', difficulty: 'easy' },
  { question: '¿Cuántos torneos Grand Slam hay en tenis?', category: 'sports', difficulty: 'medium' },
  { question: '¿Qué forma tiene una pelota de baloncesto?', category: 'sports', difficulty: 'easy' },
  { question: '¿En qué deporte se usa un puck?', category: 'sports', difficulty: 'easy' },
  { question: '¿Cuántas vueltas son las 500 millas de Indy?', category: 'sports', difficulty: 'medium' },
  { question: '¿En qué país se inventó el golf?', category: 'sports', difficulty: 'medium' },
  { question: '¿Cuántos jugadores hay en un equipo de baloncesto?', category: 'sports', difficulty: 'easy' },
  { question: '¿Qué deporte se juega en Wimbledon?', category: 'sports', difficulty: 'easy' },
  { question: '¿Cuántas cuerdas tiene una guitarra estándar?', category: 'music', difficulty: 'easy' },
  { question: '¿Qué instrumento tiene teclas negras y blancas?', category: 'music', difficulty: 'easy' },
  { question: '¿Cuántos tiempos tiene un vals?', category: 'music', difficulty: 'medium' },
  { question: '¿Cuál es el instrumento más grande de una orquesta?', category: 'music', difficulty: 'easy' },
  { question: '¿Qué grupo cantaba "Yellow Submarine"?', category: 'music', difficulty: 'easy' },
  { question: '¿Cuántas notas tiene una octava?', category: 'music', difficulty: 'medium' },
  { question: '¿Qué instrumento toca un batería?', category: 'music', difficulty: 'easy' },
  { question: '¿En qué país se originó la ópera?', category: 'music', difficulty: 'medium' },
  { question: '¿Cuál es la voz de canto más aguda?', category: 'music', difficulty: 'easy' },
  { question: '¿Cuántas cuerdas tiene un violín?', category: 'music', difficulty: 'easy' },
  { question: '¿En qué película un león se convierte en rey?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cómo se llama el mago en El mago de Oz?', category: 'movies', difficulty: 'easy' },
  { question: '¿Qué estudio hizo Frozen?', category: 'movies', difficulty: 'easy' },
  { question: '¿Qué animal es Remy en Ratatouille?', category: 'movies', difficulty: 'easy' },
  { question: '¿En qué película un niño encuentra un genio en una lámpara?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cómo se llama el pez en Buscando a Nemo?', category: 'movies', difficulty: 'easy' },
  { question: '¿En qué película hay un personaje llamado Simba?', category: 'movies', difficulty: 'easy' },
  { question: '¿De qué color es el vestido de Cenicienta?', category: 'movies', difficulty: 'easy' },
  { question: '¿En qué película los juguetes cobran vida?', category: 'movies', difficulty: 'easy' },
  { question: '¿Qué animal es Dumbo?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cuánto es 3 por 4?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántos ojos tiene una persona?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué es el sol?', category: 'general', difficulty: 'easy' },
  { question: '¿Con qué vuelan los pájaros?', category: 'general', difficulty: 'easy' },
  { question: '¿De qué está hecha la nieve?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántos minutos tiene una hora?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es lo contrario de grande?', category: 'general', difficulty: 'easy' },
  { question: '¿Con qué ves?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué animal tiene una trompa larga?', category: 'general', difficulty: 'easy' },
  { question: '¿De qué color es el sol?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántos lados tiene un cuadrado?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué respiran los peces?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué cae del cielo cuando llueve?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuánto es 15 más 15?', category: 'general', difficulty: 'easy' },
  { question: '¿Cómo se llama una oveja bebé?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántas patas tiene una silla?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es lo contrario de rápido?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué lees en un libro?', category: 'general', difficulty: 'easy' },
  { question: '¿En qué estación hay más nieve?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál sería el peor nombre para un puesto de trabajo?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál es el invento más inútil?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería un mal nombre para un jabón?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál es el peor sabor de helado?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería una contraseña terrible?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál es la forma más tonta de viajar?', category: 'funny', difficulty: 'easy' },
  { question: '¿A qué sería lo peor ser alérgico?', category: 'funny', difficulty: 'easy' },
  { question: '¿Qué es lo más vergonzoso de olvidar?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería un mal nombre para un hospital?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería el peor superpoder en una fiesta?', category: 'funny', difficulty: 'easy' },
  { question: '¿Preferirías no tener gusto o no tener olfato?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías luchar contra un pato del tamaño de un caballo o 100 caballos del tamaño de un pato?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías tener un botón de rebobinar o pausar en la vida?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías cantar siempre o susurrar siempre?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías no tener cejas o no tener pestañas?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías ser famoso o rico?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías tener cola o cuernos?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías vivir sin música o sin películas?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías un chef personal o un piloto personal?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías saber cuándo mueres o cómo mueres?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Cuánto es 7 por 8?', category: 'random', difficulty: 'medium' },
  { question: '¿Cuántos ceros tiene mil?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuál es la última letra del abecedario?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuántos lados tiene un hexágono?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuánto es el 50 por ciento de 100?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuántos segundos tiene un minuto?', category: 'random', difficulty: 'easy' },
  { question: '¿A cuántos grados Celsius se congela el agua?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuántas franjas tiene la bandera de EE.UU.?', category: 'random', difficulty: 'medium' },
  { question: '¿Cuánto es 12 por 12?', category: 'random', difficulty: 'medium' },
  { question: '¿Cuántas patas tiene un escarabajo?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuál es el símbolo químico del oro?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuántos planetas hay en nuestro sistema solar?', category: 'science', difficulty: 'easy' },
  { question: '¿Qué órgano bombea la sangre?', category: 'science', difficulty: 'easy' },
  { question: '¿Qué es H2O?', category: 'science', difficulty: 'easy' },
  { question: '¿Qué gas expulsan los humanos?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuántas alas tiene una mariposa?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuál es la estrella más cercana a la Tierra?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuál es la sustancia natural más dura?', category: 'science', difficulty: 'medium' },
  { question: '¿Cuántos cromosomas tienen los humanos?', category: 'science', difficulty: 'hard' },
  { question: '¿Qué planeta está más cerca del sol?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuál es la capital de Alemania?', category: 'geography', difficulty: 'easy' },
  { question: '¿Qué país tiene las Pirámides?', category: 'geography', difficulty: 'easy' },
  { question: '¿Cuál es la capital de Italia?', category: 'geography', difficulty: 'easy' },
  { question: '¿Qué océano está entre América y Europa?', category: 'geography', difficulty: 'easy' },
  { question: '¿Cuál es la capital de Canadá?', category: 'geography', difficulty: 'easy' },
  { question: '¿En qué país está la Torre de Pisa?', category: 'geography', difficulty: 'easy' },
  { question: '¿Cuál es la cordillera más larga?', category: 'geography', difficulty: 'medium' },
  { question: '¿Qué país tiene la Gran Muralla?', category: 'geography', difficulty: 'easy' },
  { question: '¿Cuál es la capital de México?', category: 'geography', difficulty: 'easy' },
  { question: '¿En qué país está la Estatua de la Libertad?', category: 'geography', difficulty: 'easy' },
  { question: '¿Qué verdura se usa para las patatas fritas?', category: 'food', difficulty: 'easy' },
  { question: '¿De qué color es una manzana?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué pones en una tostadora?', category: 'food', difficulty: 'easy' },
  { question: '¿Cuál es el ingrediente principal del hummus?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué fruta es verde por fuera y roja por dentro?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué añades al té para endulzarlo?', category: 'food', difficulty: 'easy' },
  { question: '¿De qué está hecho el ketchup?', category: 'food', difficulty: 'easy' },
  { question: '¿De qué color es la leche?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué cereal se usa para el arroz?', category: 'food', difficulty: 'easy' },
  { question: '¿Cuál es el ingrediente principal del guacamole?', category: 'food', difficulty: 'easy' },
  { question: '¿Cuántos puntos vale un touchdown?', category: 'sports', difficulty: 'easy' },
  { question: '¿En qué deporte se golpea un volante?', category: 'sports', difficulty: 'easy' },
  { question: '¿Cuántos jugadores tiene un equipo de béisbol?', category: 'sports', difficulty: 'medium' },
  { question: '¿De qué color es el maillot del líder del Tour de Francia?', category: 'sports', difficulty: 'medium' },
  { question: '¿En qué deporte se hace bowling?', category: 'sports', difficulty: 'easy' },
  { question: '¿Cuántos Grand Slams ganó Serena Williams?', category: 'sports', difficulty: 'hard' },
  { question: '¿Qué forma tiene un balón de fútbol americano?', category: 'sports', difficulty: 'easy' },
  { question: '¿En qué país empezó el maratón?', category: 'sports', difficulty: 'medium' },
  { question: '¿Cuántos anillos tiene la bandera olímpica?', category: 'sports', difficulty: 'easy' },
  { question: '¿Qué deporte usa una red y un balón?', category: 'sports', difficulty: 'easy' },
  { question: '¿Cuántas teclas tiene un piano estándar?', category: 'music', difficulty: 'medium' },
  { question: '¿Qué instrumento tocaba Elvis?', category: 'music', difficulty: 'easy' },
  { question: '¿Cuántas cuerdas tiene un ukelele?', category: 'music', difficulty: 'easy' },
  { question: '¿Cuál es la voz de canto más grave?', category: 'music', difficulty: 'easy' },
  { question: '¿En qué ciudad es famosa la Ópera?', category: 'music', difficulty: 'medium' },
  { question: '¿Qué grupo tenía "Bohemian Rhapsody"?', category: 'music', difficulty: 'easy' },
  { question: '¿Cuántos miembros tiene un cuarteto?', category: 'music', difficulty: 'easy' },
  { question: '¿Qué instrumento tiene un slide?', category: 'music', difficulty: 'easy' },
  { question: '¿De qué género es Beethoven?', category: 'music', difficulty: 'easy' },
  { question: '¿Cuántos álbumes sacaron los Beatles?', category: 'music', difficulty: 'hard' },
  { question: '¿En qué película un niño va a una escuela de magia?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cómo se llama el tiburón en Tiburón?', category: 'movies', difficulty: 'easy' },
  { question: '¿En qué película dicen "I will find you"?', category: 'movies', difficulty: 'medium' },
  { question: '¿Qué animal es el Burro en Shrek?', category: 'movies', difficulty: 'easy' },
  { question: '¿En qué película un robot dice "I\'ll be back"?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cómo se llama el dragón en Cómo entrenar a tu dragón?', category: 'movies', difficulty: 'easy' },
  { question: '¿Qué estudio hizo Toy Story?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cómo se llama el león en El rey león?', category: 'movies', difficulty: 'easy' },
  { question: '¿En qué película una chica tiene el pelo largo y mágico?', category: 'movies', difficulty: 'easy' },
  { question: '¿Qué vehículo usa Doc en Regreso al futuro?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cuánto es 20 más 30?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántas narices tiene una persona?', category: 'general', difficulty: 'easy' },
  { question: '¿Con qué oyes?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es lo contrario de mojado?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántas esquinas tiene un rectángulo?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué nos dan las vacas?', category: 'general', difficulty: 'easy' },
  { question: '¿Con qué hueles?', category: 'general', difficulty: 'easy' },
  { question: '¿En qué estación se caen las hojas?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántas patas tiene una mesa normalmente?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuánto es 9 menos 4?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué ponen las gallinas?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es lo contrario de claro?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántas alas tiene un pájaro?', category: 'general', difficulty: 'easy' },
  { question: '¿Con qué te lavas los dientes?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué sería lo peor que decir en una boda?', category: 'funny', difficulty: 'easy' },
  { question: '¿Qué es lo peor que se puede dejar caer en público?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería un nombre terrible para un dentista?', category: 'funny', difficulty: 'easy' },
  { question: '¿Qué es lo más tonto de coleccionar?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería el peor superpoder en una entrevista de trabajo?', category: 'funny', difficulty: 'easy' },
  { question: '¿Preferirías tener los dedos pegajosos para siempre o los pies sudorosos para siempre?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías un reloj que va hacia atrás o uno que siempre va mal?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías solo poder susurrar o solo poder gritar?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías no tener pelo o tenerlo por todas partes?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Preferirías poder hablar con plantas o con insectos?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '¿Cuánto es 6 por 7?', category: 'random', difficulty: 'medium' },
  { question: '¿Cuántos días tiene febrero en un año bisiesto?', category: 'random', difficulty: 'easy' },
  { question: '¿Qué número viene después de 99?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuántas patas tiene un cangrejo?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuánto es el 25 por ciento de 200?', category: 'random', difficulty: 'medium' },
  { question: '¿Cuál es el símbolo químico del hierro?', category: 'science', difficulty: 'medium' },
  { question: '¿Cuántos pulmones tenemos?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuál es el órgano más grande del cuerpo humano?', category: 'science', difficulty: 'medium' },
  { question: '¿Qué planeta tiene anillos?', category: 'science', difficulty: 'easy' },
  { question: '¿En qué se transforman las orugas?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuál es la capital de Inglaterra?', category: 'geography', difficulty: 'easy' },
  { question: '¿Qué mar es el Mar Muerto?', category: 'geography', difficulty: 'medium' },
  { question: '¿Cuál es la capital de la India?', category: 'geography', difficulty: 'easy' },
  { question: '¿Qué continente tiene más países?', category: 'geography', difficulty: 'medium' },
  { question: '¿Cuál es la capital de Corea del Sur?', category: 'geography', difficulty: 'easy' },
  { question: '¿De qué fruto se hace la mantequilla de cacahuete?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué fruta sale del naranjo?', category: 'food', difficulty: 'easy' },
  { question: '¿Cuál es el ingrediente principal de la mantequilla?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué verdura es morada y redonda?', category: 'food', difficulty: 'easy' },
  { question: '¿Cómo se llama la comida del mediodía?', category: 'food', difficulty: 'easy' },
  { question: '¿Cuántos jugadores tiene un equipo de voleibol?', category: 'sports', difficulty: 'easy' },
  { question: '¿De qué color es la pelota de tenis?', category: 'sports', difficulty: 'easy' },
  { question: '¿En qué deporte se monta a caballo?', category: 'sports', difficulty: 'easy' },
  { question: '¿Cuántos hoyos tiene un campo de golf?', category: 'sports', difficulty: 'medium' },
  { question: '¿Qué deporte se juega en el Super Bowl?', category: 'sports', difficulty: 'easy' },
  { question: '¿Qué instrumento se toca mucho en jazz?', category: 'music', difficulty: 'easy' },
  { question: '¿Cuántas cuerdas tiene un bajo?', category: 'music', difficulty: 'easy' },
  { question: '¿Cómo se llama un grupo de cuatro cantantes?', category: 'music', difficulty: 'medium' },
  { question: '¿Qué grupo cantaba "Stairway to Heaven"?', category: 'music', difficulty: 'easy' },
  { question: '¿Qué nota viene después de sol en la escala?', category: 'music', difficulty: 'medium' },
  { question: '¿En qué película un niño descubre que es mago?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cómo se llama la princesa en Frozen?', category: 'movies', difficulty: 'easy' },
  { question: '¿En qué película hay un personaje llamado Dory?', category: 'movies', difficulty: 'easy' },
  { question: '¿En qué película los coches cobran vida?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cómo se llama el muñeco de nieve en Frozen?', category: 'movies', difficulty: 'easy' },
];
