module.exports = [
  { question: '¿De qué color es el cielo?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántas patas tiene un perro?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuánto es 2 + 2?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es la capital de Francia?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué animal hace "mu"?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántos días tiene una semana?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué forma tiene una pelota?', category: 'general', difficulty: 'easy' },
  { question: '¿Con qué se escribe en papel?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es lo contrario de caliente?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántos dedos tienes en una mano?', category: 'general', difficulty: 'easy' },
  { question: '¿En qué planeta vivimos?', category: 'general', difficulty: 'easy' },
  { question: '¿De qué color es la hierba?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es el océano más grande?', category: 'general', difficulty: 'medium' },
  { question: '¿Cuántos continentes hay?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué idioma se habla en España?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué estación viene después del verano?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántas horas tiene un día?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es el animal más alto?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué hacen las abejas?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuánto es 10 menos 3?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es lo contrario de arriba?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántas ruedas tiene un coche?', category: 'general', difficulty: 'easy' },
  { question: '¿Cómo se llama un gato bebé?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué fruta es amarilla y curvada?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué llevas en los pies?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué es lo más gracioso que has visto nunca?', category: 'funny', difficulty: 'medium' },
  { question: '¿Cuál sería el peor nombre para una mascota?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál es el superpoder más tonto que se te ocurre?', category: 'funny', difficulty: 'easy' },
  { question: 'Si solo pudieras comer una cosa para siempre, ¿cuál sería?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería el peor consejo que podrías dar a alguien?', category: 'funny', difficulty: 'medium' },
  { question: '¿Cómo llamarías a tu barco?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería el peor regalo que podrías recibir?', category: 'funny', difficulty: 'easy' },
  { question: '¿Como qué animal sería lo peor reencarnarse?', category: 'funny', difficulty: 'medium' },
  { question: '¿Qué es lo más aburrido que te imaginas?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería un nombre horrible para un restaurante?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería el peor superpoder?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál es la peor verdura?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería un mal nombre para un grupo musical?', category: 'funny', difficulty: 'easy' },
  { question: '¿Qué es lo peor que se puede olvidar en un viaje?', category: 'funny', difficulty: 'easy' },
  { question: '¿Preferirías tener manos por pies o pies por manos?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías llegar siempre 10 minutos tarde o 20 minutos pronto?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías no tener móvil o no tener tele?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías comer solo dulce o solo salado?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías vivir en el pasado o en el futuro?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías poder volar o ser invisible?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías verano o invierno todo el año?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías tener un gato o un perro?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías no usar redes sociales o no ver películas nunca?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías hablar todos los idiomas o hablar con los animales?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías pizza ilimitada o sushi ilimitado?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías poder teletransportarte o viajar en el tiempo?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías perder la voz o el oído?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías tener un elefante diminuto o un hámster gigante?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué día es hoy?', category: 'random', difficulty: 'easy' },
  { question: '¿En qué mes estamos?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuál es la primera letra del abecedario?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuántos lados tiene un triángulo?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuál es lo contrario de día?', category: 'random', difficulty: 'easy' },
  { question: '¿Cómo se llama un perro bebé?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuál es el animal terrestre más rápido?', category: 'random', difficulty: 'medium' },
  { question: '¿Cuántas patas tiene una araña?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuál es el continente más pequeño?', category: 'random', difficulty: 'medium' },
  { question: '¿Cuánto es 100 dividido entre 10?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuántos meses tiene un año?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuánto es 5 por 5?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuántos colores tiene un arcoíris?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuál es el planeta más grande de nuestro sistema solar?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuántos huesos tiene un adulto humano?', category: 'science', difficulty: 'medium' },
  { question: '¿Cuál es el símbolo químico del agua?', category: 'science', difficulty: 'easy' },
  { question: '¿Qué fuerza nos mantiene en el suelo?', category: 'science', difficulty: 'easy' },
  { question: '¿Qué gas absorben las plantas del aire?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuántos dientes tiene normalmente un adulto?', category: 'science', difficulty: 'medium' },
  { question: '¿A cuántos grados Celsius hierve el agua?', category: 'science', difficulty: 'easy' },
  { question: '¿Qué planeta se conoce como el Planeta Rojo?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuál es la velocidad de la luz?', category: 'science', difficulty: 'hard' },
  { question: '¿Cuántos corazones tiene un pulpo?', category: 'science', difficulty: 'medium' },
  { question: '¿Cuál es la capital de Japón?', category: 'geography', difficulty: 'easy' },
  { question: '¿Cuál es el río más largo del mundo?', category: 'geography', difficulty: 'medium' },
  { question: '¿Cuál es el país más grande por superficie?', category: 'geography', difficulty: 'easy' },
  { question: '¿En qué continente está Egipto?', category: 'geography', difficulty: 'easy' },
  { question: '¿Cuál es la capital de Australia?', category: 'geography', difficulty: 'easy' },
  { question: '¿Qué océano es el más frío?', category: 'geography', difficulty: 'medium' },
  { question: '¿Cuál es el país más pequeño del mundo?', category: 'geography', difficulty: 'medium' },
  { question: '¿Qué país tiene más habitantes?', category: 'geography', difficulty: 'easy' },
  { question: '¿Cuál es la capital de Brasil?', category: 'geography', difficulty: 'easy' },
  { question: '¿En qué país está la Torre Eiffel?', category: 'geography', difficulty: 'easy' },
  { question: '¿De qué fruta salen las pasas?', category: 'food', difficulty: 'easy' },
  { question: '¿De qué color es una zanahoria?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué se obtiene al congelar agua?', category: 'food', difficulty: 'easy' },
  { question: '¿Cuál es el ingrediente principal del pan?', category: 'food', difficulty: 'easy' },
  { question: '¿De qué país es originaria la pizza?', category: 'food', difficulty: 'easy' },
  { question: '¿De qué color es un plátano cuando está maduro?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué verdura se usa para hacer encurtidos?', category: 'food', difficulty: 'easy' },
  { question: '¿Quién hace la miel?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué tipo de comida es el sushi?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué fruta es roja y tiene semillas por fuera?', category: 'food', difficulty: 'easy' },
  { question: '¿Cuántos jugadores hay en un equipo de fútbol?', category: 'sports', difficulty: 'easy' },
  { question: '¿De qué color es el anillo del medio en la bandera olímpica?', category: 'sports', difficulty: 'medium' },
  { question: '¿En qué deporte se marca un touchdown?', category: 'sports', difficulty: 'easy' },
  { question: '¿Cuántos torneos Grand Slam hay en tenis?', category: 'sports', difficulty: 'medium' },
  { question: '¿Qué forma tiene una pelota de baloncesto?', category: 'sports', difficulty: 'easy' },
  { question: '¿En qué deporte se usa un puck?', category: 'sports', difficulty: 'easy' },
  { question: '¿Cuántas vueltas son las 500 millas de Indy?', category: 'sports', difficulty: 'medium' },
  { question: '¿En qué país se inventó el golf?', category: 'sports', difficulty: 'medium' },
  { question: '¿Cuántos jugadores hay en un equipo de baloncesto?', category: 'sports', difficulty: 'easy' },
  { question: '¿Qué deporte se juega en Wimbledon?', category: 'sports', difficulty: 'easy' },
  { question: '¿Cuántas cuerdas tiene una guitarra estándar?', category: 'music', difficulty: 'easy' },
  { question: '¿Qué instrumento tiene teclas negras y blancas?', category: 'music', difficulty: 'easy' },
  { question: '¿Cuántos tiempos tiene un vals?', category: 'music', difficulty: 'medium' },
  { question: '¿Cuál es el instrumento más grande de una orquesta?', category: 'music', difficulty: 'easy' },
  { question: '¿Qué grupo cantaba "Yellow Submarine"?', category: 'music', difficulty: 'easy' },
  { question: '¿Cuántas notas tiene una octava?', category: 'music', difficulty: 'medium' },
  { question: '¿Qué instrumento toca un batería?', category: 'music', difficulty: 'easy' },
  { question: '¿En qué país se originó la ópera?', category: 'music', difficulty: 'medium' },
  { question: '¿Cuál es la voz de canto más aguda?', category: 'music', difficulty: 'easy' },
  { question: '¿Cuántas cuerdas tiene un violín?', category: 'music', difficulty: 'easy' },
  { question: '¿En qué película un león se convierte en rey?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cómo se llama el mago en El mago de Oz?', category: 'movies', difficulty: 'easy' },
  { question: '¿Qué estudio hizo Frozen?', category: 'movies', difficulty: 'easy' },
  { question: '¿Qué animal es Remy en Ratatouille?', category: 'movies', difficulty: 'easy' },
  { question: '¿En qué película un niño encuentra un genio en una lámpara?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cómo se llama el pez en Buscando a Nemo?', category: 'movies', difficulty: 'easy' },
  { question: '¿En qué película hay un personaje llamado Simba?', category: 'movies', difficulty: 'easy' },
  { question: '¿De qué color es el vestido de Cenicienta?', category: 'movies', difficulty: 'easy' },
  { question: '¿En qué película los juguetes cobran vida?', category: 'movies', difficulty: 'easy' },
  { question: '¿Qué animal es Dumbo?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cuánto es 3 por 4?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántos ojos tiene una persona?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué es el sol?', category: 'general', difficulty: 'easy' },
  { question: '¿Con qué vuelan los pájaros?', category: 'general', difficulty: 'easy' },
  { question: '¿De qué está hecha la nieve?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántos minutos tiene una hora?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es lo contrario de grande?', category: 'general', difficulty: 'easy' },
  { question: '¿Con qué ves?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué animal tiene una trompa larga?', category: 'general', difficulty: 'easy' },
  { question: '¿De qué color es el sol?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántos lados tiene un cuadrado?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué respiran los peces?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué cae del cielo cuando llueve?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuánto es 15 más 15?', category: 'general', difficulty: 'easy' },
  { question: '¿Cómo se llama una oveja bebé?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántas patas tiene una silla?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es lo contrario de rápido?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué lees en un libro?', category: 'general', difficulty: 'easy' },
  { question: '¿En qué estación hay más nieve?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál sería el peor nombre para un puesto de trabajo?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál es el invento más inútil?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería un mal nombre para un jabón?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál es el peor sabor de helado?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería una contraseña terrible?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál es la forma más tonta de viajar?', category: 'funny', difficulty: 'easy' },
  { question: '¿A qué sería lo peor ser alérgico?', category: 'funny', difficulty: 'easy' },
  { question: '¿Qué es lo más vergonzoso de olvidar?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería un mal nombre para un hospital?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería el peor superpoder en una fiesta?', category: 'funny', difficulty: 'easy' },
  { question: '¿Preferirías no tener gusto o no tener olfato?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías luchar contra un pato del tamaño de un caballo o 100 caballos del tamaño de un pato?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías tener un botón de rebobinar o pausar en la vida?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías cantar siempre o susurrar siempre?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías no tener cejas o no tener pestañas?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías ser famoso o rico?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías tener cola o cuernos?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías vivir sin música o sin películas?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías un chef personal o un piloto personal?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías saber cuándo mueres o cómo mueres?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuánto es 7 por 8?', category: 'random', difficulty: 'medium' },
  { question: '¿Cuántos ceros tiene mil?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuál es la última letra del abecedario?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuántos lados tiene un hexágono?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuánto es el 50 por ciento de 100?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuántos segundos tiene un minuto?', category: 'random', difficulty: 'easy' },
  { question: '¿A cuántos grados Celsius se congela el agua?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuántas franjas tiene la bandera de EE.UU.?', category: 'random', difficulty: 'medium' },
  { question: '¿Cuánto es 12 por 12?', category: 'random', difficulty: 'medium' },
  { question: '¿Cuántas patas tiene un escarabajo?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuál es el símbolo químico del oro?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuántos planetas hay en nuestro sistema solar?', category: 'science', difficulty: 'easy' },
  { question: '¿Qué órgano bombea la sangre?', category: 'science', difficulty: 'easy' },
  { question: '¿Qué es H2O?', category: 'science', difficulty: 'easy' },
  { question: '¿Qué gas expulsan los humanos?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuántas alas tiene una mariposa?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuál es la estrella más cercana a la Tierra?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuál es la sustancia natural más dura?', category: 'science', difficulty: 'medium' },
  { question: '¿Cuántos cromosomas tienen los humanos?', category: 'science', difficulty: 'hard' },
  { question: '¿Qué planeta está más cerca del sol?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuál es la capital de Alemania?', category: 'geography', difficulty: 'easy' },
  { question: '¿Qué país tiene las Pirámides?', category: 'geography', difficulty: 'easy' },
  { question: '¿Cuál es la capital de Italia?', category: 'geography', difficulty: 'easy' },
  { question: '¿Qué océano está entre América y Europa?', category: 'geography', difficulty: 'easy' },
  { question: '¿Cuál es la capital de Canadá?', category: 'geography', difficulty: 'easy' },
  { question: '¿En qué país está la Torre de Pisa?', category: 'geography', difficulty: 'easy' },
  { question: '¿Cuál es la cordillera más larga?', category: 'geography', difficulty: 'medium' },
  { question: '¿Qué país tiene la Gran Muralla?', category: 'geography', difficulty: 'easy' },
  { question: '¿Cuál es la capital de México?', category: 'geography', difficulty: 'easy' },
  { question: '¿En qué país está la Estatua de la Libertad?', category: 'geography', difficulty: 'easy' },
  { question: '¿Qué verdura se usa para las patatas fritas?', category: 'food', difficulty: 'easy' },
  { question: '¿De qué color es una manzana?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué pones en una tostadora?', category: 'food', difficulty: 'easy' },
  { question: '¿Cuál es el ingrediente principal del hummus?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué fruta es verde por fuera y roja por dentro?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué añades al té para endulzarlo?', category: 'food', difficulty: 'easy' },
  { question: '¿De qué está hecho el ketchup?', category: 'food', difficulty: 'easy' },
  { question: '¿De qué color es la leche?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué cereal se usa para el arroz?', category: 'food', difficulty: 'easy' },
  { question: '¿Cuál es el ingrediente principal del guacamole?', category: 'food', difficulty: 'easy' },
  { question: '¿Cuántos puntos vale un touchdown?', category: 'sports', difficulty: 'easy' },
  { question: '¿En qué deporte se golpea un volante?', category: 'sports', difficulty: 'easy' },
  { question: '¿Cuántos jugadores tiene un equipo de béisbol?', category: 'sports', difficulty: 'medium' },
  { question: '¿De qué color es el maillot del líder del Tour de Francia?', category: 'sports', difficulty: 'medium' },
  { question: '¿En qué deporte se hace bowling?', category: 'sports', difficulty: 'easy' },
  { question: '¿Cuántos Grand Slams ganó Serena Williams?', category: 'sports', difficulty: 'hard' },
  { question: '¿Qué forma tiene un balón de fútbol americano?', category: 'sports', difficulty: 'easy' },
  { question: '¿En qué país empezó el maratón?', category: 'sports', difficulty: 'medium' },
  { question: '¿Cuántos anillos tiene la bandera olímpica?', category: 'sports', difficulty: 'easy' },
  { question: '¿Qué deporte usa una red y un balón?', category: 'sports', difficulty: 'easy' },
  { question: '¿Cuántas teclas tiene un piano estándar?', category: 'music', difficulty: 'medium' },
  { question: '¿Qué instrumento tocaba Elvis?', category: 'music', difficulty: 'easy' },
  { question: '¿Cuántas cuerdas tiene un ukelele?', category: 'music', difficulty: 'easy' },
  { question: '¿Cuál es la voz de canto más grave?', category: 'music', difficulty: 'easy' },
  { question: '¿En qué ciudad es famosa la Ópera?', category: 'music', difficulty: 'medium' },
  { question: '¿Qué grupo tenía "Bohemian Rhapsody"?', category: 'music', difficulty: 'easy' },
  { question: '¿Cuántos miembros tiene un cuarteto?', category: 'music', difficulty: 'easy' },
  { question: '¿Qué instrumento tiene un slide?', category: 'music', difficulty: 'easy' },
  { question: '¿De qué género es Beethoven?', category: 'music', difficulty: 'easy' },
  { question: '¿Cuántos álbumes sacaron los Beatles?', category: 'music', difficulty: 'hard' },
  { question: '¿En qué película un niño va a una escuela de magia?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cómo se llama el tiburón en Tiburón?', category: 'movies', difficulty: 'easy' },
  { question: '¿En qué película dicen "I will find you"?', category: 'movies', difficulty: 'medium' },
  { question: '¿Qué animal es el Burro en Shrek?', category: 'movies', difficulty: 'easy' },
  { question: '¿En qué película un robot dice "I\'ll be back"?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cómo se llama el dragón en Cómo entrenar a tu dragón?', category: 'movies', difficulty: 'easy' },
  { question: '¿Qué estudio hizo Toy Story?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cómo se llama el león en El rey león?', category: 'movies', difficulty: 'easy' },
  { question: '¿En qué película una chica tiene el pelo largo y mágico?', category: 'movies', difficulty: 'easy' },
  { question: '¿Qué vehículo usa Doc en Regreso al futuro?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cuánto es 20 más 30?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántas narices tiene una persona?', category: 'general', difficulty: 'easy' },
  { question: '¿Con qué oyes?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es lo contrario de mojado?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántas esquinas tiene un rectángulo?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué nos dan las vacas?', category: 'general', difficulty: 'easy' },
  { question: '¿Con qué hueles?', category: 'general', difficulty: 'easy' },
  { question: '¿En qué estación se caen las hojas?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántas patas tiene una mesa normalmente?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuánto es 9 menos 4?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué ponen las gallinas?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es lo contrario de claro?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuántas alas tiene un pájaro?', category: 'general', difficulty: 'easy' },
  { question: '¿Con qué te lavas los dientes?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué sería lo peor que decir en una boda?', category: 'funny', difficulty: 'easy' },
  { question: '¿Qué es lo peor que se puede dejar caer en público?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería un nombre terrible para un dentista?', category: 'funny', difficulty: 'easy' },
  { question: '¿Qué es lo más tonto de coleccionar?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál sería el peor superpoder en una entrevista de trabajo?', category: 'funny', difficulty: 'easy' },
  { question: '¿Preferirías tener los dedos pegajosos para siempre o los pies sudorosos para siempre?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías un reloj que va hacia atrás o uno que siempre va mal?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías solo poder susurrar o solo poder gritar?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías no tener pelo o tenerlo por todas partes?', category: 'general', difficulty: 'easy' },
  { question: '¿Preferirías poder hablar con plantas o con insectos?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuánto es 6 por 7?', category: 'random', difficulty: 'medium' },
  { question: '¿Cuántos días tiene febrero en un año bisiesto?', category: 'random', difficulty: 'easy' },
  { question: '¿Qué número viene después de 99?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuántas patas tiene un cangrejo?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuánto es el 25 por ciento de 200?', category: 'random', difficulty: 'medium' },
  { question: '¿Cuál es el símbolo químico del hierro?', category: 'science', difficulty: 'medium' },
  { question: '¿Cuántos pulmones tenemos?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuál es el órgano más grande del cuerpo humano?', category: 'science', difficulty: 'medium' },
  { question: '¿Qué planeta tiene anillos?', category: 'science', difficulty: 'easy' },
  { question: '¿En qué se transforman las orugas?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuál es la capital de Inglaterra?', category: 'geography', difficulty: 'easy' },
  { question: '¿Qué mar es el Mar Muerto?', category: 'geography', difficulty: 'medium' },
  { question: '¿Cuál es la capital de la India?', category: 'geography', difficulty: 'easy' },
  { question: '¿Qué continente tiene más países?', category: 'geography', difficulty: 'medium' },
  { question: '¿Cuál es la capital de Corea del Sur?', category: 'geography', difficulty: 'easy' },
  { question: '¿De qué fruto se hace la mantequilla de cacahuete?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué fruta sale del naranjo?', category: 'food', difficulty: 'easy' },
  { question: '¿Cuál es el ingrediente principal de la mantequilla?', category: 'food', difficulty: 'easy' },
  { question: '¿Qué verdura es morada y redonda?', category: 'food', difficulty: 'easy' },
  { question: '¿Cómo se llama la comida del mediodía?', category: 'food', difficulty: 'easy' },
  { question: '¿Cuántos jugadores tiene un equipo de voleibol?', category: 'sports', difficulty: 'easy' },
  { question: '¿De qué color es la pelota de tenis?', category: 'sports', difficulty: 'easy' },
  { question: '¿En qué deporte se monta a caballo?', category: 'sports', difficulty: 'easy' },
  { question: '¿Cuántos hoyos tiene un campo de golf?', category: 'sports', difficulty: 'medium' },
  { question: '¿Qué deporte se juega en el Super Bowl?', category: 'sports', difficulty: 'easy' },
  { question: '¿Qué instrumento se toca mucho en jazz?', category: 'music', difficulty: 'easy' },
  { question: '¿Cuántas cuerdas tiene un bajo?', category: 'music', difficulty: 'easy' },
  { question: '¿Cómo se llama un grupo de cuatro cantantes?', category: 'music', difficulty: 'medium' },
  { question: '¿Qué grupo cantaba "Stairway to Heaven"?', category: 'music', difficulty: 'easy' },
  { question: '¿Qué nota viene después de sol en la escala?', category: 'music', difficulty: 'medium' },
  { question: '¿En qué película un niño descubre que es mago?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cómo se llama la princesa en Frozen?', category: 'movies', difficulty: 'easy' },
  { question: '¿En qué película hay un personaje llamado Dory?', category: 'movies', difficulty: 'easy' },
  { question: '¿En qué película los coches cobran vida?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cómo se llama el muñeco de nieve en Frozen?', category: 'movies', difficulty: 'easy' },
  { question: '¿En qué año terminó la Segunda Guerra Mundial?', category: 'history', difficulty: 'easy' },
  { question: '¿Quién fue la primera persona en pisar la Luna?', category: 'history', difficulty: 'easy' },
  { question: '¿Qué imperio construyó el Coliseo?', category: 'history', difficulty: 'easy' },
  { question: '¿En qué país comenzó el Renacimiento?', category: 'history', difficulty: 'medium' },
  { question: '¿Quién escribió la Declaración de Independencia?', category: 'history', difficulty: 'easy' },
  { question: '¿Qué maravilla antigua estaba en Egipto?', category: 'history', difficulty: 'easy' },
  { question: '¿Cuándo cayó el Muro de Berlín?', category: 'history', difficulty: 'medium' },
  { question: '¿Quién inventó la bombilla?', category: 'history', difficulty: 'easy' },
  { question: '¿Qué civilización construyó Machu Picchu?', category: 'history', difficulty: 'medium' },
  { question: '¿En qué siglo comenzó la Primera Guerra Mundial?', category: 'history', difficulty: 'medium' },
  { question: '¿Quién fue el primer presidente de EE.UU.?', category: 'history', difficulty: 'easy' },
  { question: '¿Qué país regaló la Estatua de la Libertad a EE.UU.?', category: 'history', difficulty: 'easy' },
  { question: '¿Quién pintó la Mona Lisa?', category: 'history', difficulty: 'easy' },
  { question: '¿Cuándo llegó el hombre a la Luna por primera vez?', category: 'history', difficulty: 'easy' },
  { question: '¿Qué imperio construyó la Gran Muralla?', category: 'history', difficulty: 'easy' },
  { question: '¿Quién descubrió América en 1492?', category: 'history', difficulty: 'easy' },
  { question: '¿Qué significan las siglas CPU?', category: 'technology', difficulty: 'easy' },
  { question: '¿Quién fundó Facebook?', category: 'technology', difficulty: 'easy' },
  { question: '¿En qué año se lanzó el primer iPhone?', category: 'technology', difficulty: 'medium' },
  { question: '¿Qué significan las siglas WiFi?', category: 'technology', difficulty: 'medium' },
  { question: '¿Qué empresa hace la PlayStation?', category: 'technology', difficulty: 'easy' },
  { question: '¿Qué significan las siglas USB?', category: 'technology', difficulty: 'medium' },
  { question: '¿Quién creó Microsoft?', category: 'technology', difficulty: 'easy' },
  { question: '¿Cómo se llama el asistente de Google?', category: 'technology', difficulty: 'easy' },
  { question: '¿Cuántos bits tiene un byte?', category: 'technology', difficulty: 'medium' },
  { question: '¿Qué significan las siglas HTML?', category: 'technology', difficulty: 'easy' },
  { question: '¿Qué empresa creó Android?', category: 'technology', difficulty: 'easy' },
  { question: '¿Qué significan las siglas GPS?', category: 'technology', difficulty: 'easy' },
  { question: '¿Cómo se llama el asistente de voz de Amazon?', category: 'technology', difficulty: 'easy' },
  { question: '¿En qué año se fundó YouTube?', category: 'technology', difficulty: 'medium' },
  { question: '¿Qué significan las siglas RAM?', category: 'technology', difficulty: 'medium' },
  { question: '¿Cuál es el animal más rápido en tierra?', category: 'nature', difficulty: 'easy' },
  { question: '¿Cuál es el mamífero más grande del mundo?', category: 'nature', difficulty: 'easy' },
  { question: '¿Cuántas patas tiene un insecto?', category: 'nature', difficulty: 'easy' },
  { question: '¿Cuál es el único mamífero que vuela?', category: 'nature', difficulty: 'easy' },
  { question: '¿Qué planeta es el Planeta Rojo?', category: 'nature', difficulty: 'easy' },
  { question: '¿Cuál es el oso más grande?', category: 'nature', difficulty: 'easy' },
  { question: '¿Cuántos estómagos tiene una vaca?', category: 'nature', difficulty: 'medium' },
  { question: '¿Cuál es el árbol más alto?', category: 'nature', difficulty: 'medium' },
  { question: '¿Qué ave no puede volar?', category: 'nature', difficulty: 'easy' },
  { question: '¿Cuál es el pájaro más pequeño del mundo?', category: 'nature', difficulty: 'medium' },
  { question: '¿Cuántos brazos tiene un pulpo?', category: 'nature', difficulty: 'easy' },
  { question: '¿Cuál es el animal oceánico más grande?', category: 'nature', difficulty: 'easy' },
  { question: '¿Qué animal duerme más?', category: 'nature', difficulty: 'medium' },
  { question: '¿Qué continente no tiene reptiles?', category: 'nature', difficulty: 'hard' },
  { question: '¿Cuántos huesos tiene el cuello de una jirafa?', category: 'nature', difficulty: 'medium' },
  { question: '¿Cuál es la capital de Francia?', category: 'travel', difficulty: 'easy' },
  { question: '¿Qué país tiene más islas?', category: 'travel', difficulty: 'medium' },
  { question: '¿Cuál es el río más largo de Europa?', category: 'travel', difficulty: 'medium' },
  { question: '¿En qué ciudad está la Acrópolis?', category: 'travel', difficulty: 'easy' },
  { question: '¿Cuál es la capital de Tailandia?', category: 'travel', difficulty: 'easy' },
  { question: '¿En qué país está el Taj Mahal?', category: 'travel', difficulty: 'easy' },
  { question: '¿Cuál es el país más pequeño del mundo?', category: 'travel', difficulty: 'easy' },
  { question: '¿En qué ciudad está el Empire State Building?', category: 'travel', difficulty: 'easy' },
  { question: '¿Cuál es la capital de Egipto?', category: 'travel', difficulty: 'easy' },
  { question: '¿En qué continente está el Sáhara?', category: 'travel', difficulty: 'easy' },
  { question: '¿Cuál es la capital de Argentina?', category: 'travel', difficulty: 'easy' },
  { question: '¿En qué país está la Gran Barrera de Coral?', category: 'travel', difficulty: 'easy' },
  { question: '¿Cuál es la capital de Sudáfrica?', category: 'travel', difficulty: 'easy' },
  { question: '¿Qué ciudad europea divide el Bósforo?', category: 'travel', difficulty: 'medium' },
  { question: '¿Cuál es la capital más alta del mundo?', category: 'travel', difficulty: 'hard' },
  { question: '¿Cuál es tu destino favorito de vacaciones?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es el mejor consejo que te han dado?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué harías si tuvieras un día libre?', category: 'general', difficulty: 'easy' },
  { question: '¿Qué habilidad te gustaría aprender?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál es tu forma favorita de relajarte?', category: 'general', difficulty: 'easy' },
  { question: '¿Cuál ha sido tu sueño más raro?', category: 'funny', difficulty: 'medium' },
  { question: '¿Cuál sería la peor canción en un funeral?', category: 'funny', difficulty: 'easy' },
  { question: '¿Qué es lo más vergonzoso de tu habitación?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cómo sería un mal nombre para una piedra como mascota?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuál es la peor frase para ligar que has oído?', category: 'funny', difficulty: 'easy' },
  { question: '¿Cuántos lados tiene una señal de stop?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuánto es 11 por 11?', category: 'random', difficulty: 'medium' },
  { question: '¿Cuántas caras tiene un cubo?', category: 'random', difficulty: 'easy' },
  { question: '¿Cuál es el único número primo par?', category: 'random', difficulty: 'medium' },
  { question: '¿Cuántos huesos tiene la mano humana?', category: 'science', difficulty: 'medium' },
  { question: '¿Cuál es el símbolo químico del sodio?', category: 'science', difficulty: 'easy' },
  { question: '¿Qué planeta está más lejos del Sol?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuál es el hueso más pequeño del cuerpo humano?', category: 'science', difficulty: 'hard' },
  { question: '¿Qué gas respiramos más?', category: 'science', difficulty: 'easy' },
  { question: '¿Cuál es la capital de España?', category: 'geography', difficulty: 'easy' },
  { question: '¿Qué país tiene más volcanes?', category: 'geography', difficulty: 'medium' },
  { question: '¿Cuál es la capital de Rusia?', category: 'geography', difficulty: 'easy' },
  { question: '¿Cuál es el ingrediente principal del chocolate?', category: 'food', difficulty: 'easy' },
  { question: '¿De qué fruta se hace el vino?', category: 'food', difficulty: 'easy' },
  { question: '¿Cuál es la carne más consumida del mundo?', category: 'food', difficulty: 'medium' },
  { question: '¿Cuántos jugadores tiene un equipo de críquet?', category: 'sports', difficulty: 'medium' },
  { question: '¿En qué deporte se hace un home run?', category: 'sports', difficulty: 'easy' },
  { question: '¿Qué instrumento tiene 88 teclas?', category: 'music', difficulty: 'easy' },
  { question: '¿Quién cantó "Thriller"?', category: 'music', difficulty: 'easy' },
  { question: '¿En qué película un adolescente es mordido por una araña?', category: 'movies', difficulty: 'easy' },
  { question: '¿Cómo se llama la escuela de magia en Harry Potter?', category: 'movies', difficulty: 'easy' },
  { question: 'What is your favorite memory from childhood?', category: 'general', difficulty: 'easy' },
  { question: 'If you could have dinner with anyone, who would it be?', category: 'general', difficulty: 'easy' },
  { question: 'What is the best book you have ever read?', category: 'general', difficulty: 'easy' },
  { question: 'What would you do if you won the lottery?', category: 'general', difficulty: 'easy' },
  { question: 'What is your favorite season and why?', category: 'general', difficulty: 'easy' },
  { question: 'What hobby would you like to try?', category: 'general', difficulty: 'easy' },
  { question: 'What is the most beautiful place you have been?', category: 'general', difficulty: 'easy' },
  { question: 'What superpower would you choose?', category: 'general', difficulty: 'easy' },
  { question: 'What is your go-to karaoke song?', category: 'general', difficulty: 'easy' },
  { question: 'What is the worst haircut you have had?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst thing to say on a first date?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the funniest autocorrect fail you have seen?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a terrible name for a perfume?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the most ridiculous fashion trend?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst animal to be reincarnated as?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the silliest thing you have ever bought?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a bad name for a gym?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst combination of foods?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst job for a vampire?', category: 'funny', difficulty: 'easy' },
  { question: 'How many degrees are in a right angle?', category: 'random', difficulty: 'easy' },
  { question: 'What is 9 times 9?', category: 'random', difficulty: 'easy' },
  { question: 'How many sides does a pentagon have?', category: 'random', difficulty: 'easy' },
  { question: 'What is the square root of 64?', category: 'random', difficulty: 'easy' },
  { question: 'How many days are in a leap year?', category: 'random', difficulty: 'easy' },
  { question: 'What is 15 percent of 100?', category: 'random', difficulty: 'easy' },
  { question: 'How many continents start with the letter A?', category: 'random', difficulty: 'medium' },
  { question: 'What is the only number that is the same in English and French?', category: 'random', difficulty: 'hard' },
  { question: 'How many keys are on a standard computer keyboard?', category: 'random', difficulty: 'medium' },
  { question: 'What is the largest prime number under 20?', category: 'random', difficulty: 'medium' },
  { question: 'What is the powerhouse of the cell?', category: 'science', difficulty: 'easy' },
  { question: 'How many bones are in the human spine?', category: 'science', difficulty: 'medium' },
  { question: 'What is the chemical symbol for carbon?', category: 'science', difficulty: 'easy' },
  { question: 'What planet is known for its rings?', category: 'science', difficulty: 'easy' },
  { question: 'How many teeth do adults typically have?', category: 'science', difficulty: 'easy' },
  { question: 'What is the smallest planet in our solar system?', category: 'science', difficulty: 'easy' },
  { question: 'What gas makes up most of the atmosphere?', category: 'science', difficulty: 'easy' },
  { question: 'How many chambers does the human heart have?', category: 'science', difficulty: 'easy' },
  { question: 'What is the speed of sound?', category: 'science', difficulty: 'hard' },
  { question: 'What is the chemical symbol for oxygen?', category: 'science', difficulty: 'easy' },
  { question: 'What is the capital of Greece?', category: 'geography', difficulty: 'easy' },
  { question: 'Which country is home to the kangaroo?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Turkey?', category: 'geography', difficulty: 'easy' },
  { question: 'Which river flows through Paris?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Poland?', category: 'geography', difficulty: 'easy' },
  { question: 'Which country has the most population in Africa?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the capital of Sweden?', category: 'geography', difficulty: 'easy' },
  { question: 'Which sea is the saltiest?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the capital of the Netherlands?', category: 'geography', difficulty: 'easy' },
  { question: 'Which mountain is the tallest in the world?', category: 'geography', difficulty: 'easy' },
  { question: 'What vegetable is known as the king of vegetables?', category: 'food', difficulty: 'medium' },
  { question: 'What is the main ingredient in tzatziki?', category: 'food', difficulty: 'easy' },
  { question: 'What nut is in pesto?', category: 'food', difficulty: 'easy' },
  { question: 'What fruit is known as the king of fruits?', category: 'food', difficulty: 'medium' },
  { question: 'What is the primary ingredient in falafel?', category: 'food', difficulty: 'easy' },
  { question: 'What type of cheese is used in Greek salad?', category: 'food', difficulty: 'easy' },
  { question: 'What grain is used to make beer?', category: 'food', difficulty: 'easy' },
  { question: 'What is the main ingredient in guacamole?', category: 'food', difficulty: 'easy' },
  { question: 'What fruit is dried to make prunes?', category: 'food', difficulty: 'easy' },
  { question: 'What is the most expensive spice in the world?', category: 'food', difficulty: 'medium' },
  { question: 'How many players are on a rugby team?', category: 'sports', difficulty: 'medium' },
  { question: 'In which sport do you use a racket and shuttlecock?', category: 'sports', difficulty: 'easy' },
  { question: 'What color is the ball in pool?', category: 'sports', difficulty: 'easy' },
  { question: 'How many Grand Slam tournaments does tennis have per year?', category: 'sports', difficulty: 'easy' },
  { question: 'In which country did basketball originate?', category: 'sports', difficulty: 'easy' },
  { question: 'What is the national sport of Canada?', category: 'sports', difficulty: 'medium' },
  { question: 'How many minutes are in a soccer half?', category: 'sports', difficulty: 'easy' },
  { question: 'In which sport do you score a try?', category: 'sports', difficulty: 'medium' },
  { question: 'What is the diameter of a basketball hoop?', category: 'sports', difficulty: 'hard' },
  { question: 'Which country has won the most World Cups?', category: 'sports', difficulty: 'easy' },
  { question: 'What instrument has 88 keys?', category: 'music', difficulty: 'easy' },
  { question: 'Who is known as the King of Pop?', category: 'music', difficulty: 'easy' },
  { question: 'How many strings does a harp have?', category: 'music', difficulty: 'hard' },
  { question: 'What is the most played song at weddings?', category: 'music', difficulty: 'medium' },
  { question: 'In which city did jazz originate?', category: 'music', difficulty: 'medium' },
  { question: 'What band sang "Sweet Child O\' Mine"?', category: 'music', difficulty: 'easy' },
  { question: 'How many members are in a trio?', category: 'music', difficulty: 'easy' },
  { question: 'What is the highest male singing voice?', category: 'music', difficulty: 'easy' },
  { question: 'Who wrote the Ninth Symphony?', category: 'music', difficulty: 'easy' },
  { question: 'What instrument is known as the king of instruments?', category: 'music', difficulty: 'medium' },
  { question: 'In which film does a boy ride a dragon?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the dragon in Game of Thrones?', category: 'movies', difficulty: 'medium' },
  { question: 'Which film features a talking raccoon?', category: 'movies', difficulty: 'easy' },
  { question: 'In which film does a robot become human?', category: 'movies', difficulty: 'medium' },
  { question: 'What is the name of the ship in Titanic?', category: 'movies', difficulty: 'easy' },
  { question: 'Which studio made Shrek?', category: 'movies', difficulty: 'easy' },
  { question: 'In which film does a clown fish search for his son?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the dinosaur in Jurassic Park?', category: 'movies', difficulty: 'easy' },
  { question: 'Which film has "May the Force be with you"?', category: 'movies', difficulty: 'easy' },
  { question: 'In which year did the Titanic sink?', category: 'movies', difficulty: 'medium' },
  { question: 'Who was the first woman to win a Nobel Prize?', category: 'history', difficulty: 'medium' },
  { question: 'In which year did the French Revolution begin?', category: 'history', difficulty: 'medium' },
  { question: 'Who built the first printing press?', category: 'history', difficulty: 'medium' },
  { question: 'Which empire was ruled by Genghis Khan?', category: 'history', difficulty: 'easy' },
  { question: 'When did the Roman Empire fall?', category: 'history', difficulty: 'hard' },
  { question: 'Who was the British prime minister during World War II?', category: 'history', difficulty: 'easy' },
  { question: 'Which country invented paper?', category: 'history', difficulty: 'medium' },
  { question: 'Who wrote the Odyssey?', category: 'history', difficulty: 'easy' },
  { question: 'In which year did man first fly in an airplane?', category: 'history', difficulty: 'medium' },
  { question: 'Who discovered penicillin?', category: 'history', difficulty: 'medium' },
  { question: 'What does AI stand for?', category: 'technology', difficulty: 'easy' },
  { question: 'Who founded Tesla?', category: 'technology', difficulty: 'easy' },
  { question: 'What year was the first computer virus created?', category: 'technology', difficulty: 'hard' },
  { question: 'What does VPN stand for?', category: 'technology', difficulty: 'medium' },
  { question: 'Which company makes the Switch?', category: 'technology', difficulty: 'easy' },
  { question: 'What does SSD stand for?', category: 'technology', difficulty: 'medium' },
  { question: 'Who created Linux?', category: 'technology', difficulty: 'hard' },
  { question: 'What is the name of Apple\'s voice assistant?', category: 'technology', difficulty: 'easy' },
  { question: 'In what year was the first email sent?', category: 'technology', difficulty: 'hard' },
  { question: 'What does HTTP stand for?', category: 'technology', difficulty: 'medium' },
  { question: 'Which animal can live the longest?', category: 'nature', difficulty: 'medium' },
  { question: 'What is the only mammal that lays eggs?', category: 'nature', difficulty: 'easy' },
  { question: 'How many eyes does a bee have?', category: 'nature', difficulty: 'medium' },
  { question: 'What is the fastest bird?', category: 'nature', difficulty: 'medium' },
  { question: 'Which animal has the longest migration?', category: 'nature', difficulty: 'hard' },
  { question: 'What is the largest land animal?', category: 'nature', difficulty: 'easy' },
  { question: 'How many stomachs does a goat have?', category: 'nature', difficulty: 'medium' },
  { question: 'What is the only bird that can fly backward?', category: 'nature', difficulty: 'medium' },
  { question: 'Which insect is the strongest relative to its size?', category: 'nature', difficulty: 'hard' },
  { question: 'What is the loudest animal on Earth?', category: 'nature', difficulty: 'hard' },
  { question: 'What is the capital of Portugal?', category: 'travel', difficulty: 'easy' },
  { question: 'Which country has the most UNESCO World Heritage sites?', category: 'travel', difficulty: 'hard' },
  { question: 'What is the capital of Norway?', category: 'travel', difficulty: 'easy' },
  { question: 'In which city is the Parthenon?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of Switzerland?', category: 'travel', difficulty: 'easy' },
  { question: 'Which country is the Great Wall in?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of Ireland?', category: 'travel', difficulty: 'easy' },
  { question: 'In which city would you find Big Ben?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of Austria?', category: 'travel', difficulty: 'easy' },
  { question: 'Which country has the most lakes?', category: 'travel', difficulty: 'hard' },
];
