module.exports = [
  { question: 'De quelle couleur est le ciel ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien de pattes a un chien ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien font 2 + 2 ?', category: 'general', difficulty: 'easy' },
  { question: 'Quelle est la capitale de la France ?', category: 'general', difficulty: 'easy' },
  { question: 'Quel animal fait "meuh" ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien de jours y a-t-il dans une semaine ?', category: 'general', difficulty: 'easy' },
  { question: 'Quelle forme a un ballon ?', category: 'general', difficulty: 'easy' },
  { question: 'Avec quoi écrit-on sur du papier ?', category: 'general', difficulty: 'easy' },
  { question: 'Quel est le contraire de chaud ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien de doigts as-tu sur une main ?', category: 'general', difficulty: 'easy' },
  { question: 'Sur quelle planète vivons-nous ?', category: 'general', difficulty: 'easy' },
  { question: 'De quelle couleur est l\'herbe ?', category: 'general', difficulty: 'easy' },
  { question: 'Quel est le plus grand océan ?', category: 'general', difficulty: 'medium' },
  { question: 'Combien y a-t-il de continents ?', category: 'general', difficulty: 'easy' },
  { question: 'Quelle langue parle-t-on en Espagne ?', category: 'general', difficulty: 'easy' },
  { question: 'Quelle saison vient après l\'été ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien d\'heures y a-t-il dans une journée ?', category: 'general', difficulty: 'easy' },
  { question: 'Quel est le plus grand animal ?', category: 'general', difficulty: 'easy' },
  { question: 'Que font les abeilles ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien font 10 moins 3 ?', category: 'general', difficulty: 'easy' },
  { question: 'Quel est le contraire de haut ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien de roues a une voiture ?', category: 'general', difficulty: 'easy' },
  { question: 'Comment appelle-t-on un bébé chat ?', category: 'general', difficulty: 'easy' },
  { question: 'Quel fruit est jaune et courbé ?', category: 'general', difficulty: 'easy' },
  { question: 'Que met-on sur ses pieds ?', category: 'general', difficulty: 'easy' },
  { question: 'Quelle est la chose la plus drôle que tu aies jamais vue ?', category: 'funny', difficulty: 'medium' },
  { question: 'Quel serait le pire nom pour un animal de compagnie ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quel est le superpouvoir le plus ridicule auquel tu penses ?', category: 'funny', difficulty: 'easy' },
  { question: 'Si tu ne pouvais manger qu\'un seul aliment pour toujours, ce serait quoi ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quel serait le pire conseil à donner à quelqu\'un ?', category: 'funny', difficulty: 'medium' },
  { question: 'Comment appellerais-tu ton bateau ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quel serait le pire cadeau à recevoir ?', category: 'funny', difficulty: 'easy' },
  { question: 'En quel animal serait-ce le pire de se réincarner ?', category: 'funny', difficulty: 'medium' },
  { question: 'Quelle est la chose la plus ennuyeuse que tu imagines ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quel serait un nom terrible pour un restaurant ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quel serait le pire superpouvoir ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quel est le pire légume ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quel serait un mauvais nom pour un groupe ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quelle est la pire chose à oublier en voyage ?', category: 'funny', difficulty: 'easy' },
  { question: 'Préférerais-tu avoir des mains pour pieds ou des pieds pour mains ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu être toujours en retard de 10 minutes ou en avance de 20 ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu ne plus avoir de téléphone ou plus de télé ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu ne manger que du sucré ou que du salé ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu vivre dans le passé ou dans le futur ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu pouvoir voler ou être invisible ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu l\'été ou l\'hiver toute l\'année ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu avoir un chat ou un chien ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu ne plus jamais utiliser les réseaux sociaux ou ne plus regarder de films ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu parler toutes les langues ou parler aux animaux ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu des pizzas à volonté ou des sushis à volonté ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu pouvoir te téléporter ou voyager dans le temps ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu perdre ta voix ou ton audition ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu un tout petit éléphant ou un hamster géant ?', category: 'general', difficulty: 'easy' },
  { question: 'Quel jour sommes-nous ?', category: 'random', difficulty: 'easy' },
  { question: 'En quel mois sommes-nous ?', category: 'random', difficulty: 'easy' },
  { question: 'Quelle est la première lettre de l\'alphabet ?', category: 'random', difficulty: 'easy' },
  { question: 'Combien de côtés a un triangle ?', category: 'random', difficulty: 'easy' },
  { question: 'Quel est le contraire du jour ?', category: 'random', difficulty: 'easy' },
  { question: 'Comment appelle-t-on un bébé chien ?', category: 'random', difficulty: 'easy' },
  { question: 'Quel est l\'animal terrestre le plus rapide ?', category: 'random', difficulty: 'medium' },
  { question: 'Combien de pattes a une araignée ?', category: 'random', difficulty: 'easy' },
  { question: 'Quel est le plus petit continent ?', category: 'random', difficulty: 'medium' },
  { question: 'Combien font 100 divisé par 10 ?', category: 'random', difficulty: 'easy' },
  { question: 'Combien de mois y a-t-il dans une année ?', category: 'random', difficulty: 'easy' },
  { question: 'Combien font 5 fois 5 ?', category: 'random', difficulty: 'easy' },
  { question: 'Combien de couleurs a un arc-en-ciel ?', category: 'random', difficulty: 'easy' },
  { question: 'Quelle est la plus grande planète de notre système solaire ?', category: 'science', difficulty: 'easy' },
  { question: 'Combien d\'os un adulte a-t-il ?', category: 'science', difficulty: 'medium' },
  { question: 'Quel est le symbole chimique de l\'eau ?', category: 'science', difficulty: 'easy' },
  { question: 'Quelle force nous garde au sol ?', category: 'science', difficulty: 'easy' },
  { question: 'Quel gaz les plantes absorbent-elles de l\'air ?', category: 'science', difficulty: 'easy' },
  { question: 'Combien de dents un adulte a-t-il en général ?', category: 'science', difficulty: 'medium' },
  { question: 'À quelle température l\'eau bout-elle en Celsius ?', category: 'science', difficulty: 'easy' },
  { question: 'Quelle planète appelle-t-on la planète rouge ?', category: 'science', difficulty: 'easy' },
  { question: 'Quelle est la vitesse de la lumière ?', category: 'science', difficulty: 'hard' },
  { question: 'Combien de cœurs a une pieuvre ?', category: 'science', difficulty: 'medium' },
  { question: 'Quelle est la capitale du Japon ?', category: 'geography', difficulty: 'easy' },
  { question: 'Quel est le plus long fleuve du monde ?', category: 'geography', difficulty: 'medium' },
  { question: 'Quel est le plus grand pays par sa superficie ?', category: 'geography', difficulty: 'easy' },
  { question: 'Sur quel continent se trouve l\'Égypte ?', category: 'geography', difficulty: 'easy' },
  { question: 'Quelle est la capitale de l\'Australie ?', category: 'geography', difficulty: 'easy' },
  { question: 'Quel océan est le plus froid ?', category: 'geography', difficulty: 'medium' },
  { question: 'Quel est le plus petit pays du monde ?', category: 'geography', difficulty: 'medium' },
  { question: 'Quel pays a le plus d\'habitants ?', category: 'geography', difficulty: 'easy' },
  { question: 'Quelle est la capitale du Brésil ?', category: 'geography', difficulty: 'easy' },
  { question: 'Dans quel pays se trouve la tour Eiffel ?', category: 'geography', difficulty: 'easy' },
  { question: 'De quel fruit viennent les raisins secs ?', category: 'food', difficulty: 'easy' },
  { question: 'De quelle couleur est une carotte ?', category: 'food', difficulty: 'easy' },
  { question: 'Que obtient-on en congelant l\'eau ?', category: 'food', difficulty: 'easy' },
  { question: 'Quel est l\'ingrédient principal du pain ?', category: 'food', difficulty: 'easy' },
  { question: 'De quel pays la pizza est-elle originaire ?', category: 'food', difficulty: 'easy' },
  { question: 'De quelle couleur est une banane mûre ?', category: 'food', difficulty: 'easy' },
  { question: 'Quel légume utilise-t-on pour les cornichons ?', category: 'food', difficulty: 'easy' },
  { question: 'Par qui le miel est-il fait ?', category: 'food', difficulty: 'easy' },
  { question: 'Quel type de cuisine est le sushi ?', category: 'food', difficulty: 'easy' },
  { question: 'Quel fruit est rouge avec des pépins à l\'extérieur ?', category: 'food', difficulty: 'easy' },
  { question: 'Combien de joueurs y a-t-il dans une équipe de football ?', category: 'sports', difficulty: 'easy' },
  { question: 'De quelle couleur est l\'anneau du milieu du drapeau olympique ?', category: 'sports', difficulty: 'medium' },
  { question: 'Dans quel sport marque-t-on un touchdown ?', category: 'sports', difficulty: 'easy' },
  { question: 'Combien de tournois du Grand Chelem y a-t-il au tennis ?', category: 'sports', difficulty: 'medium' },
  { question: 'Quelle forme a un ballon de basket ?', category: 'sports', difficulty: 'easy' },
  { question: 'Dans quel sport utilise-t-on un palet ?', category: 'sports', difficulty: 'easy' },
  { question: 'Combien de tours fait l\'Indy 500 ?', category: 'sports', difficulty: 'medium' },
  { question: 'Dans quel pays le golf a-t-il été inventé ?', category: 'sports', difficulty: 'medium' },
  { question: 'Combien de joueurs y a-t-il dans une équipe de basket ?', category: 'sports', difficulty: 'easy' },
  { question: 'Quel sport joue-t-on à Wimbledon ?', category: 'sports', difficulty: 'easy' },
  { question: 'Combien de cordes a une guitare standard ?', category: 'music', difficulty: 'easy' },
  { question: 'Quel instrument a des touches noires et blanches ?', category: 'music', difficulty: 'easy' },
  { question: 'Combien de temps a une valse ?', category: 'music', difficulty: 'medium' },
  { question: 'Quel est le plus grand instrument d\'un orchestre ?', category: 'music', difficulty: 'easy' },
  { question: 'Quel groupe a chanté "Yellow Submarine" ?', category: 'music', difficulty: 'easy' },
  { question: 'Combien de notes y a-t-il dans une octave ?', category: 'music', difficulty: 'medium' },
  { question: 'Quel instrument joue un batteur ?', category: 'music', difficulty: 'easy' },
  { question: 'Dans quel pays l\'opéra est-il né ?', category: 'music', difficulty: 'medium' },
  { question: 'Quelle est la voix chantée la plus aiguë ?', category: 'music', difficulty: 'easy' },
  { question: 'Combien de cordes a un violon ?', category: 'music', difficulty: 'easy' },
  { question: 'Dans quel film un lion devient-il roi ?', category: 'movies', difficulty: 'easy' },
  { question: 'Comment s\'appelle le magicien dans Le Magicien d\'Oz ?', category: 'movies', difficulty: 'easy' },
  { question: 'Quel studio a fait La Reine des neiges ?', category: 'movies', difficulty: 'easy' },
  { question: 'Quel animal est Rémy dans Ratatouille ?', category: 'movies', difficulty: 'easy' },
  { question: 'Dans quel film un garçon trouve-t-il un génie dans une lampe ?', category: 'movies', difficulty: 'easy' },
  { question: 'Comment s\'appelle le poisson dans Le Monde de Nemo ?', category: 'movies', difficulty: 'easy' },
  { question: 'Dans quel film y a-t-il un personnage nommé Simba ?', category: 'movies', difficulty: 'easy' },
  { question: 'De quelle couleur est la robe de Cendrillon ?', category: 'movies', difficulty: 'easy' },
  { question: 'Dans quel film les jouets prennent-ils vie ?', category: 'movies', difficulty: 'easy' },
  { question: 'Quel animal est Dumbo ?', category: 'movies', difficulty: 'easy' },
  { question: 'Combien font 3 fois 4 ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien d\'yeux a une personne ?', category: 'general', difficulty: 'easy' },
  { question: 'Qu\'est-ce que le soleil ?', category: 'general', difficulty: 'easy' },
  { question: 'Avec quoi les oiseaux volent-ils ?', category: 'general', difficulty: 'easy' },
  { question: 'De quoi est faite la neige ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien de minutes y a-t-il dans une heure ?', category: 'general', difficulty: 'easy' },
  { question: 'Quel est le contraire de grand ?', category: 'general', difficulty: 'easy' },
  { question: 'Avec quoi vois-tu ?', category: 'general', difficulty: 'easy' },
  { question: 'Quel animal a une longue trompe ?', category: 'general', difficulty: 'easy' },
  { question: 'De quelle couleur est le soleil ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien de côtés a un carré ?', category: 'general', difficulty: 'easy' },
  { question: 'Que respirent les poissons ?', category: 'general', difficulty: 'easy' },
  { question: 'Que tombe du ciel quand il pleut ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien font 15 plus 15 ?', category: 'general', difficulty: 'easy' },
  { question: 'Comment appelle-t-on un bébé mouton ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien de pieds a une chaise ?', category: 'general', difficulty: 'easy' },
  { question: 'Quel est le contraire de rapide ?', category: 'general', difficulty: 'easy' },
  { question: 'Que lis-tu dans un livre ?', category: 'general', difficulty: 'easy' },
  { question: 'Quelle saison a le plus de neige ?', category: 'general', difficulty: 'easy' },
  { question: 'Quel serait le pire intitulé de poste ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quelle est l\'invention la plus inutile ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quel serait un mauvais nom pour un savon ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quelle est la pire saveur de glace ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quel serait un mot de passe terrible ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quel est le moyen le plus ridicule de voyager ?', category: 'funny', difficulty: 'easy' },
  { question: 'À quoi serait-ce le pire d\'être allergique ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quelle est la chose la plus gênante à oublier ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quel serait un mauvais nom pour un hôpital ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quel serait le pire superpouvoir en soirée ?', category: 'funny', difficulty: 'easy' },
  { question: 'Préférerais-tu n\'avoir pas de goût ou pas d\'odorat ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu combattre un canard de la taille d\'un cheval ou 100 chevaux de la taille d\'un canard ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu un bouton rembobiner ou pause pour la vie ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu toujours chanter ou toujours chuchoter ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu n\'avoir pas de sourcils ou pas de cils ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu être célèbre ou riche ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu avoir une queue ou des cornes ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu vivre sans musique ou sans films ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu un chef personnel ou un pilote personnel ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu savoir quand tu meurs ou comment tu meurs ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien font 7 fois 8 ?', category: 'random', difficulty: 'medium' },
  { question: 'Combien de zéros a mille ?', category: 'random', difficulty: 'easy' },
  { question: 'Quelle est la dernière lettre de l\'alphabet ?', category: 'random', difficulty: 'easy' },
  { question: 'Combien de côtés a un hexagone ?', category: 'random', difficulty: 'easy' },
  { question: 'Combien font 50 pour cent de 100 ?', category: 'random', difficulty: 'easy' },
  { question: 'Combien de secondes y a-t-il dans une minute ?', category: 'random', difficulty: 'easy' },
  { question: 'À quelle température l\'eau gèle-t-elle en Celsius ?', category: 'random', difficulty: 'easy' },
  { question: 'Combien de bandes a le drapeau américain ?', category: 'random', difficulty: 'medium' },
  { question: 'Combien font 12 fois 12 ?', category: 'random', difficulty: 'medium' },
  { question: 'Combien de pattes a un scarabée ?', category: 'random', difficulty: 'easy' },
  { question: 'Quel est le symbole chimique de l\'or ?', category: 'science', difficulty: 'easy' },
  { question: 'Combien de planètes dans notre système solaire ?', category: 'science', difficulty: 'easy' },
  { question: 'Quel organe pompe le sang ?', category: 'science', difficulty: 'easy' },
  { question: 'Qu\'est-ce que H2O ?', category: 'science', difficulty: 'easy' },
  { question: 'Quel gaz les humains expirent-ils ?', category: 'science', difficulty: 'easy' },
  { question: 'Combien d\'ailes a un papillon ?', category: 'science', difficulty: 'easy' },
  { question: 'Quelle est l\'étoile la plus proche de la Terre ?', category: 'science', difficulty: 'easy' },
  { question: 'Quelle est la substance naturelle la plus dure ?', category: 'science', difficulty: 'medium' },
  { question: 'Combien de chromosomes ont les humains ?', category: 'science', difficulty: 'hard' },
  { question: 'Quelle planète est la plus proche du soleil ?', category: 'science', difficulty: 'easy' },
  { question: 'Quelle est la capitale de l\'Allemagne ?', category: 'geography', difficulty: 'easy' },
  { question: 'Quel pays a les Pyramides ?', category: 'geography', difficulty: 'easy' },
  { question: 'Quelle est la capitale de l\'Italie ?', category: 'geography', difficulty: 'easy' },
  { question: 'Quel océan est entre l\'Amérique et l\'Europe ?', category: 'geography', difficulty: 'easy' },
  { question: 'Quelle est la capitale du Canada ?', category: 'geography', difficulty: 'easy' },
  { question: 'Dans quel pays est la tour de Pise ?', category: 'geography', difficulty: 'easy' },
  { question: 'Quelle est la plus longue chaîne de montagnes ?', category: 'geography', difficulty: 'medium' },
  { question: 'Quel pays a la Grande Muraille ?', category: 'geography', difficulty: 'easy' },
  { question: 'Quelle est la capitale du Mexique ?', category: 'geography', difficulty: 'easy' },
  { question: 'Dans quel pays est la Statue de la Liberté ?', category: 'geography', difficulty: 'easy' },
  { question: 'Quel légume utilise-t-on pour les frites ?', category: 'food', difficulty: 'easy' },
  { question: 'De quelle couleur est une pomme ?', category: 'food', difficulty: 'easy' },
  { question: 'Que met-on dans un grille-pain ?', category: 'food', difficulty: 'easy' },
  { question: 'Quel est l\'ingrédient principal du houmous ?', category: 'food', difficulty: 'easy' },
  { question: 'Quel fruit est vert dehors et rouge dedans ?', category: 'food', difficulty: 'easy' },
  { question: 'Que met-on dans le thé pour le sucrer ?', category: 'food', difficulty: 'easy' },
  { question: 'De quoi est fait le ketchup ?', category: 'food', difficulty: 'easy' },
  { question: 'De quelle couleur est le lait ?', category: 'food', difficulty: 'easy' },
  { question: 'Quelle céréale pour le riz ?', category: 'food', difficulty: 'easy' },
  { question: 'Quel est l\'ingrédient principal du guacamole ?', category: 'food', difficulty: 'easy' },
  { question: 'Combien de points vaut un touchdown ?', category: 'sports', difficulty: 'easy' },
  { question: 'Dans quel sport frappe-t-on un volant ?', category: 'sports', difficulty: 'easy' },
  { question: 'Combien de joueurs dans une équipe de baseball ?', category: 'sports', difficulty: 'medium' },
  { question: 'De quelle couleur le maillot du leader du Tour de France ?', category: 'sports', difficulty: 'medium' },
  { question: 'Dans quel sport fait-on du bowling ?', category: 'sports', difficulty: 'easy' },
  { question: 'Combien de Grand Chelem Serena Williams a-t-elle gagné ?', category: 'sports', difficulty: 'hard' },
  { question: 'Quelle forme a un ballon de football américain ?', category: 'sports', difficulty: 'easy' },
  { question: 'Dans quel pays le marathon a-t-il commencé ?', category: 'sports', difficulty: 'medium' },
  { question: 'Combien d\'anneaux sur le drapeau olympique ?', category: 'sports', difficulty: 'easy' },
  { question: 'Quel sport utilise un filet et un ballon ?', category: 'sports', difficulty: 'easy' },
  { question: 'Combien de touches a un piano standard ?', category: 'music', difficulty: 'medium' },
  { question: 'Quel instrument jouait Elvis ?', category: 'music', difficulty: 'easy' },
  { question: 'Combien de cordes a un ukulélé ?', category: 'music', difficulty: 'easy' },
  { question: 'Quelle est la voix chantée la plus grave ?', category: 'music', difficulty: 'easy' },
  { question: 'Dans quelle ville l\'Opéra est-il célèbre ?', category: 'music', difficulty: 'medium' },
  { question: 'Quel groupe avait "Bohemian Rhapsody" ?', category: 'music', difficulty: 'easy' },
  { question: 'Combien de membres dans un quatuor ?', category: 'music', difficulty: 'easy' },
  { question: 'Quel instrument a une coulisse ?', category: 'music', difficulty: 'easy' },
  { question: 'Beethoven c\'est quel genre ?', category: 'music', difficulty: 'easy' },
  { question: 'Combien d\'albums les Beatles ont-ils sorti ?', category: 'music', difficulty: 'hard' },
  { question: 'Dans quel film un garçon va à l\'école des sorciers ?', category: 'movies', difficulty: 'easy' },
  { question: 'Comment s\'appelle le requin dans Les Dents de la mer ?', category: 'movies', difficulty: 'easy' },
  { question: 'Dans quel film dit-on "I will find you" ?', category: 'movies', difficulty: 'medium' },
  { question: 'Quel animal est l\'Âne dans Shrek ?', category: 'movies', difficulty: 'easy' },
  { question: 'Dans quel film un robot dit "I\'ll be back" ?', category: 'movies', difficulty: 'easy' },
  { question: 'Comment s\'appelle le dragon dans Dragons ?', category: 'movies', difficulty: 'easy' },
  { question: 'Quel studio a fait Toy Story ?', category: 'movies', difficulty: 'easy' },
  { question: 'Comment s\'appelle le lion dans Le Roi lion ?', category: 'movies', difficulty: 'easy' },
  { question: 'Dans quel film une fille a de longs cheveux magiques ?', category: 'movies', difficulty: 'easy' },
  { question: 'Quel véhicule utilise Doc dans Retour vers le futur ?', category: 'movies', difficulty: 'easy' },
  { question: 'Combien font 20 plus 30 ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien de nez a une personne ?', category: 'general', difficulty: 'easy' },
  { question: 'Avec quoi entends-tu ?', category: 'general', difficulty: 'easy' },
  { question: 'Quel est le contraire de mouillé ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien de coins a un rectangle ?', category: 'general', difficulty: 'easy' },
  { question: 'Que nous donnent les vaches ?', category: 'general', difficulty: 'easy' },
  { question: 'Avec quoi sens-tu les odeurs ?', category: 'general', difficulty: 'easy' },
  { question: 'En quelle saison les feuilles tombent-elles ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien de pieds a une table en général ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien font 9 moins 4 ?', category: 'general', difficulty: 'easy' },
  { question: 'Que pondent les poules ?', category: 'general', difficulty: 'easy' },
  { question: 'Quel est le contraire de clair ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien d\'ailes a un oiseau ?', category: 'general', difficulty: 'easy' },
  { question: 'Avec quoi te brosses-tu les dents ?', category: 'general', difficulty: 'easy' },
  { question: 'Quelle serait la pire chose à dire à un mariage ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quelle est la pire chose à faire tomber en public ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quel serait un nom terrible pour un dentiste ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quelle est la chose la plus bête à collectionner ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quel serait le pire superpouvoir en entretien d\'embauche ?', category: 'funny', difficulty: 'easy' },
  { question: 'Préférerais-tu avoir les doigts collants ou les pieds moites pour toujours ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu une horloge qui recule ou une qui est toujours fausse ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu ne pouvoir que chuchoter ou que crier ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu n\'avoir pas de cheveux ou en avoir partout ?', category: 'general', difficulty: 'easy' },
  { question: 'Préférerais-tu parler aux plantes ou aux insectes ?', category: 'general', difficulty: 'easy' },
  { question: 'Combien font 6 fois 7 ?', category: 'random', difficulty: 'medium' },
  { question: 'Combien de jours en février une année bissextile ?', category: 'random', difficulty: 'easy' },
  { question: 'Quel nombre vient après 99 ?', category: 'random', difficulty: 'easy' },
  { question: 'Combien de pattes a un crabe ?', category: 'random', difficulty: 'easy' },
  { question: 'Combien font 25 pour cent de 200 ?', category: 'random', difficulty: 'medium' },
  { question: 'Quel est le symbole chimique du fer ?', category: 'science', difficulty: 'medium' },
  { question: 'Combien de poumons avons-nous ?', category: 'science', difficulty: 'easy' },
  { question: 'Quel est le plus grand organe du corps humain ?', category: 'science', difficulty: 'medium' },
  { question: 'Quelle planète a des anneaux ?', category: 'science', difficulty: 'easy' },
  { question: 'En quoi se transforment les chenilles ?', category: 'science', difficulty: 'easy' },
  { question: 'Quelle est la capitale de l\'Angleterre ?', category: 'geography', difficulty: 'easy' },
  { question: 'Quelle mer est la mer Morte ?', category: 'geography', difficulty: 'medium' },
  { question: 'Quelle est la capitale de l\'Inde ?', category: 'geography', difficulty: 'easy' },
  { question: 'Quel continent a le plus de pays ?', category: 'geography', difficulty: 'medium' },
  { question: 'Quelle est la capitale de la Corée du Sud ?', category: 'geography', difficulty: 'easy' },
  { question: 'De quelle noix fait-on le beurre de cacahuète ?', category: 'food', difficulty: 'easy' },
  { question: 'Quel fruit donne l\'oranger ?', category: 'food', difficulty: 'easy' },
  { question: 'Quel est l\'ingrédient principal du beurre ?', category: 'food', difficulty: 'easy' },
  { question: 'Quel légume est violet et rond ?', category: 'food', difficulty: 'easy' },
  { question: 'Comment s\'appelle le repas du milieu de journée ?', category: 'food', difficulty: 'easy' },
  { question: 'Combien de joueurs dans une équipe de volley ?', category: 'sports', difficulty: 'easy' },
  { question: 'De quelle couleur est la balle de tennis ?', category: 'sports', difficulty: 'easy' },
  { question: 'Dans quel sport monte-t-on à cheval ?', category: 'sports', difficulty: 'easy' },
  { question: 'Combien de trous sur un terrain de golf ?', category: 'sports', difficulty: 'medium' },
  { question: 'Quel sport au Super Bowl ?', category: 'sports', difficulty: 'easy' },
  { question: 'Quel instrument joue-t-on souvent en jazz ?', category: 'music', difficulty: 'easy' },
  { question: 'Combien de cordes a une basse ?', category: 'music', difficulty: 'easy' },
  { question: 'Comment appelle-t-on un groupe de quatre chanteurs ?', category: 'music', difficulty: 'medium' },
  { question: 'Quel groupe a chanté "Stairway to Heaven" ?', category: 'music', difficulty: 'easy' },
  { question: 'Quelle note vient après sol dans la gamme ?', category: 'music', difficulty: 'medium' },
  { question: 'Dans quel film un garçon découvre qu\'il est sorcier ?', category: 'movies', difficulty: 'easy' },
  { question: 'Comment s\'appelle la princesse dans La Reine des neiges ?', category: 'movies', difficulty: 'easy' },
  { question: 'Dans quel film y a-t-il un personnage nommé Dory ?', category: 'movies', difficulty: 'easy' },
  { question: 'Dans quel film les voitures prennent-elles vie ?', category: 'movies', difficulty: 'easy' },
  { question: 'Comment s\'appelle le bonhomme de neige dans La Reine des neiges ?', category: 'movies', difficulty: 'easy' },
  { question: 'En quelle année la Seconde Guerre mondiale a-t-elle pris fin ?', category: 'history', difficulty: 'easy' },
  { question: 'Qui a été le premier homme sur la Lune ?', category: 'history', difficulty: 'easy' },
  { question: 'Quel empire a construit le Colisée ?', category: 'history', difficulty: 'easy' },
  { question: 'Dans quel pays la Renaissance a-t-elle commencé ?', category: 'history', difficulty: 'medium' },
  { question: 'Qui a rédigé la Déclaration d\'indépendance ?', category: 'history', difficulty: 'easy' },
  { question: 'Quelle merveille antique était en Égypte ?', category: 'history', difficulty: 'easy' },
  { question: 'Quand le mur de Berlin est-il tombé ?', category: 'history', difficulty: 'medium' },
  { question: 'Qui a inventé l\'ampoule électrique ?', category: 'history', difficulty: 'easy' },
  { question: 'Quelle civilisation a construit Machu Picchu ?', category: 'history', difficulty: 'medium' },
  { question: 'Au siècle de quelle année la Première Guerre mondiale a-t-elle commencé ?', category: 'history', difficulty: 'medium' },
  { question: 'Qui a été le premier président des États-Unis ?', category: 'history', difficulty: 'easy' },
  { question: 'Quel pays a offert la Statue de la Liberté aux États-Unis ?', category: 'history', difficulty: 'easy' },
  { question: 'Qui a peint la Joconde ?', category: 'history', difficulty: 'easy' },
  { question: 'Quand l\'homme a-t-il atterri pour la première fois sur la Lune ?', category: 'history', difficulty: 'easy' },
  { question: 'Quel empire a fait construire la Grande Muraille ?', category: 'history', difficulty: 'easy' },
  { question: 'Qui a découvert l\'Amérique en 1492 ?', category: 'history', difficulty: 'easy' },
  { question: 'Que signifient les lettres CPU ?', category: 'technology', difficulty: 'easy' },
  { question: 'Qui a fondé Facebook ?', category: 'technology', difficulty: 'easy' },
  { question: 'En quelle année le premier iPhone est-il sorti ?', category: 'technology', difficulty: 'medium' },
  { question: 'Que signifient les lettres WiFi ?', category: 'technology', difficulty: 'medium' },
  { question: 'Quelle entreprise fabrique la PlayStation ?', category: 'technology', difficulty: 'easy' },
  { question: 'Que signifient les lettres USB ?', category: 'technology', difficulty: 'medium' },
  { question: 'Qui a créé Microsoft ?', category: 'technology', difficulty: 'easy' },
  { question: 'Comment s\'appelle l\'assistant de Google ?', category: 'technology', difficulty: 'easy' },
  { question: 'Combien de bits dans un octet ?', category: 'technology', difficulty: 'medium' },
  { question: 'Que signifient les lettres HTML ?', category: 'technology', difficulty: 'easy' },
  { question: 'Quelle entreprise a créé Android ?', category: 'technology', difficulty: 'easy' },
  { question: 'Que signifient les lettres GPS ?', category: 'technology', difficulty: 'easy' },
  { question: 'Comment s\'appelle l\'assistant vocal d\'Amazon ?', category: 'technology', difficulty: 'easy' },
  { question: 'En quelle année YouTube a-t-il été créé ?', category: 'technology', difficulty: 'medium' },
  { question: 'Que signifient les lettres RAM ?', category: 'technology', difficulty: 'medium' },
  { question: 'Quel est l\'animal le plus rapide sur terre ?', category: 'nature', difficulty: 'easy' },
  { question: 'Quel est le plus grand mammifère sur Terre ?', category: 'nature', difficulty: 'easy' },
  { question: 'Combien de pattes a un insecte ?', category: 'nature', difficulty: 'easy' },
  { question: 'Quel est le seul mammifère qui peut voler ?', category: 'nature', difficulty: 'easy' },
  { question: 'Quelle planète est la planète rouge ?', category: 'nature', difficulty: 'easy' },
  { question: 'Quel est le plus grand ours ?', category: 'nature', difficulty: 'easy' },
  { question: 'Combien d\'estomacs a une vache ?', category: 'nature', difficulty: 'medium' },
  { question: 'Quel est l\'arbre le plus grand ?', category: 'nature', difficulty: 'medium' },
  { question: 'Quel oiseau ne peut pas voler ?', category: 'nature', difficulty: 'easy' },
  { question: 'Quel est le plus petit oiseau du monde ?', category: 'nature', difficulty: 'medium' },
  { question: 'Combien de bras a une pieuvre ?', category: 'nature', difficulty: 'easy' },
  { question: 'Quel est le plus grand animal marin ?', category: 'nature', difficulty: 'easy' },
  { question: 'Quel animal dort le plus ?', category: 'nature', difficulty: 'medium' },
  { question: 'Quel continent n\'a pas de reptiles ?', category: 'nature', difficulty: 'hard' },
  { question: 'Combien d\'os dans le cou d\'une girafe ?', category: 'nature', difficulty: 'medium' },
  { question: 'Quelle est la capitale de la France ?', category: 'travel', difficulty: 'easy' },
  { question: 'Quel pays a le plus d\'îles ?', category: 'travel', difficulty: 'medium' },
  { question: 'Quel est le plus long fleuve d\'Europe ?', category: 'travel', difficulty: 'medium' },
  { question: 'Dans quelle ville se trouve l\'Acropole ?', category: 'travel', difficulty: 'easy' },
  { question: 'Quelle est la capitale de la Thaïlande ?', category: 'travel', difficulty: 'easy' },
  { question: 'Dans quel pays se trouve le Taj Mahal ?', category: 'travel', difficulty: 'easy' },
  { question: 'Quel est le plus petit pays du monde ?', category: 'travel', difficulty: 'easy' },
  { question: 'Dans quelle ville se trouve l\'Empire State Building ?', category: 'travel', difficulty: 'easy' },
  { question: 'Quelle est la capitale de l\'Égypte ?', category: 'travel', difficulty: 'easy' },
  { question: 'Sur quel continent se trouve le Sahara ?', category: 'travel', difficulty: 'easy' },
  { question: 'Quelle est la capitale de l\'Argentine ?', category: 'travel', difficulty: 'easy' },
  { question: 'Dans quel pays se trouve la Grande Barrière de corail ?', category: 'travel', difficulty: 'easy' },
  { question: 'Quelle est la capitale de l\'Afrique du Sud ?', category: 'travel', difficulty: 'easy' },
  { question: 'Quelle ville européenne est traversée par le Bosphore ?', category: 'travel', difficulty: 'medium' },
  { question: 'Quelle est la capitale la plus haute du monde ?', category: 'travel', difficulty: 'hard' },
  { question: 'Quelle est ta destination de vacances préférée ?', category: 'general', difficulty: 'easy' },
  { question: 'Quel est le meilleur conseil qu\'on t\'ait donné ?', category: 'general', difficulty: 'easy' },
  { question: 'Que ferais-tu si tu avais un jour libre ?', category: 'general', difficulty: 'easy' },
  { question: 'Quelle compétence aimerais-tu apprendre ?', category: 'general', difficulty: 'easy' },
  { question: 'Comment aimes-tu te détendre ?', category: 'general', difficulty: 'easy' },
  { question: 'Quel a été ton rêve le plus bizarre ?', category: 'funny', difficulty: 'medium' },
  { question: 'Quelle serait la pire chanson à un enterrement ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quelle est la chose la plus gênante dans ta chambre ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quel serait un mauvais nom pour une pierre en animal de compagnie ?', category: 'funny', difficulty: 'easy' },
  { question: 'Quelle est la pire phrase de drague que tu aies entendue ?', category: 'funny', difficulty: 'easy' },
  { question: 'Combien de côtés a un panneau stop ?', category: 'random', difficulty: 'easy' },
  { question: 'Combien font 11 fois 11 ?', category: 'random', difficulty: 'medium' },
  { question: 'Combien de faces a un cube ?', category: 'random', difficulty: 'easy' },
  { question: 'Quel est le seul nombre premier pair ?', category: 'random', difficulty: 'medium' },
  { question: 'Combien d\'os dans la main humaine ?', category: 'science', difficulty: 'medium' },
  { question: 'Quel est le symbole chimique du sodium ?', category: 'science', difficulty: 'easy' },
  { question: 'Quelle planète est la plus éloignée du Soleil ?', category: 'science', difficulty: 'easy' },
  { question: 'Quel est le plus petit os du corps humain ?', category: 'science', difficulty: 'hard' },
  { question: 'Quel gaz respirons-nous le plus ?', category: 'science', difficulty: 'easy' },
  { question: 'Quelle est la capitale de l\'Espagne ?', category: 'geography', difficulty: 'easy' },
  { question: 'Quel pays a le plus de volcans ?', category: 'geography', difficulty: 'medium' },
  { question: 'Quelle est la capitale de la Russie ?', category: 'geography', difficulty: 'easy' },
  { question: 'Quel est l\'ingrédient principal du chocolat ?', category: 'food', difficulty: 'easy' },
  { question: 'De quel fruit fait-on le vin ?', category: 'food', difficulty: 'easy' },
  { question: 'Quelle viande est la plus consommée au monde ?', category: 'food', difficulty: 'medium' },
  { question: 'Combien de joueurs dans une équipe de cricket ?', category: 'sports', difficulty: 'medium' },
  { question: 'Dans quel sport fait-on un home run ?', category: 'sports', difficulty: 'easy' },
  { question: 'Quel instrument a 88 touches ?', category: 'music', difficulty: 'easy' },
  { question: 'Qui a chanté "Thriller" ?', category: 'music', difficulty: 'easy' },
  { question: 'Dans quel film un ado se fait mordre par une araignée ?', category: 'movies', difficulty: 'easy' },
  { question: 'Comment s\'appelle l\'école de sorcellerie dans Harry Potter ?', category: 'movies', difficulty: 'easy' },
  { question: 'What is your favorite memory from childhood?', category: 'general', difficulty: 'easy' },
  { question: 'If you could have dinner with anyone, who would it be?', category: 'general', difficulty: 'easy' },
  { question: 'What is the best book you have ever read?', category: 'general', difficulty: 'easy' },
  { question: 'What would you do if you won the lottery?', category: 'general', difficulty: 'easy' },
  { question: 'What is your favorite season and why?', category: 'general', difficulty: 'easy' },
  { question: 'What hobby would you like to try?', category: 'general', difficulty: 'easy' },
  { question: 'What is the most beautiful place you have been?', category: 'general', difficulty: 'easy' },
  { question: 'What superpower would you choose?', category: 'general', difficulty: 'easy' },
  { question: 'What is your go-to karaoke song?', category: 'general', difficulty: 'easy' },
  { question: 'What is the worst haircut you have had?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst thing to say on a first date?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the funniest autocorrect fail you have seen?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a terrible name for a perfume?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the most ridiculous fashion trend?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst animal to be reincarnated as?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the silliest thing you have ever bought?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a bad name for a gym?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst combination of foods?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst job for a vampire?', category: 'funny', difficulty: 'easy' },
  { question: 'How many degrees are in a right angle?', category: 'random', difficulty: 'easy' },
  { question: 'What is 9 times 9?', category: 'random', difficulty: 'easy' },
  { question: 'How many sides does a pentagon have?', category: 'random', difficulty: 'easy' },
  { question: 'What is the square root of 64?', category: 'random', difficulty: 'easy' },
  { question: 'How many days are in a leap year?', category: 'random', difficulty: 'easy' },
  { question: 'What is 15 percent of 100?', category: 'random', difficulty: 'easy' },
  { question: 'How many continents start with the letter A?', category: 'random', difficulty: 'medium' },
  { question: 'What is the only number that is the same in English and French?', category: 'random', difficulty: 'hard' },
  { question: 'How many keys are on a standard computer keyboard?', category: 'random', difficulty: 'medium' },
  { question: 'What is the largest prime number under 20?', category: 'random', difficulty: 'medium' },
  { question: 'What is the powerhouse of the cell?', category: 'science', difficulty: 'easy' },
  { question: 'How many bones are in the human spine?', category: 'science', difficulty: 'medium' },
  { question: 'What is the chemical symbol for carbon?', category: 'science', difficulty: 'easy' },
  { question: 'What planet is known for its rings?', category: 'science', difficulty: 'easy' },
  { question: 'How many teeth do adults typically have?', category: 'science', difficulty: 'easy' },
  { question: 'What is the smallest planet in our solar system?', category: 'science', difficulty: 'easy' },
  { question: 'What gas makes up most of the atmosphere?', category: 'science', difficulty: 'easy' },
  { question: 'How many chambers does the human heart have?', category: 'science', difficulty: 'easy' },
  { question: 'What is the speed of sound?', category: 'science', difficulty: 'hard' },
  { question: 'What is the chemical symbol for oxygen?', category: 'science', difficulty: 'easy' },
  { question: 'What is the capital of Greece?', category: 'geography', difficulty: 'easy' },
  { question: 'Which country is home to the kangaroo?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Turkey?', category: 'geography', difficulty: 'easy' },
  { question: 'Which river flows through Paris?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Poland?', category: 'geography', difficulty: 'easy' },
  { question: 'Which country has the most population in Africa?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the capital of Sweden?', category: 'geography', difficulty: 'easy' },
  { question: 'Which sea is the saltiest?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the capital of the Netherlands?', category: 'geography', difficulty: 'easy' },
  { question: 'Which mountain is the tallest in the world?', category: 'geography', difficulty: 'easy' },
  { question: 'What vegetable is known as the king of vegetables?', category: 'food', difficulty: 'medium' },
  { question: 'What is the main ingredient in tzatziki?', category: 'food', difficulty: 'easy' },
  { question: 'What nut is in pesto?', category: 'food', difficulty: 'easy' },
  { question: 'What fruit is known as the king of fruits?', category: 'food', difficulty: 'medium' },
  { question: 'What is the primary ingredient in falafel?', category: 'food', difficulty: 'easy' },
  { question: 'What type of cheese is used in Greek salad?', category: 'food', difficulty: 'easy' },
  { question: 'What grain is used to make beer?', category: 'food', difficulty: 'easy' },
  { question: 'What is the main ingredient in guacamole?', category: 'food', difficulty: 'easy' },
  { question: 'What fruit is dried to make prunes?', category: 'food', difficulty: 'easy' },
  { question: 'What is the most expensive spice in the world?', category: 'food', difficulty: 'medium' },
  { question: 'How many players are on a rugby team?', category: 'sports', difficulty: 'medium' },
  { question: 'In which sport do you use a racket and shuttlecock?', category: 'sports', difficulty: 'easy' },
  { question: 'What color is the ball in pool?', category: 'sports', difficulty: 'easy' },
  { question: 'How many Grand Slam tournaments does tennis have per year?', category: 'sports', difficulty: 'easy' },
  { question: 'In which country did basketball originate?', category: 'sports', difficulty: 'easy' },
  { question: 'What is the national sport of Canada?', category: 'sports', difficulty: 'medium' },
  { question: 'How many minutes are in a soccer half?', category: 'sports', difficulty: 'easy' },
  { question: 'In which sport do you score a try?', category: 'sports', difficulty: 'medium' },
  { question: 'What is the diameter of a basketball hoop?', category: 'sports', difficulty: 'hard' },
  { question: 'Which country has won the most World Cups?', category: 'sports', difficulty: 'easy' },
  { question: 'What instrument has 88 keys?', category: 'music', difficulty: 'easy' },
  { question: 'Who is known as the King of Pop?', category: 'music', difficulty: 'easy' },
  { question: 'How many strings does a harp have?', category: 'music', difficulty: 'hard' },
  { question: 'What is the most played song at weddings?', category: 'music', difficulty: 'medium' },
  { question: 'In which city did jazz originate?', category: 'music', difficulty: 'medium' },
  { question: 'What band sang "Sweet Child O\' Mine"?', category: 'music', difficulty: 'easy' },
  { question: 'How many members are in a trio?', category: 'music', difficulty: 'easy' },
  { question: 'What is the highest male singing voice?', category: 'music', difficulty: 'easy' },
  { question: 'Who wrote the Ninth Symphony?', category: 'music', difficulty: 'easy' },
  { question: 'What instrument is known as the king of instruments?', category: 'music', difficulty: 'medium' },
  { question: 'In which film does a boy ride a dragon?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the dragon in Game of Thrones?', category: 'movies', difficulty: 'medium' },
  { question: 'Which film features a talking raccoon?', category: 'movies', difficulty: 'easy' },
  { question: 'In which film does a robot become human?', category: 'movies', difficulty: 'medium' },
  { question: 'What is the name of the ship in Titanic?', category: 'movies', difficulty: 'easy' },
  { question: 'Which studio made Shrek?', category: 'movies', difficulty: 'easy' },
  { question: 'In which film does a clown fish search for his son?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the dinosaur in Jurassic Park?', category: 'movies', difficulty: 'easy' },
  { question: 'Which film has "May the Force be with you"?', category: 'movies', difficulty: 'easy' },
  { question: 'In which year did the Titanic sink?', category: 'movies', difficulty: 'medium' },
  { question: 'Who was the first woman to win a Nobel Prize?', category: 'history', difficulty: 'medium' },
  { question: 'In which year did the French Revolution begin?', category: 'history', difficulty: 'medium' },
  { question: 'Who built the first printing press?', category: 'history', difficulty: 'medium' },
  { question: 'Which empire was ruled by Genghis Khan?', category: 'history', difficulty: 'easy' },
  { question: 'When did the Roman Empire fall?', category: 'history', difficulty: 'hard' },
  { question: 'Who was the British prime minister during World War II?', category: 'history', difficulty: 'easy' },
  { question: 'Which country invented paper?', category: 'history', difficulty: 'medium' },
  { question: 'Who wrote the Odyssey?', category: 'history', difficulty: 'easy' },
  { question: 'In which year did man first fly in an airplane?', category: 'history', difficulty: 'medium' },
  { question: 'Who discovered penicillin?', category: 'history', difficulty: 'medium' },
  { question: 'What does AI stand for?', category: 'technology', difficulty: 'easy' },
  { question: 'Who founded Tesla?', category: 'technology', difficulty: 'easy' },
  { question: 'What year was the first computer virus created?', category: 'technology', difficulty: 'hard' },
  { question: 'What does VPN stand for?', category: 'technology', difficulty: 'medium' },
  { question: 'Which company makes the Switch?', category: 'technology', difficulty: 'easy' },
  { question: 'What does SSD stand for?', category: 'technology', difficulty: 'medium' },
  { question: 'Who created Linux?', category: 'technology', difficulty: 'hard' },
  { question: 'What is the name of Apple\'s voice assistant?', category: 'technology', difficulty: 'easy' },
  { question: 'In what year was the first email sent?', category: 'technology', difficulty: 'hard' },
  { question: 'What does HTTP stand for?', category: 'technology', difficulty: 'medium' },
  { question: 'Which animal can live the longest?', category: 'nature', difficulty: 'medium' },
  { question: 'What is the only mammal that lays eggs?', category: 'nature', difficulty: 'easy' },
  { question: 'How many eyes does a bee have?', category: 'nature', difficulty: 'medium' },
  { question: 'What is the fastest bird?', category: 'nature', difficulty: 'medium' },
  { question: 'Which animal has the longest migration?', category: 'nature', difficulty: 'hard' },
  { question: 'What is the largest land animal?', category: 'nature', difficulty: 'easy' },
  { question: 'How many stomachs does a goat have?', category: 'nature', difficulty: 'medium' },
  { question: 'What is the only bird that can fly backward?', category: 'nature', difficulty: 'medium' },
  { question: 'Which insect is the strongest relative to its size?', category: 'nature', difficulty: 'hard' },
  { question: 'What is the loudest animal on Earth?', category: 'nature', difficulty: 'hard' },
  { question: 'What is the capital of Portugal?', category: 'travel', difficulty: 'easy' },
  { question: 'Which country has the most UNESCO World Heritage sites?', category: 'travel', difficulty: 'hard' },
  { question: 'What is the capital of Norway?', category: 'travel', difficulty: 'easy' },
  { question: 'In which city is the Parthenon?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of Switzerland?', category: 'travel', difficulty: 'easy' },
  { question: 'Which country is the Great Wall in?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of Ireland?', category: 'travel', difficulty: 'easy' },
  { question: 'In which city would you find Big Ben?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of Austria?', category: 'travel', difficulty: 'easy' },
  { question: 'Which country has the most lakes?', category: 'travel', difficulty: 'hard' },
];
