module.exports = [
  { question: 'Di che colore è il cielo?', category: 'general', difficulty: 'easy' },
  { question: 'Quante zampe ha un cane?', category: 'general', difficulty: 'easy' },
  { question: 'Quanto fa 2 + 2?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è la capitale della Francia?', category: 'general', difficulty: 'easy' },
  { question: 'Quale animale fa "mu"?', category: 'general', difficulty: 'easy' },
  { question: 'Quanti giorni ha una settimana?', category: 'general', difficulty: 'easy' },
  { question: 'Che forma ha un pallone?', category: 'general', difficulty: 'easy' },
  { question: 'Con cosa si scrive su carta?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è il contrario di caldo?', category: 'general', difficulty: 'easy' },
  { question: 'Quante dita hai in una mano?', category: 'general', difficulty: 'easy' },
  { question: 'Su quale pianeta viviamo?', category: 'general', difficulty: 'easy' },
  { question: 'Di che colore è l\'erba?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è l\'oceano più grande?', category: 'general', difficulty: 'medium' },
  { question: 'Quanti continenti ci sono?', category: 'general', difficulty: 'easy' },
  { question: 'Che lingua si parla in Spagna?', category: 'general', difficulty: 'easy' },
  { question: 'Quale stagione viene dopo l\'estate?', category: 'general', difficulty: 'easy' },
  { question: 'Quante ore ha un giorno?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è l\'animale più alto?', category: 'general', difficulty: 'easy' },
  { question: 'Cosa fanno le api?', category: 'general', difficulty: 'easy' },
  { question: 'Quanto fa 10 meno 3?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è il contrario di su?', category: 'general', difficulty: 'easy' },
  { question: 'Quante ruote ha un\'auto?', category: 'general', difficulty: 'easy' },
  { question: 'Come si chiama un gattino?', category: 'general', difficulty: 'easy' },
  { question: 'Quale frutto è giallo e curvo?', category: 'general', difficulty: 'easy' },
  { question: 'Cosa si mette sui piedi?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è la cosa più divertente che hai mai visto?', category: 'funny', difficulty: 'medium' },
  { question: 'Qual sarebbe il peggior nome per un animale domestico?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è il superpotere più stupido a cui puoi pensare?', category: 'funny', difficulty: 'easy' },
  { question: 'Se potessi mangiare solo un cibo per sempre, quale sarebbe?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe il peggior consiglio da dare a qualcuno?', category: 'funny', difficulty: 'medium' },
  { question: 'Come chiameresti la tua barca?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe il peggior regalo da ricevere?', category: 'funny', difficulty: 'easy' },
  { question: 'In quale animale sarebbe peggio reincarnarsi?', category: 'funny', difficulty: 'medium' },
  { question: 'Qual è la cosa più noiosa che puoi immaginare?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe un nome terribile per un ristorante?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe il peggior superpotere?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è la verdura peggiore?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe un brutto nome per una band?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è la cosa peggiore da dimenticare in viaggio?', category: 'funny', difficulty: 'easy' },
  { question: 'Preferiresti avere mani al posto dei piedi o piedi al posto delle mani?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti essere sempre in ritardo di 10 minuti o in anticipo di 20?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti non avere più telefono o più TV?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti mangiare solo dolce o solo salato?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti vivere nel passato o nel futuro?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti poter volare o essere invisibile?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti estate o inverno tutto l\'anno?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti avere un gatto o un cane?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti non usare mai i social o non vedere mai film?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti parlare tutte le lingue o parlare con gli animali?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti pizza illimitata o sushi illimitato?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti poter teletrasportarti o viaggiare nel tempo?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti perdere la voce o l\'udito?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti un elefante minuscolo o un criceto gigante?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Che giorno è oggi?', category: 'random', difficulty: 'easy' },
  { question: 'In che mese siamo?', category: 'random', difficulty: 'easy' },
  { question: 'Qual è la prima lettera dell\'alfabeto?', category: 'random', difficulty: 'easy' },
  { question: 'Quanti lati ha un triangolo?', category: 'random', difficulty: 'easy' },
  { question: 'Qual è il contrario di giorno?', category: 'random', difficulty: 'easy' },
  { question: 'Come si chiama un cucciolo di cane?', category: 'random', difficulty: 'easy' },
  { question: 'Qual è l\'animale terrestre più veloce?', category: 'random', difficulty: 'medium' },
  { question: 'Quante zampe ha un ragno?', category: 'random', difficulty: 'easy' },
  { question: 'Qual è il continente più piccolo?', category: 'random', difficulty: 'medium' },
  { question: 'Quanto fa 100 diviso 10?', category: 'random', difficulty: 'easy' },
  { question: 'Quanti mesi ha un anno?', category: 'random', difficulty: 'easy' },
  { question: 'Quanto fa 5 per 5?', category: 'random', difficulty: 'easy' },
  { question: 'Quanti colori ha un arcobaleno?', category: 'random', difficulty: 'easy' },
  { question: 'Qual è il pianeta più grande del nostro sistema solare?', category: 'science', difficulty: 'easy' },
  { question: 'Quante ossa ha un adulto?', category: 'science', difficulty: 'medium' },
  { question: 'Qual è il simbolo chimico dell\'acqua?', category: 'science', difficulty: 'easy' },
  { question: 'Quale forza ci tiene a terra?', category: 'science', difficulty: 'easy' },
  { question: 'Quale gas assorbono le piante dall\'aria?', category: 'science', difficulty: 'easy' },
  { question: 'Quanti denti ha di solito un adulto?', category: 'science', difficulty: 'medium' },
  { question: 'A quanti gradi Celsius bolle l\'acqua?', category: 'science', difficulty: 'easy' },
  { question: 'Quale pianeta è chiamato il pianeta rosso?', category: 'science', difficulty: 'easy' },
  { question: 'Qual è la velocità della luce?', category: 'science', difficulty: 'hard' },
  { question: 'Quanti cuori ha un polpo?', category: 'science', difficulty: 'medium' },
  { question: 'Qual è la capitale del Giappone?', category: 'geography', difficulty: 'easy' },
  { question: 'Qual è il fiume più lungo del mondo?', category: 'geography', difficulty: 'medium' },
  { question: 'Qual è il paese più grande per superficie?', category: 'geography', difficulty: 'easy' },
  { question: 'In quale continente si trova l\'Egitto?', category: 'geography', difficulty: 'easy' },
  { question: 'Qual è la capitale dell\'Australia?', category: 'geography', difficulty: 'easy' },
  { question: 'Quale oceano è il più freddo?', category: 'geography', difficulty: 'medium' },
  { question: 'Qual è il paese più piccolo del mondo?', category: 'geography', difficulty: 'medium' },
  { question: 'Quale paese ha più abitanti?', category: 'geography', difficulty: 'easy' },
  { question: 'Qual è la capitale del Brasile?', category: 'geography', difficulty: 'easy' },
  { question: 'In quale paese si trova la Torre Eiffel?', category: 'geography', difficulty: 'easy' },
  { question: 'Da quale frutto vengono l\'uvetta?', category: 'food', difficulty: 'easy' },
  { question: 'Di che colore è una carota?', category: 'food', difficulty: 'easy' },
  { question: 'Cosa si ottiene congelando l\'acqua?', category: 'food', difficulty: 'easy' },
  { question: 'Qual è l\'ingrediente principale del pane?', category: 'food', difficulty: 'easy' },
  { question: 'Da quale paese viene la pizza?', category: 'food', difficulty: 'easy' },
  { question: 'Di che colore è una banana matura?', category: 'food', difficulty: 'easy' },
  { question: 'Quale verdura si usa per i sottaceti?', category: 'food', difficulty: 'easy' },
  { question: 'Da chi è fatto il miele?', category: 'food', difficulty: 'easy' },
  { question: 'Che tipo di cibo è il sushi?', category: 'food', difficulty: 'easy' },
  { question: 'Quale frutto è rosso con i semi fuori?', category: 'food', difficulty: 'easy' },
  { question: 'Quanti giocatori ci sono in una squadra di calcio?', category: 'sports', difficulty: 'easy' },
  { question: 'Di che colore è l\'anello centrale nella bandiera olimpica?', category: 'sports', difficulty: 'medium' },
  { question: 'In quale sport si segna un touchdown?', category: 'sports', difficulty: 'easy' },
  { question: 'Quanti tornei del Grande Slam ci sono nel tennis?', category: 'sports', difficulty: 'medium' },
  { question: 'Che forma ha un pallone da basket?', category: 'sports', difficulty: 'easy' },
  { question: 'In quale sport si usa un puck?', category: 'sports', difficulty: 'easy' },
  { question: 'Quanti giri sono le 500 miglia di Indianapolis?', category: 'sports', difficulty: 'medium' },
  { question: 'In quale paese è stato inventato il golf?', category: 'sports', difficulty: 'medium' },
  { question: 'Quanti giocatori ci sono in una squadra di basket?', category: 'sports', difficulty: 'easy' },
  { question: 'Quale sport si gioca a Wimbledon?', category: 'sports', difficulty: 'easy' },
  { question: 'Quante corde ha una chitarra standard?', category: 'music', difficulty: 'easy' },
  { question: 'Quale strumento ha tasti neri e bianchi?', category: 'music', difficulty: 'easy' },
  { question: 'Quanti tempi ha un valzer?', category: 'music', difficulty: 'medium' },
  { question: 'Qual è lo strumento più grande in un\'orchestra?', category: 'music', difficulty: 'easy' },
  { question: 'Quale band ha cantato "Yellow Submarine"?', category: 'music', difficulty: 'easy' },
  { question: 'Quante note ci sono in un\'ottava?', category: 'music', difficulty: 'medium' },
  { question: 'Quale strumento suona un batterista?', category: 'music', difficulty: 'easy' },
  { question: 'In quale paese è nata l\'opera?', category: 'music', difficulty: 'medium' },
  { question: 'Qual è la voce cantata più acuta?', category: 'music', difficulty: 'easy' },
  { question: 'Quante corde ha un violino?', category: 'music', difficulty: 'easy' },
  { question: 'In quale film un leone diventa re?', category: 'movies', difficulty: 'easy' },
  { question: 'Come si chiama il mago ne Il mago di Oz?', category: 'movies', difficulty: 'easy' },
  { question: 'Quale studio ha fatto Frozen?', category: 'movies', difficulty: 'easy' },
  { question: 'Che animale è Remy in Ratatouille?', category: 'movies', difficulty: 'easy' },
  { question: 'In quale film un ragazzo trova un genio in una lampada?', category: 'movies', difficulty: 'easy' },
  { question: 'Come si chiama il pesce in Alla ricerca di Nemo?', category: 'movies', difficulty: 'easy' },
  { question: 'In quale film c\'è un personaggio di nome Simba?', category: 'movies', difficulty: 'easy' },
  { question: 'Di che colore è il vestito di Cenerentola?', category: 'movies', difficulty: 'easy' },
  { question: 'In quale film i giocattoli prendono vita?', category: 'movies', difficulty: 'easy' },
  { question: 'Che animale è Dumbo?', category: 'movies', difficulty: 'easy' },
  { question: 'Quanto fa 3 per 4?', category: 'general', difficulty: 'easy' },
  { question: 'Quanti occhi ha una persona?', category: 'general', difficulty: 'easy' },
  { question: 'Cos\'è il sole?', category: 'general', difficulty: 'easy' },
  { question: 'Con cosa volano gli uccelli?', category: 'general', difficulty: 'easy' },
  { question: 'Di cosa è fatta la neve?', category: 'general', difficulty: 'easy' },
  { question: 'Quanti minuti ha un\'ora?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è il contrario di grande?', category: 'general', difficulty: 'easy' },
  { question: 'Con cosa vedi?', category: 'general', difficulty: 'easy' },
  { question: 'Quale animale ha una lunga proboscide?', category: 'general', difficulty: 'easy' },
  { question: 'Di che colore è il sole?', category: 'general', difficulty: 'easy' },
  { question: 'Quanti lati ha un quadrato?', category: 'general', difficulty: 'easy' },
  { question: 'Cosa respirano i pesci?', category: 'general', difficulty: 'easy' },
  { question: 'Cosa cade dal cielo quando piove?', category: 'general', difficulty: 'easy' },
  { question: 'Quanto fa 15 più 15?', category: 'general', difficulty: 'easy' },
  { question: 'Come si chiama un agnello?', category: 'general', difficulty: 'easy' },
  { question: 'Quante gambe ha una sedia?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è il contrario di veloce?', category: 'general', difficulty: 'easy' },
  { question: 'Cosa leggi in un libro?', category: 'general', difficulty: 'easy' },
  { question: 'Quale stagione ha più neve?', category: 'general', difficulty: 'easy' },
  { question: 'Qual sarebbe il peggior titolo di lavoro?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è l\'invenzione più inutile?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe un brutto nome per un sapone?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è il peggior gusto di gelato?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe una password terribile?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è il modo più stupido di viaggiare?', category: 'funny', difficulty: 'easy' },
  { question: 'A cosa sarebbe peggio essere allergici?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è la cosa più imbarazzante da dimenticare?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe un brutto nome per un ospedale?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe il peggior superpotere a una festa?', category: 'funny', difficulty: 'easy' },
  { question: 'Preferiresti non avere gusto o non avere olfatto?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti combattere un\'anatra grande come un cavallo o 100 cavalli grandi come un\'anatra?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti un pulsante rewind o pausa per la vita?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti sempre cantare o sempre sussurrare?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti non avere sopracciglia o ciglia?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti essere famoso o ricco?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti avere una coda o le corna?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti vivere senza musica o senza film?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti uno chef personale o un pilota personale?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti sapere quando muori o come muori?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Quanto fa 7 per 8?', category: 'random', difficulty: 'medium' },
  { question: 'Quanti zeri ha mille?', category: 'random', difficulty: 'easy' },
  { question: 'Qual è l\'ultima lettera dell\'alfabeto?', category: 'random', difficulty: 'easy' },
  { question: 'Quanti lati ha un esagono?', category: 'random', difficulty: 'easy' },
  { question: 'Quanto fa il 50 per cento di 100?', category: 'random', difficulty: 'easy' },
  { question: 'Quanti secondi ha un minuto?', category: 'random', difficulty: 'easy' },
  { question: 'A quanti gradi Celsius gela l\'acqua?', category: 'random', difficulty: 'easy' },
  { question: 'Quante strisce ha la bandiera USA?', category: 'random', difficulty: 'medium' },
  { question: 'Quanto fa 12 per 12?', category: 'random', difficulty: 'medium' },
  { question: 'Quante zampe ha uno scarabeo?', category: 'random', difficulty: 'easy' },
  { question: 'Qual è il simbolo chimico dell\'oro?', category: 'science', difficulty: 'easy' },
  { question: 'Quanti pianeti ha il nostro sistema solare?', category: 'science', difficulty: 'easy' },
  { question: 'Quale organo pompa il sangue?', category: 'science', difficulty: 'easy' },
  { question: 'Cos\'è H2O?', category: 'science', difficulty: 'easy' },
  { question: 'Quale gas espirano gli umani?', category: 'science', difficulty: 'easy' },
  { question: 'Quante ali ha una farfalla?', category: 'science', difficulty: 'easy' },
  { question: 'Qual è la stella più vicina alla Terra?', category: 'science', difficulty: 'easy' },
  { question: 'Qual è la sostanza naturale più dura?', category: 'science', difficulty: 'medium' },
  { question: 'Quanti cromosomi hanno gli umani?', category: 'science', difficulty: 'hard' },
  { question: 'Quale pianeta è più vicino al sole?', category: 'science', difficulty: 'easy' },
  { question: 'Qual è la capitale della Germania?', category: 'geography', difficulty: 'easy' },
  { question: 'In quale paese ci sono le Piramidi?', category: 'geography', difficulty: 'easy' },
  { question: 'Qual è la capitale dell\'Italia?', category: 'geography', difficulty: 'easy' },
  { question: 'Quale oceano è tra America ed Europa?', category: 'geography', difficulty: 'easy' },
  { question: 'Qual è la capitale del Canada?', category: 'geography', difficulty: 'easy' },
  { question: 'In quale paese è la Torre di Pisa?', category: 'geography', difficulty: 'easy' },
  { question: 'Qual è la catena montuosa più lunga?', category: 'geography', difficulty: 'medium' },
  { question: 'Quale paese ha la Grande Muraglia?', category: 'geography', difficulty: 'easy' },
  { question: 'Qual è la capitale del Messico?', category: 'geography', difficulty: 'easy' },
  { question: 'In quale paese c\'è la Statua della Libertà?', category: 'geography', difficulty: 'easy' },
  { question: 'Quale verdura si usa per le patatine fritte?', category: 'food', difficulty: 'easy' },
  { question: 'Di che colore è una mela?', category: 'food', difficulty: 'easy' },
  { question: 'Cosa si mette in un tostapane?', category: 'food', difficulty: 'easy' },
  { question: 'Qual è l\'ingrediente principale dell\'hummus?', category: 'food', difficulty: 'easy' },
  { question: 'Quale frutto è verde fuori e rosso dentro?', category: 'food', difficulty: 'easy' },
  { question: 'Cosa si aggiunge al tè per dolcificarlo?', category: 'food', difficulty: 'easy' },
  { question: 'Da cosa è fatto il ketchup?', category: 'food', difficulty: 'easy' },
  { question: 'Di che colore è il latte?', category: 'food', difficulty: 'easy' },
  { question: 'Quale cereale si usa per il riso?', category: 'food', difficulty: 'easy' },
  { question: 'Qual è l\'ingrediente principale del guacamole?', category: 'food', difficulty: 'easy' },
  { question: 'Quanti punti vale un touchdown?', category: 'sports', difficulty: 'easy' },
  { question: 'In quale sport si colpisce un volano?', category: 'sports', difficulty: 'easy' },
  { question: 'Quanti giocatori ha una squadra di baseball?', category: 'sports', difficulty: 'medium' },
  { question: 'Di che colore è la maglia del leader del Tour de France?', category: 'sports', difficulty: 'medium' },
  { question: 'In quale sport si fa bowling?', category: 'sports', difficulty: 'easy' },
  { question: 'Quanti Grand Slam ha vinto Serena Williams?', category: 'sports', difficulty: 'hard' },
  { question: 'Che forma ha un pallone da football americano?', category: 'sports', difficulty: 'easy' },
  { question: 'In quale paese è nata la maratona?', category: 'sports', difficulty: 'medium' },
  { question: 'Quanti anelli ha la bandiera olimpica?', category: 'sports', difficulty: 'easy' },
  { question: 'Quale sport usa una rete e un pallone?', category: 'sports', difficulty: 'easy' },
  { question: 'Quanti tasti ha un pianoforte standard?', category: 'music', difficulty: 'medium' },
  { question: 'Quale strumento suonava Elvis?', category: 'music', difficulty: 'easy' },
  { question: 'Quante corde ha un ukulele?', category: 'music', difficulty: 'easy' },
  { question: 'Qual è la voce cantata più grave?', category: 'music', difficulty: 'easy' },
  { question: 'In quale città è famosa l\'Opera?', category: 'music', difficulty: 'medium' },
  { question: 'Quale band aveva "Bohemian Rhapsody"?', category: 'music', difficulty: 'easy' },
  { question: 'Quanti membri ha un quartetto?', category: 'music', difficulty: 'easy' },
  { question: 'Quale strumento ha la coulisse?', category: 'music', difficulty: 'easy' },
  { question: 'Di che genere è Beethoven?', category: 'music', difficulty: 'easy' },
  { question: 'Quanti album hanno pubblicato i Beatles?', category: 'music', difficulty: 'hard' },
  { question: 'In quale film un ragazzo va a scuola di magia?', category: 'movies', difficulty: 'easy' },
  { question: 'Come si chiama lo squalo in Lo squalo?', category: 'movies', difficulty: 'easy' },
  { question: 'In quale film si dice "I will find you"?', category: 'movies', difficulty: 'medium' },
  { question: 'Che animale è l\'Asino in Shrek?', category: 'movies', difficulty: 'easy' },
  { question: 'In quale film un robot dice "I\'ll be back"?', category: 'movies', difficulty: 'easy' },
  { question: 'Come si chiama il drago in Come addestrare il tuo drago?', category: 'movies', difficulty: 'easy' },
  { question: 'Quale studio ha fatto Toy Story?', category: 'movies', difficulty: 'easy' },
  { question: 'Come si chiama il leone ne Il re leone?', category: 'movies', difficulty: 'easy' },
  { question: 'In quale film una ragazza ha lunghi capelli magici?', category: 'movies', difficulty: 'easy' },
  { question: 'Che veicolo usa Doc in Ritorno al futuro?', category: 'movies', difficulty: 'easy' },
  { question: 'Quanto fa 20 più 30?', category: 'general', difficulty: 'easy' },
  { question: 'Quanti nasi ha una persona?', category: 'general', difficulty: 'easy' },
  { question: 'Con cosa senti?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è il contrario di bagnato?', category: 'general', difficulty: 'easy' },
  { question: 'Quanti angoli ha un rettangolo?', category: 'general', difficulty: 'easy' },
  { question: 'Cosa ci danno le mucche?', category: 'general', difficulty: 'easy' },
  { question: 'Con cosa annusi?', category: 'general', difficulty: 'easy' },
  { question: 'In quale stagione cadono le foglie?', category: 'general', difficulty: 'easy' },
  { question: 'Quante gambe ha un tavolo di solito?', category: 'general', difficulty: 'easy' },
  { question: 'Quanto fa 9 meno 4?', category: 'general', difficulty: 'easy' },
  { question: 'Cosa fanno le galline?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è il contrario di chiaro?', category: 'general', difficulty: 'easy' },
  { question: 'Quante ali ha un uccello?', category: 'general', difficulty: 'easy' },
  { question: 'Con cosa ti lavi i denti?', category: 'general', difficulty: 'easy' },
  { question: 'Qual sarebbe la cosa peggiore da dire a un matrimonio?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è la cosa peggiore da far cadere in pubblico?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe un nome terribile per un dentista?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è la cosa più stupida da collezionare?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe il peggior superpotere a un colloquio?', category: 'funny', difficulty: 'easy' },
  { question: 'Preferiresti avere le dita appiccicose o i piedi sudati per sempre?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti un orologio che va indietro o uno sempre sbagliato?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti poter solo sussurrare o solo urlare?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti non avere capelli o averli ovunque?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Preferiresti parlare con le piante o con gli insetti?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Quanto fa 6 per 7?', category: 'random', difficulty: 'medium' },
  { question: 'Quanti giorni ha febbraio in un anno bisestile?', category: 'random', difficulty: 'easy' },
  { question: 'Quale numero viene dopo 99?', category: 'random', difficulty: 'easy' },
  { question: 'Quante zampe ha un granchio?', category: 'random', difficulty: 'easy' },
  { question: 'Quanto fa il 25 per cento di 200?', category: 'random', difficulty: 'medium' },
  { question: 'Qual è il simbolo chimico del ferro?', category: 'science', difficulty: 'medium' },
  { question: 'Quanti polmoni abbiamo?', category: 'science', difficulty: 'easy' },
  { question: 'Qual è l\'organo più grande del corpo umano?', category: 'science', difficulty: 'medium' },
  { question: 'Quale pianeta ha gli anelli?', category: 'science', difficulty: 'easy' },
  { question: 'In cosa si trasformano i bruchi?', category: 'science', difficulty: 'easy' },
  { question: 'Qual è la capitale dell\'Inghilterra?', category: 'geography', difficulty: 'easy' },
  { question: 'Quale mare è il Mar Morto?', category: 'geography', difficulty: 'medium' },
  { question: 'Qual è la capitale dell\'India?', category: 'geography', difficulty: 'easy' },
  { question: 'Quale continente ha più paesi?', category: 'geography', difficulty: 'medium' },
  { question: 'Qual è la capitale della Corea del Sud?', category: 'geography', difficulty: 'easy' },
  { question: 'Da quale noce si fa il burro di arachidi?', category: 'food', difficulty: 'easy' },
  { question: 'Quale frutto dà l\'arancio?', category: 'food', difficulty: 'easy' },
  { question: 'Qual è l\'ingrediente principale del burro?', category: 'food', difficulty: 'easy' },
  { question: 'Quale verdura è viola e rotonda?', category: 'food', difficulty: 'easy' },
  { question: 'Come si chiama il pasto di metà giornata?', category: 'food', difficulty: 'easy' },
  { question: 'Quanti giocatori ha una squadra di pallavolo?', category: 'sports', difficulty: 'easy' },
  { question: 'Di che colore è la palla da tennis?', category: 'sports', difficulty: 'easy' },
  { question: 'In quale sport si cavalca?', category: 'sports', difficulty: 'easy' },
  { question: 'Quanti buche ha un campo da golf?', category: 'sports', difficulty: 'medium' },
  { question: 'Quale sport si gioca al Super Bowl?', category: 'sports', difficulty: 'easy' },
  { question: 'Quale strumento si suona spesso nel jazz?', category: 'music', difficulty: 'easy' },
  { question: 'Quante corde ha un basso?', category: 'music', difficulty: 'easy' },
  { question: 'Come si chiama un gruppo di quattro cantanti?', category: 'music', difficulty: 'medium' },
  { question: 'Quale band ha cantato "Stairway to Heaven"?', category: 'music', difficulty: 'easy' },
  { question: 'Quale nota viene dopo sol nella scala?', category: 'music', difficulty: 'medium' },
  { question: 'In quale film un ragazzo scopre di essere un mago?', category: 'movies', difficulty: 'easy' },
  { question: 'Come si chiama la principessa in Frozen?', category: 'movies', difficulty: 'easy' },
  { question: 'In quale film c\'è un personaggio di nome Dory?', category: 'movies', difficulty: 'easy' },
  { question: 'In quale film le auto prendono vita?', category: 'movies', difficulty: 'easy' },
  { question: 'Come si chiama il pupazzo di neve in Frozen?', category: 'movies', difficulty: 'easy' },
];
