module.exports = [
  { question: 'Di che colore è il cielo?', category: 'general', difficulty: 'easy' },
  { question: 'Quante zampe ha un cane?', category: 'general', difficulty: 'easy' },
  { question: 'Quanto fa 2 + 2?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è la capitale della Francia?', category: 'general', difficulty: 'easy' },
  { question: 'Quale animale fa "mu"?', category: 'general', difficulty: 'easy' },
  { question: 'Quanti giorni ha una settimana?', category: 'general', difficulty: 'easy' },
  { question: 'Che forma ha un pallone?', category: 'general', difficulty: 'easy' },
  { question: 'Con cosa si scrive su carta?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è il contrario di caldo?', category: 'general', difficulty: 'easy' },
  { question: 'Quante dita hai in una mano?', category: 'general', difficulty: 'easy' },
  { question: 'Su quale pianeta viviamo?', category: 'general', difficulty: 'easy' },
  { question: 'Di che colore è l\'erba?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è l\'oceano più grande?', category: 'general', difficulty: 'medium' },
  { question: 'Quanti continenti ci sono?', category: 'general', difficulty: 'easy' },
  { question: 'Che lingua si parla in Spagna?', category: 'general', difficulty: 'easy' },
  { question: 'Quale stagione viene dopo l\'estate?', category: 'general', difficulty: 'easy' },
  { question: 'Quante ore ha un giorno?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è l\'animale più alto?', category: 'general', difficulty: 'easy' },
  { question: 'Cosa fanno le api?', category: 'general', difficulty: 'easy' },
  { question: 'Quanto fa 10 meno 3?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è il contrario di su?', category: 'general', difficulty: 'easy' },
  { question: 'Quante ruote ha un\'auto?', category: 'general', difficulty: 'easy' },
  { question: 'Come si chiama un gattino?', category: 'general', difficulty: 'easy' },
  { question: 'Quale frutto è giallo e curvo?', category: 'general', difficulty: 'easy' },
  { question: 'Cosa si mette sui piedi?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è la cosa più divertente che hai mai visto?', category: 'funny', difficulty: 'medium' },
  { question: 'Qual sarebbe il peggior nome per un animale domestico?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è il superpotere più stupido a cui puoi pensare?', category: 'funny', difficulty: 'easy' },
  { question: 'Se potessi mangiare solo un cibo per sempre, quale sarebbe?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe il peggior consiglio da dare a qualcuno?', category: 'funny', difficulty: 'medium' },
  { question: 'Come chiameresti la tua barca?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe il peggior regalo da ricevere?', category: 'funny', difficulty: 'easy' },
  { question: 'In quale animale sarebbe peggio reincarnarsi?', category: 'funny', difficulty: 'medium' },
  { question: 'Qual è la cosa più noiosa che puoi immaginare?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe un nome terribile per un ristorante?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe il peggior superpotere?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è la verdura peggiore?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe un brutto nome per una band?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è la cosa peggiore da dimenticare in viaggio?', category: 'funny', difficulty: 'easy' },
  { question: 'Preferiresti avere mani al posto dei piedi o piedi al posto delle mani?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti essere sempre in ritardo di 10 minuti o in anticipo di 20?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti non avere più telefono o più TV?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti mangiare solo dolce o solo salato?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti vivere nel passato o nel futuro?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti poter volare o essere invisibile?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti estate o inverno tutto l\'anno?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti avere un gatto o un cane?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti non usare mai i social o non vedere mai film?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti parlare tutte le lingue o parlare con gli animali?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti pizza illimitata o sushi illimitato?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti poter teletrasportarti o viaggiare nel tempo?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti perdere la voce o l\'udito?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti un elefante minuscolo o un criceto gigante?', category: 'general', difficulty: 'easy' },
  { question: 'Che giorno è oggi?', category: 'random', difficulty: 'easy' },
  { question: 'In che mese siamo?', category: 'random', difficulty: 'easy' },
  { question: 'Qual è la prima lettera dell\'alfabeto?', category: 'random', difficulty: 'easy' },
  { question: 'Quanti lati ha un triangolo?', category: 'random', difficulty: 'easy' },
  { question: 'Qual è il contrario di giorno?', category: 'random', difficulty: 'easy' },
  { question: 'Come si chiama un cucciolo di cane?', category: 'random', difficulty: 'easy' },
  { question: 'Qual è l\'animale terrestre più veloce?', category: 'random', difficulty: 'medium' },
  { question: 'Quante zampe ha un ragno?', category: 'random', difficulty: 'easy' },
  { question: 'Qual è il continente più piccolo?', category: 'random', difficulty: 'medium' },
  { question: 'Quanto fa 100 diviso 10?', category: 'random', difficulty: 'easy' },
  { question: 'Quanti mesi ha un anno?', category: 'random', difficulty: 'easy' },
  { question: 'Quanto fa 5 per 5?', category: 'random', difficulty: 'easy' },
  { question: 'Quanti colori ha un arcobaleno?', category: 'random', difficulty: 'easy' },
  { question: 'Qual è il pianeta più grande del nostro sistema solare?', category: 'science', difficulty: 'easy' },
  { question: 'Quante ossa ha un adulto?', category: 'science', difficulty: 'medium' },
  { question: 'Qual è il simbolo chimico dell\'acqua?', category: 'science', difficulty: 'easy' },
  { question: 'Quale forza ci tiene a terra?', category: 'science', difficulty: 'easy' },
  { question: 'Quale gas assorbono le piante dall\'aria?', category: 'science', difficulty: 'easy' },
  { question: 'Quanti denti ha di solito un adulto?', category: 'science', difficulty: 'medium' },
  { question: 'A quanti gradi Celsius bolle l\'acqua?', category: 'science', difficulty: 'easy' },
  { question: 'Quale pianeta è chiamato il pianeta rosso?', category: 'science', difficulty: 'easy' },
  { question: 'Qual è la velocità della luce?', category: 'science', difficulty: 'hard' },
  { question: 'Quanti cuori ha un polpo?', category: 'science', difficulty: 'medium' },
  { question: 'Qual è la capitale del Giappone?', category: 'geography', difficulty: 'easy' },
  { question: 'Qual è il fiume più lungo del mondo?', category: 'geography', difficulty: 'medium' },
  { question: 'Qual è il paese più grande per superficie?', category: 'geography', difficulty: 'easy' },
  { question: 'In quale continente si trova l\'Egitto?', category: 'geography', difficulty: 'easy' },
  { question: 'Qual è la capitale dell\'Australia?', category: 'geography', difficulty: 'easy' },
  { question: 'Quale oceano è il più freddo?', category: 'geography', difficulty: 'medium' },
  { question: 'Qual è il paese più piccolo del mondo?', category: 'geography', difficulty: 'medium' },
  { question: 'Quale paese ha più abitanti?', category: 'geography', difficulty: 'easy' },
  { question: 'Qual è la capitale del Brasile?', category: 'geography', difficulty: 'easy' },
  { question: 'In quale paese si trova la Torre Eiffel?', category: 'geography', difficulty: 'easy' },
  { question: 'Da quale frutto vengono l\'uvetta?', category: 'food', difficulty: 'easy' },
  { question: 'Di che colore è una carota?', category: 'food', difficulty: 'easy' },
  { question: 'Cosa si ottiene congelando l\'acqua?', category: 'food', difficulty: 'easy' },
  { question: 'Qual è l\'ingrediente principale del pane?', category: 'food', difficulty: 'easy' },
  { question: 'Da quale paese viene la pizza?', category: 'food', difficulty: 'easy' },
  { question: 'Di che colore è una banana matura?', category: 'food', difficulty: 'easy' },
  { question: 'Quale verdura si usa per i sottaceti?', category: 'food', difficulty: 'easy' },
  { question: 'Da chi è fatto il miele?', category: 'food', difficulty: 'easy' },
  { question: 'Che tipo di cibo è il sushi?', category: 'food', difficulty: 'easy' },
  { question: 'Quale frutto è rosso con i semi fuori?', category: 'food', difficulty: 'easy' },
  { question: 'Quanti giocatori ci sono in una squadra di calcio?', category: 'sports', difficulty: 'easy' },
  { question: 'Di che colore è l\'anello centrale nella bandiera olimpica?', category: 'sports', difficulty: 'medium' },
  { question: 'In quale sport si segna un touchdown?', category: 'sports', difficulty: 'easy' },
  { question: 'Quanti tornei del Grande Slam ci sono nel tennis?', category: 'sports', difficulty: 'medium' },
  { question: 'Che forma ha un pallone da basket?', category: 'sports', difficulty: 'easy' },
  { question: 'In quale sport si usa un puck?', category: 'sports', difficulty: 'easy' },
  { question: 'Quanti giri sono le 500 miglia di Indianapolis?', category: 'sports', difficulty: 'medium' },
  { question: 'In quale paese è stato inventato il golf?', category: 'sports', difficulty: 'medium' },
  { question: 'Quanti giocatori ci sono in una squadra di basket?', category: 'sports', difficulty: 'easy' },
  { question: 'Quale sport si gioca a Wimbledon?', category: 'sports', difficulty: 'easy' },
  { question: 'Quante corde ha una chitarra standard?', category: 'music', difficulty: 'easy' },
  { question: 'Quale strumento ha tasti neri e bianchi?', category: 'music', difficulty: 'easy' },
  { question: 'Quanti tempi ha un valzer?', category: 'music', difficulty: 'medium' },
  { question: 'Qual è lo strumento più grande in un\'orchestra?', category: 'music', difficulty: 'easy' },
  { question: 'Quale band ha cantato "Yellow Submarine"?', category: 'music', difficulty: 'easy' },
  { question: 'Quante note ci sono in un\'ottava?', category: 'music', difficulty: 'medium' },
  { question: 'Quale strumento suona un batterista?', category: 'music', difficulty: 'easy' },
  { question: 'In quale paese è nata l\'opera?', category: 'music', difficulty: 'medium' },
  { question: 'Qual è la voce cantata più acuta?', category: 'music', difficulty: 'easy' },
  { question: 'Quante corde ha un violino?', category: 'music', difficulty: 'easy' },
  { question: 'In quale film un leone diventa re?', category: 'movies', difficulty: 'easy' },
  { question: 'Come si chiama il mago ne Il mago di Oz?', category: 'movies', difficulty: 'easy' },
  { question: 'Quale studio ha fatto Frozen?', category: 'movies', difficulty: 'easy' },
  { question: 'Che animale è Remy in Ratatouille?', category: 'movies', difficulty: 'easy' },
  { question: 'In quale film un ragazzo trova un genio in una lampada?', category: 'movies', difficulty: 'easy' },
  { question: 'Come si chiama il pesce in Alla ricerca di Nemo?', category: 'movies', difficulty: 'easy' },
  { question: 'In quale film c\'è un personaggio di nome Simba?', category: 'movies', difficulty: 'easy' },
  { question: 'Di che colore è il vestito di Cenerentola?', category: 'movies', difficulty: 'easy' },
  { question: 'In quale film i giocattoli prendono vita?', category: 'movies', difficulty: 'easy' },
  { question: 'Che animale è Dumbo?', category: 'movies', difficulty: 'easy' },
  { question: 'Quanto fa 3 per 4?', category: 'general', difficulty: 'easy' },
  { question: 'Quanti occhi ha una persona?', category: 'general', difficulty: 'easy' },
  { question: 'Cos\'è il sole?', category: 'general', difficulty: 'easy' },
  { question: 'Con cosa volano gli uccelli?', category: 'general', difficulty: 'easy' },
  { question: 'Di cosa è fatta la neve?', category: 'general', difficulty: 'easy' },
  { question: 'Quanti minuti ha un\'ora?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è il contrario di grande?', category: 'general', difficulty: 'easy' },
  { question: 'Con cosa vedi?', category: 'general', difficulty: 'easy' },
  { question: 'Quale animale ha una lunga proboscide?', category: 'general', difficulty: 'easy' },
  { question: 'Di che colore è il sole?', category: 'general', difficulty: 'easy' },
  { question: 'Quanti lati ha un quadrato?', category: 'general', difficulty: 'easy' },
  { question: 'Cosa respirano i pesci?', category: 'general', difficulty: 'easy' },
  { question: 'Cosa cade dal cielo quando piove?', category: 'general', difficulty: 'easy' },
  { question: 'Quanto fa 15 più 15?', category: 'general', difficulty: 'easy' },
  { question: 'Come si chiama un agnello?', category: 'general', difficulty: 'easy' },
  { question: 'Quante gambe ha una sedia?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è il contrario di veloce?', category: 'general', difficulty: 'easy' },
  { question: 'Cosa leggi in un libro?', category: 'general', difficulty: 'easy' },
  { question: 'Quale stagione ha più neve?', category: 'general', difficulty: 'easy' },
  { question: 'Qual sarebbe il peggior titolo di lavoro?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è l\'invenzione più inutile?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe un brutto nome per un sapone?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è il peggior gusto di gelato?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe una password terribile?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è il modo più stupido di viaggiare?', category: 'funny', difficulty: 'easy' },
  { question: 'A cosa sarebbe peggio essere allergici?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è la cosa più imbarazzante da dimenticare?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe un brutto nome per un ospedale?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe il peggior superpotere a una festa?', category: 'funny', difficulty: 'easy' },
  { question: 'Preferiresti non avere gusto o non avere olfatto?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti combattere un\'anatra grande come un cavallo o 100 cavalli grandi come un\'anatra?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti un pulsante rewind o pausa per la vita?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti sempre cantare o sempre sussurrare?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti non avere sopracciglia o ciglia?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti essere famoso o ricco?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti avere una coda o le corna?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti vivere senza musica o senza film?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti uno chef personale o un pilota personale?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti sapere quando muori o come muori?', category: 'general', difficulty: 'easy' },
  { question: 'Quanto fa 7 per 8?', category: 'random', difficulty: 'medium' },
  { question: 'Quanti zeri ha mille?', category: 'random', difficulty: 'easy' },
  { question: 'Qual è l\'ultima lettera dell\'alfabeto?', category: 'random', difficulty: 'easy' },
  { question: 'Quanti lati ha un esagono?', category: 'random', difficulty: 'easy' },
  { question: 'Quanto fa il 50 per cento di 100?', category: 'random', difficulty: 'easy' },
  { question: 'Quanti secondi ha un minuto?', category: 'random', difficulty: 'easy' },
  { question: 'A quanti gradi Celsius gela l\'acqua?', category: 'random', difficulty: 'easy' },
  { question: 'Quante strisce ha la bandiera USA?', category: 'random', difficulty: 'medium' },
  { question: 'Quanto fa 12 per 12?', category: 'random', difficulty: 'medium' },
  { question: 'Quante zampe ha uno scarabeo?', category: 'random', difficulty: 'easy' },
  { question: 'Qual è il simbolo chimico dell\'oro?', category: 'science', difficulty: 'easy' },
  { question: 'Quanti pianeti ha il nostro sistema solare?', category: 'science', difficulty: 'easy' },
  { question: 'Quale organo pompa il sangue?', category: 'science', difficulty: 'easy' },
  { question: 'Cos\'è H2O?', category: 'science', difficulty: 'easy' },
  { question: 'Quale gas espirano gli umani?', category: 'science', difficulty: 'easy' },
  { question: 'Quante ali ha una farfalla?', category: 'science', difficulty: 'easy' },
  { question: 'Qual è la stella più vicina alla Terra?', category: 'science', difficulty: 'easy' },
  { question: 'Qual è la sostanza naturale più dura?', category: 'science', difficulty: 'medium' },
  { question: 'Quanti cromosomi hanno gli umani?', category: 'science', difficulty: 'hard' },
  { question: 'Quale pianeta è più vicino al sole?', category: 'science', difficulty: 'easy' },
  { question: 'Qual è la capitale della Germania?', category: 'geography', difficulty: 'easy' },
  { question: 'In quale paese ci sono le Piramidi?', category: 'geography', difficulty: 'easy' },
  { question: 'Qual è la capitale dell\'Italia?', category: 'geography', difficulty: 'easy' },
  { question: 'Quale oceano è tra America ed Europa?', category: 'geography', difficulty: 'easy' },
  { question: 'Qual è la capitale del Canada?', category: 'geography', difficulty: 'easy' },
  { question: 'In quale paese è la Torre di Pisa?', category: 'geography', difficulty: 'easy' },
  { question: 'Qual è la catena montuosa più lunga?', category: 'geography', difficulty: 'medium' },
  { question: 'Quale paese ha la Grande Muraglia?', category: 'geography', difficulty: 'easy' },
  { question: 'Qual è la capitale del Messico?', category: 'geography', difficulty: 'easy' },
  { question: 'In quale paese c\'è la Statua della Libertà?', category: 'geography', difficulty: 'easy' },
  { question: 'Quale verdura si usa per le patatine fritte?', category: 'food', difficulty: 'easy' },
  { question: 'Di che colore è una mela?', category: 'food', difficulty: 'easy' },
  { question: 'Cosa si mette in un tostapane?', category: 'food', difficulty: 'easy' },
  { question: 'Qual è l\'ingrediente principale dell\'hummus?', category: 'food', difficulty: 'easy' },
  { question: 'Quale frutto è verde fuori e rosso dentro?', category: 'food', difficulty: 'easy' },
  { question: 'Cosa si aggiunge al tè per dolcificarlo?', category: 'food', difficulty: 'easy' },
  { question: 'Da cosa è fatto il ketchup?', category: 'food', difficulty: 'easy' },
  { question: 'Di che colore è il latte?', category: 'food', difficulty: 'easy' },
  { question: 'Quale cereale si usa per il riso?', category: 'food', difficulty: 'easy' },
  { question: 'Qual è l\'ingrediente principale del guacamole?', category: 'food', difficulty: 'easy' },
  { question: 'Quanti punti vale un touchdown?', category: 'sports', difficulty: 'easy' },
  { question: 'In quale sport si colpisce un volano?', category: 'sports', difficulty: 'easy' },
  { question: 'Quanti giocatori ha una squadra di baseball?', category: 'sports', difficulty: 'medium' },
  { question: 'Di che colore è la maglia del leader del Tour de France?', category: 'sports', difficulty: 'medium' },
  { question: 'In quale sport si fa bowling?', category: 'sports', difficulty: 'easy' },
  { question: 'Quanti Grand Slam ha vinto Serena Williams?', category: 'sports', difficulty: 'hard' },
  { question: 'Che forma ha un pallone da football americano?', category: 'sports', difficulty: 'easy' },
  { question: 'In quale paese è nata la maratona?', category: 'sports', difficulty: 'medium' },
  { question: 'Quanti anelli ha la bandiera olimpica?', category: 'sports', difficulty: 'easy' },
  { question: 'Quale sport usa una rete e un pallone?', category: 'sports', difficulty: 'easy' },
  { question: 'Quanti tasti ha un pianoforte standard?', category: 'music', difficulty: 'medium' },
  { question: 'Quale strumento suonava Elvis?', category: 'music', difficulty: 'easy' },
  { question: 'Quante corde ha un ukulele?', category: 'music', difficulty: 'easy' },
  { question: 'Qual è la voce cantata più grave?', category: 'music', difficulty: 'easy' },
  { question: 'In quale città è famosa l\'Opera?', category: 'music', difficulty: 'medium' },
  { question: 'Quale band aveva "Bohemian Rhapsody"?', category: 'music', difficulty: 'easy' },
  { question: 'Quanti membri ha un quartetto?', category: 'music', difficulty: 'easy' },
  { question: 'Quale strumento ha la coulisse?', category: 'music', difficulty: 'easy' },
  { question: 'Di che genere è Beethoven?', category: 'music', difficulty: 'easy' },
  { question: 'Quanti album hanno pubblicato i Beatles?', category: 'music', difficulty: 'hard' },
  { question: 'In quale film un ragazzo va a scuola di magia?', category: 'movies', difficulty: 'easy' },
  { question: 'Come si chiama lo squalo in Lo squalo?', category: 'movies', difficulty: 'easy' },
  { question: 'In quale film si dice "I will find you"?', category: 'movies', difficulty: 'medium' },
  { question: 'Che animale è l\'Asino in Shrek?', category: 'movies', difficulty: 'easy' },
  { question: 'In quale film un robot dice "I\'ll be back"?', category: 'movies', difficulty: 'easy' },
  { question: 'Come si chiama il drago in Come addestrare il tuo drago?', category: 'movies', difficulty: 'easy' },
  { question: 'Quale studio ha fatto Toy Story?', category: 'movies', difficulty: 'easy' },
  { question: 'Come si chiama il leone ne Il re leone?', category: 'movies', difficulty: 'easy' },
  { question: 'In quale film una ragazza ha lunghi capelli magici?', category: 'movies', difficulty: 'easy' },
  { question: 'Che veicolo usa Doc in Ritorno al futuro?', category: 'movies', difficulty: 'easy' },
  { question: 'Quanto fa 20 più 30?', category: 'general', difficulty: 'easy' },
  { question: 'Quanti nasi ha una persona?', category: 'general', difficulty: 'easy' },
  { question: 'Con cosa senti?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è il contrario di bagnato?', category: 'general', difficulty: 'easy' },
  { question: 'Quanti angoli ha un rettangolo?', category: 'general', difficulty: 'easy' },
  { question: 'Cosa ci danno le mucche?', category: 'general', difficulty: 'easy' },
  { question: 'Con cosa annusi?', category: 'general', difficulty: 'easy' },
  { question: 'In quale stagione cadono le foglie?', category: 'general', difficulty: 'easy' },
  { question: 'Quante gambe ha un tavolo di solito?', category: 'general', difficulty: 'easy' },
  { question: 'Quanto fa 9 meno 4?', category: 'general', difficulty: 'easy' },
  { question: 'Cosa fanno le galline?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è il contrario di chiaro?', category: 'general', difficulty: 'easy' },
  { question: 'Quante ali ha un uccello?', category: 'general', difficulty: 'easy' },
  { question: 'Con cosa ti lavi i denti?', category: 'general', difficulty: 'easy' },
  { question: 'Qual sarebbe la cosa peggiore da dire a un matrimonio?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è la cosa peggiore da far cadere in pubblico?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe un nome terribile per un dentista?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è la cosa più stupida da collezionare?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual sarebbe il peggior superpotere a un colloquio?', category: 'funny', difficulty: 'easy' },
  { question: 'Preferiresti avere le dita appiccicose o i piedi sudati per sempre?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti un orologio che va indietro o uno sempre sbagliato?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti poter solo sussurrare o solo urlare?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti non avere capelli o averli ovunque?', category: 'general', difficulty: 'easy' },
  { question: 'Preferiresti parlare con le piante o con gli insetti?', category: 'general', difficulty: 'easy' },
  { question: 'Quanto fa 6 per 7?', category: 'random', difficulty: 'medium' },
  { question: 'Quanti giorni ha febbraio in un anno bisestile?', category: 'random', difficulty: 'easy' },
  { question: 'Quale numero viene dopo 99?', category: 'random', difficulty: 'easy' },
  { question: 'Quante zampe ha un granchio?', category: 'random', difficulty: 'easy' },
  { question: 'Quanto fa il 25 per cento di 200?', category: 'random', difficulty: 'medium' },
  { question: 'Qual è il simbolo chimico del ferro?', category: 'science', difficulty: 'medium' },
  { question: 'Quanti polmoni abbiamo?', category: 'science', difficulty: 'easy' },
  { question: 'Qual è l\'organo più grande del corpo umano?', category: 'science', difficulty: 'medium' },
  { question: 'Quale pianeta ha gli anelli?', category: 'science', difficulty: 'easy' },
  { question: 'In cosa si trasformano i bruchi?', category: 'science', difficulty: 'easy' },
  { question: 'Qual è la capitale dell\'Inghilterra?', category: 'geography', difficulty: 'easy' },
  { question: 'Quale mare è il Mar Morto?', category: 'geography', difficulty: 'medium' },
  { question: 'Qual è la capitale dell\'India?', category: 'geography', difficulty: 'easy' },
  { question: 'Quale continente ha più paesi?', category: 'geography', difficulty: 'medium' },
  { question: 'Qual è la capitale della Corea del Sud?', category: 'geography', difficulty: 'easy' },
  { question: 'Da quale noce si fa il burro di arachidi?', category: 'food', difficulty: 'easy' },
  { question: 'Quale frutto dà l\'arancio?', category: 'food', difficulty: 'easy' },
  { question: 'Qual è l\'ingrediente principale del burro?', category: 'food', difficulty: 'easy' },
  { question: 'Quale verdura è viola e rotonda?', category: 'food', difficulty: 'easy' },
  { question: 'Come si chiama il pasto di metà giornata?', category: 'food', difficulty: 'easy' },
  { question: 'Quanti giocatori ha una squadra di pallavolo?', category: 'sports', difficulty: 'easy' },
  { question: 'Di che colore è la palla da tennis?', category: 'sports', difficulty: 'easy' },
  { question: 'In quale sport si cavalca?', category: 'sports', difficulty: 'easy' },
  { question: 'Quanti buche ha un campo da golf?', category: 'sports', difficulty: 'medium' },
  { question: 'Quale sport si gioca al Super Bowl?', category: 'sports', difficulty: 'easy' },
  { question: 'Quale strumento si suona spesso nel jazz?', category: 'music', difficulty: 'easy' },
  { question: 'Quante corde ha un basso?', category: 'music', difficulty: 'easy' },
  { question: 'Come si chiama un gruppo di quattro cantanti?', category: 'music', difficulty: 'medium' },
  { question: 'Quale band ha cantato "Stairway to Heaven"?', category: 'music', difficulty: 'easy' },
  { question: 'Quale nota viene dopo sol nella scala?', category: 'music', difficulty: 'medium' },
  { question: 'In quale film un ragazzo scopre di essere un mago?', category: 'movies', difficulty: 'easy' },
  { question: 'Come si chiama la principessa in Frozen?', category: 'movies', difficulty: 'easy' },
  { question: 'In quale film c\'è un personaggio di nome Dory?', category: 'movies', difficulty: 'easy' },
  { question: 'In quale film le auto prendono vita?', category: 'movies', difficulty: 'easy' },
  { question: 'Come si chiama il pupazzo di neve in Frozen?', category: 'movies', difficulty: 'easy' },
  { question: 'In che anno finì la Seconda Guerra Mondiale?', category: 'history', difficulty: 'easy' },
  { question: 'Chi fu il primo uomo sulla Luna?', category: 'history', difficulty: 'easy' },
  { question: 'Quale impero costruì il Colosseo?', category: 'history', difficulty: 'easy' },
  { question: 'In quale paese iniziò il Rinascimento?', category: 'history', difficulty: 'medium' },
  { question: 'Chi scrisse la Dichiarazione di Indipendenza?', category: 'history', difficulty: 'easy' },
  { question: 'Quale meraviglia antica era in Egitto?', category: 'history', difficulty: 'easy' },
  { question: 'Quando cadde il Muro di Berlino?', category: 'history', difficulty: 'medium' },
  { question: 'Chi inventò la lampadina?', category: 'history', difficulty: 'easy' },
  { question: 'Quale civiltà costruì Machu Picchu?', category: 'history', difficulty: 'medium' },
  { question: 'In che secolo iniziò la Prima Guerra Mondiale?', category: 'history', difficulty: 'medium' },
  { question: 'Chi fu il primo presidente degli Stati Uniti?', category: 'history', difficulty: 'easy' },
  { question: 'Quale paese donò la Statua della Libertà agli USA?', category: 'history', difficulty: 'easy' },
  { question: 'Chi dipinse la Gioconda?', category: 'history', difficulty: 'easy' },
  { question: 'Quando l\'uomo sbarcò sulla Luna per la prima volta?', category: 'history', difficulty: 'easy' },
  { question: 'Quale impero fece costruire la Grande Muraglia?', category: 'history', difficulty: 'easy' },
  { question: 'Chi scoprì l\'America nel 1492?', category: 'history', difficulty: 'easy' },
  { question: 'Cosa significano le lettere CPU?', category: 'technology', difficulty: 'easy' },
  { question: 'Chi fondò Facebook?', category: 'technology', difficulty: 'easy' },
  { question: 'In che anno uscì il primo iPhone?', category: 'technology', difficulty: 'medium' },
  { question: 'Cosa significano le lettere WiFi?', category: 'technology', difficulty: 'medium' },
  { question: 'Quale azienda produce la PlayStation?', category: 'technology', difficulty: 'easy' },
  { question: 'Cosa significano le lettere USB?', category: 'technology', difficulty: 'medium' },
  { question: 'Chi fondò Microsoft?', category: 'technology', difficulty: 'easy' },
  { question: 'Come si chiama l\'assistente di Google?', category: 'technology', difficulty: 'easy' },
  { question: 'Quanti bit in un byte?', category: 'technology', difficulty: 'medium' },
  { question: 'Cosa significano le lettere HTML?', category: 'technology', difficulty: 'easy' },
  { question: 'Quale azienda creò Android?', category: 'technology', difficulty: 'easy' },
  { question: 'Cosa significano le lettere GPS?', category: 'technology', difficulty: 'easy' },
  { question: 'Come si chiama l\'assistente vocale di Amazon?', category: 'technology', difficulty: 'easy' },
  { question: 'In che anno fu fondato YouTube?', category: 'technology', difficulty: 'medium' },
  { question: 'Cosa significano le lettere RAM?', category: 'technology', difficulty: 'medium' },
  { question: 'Qual è l\'animale più veloce sulla terra?', category: 'nature', difficulty: 'easy' },
  { question: 'Qual è il mammifero più grande sulla Terra?', category: 'nature', difficulty: 'easy' },
  { question: 'Quante zampe ha un insetto?', category: 'nature', difficulty: 'easy' },
  { question: 'Qual è l\'unico mammifero che può volare?', category: 'nature', difficulty: 'easy' },
  { question: 'Quale pianeta è il Pianeta Rosso?', category: 'nature', difficulty: 'easy' },
  { question: 'Qual è l\'orso più grande?', category: 'nature', difficulty: 'easy' },
  { question: 'Quanti stomachi ha una mucca?', category: 'nature', difficulty: 'medium' },
  { question: 'Qual è l\'albero più alto?', category: 'nature', difficulty: 'medium' },
  { question: 'Quale uccello non può volare?', category: 'nature', difficulty: 'easy' },
  { question: 'Qual è il più piccolo uccello del mondo?', category: 'nature', difficulty: 'medium' },
  { question: 'Quanti bracci ha un polpo?', category: 'nature', difficulty: 'easy' },
  { question: 'Qual è il più grande animale oceanico?', category: 'nature', difficulty: 'easy' },
  { question: 'Quale animale dorme di più?', category: 'nature', difficulty: 'medium' },
  { question: 'Quale continente non ha rettili?', category: 'nature', difficulty: 'hard' },
  { question: 'Quante ossa ha il collo di una giraffa?', category: 'nature', difficulty: 'medium' },
  { question: 'Qual è la capitale della Francia?', category: 'travel', difficulty: 'easy' },
  { question: 'Quale paese ha più isole?', category: 'travel', difficulty: 'medium' },
  { question: 'Qual è il fiume più lungo d\'Europa?', category: 'travel', difficulty: 'medium' },
  { question: 'In quale città si trova l\'Acropoli?', category: 'travel', difficulty: 'easy' },
  { question: 'Qual è la capitale della Thailandia?', category: 'travel', difficulty: 'easy' },
  { question: 'In quale paese si trova il Taj Mahal?', category: 'travel', difficulty: 'easy' },
  { question: 'Qual è il paese più piccolo del mondo?', category: 'travel', difficulty: 'easy' },
  { question: 'In quale città si trova l\'Empire State Building?', category: 'travel', difficulty: 'easy' },
  { question: 'Qual è la capitale dell\'Egitto?', category: 'travel', difficulty: 'easy' },
  { question: 'In quale continente si trova il Sahara?', category: 'travel', difficulty: 'easy' },
  { question: 'Qual è la capitale dell\'Argentina?', category: 'travel', difficulty: 'easy' },
  { question: 'In quale paese si trova la Grande Barriera Corallina?', category: 'travel', difficulty: 'easy' },
  { question: 'Qual è la capitale del Sudafrica?', category: 'travel', difficulty: 'easy' },
  { question: 'Quale città europea è divisa dal Bosforo?', category: 'travel', difficulty: 'medium' },
  { question: 'Qual è la capitale più alta del mondo?', category: 'travel', difficulty: 'hard' },
  { question: 'Qual è la tua destinazione preferita per le vacanze?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è il miglior consiglio che ti hanno dato?', category: 'general', difficulty: 'easy' },
  { question: 'Cosa faresti se avessi un giorno libero?', category: 'general', difficulty: 'easy' },
  { question: 'Quale abilità vorresti imparare?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è il tuo modo preferito per rilassarti?', category: 'general', difficulty: 'easy' },
  { question: 'Qual è stato il sogno più strano che hai fatto?', category: 'funny', difficulty: 'medium' },
  { question: 'Quale sarebbe la peggiore canzone a un funerale?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è la cosa più imbarazzante nella tua stanza?', category: 'funny', difficulty: 'easy' },
  { question: 'Quale sarebbe un brutto nome per una pietra come animale?', category: 'funny', difficulty: 'easy' },
  { question: 'Qual è la peggiore frase di approccio che hai sentito?', category: 'funny', difficulty: 'easy' },
  { question: 'Quanti lati ha un segnale di stop?', category: 'random', difficulty: 'easy' },
  { question: 'Quanto fa 11 per 11?', category: 'random', difficulty: 'medium' },
  { question: 'Quante facce ha un cubo?', category: 'random', difficulty: 'easy' },
  { question: 'Qual è l\'unico numero primo pari?', category: 'random', difficulty: 'medium' },
  { question: 'Quante ossa ha la mano umana?', category: 'science', difficulty: 'medium' },
  { question: 'Qual è il simbolo chimico del sodio?', category: 'science', difficulty: 'easy' },
  { question: 'Quale pianeta è più lontano dal Sole?', category: 'science', difficulty: 'easy' },
  { question: 'Qual è l\'osso più piccolo del corpo umano?', category: 'science', difficulty: 'hard' },
  { question: 'Quale gas respiriamo di più?', category: 'science', difficulty: 'easy' },
  { question: 'Qual è la capitale della Spagna?', category: 'geography', difficulty: 'easy' },
  { question: 'Quale paese ha più vulcani?', category: 'geography', difficulty: 'medium' },
  { question: 'Qual è la capitale della Russia?', category: 'geography', difficulty: 'easy' },
  { question: 'Qual è l\'ingrediente principale del cioccolato?', category: 'food', difficulty: 'easy' },
  { question: 'Da quale frutto si fa il vino?', category: 'food', difficulty: 'easy' },
  { question: 'Qual è la carne più consumata al mondo?', category: 'food', difficulty: 'medium' },
  { question: 'Quanti giocatori in una squadra di cricket?', category: 'sports', difficulty: 'medium' },
  { question: 'In quale sport si fa un home run?', category: 'sports', difficulty: 'easy' },
  { question: 'Quale strumento ha 88 tasti?', category: 'music', difficulty: 'easy' },
  { question: 'Chi cantava "Thriller"?', category: 'music', difficulty: 'easy' },
  { question: 'In quale film un ragazzo viene morso da un ragno?', category: 'movies', difficulty: 'easy' },
  { question: 'Come si chiama la scuola di magia in Harry Potter?', category: 'movies', difficulty: 'easy' },
  { question: 'What is your favorite memory from childhood?', category: 'general', difficulty: 'easy' },
  { question: 'If you could have dinner with anyone, who would it be?', category: 'general', difficulty: 'easy' },
  { question: 'What is the best book you have ever read?', category: 'general', difficulty: 'easy' },
  { question: 'What would you do if you won the lottery?', category: 'general', difficulty: 'easy' },
  { question: 'What is your favorite season and why?', category: 'general', difficulty: 'easy' },
  { question: 'What hobby would you like to try?', category: 'general', difficulty: 'easy' },
  { question: 'What is the most beautiful place you have been?', category: 'general', difficulty: 'easy' },
  { question: 'What superpower would you choose?', category: 'general', difficulty: 'easy' },
  { question: 'What is your go-to karaoke song?', category: 'general', difficulty: 'easy' },
  { question: 'What is the worst haircut you have had?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst thing to say on a first date?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the funniest autocorrect fail you have seen?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a terrible name for a perfume?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the most ridiculous fashion trend?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst animal to be reincarnated as?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the silliest thing you have ever bought?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a bad name for a gym?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst combination of foods?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst job for a vampire?', category: 'funny', difficulty: 'easy' },
  { question: 'How many degrees are in a right angle?', category: 'random', difficulty: 'easy' },
  { question: 'What is 9 times 9?', category: 'random', difficulty: 'easy' },
  { question: 'How many sides does a pentagon have?', category: 'random', difficulty: 'easy' },
  { question: 'What is the square root of 64?', category: 'random', difficulty: 'easy' },
  { question: 'How many days are in a leap year?', category: 'random', difficulty: 'easy' },
  { question: 'What is 15 percent of 100?', category: 'random', difficulty: 'easy' },
  { question: 'How many continents start with the letter A?', category: 'random', difficulty: 'medium' },
  { question: 'What is the only number that is the same in English and French?', category: 'random', difficulty: 'hard' },
  { question: 'How many keys are on a standard computer keyboard?', category: 'random', difficulty: 'medium' },
  { question: 'What is the largest prime number under 20?', category: 'random', difficulty: 'medium' },
  { question: 'What is the powerhouse of the cell?', category: 'science', difficulty: 'easy' },
  { question: 'How many bones are in the human spine?', category: 'science', difficulty: 'medium' },
  { question: 'What is the chemical symbol for carbon?', category: 'science', difficulty: 'easy' },
  { question: 'What planet is known for its rings?', category: 'science', difficulty: 'easy' },
  { question: 'How many teeth do adults typically have?', category: 'science', difficulty: 'easy' },
  { question: 'What is the smallest planet in our solar system?', category: 'science', difficulty: 'easy' },
  { question: 'What gas makes up most of the atmosphere?', category: 'science', difficulty: 'easy' },
  { question: 'How many chambers does the human heart have?', category: 'science', difficulty: 'easy' },
  { question: 'What is the speed of sound?', category: 'science', difficulty: 'hard' },
  { question: 'What is the chemical symbol for oxygen?', category: 'science', difficulty: 'easy' },
  { question: 'What is the capital of Greece?', category: 'geography', difficulty: 'easy' },
  { question: 'Which country is home to the kangaroo?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Turkey?', category: 'geography', difficulty: 'easy' },
  { question: 'Which river flows through Paris?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Poland?', category: 'geography', difficulty: 'easy' },
  { question: 'Which country has the most population in Africa?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the capital of Sweden?', category: 'geography', difficulty: 'easy' },
  { question: 'Which sea is the saltiest?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the capital of the Netherlands?', category: 'geography', difficulty: 'easy' },
  { question: 'Which mountain is the tallest in the world?', category: 'geography', difficulty: 'easy' },
  { question: 'What vegetable is known as the king of vegetables?', category: 'food', difficulty: 'medium' },
  { question: 'What is the main ingredient in tzatziki?', category: 'food', difficulty: 'easy' },
  { question: 'What nut is in pesto?', category: 'food', difficulty: 'easy' },
  { question: 'What fruit is known as the king of fruits?', category: 'food', difficulty: 'medium' },
  { question: 'What is the primary ingredient in falafel?', category: 'food', difficulty: 'easy' },
  { question: 'What type of cheese is used in Greek salad?', category: 'food', difficulty: 'easy' },
  { question: 'What grain is used to make beer?', category: 'food', difficulty: 'easy' },
  { question: 'What is the main ingredient in guacamole?', category: 'food', difficulty: 'easy' },
  { question: 'What fruit is dried to make prunes?', category: 'food', difficulty: 'easy' },
  { question: 'What is the most expensive spice in the world?', category: 'food', difficulty: 'medium' },
  { question: 'How many players are on a rugby team?', category: 'sports', difficulty: 'medium' },
  { question: 'In which sport do you use a racket and shuttlecock?', category: 'sports', difficulty: 'easy' },
  { question: 'What color is the ball in pool?', category: 'sports', difficulty: 'easy' },
  { question: 'How many Grand Slam tournaments does tennis have per year?', category: 'sports', difficulty: 'easy' },
  { question: 'In which country did basketball originate?', category: 'sports', difficulty: 'easy' },
  { question: 'What is the national sport of Canada?', category: 'sports', difficulty: 'medium' },
  { question: 'How many minutes are in a soccer half?', category: 'sports', difficulty: 'easy' },
  { question: 'In which sport do you score a try?', category: 'sports', difficulty: 'medium' },
  { question: 'What is the diameter of a basketball hoop?', category: 'sports', difficulty: 'hard' },
  { question: 'Which country has won the most World Cups?', category: 'sports', difficulty: 'easy' },
  { question: 'What instrument has 88 keys?', category: 'music', difficulty: 'easy' },
  { question: 'Who is known as the King of Pop?', category: 'music', difficulty: 'easy' },
  { question: 'How many strings does a harp have?', category: 'music', difficulty: 'hard' },
  { question: 'What is the most played song at weddings?', category: 'music', difficulty: 'medium' },
  { question: 'In which city did jazz originate?', category: 'music', difficulty: 'medium' },
  { question: 'What band sang "Sweet Child O\' Mine"?', category: 'music', difficulty: 'easy' },
  { question: 'How many members are in a trio?', category: 'music', difficulty: 'easy' },
  { question: 'What is the highest male singing voice?', category: 'music', difficulty: 'easy' },
  { question: 'Who wrote the Ninth Symphony?', category: 'music', difficulty: 'easy' },
  { question: 'What instrument is known as the king of instruments?', category: 'music', difficulty: 'medium' },
  { question: 'In which film does a boy ride a dragon?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the dragon in Game of Thrones?', category: 'movies', difficulty: 'medium' },
  { question: 'Which film features a talking raccoon?', category: 'movies', difficulty: 'easy' },
  { question: 'In which film does a robot become human?', category: 'movies', difficulty: 'medium' },
  { question: 'What is the name of the ship in Titanic?', category: 'movies', difficulty: 'easy' },
  { question: 'Which studio made Shrek?', category: 'movies', difficulty: 'easy' },
  { question: 'In which film does a clown fish search for his son?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the dinosaur in Jurassic Park?', category: 'movies', difficulty: 'easy' },
  { question: 'Which film has "May the Force be with you"?', category: 'movies', difficulty: 'easy' },
  { question: 'In which year did the Titanic sink?', category: 'movies', difficulty: 'medium' },
  { question: 'Who was the first woman to win a Nobel Prize?', category: 'history', difficulty: 'medium' },
  { question: 'In which year did the French Revolution begin?', category: 'history', difficulty: 'medium' },
  { question: 'Who built the first printing press?', category: 'history', difficulty: 'medium' },
  { question: 'Which empire was ruled by Genghis Khan?', category: 'history', difficulty: 'easy' },
  { question: 'When did the Roman Empire fall?', category: 'history', difficulty: 'hard' },
  { question: 'Who was the British prime minister during World War II?', category: 'history', difficulty: 'easy' },
  { question: 'Which country invented paper?', category: 'history', difficulty: 'medium' },
  { question: 'Who wrote the Odyssey?', category: 'history', difficulty: 'easy' },
  { question: 'In which year did man first fly in an airplane?', category: 'history', difficulty: 'medium' },
  { question: 'Who discovered penicillin?', category: 'history', difficulty: 'medium' },
  { question: 'What does AI stand for?', category: 'technology', difficulty: 'easy' },
  { question: 'Who founded Tesla?', category: 'technology', difficulty: 'easy' },
  { question: 'What year was the first computer virus created?', category: 'technology', difficulty: 'hard' },
  { question: 'What does VPN stand for?', category: 'technology', difficulty: 'medium' },
  { question: 'Which company makes the Switch?', category: 'technology', difficulty: 'easy' },
  { question: 'What does SSD stand for?', category: 'technology', difficulty: 'medium' },
  { question: 'Who created Linux?', category: 'technology', difficulty: 'hard' },
  { question: 'What is the name of Apple\'s voice assistant?', category: 'technology', difficulty: 'easy' },
  { question: 'In what year was the first email sent?', category: 'technology', difficulty: 'hard' },
  { question: 'What does HTTP stand for?', category: 'technology', difficulty: 'medium' },
  { question: 'Which animal can live the longest?', category: 'nature', difficulty: 'medium' },
  { question: 'What is the only mammal that lays eggs?', category: 'nature', difficulty: 'easy' },
  { question: 'How many eyes does a bee have?', category: 'nature', difficulty: 'medium' },
  { question: 'What is the fastest bird?', category: 'nature', difficulty: 'medium' },
  { question: 'Which animal has the longest migration?', category: 'nature', difficulty: 'hard' },
  { question: 'What is the largest land animal?', category: 'nature', difficulty: 'easy' },
  { question: 'How many stomachs does a goat have?', category: 'nature', difficulty: 'medium' },
  { question: 'What is the only bird that can fly backward?', category: 'nature', difficulty: 'medium' },
  { question: 'Which insect is the strongest relative to its size?', category: 'nature', difficulty: 'hard' },
  { question: 'What is the loudest animal on Earth?', category: 'nature', difficulty: 'hard' },
  { question: 'What is the capital of Portugal?', category: 'travel', difficulty: 'easy' },
  { question: 'Which country has the most UNESCO World Heritage sites?', category: 'travel', difficulty: 'hard' },
  { question: 'What is the capital of Norway?', category: 'travel', difficulty: 'easy' },
  { question: 'In which city is the Parthenon?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of Switzerland?', category: 'travel', difficulty: 'easy' },
  { question: 'Which country is the Great Wall in?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of Ireland?', category: 'travel', difficulty: 'easy' },
  { question: 'In which city would you find Big Ben?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of Austria?', category: 'travel', difficulty: 'easy' },
  { question: 'Which country has the most lakes?', category: 'travel', difficulty: 'hard' },
];
