module.exports = [
  { question: 'Çfarë ngjyre ka qielli?', category: 'general', difficulty: 'easy' },
  { question: 'Sa këmbë ka qeni?', category: 'general', difficulty: 'easy' },
  { question: 'Sa bën 2 + 2?', category: 'general', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Francës?', category: 'general', difficulty: 'easy' },
  { question: 'Cili kafshë bën "muu"?', category: 'general', difficulty: 'easy' },
  { question: 'Sa ditë ka një javë?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë forme ka topi?', category: 'general', difficulty: 'easy' },
  { question: 'Me çfarë shkruhet në letër?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë është e kundërta e nxehtë?', category: 'general', difficulty: 'easy' },
  { question: 'Sa gishta ke në një dorë?', category: 'general', difficulty: 'easy' },
  { question: 'Në cilën planetë jetojmë?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë ngjyre ka bari?', category: 'general', difficulty: 'easy' },
  { question: 'Cili është oqeani më i madh?', category: 'general', difficulty: 'medium' },
  { question: 'Sa kontinente ka?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë gjuhe flitet në Spanjë?', category: 'general', difficulty: 'easy' },
  { question: 'Cila stinë vjen pas verës?', category: 'general', difficulty: 'easy' },
  { question: 'Sa orë ka një ditë?', category: 'general', difficulty: 'easy' },
  { question: 'Cili është kafsha më e lartë?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë bëjnë bletët?', category: 'general', difficulty: 'easy' },
  { question: 'Sa bën 10 minus 3?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë është e kundërta e lart?', category: 'general', difficulty: 'easy' },
  { question: 'Sa rrota ka një makinë?', category: 'general', difficulty: 'easy' },
  { question: 'Si quhet macja e vogël?', category: 'general', difficulty: 'easy' },
  { question: 'Cili frut është i verdhë dhe i lakuar?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë vihet në këmbë?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë është gjëja më qesharake që ke parë ndonjëherë?', category: 'funny', difficulty: 'medium' },
  { question: 'Cili do të ishte emri më i keq për një kafshë shtëpiake?', category: 'funny', difficulty: 'easy' },
  { question: 'Cila është superfuqia më qesharake që mund të imagjinosh?', category: 'funny', difficulty: 'easy' },
  { question: 'Nëse mund të haje vetëm një ushqim përjetë, cili do të ishte?', category: 'funny', difficulty: 'easy' },
  { question: 'Cili do të ishte këshilla më e keqe që mund t\'i jepje dikujt?', category: 'funny', difficulty: 'medium' },
  { question: 'Si do ta quaje varkën tënde?', category: 'funny', difficulty: 'easy' },
  { question: 'Cili do të ishte dhurata më e keqe që mund të merrje?', category: 'funny', difficulty: 'easy' },
  { question: 'Si cili kafshë do të ishte më keq të ringjalleje?', category: 'funny', difficulty: 'medium' },
  { question: 'Çfarë është gjëja më e mërzitshme që mund të imagjinosh?', category: 'funny', difficulty: 'easy' },
  { question: 'Cili do të ishte një emër i tmerrshëm për një restorant?', category: 'funny', difficulty: 'easy' },
  { question: 'Cila do të ishte superfuqia më e keqe?', category: 'funny', difficulty: 'easy' },
  { question: 'Cila është perimesi më i keq?', category: 'funny', difficulty: 'easy' },
  { question: 'Cili do të ishte një emër i keq për një bandë?', category: 'funny', difficulty: 'easy' },
  { question: 'Çfarë është gjëja më e keqe për ta harruar në një udhëtim?', category: 'funny', difficulty: 'easy' },
  { question: 'A do të preferoje të kishe duar në vend të këmbëve apo këmbë në vend të duarve?', category: 'general', difficulty: 'easy' },
  { question: 'A do të preferoje të ishe gjithmonë 10 minuta vonë apo 20 minuta herët?', category: 'general', difficulty: 'easy' },
  { question: 'A do të preferoje të mos kishe telefon apo televizor?', category: 'general', difficulty: 'easy' },
  { question: 'A do të preferoje të haje vetëm të ëmbla apo vetëm të kripura?', category: 'general', difficulty: 'easy' },
  { question: 'A do të preferoje të jetosh në të kaluarën apo në të ardhmen?', category: 'general', difficulty: 'easy' },
  { question: 'A do të preferoje të mund të fluturoje apo të jesh i padukshëm?', category: 'general', difficulty: 'easy' },
  { question: 'A do të preferoje verë apo dimër gjatë gjithë vitit?', category: 'general', difficulty: 'easy' },
  { question: 'A do të preferoje të kishe mace apo qen?', category: 'general', difficulty: 'easy' },
  { question: 'A do të preferoje të mos përdorje kurrë rrjetet sociale apo të mos shikosh kurrë film?', category: 'general', difficulty: 'easy' },
  { question: 'A do të preferoje të flasësh të gjitha gjuhët apo të bisedosh me kafshët?', category: 'general', difficulty: 'easy' },
  { question: 'A do të preferoje pizza të pakufishme apo sushi të pakufishëm?', category: 'general', difficulty: 'easy' },
  { question: 'A do të preferoje të mund të teleportohesh apo të udhëtoje në kohë?', category: 'general', difficulty: 'easy' },
  { question: 'A do të preferoje të humbje zërin apo dëgjimin?', category: 'general', difficulty: 'easy' },
  { question: 'A do të preferoje një elefant të vogël apo një hamster gjigant?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë dite është sot?', category: 'random', difficulty: 'easy' },
  { question: 'Në cilin muaj jemi?', category: 'random', difficulty: 'easy' },
  { question: 'Cila është shkronja e parë e alfabetit?', category: 'random', difficulty: 'easy' },
  { question: 'Sa brinjë ka një trekëndësh?', category: 'random', difficulty: 'easy' },
  { question: 'Çfarë është e kundërta e ditës?', category: 'random', difficulty: 'easy' },
  { question: 'Si quhet qeni i vogël?', category: 'random', difficulty: 'easy' },
  { question: 'Cila është kafsha më e shpejtë në tokë?', category: 'random', difficulty: 'medium' },
  { question: 'Sa këmbë ka një merimangë?', category: 'random', difficulty: 'easy' },
  { question: 'Cili është kontinenti më i vogël?', category: 'random', difficulty: 'medium' },
  { question: 'Sa bën 100 pjesëtuar me 10?', category: 'random', difficulty: 'easy' },
  { question: 'Sa muaj ka një vit?', category: 'random', difficulty: 'easy' },
  { question: 'Sa bën 5 herë 5?', category: 'random', difficulty: 'easy' },
  { question: 'Sa ngjyra ka ylberi?', category: 'random', difficulty: 'easy' },
  { question: 'Cila është planeti më i madh në sistemin tonë diellor?', category: 'science', difficulty: 'easy' },
  { question: 'Sa kocka ka një i rritur?', category: 'science', difficulty: 'medium' },
  { question: 'Cili është simboli kimik i ujit?', category: 'science', difficulty: 'easy' },
  { question: 'Çfarë force na mban në tokë?', category: 'science', difficulty: 'easy' },
  { question: 'Çfarë gazi thithin bimët nga ajri?', category: 'science', difficulty: 'easy' },
  { question: 'Sa dhëmbë ka zakonisht një i rritur?', category: 'science', difficulty: 'medium' },
  { question: 'Në sa gradë Celsius vlon uji?', category: 'science', difficulty: 'easy' },
  { question: 'Cilit planeti i thuhet Planeti i Kuq?', category: 'science', difficulty: 'easy' },
  { question: 'Sa është shpejtësia e dritës?', category: 'science', difficulty: 'hard' },
  { question: 'Sa zemra ka një oktapod?', category: 'science', difficulty: 'medium' },
  { question: 'Cila është kryeqyteti i Japonisë?', category: 'geography', difficulty: 'easy' },
  { question: 'Cila është lumi më i gjatë në botë?', category: 'geography', difficulty: 'medium' },
  { question: 'Cili është vendi më i madh sipas sipërfaqes?', category: 'geography', difficulty: 'easy' },
  { question: 'Në cilin kontinent ndodhet Egjipti?', category: 'geography', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Australisë?', category: 'geography', difficulty: 'easy' },
  { question: 'Cili oqean është më i ftohtë?', category: 'geography', difficulty: 'medium' },
  { question: 'Cili është vendi më i vogël në botë?', category: 'geography', difficulty: 'medium' },
  { question: 'Cili vend ka më shumë banorë?', category: 'geography', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Brazilit?', category: 'geography', difficulty: 'easy' },
  { question: 'Në cilin vend ndodhet Kulla Eifel?', category: 'geography', difficulty: 'easy' },
  { question: 'Nga cili frut bëhen rrush të thatë?', category: 'food', difficulty: 'easy' },
  { question: 'Çfarë ngjyre ka karota?', category: 'food', difficulty: 'easy' },
  { question: 'Çfarë fitohet kur ngrin uji?', category: 'food', difficulty: 'easy' },
  { question: 'Cili është përbërësi kryesor i bukës?', category: 'food', difficulty: 'easy' },
  { question: 'Nga cili vend origjinoi pica?', category: 'food', difficulty: 'easy' },
  { question: 'Çfarë ngjyre ka bananja kur është e pjekur?', category: 'food', difficulty: 'easy' },
  { question: 'Cila perime përdoret për turshi?', category: 'food', difficulty: 'easy' },
  { question: 'Mjaltin e bëjnë kush?', category: 'food', difficulty: 'easy' },
  { question: 'Çfarë lloj ushqimi është suushi?', category: 'food', difficulty: 'easy' },
  { question: 'Cili frut është i kuq me farë jashtë?', category: 'food', difficulty: 'easy' },
  { question: 'Sa lojtarë ka një ekip futbolli?', category: 'sports', difficulty: 'easy' },
  { question: 'Çfarë ngjyre ka unaza e mesme në flamurin olimpik?', category: 'sports', difficulty: 'medium' },
  { question: 'Në cilin sport bëhet touchdown?', category: 'sports', difficulty: 'easy' },
  { question: 'Sa turne Grand Slam ka në tenis?', category: 'sports', difficulty: 'medium' },
  { question: 'Çfarë forme ka topi i basketbollit?', category: 'sports', difficulty: 'easy' },
  { question: 'Në cilin sport përdoret puck?', category: 'sports', difficulty: 'easy' },
  { question: 'Sa xhiro ka Indy 500?', category: 'sports', difficulty: 'medium' },
  { question: 'Në cilin vend u shpik golfi?', category: 'sports', difficulty: 'medium' },
  { question: 'Sa lojtarë ka një ekip basketbolli?', category: 'sports', difficulty: 'easy' },
  { question: 'Çfarë sporti luhet në Wimbledon?', category: 'sports', difficulty: 'easy' },
  { question: 'Sa tela ka një kitarë standarde?', category: 'music', difficulty: 'easy' },
  { question: 'Cili instrument ka taste të zeza dhe të bardha?', category: 'music', difficulty: 'easy' },
  { question: 'Sa rrahje ka valsi?', category: 'music', difficulty: 'medium' },
  { question: 'Cili është instrumenti më i madh në orkestër?', category: 'music', difficulty: 'easy' },
  { question: 'Cila bandë këndoi "Yellow Submarine"?', category: 'music', difficulty: 'easy' },
  { question: 'Sa nota ka një oktavë?', category: 'music', difficulty: 'medium' },
  { question: 'Çfarë instrumenti luan bateristi?', category: 'music', difficulty: 'easy' },
  { question: 'Në cilin vend lindi opera?', category: 'music', difficulty: 'medium' },
  { question: 'Cila është zëri më i lartë në këngë?', category: 'music', difficulty: 'easy' },
  { question: 'Sa tela ka violina?', category: 'music', difficulty: 'easy' },
  { question: 'Në cilin film një luan bëhet mbret?', category: 'movies', difficulty: 'easy' },
  { question: 'Si quhet magjistari në Magjistari i Oz?', category: 'movies', difficulty: 'easy' },
  { question: 'Cili studio bëri Frozen?', category: 'movies', difficulty: 'easy' },
  { question: 'Çfarë kafshe është Remy në Ratatouille?', category: 'movies', difficulty: 'easy' },
  { question: 'Në cilin film një djalë gjen një xhind në një llambë?', category: 'movies', difficulty: 'easy' },
  { question: 'Si quhet peshku në Gjetja e Nemos?', category: 'movies', difficulty: 'easy' },
  { question: 'Në cilin film ka personazh të quajtur Simba?', category: 'movies', difficulty: 'easy' },
  { question: 'Çfarë ngjyre ka fustani i Hirushkës?', category: 'movies', difficulty: 'easy' },
  { question: 'Në cilin film lodrat marrin jetë?', category: 'movies', difficulty: 'easy' },
  { question: 'Çfarë kafshe është Dumbo?', category: 'movies', difficulty: 'easy' },
  { question: 'Sa bën 3 herë 4?', category: 'general', difficulty: 'easy' },
  { question: 'Sa sy ka një person?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë është dielli?', category: 'general', difficulty: 'easy' },
  { question: 'Me çfarë fluturojnë zogjtë?', category: 'general', difficulty: 'easy' },
  { question: 'Nga çfarë bëhet bora?', category: 'general', difficulty: 'easy' },
  { question: 'Sa minuta ka një orë?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë është e kundërta e madh?', category: 'general', difficulty: 'easy' },
  { question: 'Me çfarë shikon?', category: 'general', difficulty: 'easy' },
  { question: 'Cila kafshë ka një bathë të gjatë?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë ngjyre ka dielli?', category: 'general', difficulty: 'easy' },
  { question: 'Sa brinjë ka një katror?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë marrin frymë peshqit?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë bie nga qielli kur bie shi?', category: 'general', difficulty: 'easy' },
  { question: 'Sa bën 15 plus 15?', category: 'general', difficulty: 'easy' },
  { question: 'Si quhet qengji?', category: 'general', difficulty: 'easy' },
  { question: 'Sa këmbë ka një karrige?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë është e kundërta e shpejtë?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë lexon në një libër?', category: 'general', difficulty: 'easy' },
  { question: 'Cila stinë ka më shumë borë?', category: 'general', difficulty: 'easy' },
  { question: 'Cili do të ishte titulli më i keq i punës?', category: 'funny', difficulty: 'easy' },
  { question: 'Cila është shpikja më e padobishme?', category: 'funny', difficulty: 'easy' },
  { question: 'Cili do të ishte emër i keq për një sapun?', category: 'funny', difficulty: 'easy' },
  { question: 'Cili është shijja më e keqe e akullores?', category: 'funny', difficulty: 'easy' },
  { question: 'Cila do të ishte fjalëkalim i tmerrshëm?', category: 'funny', difficulty: 'easy' },
  { question: 'Cila është mënyra më qesharake për të udhëtuar?', category: 'funny', difficulty: 'easy' },
  { question: 'Për çfarë do të ishte më keq të jesh alergjik?', category: 'funny', difficulty: 'easy' },
  { question: 'Çfarë është më e turpshme të harrosh?', category: 'funny', difficulty: 'easy' },
  { question: 'Cili do të ishte emër i keq për një spital?', category: 'funny', difficulty: 'easy' },
  { question: 'Cila do të ishte superfuqia më e keqe në një festë?', category: 'funny', difficulty: 'easy' },
  { question: 'A do të preferoje të mos kishe shije apo të mos kishe erë?', category: 'general', difficulty: 'easy' },
  { question: 'A do të luftoje një rosë madhësi kali apo 100 kuaj madhësi rose?', category: 'general', difficulty: 'easy' },
  { question: 'A do të preferoje butonin rewind apo pause për jetën?', category: 'general', difficulty: 'easy' },
  { question: 'A do të këndoje gjithmonë apo të pëshpëriste gjithmonë?', category: 'general', difficulty: 'easy' },
  { question: 'A do të preferoje të mos kishe vetulla apo qepalla?', category: 'general', difficulty: 'easy' },
  { question: 'A do të ishe i famshëm apo i pasur?', category: 'general', difficulty: 'easy' },
  { question: 'A do të kishe bisht apo brirë?', category: 'general', difficulty: 'easy' },
  { question: 'A do të jetoje pa muzikë apo pa filma?', category: 'general', difficulty: 'easy' },
  { question: 'A do të preferoje kuzhinier personal apo pilot personal?', category: 'general', difficulty: 'easy' },
  { question: 'A do të dije kur vdes apo si vdes?', category: 'general', difficulty: 'easy' },
  { question: 'Sa bën 7 herë 8?', category: 'random', difficulty: 'medium' },
  { question: 'Sa zero ka një mijë?', category: 'random', difficulty: 'easy' },
  { question: 'Cila është shkronja e fundit e alfabetit?', category: 'random', difficulty: 'easy' },
  { question: 'Sa brinjë ka gjashtëkëndëshi?', category: 'random', difficulty: 'easy' },
  { question: 'Sa është 50 për qind e 100?', category: 'random', difficulty: 'easy' },
  { question: 'Sa sekonda ka një minutë?', category: 'random', difficulty: 'easy' },
  { question: 'Në çfarë temperature ngrin uji në Celsius?', category: 'random', difficulty: 'easy' },
  { question: 'Sa vija ka flamuri amerikan?', category: 'random', difficulty: 'medium' },
  { question: 'Sa bën 12 herë 12?', category: 'random', difficulty: 'medium' },
  { question: 'Sa këmbë ka një brumbull?', category: 'random', difficulty: 'easy' },
  { question: 'Cili është simboli kimik i arit?', category: 'science', difficulty: 'easy' },
  { question: 'Sa planete ka sistemi ynë diellor?', category: 'science', difficulty: 'easy' },
  { question: 'Cili organ pompën gjakun?', category: 'science', difficulty: 'easy' },
  { question: 'Çfarë është H2O?', category: 'science', difficulty: 'easy' },
  { question: 'Çfarë gazi nxjerrin njerëzit?', category: 'science', difficulty: 'easy' },
  { question: 'Sa krahë ka një flutur?', category: 'science', difficulty: 'easy' },
  { question: 'Cila është ylli më i afërt me Tokën?', category: 'science', difficulty: 'easy' },
  { question: 'Cila është substanca më e fortë natyrore?', category: 'science', difficulty: 'medium' },
  { question: 'Sa kromozome kanë njerëzit?', category: 'science', difficulty: 'hard' },
  { question: 'Cili planet është më afër diellit?', category: 'science', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Gjermanisë?', category: 'geography', difficulty: 'easy' },
  { question: 'Në cilin vend janë Piramidat?', category: 'geography', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Italisë?', category: 'geography', difficulty: 'easy' },
  { question: 'Cili oqean është midis Amerikës dhe Europës?', category: 'geography', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Kanadasë?', category: 'geography', difficulty: 'easy' },
  { question: 'Në cilin vend është Kulla e Pizës?', category: 'geography', difficulty: 'easy' },
  { question: 'Cili është vargu mali më i gjatë?', category: 'geography', difficulty: 'medium' },
  { question: 'Cili vend ka Murin e Madh?', category: 'geography', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Meksikës?', category: 'geography', difficulty: 'easy' },
  { question: 'Në cilin vend është Statuja e Lirisë?', category: 'geography', difficulty: 'easy' },
  { question: 'Cila perime përdoret për patate të skuqura?', category: 'food', difficulty: 'easy' },
  { question: 'Çfarë ngjyre ka mollë?', category: 'food', difficulty: 'easy' },
  { question: 'Çfarë vendoset në toster?', category: 'food', difficulty: 'easy' },
  { question: 'Cili është përbërësi kryesor i humusit?', category: 'food', difficulty: 'easy' },
  { question: 'Cili frut është jeshil jashtë dhe kuq brenda?', category: 'food', difficulty: 'easy' },
  { question: 'Çfarë shtohet në çaj për ta bërë të ëmbël?', category: 'food', difficulty: 'easy' },
  { question: 'Nga çfarë bëhet ketchupi?', category: 'food', difficulty: 'easy' },
  { question: 'Çfarë ngjyre ka qumështi?', category: 'food', difficulty: 'easy' },
  { question: 'Cili drithë përdoret për oriz?', category: 'food', difficulty: 'easy' },
  { question: 'Cili është përbërësi kryesor i guacamole?', category: 'food', difficulty: 'easy' },
  { question: 'Sa pikë vlen një touchdown?', category: 'sports', difficulty: 'easy' },
  { question: 'Në cilin sport goditet flutura?', category: 'sports', difficulty: 'easy' },
  { question: 'Sa lojtarë ka ekipi i bejsbollit?', category: 'sports', difficulty: 'medium' },
  { question: 'Çfarë ngjyre jersey mban lideri i Tour de France?', category: 'sports', difficulty: 'medium' },
  { question: 'Në cilin sport bëhet bowling?', category: 'sports', difficulty: 'easy' },
  { question: 'Sa Grand Slam fitoi Serena Williams?', category: 'sports', difficulty: 'hard' },
  { question: 'Çfarë forme ka topi i futbollit amerikan?', category: 'sports', difficulty: 'easy' },
  { question: 'Në cilin vend filloi maratona?', category: 'sports', difficulty: 'medium' },
  { question: 'Sa unaza ka flamuri olimpik?', category: 'sports', difficulty: 'easy' },
  { question: 'Cili sport përdor rrjetë dhe top?', category: 'sports', difficulty: 'easy' },
  { question: 'Sa taste ka një piano standard?', category: 'music', difficulty: 'medium' },
  { question: 'Çfarë instrumenti luante Elvis?', category: 'music', difficulty: 'easy' },
  { question: 'Sa tela ka ukulele?', category: 'music', difficulty: 'easy' },
  { question: 'Cila është zëri më i ulët i këndimit?', category: 'music', difficulty: 'easy' },
  { question: 'Në cilin qytet është e famshme Opera?', category: 'music', difficulty: 'medium' },
  { question: 'Cila bandë kishte "Bohemian Rhapsody"?', category: 'music', difficulty: 'easy' },
  { question: 'Sa anëtarë ka një kuartet?', category: 'music', difficulty: 'easy' },
  { question: 'Cili instrument ka rrëshqitës?', category: 'music', difficulty: 'easy' },
  { question: 'Beethoven është i cili zhanër?', category: 'music', difficulty: 'easy' },
  { question: 'Sa albume lançuan Beatles?', category: 'music', difficulty: 'hard' },
  { question: 'Në cilin film një djalë shkon në shkollën e magjistarëve?', category: 'movies', difficulty: 'easy' },
  { question: 'Si quhet peshku i peshqit në Jaws?', category: 'movies', difficulty: 'easy' },
  { question: 'Në cilin film thuhet "I will find you"?', category: 'movies', difficulty: 'medium' },
  { question: 'Çfarë kafshe është Gomari në Shrek?', category: 'movies', difficulty: 'easy' },
  { question: 'Në cilin film një robot thotë "I\'ll be back"?', category: 'movies', difficulty: 'easy' },
  { question: 'Si quhet dragoi në Si të stërvitni dragua tuaj?', category: 'movies', difficulty: 'easy' },
  { question: 'Cili studio bëri Toy Story?', category: 'movies', difficulty: 'easy' },
  { question: 'Si quhet luani në Mbreti i luanëve?', category: 'movies', difficulty: 'easy' },
  { question: 'Në cilin film një vajzë ka flokë të gjata magjike?', category: 'movies', difficulty: 'easy' },
  { question: 'Çfarë mjeti përdor Doc në Kthim në të ardhmen?', category: 'movies', difficulty: 'easy' },
  { question: 'Sa bën 20 plus 30?', category: 'general', difficulty: 'easy' },
  { question: 'Sa hundë ka një person?', category: 'general', difficulty: 'easy' },
  { question: 'Me çfarë dëgjon?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë është e kundërta e lagësht?', category: 'general', difficulty: 'easy' },
  { question: 'Sa qoshe ka një drejtkëndësh?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë na japin lopët?', category: 'general', difficulty: 'easy' },
  { question: 'Me çfarë nuhat?', category: 'general', difficulty: 'easy' },
  { question: 'Në cilën stinë bien gjethet?', category: 'general', difficulty: 'easy' },
  { question: 'Sa këmbë ka zakonisht një tryezë?', category: 'general', difficulty: 'easy' },
  { question: 'Sa bën 9 minus 4?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë bëjnë pulat?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë është e kundërta e ndritur?', category: 'general', difficulty: 'easy' },
  { question: 'Sa krahë ka një zog?', category: 'general', difficulty: 'easy' },
  { question: 'Me çfarë lahet dhëmbët?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë do të ishte më e keqja për të thënë në një dasmë?', category: 'funny', difficulty: 'easy' },
  { question: 'Çfarë është më e keqja për të rënë në publik?', category: 'funny', difficulty: 'easy' },
  { question: 'Cili do të ishte emër i tmerrshëm për dentist?', category: 'funny', difficulty: 'easy' },
  { question: 'Çfarë është më e qesharake për të mbledhur?', category: 'funny', difficulty: 'easy' },
  { question: 'Cila do të ishte superfuqia më e keqe në intervistë?', category: 'funny', difficulty: 'easy' },
  { question: 'A do të preferoje gishta ngjitës apo këmbë të djersitura përjetë?', category: 'general', difficulty: 'easy' },
  { question: 'A do të preferoje orë që shkon prapa apo që është gjithmonë gabim?', category: 'general', difficulty: 'easy' },
  { question: 'A do të mund të pëshpëriste vetëm apo të bërtiste vetëm?', category: 'general', difficulty: 'easy' },
  { question: 'A do të preferoje të mos kishe flokë apo kudo flokë?', category: 'general', difficulty: 'easy' },
  { question: 'A do të fliste me bimë apo me insekte?', category: 'general', difficulty: 'easy' },
  { question: 'Sa bën 6 herë 7?', category: 'random', difficulty: 'medium' },
  { question: 'Sa ditë ka shkurti në vit të brishtë?', category: 'random', difficulty: 'easy' },
  { question: 'Cili numër vjen pas 99?', category: 'random', difficulty: 'easy' },
  { question: 'Sa këmbë ka një karkalec?', category: 'random', difficulty: 'easy' },
  { question: 'Sa është 25 për qind e 200?', category: 'random', difficulty: 'medium' },
  { question: 'Cili është simboli kimik i hekurit?', category: 'science', difficulty: 'medium' },
  { question: 'Sa mushkori kemi?', category: 'science', difficulty: 'easy' },
  { question: 'Cili është organi më i madh i trupit njerëzor?', category: 'science', difficulty: 'medium' },
  { question: 'Cili planet ka unaza?', category: 'science', difficulty: 'easy' },
  { question: 'Në çfarë kthehen tërfilat?', category: 'science', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Anglisë?', category: 'geography', difficulty: 'easy' },
  { question: 'Cili det është Deti i Vdekur?', category: 'geography', difficulty: 'medium' },
  { question: 'Cila është kryeqyteti i Indisë?', category: 'geography', difficulty: 'easy' },
  { question: 'Cili kontinent ka më shumë vende?', category: 'geography', difficulty: 'medium' },
  { question: 'Cila është kryeqyteti i Koreës së Jugut?', category: 'geography', difficulty: 'easy' },
  { question: 'Nga cila arrë bëhet gjalpi i badërve?', category: 'food', difficulty: 'easy' },
  { question: 'Çfarë fruti jep pema e portokallit?', category: 'food', difficulty: 'easy' },
  { question: 'Cili është përbërësi kryesor i gjalpit?', category: 'food', difficulty: 'easy' },
  { question: 'Cila perime është vjollcë dhe e rrumbullakët?', category: 'food', difficulty: 'easy' },
  { question: 'Si quhet vakti në mes të ditës?', category: 'food', difficulty: 'easy' },
  { question: 'Sa lojtarë ka ekipi i voleybollit?', category: 'sports', difficulty: 'easy' },
  { question: 'Çfarë ngjyre ka topi i tenisit?', category: 'sports', difficulty: 'easy' },
  { question: 'Në cilin sport hipet kalë?', category: 'sports', difficulty: 'easy' },
  { question: 'Sa vrima ka fusha e golfit?', category: 'sports', difficulty: 'medium' },
  { question: 'Cili sport luhet në Super Bowl?', category: 'sports', difficulty: 'easy' },
  { question: 'Çfarë instrumenti luhet shpesh në xhaz?', category: 'music', difficulty: 'easy' },
  { question: 'Sa tela ka basi?', category: 'music', difficulty: 'easy' },
  { question: 'Si quhet grupi i katër këngëtarëve?', category: 'music', difficulty: 'medium' },
  { question: 'Cila bandë këndoi "Stairway to Heaven"?', category: 'music', difficulty: 'easy' },
  { question: 'Cila notë vjen pas sol në shkallë?', category: 'music', difficulty: 'medium' },
  { question: 'Në cilin film një djalë zbulon që është magjistar?', category: 'movies', difficulty: 'easy' },
  { question: 'Si quhet princesha në Frozen?', category: 'movies', difficulty: 'easy' },
  { question: 'Në cilin film ka personazh të quajtur Dory?', category: 'movies', difficulty: 'easy' },
  { question: 'Në cilin film makinat marrin jetë?', category: 'movies', difficulty: 'easy' },
  { question: 'Si quhet njeriu i borës në Frozen?', category: 'movies', difficulty: 'easy' },
  { question: 'Në cilin vit mbaroi Lufta e Dytë Botërore?', category: 'history', difficulty: 'easy' },
  { question: 'Kush ishte i pari që eci në hënë?', category: 'history', difficulty: 'easy' },
  { question: 'Cili perandori ndërtoi Koloseumin?', category: 'history', difficulty: 'easy' },
  { question: 'Në cilin vend filloi Rilindja?', category: 'history', difficulty: 'medium' },
  { question: 'Kush shkroi Deklaratën e Pavarësisë?', category: 'history', difficulty: 'easy' },
  { question: 'Cila mrekulli e lashtë ishte në Egjipt?', category: 'history', difficulty: 'easy' },
  { question: 'Kur ra Muri i Berlinit?', category: 'history', difficulty: 'medium' },
  { question: 'Kush shpiku llambën elektrike?', category: 'history', difficulty: 'easy' },
  { question: 'Cila civilizim ndërtoi Machu Picchu?', category: 'history', difficulty: 'medium' },
  { question: 'Në cilin shekull filloi Lufta e Parë Botërore?', category: 'history', difficulty: 'medium' },
  { question: 'Kush ishte presidenti i parë i SHBA?', category: 'history', difficulty: 'easy' },
  { question: 'Cili vend i dha SHBA Statujën e Lirisë?', category: 'history', difficulty: 'easy' },
  { question: 'Kush pikturoi Mona Lizën?', category: 'history', difficulty: 'easy' },
  { question: 'Kur zbritën njerëzit për herë të parë në hënë?', category: 'history', difficulty: 'easy' },
  { question: 'Cila perandori ndërtoi Murin e Madh?', category: 'history', difficulty: 'easy' },
  { question: 'Kush zbuloi Amerikën më 1492?', category: 'history', difficulty: 'easy' },
  { question: 'Çfarë nënkupton CPU?', category: 'technology', difficulty: 'easy' },
  { question: 'Kush themeloi Facebook?', category: 'technology', difficulty: 'easy' },
  { question: 'Në çfarë viti u lançua iPhone i parë?', category: 'technology', difficulty: 'medium' },
  { question: 'Çfarë nënkupton WiFi?', category: 'technology', difficulty: 'medium' },
  { question: 'Cila kompani bën PlayStation?', category: 'technology', difficulty: 'easy' },
  { question: 'Çfarë nënkupton USB?', category: 'technology', difficulty: 'medium' },
  { question: 'Kush krijoi Microsoft?', category: 'technology', difficulty: 'easy' },
  { question: 'Si quhet asistenti i Google?', category: 'technology', difficulty: 'easy' },
  { question: 'Sa bit ka një bajt?', category: 'technology', difficulty: 'medium' },
  { question: 'Çfarë nënkupton HTML?', category: 'technology', difficulty: 'easy' },
  { question: 'Cila kompani krijoi Android?', category: 'technology', difficulty: 'easy' },
  { question: 'Çfarë nënkupton GPS?', category: 'technology', difficulty: 'easy' },
  { question: 'Si quhet asistenti zanor i Amazon?', category: 'technology', difficulty: 'easy' },
  { question: 'Në çfarë viti u themelua YouTube?', category: 'technology', difficulty: 'medium' },
  { question: 'Çfarë nënkupton RAM?', category: 'technology', difficulty: 'medium' },
  { question: 'Cila kafshë është më e shpejta në tokë?', category: 'nature', difficulty: 'easy' },
  { question: 'Cili është gjitari më i madh në Tokë?', category: 'nature', difficulty: 'easy' },
  { question: 'Sa këmbë ka një insekt?', category: 'nature', difficulty: 'easy' },
  { question: 'Cili është i vetmi gjitar që mund të fluturojë?', category: 'nature', difficulty: 'easy' },
  { question: 'Cili planet njihet si Planeti i Kuq?', category: 'nature', difficulty: 'easy' },
  { question: 'Cili është ari më i madh?', category: 'nature', difficulty: 'easy' },
  { question: 'Sa stomake ka një lopë?', category: 'nature', difficulty: 'medium' },
  { question: 'Cila është pema më e lartë?', category: 'nature', difficulty: 'medium' },
  { question: 'Cila zog nuk mund të fluturojë?', category: 'nature', difficulty: 'easy' },
  { question: 'Cili është zogu më i vogël në botë?', category: 'nature', difficulty: 'medium' },
  { question: 'Sa krahë ka një oktapod?', category: 'nature', difficulty: 'easy' },
  { question: 'Cila është kafsha më e madhe oqeanore?', category: 'nature', difficulty: 'easy' },
  { question: 'Cila kafshë fle më shumë?', category: 'nature', difficulty: 'medium' },
  { question: 'Cili është i vetmi kontinent pa zvarranikë?', category: 'nature', difficulty: 'hard' },
  { question: 'Sa kocka ka në qafën e gjirafës?', category: 'nature', difficulty: 'medium' },
  { question: 'Cila është kryeqyteti i Francës?', category: 'travel', difficulty: 'easy' },
  { question: 'Cili vend ka më shumë ishuj?', category: 'travel', difficulty: 'medium' },
  { question: 'Cila është lumi më i gjatë në Evropë?', category: 'travel', difficulty: 'medium' },
  { question: 'Në cilin qytet ndodhet Akropoli?', category: 'travel', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Tajlandës?', category: 'travel', difficulty: 'easy' },
  { question: 'Në cilin vend ndodhet Taj Mahal?', category: 'travel', difficulty: 'easy' },
  { question: 'Cili është vendi më i vogël në botë?', category: 'travel', difficulty: 'easy' },
  { question: 'Në cilin qytet ndodhet Empire State Building?', category: 'travel', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Egjiptit?', category: 'travel', difficulty: 'easy' },
  { question: 'Në cilin kontinent ndodhet Shara?', category: 'travel', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Argjentinës?', category: 'travel', difficulty: 'easy' },
  { question: 'Në cilin vend ndodhet Great Barrier Reef?', category: 'travel', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Afrikës së Jugut?', category: 'travel', difficulty: 'easy' },
  { question: 'Cili qytet evropian ndahet nga Bosphorus?', category: 'travel', difficulty: 'medium' },
  { question: 'Cili është kryeqyteti më i lartë në botë?', category: 'travel', difficulty: 'hard' },
  { question: 'Cila është destinacioni yt i preferuar për pushime?', category: 'general', difficulty: 'easy' },
  { question: 'Cili është këshilli më i mirë që ke marrë?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë do të bëje nëse kishe një ditë të lirë?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë aftësie do të mësoje?', category: 'general', difficulty: 'easy' },
  { question: 'Si preferon të relaksohesh?', category: 'general', difficulty: 'easy' },
  { question: 'Cili ishte ëndrra më e çuditshme që ke patur?', category: 'funny', difficulty: 'medium' },
  { question: 'Cila do të ishte kënga më e keqe në një varrim?', category: 'funny', difficulty: 'easy' },
  { question: 'Çfarë është më e turpshme në dhomën tënde?', category: 'funny', difficulty: 'easy' },
  { question: 'Si do ta quaje një gur si kafshë shtëpiake?', category: 'funny', difficulty: 'easy' },
  { question: 'Cila ishte fraza më e keqe për të nisur një bisedë?', category: 'funny', difficulty: 'easy' },
  { question: 'Sa brinjë ka shenja e stopit?', category: 'random', difficulty: 'easy' },
  { question: 'Sa bën 11 herë 11?', category: 'random', difficulty: 'medium' },
  { question: 'Sa faqe ka një kub?', category: 'random', difficulty: 'easy' },
  { question: 'Cili është i vetmi numër prim çift?', category: 'random', difficulty: 'medium' },
  { question: 'Sa kocka ka dora e njeriut?', category: 'science', difficulty: 'medium' },
  { question: 'Cili është simboli kimik për natriumin?', category: 'science', difficulty: 'easy' },
  { question: 'Cili planet është më larg diellit?', category: 'science', difficulty: 'easy' },
  { question: 'Cila është kocka më e vogël në trupin e njeriut?', category: 'science', difficulty: 'hard' },
  { question: 'Çfarë gazi thithim më së shumti?', category: 'science', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Spanjës?', category: 'geography', difficulty: 'easy' },
  { question: 'Cili vend ka më shumë vullkane?', category: 'geography', difficulty: 'medium' },
  { question: 'Cila është kryeqyteti i Rusisë?', category: 'geography', difficulty: 'easy' },
  { question: 'Cili është përbërësi kryesor i çokollatës?', category: 'food', difficulty: 'easy' },
  { question: 'Cili frut përdoret për verë?', category: 'food', difficulty: 'easy' },
  { question: 'Cila është mishi më i konsumuar në botë?', category: 'food', difficulty: 'medium' },
  { question: 'Sa lojtarë ka një ekip kriketi?', category: 'sports', difficulty: 'medium' },
  { question: 'Në cilin sport bën home run?', category: 'sports', difficulty: 'easy' },
  { question: 'Cili instrument ka 88 taste?', category: 'music', difficulty: 'easy' },
  { question: 'Kush këndoi "Thriller"?', category: 'music', difficulty: 'easy' },
  { question: 'Në cilin film një adoleshent pickohet nga një merimangë?', category: 'movies', difficulty: 'easy' },
  { question: 'Si quhet shkolla e magjistarëve në Harry Potter?', category: 'movies', difficulty: 'easy' },
  { question: 'Cila është kujtimi yt i preferuar nga fëmijëria?', category: 'general', difficulty: 'easy' },
  { question: 'Me kë do të drekuaje nëse mund të zgjidhje?', category: 'general', difficulty: 'easy' },
  { question: 'Cili është libri më i mirë që ke lexuar?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë do të bëje nëse fitonje lotarinë?', category: 'general', difficulty: 'easy' },
  { question: 'Cila është stina jote e preferuar dhe pse?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë hobi do të provoje?', category: 'general', difficulty: 'easy' },
  { question: 'Cili është vendi më i bukur ku ke qenë?', category: 'general', difficulty: 'easy' },
  { question: 'Çfarë superfuqie do të zgjidhje?', category: 'general', difficulty: 'easy' },
  { question: 'Cila është kënga jote për karaoke?', category: 'general', difficulty: 'easy' },
  { question: 'Cila ishte prerja më e keqe e flokëve?', category: 'funny', difficulty: 'easy' },
  { question: 'Çfarë do të ishte më e keqja për të thënë në takimin e parë?', category: 'funny', difficulty: 'easy' },
  { question: 'Cili ishte gabimi më qesharak i autokorrektit?', category: 'funny', difficulty: 'easy' },
  { question: 'Si do ta quaje një parfum të tmerrshëm?', category: 'funny', difficulty: 'easy' },
  { question: 'Cila është trendi më absurd i modës?', category: 'funny', difficulty: 'easy' },
  { question: 'Si kafshë do të ishte më e keqja të ringjalleje?', category: 'funny', difficulty: 'easy' },
  { question: 'Çfarë gjëje më të qesharake ke blerë?', category: 'funny', difficulty: 'easy' },
  { question: 'Si do ta quaje një palestër të keqe?', category: 'funny', difficulty: 'easy' },
  { question: 'Cila është kombinimi më i keq i ushqimeve?', category: 'funny', difficulty: 'easy' },
  { question: 'Cila do të ishte puna më e keqe për një vampir?', category: 'funny', difficulty: 'easy' },
  { question: 'Sa gradë ka një kënd i drejtë?', category: 'random', difficulty: 'easy' },
  { question: 'Sa bën 9 herë 9?', category: 'random', difficulty: 'easy' },
  { question: 'Sa brinjë ka një pentagon?', category: 'random', difficulty: 'easy' },
  { question: 'Cila është rrënja katrore e 64?', category: 'random', difficulty: 'easy' },
  { question: 'Sa ditë ka një vit të brishtë?', category: 'random', difficulty: 'easy' },
  { question: 'Sa është 15 për qind e 100?', category: 'random', difficulty: 'easy' },
  { question: 'Sa kontinente fillojnë me shkronjën A?', category: 'random', difficulty: 'medium' },
  { question: 'Cili është i vetmi numër i njëjtë në anglisht dhe frëngjisht?', category: 'random', difficulty: 'hard' },
  { question: 'Sa taste ka një tastierë standarde?', category: 'random', difficulty: 'medium' },
  { question: 'Cili është numri prim më i madh nën 20?', category: 'random', difficulty: 'medium' },
  { question: 'Çfarë është "centri i energjisë" i qelizës?', category: 'science', difficulty: 'easy' },
  { question: 'Sa kocka ka kërcyeri i njeriut?', category: 'science', difficulty: 'medium' },
  { question: 'Cili është simboli kimik për karbonin?', category: 'science', difficulty: 'easy' },
  { question: 'Cili planet njihet për unazat?', category: 'science', difficulty: 'easy' },
  { question: 'Sa dhëmbë kanë zakonisht të rriturit?', category: 'science', difficulty: 'easy' },
  { question: 'Cili është planeti më i vogël në sistemin tonë diellor?', category: 'science', difficulty: 'easy' },
  { question: 'Çfarë gazi përbën pjesën më të madhe të atmosferës?', category: 'science', difficulty: 'easy' },
  { question: 'Sa dhomë ka zemra e njeriut?', category: 'science', difficulty: 'easy' },
  { question: 'Sa është shpejtësia e zërit?', category: 'science', difficulty: 'hard' },
  { question: 'Cili është simboli kimik për oksigjenin?', category: 'science', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Greqisë?', category: 'geography', difficulty: 'easy' },
  { question: 'Në cilin vend jetojnë kangurut?', category: 'geography', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Turqisë?', category: 'geography', difficulty: 'easy' },
  { question: 'Cili lumë kalon nëpër Paris?', category: 'geography', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Polonisë?', category: 'geography', difficulty: 'easy' },
  { question: 'Cili vend afrikan ka më shumë popullsi?', category: 'geography', difficulty: 'medium' },
  { question: 'Cila është kryeqyteti i Suedisë?', category: 'geography', difficulty: 'easy' },
  { question: 'Cili det është më i kripur?', category: 'geography', difficulty: 'medium' },
  { question: 'Cila është kryeqyteti i Holandës?', category: 'geography', difficulty: 'easy' },
  { question: 'Cila mal është më i larti në botë?', category: 'geography', difficulty: 'easy' },
  { question: 'Cili perime quhet mbreti i perimeve?', category: 'food', difficulty: 'medium' },
  { question: 'Cili është përbërësi kryesor i xhaçikut?', category: 'food', difficulty: 'easy' },
  { question: 'Çfarë arre përdoret në pesto?', category: 'food', difficulty: 'easy' },
  { question: 'Cili frut quhet mbreti i frutave?', category: 'food', difficulty: 'medium' },
  { question: 'Cili është përbërësi kryesor i falafelit?', category: 'food', difficulty: 'easy' },
  { question: 'Çfarë lloji djathi përdoret në sallatën greke?', category: 'food', difficulty: 'easy' },
  { question: 'Cili drithër përdoret për birrë?', category: 'food', difficulty: 'easy' },
  { question: 'Cili është përbërësi kryesor i guakamolës?', category: 'food', difficulty: 'easy' },
  { question: 'Cili frut thahet për të bërë kumbulla?', category: 'food', difficulty: 'easy' },
  { question: 'Cila është erëza më e shtrenjtë në botë?', category: 'food', difficulty: 'medium' },
  { question: 'Sa lojtarë ka një ekip rugby?', category: 'sports', difficulty: 'medium' },
  { question: 'Në cilin sport përdoret raketë dhe shuttlecock?', category: 'sports', difficulty: 'easy' },
  { question: 'Çfarë ngjyre ka topi në bilard?', category: 'sports', difficulty: 'easy' },
  { question: 'Sa turne Grand Slam ka tenisi në vit?', category: 'sports', difficulty: 'easy' },
  { question: 'Në cilin vend lindi basketbolli?', category: 'sports', difficulty: 'easy' },
  { question: 'Cili është sporti kombëtar i Kanadasë?', category: 'sports', difficulty: 'medium' },
  { question: 'Sa minuta ka një gjysmë futbolli?', category: 'sports', difficulty: 'easy' },
  { question: 'Në cilin sport bën "try"?', category: 'sports', difficulty: 'medium' },
  { question: 'Sa është diametri i unazës së basketbollit?', category: 'sports', difficulty: 'hard' },
  { question: 'Cili vend ka fituar më shumë Kupë Botërore?', category: 'sports', difficulty: 'easy' },
  { question: 'Cili instrument ka 88 taste?', category: 'music', difficulty: 'easy' },
  { question: 'Kush njihet si Mbreti i Popit?', category: 'music', difficulty: 'easy' },
  { question: 'Sa stringa ka harpa?', category: 'music', difficulty: 'hard' },
  { question: 'Cila është kënga më e kënduar në dasma?', category: 'music', difficulty: 'medium' },
  { question: 'Në cilin qytet lindi xhazi?', category: 'music', difficulty: 'medium' },
  { question: 'Cila bandë këndoi "Sweet Child O\' Mine"?', category: 'music', difficulty: 'easy' },
  { question: 'Sa anëtarë ka një trio?', category: 'music', difficulty: 'easy' },
  { question: 'Cila është zëri më i lartë mashkullor në këngë?', category: 'music', difficulty: 'easy' },
  { question: 'Kush shkroi Simfoninë e Nëntë?', category: 'music', difficulty: 'easy' },
  { question: 'Cili instrument njihet si mbreti i instrumenteve?', category: 'music', difficulty: 'medium' },
  { question: 'Në cilin film një djalë hipën mbi një drago?', category: 'movies', difficulty: 'easy' },
  { question: 'Si quhet dragoi në Game of Thrones?', category: 'movies', difficulty: 'medium' },
  { question: 'Në cilin film ka një rakun që flet?', category: 'movies', difficulty: 'easy' },
  { question: 'Në cilin film një robot bëhet njeri?', category: 'movies', difficulty: 'medium' },
  { question: 'Si quhet anija në Titanic?', category: 'movies', difficulty: 'easy' },
  { question: 'Cili studio bëri Shrek?', category: 'movies', difficulty: 'easy' },
  { question: 'Në cilin film një peshk clown kërkon të biri?', category: 'movies', difficulty: 'easy' },
  { question: 'Si quhet dinozauri në Jurassic Park?', category: 'movies', difficulty: 'easy' },
  { question: 'Në cilin film thuhet "May the Force be with you"?', category: 'movies', difficulty: 'easy' },
  { question: 'Në çfarë viti u mbyt Titanic?', category: 'movies', difficulty: 'medium' },
  { question: 'Kush ishte gruaja e parë që fitoi Çmimin Nobel?', category: 'history', difficulty: 'medium' },
  { question: 'Në çfarë viti filloi Revolucioni Francez?', category: 'history', difficulty: 'medium' },
  { question: 'Kush ndërtoi shtypin e parë?', category: 'history', difficulty: 'medium' },
  { question: 'Cila perandori u sundua nga Gengis Kan?', category: 'history', difficulty: 'easy' },
  { question: 'Kur ra Perandoria Romake?', category: 'history', difficulty: 'hard' },
  { question: 'Kush ishte kryeministri britanik gjatë Luftës së Dytë Botërore?', category: 'history', difficulty: 'easy' },
  { question: 'Cili vend shpiku letrën?', category: 'history', difficulty: 'medium' },
  { question: 'Kush shkroi Odisean?', category: 'history', difficulty: 'easy' },
  { question: 'Në çfarë viti fluturoi për herë të parë njeriu me aeroplan?', category: 'history', difficulty: 'medium' },
  { question: 'Kush zbuloi penicilinin?', category: 'history', difficulty: 'medium' },
  { question: 'Çfarë nënkupton AI?', category: 'technology', difficulty: 'easy' },
  { question: 'Kush themeloi Tesla?', category: 'technology', difficulty: 'easy' },
  { question: 'Në çfarë viti u krijua virusi i parë kompjuterik?', category: 'technology', difficulty: 'hard' },
  { question: 'Çfarë nënkupton VPN?', category: 'technology', difficulty: 'medium' },
  { question: 'Cila kompani bën Switch?', category: 'technology', difficulty: 'easy' },
  { question: 'Çfarë nënkupton SSD?', category: 'technology', difficulty: 'medium' },
  { question: 'Kush krijoi Linux?', category: 'technology', difficulty: 'hard' },
  { question: 'Si quhet asistenti zanor i Apple?', category: 'technology', difficulty: 'easy' },
  { question: 'Në çfarë viti u dërgua emaili i parë?', category: 'technology', difficulty: 'hard' },
  { question: 'Çfarë nënkupton HTTP?', category: 'technology', difficulty: 'medium' },
  { question: 'Cila kafshë mund të jetojë më gjatë?', category: 'nature', difficulty: 'medium' },
  { question: 'Cili është i vetmi gjitar që vendos vezë?', category: 'nature', difficulty: 'easy' },
  { question: 'Sa sy ka një bletë?', category: 'nature', difficulty: 'medium' },
  { question: 'Cili është zogu më i shpejtë?', category: 'nature', difficulty: 'medium' },
  { question: 'Cila kafshë bën migrimin më të gjatë?', category: 'nature', difficulty: 'hard' },
  { question: 'Cila është kafsha më e madhe tokësore?', category: 'nature', difficulty: 'easy' },
  { question: 'Sa stomake ka një dhi?', category: 'nature', difficulty: 'medium' },
  { question: 'Cili është i vetmi zog që mund të fluturojë prapa?', category: 'nature', difficulty: 'medium' },
  { question: 'Cili insekt është më i fortë në raport me madhësinë?', category: 'nature', difficulty: 'hard' },
  { question: 'Cila është kafsha më e zhurmshme në Tokë?', category: 'nature', difficulty: 'hard' },
  { question: 'Cila është kryeqyteti i Portugalisë?', category: 'travel', difficulty: 'easy' },
  { question: 'Cili vend ka më shumë vende të trashëgimisë botërore UNESCO?', category: 'travel', difficulty: 'hard' },
  { question: 'Cila është kryeqyteti i Norvegjisë?', category: 'travel', difficulty: 'easy' },
  { question: 'Në cilin qytet ndodhet Partenoni?', category: 'travel', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Zvicrës?', category: 'travel', difficulty: 'easy' },
  { question: 'Në cilin vend ndodhet Muri i Madh?', category: 'travel', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Irlandës?', category: 'travel', difficulty: 'easy' },
  { question: 'Në cilin qytet ndodhet Big Ben?', category: 'travel', difficulty: 'easy' },
  { question: 'Cila është kryeqyteti i Austrisë?', category: 'travel', difficulty: 'easy' },
  { question: 'Cili vend ka më shumë liqene?', category: 'travel', difficulty: 'hard' },
];
