module.exports = [
  { question: 'Gökyüzü ne renktir?', category: 'general', difficulty: 'easy' },
  { question: 'Bir köpeğin kaç ayağı vardır?', category: 'general', difficulty: 'easy' },
  { question: '2 + 2 kaç eder?', category: 'general', difficulty: 'easy' },
  { question: 'Fransa\'nın başkenti neresidir?', category: 'general', difficulty: 'easy' },
  { question: 'Hangi hayvan "mö" der?', category: 'general', difficulty: 'easy' },
  { question: 'Bir haftada kaç gün vardır?', category: 'general', difficulty: 'easy' },
  { question: 'Topun şekli nedir?', category: 'general', difficulty: 'easy' },
  { question: 'Kağıda ne ile yazılır?', category: 'general', difficulty: 'easy' },
  { question: 'Sıcakın zıttı nedir?', category: 'general', difficulty: 'easy' },
  { question: 'Bir elde kaç parmak vardır?', category: 'general', difficulty: 'easy' },
  { question: 'Hangi gezegende yaşıyoruz?', category: 'general', difficulty: 'easy' },
  { question: 'Çim ne renktir?', category: 'general', difficulty: 'easy' },
  { question: 'En büyük okyanus hangisidir?', category: 'general', difficulty: 'medium' },
  { question: 'Kaç kıta vardır?', category: 'general', difficulty: 'easy' },
  { question: 'İspanya\'da hangi dil konuşulur?', category: 'general', difficulty: 'easy' },
  { question: 'Yazdan sonra hangi mevsim gelir?', category: 'general', difficulty: 'easy' },
  { question: 'Bir günde kaç saat vardır?', category: 'general', difficulty: 'easy' },
  { question: 'En uzun hayvan hangisidir?', category: 'general', difficulty: 'easy' },
  { question: 'Arılar ne yapar?', category: 'general', difficulty: 'easy' },
  { question: '10 eksi 3 kaç eder?', category: 'general', difficulty: 'easy' },
  { question: 'Yukarının zıttı nedir?', category: 'general', difficulty: 'easy' },
  { question: 'Bir arabanın kaç tekerleği vardır?', category: 'general', difficulty: 'easy' },
  { question: 'Yavru kediye ne denir?', category: 'general', difficulty: 'easy' },
  { question: 'Hangi meyve sarı ve kıvrıktır?', category: 'general', difficulty: 'easy' },
  { question: 'Ayaklara ne giyilir?', category: 'general', difficulty: 'easy' },
  { question: 'Şimdiye kadar gördüğün en komik şey ne?', category: 'funny', difficulty: 'medium' },
  { question: 'Bir evcil hayvan için en kötü isim ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'Aklına gelen en saçma süper güç ne?', category: 'funny', difficulty: 'easy' },
  { question: 'Sadece bir yemek yiyebilseydin sonsuza kadar, ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'Birine verebileceğin en kötü tavsiye ne olurdu?', category: 'funny', difficulty: 'medium' },
  { question: 'Teknene ne isim verirdin?', category: 'funny', difficulty: 'easy' },
  { question: 'Alabileceğin en kötü hediye ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'Reenkarnasyonla hangi hayvana dönmek en kötü olurdu?', category: 'funny', difficulty: 'medium' },
  { question: 'Hayal edebileceğin en sıkıcı şey ne?', category: 'funny', difficulty: 'easy' },
  { question: 'Bir restoran için korkunç bir isim ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'En kötü süper güç ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'En kötü sebze hangisi?', category: 'funny', difficulty: 'easy' },
  { question: 'Bir grup için kötü bir isim ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'Yolculukta unutulacak en kötü şey ne?', category: 'funny', difficulty: 'easy' },
  { question: 'Ayak yerine el mi yoksa el yerine ayak mı olsun isterdin?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Her zaman 10 dakika geç mi kalsan yoksa 20 dakika erken mi gelsin isterdin?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Telefonun mu olmasın yoksa televizyonun mu?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Sadece tatlı mı yoksa sadece tuzlu mu yesen?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Geçmişte mi yoksa gelecekte mi yaşardın?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Uçabilsen mi yoksa görünmez olsan mı isterdin?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Tüm yıl yaz mı yoksa kış mı olsun isterdin?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Kedi mi yoksa köpek mi olsun isterdin?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Asla sosyal medya mı kullanmasan yoksa asla film mi izlemesen?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Tüm dilleri mi konuşabilsen yoksa hayvanlarla mı konuşabilsen?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Sınırsız pizza mı yoksa sınırsız suşi mi isterdin?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Işınlanabilsen mi yoksa zamanda yolculuk mu yapabilsen?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Sesini mi yoksa işitmeni mi kaybetsen?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Minik bir fil mi yoksa dev bir hamster mı olsun isterdin?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Bugün günlerden ne?', category: 'random', difficulty: 'easy' },
  { question: 'Hangi aydayız?', category: 'random', difficulty: 'easy' },
  { question: 'Alfabedeki ilk harf hangisi?', category: 'random', difficulty: 'easy' },
  { question: 'Bir üçgenin kaç kenarı vardır?', category: 'random', difficulty: 'easy' },
  { question: 'Gündüzün zıttı ne?', category: 'random', difficulty: 'easy' },
  { question: 'Yavru köpeğe ne denir?', category: 'random', difficulty: 'easy' },
  { question: 'En hızlı kara hayvanı hangisi?', category: 'random', difficulty: 'medium' },
  { question: 'Bir örümceğin kaç ayağı vardır?', category: 'random', difficulty: 'easy' },
  { question: 'En küçük kıta hangisi?', category: 'random', difficulty: 'medium' },
  { question: '100 bölü 10 kaç eder?', category: 'random', difficulty: 'easy' },
  { question: 'Bir yılda kaç ay vardır?', category: 'random', difficulty: 'easy' },
  { question: '5 kere 5 kaç eder?', category: 'random', difficulty: 'easy' },
  { question: 'Gökkuşağında kaç renk vardır?', category: 'random', difficulty: 'easy' },
  { question: 'Güneş sistemimizdeki en büyük gezegen hangisi?', category: 'science', difficulty: 'easy' },
  { question: 'Yetişkin bir insanın kaç kemiği vardır?', category: 'science', difficulty: 'medium' },
  { question: 'Suyun kimyasal sembolü nedir?', category: 'science', difficulty: 'easy' },
  { question: 'Bizi yerde tutan kuvvet nedir?', category: 'science', difficulty: 'easy' },
  { question: 'Bitkiler havadan hangi gazı alır?', category: 'science', difficulty: 'easy' },
  { question: 'Yetişkinin genelde kaç dişi vardır?', category: 'science', difficulty: 'medium' },
  { question: 'Su Celsius\'ta kaç derecede kaynar?', category: 'science', difficulty: 'easy' },
  { question: 'Hangi gezegene Kızıl Gezegen denir?', category: 'science', difficulty: 'easy' },
  { question: 'Işık hızı nedir?', category: 'science', difficulty: 'hard' },
  { question: 'Bir ahtapotun kaç kalbi vardır?', category: 'science', difficulty: 'medium' },
  { question: 'Japonya\'nın başkenti neresidir?', category: 'geography', difficulty: 'easy' },
  { question: 'Dünyanın en uzun nehri hangisi?', category: 'geography', difficulty: 'medium' },
  { question: 'Yüzölçümü en büyük ülke hangisi?', category: 'geography', difficulty: 'easy' },
  { question: 'Mısır hangi kıtadadır?', category: 'geography', difficulty: 'easy' },
  { question: 'Avustralya\'nın başkenti neresidir?', category: 'geography', difficulty: 'easy' },
  { question: 'Hangi okyanus en soğuktur?', category: 'geography', difficulty: 'medium' },
  { question: 'Dünyanın en küçük ülkesi hangisi?', category: 'geography', difficulty: 'medium' },
  { question: 'Hangi ülkenin nüfusu en fazla?', category: 'geography', difficulty: 'easy' },
  { question: 'Brezilya\'nın başkenti neresidir?', category: 'geography', difficulty: 'easy' },
  { question: 'Eyfel Kulesi hangi ülkededir?', category: 'geography', difficulty: 'easy' },
  { question: 'Kuru üzüm hangi meyveden yapılır?', category: 'food', difficulty: 'easy' },
  { question: 'Havuç ne renktir?', category: 'food', difficulty: 'easy' },
  { question: 'Su donunca ne olur?', category: 'food', difficulty: 'easy' },
  { question: 'Ekmekte ana malzeme nedir?', category: 'food', difficulty: 'easy' },
  { question: 'Pizza hangi ülkeden çıkmıştır?', category: 'food', difficulty: 'easy' },
  { question: 'Olgun bir muz ne renktir?', category: 'food', difficulty: 'easy' },
  { question: 'Turşu hangi sebzeden yapılır?', category: 'food', difficulty: 'easy' },
  { question: 'Balı kim yapar?', category: 'food', difficulty: 'easy' },
  { question: 'Suşi ne tür bir yemektir?', category: 'food', difficulty: 'easy' },
  { question: 'Dışı kırmızı ve dışında çekirdekleri olan meyve hangisi?', category: 'food', difficulty: 'easy' },
  { question: 'Bir futbol takımında kaç oyuncu vardır?', category: 'sports', difficulty: 'easy' },
  { question: 'Olimpiyat bayrağındaki ortadaki halka ne renktir?', category: 'sports', difficulty: 'medium' },
  { question: 'Touchdown hangi sporda atılır?', category: 'sports', difficulty: 'easy' },
  { question: 'Teniste kaç Grand Slam turnuvası vardır?', category: 'sports', difficulty: 'medium' },
  { question: 'Basketbol topunun şekli nedir?', category: 'sports', difficulty: 'easy' },
  { question: 'Puck hangi sporda kullanılır?', category: 'sports', difficulty: 'easy' },
  { question: 'Indy 500 kaç turdur?', category: 'sports', difficulty: 'medium' },
  { question: 'Golf hangi ülkede icat edildi?', category: 'sports', difficulty: 'medium' },
  { question: 'Basketbol takımında kaç oyuncu vardır?', category: 'sports', difficulty: 'easy' },
  { question: 'Wimbledon\'da hangi oyun oynanır?', category: 'sports', difficulty: 'easy' },
  { question: 'Standart bir gitarın kaç teli vardır?', category: 'music', difficulty: 'easy' },
  { question: 'Siyah ve beyaz tuşları olan enstrüman hangisi?', category: 'music', difficulty: 'easy' },
  { question: 'Vals kaç tempoludur?', category: 'music', difficulty: 'medium' },
  { question: 'Orkestradaki en büyük enstrüman hangisi?', category: 'music', difficulty: 'easy' },
  { question: '"Yellow Submarine"ı hangi grup söyledi?', category: 'music', difficulty: 'easy' },
  { question: 'Bir oktavda kaç nota vardır?', category: 'music', difficulty: 'medium' },
  { question: 'Davulcu hangi enstrümanı çalar?', category: 'music', difficulty: 'easy' },
  { question: 'Opera hangi ülkede doğdu?', category: 'music', difficulty: 'medium' },
  { question: 'En tiz şarkı sesi hangisi?', category: 'music', difficulty: 'easy' },
  { question: 'Bir kemanın kaç teli vardır?', category: 'music', difficulty: 'easy' },
  { question: 'Hangi filmde bir aslan kral olur?', category: 'movies', difficulty: 'easy' },
  { question: 'Oz Büyücüsü\'ndeki büyücünün adı ne?', category: 'movies', difficulty: 'easy' },
  { question: 'Frozen\'ı hangi stüdyo yaptı?', category: 'movies', difficulty: 'easy' },
  { question: 'Ratatouille\'de Remy ne hayvan?', category: 'movies', difficulty: 'easy' },
  { question: 'Hangi filmde bir çocuk lambada cin bulur?', category: 'movies', difficulty: 'easy' },
  { question: 'Kayıp Balık Nemo\'daki balığın adı ne?', category: 'movies', difficulty: 'easy' },
  { question: 'Simba adlı karakter hangi filmde var?', category: 'movies', difficulty: 'easy' },
  { question: 'Külkedisi\'nin elbisesi ne renktir?', category: 'movies', difficulty: 'easy' },
  { question: 'Hangi filmde oyuncaklar canlanır?', category: 'movies', difficulty: 'easy' },
  { question: 'Dumbo ne hayvan?', category: 'movies', difficulty: 'easy' },
  { question: '3 kere 4 kaç eder?', category: 'general', difficulty: 'easy' },
  { question: 'Bir insanın kaç gözü vardır?', category: 'general', difficulty: 'easy' },
  { question: 'Güneş nedir?', category: 'general', difficulty: 'easy' },
  { question: 'Kuşlar neyle uçar?', category: 'general', difficulty: 'easy' },
  { question: 'Kar neyden yapılır?', category: 'general', difficulty: 'easy' },
  { question: 'Bir saatte kaç dakika vardır?', category: 'general', difficulty: 'easy' },
  { question: 'Büyüğün zıttı ne?', category: 'general', difficulty: 'easy' },
  { question: 'Ne ile görürsün?', category: 'general', difficulty: 'easy' },
  { question: 'Uzun hortumu olan hayvan hangisi?', category: 'general', difficulty: 'easy' },
  { question: 'Güneş ne renktir?', category: 'general', difficulty: 'easy' },
  { question: 'Bir karenin kaç kenarı vardır?', category: 'general', difficulty: 'easy' },
  { question: 'Balıklar ne solur?', category: 'general', difficulty: 'easy' },
  { question: 'Yağmur yağınca gökten ne düşer?', category: 'general', difficulty: 'easy' },
  { question: '15 artı 15 kaç eder?', category: 'general', difficulty: 'easy' },
  { question: 'Bebek koyuna ne denir?', category: 'general', difficulty: 'easy' },
  { question: 'Bir sandalyenin kaç ayağı vardır?', category: 'general', difficulty: 'easy' },
  { question: 'Hızlının zıttı ne?', category: 'general', difficulty: 'easy' },
  { question: 'Kitapta ne okursun?', category: 'general', difficulty: 'easy' },
  { question: 'En çok kar hangi mevsimde?', category: 'general', difficulty: 'easy' },
  { question: 'En kötü iş unvanı ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'En gereksiz icat ne?', category: 'funny', difficulty: 'easy' },
  { question: 'Bir sabun için kötü isim ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'En kötü dondurma aroması hangisi?', category: 'funny', difficulty: 'easy' },
  { question: 'Berbat bir şifre ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'En saçma seyahat yolu ne?', category: 'funny', difficulty: 'easy' },
  { question: 'Neye alerji olmak en kötü olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'Unutulacak en utanç verici şey ne?', category: 'funny', difficulty: 'easy' },
  { question: 'Bir hastane için kötü isim ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'Partide en kötü süper güç hangisi?', category: 'funny', difficulty: 'easy' },
  { question: 'Tat alamamak mı koku alamamak mı tercih edersin?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'At büyüklüğünde bir ördek mi yoksa 100 ördek büyüklüğünde at mı ile savaşırdın?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Hayatta geri sarma mı duraklatma butonu mu isterdin?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Hep şarkı mı söylesen hep fısıldasan mı?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Kaşın mı kirpiğin mi olmasın?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Ünlü mü zengin mi olmak isterdin?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Kuyruk mu boynuz mu olsun isterdin?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Müziksiz mi filmsiz mi yaşardın?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Kişisel şef mi kişisel pilot mu isterdin?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Ne zaman mı nasıl öleceğini mi bilmek isterdin?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '7 kere 8 kaç eder?', category: 'random', difficulty: 'medium' },
  { question: 'Binde kaç sıfır var?', category: 'random', difficulty: 'easy' },
  { question: 'Alfabenin son harfi ne?', category: 'random', difficulty: 'easy' },
  { question: 'Altıgenin kaç kenarı var?', category: 'random', difficulty: 'easy' },
  { question: '100\'ün yüzde 50\'si kaç?', category: 'random', difficulty: 'easy' },
  { question: 'Bir dakikada kaç saniye var?', category: 'random', difficulty: 'easy' },
  { question: 'Su Celsius\'ta kaç derecede donar?', category: 'random', difficulty: 'easy' },
  { question: 'ABD bayrağında kaç şerit var?', category: 'random', difficulty: 'medium' },
  { question: '12 kere 12 kaç eder?', category: 'random', difficulty: 'medium' },
  { question: 'Bir böceğin kaç bacağı var?', category: 'random', difficulty: 'easy' },
  { question: 'Altının kimyasal sembolü ne?', category: 'science', difficulty: 'easy' },
  { question: 'Güneş sistemimizde kaç gezegen var?', category: 'science', difficulty: 'easy' },
  { question: 'Kanı hangi organ pompalar?', category: 'science', difficulty: 'easy' },
  { question: 'H2O nedir?', category: 'science', difficulty: 'easy' },
  { question: 'İnsanlar hangi gazı verir?', category: 'science', difficulty: 'easy' },
  { question: 'Bir kelebeğin kaç kanadı var?', category: 'science', difficulty: 'easy' },
  { question: 'Dünyaya en yakın yıldız hangisi?', category: 'science', difficulty: 'easy' },
  { question: 'En sert doğal madde ne?', category: 'science', difficulty: 'medium' },
  { question: 'İnsanın kaç kromozomu var?', category: 'science', difficulty: 'hard' },
  { question: 'Güneşe en yakın gezegen hangisi?', category: 'science', difficulty: 'easy' },
  { question: 'Almanya\'nın başkenti neresi?', category: 'geography', difficulty: 'easy' },
  { question: 'Piramitler hangi ülkede?', category: 'geography', difficulty: 'easy' },
  { question: 'İtalya\'nın başkenti neresi?', category: 'geography', difficulty: 'easy' },
  { question: 'Amerika ile Avrupa arasında hangi okyanus var?', category: 'geography', difficulty: 'easy' },
  { question: 'Kanada\'nın başkenti neresi?', category: 'geography', difficulty: 'easy' },
  { question: 'Pisa Kulesi hangi ülkede?', category: 'geography', difficulty: 'easy' },
  { question: 'En uzun dağ sırası hangisi?', category: 'geography', difficulty: 'medium' },
  { question: 'Çin Seddi hangi ülkede?', category: 'geography', difficulty: 'easy' },
  { question: 'Meksika\'nın başkenti neresi?', category: 'geography', difficulty: 'easy' },
  { question: 'Özgürlük Heykeli hangi ülkede?', category: 'geography', difficulty: 'easy' },
  { question: 'Patates kızartması hangi sebzeden yapılır?', category: 'food', difficulty: 'easy' },
  { question: 'Elma ne renktir?', category: 'food', difficulty: 'easy' },
  { question: 'Tost makinesine ne konur?', category: 'food', difficulty: 'easy' },
  { question: 'Humusun ana malzemesi ne?', category: 'food', difficulty: 'easy' },
  { question: 'Dışı yeşil içi kırmızı meyve hangisi?', category: 'food', difficulty: 'easy' },
  { question: 'Çayı tatlandırmak için ne eklenir?', category: 'food', difficulty: 'easy' },
  { question: 'Ketçap neyden yapılır?', category: 'food', difficulty: 'easy' },
  { question: 'Süt ne renktir?', category: 'food', difficulty: 'easy' },
  { question: 'Pilav hangi tahıldan?', category: 'food', difficulty: 'easy' },
  { question: 'Guacamole\'nin ana malzemesi ne?', category: 'food', difficulty: 'easy' },
  { question: 'Touchdown kaç puan değer?', category: 'sports', difficulty: 'easy' },
  { question: 'Tüytop hangi sporda kullanılır?', category: 'sports', difficulty: 'easy' },
  { question: 'Bir beyzbol takımında kaç oyuncu var?', category: 'sports', difficulty: 'medium' },
  { question: 'Tour de France lideri hangi renk forması giyer?', category: 'sports', difficulty: 'medium' },
  { question: 'Bowling hangi sporda yapılır?', category: 'sports', difficulty: 'easy' },
  { question: 'Serena Williams kaç Grand Slam kazandı?', category: 'sports', difficulty: 'hard' },
  { question: 'Amerikan futbol topu ne şekilde?', category: 'sports', difficulty: 'easy' },
  { question: 'Maraton koşusu hangi ülkede başladı?', category: 'sports', difficulty: 'medium' },
  { question: 'Olimpiyat bayrağında kaç halka var?', category: 'sports', difficulty: 'easy' },
  { question: 'File ve top hangi sporda kullanılır?', category: 'sports', difficulty: 'easy' },
  { question: 'Standart piyanoda kaç tuş var?', category: 'music', difficulty: 'medium' },
  { question: 'Elvis hangi enstrümanı çalardı?', category: 'music', difficulty: 'easy' },
  { question: 'Ukulele\'de kaç tel var?', category: 'music', difficulty: 'easy' },
  { question: 'En kalın şan sesi hangisi?', category: 'music', difficulty: 'easy' },
  { question: 'Opera binası hangi şehirde ünlü?', category: 'music', difficulty: 'medium' },
  { question: '"Bohemian Rhapsody" hangi grubun?', category: 'music', difficulty: 'easy' },
  { question: 'Dörtlüde kaç üye var?', category: 'music', difficulty: 'easy' },
  { question: 'Sürgüsü olan enstrüman hangisi?', category: 'music', difficulty: 'easy' },
  { question: 'Beethoven hangi tür?', category: 'music', difficulty: 'easy' },
  { question: 'Beatles kaç albüm çıkardı?', category: 'music', difficulty: 'hard' },
  { question: 'Hangi filmde bir çocuk büyücü okuluna gider?', category: 'movies', difficulty: 'easy' },
  { question: 'Jaws\'taki köpekbalığının adı ne?', category: 'movies', difficulty: 'easy' },
  { question: '"I will find you" hangi filmde geçer?', category: 'movies', difficulty: 'medium' },
  { question: 'Shrek\'teki Eşek ne hayvan?', category: 'movies', difficulty: 'easy' },
  { question: 'Hangi filmde bir robot "I\'ll be back" der?', category: 'movies', difficulty: 'easy' },
  { question: 'Ejderhanı Nasıl Eğitirsin\'deki ejderhanın adı ne?', category: 'movies', difficulty: 'easy' },
  { question: 'Toy Story\'yi hangi stüdyo yaptı?', category: 'movies', difficulty: 'easy' },
  { question: 'Aslan Kral\'daki aslanın adı ne?', category: 'movies', difficulty: 'easy' },
  { question: 'Hangi filmde bir kızın uzun sihirli saçları var?', category: 'movies', difficulty: 'easy' },
  { question: 'Geleceğe Dönüş\'te Doc ne aracı kullanır?', category: 'movies', difficulty: 'easy' },
  { question: '20 artı 30 kaç eder?', category: 'general', difficulty: 'easy' },
  { question: 'Bir insanın kaç burnu var?', category: 'general', difficulty: 'easy' },
  { question: 'Ne ile duyarsın?', category: 'general', difficulty: 'easy' },
  { question: 'Islağın zıttı ne?', category: 'general', difficulty: 'easy' },
  { question: 'Dikdörtgenin kaç köşesi var?', category: 'general', difficulty: 'easy' },
  { question: 'İnekler bize ne verir?', category: 'general', difficulty: 'easy' },
  { question: 'Ne ile koku alırsın?', category: 'general', difficulty: 'easy' },
  { question: 'Yapraklar hangi mevsimde düşer?', category: 'general', difficulty: 'easy' },
  { question: 'Bir masanın genelde kaç ayağı var?', category: 'general', difficulty: 'easy' },
  { question: '9 eksi 4 kaç eder?', category: 'general', difficulty: 'easy' },
  { question: 'Tavuklar ne yumurtlar?', category: 'general', difficulty: 'easy' },
  { question: 'Aydınlığın zıttı ne?', category: 'general', difficulty: 'easy' },
  { question: 'Bir kuşun kaç kanadı var?', category: 'general', difficulty: 'easy' },
  { question: 'Dişlerini neyle fırçalarsın?', category: 'general', difficulty: 'easy' },
  { question: 'Düğünde söylenecek en kötü şey ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'Toplumda düşürülecek en kötü şey ne?', category: 'funny', difficulty: 'easy' },
  { question: 'Bir dişçi için berbat isim ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'Koleksiyonu yapılacak en saçma şey ne?', category: 'funny', difficulty: 'easy' },
  { question: 'Mülakatta en kötü süper güç hangisi?', category: 'funny', difficulty: 'easy' },
  { question: 'Sonsuza kadar yapışkan parmak mı terli ayak mı?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Geri giden saat mi hep yanlış gösteren saat mi?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Sadece fısıldayabilsen mi sadece bağırabilsen mi?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Hiç saçın mı olmasın her yerde saç mı olsun?', category: 'would_you_rather', difficulty: 'easy' },
  { question: 'Bitkilerle mi böceklerle mi konuşabilsen?', category: 'would_you_rather', difficulty: 'easy' },
  { question: '6 kere 7 kaç eder?', category: 'random', difficulty: 'medium' },
  { question: 'Artık yılda şubat kaç gün?', category: 'random', difficulty: 'easy' },
  { question: '99\'dan sonra hangi sayı gelir?', category: 'random', difficulty: 'easy' },
  { question: 'Bir yengecin kaç bacağı var?', category: 'random', difficulty: 'easy' },
  { question: '200\'ün yüzde 25\'i kaç?', category: 'random', difficulty: 'medium' },
  { question: 'Demirin kimyasal sembolü ne?', category: 'science', difficulty: 'medium' },
  { question: 'İnsanın kaç akciğeri var?', category: 'science', difficulty: 'easy' },
  { question: 'İnsan vücudunun en büyük organı hangisi?', category: 'science', difficulty: 'medium' },
  { question: 'Hangi gezegenin halkaları var?', category: 'science', difficulty: 'easy' },
  { question: 'Tırtıllar neye dönüşür?', category: 'science', difficulty: 'easy' },
  { question: 'İngiltere\'nin başkenti neresi?', category: 'geography', difficulty: 'easy' },
  { question: 'Ölü Deniz hangi deniz?', category: 'geography', difficulty: 'medium' },
  { question: 'Hindistan\'ın başkenti neresi?', category: 'geography', difficulty: 'easy' },
  { question: 'En çok ülkesi olan kıta hangisi?', category: 'geography', difficulty: 'medium' },
  { question: 'Güney Kore\'nin başkenti neresi?', category: 'geography', difficulty: 'easy' },
  { question: 'Fıstık ezmesi hangi yemişten yapılır?', category: 'food', difficulty: 'easy' },
  { question: 'Portakal ağacından hangi meyve çıkar?', category: 'food', difficulty: 'easy' },
  { question: 'Tereyağının ana malzemesi ne?', category: 'food', difficulty: 'easy' },
  { question: 'Mor ve yuvarlak sebze hangisi?', category: 'food', difficulty: 'easy' },
  { question: 'Gün ortası yemeğine ne denir?', category: 'food', difficulty: 'easy' },
  { question: 'Voleybol takımında kaç oyuncu var?', category: 'sports', difficulty: 'easy' },
  { question: 'Tenis topu ne renktir?', category: 'sports', difficulty: 'easy' },
  { question: 'Hangi sporda ata binilir?', category: 'sports', difficulty: 'easy' },
  { question: 'Golf sahasında kaç delik var?', category: 'sports', difficulty: 'medium' },
  { question: 'Super Bowl\'da hangi spor oynanır?', category: 'sports', difficulty: 'easy' },
  { question: 'Cazda genelde hangi enstrüman çalınır?', category: 'music', difficulty: 'easy' },
  { question: 'Bas gitarında kaç tel var?', category: 'music', difficulty: 'easy' },
  { question: 'Dört şarkıcıdan oluşan gruba ne denir?', category: 'music', difficulty: 'medium' },
  { question: '"Stairway to Heaven" hangi grubun?', category: 'music', difficulty: 'easy' },
  { question: 'Gamda sol\'dan sonra hangi nota gelir?', category: 'music', difficulty: 'medium' },
  { question: 'Hangi filmde bir çocuk büyücü olduğunu keşfeder?', category: 'movies', difficulty: 'easy' },
  { question: 'Karlar Ülkesi\'ndeki prensesin adı ne?', category: 'movies', difficulty: 'easy' },
  { question: 'Dory adlı karakter hangi filmde?', category: 'movies', difficulty: 'easy' },
  { question: 'Hangi filmde arabalar canlanır?', category: 'movies', difficulty: 'easy' },
  { question: 'Karlar Ülkesi\'ndeki kardan adamın adı ne?', category: 'movies', difficulty: 'easy' },
];
