module.exports = [
  { question: 'Gökyüzü ne renktir?', category: 'general', difficulty: 'easy' },
  { question: 'Bir köpeğin kaç ayağı vardır?', category: 'general', difficulty: 'easy' },
  { question: '2 + 2 kaç eder?', category: 'general', difficulty: 'easy' },
  { question: 'Fransa\'nın başkenti neresidir?', category: 'general', difficulty: 'easy' },
  { question: 'Hangi hayvan "mö" der?', category: 'general', difficulty: 'easy' },
  { question: 'Bir haftada kaç gün vardır?', category: 'general', difficulty: 'easy' },
  { question: 'Topun şekli nedir?', category: 'general', difficulty: 'easy' },
  { question: 'Kağıda ne ile yazılır?', category: 'general', difficulty: 'easy' },
  { question: 'Sıcakın zıttı nedir?', category: 'general', difficulty: 'easy' },
  { question: 'Bir elde kaç parmak vardır?', category: 'general', difficulty: 'easy' },
  { question: 'Hangi gezegende yaşıyoruz?', category: 'general', difficulty: 'easy' },
  { question: 'Çim ne renktir?', category: 'general', difficulty: 'easy' },
  { question: 'En büyük okyanus hangisidir?', category: 'general', difficulty: 'medium' },
  { question: 'Kaç kıta vardır?', category: 'general', difficulty: 'easy' },
  { question: 'İspanya\'da hangi dil konuşulur?', category: 'general', difficulty: 'easy' },
  { question: 'Yazdan sonra hangi mevsim gelir?', category: 'general', difficulty: 'easy' },
  { question: 'Bir günde kaç saat vardır?', category: 'general', difficulty: 'easy' },
  { question: 'En uzun hayvan hangisidir?', category: 'general', difficulty: 'easy' },
  { question: 'Arılar ne yapar?', category: 'general', difficulty: 'easy' },
  { question: '10 eksi 3 kaç eder?', category: 'general', difficulty: 'easy' },
  { question: 'Yukarının zıttı nedir?', category: 'general', difficulty: 'easy' },
  { question: 'Bir arabanın kaç tekerleği vardır?', category: 'general', difficulty: 'easy' },
  { question: 'Yavru kediye ne denir?', category: 'general', difficulty: 'easy' },
  { question: 'Hangi meyve sarı ve kıvrıktır?', category: 'general', difficulty: 'easy' },
  { question: 'Ayaklara ne giyilir?', category: 'general', difficulty: 'easy' },
  { question: 'Şimdiye kadar gördüğün en komik şey ne?', category: 'funny', difficulty: 'medium' },
  { question: 'Bir evcil hayvan için en kötü isim ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'Aklına gelen en saçma süper güç ne?', category: 'funny', difficulty: 'easy' },
  { question: 'Sadece bir yemek yiyebilseydin sonsuza kadar, ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'Birine verebileceğin en kötü tavsiye ne olurdu?', category: 'funny', difficulty: 'medium' },
  { question: 'Teknene ne isim verirdin?', category: 'funny', difficulty: 'easy' },
  { question: 'Alabileceğin en kötü hediye ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'Reenkarnasyonla hangi hayvana dönmek en kötü olurdu?', category: 'funny', difficulty: 'medium' },
  { question: 'Hayal edebileceğin en sıkıcı şey ne?', category: 'funny', difficulty: 'easy' },
  { question: 'Bir restoran için korkunç bir isim ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'En kötü süper güç ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'En kötü sebze hangisi?', category: 'funny', difficulty: 'easy' },
  { question: 'Bir grup için kötü bir isim ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'Yolculukta unutulacak en kötü şey ne?', category: 'funny', difficulty: 'easy' },
  { question: 'Ayak yerine el mi yoksa el yerine ayak mı olsun isterdin?', category: 'general', difficulty: 'easy' },
  { question: 'Her zaman 10 dakika geç mi kalsan yoksa 20 dakika erken mi gelsin isterdin?', category: 'general', difficulty: 'easy' },
  { question: 'Telefonun mu olmasın yoksa televizyonun mu?', category: 'general', difficulty: 'easy' },
  { question: 'Sadece tatlı mı yoksa sadece tuzlu mu yesen?', category: 'general', difficulty: 'easy' },
  { question: 'Geçmişte mi yoksa gelecekte mi yaşardın?', category: 'general', difficulty: 'easy' },
  { question: 'Uçabilsen mi yoksa görünmez olsan mı isterdin?', category: 'general', difficulty: 'easy' },
  { question: 'Tüm yıl yaz mı yoksa kış mı olsun isterdin?', category: 'general', difficulty: 'easy' },
  { question: 'Kedi mi yoksa köpek mi olsun isterdin?', category: 'general', difficulty: 'easy' },
  { question: 'Asla sosyal medya mı kullanmasan yoksa asla film mi izlemesen?', category: 'general', difficulty: 'easy' },
  { question: 'Tüm dilleri mi konuşabilsen yoksa hayvanlarla mı konuşabilsen?', category: 'general', difficulty: 'easy' },
  { question: 'Sınırsız pizza mı yoksa sınırsız suşi mi isterdin?', category: 'general', difficulty: 'easy' },
  { question: 'Işınlanabilsen mi yoksa zamanda yolculuk mu yapabilsen?', category: 'general', difficulty: 'easy' },
  { question: 'Sesini mi yoksa işitmeni mi kaybetsen?', category: 'general', difficulty: 'easy' },
  { question: 'Minik bir fil mi yoksa dev bir hamster mı olsun isterdin?', category: 'general', difficulty: 'easy' },
  { question: 'Bugün günlerden ne?', category: 'random', difficulty: 'easy' },
  { question: 'Hangi aydayız?', category: 'random', difficulty: 'easy' },
  { question: 'Alfabedeki ilk harf hangisi?', category: 'random', difficulty: 'easy' },
  { question: 'Bir üçgenin kaç kenarı vardır?', category: 'random', difficulty: 'easy' },
  { question: 'Gündüzün zıttı ne?', category: 'random', difficulty: 'easy' },
  { question: 'Yavru köpeğe ne denir?', category: 'random', difficulty: 'easy' },
  { question: 'En hızlı kara hayvanı hangisi?', category: 'random', difficulty: 'medium' },
  { question: 'Bir örümceğin kaç ayağı vardır?', category: 'random', difficulty: 'easy' },
  { question: 'En küçük kıta hangisi?', category: 'random', difficulty: 'medium' },
  { question: '100 bölü 10 kaç eder?', category: 'random', difficulty: 'easy' },
  { question: 'Bir yılda kaç ay vardır?', category: 'random', difficulty: 'easy' },
  { question: '5 kere 5 kaç eder?', category: 'random', difficulty: 'easy' },
  { question: 'Gökkuşağında kaç renk vardır?', category: 'random', difficulty: 'easy' },
  { question: 'Güneş sistemimizdeki en büyük gezegen hangisi?', category: 'science', difficulty: 'easy' },
  { question: 'Yetişkin bir insanın kaç kemiği vardır?', category: 'science', difficulty: 'medium' },
  { question: 'Suyun kimyasal sembolü nedir?', category: 'science', difficulty: 'easy' },
  { question: 'Bizi yerde tutan kuvvet nedir?', category: 'science', difficulty: 'easy' },
  { question: 'Bitkiler havadan hangi gazı alır?', category: 'science', difficulty: 'easy' },
  { question: 'Yetişkinin genelde kaç dişi vardır?', category: 'science', difficulty: 'medium' },
  { question: 'Su Celsius\'ta kaç derecede kaynar?', category: 'science', difficulty: 'easy' },
  { question: 'Hangi gezegene Kızıl Gezegen denir?', category: 'science', difficulty: 'easy' },
  { question: 'Işık hızı nedir?', category: 'science', difficulty: 'hard' },
  { question: 'Bir ahtapotun kaç kalbi vardır?', category: 'science', difficulty: 'medium' },
  { question: 'Japonya\'nın başkenti neresidir?', category: 'geography', difficulty: 'easy' },
  { question: 'Dünyanın en uzun nehri hangisi?', category: 'geography', difficulty: 'medium' },
  { question: 'Yüzölçümü en büyük ülke hangisi?', category: 'geography', difficulty: 'easy' },
  { question: 'Mısır hangi kıtadadır?', category: 'geography', difficulty: 'easy' },
  { question: 'Avustralya\'nın başkenti neresidir?', category: 'geography', difficulty: 'easy' },
  { question: 'Hangi okyanus en soğuktur?', category: 'geography', difficulty: 'medium' },
  { question: 'Dünyanın en küçük ülkesi hangisi?', category: 'geography', difficulty: 'medium' },
  { question: 'Hangi ülkenin nüfusu en fazla?', category: 'geography', difficulty: 'easy' },
  { question: 'Brezilya\'nın başkenti neresidir?', category: 'geography', difficulty: 'easy' },
  { question: 'Eyfel Kulesi hangi ülkededir?', category: 'geography', difficulty: 'easy' },
  { question: 'Kuru üzüm hangi meyveden yapılır?', category: 'food', difficulty: 'easy' },
  { question: 'Havuç ne renktir?', category: 'food', difficulty: 'easy' },
  { question: 'Su donunca ne olur?', category: 'food', difficulty: 'easy' },
  { question: 'Ekmekte ana malzeme nedir?', category: 'food', difficulty: 'easy' },
  { question: 'Pizza hangi ülkeden çıkmıştır?', category: 'food', difficulty: 'easy' },
  { question: 'Olgun bir muz ne renktir?', category: 'food', difficulty: 'easy' },
  { question: 'Turşu hangi sebzeden yapılır?', category: 'food', difficulty: 'easy' },
  { question: 'Balı kim yapar?', category: 'food', difficulty: 'easy' },
  { question: 'Suşi ne tür bir yemektir?', category: 'food', difficulty: 'easy' },
  { question: 'Dışı kırmızı ve dışında çekirdekleri olan meyve hangisi?', category: 'food', difficulty: 'easy' },
  { question: 'Bir futbol takımında kaç oyuncu vardır?', category: 'sports', difficulty: 'easy' },
  { question: 'Olimpiyat bayrağındaki ortadaki halka ne renktir?', category: 'sports', difficulty: 'medium' },
  { question: 'Touchdown hangi sporda atılır?', category: 'sports', difficulty: 'easy' },
  { question: 'Teniste kaç Grand Slam turnuvası vardır?', category: 'sports', difficulty: 'medium' },
  { question: 'Basketbol topunun şekli nedir?', category: 'sports', difficulty: 'easy' },
  { question: 'Puck hangi sporda kullanılır?', category: 'sports', difficulty: 'easy' },
  { question: 'Indy 500 kaç turdur?', category: 'sports', difficulty: 'medium' },
  { question: 'Golf hangi ülkede icat edildi?', category: 'sports', difficulty: 'medium' },
  { question: 'Basketbol takımında kaç oyuncu vardır?', category: 'sports', difficulty: 'easy' },
  { question: 'Wimbledon\'da hangi oyun oynanır?', category: 'sports', difficulty: 'easy' },
  { question: 'Standart bir gitarın kaç teli vardır?', category: 'music', difficulty: 'easy' },
  { question: 'Siyah ve beyaz tuşları olan enstrüman hangisi?', category: 'music', difficulty: 'easy' },
  { question: 'Vals kaç tempoludur?', category: 'music', difficulty: 'medium' },
  { question: 'Orkestradaki en büyük enstrüman hangisi?', category: 'music', difficulty: 'easy' },
  { question: '"Yellow Submarine"ı hangi grup söyledi?', category: 'music', difficulty: 'easy' },
  { question: 'Bir oktavda kaç nota vardır?', category: 'music', difficulty: 'medium' },
  { question: 'Davulcu hangi enstrümanı çalar?', category: 'music', difficulty: 'easy' },
  { question: 'Opera hangi ülkede doğdu?', category: 'music', difficulty: 'medium' },
  { question: 'En tiz şarkı sesi hangisi?', category: 'music', difficulty: 'easy' },
  { question: 'Bir kemanın kaç teli vardır?', category: 'music', difficulty: 'easy' },
  { question: 'Hangi filmde bir aslan kral olur?', category: 'movies', difficulty: 'easy' },
  { question: 'Oz Büyücüsü\'ndeki büyücünün adı ne?', category: 'movies', difficulty: 'easy' },
  { question: 'Frozen\'ı hangi stüdyo yaptı?', category: 'movies', difficulty: 'easy' },
  { question: 'Ratatouille\'de Remy ne hayvan?', category: 'movies', difficulty: 'easy' },
  { question: 'Hangi filmde bir çocuk lambada cin bulur?', category: 'movies', difficulty: 'easy' },
  { question: 'Kayıp Balık Nemo\'daki balığın adı ne?', category: 'movies', difficulty: 'easy' },
  { question: 'Simba adlı karakter hangi filmde var?', category: 'movies', difficulty: 'easy' },
  { question: 'Külkedisi\'nin elbisesi ne renktir?', category: 'movies', difficulty: 'easy' },
  { question: 'Hangi filmde oyuncaklar canlanır?', category: 'movies', difficulty: 'easy' },
  { question: 'Dumbo ne hayvan?', category: 'movies', difficulty: 'easy' },
  { question: '3 kere 4 kaç eder?', category: 'general', difficulty: 'easy' },
  { question: 'Bir insanın kaç gözü vardır?', category: 'general', difficulty: 'easy' },
  { question: 'Güneş nedir?', category: 'general', difficulty: 'easy' },
  { question: 'Kuşlar neyle uçar?', category: 'general', difficulty: 'easy' },
  { question: 'Kar neyden yapılır?', category: 'general', difficulty: 'easy' },
  { question: 'Bir saatte kaç dakika vardır?', category: 'general', difficulty: 'easy' },
  { question: 'Büyüğün zıttı ne?', category: 'general', difficulty: 'easy' },
  { question: 'Ne ile görürsün?', category: 'general', difficulty: 'easy' },
  { question: 'Uzun hortumu olan hayvan hangisi?', category: 'general', difficulty: 'easy' },
  { question: 'Güneş ne renktir?', category: 'general', difficulty: 'easy' },
  { question: 'Bir karenin kaç kenarı vardır?', category: 'general', difficulty: 'easy' },
  { question: 'Balıklar ne solur?', category: 'general', difficulty: 'easy' },
  { question: 'Yağmur yağınca gökten ne düşer?', category: 'general', difficulty: 'easy' },
  { question: '15 artı 15 kaç eder?', category: 'general', difficulty: 'easy' },
  { question: 'Bebek koyuna ne denir?', category: 'general', difficulty: 'easy' },
  { question: 'Bir sandalyenin kaç ayağı vardır?', category: 'general', difficulty: 'easy' },
  { question: 'Hızlının zıttı ne?', category: 'general', difficulty: 'easy' },
  { question: 'Kitapta ne okursun?', category: 'general', difficulty: 'easy' },
  { question: 'En çok kar hangi mevsimde?', category: 'general', difficulty: 'easy' },
  { question: 'En kötü iş unvanı ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'En gereksiz icat ne?', category: 'funny', difficulty: 'easy' },
  { question: 'Bir sabun için kötü isim ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'En kötü dondurma aroması hangisi?', category: 'funny', difficulty: 'easy' },
  { question: 'Berbat bir şifre ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'En saçma seyahat yolu ne?', category: 'funny', difficulty: 'easy' },
  { question: 'Neye alerji olmak en kötü olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'Unutulacak en utanç verici şey ne?', category: 'funny', difficulty: 'easy' },
  { question: 'Bir hastane için kötü isim ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'Partide en kötü süper güç hangisi?', category: 'funny', difficulty: 'easy' },
  { question: 'Tat alamamak mı koku alamamak mı tercih edersin?', category: 'general', difficulty: 'easy' },
  { question: 'At büyüklüğünde bir ördek mi yoksa 100 ördek büyüklüğünde at mı ile savaşırdın?', category: 'general', difficulty: 'easy' },
  { question: 'Hayatta geri sarma mı duraklatma butonu mu isterdin?', category: 'general', difficulty: 'easy' },
  { question: 'Hep şarkı mı söylesen hep fısıldasan mı?', category: 'general', difficulty: 'easy' },
  { question: 'Kaşın mı kirpiğin mi olmasın?', category: 'general', difficulty: 'easy' },
  { question: 'Ünlü mü zengin mi olmak isterdin?', category: 'general', difficulty: 'easy' },
  { question: 'Kuyruk mu boynuz mu olsun isterdin?', category: 'general', difficulty: 'easy' },
  { question: 'Müziksiz mi filmsiz mi yaşardın?', category: 'general', difficulty: 'easy' },
  { question: 'Kişisel şef mi kişisel pilot mu isterdin?', category: 'general', difficulty: 'easy' },
  { question: 'Ne zaman mı nasıl öleceğini mi bilmek isterdin?', category: 'general', difficulty: 'easy' },
  { question: '7 kere 8 kaç eder?', category: 'random', difficulty: 'medium' },
  { question: 'Binde kaç sıfır var?', category: 'random', difficulty: 'easy' },
  { question: 'Alfabenin son harfi ne?', category: 'random', difficulty: 'easy' },
  { question: 'Altıgenin kaç kenarı var?', category: 'random', difficulty: 'easy' },
  { question: '100\'ün yüzde 50\'si kaç?', category: 'random', difficulty: 'easy' },
  { question: 'Bir dakikada kaç saniye var?', category: 'random', difficulty: 'easy' },
  { question: 'Su Celsius\'ta kaç derecede donar?', category: 'random', difficulty: 'easy' },
  { question: 'ABD bayrağında kaç şerit var?', category: 'random', difficulty: 'medium' },
  { question: '12 kere 12 kaç eder?', category: 'random', difficulty: 'medium' },
  { question: 'Bir böceğin kaç bacağı var?', category: 'random', difficulty: 'easy' },
  { question: 'Altının kimyasal sembolü ne?', category: 'science', difficulty: 'easy' },
  { question: 'Güneş sistemimizde kaç gezegen var?', category: 'science', difficulty: 'easy' },
  { question: 'Kanı hangi organ pompalar?', category: 'science', difficulty: 'easy' },
  { question: 'H2O nedir?', category: 'science', difficulty: 'easy' },
  { question: 'İnsanlar hangi gazı verir?', category: 'science', difficulty: 'easy' },
  { question: 'Bir kelebeğin kaç kanadı var?', category: 'science', difficulty: 'easy' },
  { question: 'Dünyaya en yakın yıldız hangisi?', category: 'science', difficulty: 'easy' },
  { question: 'En sert doğal madde ne?', category: 'science', difficulty: 'medium' },
  { question: 'İnsanın kaç kromozomu var?', category: 'science', difficulty: 'hard' },
  { question: 'Güneşe en yakın gezegen hangisi?', category: 'science', difficulty: 'easy' },
  { question: 'Almanya\'nın başkenti neresi?', category: 'geography', difficulty: 'easy' },
  { question: 'Piramitler hangi ülkede?', category: 'geography', difficulty: 'easy' },
  { question: 'İtalya\'nın başkenti neresi?', category: 'geography', difficulty: 'easy' },
  { question: 'Amerika ile Avrupa arasında hangi okyanus var?', category: 'geography', difficulty: 'easy' },
  { question: 'Kanada\'nın başkenti neresi?', category: 'geography', difficulty: 'easy' },
  { question: 'Pisa Kulesi hangi ülkede?', category: 'geography', difficulty: 'easy' },
  { question: 'En uzun dağ sırası hangisi?', category: 'geography', difficulty: 'medium' },
  { question: 'Çin Seddi hangi ülkede?', category: 'geography', difficulty: 'easy' },
  { question: 'Meksika\'nın başkenti neresi?', category: 'geography', difficulty: 'easy' },
  { question: 'Özgürlük Heykeli hangi ülkede?', category: 'geography', difficulty: 'easy' },
  { question: 'Patates kızartması hangi sebzeden yapılır?', category: 'food', difficulty: 'easy' },
  { question: 'Elma ne renktir?', category: 'food', difficulty: 'easy' },
  { question: 'Tost makinesine ne konur?', category: 'food', difficulty: 'easy' },
  { question: 'Humusun ana malzemesi ne?', category: 'food', difficulty: 'easy' },
  { question: 'Dışı yeşil içi kırmızı meyve hangisi?', category: 'food', difficulty: 'easy' },
  { question: 'Çayı tatlandırmak için ne eklenir?', category: 'food', difficulty: 'easy' },
  { question: 'Ketçap neyden yapılır?', category: 'food', difficulty: 'easy' },
  { question: 'Süt ne renktir?', category: 'food', difficulty: 'easy' },
  { question: 'Pilav hangi tahıldan?', category: 'food', difficulty: 'easy' },
  { question: 'Guacamole\'nin ana malzemesi ne?', category: 'food', difficulty: 'easy' },
  { question: 'Touchdown kaç puan değer?', category: 'sports', difficulty: 'easy' },
  { question: 'Tüytop hangi sporda kullanılır?', category: 'sports', difficulty: 'easy' },
  { question: 'Bir beyzbol takımında kaç oyuncu var?', category: 'sports', difficulty: 'medium' },
  { question: 'Tour de France lideri hangi renk forması giyer?', category: 'sports', difficulty: 'medium' },
  { question: 'Bowling hangi sporda yapılır?', category: 'sports', difficulty: 'easy' },
  { question: 'Serena Williams kaç Grand Slam kazandı?', category: 'sports', difficulty: 'hard' },
  { question: 'Amerikan futbol topu ne şekilde?', category: 'sports', difficulty: 'easy' },
  { question: 'Maraton koşusu hangi ülkede başladı?', category: 'sports', difficulty: 'medium' },
  { question: 'Olimpiyat bayrağında kaç halka var?', category: 'sports', difficulty: 'easy' },
  { question: 'File ve top hangi sporda kullanılır?', category: 'sports', difficulty: 'easy' },
  { question: 'Standart piyanoda kaç tuş var?', category: 'music', difficulty: 'medium' },
  { question: 'Elvis hangi enstrümanı çalardı?', category: 'music', difficulty: 'easy' },
  { question: 'Ukulele\'de kaç tel var?', category: 'music', difficulty: 'easy' },
  { question: 'En kalın şan sesi hangisi?', category: 'music', difficulty: 'easy' },
  { question: 'Opera binası hangi şehirde ünlü?', category: 'music', difficulty: 'medium' },
  { question: '"Bohemian Rhapsody" hangi grubun?', category: 'music', difficulty: 'easy' },
  { question: 'Dörtlüde kaç üye var?', category: 'music', difficulty: 'easy' },
  { question: 'Sürgüsü olan enstrüman hangisi?', category: 'music', difficulty: 'easy' },
  { question: 'Beethoven hangi tür?', category: 'music', difficulty: 'easy' },
  { question: 'Beatles kaç albüm çıkardı?', category: 'music', difficulty: 'hard' },
  { question: 'Hangi filmde bir çocuk büyücü okuluna gider?', category: 'movies', difficulty: 'easy' },
  { question: 'Jaws\'taki köpekbalığının adı ne?', category: 'movies', difficulty: 'easy' },
  { question: '"I will find you" hangi filmde geçer?', category: 'movies', difficulty: 'medium' },
  { question: 'Shrek\'teki Eşek ne hayvan?', category: 'movies', difficulty: 'easy' },
  { question: 'Hangi filmde bir robot "I\'ll be back" der?', category: 'movies', difficulty: 'easy' },
  { question: 'Ejderhanı Nasıl Eğitirsin\'deki ejderhanın adı ne?', category: 'movies', difficulty: 'easy' },
  { question: 'Toy Story\'yi hangi stüdyo yaptı?', category: 'movies', difficulty: 'easy' },
  { question: 'Aslan Kral\'daki aslanın adı ne?', category: 'movies', difficulty: 'easy' },
  { question: 'Hangi filmde bir kızın uzun sihirli saçları var?', category: 'movies', difficulty: 'easy' },
  { question: 'Geleceğe Dönüş\'te Doc ne aracı kullanır?', category: 'movies', difficulty: 'easy' },
  { question: '20 artı 30 kaç eder?', category: 'general', difficulty: 'easy' },
  { question: 'Bir insanın kaç burnu var?', category: 'general', difficulty: 'easy' },
  { question: 'Ne ile duyarsın?', category: 'general', difficulty: 'easy' },
  { question: 'Islağın zıttı ne?', category: 'general', difficulty: 'easy' },
  { question: 'Dikdörtgenin kaç köşesi var?', category: 'general', difficulty: 'easy' },
  { question: 'İnekler bize ne verir?', category: 'general', difficulty: 'easy' },
  { question: 'Ne ile koku alırsın?', category: 'general', difficulty: 'easy' },
  { question: 'Yapraklar hangi mevsimde düşer?', category: 'general', difficulty: 'easy' },
  { question: 'Bir masanın genelde kaç ayağı var?', category: 'general', difficulty: 'easy' },
  { question: '9 eksi 4 kaç eder?', category: 'general', difficulty: 'easy' },
  { question: 'Tavuklar ne yumurtlar?', category: 'general', difficulty: 'easy' },
  { question: 'Aydınlığın zıttı ne?', category: 'general', difficulty: 'easy' },
  { question: 'Bir kuşun kaç kanadı var?', category: 'general', difficulty: 'easy' },
  { question: 'Dişlerini neyle fırçalarsın?', category: 'general', difficulty: 'easy' },
  { question: 'Düğünde söylenecek en kötü şey ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'Toplumda düşürülecek en kötü şey ne?', category: 'funny', difficulty: 'easy' },
  { question: 'Bir dişçi için berbat isim ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'Koleksiyonu yapılacak en saçma şey ne?', category: 'funny', difficulty: 'easy' },
  { question: 'Mülakatta en kötü süper güç hangisi?', category: 'funny', difficulty: 'easy' },
  { question: 'Sonsuza kadar yapışkan parmak mı terli ayak mı?', category: 'general', difficulty: 'easy' },
  { question: 'Geri giden saat mi hep yanlış gösteren saat mi?', category: 'general', difficulty: 'easy' },
  { question: 'Sadece fısıldayabilsen mi sadece bağırabilsen mi?', category: 'general', difficulty: 'easy' },
  { question: 'Hiç saçın mı olmasın her yerde saç mı olsun?', category: 'general', difficulty: 'easy' },
  { question: 'Bitkilerle mi böceklerle mi konuşabilsen?', category: 'general', difficulty: 'easy' },
  { question: '6 kere 7 kaç eder?', category: 'random', difficulty: 'medium' },
  { question: 'Artık yılda şubat kaç gün?', category: 'random', difficulty: 'easy' },
  { question: '99\'dan sonra hangi sayı gelir?', category: 'random', difficulty: 'easy' },
  { question: 'Bir yengecin kaç bacağı var?', category: 'random', difficulty: 'easy' },
  { question: '200\'ün yüzde 25\'i kaç?', category: 'random', difficulty: 'medium' },
  { question: 'Demirin kimyasal sembolü ne?', category: 'science', difficulty: 'medium' },
  { question: 'İnsanın kaç akciğeri var?', category: 'science', difficulty: 'easy' },
  { question: 'İnsan vücudunun en büyük organı hangisi?', category: 'science', difficulty: 'medium' },
  { question: 'Hangi gezegenin halkaları var?', category: 'science', difficulty: 'easy' },
  { question: 'Tırtıllar neye dönüşür?', category: 'science', difficulty: 'easy' },
  { question: 'İngiltere\'nin başkenti neresi?', category: 'geography', difficulty: 'easy' },
  { question: 'Ölü Deniz hangi deniz?', category: 'geography', difficulty: 'medium' },
  { question: 'Hindistan\'ın başkenti neresi?', category: 'geography', difficulty: 'easy' },
  { question: 'En çok ülkesi olan kıta hangisi?', category: 'geography', difficulty: 'medium' },
  { question: 'Güney Kore\'nin başkenti neresi?', category: 'geography', difficulty: 'easy' },
  { question: 'Fıstık ezmesi hangi yemişten yapılır?', category: 'food', difficulty: 'easy' },
  { question: 'Portakal ağacından hangi meyve çıkar?', category: 'food', difficulty: 'easy' },
  { question: 'Tereyağının ana malzemesi ne?', category: 'food', difficulty: 'easy' },
  { question: 'Mor ve yuvarlak sebze hangisi?', category: 'food', difficulty: 'easy' },
  { question: 'Gün ortası yemeğine ne denir?', category: 'food', difficulty: 'easy' },
  { question: 'Voleybol takımında kaç oyuncu var?', category: 'sports', difficulty: 'easy' },
  { question: 'Tenis topu ne renktir?', category: 'sports', difficulty: 'easy' },
  { question: 'Hangi sporda ata binilir?', category: 'sports', difficulty: 'easy' },
  { question: 'Golf sahasında kaç delik var?', category: 'sports', difficulty: 'medium' },
  { question: 'Super Bowl\'da hangi spor oynanır?', category: 'sports', difficulty: 'easy' },
  { question: 'Cazda genelde hangi enstrüman çalınır?', category: 'music', difficulty: 'easy' },
  { question: 'Bas gitarında kaç tel var?', category: 'music', difficulty: 'easy' },
  { question: 'Dört şarkıcıdan oluşan gruba ne denir?', category: 'music', difficulty: 'medium' },
  { question: '"Stairway to Heaven" hangi grubun?', category: 'music', difficulty: 'easy' },
  { question: 'Gamda sol\'dan sonra hangi nota gelir?', category: 'music', difficulty: 'medium' },
  { question: 'Hangi filmde bir çocuk büyücü olduğunu keşfeder?', category: 'movies', difficulty: 'easy' },
  { question: 'Karlar Ülkesi\'ndeki prensesin adı ne?', category: 'movies', difficulty: 'easy' },
  { question: 'Dory adlı karakter hangi filmde?', category: 'movies', difficulty: 'easy' },
  { question: 'Hangi filmde arabalar canlanır?', category: 'movies', difficulty: 'easy' },
  { question: 'Karlar Ülkesi\'ndeki kardan adamın adı ne?', category: 'movies', difficulty: 'easy' },
  { question: 'İkinci Dünya Savaşı hangi yılda bitti?', category: 'history', difficulty: 'easy' },
  { question: 'Aya ilk ayak basan kimdi?', category: 'history', difficulty: 'easy' },
  { question: 'Kolezyum\'u hangi imparatorluk yaptı?', category: 'history', difficulty: 'easy' },
  { question: 'Rönesans hangi ülkede başladı?', category: 'history', difficulty: 'medium' },
  { question: 'Bağımsızlık Bildirgesi\'ni kim yazdı?', category: 'history', difficulty: 'easy' },
  { question: 'Mısır\'daki antik dünya harikası hangisi?', category: 'history', difficulty: 'easy' },
  { question: 'Berlin Duvarı ne zaman yıkıldı?', category: 'history', difficulty: 'medium' },
  { question: 'Ampulü kim icat etti?', category: 'history', difficulty: 'easy' },
  { question: 'Machu Picchu\'yu hangi uygarlık inşa etti?', category: 'history', difficulty: 'medium' },
  { question: 'Birinci Dünya Savaşı hangi yüzyılda başladı?', category: 'history', difficulty: 'medium' },
  { question: 'ABD\'nin ilk başkanı kimdi?', category: 'history', difficulty: 'easy' },
  { question: 'Özgürlük Heykeli\'ni ABD\'ye hangi ülke hediye etti?', category: 'history', difficulty: 'easy' },
  { question: 'Mona Lisa\'yı kim çizdi?', category: 'history', difficulty: 'easy' },
  { question: 'İnsan ilk kez ne zaman Ay\'a ayak bastı?', category: 'history', difficulty: 'easy' },
  { question: 'Çin Seddi\'ni hangi imparatorluk yaptırdı?', category: 'history', difficulty: 'easy' },
  { question: '1492\'de Amerika\'yı kim keşfetti?', category: 'history', difficulty: 'easy' },
  { question: 'CPU ne anlama gelir?', category: 'technology', difficulty: 'easy' },
  { question: 'Facebook\'u kim kurdu?', category: 'technology', difficulty: 'easy' },
  { question: 'İlk iPhone hangi yıl çıktı?', category: 'technology', difficulty: 'medium' },
  { question: 'WiFi ne anlama gelir?', category: 'technology', difficulty: 'medium' },
  { question: 'PlayStation\'ı hangi şirket yapıyor?', category: 'technology', difficulty: 'easy' },
  { question: 'USB ne anlama gelir?', category: 'technology', difficulty: 'medium' },
  { question: 'Microsoft\'u kim kurdu?', category: 'technology', difficulty: 'easy' },
  { question: 'Google asistanının adı ne?', category: 'technology', difficulty: 'easy' },
  { question: 'Bir byte\'ta kaç bit var?', category: 'technology', difficulty: 'medium' },
  { question: 'HTML ne anlama gelir?', category: 'technology', difficulty: 'easy' },
  { question: 'Android\'i hangi şirket geliştirdi?', category: 'technology', difficulty: 'easy' },
  { question: 'GPS ne anlama gelir?', category: 'technology', difficulty: 'easy' },
  { question: 'Amazon\'un sesli asistanının adı ne?', category: 'technology', difficulty: 'easy' },
  { question: 'YouTube hangi yıl kuruldu?', category: 'technology', difficulty: 'medium' },
  { question: 'RAM ne anlama gelir?', category: 'technology', difficulty: 'medium' },
  { question: 'Karada en hızlı hayvan hangisi?', category: 'nature', difficulty: 'easy' },
  { question: 'Dünyanın en büyük memelisi hangisi?', category: 'nature', difficulty: 'easy' },
  { question: 'Bir böceğin kaç ayağı var?', category: 'nature', difficulty: 'easy' },
  { question: 'Uçabilen tek memeli hangisi?', category: 'nature', difficulty: 'easy' },
  { question: 'Kızıl Gezegen hangisi?', category: 'nature', difficulty: 'easy' },
  { question: 'En büyük ayı türü hangisi?', category: 'nature', difficulty: 'easy' },
  { question: 'Bir inek kaç mideye sahip?', category: 'nature', difficulty: 'medium' },
  { question: 'En uzun ağaç türü hangisi?', category: 'nature', difficulty: 'medium' },
  { question: 'Hangi kuş uçamaz?', category: 'nature', difficulty: 'easy' },
  { question: 'Dünyanın en küçük kuşu hangisi?', category: 'nature', difficulty: 'medium' },
  { question: 'Bir ahtapotun kaç kolu var?', category: 'nature', difficulty: 'easy' },
  { question: 'En büyük okyanus hayvanı hangisi?', category: 'nature', difficulty: 'easy' },
  { question: 'En çok hangi hayvan uyur?', category: 'nature', difficulty: 'medium' },
  { question: 'Hangi kıtada sürüngen yok?', category: 'nature', difficulty: 'hard' },
  { question: 'Zürafanın boynunda kaç kemik var?', category: 'nature', difficulty: 'medium' },
  { question: 'Fransa\'nın başkenti neresi?', category: 'travel', difficulty: 'easy' },
  { question: 'En çok adaya hangi ülke sahip?', category: 'travel', difficulty: 'medium' },
  { question: 'Avrupa\'nın en uzun nehri hangisi?', category: 'travel', difficulty: 'medium' },
  { question: 'Akropol hangi şehirde?', category: 'travel', difficulty: 'easy' },
  { question: 'Tayland\'ın başkenti neresi?', category: 'travel', difficulty: 'easy' },
  { question: 'Tac Mahal hangi ülkede?', category: 'travel', difficulty: 'easy' },
  { question: 'Dünyanın en küçük ülkesi hangisi?', category: 'travel', difficulty: 'easy' },
  { question: 'Empire State Building hangi şehirde?', category: 'travel', difficulty: 'easy' },
  { question: 'Mısır\'ın başkenti neresi?', category: 'travel', difficulty: 'easy' },
  { question: 'Sahra hangi kıtada?', category: 'travel', difficulty: 'easy' },
  { question: 'Arjantin\'in başkenti neresi?', category: 'travel', difficulty: 'easy' },
  { question: 'Büyük Set Resifi hangi ülkede?', category: 'travel', difficulty: 'easy' },
  { question: 'Güney Afrika\'nın başkenti neresi?', category: 'travel', difficulty: 'easy' },
  { question: 'Hangi Avrupa şehri Boğaziçi ile ikiye ayrılır?', category: 'travel', difficulty: 'medium' },
  { question: 'Dünyanın en yüksek başkenti hangisi?', category: 'travel', difficulty: 'hard' },
  { question: 'En sevdiğin tatil destinasyonu neresi?', category: 'general', difficulty: 'easy' },
  { question: 'Aldığın en iyi tavsiye ne?', category: 'general', difficulty: 'easy' },
  { question: 'Bir gün boş olsa ne yapardın?', category: 'general', difficulty: 'easy' },
  { question: 'Hangi beceriyi öğrenmek isterdin?', category: 'general', difficulty: 'easy' },
  { question: 'En sevdiğin rahatlama yöntemin ne?', category: 'general', difficulty: 'easy' },
  { question: 'Gördüğün en garip rüya neydi?', category: 'funny', difficulty: 'medium' },
  { question: 'Cenazede çalınacak en kötü şarkı ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'Odandaki en utanç verici şey ne?', category: 'funny', difficulty: 'easy' },
  { question: 'Evcil bir taş için kötü bir isim ne olurdu?', category: 'funny', difficulty: 'easy' },
  { question: 'Duyduğun en kötü flört cümlesi ne?', category: 'funny', difficulty: 'easy' },
  { question: 'Dur işaretinde kaç kenar var?', category: 'random', difficulty: 'easy' },
  { question: '11 kere 11 kaç eder?', category: 'random', difficulty: 'medium' },
  { question: 'Bir küpün kaç yüzü var?', category: 'random', difficulty: 'easy' },
  { question: 'Tek çift asal sayı hangisi?', category: 'random', difficulty: 'medium' },
  { question: 'İnsan elinde kaç kemik var?', category: 'science', difficulty: 'medium' },
  { question: 'Sodyumun kimyasal sembolü ne?', category: 'science', difficulty: 'easy' },
  { question: 'Güneş\'e en uzak gezegen hangisi?', category: 'science', difficulty: 'easy' },
  { question: 'İnsan vücudundaki en küçük kemik hangisi?', category: 'science', difficulty: 'hard' },
  { question: 'En çok hangi gazı soluruz?', category: 'science', difficulty: 'easy' },
  { question: 'İspanya\'nın başkenti neresi?', category: 'geography', difficulty: 'easy' },
  { question: 'En çok hangi ülkenin volkanı var?', category: 'geography', difficulty: 'medium' },
  { question: 'Rusya\'nın başkenti neresi?', category: 'geography', difficulty: 'easy' },
  { question: 'Çikolatanın ana malzemesi ne?', category: 'food', difficulty: 'easy' },
  { question: 'Şarap hangi meyveden yapılır?', category: 'food', difficulty: 'easy' },
  { question: 'Dünyada en çok hangi et tüketilir?', category: 'food', difficulty: 'medium' },
  { question: 'Krikette bir takımda kaç oyuncu var?', category: 'sports', difficulty: 'medium' },
  { question: 'Hangi sporda home run yapılır?', category: 'sports', difficulty: 'easy' },
  { question: '88 tuşlu enstrüman hangisi?', category: 'music', difficulty: 'easy' },
  { question: '"Thriller"ı kim söyledi?', category: 'music', difficulty: 'easy' },
  { question: 'Hangi filmde bir genç örümcek tarafından ısırılıyor?', category: 'movies', difficulty: 'easy' },
  { question: 'Harry Potter\'daki büyü okulunun adı ne?', category: 'movies', difficulty: 'easy' },
  { question: 'What is your favorite memory from childhood?', category: 'general', difficulty: 'easy' },
  { question: 'If you could have dinner with anyone, who would it be?', category: 'general', difficulty: 'easy' },
  { question: 'What is the best book you have ever read?', category: 'general', difficulty: 'easy' },
  { question: 'What would you do if you won the lottery?', category: 'general', difficulty: 'easy' },
  { question: 'What is your favorite season and why?', category: 'general', difficulty: 'easy' },
  { question: 'What hobby would you like to try?', category: 'general', difficulty: 'easy' },
  { question: 'What is the most beautiful place you have been?', category: 'general', difficulty: 'easy' },
  { question: 'What superpower would you choose?', category: 'general', difficulty: 'easy' },
  { question: 'What is your go-to karaoke song?', category: 'general', difficulty: 'easy' },
  { question: 'What is the worst haircut you have had?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst thing to say on a first date?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the funniest autocorrect fail you have seen?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a terrible name for a perfume?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the most ridiculous fashion trend?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst animal to be reincarnated as?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the silliest thing you have ever bought?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be a bad name for a gym?', category: 'funny', difficulty: 'easy' },
  { question: 'What is the worst combination of foods?', category: 'funny', difficulty: 'easy' },
  { question: 'What would be the worst job for a vampire?', category: 'funny', difficulty: 'easy' },
  { question: 'How many degrees are in a right angle?', category: 'random', difficulty: 'easy' },
  { question: 'What is 9 times 9?', category: 'random', difficulty: 'easy' },
  { question: 'How many sides does a pentagon have?', category: 'random', difficulty: 'easy' },
  { question: 'What is the square root of 64?', category: 'random', difficulty: 'easy' },
  { question: 'How many days are in a leap year?', category: 'random', difficulty: 'easy' },
  { question: 'What is 15 percent of 100?', category: 'random', difficulty: 'easy' },
  { question: 'How many continents start with the letter A?', category: 'random', difficulty: 'medium' },
  { question: 'What is the only number that is the same in English and French?', category: 'random', difficulty: 'hard' },
  { question: 'How many keys are on a standard computer keyboard?', category: 'random', difficulty: 'medium' },
  { question: 'What is the largest prime number under 20?', category: 'random', difficulty: 'medium' },
  { question: 'What is the powerhouse of the cell?', category: 'science', difficulty: 'easy' },
  { question: 'How many bones are in the human spine?', category: 'science', difficulty: 'medium' },
  { question: 'What is the chemical symbol for carbon?', category: 'science', difficulty: 'easy' },
  { question: 'What planet is known for its rings?', category: 'science', difficulty: 'easy' },
  { question: 'How many teeth do adults typically have?', category: 'science', difficulty: 'easy' },
  { question: 'What is the smallest planet in our solar system?', category: 'science', difficulty: 'easy' },
  { question: 'What gas makes up most of the atmosphere?', category: 'science', difficulty: 'easy' },
  { question: 'How many chambers does the human heart have?', category: 'science', difficulty: 'easy' },
  { question: 'What is the speed of sound?', category: 'science', difficulty: 'hard' },
  { question: 'What is the chemical symbol for oxygen?', category: 'science', difficulty: 'easy' },
  { question: 'What is the capital of Greece?', category: 'geography', difficulty: 'easy' },
  { question: 'Which country is home to the kangaroo?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Turkey?', category: 'geography', difficulty: 'easy' },
  { question: 'Which river flows through Paris?', category: 'geography', difficulty: 'easy' },
  { question: 'What is the capital of Poland?', category: 'geography', difficulty: 'easy' },
  { question: 'Which country has the most population in Africa?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the capital of Sweden?', category: 'geography', difficulty: 'easy' },
  { question: 'Which sea is the saltiest?', category: 'geography', difficulty: 'medium' },
  { question: 'What is the capital of the Netherlands?', category: 'geography', difficulty: 'easy' },
  { question: 'Which mountain is the tallest in the world?', category: 'geography', difficulty: 'easy' },
  { question: 'What vegetable is known as the king of vegetables?', category: 'food', difficulty: 'medium' },
  { question: 'What is the main ingredient in tzatziki?', category: 'food', difficulty: 'easy' },
  { question: 'What nut is in pesto?', category: 'food', difficulty: 'easy' },
  { question: 'What fruit is known as the king of fruits?', category: 'food', difficulty: 'medium' },
  { question: 'What is the primary ingredient in falafel?', category: 'food', difficulty: 'easy' },
  { question: 'What type of cheese is used in Greek salad?', category: 'food', difficulty: 'easy' },
  { question: 'What grain is used to make beer?', category: 'food', difficulty: 'easy' },
  { question: 'What is the main ingredient in guacamole?', category: 'food', difficulty: 'easy' },
  { question: 'What fruit is dried to make prunes?', category: 'food', difficulty: 'easy' },
  { question: 'What is the most expensive spice in the world?', category: 'food', difficulty: 'medium' },
  { question: 'How many players are on a rugby team?', category: 'sports', difficulty: 'medium' },
  { question: 'In which sport do you use a racket and shuttlecock?', category: 'sports', difficulty: 'easy' },
  { question: 'What color is the ball in pool?', category: 'sports', difficulty: 'easy' },
  { question: 'How many Grand Slam tournaments does tennis have per year?', category: 'sports', difficulty: 'easy' },
  { question: 'In which country did basketball originate?', category: 'sports', difficulty: 'easy' },
  { question: 'What is the national sport of Canada?', category: 'sports', difficulty: 'medium' },
  { question: 'How many minutes are in a soccer half?', category: 'sports', difficulty: 'easy' },
  { question: 'In which sport do you score a try?', category: 'sports', difficulty: 'medium' },
  { question: 'What is the diameter of a basketball hoop?', category: 'sports', difficulty: 'hard' },
  { question: 'Which country has won the most World Cups?', category: 'sports', difficulty: 'easy' },
  { question: 'What instrument has 88 keys?', category: 'music', difficulty: 'easy' },
  { question: 'Who is known as the King of Pop?', category: 'music', difficulty: 'easy' },
  { question: 'How many strings does a harp have?', category: 'music', difficulty: 'hard' },
  { question: 'What is the most played song at weddings?', category: 'music', difficulty: 'medium' },
  { question: 'In which city did jazz originate?', category: 'music', difficulty: 'medium' },
  { question: 'What band sang "Sweet Child O\' Mine"?', category: 'music', difficulty: 'easy' },
  { question: 'How many members are in a trio?', category: 'music', difficulty: 'easy' },
  { question: 'What is the highest male singing voice?', category: 'music', difficulty: 'easy' },
  { question: 'Who wrote the Ninth Symphony?', category: 'music', difficulty: 'easy' },
  { question: 'What instrument is known as the king of instruments?', category: 'music', difficulty: 'medium' },
  { question: 'In which film does a boy ride a dragon?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the dragon in Game of Thrones?', category: 'movies', difficulty: 'medium' },
  { question: 'Which film features a talking raccoon?', category: 'movies', difficulty: 'easy' },
  { question: 'In which film does a robot become human?', category: 'movies', difficulty: 'medium' },
  { question: 'What is the name of the ship in Titanic?', category: 'movies', difficulty: 'easy' },
  { question: 'Which studio made Shrek?', category: 'movies', difficulty: 'easy' },
  { question: 'In which film does a clown fish search for his son?', category: 'movies', difficulty: 'easy' },
  { question: 'What is the name of the dinosaur in Jurassic Park?', category: 'movies', difficulty: 'easy' },
  { question: 'Which film has "May the Force be with you"?', category: 'movies', difficulty: 'easy' },
  { question: 'In which year did the Titanic sink?', category: 'movies', difficulty: 'medium' },
  { question: 'Who was the first woman to win a Nobel Prize?', category: 'history', difficulty: 'medium' },
  { question: 'In which year did the French Revolution begin?', category: 'history', difficulty: 'medium' },
  { question: 'Who built the first printing press?', category: 'history', difficulty: 'medium' },
  { question: 'Which empire was ruled by Genghis Khan?', category: 'history', difficulty: 'easy' },
  { question: 'When did the Roman Empire fall?', category: 'history', difficulty: 'hard' },
  { question: 'Who was the British prime minister during World War II?', category: 'history', difficulty: 'easy' },
  { question: 'Which country invented paper?', category: 'history', difficulty: 'medium' },
  { question: 'Who wrote the Odyssey?', category: 'history', difficulty: 'easy' },
  { question: 'In which year did man first fly in an airplane?', category: 'history', difficulty: 'medium' },
  { question: 'Who discovered penicillin?', category: 'history', difficulty: 'medium' },
  { question: 'What does AI stand for?', category: 'technology', difficulty: 'easy' },
  { question: 'Who founded Tesla?', category: 'technology', difficulty: 'easy' },
  { question: 'What year was the first computer virus created?', category: 'technology', difficulty: 'hard' },
  { question: 'What does VPN stand for?', category: 'technology', difficulty: 'medium' },
  { question: 'Which company makes the Switch?', category: 'technology', difficulty: 'easy' },
  { question: 'What does SSD stand for?', category: 'technology', difficulty: 'medium' },
  { question: 'Who created Linux?', category: 'technology', difficulty: 'hard' },
  { question: 'What is the name of Apple\'s voice assistant?', category: 'technology', difficulty: 'easy' },
  { question: 'In what year was the first email sent?', category: 'technology', difficulty: 'hard' },
  { question: 'What does HTTP stand for?', category: 'technology', difficulty: 'medium' },
  { question: 'Which animal can live the longest?', category: 'nature', difficulty: 'medium' },
  { question: 'What is the only mammal that lays eggs?', category: 'nature', difficulty: 'easy' },
  { question: 'How many eyes does a bee have?', category: 'nature', difficulty: 'medium' },
  { question: 'What is the fastest bird?', category: 'nature', difficulty: 'medium' },
  { question: 'Which animal has the longest migration?', category: 'nature', difficulty: 'hard' },
  { question: 'What is the largest land animal?', category: 'nature', difficulty: 'easy' },
  { question: 'How many stomachs does a goat have?', category: 'nature', difficulty: 'medium' },
  { question: 'What is the only bird that can fly backward?', category: 'nature', difficulty: 'medium' },
  { question: 'Which insect is the strongest relative to its size?', category: 'nature', difficulty: 'hard' },
  { question: 'What is the loudest animal on Earth?', category: 'nature', difficulty: 'hard' },
  { question: 'What is the capital of Portugal?', category: 'travel', difficulty: 'easy' },
  { question: 'Which country has the most UNESCO World Heritage sites?', category: 'travel', difficulty: 'hard' },
  { question: 'What is the capital of Norway?', category: 'travel', difficulty: 'easy' },
  { question: 'In which city is the Parthenon?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of Switzerland?', category: 'travel', difficulty: 'easy' },
  { question: 'Which country is the Great Wall in?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of Ireland?', category: 'travel', difficulty: 'easy' },
  { question: 'In which city would you find Big Ben?', category: 'travel', difficulty: 'easy' },
  { question: 'What is the capital of Austria?', category: 'travel', difficulty: 'easy' },
  { question: 'Which country has the most lakes?', category: 'travel', difficulty: 'hard' },
];
